### ISSUE TITLE
The loading icon is not at the same position as the checkbox it replaces

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7724]
In the _Sharing_ tab of the details view of the _Files_ app when a checkbox is clicked it is replaced by a working/loading icon while the operation is being processed in the server. However, the icon is not placed exactly at the same position as the checkbox it replaces.

In the screenshots below it is subtle, but it can be clearly noticed when clicking on the checkbox, as when the icon is shown the text next to it is moved (in the first case to the left, in the second case to the right).

Share link:
![share-link-checkbox](https://user-images.githubusercontent.com/26858233/34651290-aba1660a-f3ce-11e7-9262-005f8c7a9bf1.png)
![share-link-loading](https://user-images.githubusercontent.com/26858233/34651291-ad8bf160-f3ce-11e7-869e-a387767f1fbe.png)

Allow editing:
![share-link-editing-checkbox](https://user-images.githubusercontent.com/26858233/34651293-afa7f138-f3ce-11e7-8d18-1a0703218906.png)
![share-link-editing-loading](https://user-images.githubusercontent.com/26858233/34651294-b16372cc-f3ce-11e7-9313-0c585a237ac2.png)

I have noticed this in the _Sharing_ tab, although I do not know if this technique of replacing the checkbox with the icon is used anywhere else (although in my opinion it should be, as it shows that the operation is in process while also ensuring that the user will not mess with it by clicking again on the checkbox before it has finished ;-) ).

@nextcloud/designers

**Comment by MorrisJobke** [comment]
It's fine to fix this in 14 and maybe backport to stable13.

**Comment by skjnldsv** [comment]
@MorrisJobke backporting isn't really necessary, this doesn't break the uid nor the ux!

**Comment by soumyanjaleemahapatra** [comment]
Can I take over this issue?

**Comment by skjnldsv** [comment]
@soumyanjaleemahapatra go ahead ! :)

**Comment by AasthaGupta** [comment]
@soumyanjaleemahapatra are you still working on this or can I take this up?

**Comment by skjnldsv** [comment]
If one of you is taking over this ussue, please fix this in a global way. So that every checkbox using the icon-loading-small class has the same design. Do not fix only the sharing sidebar checkboxes :)

**Comment by soumyanjaleemahapatra** [comment]
@AasthaGupta Please take over the issue if you can. Thanks!

**Comment by MorrisJobke** [comment]
Fixed by the migration to the dropdown:

![bildschirmfoto 2018-07-24 um 16 59 21](https://user-images.githubusercontent.com/245432/43147274-f2381ee4-8f62-11e8-968e-ef6569a77e06.png)

#10218
