### ISSUE TITLE
Upgrade to 13.0.0 Beta 4 - Tablespace for table '`nextcloud`.`oc_deck_boards`' exists

### ISSUE THREAD

**Issue by mannp** [nextcloud/server#7725]
Updating from 12.0.4 to 13b4 gives me the following error;

> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_deck_boards` (`id` INT AUTO_INCREMENT NOT NULL, `title` VARCHAR(100) NOT NULL, `owner` VARCHAR(64) NOT NULL, `color` VARCHAR(6) DEFAULT NULL, `archived` TINYINT(1) DEFAULT '0', `deleted_at` BIGINT UNSIGNED DEFAULT 0, PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[HY000]: General error: 1813 Tablespace for table '`nextcloud`.`oc_deck_boards`' exists. Please DISCARD the tablespace before IMPORT.

**Comment by MorrisJobke** [comment]
cc @juliushaertl - looks like a deck problem.

Or is this wrong @nickvergessen?

**Comment by juliushaertl** [comment]
@MorrisJobke I've no idea what might cause deck to create the table again when updating. 

@mannp What version of deck was installed when doing the update?

**Comment by nickvergessen** [comment]
Also please provide the info which database you are running etc.

**Comment by mannp** [comment]
Hi all, I got this running by disabling the deck plugin using occ and going through the upgrade again.

I haven't yet tried to re-enable the deck plugin in v13, but it was the latest version available on v12, that is deck was up to date.

The db is mariadb.

**Comment by MorrisJobke** [comment]
There were several fixes to the deck app in the meantime and we have many running instances with it installed on 13.0.4. Could you check again if this is still a problem for you?

Until then I will close this ticket here. We can reopen if this is still happening.

**Comment by mannp** [comment]
@MorrisJobke It was due to previous beta testing where the app caused an issue with my db.

I have started from scratch and no longer beta test due to these type of issues (the same for e2ee)
