### ISSUE TITLE
Long ical URL truncated in caldav

### ISSUE THREAD

**Issue by hidrarga** [nextcloud/server#7726]
### Steps to reproduce
1. Insert a very long url (more than 256 chars) to the new calendar subscription box. For instance: https://wiki.pirateparty.be/Special:Ask/-5B-5BHas-20event-20type::%2B-5D-5D/-3FHas-20title%3Dtitle/-3FHas-20title%3Dsummary/-3FHas-20date%3Dstart/-3FHas-20date%3Dend/-3FHas-20location%3Dlocation/-3FHas-20url%3Ddescription/-3FHas-20url%3Durl/mainlabel%3D/limit%3D-20100/order%3D-20desc/sort%3D-20Has-20date/offset%3D0/format%3D-20icalendar (**note**: this link is generated by a MediaWiki extension, and it is not possible to make it shorter, unfortunately...)
2. This will fail (see error below)

You can also try with a url shortener, the same behaviour will occur. The short url is actually being replaced by the long url, which is then truncated as before. This happens when the redirection is permanent, but **not** when the redirection is temporary. 

This limit of 256 chars is due to one of these database fields: https://github.com/nextcloud/server/blob/da6c2c9da1721de7aa05b15af1356e3511069980/apps/dav/lib/Migration/Version1004Date20170825134824.php#L298

Would it be possible to increase this limit? Another possibility would be to store in db the short url from url shorteners. Thanks!

### Expected behaviour

It should subscribe to the new calendar.

### Actual behaviour

I got the following error : 
>Severe error in webcal proxy. Please contact administrator for more information.

## Server configuration detail

**Operating system:** Linux 2.6.32-773.26.1.lve1.4.35.el6.x86_64 SMP Tue Sep 26 06:34:34 EDT 2017 x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 5.5.56

**PHP version:** 7.0.23

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Calendar version:** 1.5.7

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by ChristophWurst** [comment]
@georgehrke :ping_pong:
