### ISSUE TITLE
"Access through untrusted domain"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#7732]
When having not properly setup "trusted_domains" we get on nextcloud android app only "unknown error occured".
We are calling "server/status.php" and get 400 back.
Is 400 only returned in this case, so it is safe to check for this? Or is there a more decent way to get this?

Ratio: from time to time home users approach to us and have it misconfigured. So I want to improve this a bit

**Comment by MorrisJobke** [comment]
@nickvergessen @blizzz @rullzer @ChristophWurst Do you have an idea for an API?

**Comment by blizzz** [comment]
>  We are calling "server/status.php" and get 400 back.

Cannot say or promise for sure. 400 is pretty broad.

Would it already suffice to provide a different message to this code? "400 Untrusted Domain"?

**Comment by blizzz** [comment]
if we go for an API it'll be a bit more invasive since the domain is tested early in base.php

**Comment by tobiasKaminsky** [comment]
If possible I do not want to check for the message. But maybe an arbitrary status code is possible?

**Comment by rullzer** [comment]
Well we check early in base php and normally we return a page. We could of cource check for the `Accept` header and if that is json return some static json.

Of course this only works if you properly check status.php first?

**Comment by tobiasKaminsky** [comment]
> Would it already suffice to provide a different message to this code? "400 Untrusted Domain"?

Currently when accessing /status.php we get the complete html website back.
We are parsing the status code, and return our own string, so changing the message on server side would not be sufficient.

If 400 is only used there, I can simply add a "translation" for 400.
But as 400 is so generic, maybe it is better to return a new one, e.g. 455 is not in use (according to https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors)

**Comment by MorrisJobke** [comment]
Or just return a proper status.php XML/JSON with the correct error message: 😉 (using HTTP codes for this is not really good)

**Comment by tobiasKaminsky** [comment]
Well, this can still be accessible via web browser (of course if misconfigured), so a proper NC error web page is still nice for regular web browser user.

**Comment by MorrisJobke** [comment]
> Well, this can still be accessible via web browser (of course if misconfigured), so a proper NC error web page is still nice for regular web browser user.

But not on the `/status.php` URL ;)

**Comment by tobiasKaminsky** [comment]
Indeed 👍

**Comment by MorrisJobke** [comment]
Fix is in #7991
