### ISSUE TITLE
Add the ability to change user password using the api with encryption enabled

### ISSUE THREAD

**Issue by akalevich** [nextcloud/server#7735]
Hello. I want change user password using api with enabled encryption (recovery enabled) and the password does not change. "User" class method setPassword has parameter "recoveryPassword", but API does not use it. Can you upgrade api?

**Comment by MorrisJobke** [comment]
cc @schiessle

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
