### ISSUE TITLE
[ldap] add support for ldapi:// URL

### ISSUE THREAD

**Issue by Jean-Daniel** [nextcloud/server#7737]
### Steps to reproduce
1. Install Nextcloud and a local ldap server.
2. Go to LDAP auth configuration.
3. Try to setup the server to use ldapi:// unix socket instead of ldap://

Actually, the underlying php ldap module properly support ldapi:// URI. The main issue is with the 
user_ldap module forcing to set a port and always append the port to the ldap URI.
 
By relaxing the port requirement, I managed to setup a connection using ldapi:// url.

An other issue is that it look like the code path to check the configuration in the front-end is not the same than the one used when doing ldap:config-test.

When using ldapi:// URI, the front-end refuses to validate or detect the DN and always tell me there is a configuration issue, while running occ ldap:config-test report that connection is OK.

### Expected behaviour
It should be possible to use ldapi URI for LDAP configuration and all LDAP features should work the same than when using ldap protocol.

### Actual behaviour
ldapi can't be configured because the nextcloud code require a port settings and append it to the URI and even without that problem, the configuration panel remain broken.

### Server configuration

**Operating system**:
Ubuntu Xenial

**Web server:**
NGINX

**Database:**
PostgreSQL

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Command line

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

`No errors have been found.`

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
> By relaxing the port requirement, I managed to setup a connection using ldapi:// url.

mind opening a PR? Making port required can be evaluated by checking whether the ldapi:// protocol is specified.

**Comment by SchoolGuy** [comment]
+1 for this!

**Comment by pherman** [comment]
+1 for this from me too!

**Comment by blizzz** [comment]
🛈 pluses won't make this happen. pull requests will.

**Comment by cosmedd** [comment]
Hi!

**ldapi:///run/ldapi** in the front-end works just fine with Nextcloud 15.0.7 under Debian 9.9 and PHP 7.0

**Comment by zenlord** [comment]
I can confirm that the patches in the @nick-dumas fork solve the issue if I use the occ LDAP commands (Debian 10, PHP 7.3, NC 20.2)
The front-end still checks for the missing port number

**Comment by zenlord** [comment]
ping? I proposed a patch several months ago, but the pull request is not being picked up? I can confirm the patches are still working on my updated instance v 21.0.1...
