### ISSUE TITLE
ldap plugin maps admin group to admin_2

### ISSUE THREAD

**Issue by yennor** [nextcloud/server#7743]
### Steps to reproduce
1. create a ldap connection to a ldap server using the ldap / ad plugin
2. in the ldap server, have a group "admin", and an user which is member of it but does not have the user name admin.
3. login with that user.

### Expected behaviour
The user, as member of the group admin, should become admin of the nextcloud instance.

### Actual behaviour
The user is able to login, but he will be member of the group "admin_2" instead of admin. And he does not have admin rights. Only if he has the username "admin" he gains admin rights independent of the group he belongs to.

**Operating system:** Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** pgsql PostgreSQL 9.6.6 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit

**PHP version:** 7.0.19-1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "ocegk1smvagl",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "\/var\/www\/html\/cloud\/data",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "12.0.4.3",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
}
```
</details>

<details><summary>LDAP configuration (delete this part if not used)</summary>
+-------------------------------+------------------------------------------------+
| Configuration                 |                                                |
+-------------------------------+------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                              |
| hasPagedResultSupport         |                                                |
| homeFolderNamingRule          |                                                |
| lastJpegPhotoLookup           | 0                                              |
| ldapAgentName                 |                                                |
| ldapAgentPassword             | ***                                            |
| ldapAttributesForGroupSearch  |                                                |
| ldapAttributesForUserSearch   |                                                |
| ldapBackupHost                |                                                |
| ldapBackupPort                |                                                |
| ldapBase                      | dc=hebamme,dc=ch                               |
| ldapBaseGroups                | ou=Group,dc=hebamme,dc=ch                      |
| ldapBaseUsers                 | ou=People,dc=hebamme,dc=ch                     |
| ldapCacheTTL                  | 600                                            |
| ldapConfigurationActive       | 1                                              |
| ldapDefaultPPolicyDN          |                                                |
| ldapDynamicGroupMemberURL     |                                                |
| ldapEmailAttribute            |                                                |
| ldapExperiencedAdmin          | 0                                              |
| ldapExpertUUIDGroupAttr       |                                                |
| ldapExpertUUIDUserAttr        | uid                                            |
| ldapExpertUsernameAttr        |                                                |
| ldapGidNumber                 | gidNumber                                      |
| ldapGroupDisplayName          | cn                                             |
| ldapGroupFilter               | (&(|(objectclass=groupOfNames)))               |
| ldapGroupFilterGroups         |                                                |
| ldapGroupFilterMode           | 0                                              |
| ldapGroupFilterObjectclass    | groupOfNames                                   |
| ldapGroupMemberAssocAttr      | member                                         |
| ldapHost                      | localhost                                      |
| ldapIgnoreNamingRules         |                                                |
| ldapLoginFilter               | (&(&(|(objectclass=inetOrgPerson)))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                |
| ldapLoginFilterEmail          | 0                                              |
| ldapLoginFilterMode           | 0                                              |
| ldapLoginFilterUsername       | 1                                              |
| ldapNestedGroups              | 0                                              |
| ldapOverrideMainServer        |                                                |
| ldapPagingSize                | 500                                            |
| ldapPort                      | 389                                            |
| ldapQuotaAttribute            |                                                |
| ldapQuotaDefault              |                                                |
| ldapTLS                       | 0                                              |
| ldapUserDisplayName           | cn                                             |
| ldapUserDisplayName2          |                                                |
| ldapUserFilter                | (&(|(objectclass=inetOrgPerson)))              |
| ldapUserFilterGroups          |                                                |
| ldapUserFilterMode            | 0                                              |
| ldapUserFilterObjectclass     | inetOrgPerson                                  |
| ldapUuidGroupAttribute        | auto                                           |
| ldapUuidUserAttribute         | auto                                           |
| turnOffCertCheck              | 0                                              |
| turnOnPasswordChange          | 1                                              |
| useMemberOfToDetectMembership | 1                                              |
+-------------------------------+------------------------------------------------+
</details>

**Comment by MorrisJobke** [comment]
AFAIK this is not supported, because LDAP tries to detect collisions and therefore adds the `_2`. cc @blizzz

**Comment by blizzz** [comment]
what @MorrisJobke  says. Add the users to the local admin group for them to become admins.

**Comment by yennor** [comment]
I can do that as long as it is only for one application.
But if every application would argue like that, one could just throw central user management away and go back to manage them in every application individually...

**Comment by MorrisJobke** [comment]
> But if every application would argue like that, one could just throw central user management away and go back to manage them in every application individually...

The enhancement request for the admin groups is in #6428

**Comment by yennor** [comment]
ups, I'm really sorry. I didn't see that when I was searching the bugs...

**Comment by MorrisJobke** [comment]
> ups, I'm really sorry. I didn't see that when I was searching the bugs...

Don't worry :)
