### ISSUE TITLE
Ability to update user profile picture with OCS API

### ISSUE THREAD

**Issue by dachinat** [nextcloud/server#7744]
Current OCS API supports updating profile (display name, quota, email address, etc.) of any user with single administrator credentials. As I know, updating a profile picture using OCS API is not implemented. It'd be nice to have such feature. Thanks.

**Comment by rullzer** [comment]
It should not be that hard to add this to the provisioning API.

Basically:
1. New endpoint
  * The current edit endpoint is for text not data
  * POST to <server>/ocs/v2.php/cloud/users/<userid>/avatar
2. Endpoint checks
  * Avatar square?
  * Submitted size?
  * Valid format?
3. Store avatar

DELETE on that route is pretty clear as well
GET I would just return the route to obtain the avatar

**Comment by markus2330** [comment]
For https://github.com/nextcloud/talk-android/issues/628 we would need also a possibility that users update their own profile picture. Would that be a different issue?

**Comment by PVince81** [comment]
closing in favor of https://github.com/nextcloud/server/issues/10549 which has slightly more info

also see https://github.com/nextcloud/android/issues/2949
