### ISSUE TITLE
Proper preview endpoints

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#775]
As discussed during the hackweek I want to fix shared previews (https://github.com/nextcloud/server/issues/702) But in doing this I noticed that our preview endpoints are kind of messed up.

Currently we have:
- `/index.php/core/preview.png?...`
- `/index.php/apps/files_sharing/ajax/publicpreview.php?...`
- `/index.php/apps/files//api/v1/thumbnail/{x}/{y}/{file}`

So not a nice collection of routes.

I think in the end the cleanest solution is to have proper webdav endpoints. I propose to make a clear distinction in the endpoints betwee thumbnails and previews. A preview should always keep aspect ratio and never crop the image. While a thumbnail crops te image.

The thumbnail endpoint is easy enough and the current endpoint is a good example.
But for the previews is becomes more messy. Since we want to be able to:
- Set mode (fill/cover)
- Set only width/height (since the other once can be calculated)

Making them webdav endpoints has the big advantage that all clients can also start using them.

For now I'll keep the routes as they are and try to get the new fancy code to run on them.

CC: @oparoz @MorrisJobke @icewind1991

**Comment by oparoz** [comment]
> I propose to make a clear distinction in the endpoints betwee thumbnails and previews. A preview should always keep aspect ratio and never crop the image. While a thumbnail crops te image.

I wonder if this is the best solution. Here is an example of an API which just adds an extra argument to get the cropped version:
https://dev.onedrive.com/items/thumbnails.htm#custom-thumbnail-sizes

Is there an advantage in having 2 different routes to generate previews? Especially if we have extra parameters such as fill and cover. Crop seems to just be another parameter.

**Comment by rullzer** [comment]
Lets close this. Current endpoint seems to be OK. We'll think about this when we have to.
