### ISSUE TITLE
Password problem when setting up nextcloud via web installer

### ISSUE THREAD

**Issue by stfn-jcb** [nextcloud/server#7750]
Hi there,
I tried a web update from nextcloud 12.0.3 to 12.0.4 but then somehow mysterically my config/config.php got removed and I couldn't find any appropriate backup. Out of curiosity, I tried to set up a new instance with an empty config.php file. During the step of setting up the connection to the database, the script somehow seemed to mishandle the two passwords for the newly created nextcloud user and the user for the database, because Firefox proposed to save the credentials for the website with the nextcloud user password as user name (see attached screenshot). I didn't take a look into the internal php scripts so perhaps this isn't a real bug, but I just wanted to let you know.
(Since Github somehow can't handle the file upload at the moment, I uploaded my screenshot here: https://eaa.spdns.org/nc/NC-Password-Problem.png)

**Comment by MorrisJobke** [comment]
We improved the handling of passwords for browsers in 13 (and also in the upcoming 12.0.5 as well). So I would say this will not be an issue anymore in the future. Thanks for the report anyway.

**Comment by stfn-jcb** [comment]
Cool, thanks, looking forward to updating to 12.0.5 and also to upgrading to 13!
