### ISSUE TITLE
Announces inexistent directory, transfer fails

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/server#7751]
### Expected behaviour
Nextcloud should announce the files via webdav which actually exist on the server

### Actual behaviour

The nextcloud server stubbornly anounces a directory /ÖPR via webdav, which does not exist. Consequently, download fails via webdav with clients reporting an  "internal server error".

Tried with three different clients, two nextcloud linux clients, one Nextcloud windows client.

Also tried to fix it with occ files:scan but that did not change a thing.

A directory of the same name actually exists, but it is a sub-sub directory, and it is correctly shown and synched.

### Steps to reproduce
(I have no idea what triggert this, I therefore don't have the slightest idea how it can be reproduced nor how I can get rid of this.
### Server configuration
Operating system: Ubuntu 16.10

Web server:  Nginx 1.12.1

Database: Mariadb 10.1.25

PHP version:  php7.1-fpm 

Nextcloud version: 12.4

Storage backend (external storage):

### Client configuration
Client version: 2.3 and owncloud client 2.4

Operating system: Debian Stretch, WIndows 10, Arch Linux

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): Arch linux from distro, Debian from Nextcloud repo

Installation path of client: /usr

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `Nextcloud --logwindow` or `Nextcloud --logfile log.txt`
01-09 07:57:17:694 0x55e462447a18 _csync_detect_update: remote rename detected based on fileid INFOE/Russland/ÖPR ÖPR
01-09 07:57:17:694 0x55e462447a18 _csync_detect_update: file: ÖPR, instruction: INSTRUCTION_EVAL_RENAME <<=
01-09 07:57:17:694 11815 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x55e46250b0d0) ÖPR Calling into main thread...
01-09 07:57:17:694 11782 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://cloud.rohr.org" + "/ÖPR" "OCC::DiscoverySingleDirectoryJob"
01-09 07:57:17:829 11782 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(InternalServerError) "Error transferring https://cloud.rohr.org/remote.php/dav/files/jr/ÖPR - server replied: Internal Server Error" QVariant(int, 500)
01-09 07:57:17:829 11782 OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot: void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply*) "Error transferring https://cloud.rohr.org/remote.php/dav/files/jr/ÖPR - server replied: Internal Server Error" 500 QNetworkReply::NetworkError(InternalServerError)
01-09 07:57:17:829 11782 OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot: void OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, const QString&) 5 "Error transferring https://cloud.rohr.org/remote.php/dav/files/jr/ÖPR - server replied: Internal Server Error"
01-09 07:57:17:829 11815 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x55e46250b0d0) ÖPR ...Returned from main thread
01-09 07:57:17:829 11815 OCC::DiscoveryJob::remote_vio_opendir_hook: 5 when opening ÖPR msg= "Error transferring https://cloud.rohr.org/remote.php/dav/files/jr/ÖPR - server replied: Internal Server Error"
01-09 07:57:17:829 0x55e462447a18 csync_ftw: opendir failed for ÖPR - errno 5
01-09 07:57:17:829 11815 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t*, void*) OCC::DiscoveryJob(0x55e46250b0d0) ""
01-09 07:57:17:830 0x55e462447a18 csync_statedb_close: sqlite3_close=0
01-09 07:57:17:830 11782 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "Beim Öffnen eines Ordners ist ein Fehler aufgetreten. Error transferring https://cloud.rohr.org/remote.php/dav/files/jr/ÖPR - server replied: Internal Server Error"

2. Web server error log:

owncloud.rohr.org-access.log:  79.199.251.199 - jr [09/Jan/2018:07:37:47 +0100]    "PROPFIND /remote.php/dav/files/jr/%C3%96PR HTTP/1.1" 500 626    "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"    "-"
owncloud.rohr.org-access.log:  79.199.251.199 - jr [09/Jan/2018:07:46:47 +0100]    "PROPFIND /remote.php/webdav/INFOE/Russland/%C3%96PR HTTP/1.1" 207 1078    "-" "gvfs/1.34.2"    "-"
owncloud.rohr.org-access.log:  79.199.251.199 - jr [09/Jan/2018:07:46:47 +0100]    "PROPFIND /remote.php/webdav/INFOE/Russland/%C3%96PR/ HTTP/1.1" 207 2548    "-" "gvfs/1.34.2"    "-"

3. Server logfile: Nextcloud log (data/Nextcloud.log):
,"message":"Error while trying to create shared mount","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"12.0.4.3"}                                                                          
{"reqId":"nGxlPFaMRjyOb8SDs1Zf","level":3,"time":"2018-01-09T06:37:47+00:00","remoteAddr":"79.199.251.199","user":"jr","app":"no app in context","method":"PROPFIND","url":"\/remote.php\/dav\/files\/jr\/%C3%96PR","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"Node for share not found, fileid: 84559\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/lib\\\/private\\\/Share20\\\/DefaultShareProvider.php(446): OC\\\\Share20\\\\Share->getNode()\\n#1 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/lib\\\/private\\\/Share20\\\/Manager.php(1023): OC\\\\Share20\\\\DefaultShareProvider->move(Object(OC\\\\Share20\\\\Share), 'jr')\\n#2 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(120): OC\\\\Share20\\\\Manager->moveShare(Object(OC\\\\Share20\\\\Share), 'jr')\\n#3 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(102): OCA\\\\Files_Sharing\\\\SharedMount->updateFileTarget('\\\/INFOE (2)', Object(OC\\\\Share20\\\\Share))\\n#4 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(73): OCA\\\\Files_Sharing\\\\SharedMount->verifyMountPoint(Object(OC\\\\Share20\\\\Share), Array)\\n#5 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/apps\\\/files_sharing\\\/lib\\\/MountProvider.php(96): OCA\\\\Files_Sharing\\\\SharedMount->__construct('\\\\\\\\OCA\\\\\\\\Files_Shar...', Array, Array, Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#6 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(108): OCA\\\\Files_Sharing\\\\MountProvider->getMountsForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#7 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/lib\\\/private\\\/Files\\\/Filesystem.php(445): OC\\\\Files\\\\Config\\\\MountProviderCollection->addMountForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Mount\\\\Manager))\\n#8 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/lib\\\/private\\\/Files\\\/Filesystem.php(374): OC\\\\Files\\\\Filesystem::initMountPoints('jr')\\n#9 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/lib\\\/private\\\/legacy\\\/util.php(280): OC\\\\Files\\\\Filesystem::init('jr', '\\\/jr\\\/files')\\n#10 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(123): OC_Util::setupFS('jr')\\n#11 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php(105): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->validateUserPass(*** sensitive parameters replaced ***)\\n#12 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(252): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(154): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(201): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(150): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#18 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#19 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#20 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#21 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#22 \\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/remote.php(162): require_once('\\\/var\\\/www\\\/chroot...')\\n#23 {main}\",\"File\":\"\\\/var\\\/www\\\/chrooted\\\/jrweb\\\/htdocs\\\/owncloud.rohr.org\\\/lib\\\/private\\\/Share20\\\/Share.php\",\"Line\":167}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"12.0.4.3"}                                                                   
{"reqId":"nGxlPFaMRjyOb8SDs1Zf","level":3,"time":"2018-01-09T06:37:47+00:00","remoteAddr":"79.199.251.199","user":"jr","app":"no app in context","method":"PROPFIND","url":"\/remote.php\/dav\/files\/jr\/%C3%96PR","message":"Error while trying to create shared mount","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"12.0.4.3"}

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer @nickvergessen @blizzz Have you seen this?

**Comment by rullzer** [comment]
Mmmm it seems it tries to resolve some weird conflict.

What version of Nextcloud are you running @vasyugan?
Did a file/folder with that name ever exist but was it removed?

**Comment by rullzer** [comment]
It seems to originate at https://github.com/nextcloud/server/blob/master/lib/private/Share20/DefaultShareProvider.php#L455

I can provide a patch that should at least make it not fail I think

**Comment by MorrisJobke** [comment]
Fixed by #7763
