### ISSUE TITLE
NextCloud Instance Down

### ISSUE THREAD

**Issue by ibr123** [nextcloud/server#7752]
Hi,

i have installed NextCloud version 12 server on a linux server of my own, following  the [link](https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html) and it was working fine but now i'm having this error
![serverdown](https://user-images.githubusercontent.com/26926171/34711067-8aad54dc-f526-11e7-831e-025db9d83ebe.png)
the server that i have installed NextCloud on it is working, and  the question is, since the NextCloud server is installed  on my server,  how is it closed for maintenance ? meaning is it still requesting or linked to a different location ? and is the only this instance down (my instance) or is the same for all ?
Thanks

**Comment by BernhardPosselt** [comment]
Check your logs and check https://docs.nextcloud.com/server/12/admin_manual/maintenance/backup.html#maintenance-mode

**Comment by MorrisJobke** [comment]
you need to disable the maintenance mode, because it kept active after the upgrade (usually it resets it to off, but in case of an issue or warning it does not).

After this the instance should be available again.

**Comment by ibr123** [comment]
yeah i already changed maintenance to false, but when i do the following, the problem reappear 
1- i already have an app on NextCloud server and working fine
2- want to modify the app, i i modify the code then change the `<version>0.0.1</version>` at `info.xml` for the same app
3- copy the app to `nextcloud/extra-apps/`
4- the server isn't responding
**to solve it:**
1- delete the app
2- set maintenance to true at config.php
3- the message "this nextcloud instance is currently in maintenance ......"
4- set maintenance to false again, then the server is working

of course that solved the issue, yet that means i can't modify the app already on the server, does it have anything to do with the app version, it was working fine (modifying the app) until i reached  `<version>0.0.17</version>` any idea?
NOTE: if i created a new app with a new name, the NextCloud server accepts it
Thanks

**Comment by MorrisJobke** [comment]
> it was working fine (modifying the app) until i reached <version>0.0.17</version> any idea?

Downgrade (from 0.0.17 to 0.0.1) of apps is not supported. I guess that this is the reason of the failure.

**Comment by ibr123** [comment]
actually what happened i didn't do downgrade, my app **"AppOne"** the version started as `0.0.1` and i kept modifying and then increasing the version until i reached `0.0.17` or `0.0.16` then the problem started to show.
what i did, i created another app **"AppTwo"** with version `0.0.1` and then changed the version to `0.0.2` and copied it again to server, and the previous issue didn't appear, seems there is a certain limit for the first digit at the version

**Comment by MorrisJobke** [comment]
> what i did, i created another app "AppTwo" with version 0.0.1 and then changed the version to 0.0.2 and copied it again to server, and the previous issue didn't appear, seems there is a certain limit for the first digit at the version

Mmmmh ... usually not and nothing that I'm aware of :/ Could you check with the second app to also go through all of this until 0.0.17 and verify it is that?

**Comment by ibr123** [comment]
it happened again today but i didn't went above version 0.0.17, it did't even pass 10,  i'm sure it has to do with  app version, maybe if any consistency in versions happened this issue appears 
still, i'm not sure what scenario makes it

**Comment by MorrisJobke** [comment]
> it happened again today but i didn't went above version 0.0.17, it did't even pass 10, i'm sure it has to do with app version, maybe if any consistency in versions happened this issue appears
> still, i'm not sure what scenario makes it

I'm pretty sure it's unrelated to the version number, but to a different change. Maybe turn on debug mode and set the log level to debug as well.

**Comment by ibr123** [comment]
actually i disabled debugging app for now, what makes think it has to do with the app version, is that when i have the same problem i create a different app, copy the code to it, and works normally again, and i also can increase the version number in the newly created app
