### ISSUE TITLE
NC12 - User Management API - Admin password timeout for POST requests

### ISSUE THREAD

**Issue by efontain** [nextcloud/server#7753]
Hello, i have the same issue than this "closed" issue : https://github.com/nextcloud/server/issues/6476.

Was there a solution to this problem ? I can't find it in the post. And all post i found why the same issue have still no response.

**Comment by rullzer** [comment]
So this curl command fails for you??:

```
curl -u <user>:<pass> <server>/ocs/v2.php/cloud/users -H 'ocs-apirequest: true' -X POST -d "userid=foo&password=bar"
```

Obviously replace <user>, <pass> and <server>

**Comment by efontain** [comment]
Hello this doesn't work, saying "Current user is not logged in".
And with postman i now get "Password confirmation is required" after using it for 30 minutes

**Comment by rullzer** [comment]
That is very weird. I tries this on 3 different systems and it works every time...

Can you post your config.php, and your apache/nginx config?

**Comment by efontain** [comment]
Well it works, but try it after 30 min with the same user and system ! I think it won't work anymore

**Comment by rullzer** [comment]
It should with curl.

Be sure to not store and send cookies! We parse cookies first. So if you send cookies the timeout might happen after 30 minutes.

**Comment by efontain** [comment]
Oh god thats it ! Looks like Postman store/send cookies automatically..

Thanks ! :)

**Comment by donquixote** [comment]
> Be sure to not store and send cookies! We parse cookies first. So if you send cookies the timeout might happen after 30 minutes.

As in [my comment in the other issue](https://github.com/nextcloud/server/issues/6476#issuecomment-1481977293):
- basic auth is much slower than cookie auth.
- token auth is a bit slower than cookie auth, and it does not protect you from the "Password confirmation is required" for routes annotated with `@PasswordConfirmationRequired`, e.g. `/ocs/v1.php/cloud/users/{userId}/enable`.

So cookie auth is still the best bet.
