### ISSUE TITLE
Settings section missing as their classes cannot be resolved by the DI container

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#7755]
### Steps to reproduce
1. Update to nc13 beta4
2. Install news or one of 2fa apps (totp, u2f)
3. Find no settings in your personal security section

### Expected behaviour
See app's settings section.

### Actual behaviour
Section not shown. Does not exist in DB.

Originally reported as https://github.com/nextcloud/twofactor_u2f/issues/83 by @schiessle. Since it's apparently happening for three installed apps, I'm assuming this is a bug in the server components rather than the apps.

```
"Could not resolve OCA\\\\News\\\\Settings\\\\Section! Class OCA\\\\News\\\\Settings\\\\Section does not exist\"
"Could not resolve OCA\\\\TwoFactorTOTP\\\\Settings\\\\Personal! Class OCA\\\\TwoFactorTOTP\\\\Settings\\\\Personal does not exist\"
"Could not resolve OCA\\\\News\\\\Settings\\\\Section! Class OCA\\\\News\\\\Settings\\\\Section does not exist\"
"Could not resolve OCA\\\\TwoFactorTOTP\\\\Settings\\\\Personal! Class OCA\\\\TwoFactorTOTP\\\\Settings\\\\Personal does not exist\"
```

Sentry report and stack trace https://sentry.io/share/issue/286d96e539844c288c05d069e097331e/

Database entries

```
> select * from oc_personal_settings;
+----+--------------------------------------------+----------+----------+
| id | class                                      | section  | priority |
+----+--------------------------------------------+----------+----------+
|  1 | OCA\FederatedFileSharing\Settings\Personal | sharing  |       40 |
|  2 | OCA\TwoFactorBackupCodes\Settings\Personal | security |       40 |
+----+--------------------------------------------+----------+----------+
2 rows in set (0.01 sec)
```

cc @blizzz

**Comment by blizzz** [comment]
Hm, I have news installed and settings are working.

**Comment by ChristophWurst** [comment]
My production instance is on php5.6, if that makes a difference.

**Comment by ChristophWurst** [comment]
There are also no custom classes/interfaces that need to be resolved (which was my first guess for the DI failure): https://github.com/nextcloud/twofactor_totp/blob/master/lib/Settings/Personal.php

**Comment by blizzz** [comment]
not sure, but it is a difference. I am on 7.0 in production. Strange thing.

@schiessle are you also on 5.6?

**Comment by blizzz** [comment]
well, we should catch, log and forget it otherwise

**Comment by blizzz** [comment]
@ChristophWurst  do you have a Backtrace?

**Comment by ChristophWurst** [comment]
> @schiessle are you also on 5.6?

It's c.nc.com.

> @ChristophWurst do you have a Backtrace?

https://sentry.io/share/issue/286d96e539844c288c05d069e097331e/

**Comment by rullzer** [comment]
Lets see if I can reproduce this on a clean install...

**Comment by rullzer** [comment]
Boom got it on my dev instance... lets see :)

**Comment by rullzer** [comment]
@ChristophWurst can you verify that the app is enabled?

**Comment by ChristophWurst** [comment]
Ha! Yes, it is! HOWEVER, since I'm on php5.6, they all got disabled during the upgrade. I've manually re-enabled them afterwards.

**Comment by rullzer** [comment]
mmm still strange... if you disable and enable the app does it work then?

**Comment by rullzer** [comment]
I have the feeling we don't cleanup properly sometimes

**Comment by ChristophWurst** [comment]
Disabled and re-enabled the 2FA apps and settings are back.

**Comment by ChristophWurst** [comment]
DB got successfully populated

```
> select * from oc_personal_settings;
+----+--------------------------------------------+----------+----------+
| id | class                                      | section  | priority |
+----+--------------------------------------------+----------+----------+
|  1 | OCA\FederatedFileSharing\Settings\Personal | sharing  |       40 |
|  2 | OCA\TwoFactorBackupCodes\Settings\Personal | security |       40 |
|  4 | OCA\TwoFactorTOTP\Settings\Personal        | security |       40 |
|  5 | OCA\TwoFactorU2F\Settings\Personal         | security |       40 |
+----+--------------------------------------------+----------+----------+
4 rows in set (0.00 sec)
```

Now, can we prevent this from happening on other instances? Could you figure out when that happens?

**Comment by rullzer** [comment]
My bet is that the app doesn't get disabled gracefully... so there is some leftover or something... I guess the best is to catch the query exception in the settings so we just don't show this huge stacktrace when a class can't be found

**Comment by ChristophWurst** [comment]
> I guess the best is to catch the query exception in the settings so we just don't show this huge stacktrace when a class can't be found

Well, actually that never pops up. The settings are simply missing some sections. The only notice of an error is in the error log (or Sentry, if used). Hence it might even affect other users, but they have not noticed yet 🙁

**Comment by rullzer** [comment]
Mmmm I can't trigger it anymore (I believe with my last clean install I also updated the totp app).

Anyway... the root cause here is https://github.com/nextcloud/server/blob/master/lib/private/Settings/Manager.php#L347

So we already just ignored the non instantiatable session. But log there...

**Comment by ChristophWurst** [comment]
I don't really know the code in question, but I'm wondering why we're not failing hard if that occurs: https://github.com/nextcloud/server/blob/9386b07ed8c469189779949debb4483e713e3836/lib/private/Settings/Manager.php#L455

We do log it, yes. But then just carry on as if that's fine. @blizzz are there any cases where it fails and we ca n safely ignore it?

**Comment by rullzer** [comment]
yes:

* when a user just removes an app folder for example.
* Or when you update an app and a section is removed from the info.xml Then we have no way to find out which sections are missing etc.

**Comment by rullzer** [comment]
PR to log as INFO in #7766

**Comment by rullzer** [comment]
@ChristophWurst I think/hope this was a 1 time issue with upgrade of server and update of the apps and something not going quite ok. I have not been able to trigger it since.

If you can please reopen.

**Comment by blizzz** [comment]
For 14? we already thought of removing this from the DB and react on the info.xml only. Wouldn't necessarily be safe from broken DI magic spells whatsoever, but would avoid messy DBs and the tango around it.

**Comment by schiessle** [comment]
I have the same issue now on my instance... updated to Nextcloud 13 and the settings for u2f are gone

**Comment by MorrisJobke** [comment]
Fixed in 14. It is not cached in the DB anymore.
