### ISSUE TITLE
Last modified timestamp after cronjob/filescan

### ISSUE THREAD

**Issue by loeffelpan** [nextcloud/server#7761]
### Steps to reproduce
1. Delete External Storages
2. Reconfigure External Storages (Local)
3. Wait until the next cronjob has been executed

### Expected behaviour
Cronjon (or file-scan or whatever is happening to caluclate the sizes of files and folders) should prevent the last-modified-date.

### Actual behaviour
Every Folder seems to be modified at first execution of cronjob. Second and further execution doesn't change the last-modified-date.

### Server configuration

**Operating system**: Ubuntu Server 17.10

**Web server:** Apache 2.4.27

**Database:** MySQL

**PHP version:** PHP 7.1.11-0ubuntu0.17.10.1

**Nextcloud version:** 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud.com

**List of activated apps:**
<details><summary>App list</summary>
Enabled:
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_sharing: 1.4.0
  - files_videoplayer: 1.1.0
  - lookup_server_connector: 1.0.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - provisioning_api: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_pdfviewer
  - files_texteditor
  - files_trashbin
  - files_versions
  - firstrunwizard
  - gallery
  - logreader
  - nextcloud_announcements
  - password_policy
  - serverinfo
  - sharebymail
  - survey_client
  - systemtags
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "oc65jgv8zf6o",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "toothless.goip.de",
            "toothless.fritz.box"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/toothless.goip.de",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "skeletondirectory": "",
        "logtimezone": "Europe\/Berlin",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": "6379"
        },
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "jan.noormann",
        "mail_domain": "gmail.com",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls"
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera, Chrome, Firefox

**Operating system:** Windows 10

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.
