### ISSUE TITLE
Link in e-mail to a shared folder does not work in Internet Explorer 11

### ISSUE THREAD

**Issue by HenselIT** [nextcloud/server#7775]
When sharing a folder with an active directory user this user will recieve an e-mail with a link to the shared folder. If the user opens the Link in Internet Explorer 11 and is not logged in the user does not get redirect to the login page. Instead Internet Explorer tries to download a file.

### Steps to reproduce
1. Log in to nextcloud
2. Create a new folder
3. Share this folder with an active directory user
4. User recieves an email with a link to the shared folder
5. Open this link in Internet Explorer
6. User is not logged in. Instead of redirecting the user to the login page Internet Explorer tries to download a file.

### Expected behaviour
User should be redirect to the login page. After authentication user should see the shared folder like in Firefox, Chrome, ...

### Actual behaviour
User not redirected to the login page. Internet Explorer tries to download a file.

### Server configuration

**Operating system**: Ubuntu Server 16.04.3 LTS

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.20

**PHP version:** PHP 7.0.22

**Nextcloud version:** (see Nextcloud admin page) 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

  - activity: 2.5.2
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_automatedtagging: 1.2.2
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "oce01v6ybwls",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mycompany.de"
        ],
        "datadirectory": "\/mnt\/nextclouddata",
        "overwrite.cli.url": "https:\/\/cloud.mycompany.de",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "proxy": "http:\/\/192.168.1.19:8080",
        "skeletondirectory": "\/var\/www\/html\/nextcloud\/core\/hensel",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "production",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "cloud",
        "mail_domain": "mycompany.de",
        "mail_smtphost": "192.168.1.235",
        "mail_smtpport": "25",
        "mail_smtpauth": 1
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                  |
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                |
| hasPagedResultSupport         |                                                                                                                                                  |
| homeFolderNamingRule          | attr:sAMAccountName                                                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                                                                                |
| ldapAgentName                 | CN=Empagent\, Empirum,OU=IT,OU=Benutzer,OU=HKG,OU=mycompany,DC=mycompany,DC=de                                                                       |
| ldapAgentPassword             | ***                                                                                                                                              |
| ldapAttributesForGroupSearch  |                                                                                                                                                  |
| ldapAttributesForUserSearch   |                                                                                                                                                  |
| ldapBackupHost                |                                                                                                                                                  |
| ldapBackupPort                |                                                                                                                                                  |
| ldapBase                      | DC=mycompany,DC=de                                                                                                                                |
| ldapBaseGroups                | DC=mycompany,DC=de                                                                                                                                |
| ldapBaseUsers                 | DC=mycompany,DC=de                                                                                                                                |
| ldapCacheTTL                  | 600                                                                                                                                              |
| ldapConfigurationActive       | 1                                                                                                                                                |
| ldapDefaultPPolicyDN          |                                                                                                                                                  |
| ldapDynamicGroupMemberURL     |                                                                                                                                                  |
| ldapEmailAttribute            | mail                                                                                                                                             |
| ldapExperiencedAdmin          | 0                                                                                                                                                |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                  |
| ldapExpertUUIDUserAttr        |                                                                                                                                                  |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                                   |
| ldapGidNumber                 | gidNumber                                                                                                                                        |
| ldapGroupDisplayName          | cn                                                                                                                                               |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=G_MuK)))                                                                                                           |
| ldapGroupFilterGroups         | G_MuK                                                                                                                                            |
| ldapGroupFilterMode           | 0                                                                                                                                                |
| ldapGroupFilterObjectclass    | group                                                                                                                                            |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                                     |
| ldapHost                      | 192.168.1.186                                                                                                                                    |
| ldapIgnoreNamingRules         |                                                                                                                                                  |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(|(memberof=CN=owncloud,OU=Gruppen,OU=HKG,OU=mycompany,DC=mycompany,DC=de)(primaryGroupID=10334))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                                  |
| ldapLoginFilterEmail          | 0                                                                                                                                                |
| ldapLoginFilterMode           | 0                                                                                                                                                |
| ldapLoginFilterUsername       | 1                                                                                                                                                |
| ldapNestedGroups              | 0                                                                                                                                                |
| ldapOverrideMainServer        |                                                                                                                                                  |
| ldapPagingSize                | 500                                                                                                                                              |
| ldapPort                      | 389                                                                                                                                              |
| ldapQuotaAttribute            |                                                                                                                                                  |
| ldapQuotaDefault              |                                                                                                                                                  |
| ldapTLS                       | 0                                                                                                                                                |
| ldapUserDisplayName           | sAMAccountName                                                                                                                                   |
| ldapUserDisplayName2          |                                                                                                                                                  |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof=CN=owncloud,OU=Gruppen,OU=HKG,OU=mycompany,DC=mycompany,DC=de)(primaryGroupID=10334))))                         |
| ldapUserFilterGroups          | owncloud                                                                                                                                         |
| ldapUserFilterMode            | 0                                                                                                                                                |
| ldapUserFilterObjectclass     | user                                                                                                                                             |
| ldapUuidGroupAttribute        | auto                                                                                                                                             |
| ldapUuidUserAttribute         | auto                                                                                                                                             |
| turnOffCertCheck              | 0                                                                                                                                                |
| turnOnPasswordChange          | 0                                                                                                                                                |
| useMemberOfToDetectMembership | 1                                                                                                                                                |
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+

</details>

### Client configuration
**Browser:** Internet Explorer 11.125.16299.0

**Operating system:** Windows 10 Enterprise LTSB

**Comment by helmut72** [comment]
We have exactly the same problem. If the user is logged in, it will will work.

**Comment by helmut72** [comment]
Problem is fixed at least for us. After some investigations, companies Internet Explorer use *.domain.com in Security -> Intranet Sites for different other services.

Adding our Nextcloud domain name as an exception in Security -> Trusted Sites fixes our problem with IE and Nextcloud.

**Comment by ChristophWurst** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen.
