### ISSUE TITLE
Don't use zip64 for less than 4GB of data

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#7782]
I guess the 99.9% use case would not download more that 4GB of files. Since we use the streamer often when we already know which files we'll add it makes sense to just count the size and if this is less that 3.9GB (just to be save) do not use zip64.

This way we could also serve zip files to OSX then. So when people download a small zip files they can open it on most platforms and share it etc.

As discussed @MorrisJobke

**Comment by jancborchardt** [comment]
@rullzer to be a good first issue, this needs a bit more info on where to start, how to tackle it. :) Good first issues have almost all info provided so newcomers can easily dive in.
