### ISSUE TITLE
Infinite Credentials prompt when adding webdav as network share 

### ISSUE THREAD

**Issue by ali3seven** [nextcloud/server#7784]
Fist of all sorry for couldn't have enough time for filling all the pre-defined  fields. Actually Too many parameters was placed in the template that sounds some wonderful. 
The problem is about showing infinite credential prompt for user account while want to use nextcloud webdav and map drive.  I'm using Windows 8.1 and Nextcloud 12 was installed with  the latest version of mailinabox as bundle. I can use web ui for putting files at threre but can not mount as map drive using webdav. Also I tried different user format like: user@domain.com, user but no one successful. Could you tell me please how can I input this in the username field if there is a correct format defined. I also found some alike issue in the forum too that didn't resolve unfortunately. Then I send this. Thanks in advance. 

https://help.nextcloud.com/t/webdav-doesnt-work-in-nextcloud-11/6838/35

**Comment by tflidd** [comment]
I can't give you a real hint for your problem. However, we have seen a couple of problems with the native Windows implementation of webdav, especially when opening documents in Word you need to enter the credentials again. There were some hints to improve the situation but to my knowledge there is no confirmed setting that works for everybody.

What you can do is to use the litmus test to check your webdav server if the webdav protocol was properly implemented: https://forum.owncloud.org/viewtopic.php?t=21185
Or you can try the Window webdav connection with other webdav servers if there is the same problem. You need some more pointers for the developers, it could as well be a problem of the webdav implementation from Microsoft. Other commercial solutions seem to work with Nextcloud: Netdrive, Webdrive, ...

**Comment by MorrisJobke** [comment]
With 13.0.3 a lot of improvements for using the native Windows implementation are included. Please try the upcoming release.

Thanks
