### ISSUE TITLE
Nextcloud 12 a 13 not compatible with DigitalOcean Spaces

### ISSUE THREAD

**Issue by nebulacrypt** [nextcloud/server#7789]
### Steps to reproduce
1. Create new Digital Ocean Spaces, In the docs says "its compatible with Amazon S3 External Driver Addon
2. Activate the External Drives Addon and fill the data. Reference Image [https://i.imgur.com/QNKXfgR.png](https://i.imgur.com/QNKXfgR.png)
3. It's to be ok the connection. But is not.
4. You click in the folder and upload a new file. Reference Image :  [https://i.imgur.com/7tqXMdr.png](https://i.imgur.com/7tqXMdr.png)
5. Refresh the page... and, Its Gone!. Reference Image : [https://i.imgur.com/1IM0r10.png](https://i.imgur.com/1IM0r10.png)
6. Login in digitalocean, and view your spaces. And.... Surprise! The file exists... Reference Image : [https://i.imgur.com/kJZ9TWO.png](https://i.imgur.com/kJZ9TWO.png)
### Server configuration

Ubuntu 16.04 Minimal

Apache 

Mariadb 10

php 7.1

13.0.0 Beta 4

**List of activated apps:**
<details>
<summary>App list</summary>

**Enabled:**
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_frommail: 0.1.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.7
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0

**Disabled:**
  - encryption
  - firstrunwizard
  - lsd
  - nextcloud_announcements
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'installed' => true,
  'instanceid' => 'ocxvp8m93ek0',
  'passwordsalt' => '*********************',
  'secret' => '******************',
  'trusted_domains' => 
  array (
    0 => '*************',
  ),
  'datadirectory' => '/var/www/data',
  'overwrite.cli.url' => '***********',
  'dbtype' => 'mysql',
  'version' => '13.0.0.9',
  'dbname' => '*********',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '*****************',
  'dbpassword' => '**********',
  'integrity.check.disabled' => true,
  'maintenance' => false,
  'updater.release.channel' => 'daily',
  'updater.secret' => '********',
  'theme' => '',
  'loglevel' => 2,
);
```

</details>

**Are you using external storage:** Digital Ocean Spaces , With Amazon s3 Config.
Reference Doc : [https://www.digitalocean.com/community/questions/is-it-possible-to-mount-do-spaces-as-external-storage-in-nextcloud-as-i-mount-aws-s3-storage](https://www.digitalocean.com/community/questions/is-it-possible-to-mount-do-spaces-as-external-storage-in-nextcloud-as-i-mount-aws-s3-storage)

**Are you using encryption:** no

**Are you using an external user-backend** no

### Client configuration
**Browser:** Versión 63.0.3239.132 (Build oficial) (64 bits)

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
Image Logs : https://i.imgur.com/NjHIfmr.png
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```

Too long to upload here, download at : https://cloud.macosfera.com/index.php/s/8szKRYWJkfXHg6F

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
There's no log errors in console.
</details>

**Comment by MorrisJobke** [comment]
Please fill out the issue template: https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md

Because as of now it's pure guessing what system you use and what configuration is in place.

**Comment by lordsynapsis** [comment]
@MorrisJobke  Hi, i have update now the topic.
Sorry for my bad english

**Comment by nebulacrypt** [comment]
@mo

**Comment by nebulacrypt** [comment]
Nothing?

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by dnwk** [comment]
I am using DigitalOcean's space as S3 Primary storage with my NextCloud 13.0.0. I have issues but useable.

**Comment by wayneoutthere** [comment]
i'm having a big problem making this work. I was using NC 12 yesterday and it immediately connected but now with 13 I can't make the 'spaces' at Digital ocean connect as external storage. It says "smbclient" is not installed. Mounting of "SMB / CIFS", "SMB / CIFS using OC login" is not possible. Please ask your system administrator to install it.  

I'm using shared hosting but ... like I say, yesterday it was no problem at all and i'm following this tutorial just like I did yesterday:

https://www.digitalocean.com/community/questions/is-it-possible-to-mount-do-spaces-as-external-storage-in-nextcloud-as-i-mount-aws-s3-storage

**Comment by wayneoutthere** [comment]
update!  my apologies it seems like Digital Ocean was 'down' when i was trying to connect and the problem was Digital ocean server, not NC.  Please disregard my post above but hopefully this post will help someone troubleshoot in future

**Comment by nebulacrypt** [comment]
It is incredible that in two months they did not even pronounce themselves.
The error continues, in Amazon s3 and DigitalOcean Spaces.
If a user, requires the patch, I will give it privately, since this community has not contributed, or even pronounced something about it.

Regards.

**Comment by r4co0n** [comment]
@nebulacrypt, as you stated, this is not fixed. Would you mind leaving this bug open?

I had some luck with using [s3ql](https://bitbucket.org/nikratio/s3ql/), which is also available in Debian repos. Then use external storage via folder. If you plan on letting your users add external storages, that's not an option, though. I will tidy up my notes and provide them via gist here later - It's mainly a systemd unit managing the s3ql Spaces mount point. Performance and reliability are much better than with the External Storage plugin, I can't say more yet - I only solved this today.

If you could share your patch here, that would be really nice. And the community has contributed the original plugin that you fixed, don't forget that. ;)

**Comment by douglasroos** [comment]
@r4co0n can you share how did you managed to get s3ql fully working with DO spaces? I have managed to connect the filesystem but it shows no files, created a folder from the DO dashboard and not appearing in the mounted filesystem on the server, also the nextcloud says I can't create any file or folder inside that filesystem

**Comment by frbaroni** [comment]
I got a NextCloud working using a s3ql mounted folder to save it's data. The performance is much better than s3fs, but not as close as RioFS (which unfortunately won't support NextCloud, as no renames are possible).


Here's how I built the s3ql mounted folder:
```bash
mkfs.s3ql --plain --cachedir /var/cache/s3ql s3c://nyc3.digitaloceanspaces.com:443/{{YOUR_SPACES_NAME_GOES_HERE}}/s3ql_spaces
mount.s3ql --cachedir /var/cache/s3ql s3c://{{YOUR_SPACES_NAME_GOES_HERE}}.nyc3.digitaloceanspaces.com:443/{{YOUR_SPACES_NAME_GOES_HERE}}/s3ql_spaces /media/spaces-s3/
```
Note: I use nyc3 spaces region.

Then I installed Nextcloud and did the following changes so that it used the /media/spaces-s3 mounted s3ql founder:
```bash
snap install nextcloud
snap connect nextcloud:removable-media # so we can access /media, where s3ql is mounted
vim /var/snap/nextcloud/current/nextcloud/config/config.php
  # change
  # -     'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',
  # to
  # +     'datadirectory' => '/media/spaces-s3/nextcloud',
nextcloud.manual-install <username> <password>
nextcloud.enable-https lets-encrypt
snap run nextcloud.occ config:system:get trusted_domains
nextcloud.occ config:system:set trusted_domains 1 --value={{YOUR_DOMAIN}}
snap run nextcloud.occ config:system:get trusted_domains
cp -R /var/snap/nextcloud/common/nextcloud/data/* /media/spaces-s3/nextcloud/
snap restart nextcloud
```

**Comment by douglasroos** [comment]
@frbaroni after doing this the server gives me 500 internal error, in the log it says FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /media/s3ql/nextcloud.log in /var/www/drive.turiguia.net/html/lib/private/Log/File.php on line 136

**Comment by frbaroni** [comment]
@douglasroos, you're trying to use the mount point as the data folder, but it doesn't work that way. The mount point have different permissions than the ones required by NextCloud.

This is why I advised using something like this: `/media/spaces-s3/nextcloud` where `/media/spaces-s3` is my mount point, and `nextcloud/` is a inside the s3ql file system. Only this way you can have the required permissions in the data root folder.

Move your files from /media/s3ql/ to something like /media/s3ql/nextcloud_data/nextcloud.log and it should work. Also, obviously, change config.php to point to the new data folder.

**Comment by douglasroos** [comment]
@fbaroni thanks! I got it working with your help, many thanks !!

**Comment by VincentChalnot** [comment]
For those stumbling on this issue, I needed to change the group php-fpm was running on in order for this to work.
This configuration doesn't work:
 - php-fpm executed as deploy:**www-data**
 - S3ql volume mounted with user deploy
But this one does:
 - php-fpm executed as deploy:deploy
 - S3ql volume mounted with user deploy
 
This seems really strange to me...

**Comment by squareclouds** [comment]
im still having the issue with nextcloud 17, has this been fixed? files are uploaded and folders created, but they dont get listed in NC, only in DO, theres nothing showing
