### ISSUE TITLE
Logs filling up with UniqueConstraintViolationException whilst inserting into oc_file_locks

### ISSUE THREAD

**Issue by j4m35** [nextcloud/server#7795]
### The Issue
I keep getting a (Level 4) error, caused by a UniqueConstraintViolationException whilst inserting into oc_file_locks from 1 particular user. This error keeps filling up the logs continuously whilst he is syncing. See attached screenshot:
![image](https://user-images.githubusercontent.com/6158416/34829191-d7632b30-f71a-11e7-933d-4821e68dcd52.png)

This error is not exhibited by other users. Other troubleshooting steps I've taken is to delete that user from the server, remove all his files, recreate a new account, and start the sync again from the same machine.

One thing I've noticed is that this user is operating from location that has a multi-homed network, and as such the errors thrown are from 3 unique remoteAddr and are very closely spaced together time wise. See screenshot below:
![image](https://user-images.githubusercontent.com/6158416/34829140-aac6cbc2-f71a-11e7-9c6d-8e171201c4a5.png)

I am at a loss and do not know how to resolve this. Could it be possible it is a race condition from the same lock request occurring from the same user id but different remoteAddr?

A section of the log is attached:
[nextcloud.log](https://github.com/nextcloud/server/files/1622884/nextcloud.log)

### Server configuration

**Operating system:** Gentoo Linux, Kernel 4.14.13

**Web server:** Apache 2.6.4

**Database:** PostgreSQL 9.6.6

**PHP version:** 7.1.13

**Nextcloud version:** 12.0.4

**Comment by MorrisJobke** [comment]
Could you try to migrate the locking to a redis key-value-store that often resolves such issues and it is also the better suited tool for such transactions.

**Comment by j4m35** [comment]
I originally started with Redis for memcache.local and memcache.locking with the following in my config.php file:
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),

But the logs ended up being filled with "hmac sha1" error after a UniqueConstraintViolationException was thrown one line above. To try and debug, I removed Redis; which resulted in what's listed in the first post.

I'm going to try only locking via Redis with just the following in the config.php file:
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),

Will report back when I know more.

**Comment by j4m35** [comment]
@MorrisJobke 

I've been running with locking via Redis without memcache.local (i.e. with just the following in the config.php file) for about 1 week and everything seems stable:
'memcache.locking' => '\OC\Memcache\Redis',
'redis' =>
array (
'host' => 'localhost',
'port' => 6379,
),

As such, I will close this issue. I'll let it run for a while more before I add APCu to memcache.local, to see if I encounter the "hmac sha1" error; if I do I will then open another issue altogether. Thanks for the help.
