### ISSUE TITLE
Nextcloud Talk APP NOT Working

### ISSUE THREAD

**Issue by andyxh** [nextcloud/server#7801]
Hello so the nextcloud talk app on my server doesn't work correct.  I tried doing a call and I can see my self but everything else is black and I cant hear anyone or see them. I'm using nextcloud 13 beta RC1. I tired different browsers and I tried ios and android app and still no luck. I don't see any error in the event log

**Comment by jookk** [comment]
I have the same situation on my nc13rc1.

**Comment by rullzer** [comment]
Please report in https://github.com/nextcloud/spreed
