### ISSUE TITLE
Single codebase for multiple vhosts

### ISSUE THREAD

**Issue by markc** [nextcloud/server#7802]
This is a feature request reposted from the forums for higher visibility...

https://help.nextcloud.com/t/single-codebase-for-multiple-vhosts/413

**muppeth** I think this is awesome idea and something I've been waiting to happen for long time.
Sorta Wordpress Multisite solution for Nextcloud is a must.

**jyaworski** I would have a use for multi-tenancy. Are you talking about each vhost being segregated from the other, or multiple vhosts sharing the same Nextcloud? I'm assuming the former.

**markc** If I understand what you mean, no, not like Wordpress's idea of multihosting where the "sites" are virtual all using the same database. I mean simply a single copy of the Nextcloud codebase installed anywhere on the server and each vhost instance has it's own webroot and files/ area with an individual database per site. I tried using symlinks for generic files and folders and made a real copy of the other folders needed per site (this was 2 months ago now so I have forgotten exactly which files and folders were symlinks and which were real copies) and the only problem with this simplistic approach was that some of the core PHP files user $cwd = dirname(dirname(__FILE__) which became relative to the symlinked destination rather than where the symlink was created in each vhost area. I think I searched for less than a dozen places where the code could be changed to using, say, $cwd = $_SERVER['DOCUMENT_ROOT'] instead and then everything could then work relative to the current web docroot and not prevent the current mode of operation from also working.

Wordpress itself could also do this as long as it's ABSPATH const was dynamically assigned in 3 or 4 places!

It would be amazing to do a git pull in one codebase per server and be able to keep any number of vhost sites uptodate.

**Comment by rullzer** [comment]
There is the enviroment variable `NEXTCLOUD_CONFIG_DIR` if you can set that per vhost you can have a differnt config (and this also set a different datadir) per vhost.

**Comment by markc** [comment]
@rullzer thanks for the tip. Too easy, assuming it works as I kind of outlined above (the end result, not my kludgy methodology). Next issue is documentation for this setting. I'll keep googling but this is all I've found so far...

https://github.com/nextcloud/server/issues/300

Time to set up a dev server and start testing to see just how `NEXTCLOUD_CONFIG_DIR` might work from `nginx`. I could post a link to a howto gist if I have any success.

**Comment by rullzer** [comment]
Well it is not really documented because this is not recommended or supported really ;)

**Comment by punkyard** [comment]
hi!
sorry to dig that out ^^ but what about now?: how uch possible is it to have a nextcloud multisite???
I'm looking for that solution
thanks

**Comment by cmq-cmq** [comment]
I would also appreciate a multi-tenancy solution. Running half a dozen NC instances on my server - it works well, but I have to update each single instance, which takes a lot of time. Not to mention the waste of diskspace. 

Would be great if there is only one instance to update, while each instance keeps its individual configuration and DB.

**Comment by henningsieh** [comment]
still no sulution for 2 domains for the same instance?

**Comment by punkyard** [comment]
my walkaround:
i use nginw to proxy several URL leading to the same IP and port.
I limit users to access only members of their groups.
And i invite groups admins to use circles for shares.  
I had then to choose one generic logo and background for everyone..

so far, it does the job.. until a real solution emerge!
