### ISSUE TITLE
Unable to share files to gmail

### ISSUE THREAD

**Issue by venkat118** [nextcloud/server#7803]
### Steps to reproduce
1. Share a file or folder to a gmail

### Expected behaviour
An email should be sent to the gmail to allow access to the file

### Actual behaviour
No email has been sent out to the gmail.
It works for Hotmail and Yahoo mail

### Server configuration

**Operating system**:

Nextcloud version: 12.0.4

**Comment by rullzer** [comment]
We don't have any special code in place to handle gmail differently. Maybe gmail is blocking your e-mail host? Since it works to other e-mail services nextcloud seems to successfully send the e-mail to your mailserver. The e-mail not arriving is not something we can fix.
