### ISSUE TITLE
Log file flooded with apps/user_ldap/lib/Access.php#1852

### ISSUE THREAD

**Issue by buttle** [nextcloud/server#7804]
Hello,

We’ve recently started using LDAP with more than just test users. I am seeing this error in the log.

Nextcloud version (eg, 12.0.2): 12.0.4.3
Operating system and version (eg, Ubuntu 17.04): ubuntu xenial
Apache or nginx version (eg, Apache 2.4.25): Apache/2.4.18 (Ubuntu)
PHP version (eg, 7.1): PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

Is this the first time you’ve seen this error? (Y/N): Y

Steps to replicate it: Unknown

The output of your Nextcloud log in Admin > Logging:
**The log file is absolutely flooded with this message
Invalid argument supplied for foreach() at /var/www/nextcloud/apps/user_ldap/lib/Access.php#1852**

The output of  config.php file

```
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx,
  'trusted_domains' => 
  array (
    0 => 'my_domain.com',
  ),
  'datadirectory' => '/opt/nextcloud-data',
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'http://my_domain.com',
  'htaccess.RewriteBase' => '/',
  'dbtype' => 'mysql',
  'version' => '12.0.4.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'default_language' => 'ca',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' => 
  array ( 
    'host' => 'localhost',
    'port' => 6379,
  ),
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'mail_smtpmode' => 'sendmail',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'no-reply',
  'mail_domain' => 'mydomain.com',
);
```

Thanks for any help!

**Comment by blizzz** [comment]
Seems to be an LDAP config issue, please check your bases.

**Comment by MorrisJobke** [comment]
Could this one be catched a bit more nicely? To avoid such strange errors in the logs (because a wrong configuration should not lead to exceptions like this IMO).

**Comment by buttle** [comment]
Hi,
I've checked my config again. All tests in the wizard pass Ok.

I've noticed that every login generates two log entries

```
Error | PHP | Invalid argument supplied for foreach() at /var/www/nextcloud/apps/user_ldap/lib/Access.php#1855 | 2018-02-01T13:14:18+0100
Error | PHP | Invalid argument supplied for foreach() at /var/www/nextcloud/apps/user_ldap/lib/Access.php#1855 | 2018-02-01T13:14:18+0100
```

If you tell me how, I'll be pleased to provide more info.

Thanks.

**Comment by buttle** [comment]
Hi,
Just updated to nextcloud 13.0.0

```
Error | PHP | Invalid argument supplied for foreach() at /var/www/nextcloud/apps/user_ldap/lib/Access.php#1913 | 2018-02-06T14:51:58+0100
Error | PHP | Invalid argument supplied for foreach() at /var/www/nextcloud/apps/user_ldap/lib/Access.php#1913 | 2018-02-06T14:51:58+0100
```
I have removed the "Default password policy DN" policy I use (which seemed to test ok), and the error has stopped!
I hope that helps debug this.

Cheers.

**Comment by blizzz** [comment]
@GitHubUser4234 any chance you could look into it?
