### ISSUE TITLE
Issue with login flow

### ISSUE THREAD

**Issue by mario** [nextcloud/server#7805]
$this->request->getServerProtocol() sometimes report http even if the server is on https?

Maybe proxy or something in the back?

Demo server: https://demo13.nextcloud.bayton.org/login
Username: admin
Pass: admin

**Comment by mario** [comment]
I assume we'd need to check HTTP_X_FORWARDED_PROTO and HTTP_X_FORWARDED_SSL too?

**Comment by MorrisJobke** [comment]
Fixed by #7806
