### ISSUE TITLE
Stable13 and master adjustments for apps

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#7808]
If your app is not in the list but you want it to be, feel free to mention me in a comment

# travis.yml in stable13

- [x] https://github.com/nextcloud/survey_client/pull/69
- [x] https://github.com/nextcloud/serverinfo/pull/110
- [x] https://github.com/nextcloud/quota_warning/pull/27
- [x] https://github.com/nextcloud/password_policy/pull/53
- [x] https://github.com/nextcloud/notifications/pull/108
- [x] https://github.com/nextcloud/nextcloud_announcements/pull/28
- [x] https://github.com/nextcloud/gallery/pull/361
- [x] https://github.com/nextcloud/firstrunwizard/pull/52
- [x] https://github.com/nextcloud/files_texteditor/pull/77
- [x] https://github.com/nextcloud/files_retention/pull/41
- [x] https://github.com/nextcloud/files_pdfviewer/pull/46
- [x] https://github.com/nextcloud/files_downloadactivity/pull/26
- [x] https://github.com/nextcloud/files_automatedtagging/pull/43
- [x] https://github.com/nextcloud/files_accesscontrol/pull/86
- [x] https://github.com/nextcloud/announcementcenter/pull/91
- [x] https://github.com/nextcloud/activity/pull/234
- [x] Manually adjustment of user_saml and end_to_end_encryption needed: @schiessle

**Comment by joekerna** [comment]
What about the Tasks app?

**Comment by nickvergessen** [comment]
## Master version, doc links and required server version changes

- [ ] https://github.com/nextcloud/activity/pull/235
- [ ] https://github.com/nextcloud/admin_notifications/pull/15
- [ ] https://github.com/nextcloud/announcementcenter/pull/92
- [ ] https://github.com/nextcloud/external/pull/71
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/87
- [ ] https://github.com/nextcloud/files_antivirus/pull/40
- [ ] Manually adjustment of end_to_end_encryption needed: @schiessle
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/44
- [ ] https://github.com/nextcloud/files_downloadactivity/pull/27
- [ ] https://github.com/nextcloud/files_pdfviewer/pull/47
- [ ] https://github.com/nextcloud/files_retention/pull/42
- [ ] https://github.com/nextcloud/files_texteditor/pull/78
- [ ] https://github.com/nextcloud/files_videoplayer/pull/47
- [ ] https://github.com/nextcloud/firstrunwizard/pull/53
- [ ] https://github.com/nextcloud/gallery/pull/362
- [ ] https://github.com/nextcloud/jsloader/pull/4
- [ ] https://github.com/nextcloud/logreader/pull/66
- [ ] https://github.com/nextcloud/nextcloud_announcements/pull/29
- [ ] https://github.com/nextcloud/notifications/pull/109
- [ ] https://github.com/nextcloud/password_policy/pull/54
- [ ] https://github.com/nextcloud/quota_warning/pull/28
- [ ] https://github.com/nextcloud/serverinfo/pull/111
- [ ] https://github.com/nextcloud/survey_client/pull/70
- [ ] https://github.com/nextcloud/user_saml/pull/171

**Comment by nickvergessen** [comment]
## Supported PHP version changes

- [ ] https://github.com/nextcloud/activity/pull/236
- [ ] https://github.com/nextcloud/announcementcenter/pull/93
- [x] https://github.com/nextcloud/end_to_end_encryption/pull/42
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/88
- [ ] https://github.com/nextcloud/files_antivirus/pull/41
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/45
- [ ] https://github.com/nextcloud/files_downloadactivity/pull/28
- [ ] https://github.com/nextcloud/files_pdfviewer/pull/48
- [ ] https://github.com/nextcloud/files_retention/pull/43
- [ ] https://github.com/nextcloud/files_texteditor/pull/79
- [ ] https://github.com/nextcloud/firstrunwizard/pull/54
- [ ] https://github.com/nextcloud/gallery/pull/363
- [ ] https://github.com/nextcloud/nextcloud_announcements/pull/30
- [ ] https://github.com/nextcloud/notifications/pull/110
- [ ] https://github.com/nextcloud/password_policy/pull/55
- [ ] https://github.com/nextcloud/quota_warning/pull/29
- [ ] https://github.com/nextcloud/serverinfo/pull/112
- [ ] https://github.com/nextcloud/survey_client/pull/71

**Comment by schiessle** [comment]
i updated end-to-end-encryption

**Comment by MorrisJobke** [comment]
This is done -> closing.
