### ISSUE TITLE
Rewrite fails on Debian, index.php exposed in URL

### ISSUE THREAD

**Issue by cobbjb** [nextcloud/server#7823]
### Steps to reproduce
1. Visit your Nextcloud instance
2. index.php will be exposed in the login URL
3. Fin

### Expected behaviour
Rewrite should create URLs which look more like fqdn.com/apps/files

### Actual behaviour
URL becomes fqdn.com/index.php/apps/files

### Server configuration

**Operating system**: Debian

**Web server:** Apache 2

**Database:** mysql

**PHP version:** 7.0.27-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page) 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud

**Where did you install Nextcloud from:** repo.morph027.de Debian repository

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>Only default apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activitylog
  - encryption
  - files_external
  - user_external
  - user_ldap

</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

Note that in these logs, our subdomain is NOT "nc-server", it's more like "cloudshare".  nc-server is the hostname of the server.

```
[Tue Jan 09 19:30:03.298259 2018] [core:trace5] [pid 1459] protocol.c(645): [client ::1:58070] Request received from client: OPTIONS * HTTP/1.0
[Tue Jan 09 19:30:03.298389 2018] [http:trace4] [pid 1459] http_request.c(420): [client ::1:58070] Headers received from client:
[Tue Jan 09 19:30:03.298420 2018] [http:trace4] [pid 1459] http_request.c(424): [client ::1:58070]   User-Agent: Apache/2.4.25 (Debian) OpenSSL/1.0.2l (internal dummy connection)
[Tue Jan 09 19:30:03.298447 2018] [rewrite:trace8] [pid 1459] mod_rewrite.c(477): [client ::1:58070] ::1 - - [nc-server.ourdomain.com/sid#7f12a4c61f08][rid#7f12a4c61f08/initial] Declining, request-URI '*' is not a URL-path. Consult the manual entry for the RewriteOptions directive for options and caveats about matching other strings.
[Tue Jan 09 19:30:03.298533 2018] [http:trace3] [pid 1459] http_filters.c(1089): [client ::1:58070] Response sent with status 200, headers:
[Tue Jan 09 19:30:03.298566 2018] [http:trace5] [pid 1459] http_filters.c(1096): [client ::1:58070]   Date: Wed, 10 Jan 2018 01:30:03 GMT
[Tue Jan 09 19:30:03.298578 2018] [http:trace5] [pid 1459] http_filters.c(1099): [client ::1:58070]   Server: Apache/2.4.25 (Debian)
[Tue Jan 09 19:30:03.298588 2018] [http:trace4] [pid 1459] http_filters.c(918): [client ::1:58070]   Content-Length: 0
[Tue Jan 09 19:30:03.298597 2018] [http:trace4] [pid 1459] http_filters.c(918): [client ::1:58070]   Connection: close
[Tue Jan 09 19:30:03.298630 2018] [core:trace6] [pid 1459] core_filters.c(525): [client ::1:58070] core_output_filter: flushing because of FLUSH bucket
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
See https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#pretty-urls for the steps to set this up.
