### ISSUE TITLE
Rewrite works, but still index.php in filelisting

### ISSUE THREAD

**Issue by loeffelpan** [nextcloud/server#7828]
### Steps to reproduce
1. Activate rewriting as documented
2. See links in listing of files-app

### Expected behaviour
No index.php in any link.

### Actual behaviour
For file-listing my browser shows URLs with index.php.
For example a copied link from file list is https://toothless.goip.de/index.php/apps/files?dir=//Videos1
while Browser says https://toothless.goip.de/apps/files/?dir=/Videos&fileid=135

### Server configuration

**Operating system**: Ubuntu Server 17.10

**Web server:** Apache 2.4.27

**Database:** MySQL

**PHP version:** PHP 7.1.11-0ubuntu0.17.10.1

**Nextcloud version:** 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud.com

**List of activated apps:**
<details><summary>App list</summary>
Enabled:
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_sharing: 1.4.0
  - files_videoplayer: 1.1.0
  - lookup_server_connector: 1.0.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - provisioning_api: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_pdfviewer
  - files_texteditor
  - files_trashbin
  - files_versions
  - firstrunwizard
  - gallery
  - logreader
  - nextcloud_announcements
  - password_policy
  - serverinfo
  - sharebymail
  - survey_client
  - systemtags
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "oc65jgv8zf6o",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "toothless.goip.de",
            "toothless.fritz.box"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/toothless.goip.de",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "skeletondirectory": "",
        "logtimezone": "Europe\/Berlin",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": "6379"
        },
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "jan.noormann",
        "mail_domain": "gmail.com",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls"
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera, Chrome, Firefox

**Operating system:** Windows 10

**Comment by MorrisJobke** [comment]
Then it is not properly set up: Please check twice that it is set up like described in https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#pretty-urls and also check that maybe proxies in between are also properly configured (see https://docs.nextcloud.com/server/12/admin_manual/configuration_server/reverse_proxy_configuration.html for this).

Beside that: if you need further help reach out in the forums because that is the place to help with setup issues. 😉

**Comment by loeffelpan** [comment]
You are wrong. It is configured properly like described in the documentation. I checked that more than twice. I was in the forum before and it seem to be not an configuration issue.
https://help.nextcloud.com/t/rewrite-works-but-still-index-php-in-filelisting/24940

To describe again:
I the adress line of the browser never appears index.php - rewriting seems to work.
Just in the links of the file list generated by the files app. Clicking them rewrites the link successful (in browsers adress line) without index.php.

**Comment by MorrisJobke** [comment]
On a lot of instances this is exactly how it works - `'htaccess.RewriteBase'` in config.php and then an `occ maintenance:update:htaccess` should do the trick. If you have a reverse proxy in front of this, then it also need to be configured correctly, but I can't see any problems with this config as it works exactly like that on many machines.

How does your setup look like?

**Comment by loeffelpan** [comment]
My configuration is to see in the first post:
Ubuntu Server, Apache, MySQL, PHP, no proxy, direct connection.
And it‘s exactly configured as you explain.

I would bet, that in your pretty configuration this issue is present, too.
Please go to the files app and copy or just hover a file or folder. In that link will appear index.php.
Clicking and open it will get the link in the adress line of my browser without index.php.
