### ISSUE TITLE
Quotas for groups (Individually)

### ISSUE THREAD

**Issue by Tomoli75** [nextcloud/server#7830]
I want to be able to add people to a group, and have their personal quota set whilst they are in the group.

Possible via app or core, i don't know, but couldn't find anything that lets me do that.

**Comment by tflidd** [comment]
Can you specify? Do you mean that users of a group have a common total quota:
https://github.com/nextcloud/server/issues/4275

Or do you just want to set default quotas for users depending on the group?

**Comment by MorrisJobke** [comment]
Closing as duplicate of #4275
