### ISSUE TITLE
13.0.0 RC1 Gallery while logged containers fewer photos than the same gallery using the share link

### ISSUE THREAD

**Issue by rubrik** [nextcloud/server#7841]
(system info in #7831)

When I am logged into Nextcloud, and view a directory of images using Files, I see everything that is there.
If I switch to grid view/Gallery, I see far fewer photos, like it is paginating but not giving me the option to go to the next page.

The same folder is shared using a share link, there all photos are always visible.

I don't remember having this problem in 12, but I wouldn't swear on it :)

**Comment by koarlmichael** [comment]
I can reproduce the error. Here also runs NC 13 RC1. The error was definitely not in NC 12.0.4.

**Comment by MorrisJobke** [comment]
This is a bug in the gallery app - could you reopen it in the gallery issue tracker: https://github.com/nextcloud/gallery/issues
