### ISSUE TITLE
Nextcloud with ISPConfig3

### ISSUE THREAD

**Issue by rubenszolt** [nextcloud/server#7851]
I have a problem with Netxcloud and ISPConfig, I try many configs nginx directives to working corectly with ISPconfig, but without success. I receive the next error messages: Error while app is enabled when I try to install an app.

Please somebody to help, have a good config.

Here is the latest nginx directive config:
        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
        client_max_body_size 512M;
        fastcgi_buffers 64 4K;

        rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
        rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
        rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;

        index index.php;
        error_page 403 = /core/templates/403.php;
        error_page 404 = /core/templates/404.php;

        location ~ ^/(data|config|\.ht|db_structure\.xml|README) {
                  deny all;
        }

        location / {
                  rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
                  rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;
                  rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
                  rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;
                  rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;
                  try_files $uri $uri/ /index.php?$args;
        }

        location ~ ^(.+?\.php)(/.*)?$ {
                  try_files $1 = 404;
                  include fastcgi_params;
                  fastcgi_param PATH_INFO $2;
                  fastcgi_param SCRIPT_FILENAME $document_root$1;
                  fastcgi_pass unix:/var/lib/php7.0-fpm/web2.sock;
        }

        location ~* ^.+\.(jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
                  expires 30d;
                  access_log off;
        }

        location = /data/htaccesstest.txt {
                  allow all;
                  log_not_found off;
                  access_log off;
        }

### Server configuration
**Operating system**: debian 9.3 x64
**Web server:** apache2
**Database:** mariadb
**PHP version:** 7.0
**Nextcloud version:** 12.0.4
**Nextcloud fresh install:**

**Comment by MorrisJobke** [comment]
The full needed Nginx config can be found in our documentation: https://docs.nextcloud.com/server/13/admin_manual/installation/nginx.html

**Comment by rubenszolt** [comment]
Thanks I've already found it, but I think it is not solution for my question.
