### ISSUE TITLE
Can't log in with saml

### ISSUE THREAD

**Issue by jsargent7089** [nextcloud/server#7860]
### Steps to reproduce
Login
### Expected behaviour
Login

### Actual behaviour
Account not provisioned.
Your account is not provisioned, access to this service is thus not possible.
**Operating system**:
Ubuntu
**Web server:**
Apache
**Database:**
mysql
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
12.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by schiessle** [comment]
Would be good to have more information (which IdP do you use, how does your configuration looks, what's in the logs,...). You can also use the Firefox extension "SAML tracer" to see the messages send between the IdP and your Nextcloud to debug it.

One idea: Use another attribute to map it to the UID. In the past I saw IdP's who didn't send some attributes not correctly to the Nextcloud server.

**Comment by jsargent7089** [comment]
€‹<samlp:Response Destination="https://dozedrive.dozecloud.com/index.php/apps/user_saml/saml/acs"
    ID="_b76bbc02c0844304d00c" InResponseTo="ONELOGIN_87f5977eb5e9fd88b9fe7b510598c52b18b24f84"
    IssueInstant="2018-01-17T00:03:12Z" Version="2.0" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">urn:sso-dozecloud.auth0.com</saml:Issuer>
    <samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status>
    <saml:Assertion ID="_4msp8DkVoa0IDPfT2041WYhhZPk41IxJ" IssueInstant="2018-01-17T00:03:12.984Z"
        Version="2.0" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">
        <saml:Issuer>urn:sso-dozecloud.auth0.com</saml:Issuer>
        <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
            <SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                <Reference URI="#_4msp8DkVoa0IDPfT2041WYhhZPk41IxJ">
                    <Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                    <DigestValue>9ly4MJAx8wpi4gpWZHUYz6ULZvY=</DigestValue>
                </Reference>
            </SignedInfo>
            <SignatureValue>OQ/Ahbz7Cr1ZREVUG3EcZUmwg3/EGwO9gmR+4mI04I1iVZPLormlVoLP6jztTNlE5QXzbIbrwhi0XfBYuMYOQ97gaNRI1JW/RrsaXb+iSW7Q0s0N2GJUsDQuxJ9G+01yviUZtXge8lzKNETh7rDx/ZCNWzo+EtgSmBmiJy/2PqpkJ3nsXbeTv8RJa1BI9QuSL2MKBrgEhYYBcnI+CT8n2hbAxeqXkW4zlG/npmkIOL9brXm2OtfVw3nqc8BxJyQjrjb4+/+Vj7OGktiVPIRgaT41ODrsUNFZevEeKwo+8s6Gx7L19FDybOi4WhX0B93Yi5mTipxjzpWJPBVFrRJbug==</SignatureValue>
            <KeyInfo>
                <X509Data>
                    <X509Certificate>MIIDCTCCAfGgAwIBAgIJduAefBogKyPhMA0GCSqGSIb3DQEBCwUAMCIxIDAeBgNVBAMTF3Nzby1kb3plY2xvdWQuYXV0aDAuY29tMB4XDTE4MDExNDAzNDM0MFoXDTMxMDkyMzAzNDM0MFowIjEgMB4GA1UEAxMXc3NvLWRvemVjbG91ZC5hdXRoMC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCiBOZDZHL+1sisOnHfqpJ6Gf3De4KpxYaonxmHtu82zvr+UEWbXZWeOi1Eeg3jrn6MyrGYQQKCE7qpzHX/AzbL4XM4NsftIbykQd4XUPxHgUsQWaxhHHzVV7dIU30b/HeyintrsqpFjxLM/zh60DdQdtAd66aGSkePtZo3b4pe2YUfBi6QdUF4Z38gEYxwjv9lY3sqSFJd1tDi+VoWWabSHcvKO4bYSNi/lPGabxhV7WRBAT114PSAv8odLkIfQEAYn/v0dcvktj/JTkhw2pXypS/OTbZlPYo43XZsGaGNyUS180070J8KLnRSnDES9c5uRct+jCtGWyh7FZDPLdSXAgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFKtywgWHdSzjpvcA7+IJZId7zeLYMA4GA1UdDwEB/wQEAwIChDANBgkqhkiG9w0BAQsFAAOCAQEAGHBy3HIkQ4VVdAOJq13OZ9LJcnNx2opdZbnjkYae/FgDRsz6tjTT8zB+n8dTe69VDXS446J+r71cS5lZpHW+ZxFKIqyuHuv/6T76ZfahhflnRrZk+vyIvPw0ozUVKxs7bGJ5GFqCS9euFkq0ovs5uMa3ptj43CyCdpWGH6D6f//F1aC9D93pRFQ3Mn9deHfnMyFlWQoJJiJQWrx6iElHmtRp15rsBtH3lq7M53kjbazbexq9aWdtQEJmz1Dk4zn4VaxRQ1GHwf6hutDRqxb2qG/j7TTGbfor1jerXX42KeP64HCZrX+n+UlHXNU7dAlXu0Agpdpb9MeRmWnxYHSYpg==</X509Certificate>
                </X509Data>
            </KeyInfo>
        </Signature>
        <saml:Subject>
            <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">admin@doze-cloud.tech</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData InResponseTo="ONELOGIN_87f5977eb5e9fd88b9fe7b510598c52b18b24f84"
                NotOnOrAfter="2018-01-17T01:03:12.984Z"
                Recipient="https://dozedrive.dozecloud.com/index.php/apps/user_saml/saml/acs"/></saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2018-01-17T00:03:12.984Z" NotOnOrAfter="2018-01-17T01:03:12.984Z">
            <saml:AudienceRestriction>
                <saml:Audience>https://dozedrive.dozecloud.com/index.php/apps/user_saml/saml/metadata</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2018-01-17T00:03:12.984Z"
            SessionIndex="_fK-mdQrCEiEkFrZO6ejHGBIHJh1LfNyq">
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">auth0|5a5bde6f70101b282fb6ae98</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">admin@doze-cloud.tech</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">admin@doze-cloud.tech</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">admin@doze-cloud.tech</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/identities/default/provider"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">auth0</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/identities/default/connection"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">Username-Password-Authentication</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/identities/default/isSocial"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:boolean">false</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/username"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">jsargent</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/picture"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">https://s.gravatar.com/avatar/ea872e5cec6ad997b9f6983287b1baaa?s=480&amp;r=pg&amp;d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fad.png</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/nickname"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">jsargent</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/email_verified"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:boolean">true</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/clientID"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">DNbf3Sb3ulRMffL9Z3TtkI_W42V01i8b</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/identities"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:anyType">[object Object]</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/updated_at"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:anyType">Wed Jan 17 2018 00:03:12 GMT+0000 (UTC)</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/created_at"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:anyType">Sun Jan 14 2018 22:49:19 GMT+0000 (UTC)</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="http://schemas.auth0.com/multifactor"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">guardian</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>
</samlp:Response>

**Comment by jsargent7089** [comment]
My provider is Auth0

**Comment by jsargent7089** [comment]
Here is the log from nextcloud



Error | index | OneLogin_Saml2_Error: Invalid array settings: sp_certs_not_found_and_required/var/www/html/apps/user_saml/lib/Controller/SAMLController.php - line 171: OneLogin_Saml2_Settings->__construct(Array)[internal function] OCA\User_SAML\Controller\SAMLController->getMetadata()/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 90:OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\User_SAML\Controller\SAMLController), 'getMetadata')/var/www/html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\User_SAML\Controller\SAMLController), 'getMetadata')/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App main('OCA\\User_SAML\\C...', 'getMetadata', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/html/lib/private/Route/Router.php - line 299:call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/html/lib/base.php - line 1004: OC\Route\Router->match('/apps/user_saml...')/var/www/html/index.php - line 48: OC handleRequest(){main} | 2018-01-16T15:47:57-0800
-- | -- | -- | --
Error | index | OneLogin_Saml2_Error: Invalid array settings: sp_certs_not_found_and_required/var/www/html/apps/user_saml/lib/Controller/SAMLController.php - line 171: OneLogin_Saml2_Settings->__construct(Array)[internal function] OCA\User_SAML\Controller\SAMLController->getMetadata()/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 90:OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\User_SAML\Controller\SAMLController), 'getMetadata')/var/www/html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\User_SAML\Controller\SAMLController), 'getMetadata')/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App main('OCA\\User_SAML\\C...', 'getMetadata', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/html/lib/private/Route/Router.php - line 299:call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/html/lib/base.php - line 1004: OC\Route\Router->match('/apps/user_saml...')/var/www/html/index.php - line 48: OC handleRequest(){main}

**Comment by jsargent7089** [comment]
![screenshot from 2018-01-16 17-56-00](https://user-images.githubusercontent.com/27903375/35021659-a80a2a80-fae6-11e7-98d6-f593a2baf2b7.png)
![screenshot from 2018-01-16 17-55-57](https://user-images.githubusercontent.com/27903375/35021660-a8246ba2-fae6-11e7-8b2d-7dc1db3126fb.png)

**Comment by jsargent7089** [comment]
@schiessle

**Comment by schiessle** [comment]
I never trued oauth0, are you sure that it is a SAML provider? The name indicate that it does oAuth.

Sadly your screenshot doesn't show the first input field where you enter the Attribute which should be mapped to the UID. You could also install the saml tracer plugin to see what oauth2 sends back to nextcloud, if the attribute you configured comes back to Nextcloud and if it has a useful value attached to it.

**Comment by jsargent7089** [comment]
[Saml (1).pdf](https://github.com/nextcloud/server/files/1866137/Saml.1.pdf)

**Comment by jsargent7089** [comment]
@schiessle
