### ISSUE TITLE
fix auto-log-out which is broken due to notification polling/heartbeat

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#7864]
For some compliance frameworks you need to log users out automatically after a certain period of inactivity.

Notification polling kills our auto-logout: you never get more than 30 sec inactivity. It should be ignored when determining the inactive period of a user. Same with heartbeat and perhaps other things.

**Comment by camoflash** [comment]
Session idle timeout is definitely an important factor when securing sensitive data - especially now when the new EU law on data protection and privacy has come into play.
We are hoping to start up with nextcloud this fall and are having some trouble as well with session lifetime. As jospoortvliet is mentioning, Nextcloud are having a notification pooling / heartbeat happening every 30 sec that possibly is keeping the session active even though the session are meant to expire. Practically when session lifetime is configured to 29 seconds in nextcloud's config.php file like this:

'remember_login_cookie_lifetime' => 0,
'session_lifetime' => 29,
'session_keepalive' => false

users are being logged out after 29 seconds. But when it is set to 30 or more - users are not being logged out.

This is, for us, a huge security concern when working around unauthorized people every minute of the day with laptops.

**Comment by jospoortvliet** [comment]
FYI if this is a blocker, you can contact our sales team as customer demand might push a resolution higher on the roadmap :rocket:

**Comment by MorrisJobke** [comment]
This actually can be done by setting this config.php option:

```php
'session_keepalive' => false,
```

Then the polling for notifications and heartbeat will not happen and the session can timeout.

**Comment by MorrisJobke** [comment]
Refering to the notifications apps code:

https://github.com/nextcloud/notifications/blob/master/src/App.vue#L180
https://github.com/nextcloud/notifications/blob/stable13/js/app.js#L107
