### ISSUE TITLE
Test theme Blackysgate neXtrealTime

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#7868]
Hi,
i have uploaded a Theme " neXtrealTime " where i have 
build up and can be as "test Theme" for nextcloud.
todo: 
changeing out, Foldericons and other Icons.

--
**Issue for Nextcloud-programming-Community :** 

make the Foldericons again to normal png-icons
to have a possible to change it with the theme.

And a possible for upload Themefiles for N3xtcl0ud ;)
i bet with you, if you make a possible for upload themes, 
would give many peoples who make different themes for NextCloud

--

all it is a bit Customized in dark/black Style with green buttons
and css-linking in own application.css and so on.
many fun for testing and looking in the files : 

Milestone Nextcloud 13.0 "More easy changing to other Themes"
Themename :  neXtrealTime 

Readme.txt
```
The process is simple:

1. Put this neXrealTime folder in the ./themes folder of NextCloud
2. Activate it by putting 'theme' => 'themename', into the config.php file

like this 

"  
'theme' => 'neXtrealTime',
"
in front of 
" 
); 
"
and disable in Nextcloud 12.0 the Theme-app 
for able to make the native theme-engine running !


best regards
Blackysgate.de
```
Download : http://blackysgate.de/files/folder-root/nextcloud/neXtrealTime-0.9.5-15.01.18.tar.gz

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers 



> make the Foldericons again to normal png-icons
> to have a possible to change it with the theme.

We use SVGs to make them easier themable.



> And a possible for upload Themefiles for N3xtcl0ud ;)
> i bet with you, if you make a possible for upload themes,
> would give many peoples who make different themes for NextCloud

I would also say, that we should not aim for themes, but making the theming app the way how to change the look and feel. Themes are so powerful, that they mostly result in a broken setup in some way and should only be used by very experienced people, that really know what they do.

**Comment by MorrisJobke** [comment]
In my opinion I would not allow to upload themes to the appstore.

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming

**Comment by MariusBluem** [comment]
At least technically it seems to be possible to have an theme as an app. Not a problem until somebody submits themes to the appstore - but I‘d prefer expanding the theming-app or create apps for customization-apps like theming_customcss instead of hardcoded themes in the appstore.

I‘d vote for closing.

**Comment by blackcrack** [comment]
appstore it is for apps, themestore on NC would really nice :)
i'd vote for speak about a Themestore ;) \*s*

**Comment by juliushaertl** [comment]
> "We use SVGs to make them easier themable."
> svg's ? oh, which css (line) file (name.svg) ?
> i use svg too :) i should know which svg file it is for Folders
> for placed in in the css file .. (so the id or class of it)

Not sure if I get you right, but you may just check the documentation on how to theme mimetype icons.

> appstore it is for apps, themestore on NC would really nice :)
> i'd vote for speak about a Themestore ;) *s*

Custom themes have to much potential of breakage, therefore we should not encourage users to use them too much. The theming app should work fine for most of the use cases. 

> i have uploaded a Theme " neXtrealTime " where i have build up and can be as "test Theme" for nextcloud.

I guess the forum is a better place to announce a custom theme you built. The GitHub repo is just for reporting issues with the server component.

**Comment by blackcrack** [comment]
Forum, ehh right.. totally forget.. was an short shoot.. just for bring in ..
how to theme mimetypeicons.. , did not seach.. but goot to know.. 👍 

why want you give Garantie for themes ? 
The Standard-theme works and this is official, all other it's not officially and it is out from the Community and should be supported by the Thememaker/Designer..
the themes works or works not.. and it is not used,.. the wohle rest it is the designer who 
should support it or not.. or "Moderator" can kick out the theme if's not work.. end.. 
thing end and clean themes.
"Theme is broken"[X]  an other part it is a Theme-Ranking.. +++ or ---- like on Winfuture.de the replys
ranking by download and stars. If upload a Themer/Designer an theme who it is broken, it's his own blame.
The Internal Nextcloud-Group can not support at all, they can give the possible only at hand..

best regards
Blacky

**Comment by skjnldsv** [comment]
> In my opinion I would not allow to upload themes to the appstore.

Funny, I thought about this today :)
I think having presets on the theming settings could be a great addition! But clearly not full themes :)

**Comment by blackcrack** [comment]
Well, therefore told i am, we should have an other possibility
for upload themes from peoples who want exchange and 
change the themes skjnldsv / John Molakvoæ , 
who can read is clearly in the advantage.

best regards
Blacky

**Comment by MariusBluem** [comment]
> who can read is clearly in the advantage.

As already told in the past - Please stay constructive and read our code of conduct: https://nextcloud.com/code-of-conduct/

There was an app for uploading or at least changing the old-themes via webinterface from an community contributor.

I see no real market for more advanced theming-capabilities next to our theming-app. People who want to customize their Nextcloud in a way which is not covered by our theming-app - know what they are doing (CSS and PHP-skills). Those who haven’t - should not edit the theming files (easily breaks stuff).

I still want to recommend you the theming_customcss app, which allows you to set custom css rules in the Nextcloud frontend.

**Comment by blackcrack** [comment]
okey, i delete all my comments..
sorry for doing that..

best regards
Blacky
