### ISSUE TITLE
Email invitation token validness time should be adjustable

### ISSUE THREAD

**Issue by y0va** [nextcloud/server#7871]
Invitation emails become invalid over the weekend.

### Expected behaviour
Email invitations should stay valid for ~10 days, or up to a configurable amount of time.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers for the UX part of this.
cc @nextcloud/security for the security part of this.

**Comment by nickvergessen** [comment]
Invitation to what?

**Comment by y0va** [comment]
Invitation to become a user of the nextcloud instance.

**Comment by fakemoth** [comment]
Just wanted to second the OP in this request - there should be a setting for this. BTW what is the current validity interval? Seems I can't find this info, and my invitations expired in a few days or so... And no way to resend them also?

**Comment by y0va** [comment]
The situation seem to worsen: Now the token became invalid over night.

**Comment by jancborchardt** [comment]
There shouldn't need to be a setting for a detail like this. They should simply be valid for a longer, reasonable time (like 10 days as mentioned).

And in the users management, there should be a way to "Resend invitation" in the 3-dot-menu. (Additionally, never active users could be sorted up top, or there could be a navigation entry for them.)

**Comment by y0va** [comment]
Any news on this? Invitation with user-set passwords is hardly working like that.

**Comment by MorrisJobke** [comment]
It was changed to 7d with Nextcloud 14: #10942

Let's close this then.
