### ISSUE TITLE
Webdav search: very slow on list all photos

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#7875]
For android we have a "photos" view, which currently lists all photos.
On my test instance I have ~9000 images (find | grep -i jpg | wc)

The search (query is "image/%") is very very slow and takes ~35s where mysql process is 100%.
Is this "only" due to my test instance or is this always such slow and can be improved?

(a second identical call takes the same time, so no caching?)

**Comment by rullzer** [comment]
This sounds like we are missing an index somewhere.

@tobiasKaminsky do you have the webdav call that is send to the server?

**Comment by tobiasKaminsky** [comment]
path: /nc/remote.php/dav
request entitiy: 
```<?xml version="1.0" encoding="UTF-8"?>
	<d:searchrequest xmlns:d="DAV:" xmlns:oc="http://nextcloud.com/ns">
		<d:basicsearch>
			<d:select>
				<d:prop><d:displayname/><d:getcontenttype/><d:resourcetype/><d:getcontentlength/><d:getlastmodified/><d:creationdate/><d:getetag/><d:quota-used-bytes/><d:quota-available-bytes/><oc:permissions xmlns:oc="http://owncloud.org/ns"/><oc:id xmlns:oc="http://owncloud.org/ns"/><oc:size xmlns:oc="http://owncloud.org/ns"/><oc:favorite xmlns:oc="http://owncloud.org/ns"/></d:prop>
			</d:select>
			<d:from>
				<d:scope><d:href>/files/tobi</d:href><d:depth>infinity</d:depth></d:scope>
			</d:from>
			<d:where>
				<d:like><d:prop><d:getcontenttype/></d:prop><d:literal>image/%</d:literal></d:like>
			</d:where>
			<d:orderby/>
	</d:basicsearch>
</d:searchrequest>```

**Comment by rullzer** [comment]
This basically happens because we need to do a propfind for each of the nodes we find. So in your case this results in 9k propfinds. So yeas that takes a lot of time ;)

**Comment by tobiasKaminsky** [comment]
As discussed on IRC, we want now to do this with a limited search (e.g. 100) and when reaching the end of the list fetch the next 100 items.
--> closing as we have a workaround.
