### ISSUE TITLE
Download of  file using REST API fails.

### ISSUE THREAD

**Issue by tummimadhu** [nextcloud/server#7880]
Hi All,

I am trying to download a file from a user account in NextCloud, using NextCloud API's with Curl command.

For small files it executes with out error but when I do 'ls' on the current folder it does not show the file.

1. command used  
curl -u user3:user3@123 -X GET 'http://x.x.x.x/remote.php/dav/files/user3/push.sh'

2. file location in UI

3. ls on
![34824746-be57bbee-f6f5-11e7-871f-4bb3b4aa7c16](https://user-images.githubusercontent.com/6253033/34986575-0fff0c04-fade-11e7-88e9-af7eadb4645b.png)
![34824821-0504dee6-f6f6-11e7-9fbc-6989997a1bcc](https://user-images.githubusercontent.com/6253033/34986576-10282f76-fade-11e7-8d56-a7d3210a2bb7.png)
![34824891-597229f2-f6f6-11e7-9dce-1efd067a2c59](https://user-images.githubusercontent.com/6253033/34986577-1051db6e-fade-11e7-9b51-646815dba792.png)

 local system ip masked intentionally
![image](https://user-images.githubusercontent.com/6253033/34824821-0504dee6-f6f6-11e7-9fbc-6989997a1bcc.png)
4. uploading a bigger  file throws binary data on the console

ex: curl -u user3:user3@123 -X GET 'http://x.x.x/remote.php/dav/files/user3/VXLAN_Scaling_Data_Center_Designs.pdf'

Please let me know what I am doing wrong.

I am also providing log output for large file 
[largeFile.log](https://github.com/owncloud/core/files/1622457/largeFile.log)

**Comment by tummimadhu** [comment]
Any update?

**Comment by tummimadhu** [comment]
Using the command curl -u user3:user3@123 -X GET 'http://x.x.x/remote.php/dav/files/user3/config.txt, I am getting the contents of the file printed on the console, So my understanding is GET is used to get the content of a file. However I need a REST API to download the file from a user account. Can any one help out with the API's.??

**Comment by tummimadhu** [comment]
Hi All,

I am able to download the file I have written a c program using CURL library to down load the file using GET REST API
GET 'http://x.x.x/remote.php/dav/files/user3/config.txt

Issue can be closed

**Comment by Luby1917** [comment]
Using the **curl** command have the **-o** option to specify the file to store the output, by default it prints the output on screen.

curl -u user3:user3@123 -o config.txt http://x.x.x/remote.php/dav/files/user3/config.txt
