### ISSUE TITLE
403: Webdav encrypted

### ISSUE THREAD

**Issue by benhartwich** [nextcloud/server#7890]
### Steps to reproduce
1. Install Nextcloud 13 RC1
2. Install beta android app
3. Create a folder called encrypted
4. Set encryption for this empty folder
5. Upload two images
6. Visit web backend and click on folder encrypted

### Expected behaviour
Show me the encrypted files

### Actual behaviour
Nothing is shown and loading wheel is turning open end.

### Server configuration

**Operating system**: 
Debian 9

**Web server:**
nginx 1.10.3

**Database:**
MariaDB 10.1.30

**PHP version:**
7.0.27

**Nextcloud version:** (see Nextcloud admin page)
13 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13 Beta 4

**Where did you install Nextcloud from:**
Nextcloud.org

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - end_to_end_encryption: 1.0.1
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_automatedtagging: 1.3.0
  - files_fullnextsearch: 0.3.1
  - files_fulltextsearch: 0.5.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.2.0
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - fullnextsearch_elasticsearch: 0.3.1
  - fulltextsearch: 0.5.0
  - fulltextsearch_elasticsearch: 0.5.0
  - gallery: 18.0.0
  - groupfolders: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ocdownloader: 1.5.5
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 1.12.40
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_diaspora: 1.0.2
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - spreed: 3.0.1
  - spreedme: 0.3.11
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "beta.speibox.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/beta.speibox.de",
        "dbtype": "mysql",
        "version": "13.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "beta",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:** 
Chrome

**Operating system:** 
Windows 7

#### Browser log
<details>
<summary>Browser log</summary>

core.js?v=a969e03c-0:5729 PROPFIND https://beta.speibox.de/remote.php/webdav/Encrypted 403 ()
request @ core.js?v=a969e03c-0:5729
propFind @ core.js?v=a969e03c-0:5569
getFolderContents @ client.js?v=a969e03c-0:472
reload @ merged-index.js?v=a969e03c-0:5844
changeDirectory @ merged-index.js?v=a969e03c-0:5700
_onUrlChanged @ merged-index.js?v=a969e03c-0:4714
dispatch @ core.js?v=a969e03c-0:3
r.handle @ core.js?v=a969e03c-0:3
trigger @ core.js?v=a969e03c-0:3
a.event.trigger @ core.js?v=a969e03c-0:7
(anonymous) @ core.js?v=a969e03c-0:3
each @ core.js?v=a969e03c-0:2
each @ core.js?v=a969e03c-0:2
trigger @ core.js?v=a969e03c-0:3
_onPopState @ merged-index.js?v=a969e03c-0:279
initialize @ merged-index.js?v=a969e03c-0:110
(anonymous) @ merged-index.js?v=a969e03c-0:320
(anonymous) @ core.js?v=a969e03c-0:781
setTimeout (async)
_.delay @ core.js?v=a969e03c-0:780
executeBound @ core.js?v=a969e03c-0:714
bound @ core.js?v=a969e03c-0:746
(anonymous) @ merged-index.js?v=a969e03c-0:319
j @ core.js?v=a969e03c-0:2
fireWith @ core.js?v=a969e03c-0:2
ready @ core.js?v=a969e03c-0:2
I @ core.js?v=a969e03c-0:2
client.js?v=a969e03c-0:421 Uncaught (in promise) TypeError: Cannot read property 'getElementsByTagNameNS' of null
    at Client._getSabreException (client.js?v=a969e03c-0:421)
    at client.js?v=a969e03c-0:485
    at <anonymous>
</details>

**Comment by rullzer** [comment]
This is by design. You are not allowed to interact with the encrypted files from the web. You can't open them anyway :wink:

**Comment by benhartwich** [comment]
Yes, but the GUI should say you so :)

**Comment by rullzer** [comment]
It should. If not please open an issue in https://github.com/nextcloud/end_to_end_encryption
