### ISSUE TITLE
Add endpoint to list apps enabled in the server and its urls

### ISSUE THREAD

**Issue by camilasan** [nextcloud/server#7893]
For example the Calendar app could request to have a 'Calendar' entry in the primary Desktop Client Menu. On click it should open the default browser with an url. In this case the Nextcloud Calendar.

**Comment by MorrisJobke** [comment]
Maybe we could integrate this with the server side menu (app `external`). cc @nickvergessen 

@camilasan Could you elaborate on the goal for this? I guess to add entries like "Contacts" and "Calendar" to the tray menu of the desktop client, right?

cc @rullzer for the tray menu things

**Comment by rullzer** [comment]
@MorrisJobke I think we can also integrate this into the external app for sure. But I would also be interested in getting things like direct link to deck etc.

I would suggest to do this via the capabilities.

The question is of course how. Do we want to add a new capability interface?
Do we want this for all apps?

**Comment by camilasan** [comment]
Capabilities e.g. https://example.org/ocs/v2.php/cloud/capabilities ?

**Comment by juliushaertl** [comment]
There is already an OCS api for the external sites app: https://github.com/nextcloud/external#ocs-api I guess those should be shown in the client as well.

> I would suggest to do this via the capabilities.
> The question is of course how. Do we want to add a new capability interface?

I'd suggest to add this to the core capabilities, besides the existing webdav-root it might make sense to have a list of "webapps" there.

**Comment by camilasan** [comment]
I am testing my changes and the response for non-admin users don't return the 2 external sites I have in my test env:
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message>OK</message>
 </meta>
 <data/>
</ocs>

Is this expected?

**Comment by camilasan** [comment]
It would be nice to be able to retrieve only the apps enabled and that are in the top left menu in the web interface. Is it possible?

**Comment by MorrisJobke** [comment]
> It would be nice to be able to retrieve only the apps enabled and that are in the top left menu in the web interface. Is it possible?

That would be the idea here, because for those we have an entry URL.

**Comment by juliushaertl** [comment]
Let me have a look if I can come up with something here.

**Comment by nickvergessen** [comment]
I would suggest to:
* Not abuse the external sites app for this. It is an app to embed 3rd party sites into Nextcloud, not to get the menu to the client. And also the app might be disabled.
* Not abuse the capabilities even more

Also we need to make sure that the external sites are not shown twice. They should already be displayed because of a costumer (or is this mobile apps only) and they are also registered in the navigation.

But maybe the navigation manager could just publish their collection via an endpoint.

**Comment by juliushaertl** [comment]
> Also we need to make sure that the external sites are not shown twice. They should already be displayed because of a costumer (or is this mobile apps only) and they are also registered in the navigation.

As the external sites are exposed to the NavigationManager this should work just fine then.

> Not abuse the capabilities even more

Ah, yes, I guess it makes sense to have it as a generic core endpoint so we can also use it when updating the app menu after installing/removing apps.

**Comment by MorrisJobke** [comment]
Fixed in #8095
