### ISSUE TITLE
NextCloud Talk and Safari

### ISSUE THREAD

**Issue by egaldoch** [nextcloud/server#7896]
### Steps to reproduce
1. Make a call from Safari 11.0.2 (macOS) to Safari (macOS), FireFox (macOS) to Safari (macOS)
2. Make a call from Safari (iOS) to Safari (macOS)
### Expected behaviour
Video Conversation
### Actual behaviour
It seems that Safari is not functioning correctly with the talk app. If I take a guest call as soon one client is running safari no connection is established. With the Talk App for iOS and Firefox on macOS it is working flawless. A connection between the Talk App and a Safari client is also not working. 

 
### Server configuration
TURN Server running, Apache 2, PHP 7

**Operating system**:
debian

**Nextcloud version:** (see Nextcloud admin page)
13 RC1
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Comment by rullzer** [comment]
Please report in https://github.com/nextcloud/spreed
