### ISSUE TITLE
CSS broken in firefox

### ISSUE THREAD

**Issue by immae** [nextcloud/server#7905]
### Steps to reproduce
1. Open cloud instance on firefox 57.0.3
2. login

### Expected behaviour
Expecting to see the file list

### Actual behaviour
The CSS is completely screwed.
![2018-01-17_01_03_41](https://user-images.githubusercontent.com/510202/35018526-59293d84-fb22-11e7-828e-1f7432189547.png)

The web console complains that he cannot parse "/index.php/css/core/5fe99a33a90920b07ba9e99bde4e824b-server.css?v=3b461525fc1dda6972a9b575d24e0703-0", and actually the file seems to be empty.

The same link seen on chromium is correctly populated with styles.
The same link downloaded with wget is also empty.

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** postgresql

**PHP version:** 7.1

**Nextcloud version:** 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from nextcloud 12.0.3 (which was working correctly)

**Where did you install Nextcloud from:**
Packaged by the archlinux distribution

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bookmarks: 0.10.1
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.1.4
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - gpxedit: 0.0.7
  - gpxpod: 2.1.4
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.2
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - firstrunwizard
  - user_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "occ80acffb59",
        "datadirectory": "\/home\/immae\/.no_backup\/owncloud",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "12.0.4.3",
        "dbname": "webapps",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maxZipInputSize": 0,
        "allowZipDownload": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "outils.immae.eu",
            "cloud.immae.eu"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstoreenabled": false,
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "sendmail",
        "mail_from_address": "owncloud",
        "mail_domain": "immae.eu",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "dbindex": 14
        },
        "overwrite.cli.url": "https:\/\/cloud.immae.eu",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox (works correctly with Chromium)

**Operating system:** Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No error
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"5Lwjk5iAtELJ0EAz0k50","level":0,"time":"2018-01-16T23:56:38+00:00","remoteAddr":"X.X.X.X","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OCA\\Activity\\BackgroundJob\\RemoteActivity job with ID 5880","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
{"reqId":"5Lwjk5iAtELJ0EAz0k50","level":0,"time":"2018-01-16T23:56:38+00:00","remoteAddr":"X.X.X.X.","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OCA\\Activity\\BackgroundJob\\RemoteActivity job with ID 5880 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Content Security Policy: La directive « frame-src » est obsolète. Veuillez utiliser la directive « child-src » à la place.
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« script-src 'nonce-dWU1T1FyWkVGNW4rUXcvVC8ycFJNbDNJU0dkamwrRmx1YStHY1FNNWE5UT06MUkwRURkbzBmOC9PSVVlaWx4QWRlek92RHpNMzJxY0ozZVhUQjJRS0ErUT0=' 'unsafe-eval' »). Source: (function e(t,n,r){function s(o,u){if(!n....
files:1
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
Erreur dans les liens source : request failed with status 404
URL de la ressource : https://cloud.immae.eu/core/vendor/core.js?v=3b461525fc1dda6972a9b575d24e0703-0
URL du lien source : purify.min.js.map
[En savoir plus]
window.controllers/Controllers est obsolète. Veuillez ne pas l’utiliser pour détecter l’agent utilisateur (UA).

network log all 200.

Cache cleared
```
</details>

**Comment by macau23** [comment]
Are you sure? It works for me on Firefox 57. Do you have any add-ons installed that might be causing this?

**Comment by immae** [comment]
I may, but I have no hint...
Note that it’s consistent: three computers have the problem with firefox, and they have distinct add-on settings. And wget also have the empty stylesheet, and it has no add-on...

**Comment by immae** [comment]
(Also, I’m not alone: https://help.nextcloud.com/t/css-not-working-after-login-reinstall-instance-from-existing-one/24284 )

**Comment by immae** [comment]
Ok, so I checked the (nextcloud) apps, and it turns out that there is a "Theming" app that is activated by default (I never used it as far as I remember). If I disable it, it works correctly, and if I enable it it’s broken again. I should probably open a distinct issue for that then

**Comment by Jerico815** [comment]
I got exactly the same issue.
After my root disk was filled up 100%, I extended my disk and reboot ubuntu. Then I got this css problem.

This command solved the problem for me too:
`sudo -u www-data php /var/www/nextcloud/occ app:disable theming`

I never used this app before. This app was installed by default.
Thank you for the help.

**Comment by fbrousse** [comment]
Fix for me as well ! thanks. (issue on chrome and nextcloud 15.0.5)

**Comment by linus-ha** [comment]
Interesting. I've got it working again on nextcloud 18.0.0 by activating the app "theming". I've accidentally disabled it.  
`sudo -u www-data php /var/www/nextcloud/occ app:enable theming`

**Comment by Terrox** [comment]
I have this problem now. Not sure why, my CSS files are full of what looks like gzip encoded data. changing theming doesn't do anything.

**Comment by TobjasR** [comment]
I'm having same problem now, however only with one of my two custom URLs (cloud.mydomain.tld and mycloud.dyndns.tld).
Have already tried all suggested solutions – no effect.
