### ISSUE TITLE
NC12 cant connect to database after mariadb upgrade from 10.1.25 to 10.1.30

### ISSUE THREAD

**Issue by snapper87** [nextcloud/server#7906]
### Steps to reproduce
1. Install Ubuntu Security Update for MariaDB 10.1.30 over 10.1.25
2. NC 12 breaks
3.

### Expected behaviour
After the upgrade of MariaDB, all should work fine. 

### Actual behaviour
503 Server error 
also 
in error.log 
PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused in /var/www/nextcloud/lib/private/DB/Connection.php:61
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(148): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doc in /var/www/nextcloud/lib/private/DB/Connection.php on line 61

### Workaround
Downgrade to MariaDB 10.1.25 from ubuntu repositories

### Server configuration

**Operating system**:
Ubuntu 17.10. Server
**Web server:**
Apache 2.4.29
**Database:**
MariaDB 10.1
**PHP version:**
7.1.13
**Nextcloud version:** (see Nextcloud admin page)
12.0.5 RC1

**Comment by deg0nz** [comment]
I have the exact same issue. I think this should be reopened if others have the issue too.

This is also true for MariaDB 10.2.12.

**Comment by snapper87** [comment]
I restarted mysql/mariadb services and restarted php7.1-fpm. After that, it started working again. Thats why I closed the ticket.
