### ISSUE TITLE
authentication problem through the browser!!

### ISSUE THREAD

**Issue by imal987** [nextcloud/server#7908]
Hello, 
I have an issue when I try to access nextcloud through the browser, it says "password is wrong". However in the command line (on the server) when I access the database through the same user and the same password it connects to the mariadb and works perfectly fine!!

If there is any possible way to solve this problem let me know !!
I am at your disposal for any further information !!
Here's the server configuration and the client configuration parameters: 
### Server configuration
**Operating system: redhat 7
**Web server: apache2
**Database: mariadb
**PHP version: php 7
**Nextcloud version:** nextcloud 12
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

### Client configuration
**Browser: Internet explorer / Firefox
**Operating system: Windows 7

Thanks.

**Comment by MorrisJobke** [comment]
> I have an issue when I try to access nextcloud through the browser, it says "password is wrong". However in the command line (on the server) when I access the database through the same user and the same password it connects to the mariadb and works perfectly fine!!

The nextcloud has a different user/password than your database server. Please use the password of nextcloud and not the one for the database.

If you forgot the password you can use the CLI tool to update the password: `./occ user:resetpassword USERNAME`

For more help, please ask in the forums: https://help.nextcloud.com
