### ISSUE TITLE
files_external notify

### ISSUE THREAD

**Issue by rillion** [nextcloud/server#7913]
### Steps to reproduce
1.
install nextcloud
2.
setup LDAP auth and external samba storage with session credentials
3.
setup file notify
sudo -u apache php occ files_external:notify --user 'xxx' --password 'xxxx' 1

### Expected behaviour
samba file change notification should start

### Actual behaviour
Error while running self-test, no changes detected                                        
  [Icewind\SMB\Exception\ConnectionException]  
  Connection not valid                         

From the samba server (windows) i can see that NC attempts to login with GUEST account no matter what i place as a user on the CLI. Only exeption is if i but user in format "xxx@xxx" in that case NC uses that username for login but login fails because there is no such user in AD

### Server configuration

**Operating system**:
Centos 7
**Web server:**
Apache/2.4.6
**Database:**
mariadb-server-5.5.56
**PHP version:**
PHP 7.0.27 
**Nextcloud version:** (see Nextcloud admin page)
12.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
Tarball
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external

</details>

**Are you using external storage, if yes which one:**

smb

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** 

ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

</details>

### Client configuration
**Browser:**
N/A
**Operating system:**
N/A
### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"RvXvccAr5464aVbKNUkM","level":3,"time":"2018-01-17T11:56:43+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"fwrite() expects parameter 1 to be resource, boolean given at \/var\/www\/html\/lib\/private\/Files\/Storage\/Common.php#200","userAgent":"--","version":"12.0.4.3"}
{"reqId":"RvXvccAr5464aVbKNUkM","level":3,"time":"2018-01-17T11:56:43+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"fclose() expects parameter 1 to be resource, boolean given at \/var\/www\/html\/lib\/private\/Files\/Storage\/Common.php#201","userAgent":"--","version":"12.0.4.3"}

</details>

**Comment by rullzer** [comment]
@icewind1991

**Comment by addaitrs** [comment]
I had to include the domain name with the username to get past this issue.

sudo -u www-data php /var/www/nextcloud/occ files_external:notify --user DOMAIN/username --password password 1

**Comment by blizzz** [comment]
@rillion does it help? ^

**Comment by rillion** [comment]
Hi,

Same as without the domain.
