### ISSUE TITLE
WebDAV WAF Reverseproxy

### ISSUE THREAD

**Issue by bebopt** [nextcloud/server#7922]
Hi,
I have installated a nextcloud on centos 7 with apache. When try to connect with the app from desktop or android i cant. The server is a DMZ zone and on top there is firewall that proxy the reqest. On top to firewall thereis a WAF but in this test it is disabled. 

### Actual behaviour
The webdav doesn't work with gui error: "Error transfering - server replied: Forbidden"
and on the log:
{"reqId":"Wl@Tot3eaQcSLyKBU29R9wAAAAE","level":0,"time":"2018-01-17T18:19:15+00:00","remoteAddr":"10.199.50.254","user":"--","app":"webdav","method":"GET","url":"\/nextcloud\/remote.php\/webdav\/","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Message\":\"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168}","userAgent":"curl\/7.57.0","version":"12.0.4.3"}

### Server configuration

**Operating system**: CentOS Linux release 7.4.1708 (Core) 

**Web server:** httpd-2.4.6-67.el7.centos.6.x86_64

**Database:**

**PHP version:** php71w-common-7.1.11-1.w7.x86_64

**Nextcloud version:** '12.0.4.3'

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Apache conf**
Alias /nextcloud "/var/www/html/nextcloud/"
 
<Directory /var/www/html/nextcloud/>
  Options +FollowSymlinks
  AllowOverride All

 <IfModule mod_dav.c>
  Dav off
 </IfModule>
 
 SetEnv HOME /var/www/html/nextcloud
 SetEnv HTTP_HOME /var/www/html/nextcloud
 
</Directory>

**Comment by MorrisJobke** [comment]
> No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured

It seems that the headers are filtered out somewhere. Please check that the PHP can read all the headers that are send. As this looks like a setup issue and not like a bug I will close this. Please as for help in the forums: https://help.nextcloud.com
