### ISSUE TITLE
The number of users and files in the monitor is incorrect

### ISSUE THREAD

**Issue by HandsomeBoby** [nextcloud/server#7926]
### Steps to reproduce
1.Install nextcloud normally, install monitor plug-in
2.View the number of users and the number of files is not displayed correctly

### Expected behaviour
Tell us what should happen
The number displayed is normal
### Actual behaviour
Tell us what happens instead
The number displayed is wrong
![image](https://user-images.githubusercontent.com/19202505/35079223-183886ca-fc41-11e7-9d07-223262b7ce52.png)
### Server configuration

**Operating system**:Ubuntu16.04

**Web server:**

**Database:**10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04

**PHP version:**PHP 7.0.22

**Nextcloud version:** (see Nextcloud admin page) 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Nextcloud.zip

**Signing status:**No
<details>
<summary>Signing status</summary>

### Client configuration
**Browser:**Firefox 57.0.4

**Comment by ziqingshi** [comment]
I have the same questions.

**Comment by HandsomeBoby** [comment]
@blizzz @MorrisJobke @icewind1991  Thanks.

**Comment by blizzz** [comment]
The file number is as according to the filecache entry. And this may include more files  than thus the user visible,  e.g. versions, avatars, files in trashbin, previews, but also app data like generated CSS files.
