### ISSUE TITLE
Deploy NextCloud Server on a Machine 

### ISSUE THREAD

**Issue by ibr123** [nextcloud/server#7928]
Hi,

is there any way or method to deploy the latest NextCloud  server code on a machine? not the normal installation from snap

Thanks

**Comment by GLLM** [comment]
Yes, it is possible, have you looked into the documentation ?
https://nextcloud.com/install/#instructions-server

This is not an issue for github  ;-)

**Comment by ibr123** [comment]
@GLLM I want to deploy from git as I want to run the latest code. The link you provided only allows me to download version 12.0.4

**Comment by nickvergessen** [comment]
You should not really run from git on a production instance.
But you could run the daily builds instead. That has test files and other stuff removed, which is available in git and could potentially harm your server.
