### ISSUE TITLE
missing/unthemed icon for sharepoint

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#7934]
I am adding 13 compatibility for the sharepoint app. Essentially, it registered a backend for files_external. Now, apparently something changed about generating the icons for the mounts? When I create a share point mount, the Files app will want to display ``apps/sharepoint/img/folder-sharepoint.svg``, which does not exist. Thus, no icon is shown, just whitespace:

![screenshot_20180118_135543](https://user-images.githubusercontent.com/2184312/35099162-47abac0a-fc57-11e7-89ee-909b11f85ac1.png)

For comparison, an external mount of a Local type will have ``apps/theming/img/core/filetypes/folder-external.svg`` as icon – themed.

When I copy over folder-external.svg from core to the sharepoint destination, this will be shown, but unthemed.

What's the correct way to have a themed icon displayed in this case? @nextcloud/theming @icewind1991

**Comment by skjnldsv** [comment]
@juliushaertl :)

**Comment by juliushaertl** [comment]
@blizzz The folder-sharepoint icon is currently hardcoded in the files_external app:
https://github.com/nextcloud/server/blob/master/apps/files_external/js/statusmanager.js#L563-L565

Removing it from there should just load the default external folder icon that is also themed. Not sure if there is a way to specify the icon from the sharepoint app side.

**Comment by blizzz** [comment]
@juliushaertl thx! That's actually old code, funny that it apperently only pops up now. I'll remove it, we're just gonna stick with the default icon.
