### ISSUE TITLE
13.0.0RC1 --> 13.0.0RC2 failed.

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#7947]
Don't have access to the server issue app right now so sorry for the little details in this post. Though I don't think it's needed as the issue is general.

Steps to reproduce:
1. Use the updater in GUI
2. Use the `occ command` to upgrade.
3. Notice this text: *The files of the app First run wizard (firstrunwizard), Gallery (gallery), Password policy (password_policy) were not replaced correctly. Make sure it is a version compatible with the server.*

![screenshot from 2018-01-18 19 37 02](https://user-images.githubusercontent.com/4511254/35115100-51a1c502-fc87-11e7-8946-609e69ecc002.png)

**Comment by MorrisJobke** [comment]
I will have a look.

**Comment by MorrisJobke** [comment]
> Use the updater in GUI

This could not be the case - 13.0.0 RC2 is not even served via the updater.

**Comment by enoch85** [comment]
Found the fault, it's 14.0.0 alpha. Hehe, lucky to have backups. :D

Sorry, I never use the GUI updater as I run with scripts.

**Comment by MorrisJobke** [comment]
> Found the fault, it's 14.0.0 alpha. Hehe, lucky to have backups. :D

Whoot?!? What did you do? Was this the daily channel? Otherwise I could not explain why this happens. The updater is usually rock solid.

**Comment by MorrisJobke** [comment]
> The updater is usually rock solid.

With updater I mean this one here:

![bildschirmfoto 2018-01-18 um 20 02 13](https://user-images.githubusercontent.com/245432/35116153-ab54739e-fc8a-11e7-8f37-3ec4253e9b1d.png)

**Comment by enoch85** [comment]
I did this: https://cloud.techandme.se :D

**Comment by MorrisJobke** [comment]
> I did this: https://cloud.techandme.se :D

We could add such stuff as well ;) Currently we only serve a white page, but that's how it is ;)
