### ISSUE TITLE
Webpack for server apps

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#7950]
Ref https://github.com/nextcloud/server/pull/7933#discussion_r162316115

@nextcloud/javascript How can I make sure this uses the version we load from the updatenotification/js/vue.js instead of the version from e.g. mail?

Or how do we handle this, when there are multiple different versions on one instance because of multiple apps?

**Comment by nickvergessen** [comment]
The thing with webpack is, that we either:
* commit the built artifacts => bad for diff/conflicting PRs/bisect
* dont commit the artifacts => bad for developers because default doesnt work without running npm and stuff

**Comment by tcitworld** [comment]
If the build process is simple enough (`make assets`), I don't mind running this before having a working NC dev installation.

**Comment by juliushaertl** [comment]
I would still prefer to have a common vue version for the server part. @ChristophWurst Is there any method using webpack to just bundle vue itself and have it exported at a different namespace, maybe something like OC.Lib.Vue ? So we have a shipped one that doesn't interfere with the ones that apps might ship. And we would need to run that build step only for bumping the vue version.

I also thought about using vue for the app settings page, which would be a huge improvement to have a clean javascript code there.

**Comment by juliushaertl** [comment]
> If the build process is simple enough (make assets), I don't mind running this before having a working NC dev installation.

We had that discussion with the SCSS introduction as well. Mostly against having a build process for js/scss in the server component: https://github.com/nextcloud/server/issues/1786

**Comment by tcitworld** [comment]
I've read this discussion before. However, building assets for a project is pretty common these days (and we do it for some apps), I don't think it should be regarded as a blocking point, even more if we can tell something like "assets are not build" in the dev env.

**Comment by nickvergessen** [comment]
@tcitworld well same for composer to get php dependencies.
Still until I had to run the mail app, I did not have npm installed. I'm a php developer and just want to make a simple php patch. What do I need npm for on my machine?
It's just one additional burden and exactly where this is coming from. Frontend people dont want to run composer, backend people dont want to run npm/bower/...

**Comment by MorrisJobke** [comment]
The problem I see with a shipped Vue: it is super hard to update and we keep an old version for ages, because a ton of code depends on it :/ (like your jQuery and jQuery migrate and jQuery UI)

**Comment by tcitworld** [comment]
@nickvergessen There's solutions like `mouf/nodejs-installer` (or the reverse) which can be wrapped inside a make command for instance.

I see the point here, but at least please tell me that shipping build files isn't an option ;)

**Comment by go2sh** [comment]
In the end you can't have all: No build dependencies, no global libraries and no checked in build artifacts.

I would vote adding build dependencies and use something like yarn, which massively speeds up the build process.

**Comment by splitt3r** [comment]
I would say Docker solves this problem 😀 The dev doesn´t care anymore if Nc doesn´t run on windows or if it needs npm / yarn / whatever. Ref #4355

**Comment by skjnldsv** [comment]
jancborchardt will love this discussion :) The previous decision iirc was not increase the level entry and not to imprégner

**Comment by go2sh** [comment]
I mean, you definitely could create some crazy php logic (like the js concat and scss pre stuff) to insert libraries into some local namespaces. Makes debugging harder, but you don't need a make function and a low entry level. But the performance of not precompiled components will hurt some time, especially if some thing like the settings get updated.

**Comment by rullzer** [comment]
The conclusion was to check in build artifacts. So closing this.
