### ISSUE TITLE
URL Redirect is wrong, can it be changed?

### ISSUE THREAD

**Issue by Dirk23** [nextcloud/server#7954]
### Steps to reproduce
1. open https://your.nextcloud.domain.com/ocs/v2.php/apps/serverinfo/api/v1/info and get redirected to Loginpage
2.  Redirection URL of Login Pages shows:  https://your.nextcloud.domain.com/index.php/login?redirect_url=/nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info
3.redirect_url=/nextcloud/ is the problem

### Expected behaviour
There should be:
redirect_url=/ocs/v2.php/apps/serverinfo/api/v1/info 

instead of:
redirect_url=/nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info

### Actual behaviour
There is:
redirect_url=/nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info
in the URL

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7

**Nextcloud version:** (see Nextcloud admin page) 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oco05ryxm706",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.2.58",
            "cloud.domain.com"
        ],
        "datadirectory": "\/var\/www\/nextcloud-data",
        "overwrite.cli.url": "https:\/\/cloud.domain.com",
        "overwritehost": "cloud.domain.com",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "integrity.check.disabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "info",
        "mail_domain": "domain.com",
        "maintenance": false,
        "loglevel": 2,
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.domain.com",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Comment by j-ed** [comment]
You should check your Nextcloud configuration and make sure that `'overwritewebroot'` is correctly set. In your case I would expect that it is set to `'/'`.

**Comment by Dirk23** [comment]
@j-ed did you read "Config report"? It is set to `'/'`

**Comment by Dirk23** [comment]
More Information:
I have a apache2 mod_proxy in front of Nextcloud server wich proxys cloud.domain.com to http://my.internal.ip/nextcloud/
Can that be the reason why i have /nextcloud in redirect URL?

**Comment by MorrisJobke** [comment]
> Can that be the reason why i have /nextcloud in redirect URL?

Yes. Very likely. Because we also check what the proxy tells us.

**Comment by Dirk23** [comment]
@MorrisJobke so how can i fix that?

**Comment by Dirk23** [comment]
Ok, so my fix was:
change /etc/apache2/sites-available/nextcloud.conf from
`Alias /nextcloud "/var/www/nextcloud/"` to Alias / "/var/www/nextcloud/"
and changed my proxy from
`ProxyPass / http://my.internal.ip/nextcloud` to `ProxyPass / http://my.internal.ip/`
Now Redirect URL is correct and i can monitor my Server.
