### ISSUE TITLE
13.0.0 RC2 nginx config gives "access forbidden by rule" GET /data/.ocdata?t=N

### ISSUE THREAD

**Issue by rubrik** [nextcloud/server#7966]
When I use the nginx config from https://docs.nextcloud.com/server/12/admin_manual/installation/nginx.html

I get this in my nginx error log:

`2018/01/19 19:20:20 [error] 1065#1065: *1371 access forbidden by rule, client: 1.2.3.4, server: localhost, request: "GET /data/.ocdata?t=121638484183 HTTP/1.0", host: "nextcloud.example.com"`

System setup in #7831 but with RC2

**Comment by juliushaertl** [comment]
That is by design. The file .ocdata is requested by the admin settings to check if acccess to the access to the data folder is denied.

**Comment by Ark74** [comment]
So what does it means?
If the .ocdata extist then deny access?

Did the upgrade left it there? Where did it came from in the first place?

**Comment by juliushaertl** [comment]
It is put there by Nextcloud and is used to check if the webserver config is working correctly.

**Comment by Ark74** [comment]
Thanks I realized it not much after I wrote the message.
I thought it was related to nginx issues i had with the configuration.

Thanks for the explanation.
Cheers!

**Comment by itCode666** [comment]
How exactly did you solve it
