### ISSUE TITLE
"Your apps" not fully alphabetical

### ISSUE THREAD

**Issue by rubrik** [nextcloud/server#7969]
If I go to Settings> "Your apps", the list is alphabetised, until I get to the end. Then I see this:
![atoz](https://user-images.githubusercontent.com/3472354/35167695-ba64de2e-fd56-11e7-8d46-afa09434d455.png)

The lists in Enabled apps and Disabled apps are alphabetised.

System setup in #7831 but with RC2

**Comment by juliushaertl** [comment]
The apps in the "Your apps" category are sorted by enabled/disabled. After that a alphabetical order is applied to that subgroups.

**Comment by rubrik** [comment]
Should/could the UI indicate that? It's not at all clear.
