### ISSUE TITLE
"Retention" app (official app) missing from store/enabled/disabled apps

### ISSUE THREAD

**Issue by rubrik** [nextcloud/server#7970]
The "Retention" app is not listed in the store, or in the enabled or disabled apps screens.

However it is listed under App Bundles> Enterprise Bundle where I can enable it.

Maybe other apps are missing too.

System setup in #7831 but with RC2

**Comment by juliushaertl** [comment]
> The "Retention" app is not listed in the store

Works fine here, maybe check the tools category? That is where it is located.

> or in the enabled or disabled apps screens.

It will only appear there after you have installed it from the store.

**Comment by rubrik** [comment]
I couldn't find the app in the store, either by looking under "R", or by searching for it - a search for "retention" showed one app, I think the tagging app, but not the retention app.

**Comment by juliushaertl** [comment]
@rubrik Please have another look at the tools category. The search currently will only work on the current view. In case the app is not installed, it will also not be found on the your apps section.

**Comment by rubrik** [comment]
![retention](https://user-images.githubusercontent.com/3472354/35351539-7869561e-0141-11e8-8e19-1e6902a045e1.png)

**Comment by juliushaertl** [comment]
Hm no idea then. Maybe @MorrisJobke or @nickvergessen ?

**Comment by nickvergessen** [comment]
The app is there: https://apps.nextcloud.com/apps/files_retention

But its currently only listed in rools:
https://apps.nextcloud.com/categories/tools

I can also find it there on an update to date Nextcloud 13 instance.

**Comment by rubrik** [comment]
I don't know why this issue was closed, the screenshot above is from Tools. I have an up-to-date instance, and you can see that it is missing.

**Comment by nickvergessen** [comment]
> ![bildschirmfoto von 2018-01-30 13-59-04](https://user-images.githubusercontent.com/213943/35568236-6c2f46de-05c8-11e8-9728-52de9f37a737.png)

For me the app is displayed directly after the registration app.

**Comment by rubrik** [comment]
Well, okay, so you can't reproduce it. Fair enough. Not a lot I can do here.
