### ISSUE TITLE
Integrity check for files_reader and audio_player fails in NC 13 RC2

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#7973]
I updated my test setup to NC 13 RC 2 and got an integrity check error:

> Technical information
> =====================
> The following list covers which files have failed the integrity check. Please read
> the previous linked documentation to learn more about the errors and how to fix
> them.
> 
> Results
> =======
> - audioplayer
> 	- EXCEPTION
> 		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
> 		- Certificate is not valid.
> - files_reader
> 	- EXCEPTION
> 		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
> 		- Certificate is not valid.

@Rello @xraMsamohT for the audioplayer.

## Server configuration detail

**Operating system:** Linux 4.4.98-2-pve #1 SMP PVE 4.4.98-101 (Mon, 18 Dec 2017 13:36:02 +0100) x86_64

**Webserver:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 10.0.32

**PHP version:** 7.0.27-1~dotdeb+8.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, igbinary, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 RC 2 - 13.0.0.11

**Updated from an older Nextcloud/ownCloud or fresh install:** update (test setup, started back in NC 11 or NC 12)

**Where did you install Nextcloud from:** manually

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_notifications: 1.0.1
 - apporder: 0.4.1
 - audioplayer: 2.2.3
 - bookmarks: 0.10.1
 - calendar: 1.5.7
 - circles: 0.13.6
 - comments: 1.3.0
 - contacts: 2.0.1
 - dav: 1.4.6
 - deck: 0.3.0
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_automatedtagging: 1.3.0
 - files_external: 1.4.1
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.2.0
 - files_reader: 1.1.4
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - githubmergetracker: 0.0.18
 - groupfolders: 1.1.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - news: 12.0.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - ransomware_protection: 1.1.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_email: 1.0.3
 - spreed: 3.0.1
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - twofactor_u2f: 1.5.1
 - updatenotification: 1.3.0
 - user_external: 0.4
 - user_usage_report: 1.0.1
 - weather: 1.5.1
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - mail
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/nextcloud",
    "htaccess.RewriteBase": "\/nextcloud",
    "dbtype": "mysql",
    "version": "13.0.0.11",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "{***REMOVED SENSITIVE VALUE***:993\/imap\/ssl}"
            ]
        }
    ],
    "updater.release.channel": "beta",
    "loglevel": 0,
    "log_rotate_size": 10485760,
    "maintenance": false,
    "allow_user_to_change_display_name": true,
    "theme": "",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpdebug": true
}
```
</details>

**Comment by xenithorb** [comment]
I can confirm that I'm seeing this exact error as well on 13.0.0 RC2 with: 

Linux 3.10.0-693.11.6.el7.x86_64
CentOS 7.4.1708
MariaDB 5.5.56 
PHP 7.1.13
nginx 1.13.8

**Comment by Rello** [comment]
I assume that this might be related to
`/appinfo/signature.json`

This file us used for the ownCloud Marketplace and for Nextcloud to sign an app - and in case of the AP, I want to avoid 2 archives.

As code signing is only required for OFFICIAL apps in NC, I relied on this for the oC app store + the archive signing for the NC app store.
...but this obviously does not work...

so again 2 archives

**Comment by xraMsamohT** [comment]
https://github.com/Yetangitu/owncloud-apps/issues/71

**Comment by tflidd** [comment]
Thanks for the quick fix @Rello

**Comment by Yetangitu** [comment]
OK, so that is what's driving this issue. This is... annoying, to say the least. I'll have to start using different archives for NC and OC as well then, much to my chagrin. Come on, folks, don't make it harder for developers to stay compatible with NC and OC.

**Comment by tflidd** [comment]
Allow me this naive question, wouldn't it be possible to have a signature.nc.json and signature.oc.json, or include both signatures in the same file? There must be a better solution for app developers, they contribute so much to the community, don't make their work harder than necessary!

**Comment by MorrisJobke** [comment]
> Allow me this naive question, wouldn't it be possible to have a signature.nc.json and signature.oc.json, or include both signatures in the same file? There must be a better solution for app developers, they contribute so much to the community, don't make their work harder than necessary!

Good idea, could you open a new ticket for that? Then we could check out how we fix this, but this should be possible. There are some side effect, but they could be fixed (like you need to ignore the other signature from the verify step).

**Comment by Rello** [comment]
without knowing the details - how should a fix look like?
both solutions provide the possibility for code signing and use the same process/occ and the same output file.

the only difference is, that the server is using other keys to sign the .crt file.
when not going for a completely different file, I assume it would be hard to recognise if a signature file was created with another key of has a integrity issue.

Adding both in one file would create a rather big file (every file is mentioned with its hash => *2) and both solutions would need to roll out this in a synchronised way.

In general I also hope that a workable solution can be found. 
Whats positive is, is that the occ-command remained the same until now so I can sign both packages out of one NC installation (by providing different key files only).

**Comment by tflidd** [comment]
Issue in files_reader was fixed (https://github.com/Yetangitu/owncloud-apps/issues/71).

Regarding the code signing, let's continue the discussion in this new topic:
https://github.com/nextcloud/server/issues/8001

Thanks to everybody.

**Comment by BernhardPosselt** [comment]
@Rello do not use code signing via occ but only sign the package. Or build two releases.

**Comment by Rello** [comment]
@BernhardPosselt OC depends on it - and I wanted to save the effort for 2 packages.
even NC Dev-Docu still explains it
https://docs.nextcloud.com/server/12/developer_manual/app/code_signing.html

anyway. two packages being created for both apps mentioned here...
