### ISSUE TITLE
Support for config files outside the installation

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#7976]
I would like to see support for config files outside the installation dir. I can manage this with an `include` or `include_once` directive, but I fear nextcloud will have problems, when it tries to write somethin to the `config.php`.

A single directive like 
`$CONFIG = array (
  'config_file' => '/path/config.php',
);` could offer this possibility.

**Comment by MorrisJobke** [comment]
I would say, that adding more complexity to this does not make our life as maintainers easier. If you want this, then there are multiple ways:

* create a file named `abc.config.php` inside of config/ and it will be loaded as well and merged with the existing config.php
* combined the first with a symlink you could accomplish your wanted behaviour
* use environment variables to inject configuration: see #3966 - basically `NC_datadir` to configure the data directory

I hope this solves the problems you are experiencing.

If not we are happy to look into it in further detail.
