### ISSUE TITLE
Add occ commands to pregenerate CSS and JS files

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#7984]
Just so it doesn't have to happen on demand.

As an added bonus we could add a '--rebuild' flag or something. So that if people somehow mess up their files in the appdata dir. That we just regenerate everything.

@skjnldsv does this make sense to you?

**Comment by skjnldsv** [comment]
So we could have a fix to give to users who have a broken setup?

**Comment by juliushaertl** [comment]
Makes sense to have, basically this is what is left in https://github.com/nextcloud/server/issues/6587.

**Comment by juliushaertl** [comment]
We should also fore rebuild during upgrade when implementing this.

**Comment by juliushaertl** [comment]
PR to clear the caches during update / occ maintenance:repair is in https://github.com/nextcloud/server/issues/7984

**Comment by rullzer** [comment]
So JS will be generated at build time for all the vue apps. That would cover most of it at some point.

**Comment by juliushaertl** [comment]
We could do that for core scss/js but we cannot easily determine what files apps use for their styles or scripts and need to do it at runtime. At least with our current API.

**Comment by MorrisJobke** [comment]
Most likely nothing for 14 -> moving to 15.

**Comment by DanScharon** [comment]
is this still being worked on? Integrating this into occ maintenance:repair is overkill for us as it puts the instance into maintenance mode when we just want to regenerate CSS and JS files

**Comment by MorrisJobke** [comment]
I guess nobody is working on this. We also will not have the dynamic SCSS generation on the instances itself that long anymore. It is planned to be moved into the build process once we can remove the IE compatibility, which we will deprecated in Nextcloud 20 and most likely 2-3 releases later. Then we can use CSS variables and this whole problem is not anymore.

**Comment by nickvergessen** [comment]
SCSS cacher has been removed and JS+CSS are compiled in the package now
