### ISSUE TITLE
Error downloading from shared link, shared by a user who no longer has access to the files

### ISSUE THREAD

**Issue by pgassmann** [nextcloud/server#7987]
### Steps to reproduce
1. Share a folder with a user, including resharing
2. This user shares a folder via link,
3. Revoke share with user,
4. Download using the shared link leads to an error.

### Expected behaviour
Two levels:
1. Shared link should no longer work when the user that created the link no longer has permissions on it.
2. If link is still working, the download should work without error.

### Actual behaviour

*Internal Server Error* instead of download.

The Error happens when the file_sharing app tries to create an activity for the download. It looks like it cannot access the user because he no longer has access to the folder.

https://github.com/nextcloud/server/blob/v12.0.4/apps/files_sharing/lib/Controller/ShareController.php#L566

![bildschirmfoto vom 2018-01-22 14-35-29](https://user-images.githubusercontent.com/460192/35223446-b0086e82-ff81-11e7-99c8-d0cba56c9911.png)

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1

**Nextcloud version:** 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** zipfile

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_reader: 1.1.5
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - flowupload: 0.0.6
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - impersonate: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - music: 0.5.5
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - ransomware_protection: 1.0.5
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - activitylog
  - documents
  - encryption
  - passman
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "files.b.org"
        ],
        "datadirectory": "\/var\/www\/nextcloud-data",
        "overwrite.cli.url": "http:\/\/files.b.org",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_domain": "files.b.org",
        "filelocking.enabled": true,
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "updater.release.channel": "production",
        "trusted_proxies": [
            "10.0.3.19"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** Yes, WebDAV

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** All

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
See screenshot
```
![bildschirmfoto vom 2018-01-22 14-35-29](https://user-images.githubusercontent.com/460192/35223446-b0086e82-ff81-11e7-99c8-d0cba56c9911.png)
</details>

**Comment by dirigit** [comment]
Hi,

in case user sharing something and loosing permission to access something all shared links to those resources created by "this" user should be dropped.

Reason to deny access of a user to a resource could be illegal content as well as malware, virus or whatever. In such a case further delivery caused by "this" user should be omitted in any case without any error message except "resource doesn't exist anymore" or something the like.

jm2c

cu

**Comment by MorrisJobke** [comment]
> Shared link should no longer work when the user that created the link no longer has permissions on it.

That was never implemented like that, right? @schiessle @rullzer 


And @rullzer as well for the exception.

**Comment by rullzer** [comment]
Well for shared links it is. As they hold no context. THey should be removed or at least invalidated.

I'll look into this.

**Comment by rullzer** [comment]
Ok  I just checked and it does not happen on master (aka, the link share is properly removed). I'll check 12 later

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
