### ISSUE TITLE
LDAP Groups Issue

### ISSUE THREAD

**Issue by Budwise** [nextcloud/server#7992]
--> 
### Steps to reproduce
1. Add LDAP Group
2. Verify that it can query users etc
3. Go to Users section and see if it populates

### Expected behaviour
All users should populate

### Actual behaviour
Once I get beyond 2 groups the 3rd one fails to populate.  I've created a test LDAP group as well with only a few users in it.  This causes the "Everyone" view to fail as well but the other groups populate and show users fine.

### Server configuration

**Operating system**: TechAndMe Appliance

**Web server:**TechAndMe Appliance

**Database:**TechAndMe Appliance

**PHP version:**TechAndMe Appliance

**Nextcloud version:** 13.0.0 RC 2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh to 13.0 beta3 and then updated

**Where did you install Nextcloud from:** the VM Appliance

**List of activated apps:**
<details>
<summary>Files automated tagging
impersonate
LDAP
Retention
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Enabled:
  - activity: 2.6.1
  - calendar: 1.5.7
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_automatedtagging: 1.3.0
  - files_pdfviewer: 1.2.0
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - impersonate: 1.0.2
  - issuetemplate: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - files_external
  - user_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system

    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "10.40.2.251",
            "nextcloud",
            "SITE REMOVED"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud\/",
        "dbtype": "mysql",
        "version": "13.0.0.11",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "log_rotate_size": "10485760",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/ncdata\/nextcloud.log",
        "logtimezone": "America\/Chicago",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}

</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
I don't think my company will allow this...
</details>

### Client configuration
**Browser:** Any

**Operating system:** Win 10

#### Web server error log
<details>
nothing pertaining to this in apache2 logs
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"C6yzvZYd70Fp8935vdAW","level":3,"time":"2018-01-22T09:10:24-06:00","remoteAddr":"REMOVED IP","user":"3A2E48B0-A86B-41AC-B9AA-4496F07060B5","app":"index","method":"GET","url":"\/settings\/users\/users?offset=0&limit=50&gid=NextCloud+Users&pattern=","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"2A1809A0-F4DB-434C-85DB-AAF43F1731FB is not a valid user anymore\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\User_LDAP\\\\User_LDAP->getHome('2A1809A0-F4DB-4...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(108): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/Proxy.php(150): OCA\\\\User_LDAP\\\\User_Proxy->callOnLastSeenOn('2A1809A0-F4DB-4...', 'getHome', Array, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(227): OCA\\\\User_LDAP\\\\Proxy->handleRequest('2A1809A0-F4DB-4...', 'getHome', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/User.php(282): OCA\\\\User_LDAP\\\\User_Proxy->getHome('2A1809A0-F4DB-4...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/UsersController.php(261): OC\\\\User\\\\User->getHome()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/UsersController.php(322): OC\\\\Settings\\\\Controller\\\\UsersController->formatUserForIndex(Object(OC\\\\User\\\\User))\\n#7 [internal function]: OC\\\\Settings\\\\Controller\\\\UsersController->index(0, 50, 'NextCloud Users', '', '')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'index')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'index')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(990): OC\\\\Route\\\\Router->match('\\\/settings\\\/users...')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php\",\"Line\":433}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.11"}
{"reqId":"daXo7sI5gZ0Is6szX3eO","level":3,"time":"2018-01-22T09:10:26-06:00","remoteAddr":"IP REMOVED","user":"3A2E48B0-A86B-41AC-B9AA-4496F07060B5","app":"index","method":"GET","url":"\/settings\/users\/users?offset=0&limit=50&gid=NextCloud+Users&pattern=","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"2A1809A0-F4DB-434C-85DB-AAF43F1731FB is not a valid user anymore\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\User_LDAP\\\\User_LDAP->getHome('2A1809A0-F4DB-4...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(108): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/Proxy.php(150): OCA\\\\User_LDAP\\\\User_Proxy->callOnLastSeenOn('2A1809A0-F4DB-4...', 'getHome', Array, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_Proxy.php(227): OCA\\\\User_LDAP\\\\Proxy->handleRequest('2A1809A0-F4DB-4...', 'getHome', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/User.php(282): OCA\\\\User_LDAP\\\\User_Proxy->getHome('2A1809A0-F4DB-4...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/UsersController.php(261): OC\\\\User\\\\User->getHome()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/UsersController.php(322): OC\\\\Settings\\\\Controller\\\\UsersController->formatUserForIndex(Object(OC\\\\User\\\\User))\\n#7 [internal function]: OC\\\\Settings\\\\Controller\\\\UsersController->index(0, 50, 'NextCloud Users', '', '')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'index')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'index')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(990): OC\\\\Route\\\\Router->match('\\\/settings\\\/users...')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php\",\"Line\":433}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.11"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

DevTools failed to parse SourceMap: https://SITE REMOVED/core/vendor/purify.min.js.map
core.js?v=d4122784-4:7 JQMIGRATE: Migrate is installed, version 1.4.0
merged-template-prepend.js?v=d4122784-4:2330 Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification
hide @ merged-template-prepend.js?v=d4122784-4:2330
initDeleteHandling @ users.js?v=d4122784-4:348
(anonymous) @ users.js?v=d4122784-4:712
j @ core.js?v=d4122784-4:2
fireWith @ core.js?v=d4122784-4:2
ready @ core.js?v=d4122784-4:2
I @ core.js?v=d4122784-4:2
merged-template-prepend.js?v=d4122784-4:2330 Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification
hide @ merged-template-prepend.js?v=d4122784-4:2330
initDeleteHandling @ groups.js?v=d4122784-4:286
(anonymous) @ groups.js?v=d4122784-4:333
j @ core.js?v=d4122784-4:2
fireWith @ core.js?v=d4122784-4:2
ready @ core.js?v=d4122784-4:2
I @ core.js?v=d4122784-4:2
core.js?v=d4122784-4:4 GET https://SITE REMOVED/settings/users/users?offset=0&limit=50&gid=&pattern= 500 (Internal Server Error)
send @ core.js?v=d4122784-4:4
ajax @ core.js?v=d4122784-4:4
n.(anonymous function) @ core.js?v=d4122784-4:4
update @ users.js?v=d4122784-4:388
(anonymous) @ users.js?v=d4122784-4:1206
j @ core.js?v=d4122784-4:2
fireWith @ core.js?v=d4122784-4:2
ready @ core.js?v=d4122784-4:2
I @ core.js?v=d4122784-4:2
DevTools failed to parse SourceMap: https://SITE REMOVED/core/vendor/purify.min.js.map
core.js?v=d4122784-4:4 GET https://SITE REMOVED/settings/users/users?offset=0&limit=50&gid=NextCloud+Users&pattern= 500 (Internal Server Error)
send @ core.js?v=d4122784-4:4
ajax @ core.js?v=d4122784-4:4
n.(anonymous function) @ core.js?v=d4122784-4:4
update @ users.js?v=d4122784-4:388
showGroup @ groups.js?v=d4122784-4:222
(anonymous) @ groups.js?v=d4122784-4:368
dispatch @ core.js?v=d4122784-4:3
r.handle @ core.js?v=d4122784-4:3
</details>

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by Budwise** [comment]
Oddly this eventually did populate but it took a while which is strange since it was less than 10 users.

**Comment by blizzz** [comment]
cache of 10 min life time
