### ISSUE TITLE
Remove »remember log in« and just remember automatically

### ISSUE THREAD

**Issue by My1** [nextcloud/server#8004]
On the Login page the layout it the following:

User, Password, Submit, Remember me.

I think this is a pretty weird layout especially as the most common one being first the user and password, then remember and AFTER THAT the submit button.

this gets majorly annoying when someone goes in with keyboard and, just out of muscle memory goes User, tab, password, tab, spacebar (to select remember me), enter, which instead makes the spacebar trigger the submit and not the checkbox, has happened to me already on multiple instances.

so it would be awesome to just swap those 2, or at least their tab order.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Hum, I'm not convinced about this. Any other opinions? :)

**Comment by tcitworld** [comment]
I feel like there's two use cases here : 
* when you want to select « remember me », so you'll go trigger the checkbox only once (at least on this device).
* when you don't want your session to be remembered so you'll always use the quick path to the submit button without going through the checkbox

Therefore it looks fine to me.

**Comment by My1** [comment]
I would have just thought that that would make it more consistant to what it's normally, it is kinda annoying when you do it only with the keyboard and go user-tab-password-tab-space-enter  (as one is usually usd to) you just hit the submit button, this might also be better accessibility wise, and would probably also fall under the Principle of least surprise/astonishment.

https://en.wikipedia.org/wiki/Principle_of_least_astonishment

not that the way that is now if totally bad or anything, I just think it would be better to switch.

**Comment by jancborchardt** [comment]
The design reasoning here:
- Visually it looks much better like it is now
- If you don’t want to remember log in, this layout is great
- When you remember log in, you will ideally never see this screen again anyway
- Also when you remember log in, clicking that will directly log you in so you don’t need to click the button again anyhow

**Comment by My1** [comment]
at least from a keyboarding aspect, this layout wouldnt change anything if you dont want to remember, just press enter after the password and you are in.

the annoyance is that at (while I dunno about the experience of others) that i way too often accidentially logged in without remembering, while I wanted to remember.

**Comment by skjnldsv** [comment]
@nextcloud/designers any counter-opinion?
Or should we close?

**Comment by MorrisJobke** [comment]
What about adding the tab index to be like 1 - name, 2 - password, 3 - remember me and 4 - submit to have the nice keyboard flow as well as the nice design=

**Comment by skjnldsv** [comment]
@MorrisJobke it could work! :)
I'll try today.

**Comment by My1** [comment]
@MorrisJobke sure an Idea (I did note that in the last line of the original post as an alternative way).

**Comment by jancborchardt** [comment]
@My1 as said, it's a one-time thing to click.

@MorrisJobke @skjnldsv it's not good practice to use tabindex different from the visual cues, so let's not do that.

------

The proper solution would be to just cut the setting for "remember log in" entirely and to remember log in by default. It can be forgotten when you "Log out" through the interface. (This is exactly how services like Facebook, Twitter, Github etc. do it. None of them has "remember log in" anymore.)

**Comment by skjnldsv** [comment]
I don't really have an opinion on this, so I'll let you guys choose. Le'ts close the ticket if a decision is made :)

**Comment by My1** [comment]
@jancborchardt I wouldnt compare NC to FB or twitter, Twitter and FB are just social networks, while nextcloud is a cloud storage service.

**Comment by MorrisJobke** [comment]
> The proper solution would be to just cut the setting for "remember log in" entirely and to remember log in by default. It can be forgotten when you "Log out" through the interface. (This is exactly how services like Facebook, Twitter, Github etc. do it. None of them has "remember log in" anymore.)

I would be fine by this.

**Comment by jancborchardt** [comment]
@My1 I don't see why we need to make a difference. The log in process needs to be easy everywhere. Also, to look at other cloud storage providers: Box.com also remembers by default, and Dropbox has the checkbox but checked by default.


@MorrisJobke cool! How can we make that happen? :)

**Comment by MorrisJobke** [comment]
> @MorrisJobke cool! How can we make that happen? :)

I'm already fully booked. So feel free to do it. :)

**Comment by jancborchardt** [comment]
Anyone of @nextcloud/javascript or @nextcloud/designers up for this? :)
