### ISSUE TITLE
Disabled users count for sub admins wrong

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#8009]
* having a group "A" with two users "user1" and "user2"
* having users "user3" and "user4" without a group
* disable "user1" and "user3"
* make "user2" the group admin of group "A"
* login as "user2"
* expected: disabled count is 1 (because only one of the users that are in the scope of the group admin "user2" is disabled)
* actual: disabled count is 2 (user1 and user3)

admin view:
![bildschirmfoto 2018-01-23 um 15 46 53](https://user-images.githubusercontent.com/245432/37347847-10f8a892-26d3-11e8-9a02-dc5f2a0058fa.png)

![bildschirmfoto 2018-01-23 um 15 46 55](https://user-images.githubusercontent.com/245432/35282248-4a7ca1e4-0055-11e8-971d-d2520bdd16f5.png)

subadmin view:
![bildschirmfoto 2018-01-23 um 15 46 57](https://user-images.githubusercontent.com/245432/35282249-4a97340a-0055-11e8-8f6d-882683008068.png)

cc @michag86 for noticing this

@nickvergessen @rullzer @danxuliu @blizzz for the user management 

May be related to #8008

**Comment by MorrisJobke** [comment]
@skjnldsv Could you have a look at this? It's still some kind of confusing :/ (just tested with latest master)

**Comment by rirochet93** [comment]
hey, care to check whats my problem is?
why i don't see any groups count? i means how many users in that group?
![image](https://user-images.githubusercontent.com/24819938/51426956-68914380-1c2c-11e9-8f2d-ca3f8a15b00b.png)
