### ISSUE TITLE
Duplicate admin group

### ISSUE THREAD

**Issue by allorder** [nextcloud/server#8010]
I created by mistake another admin group that I cannot delete.

### Steps to reproduce
1. Create admin group in lower case.
2.
3.

### Expected behaviour
Don't create it/error

### Actual behaviour
Double admin group 

### Server configuration

**Operating system**: Debian 9.03

**Web server:** apache 2.4.25

**Database:** mariadb 10.1.26

***Nextcloud:*** 12.0.4

*** Does someone have an easy fix ?

**Comment by juliushaertl** [comment]
How did you create that group? When I try to create a group named `admin`, I get a proper error that the group already exists.

**Comment by allorder** [comment]
Maybe it is with a capital A
