### ISSUE TITLE
Add an option to change or remove default new profile files

### ISSUE THREAD

**Issue by realies** [nextcloud/server#8012]
Currently default new profile files have to be changed or removed every time Nextcloud is updated. It would be great if those are kept intact if modified by the user.

**Comment by MorrisJobke** [comment]
@realies Could you explain this a bit more? What do you mean with that and on what version do you run Nextcloud?

**Comment by realies** [comment]
@MorrisJobke, referring to the files located in `nextcloud/core/skeleton` that are copied to new user profiles when they log in for the first time. Would be great if those are not reset to the default ones when updating Nextcloud. Running 12.0.5.

**Comment by MorrisJobke** [comment]
Ah - got it :)

Then just create an empty directory on your server and set the config option for the skeleton directory to this empty folder.

https://github.com/nextcloud/server/blob/master/config/config.sample.php#L245-L255
