### ISSUE TITLE
Migrate from OC  10.0.4 to NC 12.0.4 fails

### ISSUE THREAD

**Issue by tuxmaster** [nextcloud/server#8013]
I use the migration script from https://download.nextcloud.com/server/installer/migrator/index.php.
The version check will passed, but than the follow error message will be shown and the update will halt.

> Check for expected files
> The following extra files have been found:
>     etc
>     assets
>

**Comment by MorrisJobke** [comment]
Please delete the folder `assets` and then start the migrator again. Sorry for the inconvenience.

@jospoortvliet Maybe add this to the migration page.
