### ISSUE TITLE
Sort apps to be updated to the top

### ISSUE THREAD

**Issue by thomwiggers** [nextcloud/server#8014]
### Current behaviour

After I get a notification to update one of the installed apps, I then need to scroll through the list of installed apps and hunt down the one that has an update button. 

### Desired behaviour

It'd be nice if there's either a screen with all the apps that need to be updated or if they're sorted to the top of the list.

**Comment by juliushaertl** [comment]
There is a fix for this coming with NC13. The updates have a separate section now and when you click on the update notification, the new update view will open.
