### ISSUE TITLE
Why when I add  the LDAP service,the server is especially special slow??? 

### ISSUE THREAD

**Issue by ziqingshi** [nextcloud/server#8018]
Before I configure the LDAP service, the nextcloud server is fast,but when I add the LDAP service, the nextcloud server is especially special slow, why? The ldap users is just 62. After configured the ldap service, I login the app and web server, theconnection will become very very slowly,I can't understand why the server is especially special slow after configured the ldap service.

### Server configuration

**Operating system**:Ubuntu 16.04

**Database:10.0.33-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

**Nextcloud version:13.0.0.4

**Comment by ziqingshi** [comment]
@blizzz @MorrisJobke @icewind1991  Thanks .

**Comment by ziqingshi** [comment]
This problem occured just the ldap users.

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
Please discuss in the [forums](http://help.nextcloud.com), unless you can exclude a configuration issue of your instance. Then, we can reopen.
