### ISSUE TITLE
Aspect ratio of logo on 503 page like old share link

### ISSUE THREAD

**Issue by xf-** [nextcloud/server#8035]
### Steps to reproduce
1. create a share link
2. Modify URL for broken or old link
3. aspect ratio of you logo is

### Expected behaviour
Correct aspect ratio

### Actual behaviour
Stetched

### Server configuration

**Operating system**: Arch

**Web server:** nginx

**Database:** mariaDB

**PHP version:** 7.2

**Nextcloud version:** 13 RC2

**Updated from an older Nextcloud/ownCloud or fresh install:** older

**Where did you install Nextcloud from:** repo/aur

### Client configuration
**Browser:** FF 60 / Chromium (worse)

**Operating system:**  Arch

### Screenshot
Background image works great, but <img tag has no ratio and fills the container.
![image](https://user-images.githubusercontent.com/1295633/35344115-98f99bc4-012c-11e8-8fea-e8bc3b62d7bc.png)
Replaced image URL with Nextcloud Logo to show the issue
![image](https://user-images.githubusercontent.com/1295633/35344211-d7ebb9c0-012c-11e8-980b-f9eb7166c631.png)

(I used the search for 503 or ratio or logo and found no closed issue since RC2 or an open one)

**Comment by rullzer** [comment]
@skjnldsv @juliushaertl didn't one of you recently work on this?

**Comment by skjnldsv** [comment]
@rullzer not me!
@MorrisJobke ?

**Comment by juliushaertl** [comment]
Looks similar to https://github.com/nextcloud/server/issues/7575

I'll have a look.

**Comment by juliushaertl** [comment]
Ok, seems that only theming is affected.

**Comment by skjnldsv** [comment]
@juliushaertl is it fixed then?

**Comment by rullzer** [comment]
Yes in #8155
