### ISSUE TITLE
nodejs webdav-client can't connect  nexcloud webdav

### ISSUE THREAD

**Issue by m1cka** [nextcloud/server#8037]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
webdav client must scant users folder , and log content to console

### Actual behaviour
we canot connect to webdav from nodejs webdav client (using webdav, webdav-client ir js-owncloud client)
https://nextcloud.com/blog/using-webdav-fs-to-access-files-in-nextcloud/

### Server configuration

**Operating system**:
Centos7
**Web server:**
apache
**Database:**
mysql 5.7
**PHP version:**
PHP 7.1.11
**Nextcloud version:** (see Nextcloud admin page)
12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-12.0.3.zip
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.1
  - bruteforcesettings: 1.0.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - gallery: 17.0.0
  - impersonate: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ojsxc: 3.3.2
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - ransomware_protection: 1.0.5
  - serverinfo: 1.2.0
  - survey_client: 1.0.0
  - theming: 1.3.0
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - comments
  - encryption
  - federation
  - files_external
  - files_texteditor
  - files_videoplayer
  - firstrunwizard
  - flowupload
  - sharebymail
  - systemtags
  - user_external
  - user_ldap
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'passwordsalt' => '*****************',
  'secret' => '************************',
  'trusted_domains' =>
  array (
    0 => 'LOCALIP',
    1 => 'DOMAIN.ORG',
    2 => 'NODEJS_IP',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://IP/owncloud',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'DBNAME',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'USER',
  'dbpassword' => 'PASSWORD',
  'logtimezone' => ' "**curent**"',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'log_type' => 'owncloud',
  'logfile' => '/var/log/owncloud.log',
  'loglevel' => 1,
  'knowledgebaseenabled' => false,
  'session_lifetime' => 288000,
  'session_keepalive' => true,
  'cipher' => 'AES-256-CFB',
  'debug' => true,
  'enable_avatars' => true,
  'allow_user_to_change_display_name' => true,
  'instanceid' => 'oc7h9ruy14l8',
  'defaultapp' => 'files',
  'log_rotate_size' => 104857600,
  'activity_expire_days' => 100,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0.0,
  ),
);

apache config

<VirtualHost IP:80>
        <Directory /var/www/html/owncloud/>
#                Options -Indexes +FollowSymLinks -ExecCGI -Includes
                Options +FollowSymLinks
                AllowOverride All
                        <IfModule mod_dav.c>
                                Dav off
                        </IfModule>
                SetEnv HOME /var/www/html/owncloud
                SetEnv HTTP_HOME /var/www/html/owncloud
                LimitRequestBody 214748364
        </Directory>
        <IfModule mod_headers.c>
              Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
              Header always set Access-Control-Allow-Origin "http://nodejs_ip:3000"
#             Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
              Header always set Access-Control-Allow-Credentials "true"
</IfModule>

</details>
</VirtualHost>
**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>no</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
latest chrome,ie,firefox
**Operating system:**
windows
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
in debug mode, none


```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
![image](https://user-images.githubusercontent.com/5598270/35349359-5f5e1414-0143-11e8-97a3-16a9bcc6e874.png)

b) The network log
c) apache error
IP- - [23/Jan/2018:22:09:04 +0200] "OPTIONS /owncloud/remote.php/webdav/test/ HTTP/1.1" 401 414 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
IP - - [23/Jan/2018:22:09:04 +0200] "OPTIONS /owncloud/remote.php/webdav/test/ HTTP/1.1" 401 414 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
IP - - [23/Jan/2018:22:09:04 +0200] "OPTIONS /owncloud/ocs/v1.php/cloud/capabilities HTTP/1.1" 405 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
![image](https://user-images.githubusercontent.com/5598270/35349142-d48f4ec0-0142-11e8-9471-c639acca46b6.png)



```
</details>

**Comment by MorrisJobke** [comment]
This looks like you use the wrong credentials because you get 401 responses (Unauthorized).

For further questions please check out the forums: https://help.nextcloud.com
