### ISSUE TITLE
Rewrite webcal:// to webcals:// if TLS is used

### ISSUE THREAD

**Issue by Somebodyisnobody** [nextcloud/server#8039]
### Steps to reproduce
1. Create and share a calendar
2. Open shared calendar
3. Click right on "subscribe" to copy the link of the button and paste it somewhere to take a look on it.

### Expected behaviour
Nextcloud applies PFS to the webcal-link and forms it into an webcals-link

### Actual behaviour
Link is still webcal://

**I didn't found a RFC of the IETF for webcal but all of my clients does support the webcals://-sheme**

### Server configuration
**Web server: nginx**

**Database: mysql**

**PHP version: 7.x**

**Nextcloud version: 12.0.4** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install: older Nextcloud with Webupdater, imported from OC a long time ago**

**Where did you install Nextcloud from: download tar, unzip and put into /var/www/**

**Are you using external storage, if yes which one: N/A**

**Are you using encryption: no**

**Are you using an external user-backend, if yes which one: standard webdav, spreed**

### Client configuration
**Browser: Firefox 57.0.4**

**Operating system:Win10.1703**

**Comment by rullzer** [comment]
@georgehrke

**Comment by georgehrke** [comment]
@Somebodyisnobody please reopen in https://github.com/nextcloud/calendar. This doesnt belong into server repo.

Furthermore I've never seen `webcals` anywhere on the internet. When creating the issue in the calendar repo, please link some spec specifying webcals
