### ISSUE TITLE
Validation error in vCard: REV MUST NOT appear more than once in a VCARD component

### ISSUE THREAD

**Issue by kiplingw** [nextcloud/server#8040]
Hey everyone,

I am having some difficulties synchronizing my contacts. I am using a NextCloud 12.0.5 installation and an Android phone running the DAVdroid 1.9.10-ose and Nextcloud dev 20180121 clients. I have opened tickets upstream with both DAVdroid and NextCloud because it's not obvious to me where the problem is.

When I attempt to synchronize my contacts on my handset, either manually or automatically, the DAVdroid client emits the enclosed debugging log. The corresponding NextCloud server side event log for the same synchronization I've also enclosed.

I'm aware others have raised this issue before, but my understanding was that it was already patched a while ago. All three of the server installation and both clients for the handset have since been upgraded, so any help is appreciated.
[DAVdroid.txt](https://github.com/nextcloud/server/files/1661744/DAVdroid.txt)
[NextCloud.txt](https://github.com/nextcloud/server/files/1661745/NextCloud.txt)

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by georgehrke** [comment]
I would definitely say that this is an issue in DavDroid / Android.

Checking the DAVdroid.txt:
```
BEGIN:VCARD↵
VERSION:4.0↵
PRODID:+//IDN bitfire.at//DAVdroid/1.9.10-ose ez-vcard/0.10.3↵
REV;VALUE=timestamp:2017-08-31T02:30:25Z(2)↵
X-EVOLUTION-FILE-AS:LastName\, FirstName↵
X-MOZILLA-HTML:FALSE↵
X-EVOLUTION-MANAGER:↵
X-EVOLUTION-ASSISTANT:↵
X-EVOLUTION-SPOUSE:↵
X-EVOLUTION-BLOG-URL:↵
X-EVOLUTION-VIDEO-URL:↵
davdroid1.X-ABLabel:Other↵
CALURI:↵
FBURL:↵
UID:pas-id-4CF2E9D800000083↵
FN:Dr. FirstName LastName↵
N:LastName;FirstName;;Dr.;↵
TEL;TYPE=fax,work:111-111-1111↵
TEL;TYPE=work:111-111-1111↵
TEL;TYPE=work;PREF=1:111-111-1111↵
TEL;TYPE=cell:111-111-1111↵
EMAIL;TYPE=home:some_email@address.com↵
davdroid1.EMAIL;TYPE=x-other:another_email@address.com↵
ADR;TYPE=work;LABEL="Some address;Canada↵
NOTE:Some notes.↵
URL:↵
REV:20180124T183417Z↵
END:VCARD↵
```

There is a `REV` in line 4 and another `REV` in the second to last line.

Checking RFC 6350, the vcard standard, it says the following about `REV` in [section 6.7.4](
https://tools.ietf.org/html/rfc6350#section-6.7.4):

`Cardinality:  *1` => `Exactly one instance per vCard MAY be present. `

So Nextcloud is just rejecting an invalid VCard.
