### ISSUE TITLE
Update 12.04 to 12.5 breaks .htaccess

### ISSUE THREAD

**Issue by dirigit** [nextcloud/server#8046]
Thought it has been fixed with 12.0.4 but: No. Long time known issue returns back with 12.0.5 (sorry for typo in subject)!

.htaccess is broken when NC is located in a sub directory.

Updating via webupdater breaks whole installation (nothing works).

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
Could you please share some more information about what's broken?

**Comment by dirigit** [comment]
rewritebase is missing again. therefore no redirect works. currently i'm uploading a fresh download from website to see if it's possible to fix something manually ...

**Comment by MorrisJobke** [comment]
Could you check if this is fixed by running `occ maintenance:update:htaccess`?

**Comment by dirigit** [comment]
I will do it after download is complete. I'm in a hotel currently and internet connection is not the fastest one (read: slow) ...

**Comment by dirigit** [comment]
ok, due to limited time I startet a test.

htaccess is modified running command mentioned above. result:
Internal Server Error

The server encountered an internal error and was unable to complete your request.

Sorry, don't have the time to perform further tests - it's meeting time.  Nevertheless it's very sad a minor update breaks a running system that hard. This is something which should never happen. I'll retry to install a downgrade (12.0.4) later. Hope it works ...

**Comment by dirigit** [comment]
ok, had a little time left:
occ deleted rewritebase in .htaccess again and several some additional errors in .htaccess (error 500). There are errors in nextcloud.log as well related to remote.php and sabre.

PHP version being active is 7.0.27. I'm not sure what happens when switching to 7.1 ...

Downgraded files except version.php to 12.0.4. Site is working again with wrong version information (12.0.5) because downgrade is not supported even for minor updates. Backend tells "something is wrong" which is correct because of faking wrong sub version.

When time permits I'll try upgrading again.

**Comment by HungryFeline** [comment]
If occ isn't putting a rewritebase into your htaccess, you probably haven't set one in your config. Have you tried adding `'htaccess.RewriteBase' => '/subfolder',` to your `config/config.php`?

If there's an internal server error, there should be a description in your webserver's or php's log. Try finding and posting that, please. (That should've been the first place to look for hints before doing all that time-consuming stuff you already did.)

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
