### ISSUE TITLE
Call to a member function instanceOfStorage() on null  in nextcloud/apps/files_sharing/lib/Cache.php:80

### ISSUE THREAD

**Issue by weaselp** [nextcloud/server#8047]
Hi!

I have nextcloud 12.0.5, with external (local) storages, one per user.

Since the upgrade from 12.0.4 I noticed that if
 o user A shared a file or directory in A's external-storage with user B,
   *AND*
 o user B shared a file or directory in B's external-storage with user A,
then upon visiting https://cl.EXAMPLE.org/apps/files/, user A gets a
  "This directory is unavailable, please check the logs or contact the administrator"
and no files or mounts or anything are listed.

The shares show up correctly in the "shared with others" and "shared with you"
views, and the list of external storages also contains the external storage.

The view works if either A does not share a file with B or if B does not share
a file with A.  It only breaks if (different) files are shared in both
directions.  Sharing from the not-external storage does not cause this.

The nextcloud.log below has a "Call to a member function instanceOfStorage() on null"
Exception in nextcloud/apps/files_sharing/lib/Cache.php:80.  (See full (parsed) backtrace below.)

I'd expect that view not to break.

**Operating system**:
 Debian stretch

**Web server:**
 Apache 2.4

**Database:**
 sqlite

**PHP version:**
 7.0.x

**Nextcloud version:** (see Nextcloud admin page)
 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
 updated from 12.0.4 which was updated from ...

**Signing status:**
<details>
<summary>Signing status: No errors found</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activity
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cl.EXAMPLE.org"
        ],
        "datadirectory": "\/srv\/www\/cl.EXAMPLE.org\/nextcloud-data",
        "overwrite.cli.url": "https:\/\/cl.EXAMPLE.org",
        "dbtype": "sqlite3",
        "version": "12.0.5.3",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "XXX",
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "sendmail",
        "mail_from_address": "nextcloud",
        "mail_domain": "EXAMPLE.org",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
```
</details>

**Are you using external storage, if yes which one:**
local

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
 firefox or chrome

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

parsed:
```
{
  "reqId": "XXXX",
  "level": 3,
  "time": "2018-01-25T15:16:43+00:00",
  "remoteAddr": "XXXX",
  "user": "weasel",
  "app": "remote",
  "method": "PROPFIND",
  "url": "/remote.php/webdav/",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
  "version": "12.0.5.3"
}
message: Exception
{
  "Exception": "Error",
  "Message": "Call to a member function instanceOfStorage() on null",
  "Code": 0,
  "File": "/srv/www/cl.EXAMPLE.org/nextcloud/apps/files_sharing/lib/Cache.php",
  "Line": 80
}
Trace:
#0 /srv/www/cl.EXAMPLE.org/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php(69): OCA\Files_Sharing\Cache->getRoot()
#1 /srv/www/cl.EXAMPLE.org/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php(314): OC\Files\Cache\Wrapper\CacheJail->getJailedPath(NULL)
#2 /srv/www/cl.EXAMPLE.org/nextcloud/lib/private/Files/View.php(1724): OC\Files\Cache\Wrapper\CacheJail->getPathById(14186)
#3 /srv/www/cl.EXAMPLE.org/nextcloud/apps/files_sharing/lib/SharedStorage.php(118): OC\Files\View->getPath(14186)
#4 /srv/www/cl.EXAMPLE.org/nextcloud/apps/files_sharing/lib/SharedStorage.php(458): OCA\Files_Sharing\SharedStorage->init()
#5 [internal function]: OCA\Files_Sharing\SharedStorage->getSourceStorage()
#6 /srv/www/cl.EXAMPLE.org/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(501): call_user_func_array(Array, Array)
#7 /srv/www/cl.EXAMPLE.org/nextcloud/apps/files_sharing/lib/Cache.php(91): OC\Files\Storage\Wrapper\Wrapper->__call('getSourceStorag...', Array)
#8 /srv/www/cl.EXAMPLE.org/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php(313): OCA\Files_Sharing\Cache->getCache()
#9 /srv/www/cl.EXAMPLE.org/nextcloud/lib/private/Files/View.php(1724): OC\Files\Cache\Wrapper\CacheJail->getPathById(14185)
#10 /srv/www/cl.EXAMPLE.org/nextcloud/apps/files_sharing/lib/SharedStorage.php(118): OC\Files\View->getPath(14185)
#11 /srv/www/cl.EXAMPLE.org/nextcloud/apps/files_sharing/lib/SharedStorage.php(463): OCA\Files_Sharing\SharedStorage->init()
#12 /srv/www/cl.EXAMPLE.org/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(490): OCA\Files_Sharing\SharedStorage->getWrapperStorage()
#13 /srv/www/cl.EXAMPLE.org/nextcloud/apps/files_sharing/lib/SharedStorage.php(156): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('\\OCP\\Files\\IHom...')
#14 /srv/www/cl.EXAMPLE.org/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(490): OCA\Files_Sharing\SharedStorage->instanceOfStorage('\\OCP\\Files\\IHom...')
#15 /srv/www/cl.EXAMPLE.org/nextcloud/lib/private/Files/FileInfo.php(310): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('\\OCP\\Files\\IHom...')
#16 /srv/www/cl.EXAMPLE.org/nextcloud/apps/dav/lib/Connector/Sabre/Node.php(299): OC\Files\FileInfo->isMounted()
#17 /srv/www/cl.EXAMPLE.org/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php(312): OCA\DAV\Connector\Sabre\Node->getDavPermissions()
#18 /srv/www/cl.EXAMPLE.org/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php(98): OCA\DAV\Connector\Sabre\FilesPlugin->OCA\DAV\Connector\Sabre\{closure}(*** sensitive parameters replaced ***)
#19 /srv/www/cl.EXAMPLE.org/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php(318): Sabre\DAV\PropFind->handle('{http://ownclou...', Object(Closure))
#20 [internal function]: OCA\DAV\Connector\Sabre\FilesPlugin->handleGetProperties(Object(Sabre\DAV\PropFind), Object(OCA\DAV\Connector\Sabre\Directory))
#21 /srv/www/cl.EXAMPLE.org/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#22 /srv/www/cl.EXAMPLE.org/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(1059): Sabre\Event\EventEmitter->emit('propFind', Array)
#23 /srv/www/cl.EXAMPLE.org/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(981): Sabre\DAV\Server->getPropertiesByNode(Object(Sabre\DAV\PropFind), Object(OCA\DAV\Connector\Sabre\Directory))
#24 /srv/www/cl.EXAMPLE.org/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(1666): Sabre\DAV\Server->getPropertiesIteratorForPath('', Array, 1)
#25 /srv/www/cl.EXAMPLE.org/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(355): Sabre\DAV\Server->generateMultiStatus(Object(Generator), false)
#26 [internal function]: Sabre\DAV\CorePlugin->httpPropFind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#27 /srv/www/cl.EXAMPLE.org/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#28 /srv/www/cl.EXAMPLE.org/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:PROPFIND', Array)
#29 /srv/www/cl.EXAMPLE.org/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#30 /srv/www/cl.EXAMPLE.org/nextcloud/apps/dav/appinfo/v1/webdav.php(76): Sabre\DAV\Server->exec()
#31 /srv/www/cl.EXAMPLE.org/nextcloud/remote.php(162): require_once('/srv/www/cl.EXA...')
#32 {main}

```
</details>

**Comment by weaselp** [comment]
This makes it not break for me, but I have no idea if it's actually Right:

```
--- a/apps/files_sharing/lib/Cache.php
+++ b/apps/files_sharing/lib/Cache.php
@@ -78,7 +78,7 @@ class Cache extends CacheJail {
                        // in the case where a folder is shared from a Jail we need to ensure that the share Jail
                        // has it's root set relative to the source Jail
                        $currentStorage = $this->storage->getSourceStorage();
-                       if ($currentStorage->instanceOfStorage(Jail::class)) {
+                       if ($currentStorage && $currentStorage->instanceOfStorage(Jail::class)) {
                                /** @var Jail $currentStorage */
                                $absoluteRoot = $currentStorage->getJailedPath($absoluteRoot);
                        }
```

**Comment by bl4ckOut** [comment]
Got the same problem after Upgrade from 12.0.4 to 12.0.5 stable.:
"This directory is unavailable, please check the logs or contact the administrator"
Sync also didn't work anymore.

<details>
<summary> Log: </summary>
{"reqId":"WUw4ZCtdzcBpwFPVbO4z","level":3,"time":"2018-01-26T01:06:39+01:00","remoteAddr":"91.58.113.217","user":"bl4ckOut","app":"remote","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function instanceOfStorage() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Wrapper\\\/CacheJail.php(69): OCA\\\\Files_Sharing\\\\Cache->getRoot()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Wrapper\\\/CacheJail.php(314): OC\\\\Files\\\\Cache\\\\Wrapper\\\\CacheJail->getJailedPath(NULL)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1724): OC\\\\Files\\\\Cache\\\\Wrapper\\\\CacheJail->getPathById(124020)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedStorage.php(118): OC\\\\Files\\\\View->getPath(124020)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedStorage.php(458): OCA\\\\Files_Sharing\\\\SharedStorage->init()\\n#5 [internal function]: OCA\\\\Files_Sharing\\\\SharedStorage->getSourceStorage()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(501): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/Cache.php(91): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->__call('getSourceStorag...', Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Wrapper\\\/CacheJail.php(313): OCA\\\\Files_Sharing\\\\Cache->getCache()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1724): OC\\\\Files\\\\Cache\\\\Wrapper\\\\CacheJail->getPathById(103607)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedStorage.php(118): OC\\\\Files\\\\View->getPath(103607)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedStorage.php(463): OCA\\\\Files_Sharing\\\\SharedStorage->init()\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(490): OCA\\\\Files_Sharing\\\\SharedStorage->getWrapperStorage()\\n#13 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedStorage.php(156): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->instanceOfStorage('\\\\\\\\OCP\\\\\\\\Files\\\\\\\\IHom...')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(490): OCA\\\\Files_Sharing\\\\SharedStorage->instanceOfStorage('\\\\\\\\OCP\\\\\\\\Files\\\\\\\\IHom...')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/FileInfo.php(310): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->instanceOfStorage('\\\\\\\\OCP\\\\\\\\Files\\\\\\\\IHom...')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Node.php(299): OC\\\\Files\\\\FileInfo->isMounted()\\n#17 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/FilesPlugin.php(312): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Node->getDavPermissions()\\n#18 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropFind.php(98): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\FilesPlugin->OCA\\\\DAV\\\\Connector\\\\Sabre\\\\{closure}(*** sensitive parameters replaced ***)\\n#19 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/FilesPlugin.php(318): Sabre\\\\DAV\\\\PropFind->handle('{http:\\\/\\\/ownclou...', Object(Closure))\\n#20 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\FilesPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#21 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#22 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1059): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#23 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(981): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#24 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1666): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('', Array, 1)\\n#25 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#26 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#27 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#28 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#29 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#30 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#31 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#32 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/Cache.php\",\"Line\":80}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.5.3"}
{"reqId":"dOMJ07VNGN1hqOwDnDFD","level":4,"time":"2018-01-26T01:07:02+01:00","remoteAddr":"91.58.113.217","user":"bl4ckOut","app":"webdav","method":"PROPFIND","url":"\/remote.php\/dav\/files\/bl4ckOut\/","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"Error: Call to a member function instanceOfStorage() on null\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(*** sensitive parameters replaced ***)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/remote.php(70): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/remote.php(167): handleException(Object(Error))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/remote.php\",\"Line\":68}","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.5.3"}
</details>

@weaselp 
Your commit fixed it for me too.

**Comment by BlauerHunger** [comment]
I had the same problem after upgrade from 12.0.4 to 12.0.5 stable, the fix from @weaselp fixed it for me. 
I'm using the external users backend ldap. External storages worked without this fix, but I had to enter the URL directly. 
Now (with the patch) everything works as expected.

**Comment by MorrisJobke** [comment]
@nextcloud/sharing @icewind1991 @rullzer @nickvergessen Mind to have a look at the problem and the fix?

**Comment by rullzer** [comment]
I might have a fix in #8160. Please test if you can. It is against master but the cahnge is the same on 12 and 13 if I'm not mistaken.

**Comment by viking-frank** [comment]
Hey,
Had the same Problem, also using ldap authentication. The patch from @weaselp fixed it for me. 
(Also nextcloud 12.0.5)
Thanks a lot guys.

**Comment by spantaleev** [comment]
Just experienced this today using the `nextcloud:13.0.0` Docker image.

I also have 2 users - both using Local external storage and both sharing files with one another.
Previously only user A was sharing with user B and all was fine. But once user B started sharing with user A, the `Call to a member function instanceOfStorage() on null` problem happened.

It seems like #8160 doesn't fix it?

Applying @weaselp's patch above fixes the problem for me.

**Comment by rullzer** [comment]
@spantaleev did you try the patch in #8160 as that is not yet released.

**Comment by icewind1991** [comment]
Additionally @weaselp's patch only hides the symptom without actually fixing the issue

**Comment by spantaleev** [comment]
@rullzer, ahh.. I thought #8160 had made it into 13.0.0 judging by the date it was created.
I tried that patch by itself (without the other one) and I can confirm that it solves the problem for me.

**Comment by florianbeer** [comment]
I just upgraded to 13.0.0.14 and #8160 also fixed my installation. Thank you!

**Comment by PichlAlex** [comment]
this also worked for me.

Symptom: Errors in log "Error: Call to a member function instanceOfStorage() on null" when a User logged in with User A shares User B and back

#8160 also fixed my problem
