### ISSUE TITLE
Wrong icon after renaming an external mountpoint

### ISSUE THREAD

**Issue by AND51** [nextcloud/server#8049]
### Steps to reproduce
1. Have an external storage successfully mounted (named "Mega Cloud").
![image](https://user-images.githubusercontent.com/26226303/35402212-285d6c94-01fc-11e8-97fc-0cbbf0553ebd.png)
2. Folder has storage-icon (square with arrow pointing to north east).
3. Rename via three-dots-menu, then "rename" and name it e. g. "Giga Cloud".
4. Renaming is successful.

### Expected behaviour
Icon stays the same (square with the arrow), indicating that this is an external storage.

### Actual behaviour
After renaming icon becomes the same icon as for standard folders.
![image](https://user-images.githubusercontent.com/26226303/35402229-32bcc2f2-01fc-11e8-90e2-7a0287167a68.png)

### Server configuration

**Operating system**: Ubuntu 16.04.3

**Web server:** Apache 2.4.18

**PHP version:** PHP 7.0 

**Nextcloud version:** 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 12.0.4

**Where did you install Nextcloud from:** Installed via tar.gz, updated regularly via updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - caniupdate: 0.1.2
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.1
  - deck: 0.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_clipboard: 0.6.5
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - impersonate: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - passman: 2.1.4
  - password_policy: 1.2.2
  - previewgenerator: 1.0.9
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.40
  - serverinfo: 1.2.0
  - socialsharing_email: 1.0.3
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - bookmarks
  - encryption
  - files_automatedtagging
  - sharebymail
  - spreed
  - spreedme
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Are you using external storage, if yes which one:** WebDAV

**Are you using encryption:** no

### Client configuration
**Browser:** Vivaldi 1.13.1008.44 (Stable channel) (64-Bit) && Firefox 58.0 64-bit

**Operating system:** Linux Mint 18.2

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"WmoOMn8AAQEAAF3fiCcAAAB8","level":1,"time":"2018-01-25T18:04:50+01:00","remoteAddr":"99.99.99.99","user":"sensitive_data","app":"admin_audit","method":"POST","url":"\/login","message":"Login successful: \"sensitive_data\"","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
{"reqId":"WmoOXH8AAQEAAF3e4f0AAAAl","level":1,"time":"2018-01-25T18:05:32+01:00","remoteAddr":"99.99.99.99","user":"sensitive_data","app":"admin_audit","method":"MOVE","url":"\/remote.php\/webdav\/Mega%20Cloud","message":"File renamed: \"\/Mega Cloud\" to \"\/Giga Cloud\"","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
```
</details>

**Comment by AND51** [comment]
Forgot to mention this: if you reload the page, then the icon is correct again.

**Comment by MorrisJobke** [comment]
Will be gone after we overhaul the file listing which is planned for 17 or 18. Until then that's how it is for now as it's only a temporary UI glitch with very little impact. Thanks anyways for bringing this up.
