### ISSUE TITLE
When I choose to delete all files in external storage, some file prompts cannot be deleted, why?

### ISSUE THREAD

**Issue by supermanlinux** [nextcloud/server#8065]
When I choose to delete all files in locla external storage, some file  cannot be deleted, and then I check the log.I found that  undeleted files have been locked.But sometimes it seems ok,Most of the time it  happened.I can understand why ?
### Steps to reproduce
1.Click into the external storages
2.select all files and delete.

### Expected behaviour
All files could be deleted.

### Actual behaviour
Some files can't deleted.

### Server configuration

**Operating system**:Ubuntu 16.04.1 LTS

**Web server:   Nextcloud 12.0.0

**Database:10.0.31-MariaDB-0ubuntu0.16.04.2

**PHP version:PHP 7.0.22

**Nextcloud version:Nextcloud 12.0.0

![delete](https://user-images.githubusercontent.com/34739130/35424824-46c3ea6a-0291-11e8-931d-ed04aa2348fc.png)
![delete2](https://user-images.githubusercontent.com/34739130/35424827-4f4fd0b8-0291-11e8-86ba-fb09ae17d571.png)
![delete3](https://user-images.githubusercontent.com/34739130/35424832-563a5bbe-0291-11e8-8a41-64065e335850.png)

**Comment by ziqingshi** [comment]
@blizzz @icewind1991 @MorrisJobke  Thanks.

**Comment by ziqingshi** [comment]
@blizzz @icewind1991 @MorrisJobke I think it has something to do with the dav folder.I check the nextcloud.log.The content that appears is related to the dav.I find that the delete function is the same as anywhere else.But why in local extrenal storages folder files sometimes can't delete???Thanks for help.
![image](https://user-images.githubusercontent.com/34739130/35480000-92cec47a-043f-11e8-9d50-e126e7d7f552.png)

**Comment by blizzz** [comment]
anything in the server log?

**Comment by ziqingshi** [comment]
@blizzz I choose to select all files in local external storage,then  I click the delete button, some files cannot be deleted,I check the server log.Not deleted files is locked,the server log is :user":"admin","app":"webdav","method":"DELETE","url":"\/remote.php\/webdav\/extrenal%20storage\/de_DE.js","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"extrenal storage\\\/**de_DE.js**\\\" **is locked**\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\**FileLocked**\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/coral-server\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179):
![image](https://user-images.githubusercontent.com/34739130/35513130-fe2b5046-053c-11e8-9bfc-2789583338c1.png)
My nextcloud version is **12.0.0.0.**

**Comment by ziqingshi** [comment]
@blizzz @icewind1991 @MorrisJobke Thanks.

**Comment by ziqingshi** [comment]
@blizzz @icewind1991 @MorrisJobke @rullzer Today I added 'filelocking.enabled' => false into config.php,then I selected all files in local external storages folder,click delete button,all files deleted.Is this a dangerous operation?Or do you have other solutions? Thanks for your answer.

**Comment by ziqingshi** [comment]
@blizzz @icewind1991 @MorrisJobke @rullzer Thanks.

**Comment by MorrisJobke** [comment]
@ziqingshi Please stop pinging us. This is a community driven project and each of us has stuff to do and does the stuff which is on it's priority list at the top. Once we have the time we will write here. If you need timely answer maybe think about a support subscription.

**Comment by MorrisJobke** [comment]
Looks like #8723 - let's continue there
