### ISSUE TITLE
Squeeze size of preview images

### ISSUE THREAD

**Issue by AND51** [nextcloud/server#8080]
Hi,

my idea is to reduce the size of the preview images in appdata_*/preview. I'm using NC 12.0.5.

### Comments

The preview images do have this comment  "CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 90". I did a quick research. My preview folder is 26 GB in size with 299,000 files. All comments in all previews sum up to 15.5 MB that could be saved. So my suggestion is to strip comments.

When I installed php-imagick, new pereviews have the same comment. So this didn't make a difference, as gd seems to be used instead of imagick, despite the documentation https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html saying something else.

### Quality

According to the comment, quality setting 90 is used. This is too much. I did a research on this, too. When stripping comments and using quality 75, you can cut down disk space into half. See the screenshot for side-by-side comparison. Left = quality 90, Right = quality 75. Test was done with a real life photo, not a graphic.

![image](https://user-images.githubusercontent.com/26226303/35465451-5de35684-02fc-11e8-82fb-96f37bfb6df0.png)

In my opinion, quality 75 is sufficient even for 1536-1536-crop.jpg. However, I suggest to use multiple quality settings. For previews smaller than 100x100 you should use quality 50, between 100x100 and 300x300 you can use quality 65, between 300x300 and 800x800 you can use quality 75, and so on. This way smaller previews will be compressed better. You don't need such details in such small previews anyway. But in the larger previews, the details may be important, so a higher quality is desirable. At the moment, I cannot provide best quality settings for certain preview sizes, but I think you can figure this out quite well, too!

**Comment by ArnisR** [comment]
I would say that 20 different previews for each photo (by default settings) is bigger problem. They use not only disk space, but also inflate oc_filecache table. Fortunately last version of PreviewGenerator allows  custom size previews to be generated.

**Comment by MorrisJobke** [comment]
cc @rullzer @juliushaertl

**Comment by juliushaertl** [comment]
It is acutally possible to adjust the quality of JPEG preview by setting an app config value https://github.com/nextcloud/server/pull/3575/files#diff-8e6e137079bc48f2b3a405dfbe27a8e3R365

No idea how the previews are generated in different sizes, but it would make sense to at least have a config option to reduce the amount of previews per image. Maybe @rullzer can tell more about that.

**Comment by rullzer** [comment]
For the requested size we round up to the nearest power of 2. So if you have a square image you and request 600x600 you'll get 1024x1024.

I still have the plan (and some code) to move preview providers to apps. That way we could also add such settings easily. Or people could write their own app that does all sorts of fancy things.

**Comment by AND51** [comment]
@juliushaertl 
Cool feature, but it's not documented. Or did I overlook it? How can the documentation of this parameter be achieved?

@rullzer 
So how do we/you continue? Would you like to keep this ticket open until you implemented your plan? I think your plan sounds great.

**Comment by juliushaertl** [comment]
> Cool feature, but it's not documented. Or did I overlook it? How can the documentation of this parameter be achieved?

I cannot find it in the docs, just found this when checking the quality setting for this issue. Feel free to open a pull request to add this to the documentation. :wink:

**Comment by AND51** [comment]
Hmm... Sorry, I'm not that familiar with GitHub and all the Nextcloud-procedures here yet. But I'm willing to learn, that's why I've started to submit bugs ;-) 

So it would be wonderful, if somebody can do this for me. Otherwise, this must wait until I can ask some programmer friends how to do this :-(

**Comment by juliushaertl** [comment]
@AND51 The easiest way is to just find the page in the documentation that you would like to edit, like https://docs.nextcloud.com/server/13/admin_manual/configuration_files/previews_configuration.html and use the "Edit this page on GitHub" link on the bottom of the page. GitHub will create a pull request for the changes you make there automatically.

**Comment by schniepp** [comment]
Re: Comments — I agree that this is probably not the problem. 15MB/26GB amounts to about 0.05%. Indeed there are much bigger problems...

For instance, I currently have almost 4 million previews on my system. About 1.8 million PNGs and and about 1.9 million JPGs. Why are PNGs being used? In many cases, they provide much worse compression than JPG. Does it depend on the file type? I might have a lot of PDF, ODT, DOCX, PPTX. I haven't determined yet what file types will lead to what type of preview.

The quality suggestions sound great! From my experience, 75% is fully sufficient in nearly all cases. For anything beyond that, the original can always be downloaded. 

I agree that the number of previews could be dramatically reduced. How about from 20 to 3 or so? One size for smaller thumbnails, one size for the "tile view" (grid view?) used by gallery, and then one size for full-screen viewing (as defined by the `preview_max` parameters in `config.php`). The latter would allow one to watch each image at full screen resolution. This should minimize bandwidth enough for quick previews. I do not understand why different aspect ratios/croppings are saved in previews. Previews could be done in the same size as the original pictures; cropping/scaling can easily (and quickly) be done in the browser. Of course, the download bandwidth may be slightly higher when no perfectly sized preview is available. But having 300 GB in 4 millions of preview files (when the actual image data may not be much more than that...) is kind of extreme — let alone the CPU time it took to render all of these.

**Comment by Gatak** [comment]
You can always set the jpeg quality to 50 or even lower.

**Comment by Rayn0r** [comment]
I stumbled upon this post today since I also want to reduce the image preview size. Large preview files tend to be over 1MB even with preview_max_x and preview_max_y set to 2048.
Looking into my nextcloud DB I found this:
```
me@server:/usr/share/nextcloud# /usr/bin/mysql nextcloud -u nextcloud -p --execute="select * from oc_appconfig where appid='preview'"
Enter password:
+---------+--------------+-------------+
| appid   | configkey    | configvalue |
+---------+--------------+-------------+
| preview | jpeg_quality | 75          |
+---------+--------------+-------------+
```
So image quality is set to 75%.
lib/private/legacy/image.php contains the line:
`$quality = $this->config->getAppValue('preview', 'jpeg_quality', 90);`
I added the following right below:
`syslog(LOG_INFO,"Image Quality: $quality");`
The output in /var/log/syslog however returns this:
```
Apr 10 08:24:05 server apache2: Image Quality: 90
```
To me it looks like the getAppValue() does not fetch the value from the DB.

Am I doing something wrong here or is there perhaps a bug in the code?

**Comment by Rayn0r** [comment]
> Am I doing something wrong here or is there perhaps a bug in the code?

Please disregard my above comment. I figured out how to set the value properly.
For any one else interested... It is done like this:
```
sudo -u www-data php occ config:app:set preview jpeg_quality --value 75
```

**Comment by ohthehugemanatee** [comment]
Can someone explain for me why we store information about image cache in the database? 

Surely all Nextcloud cares about is if a given preview format has been generated for a given file yet.  That's way faster to check with `file_exists()` than a DB lookup... particularly on Linux where it comes from the filesystem metadata cache.  

A common pattern is to have a well-known path scheme, such as `appdata_ocXXXXX/previews/format_id/path/to/original/file.jpg` . Then a single fstat tells you everything you need to know, and clearing the preview cache is as easy as `rm -rf appdata_ocXXXXX/previews/` .

**Comment by szaimen** [comment]
Here is the recommended preview configuration: https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/
