### ISSUE TITLE
The migration script don't check for selinux rights.

### ISSUE THREAD

**Issue by tuxmaster** [nextcloud/server#8082]
When I try to migrate from OC 10.0.4. to NC  12.0.4, it will fail at:
```
Replace entry points
Can't replace entry point: ocs/v1.php

```
because  the  migration tool don't check the selinux context of the files.
The files has write permission for the user, but selinux don't allow it.
httpd_sys_content_t vs. httpd_sys_rw_content_t

**Comment by juliushaertl** [comment]
This issue is unrelated to the server component. Please reopen it at the https://github.com/nextcloud/owncloud-web-migrator repo.
