### ISSUE TITLE
After migration from OC to NC unable to open folders with space in path name

### ISSUE THREAD

**Issue by tuxmaster** [nextcloud/server#8083]
After update to NC 12.0.4 from OC  10.0.4 an than update to NC 12.0.5 I am unable to open directory which contains an space in its name.
On the web page the name is shown correct, but when I try to open it, I only get an error in the apache log.
Invalid status line from script 'Schule%20-%20Klassenfotos': 0
The original name will be: Schule - Klassenfotos
Create an new folder on the web page will fail with the same error.
System: CentOS  7.4
PHP 7.1 via fpm

**Comment by tuxmaster** [comment]
The fix for it was to switch from ProxyPassMatch to SetHandler.
Is it possible to create an check for it in the migrstion script?
And show an warning.

**Comment by juliushaertl** [comment]
As this is a webserver configuration issue/recommendation, this should probably go into the documentation repo. Please reopen an issue over https://github.com/nextcloud/documentation.
