### ISSUE TITLE
Table oc_migrations is not utf8mb4

### ISSUE THREAD

**Issue by AND51** [nextcloud/server#8085]
### Steps to reproduce
1. Prepare MariaDB according to https://docs.nextcloud.com/server/12/admin_manual/configuration_database/mysql_4byte_support.html#enabling-mysql-4-byte-support
2. Install fresh Nextcloud 13.0.0.8 aka Nextcloud 13 Beta 3

### Expected behaviour
All tables have collation utf8mb4_bin.

### Actual behaviour
All tables are utf8_mb4, except for `oc_migrations`, which is utf8_unicode_bin.

### Server configuration

**Operating system**: Ubuntu 16.04
**Web server:** Apache 2.4.18
**Database:** mysql  Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1
**Nextcloud version:**  Nextcloud 13 Beta 3
**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh
**Where did you install Nextcloud from:** nextcloud-13.0.0beta3.zip

![image](https://user-images.githubusercontent.com/26226303/35475264-962374e4-039b-11e8-9978-cf101b02bbf4.png)

I must admit that I don't know the exact purpose of `oc_migrations`. Maybe this is on purpose. However, the documentation at https://docs.nextcloud.com/server/12/admin_manual/configuration_database/mysql_4byte_support.html#enabling-mysql-4-byte-support describes how to alter ALL tables to use utf8mb4.

From that I conclude that either the documentation is not accurate enough and needs to be updated accordingly. Or the installer does a mistake. 

Maybe this is related to #7528 and therein referenced tickets? If you think I'm on the woodway, then just close this ticket.

**Comment by rullzer** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
Hmm works fine here. Anyone else having the problem?

**Comment by AND51** [comment]
Question is, should `oc_migrations` be utf8mb4_bin or `utf8_bin`?

I can reproduce this even in a completely different envionment:

```
mysql> show table status like "oc_migrations" \G
*************************** 1. row ***************************
           Name: oc_migrations
         Engine: InnoDB
        Version: 10
     Row_format: Dynamic
           Rows: 16
 Avg_row_length: 1024
    Data_length: 16384
Max_data_length: 0
   Index_length: 0
      Data_free: 0
 Auto_increment: NULL
    Create_time: 2018-01-30 18:35:08
    Update_time: 2018-01-30 18:35:13
     Check_time: NULL
      Collation: utf8_unicode_ci
       Checksum: NULL
 Create_options: 
        Comment: 
1 row in set (0.00 sec)

mysql> show table status like "oc_users" \G
*************************** 1. row ***************************
           Name: oc_users
         Engine: InnoDB
        Version: 10
     Row_format: Compressed
           Rows: 1
 Avg_row_length: 8192
    Data_length: 8192
Max_data_length: 0
   Index_length: 0
      Data_free: 0
 Auto_increment: NULL
    Create_time: 2018-01-30 18:35:08
    Update_time: 2018-01-30 18:35:10
     Check_time: NULL
      Collation: utf8mb4_bin
       Checksum: NULL
 Create_options: row_format=COMPRESSED
        Comment: 
1 row in set (0.01 sec)

```

I quickly installed NC 13 Beta in this environment:

- Debian 8
- MySQL 5.7 (mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper)
- Nextcloud freshly installed from this link: https://download.nextcloud.com/server/prereleases/nextcloud-13.0.0beta3.zip
- After installation the parameter "mysql.utf8mb4 => true" is set in the config

Does this help you or do you need further information?

**Comment by nickvergessen** [comment]
Did you run `occ db:convert-mysql-charset` after changing the config

**Comment by nickvergessen** [comment]
Okay, just happened here as well.
Running the command fixed the issue. I will try to find out why it is created with the wrong collation in first place.
