### ISSUE TITLE
Federation scope icon not visible when scope item has zero or null value in oc_accounts

### ISSUE THREAD

**Issue by mjanssens** [nextcloud/server#8088]
Currently on Nexcloud 12.0.5
But the issue is also reproducible in 13.0.0 RC 2

### Expected behavior
Federation scope icon should be visible for all users so they can select from the 3 options in the drop down menu.

### Actual behavior
For some users the federation scope icon is not visible for several fields. These users cannot select or change scope.

### Steps to reproduce
This concerns accounts that were created several releases ago, don't know which particular version, because I can't go so far back in time with my install.
I'm not using an external user-backend, so locally stored accounts in the database.

1. log in with one of the old accounts
2. go to personal settings
3. try to select the drop down menu for federation scope
4. Some old accounts don't have the icon next to profile picture, full name and email address fields.
5. other fields do have the federation icon and you can select the drop down menu.

When looking inside the database table oc_accounts, these accounts have for example:
`{"avatar":{"scope":""},"displayname":{"value":"testuser1","scope":""},"email":{"value":"email@address.com","scope":"","verified":"1"},"website":{"value":"","scope":"private","verified":"0"},"address":{"value":"street 01","scope":"private"},"phone":{"value":"0123456789","scope":"private"},"twitter":{"value":"","scope":"private","verified":"0"}}`

Just for testing I updated the data field in the database for one of the test accounts to:
`{"avatar":{"scope":"private"},"displayname":{"value":"testuser1","scope":"private"},"email":{"value":"email@address.com","scope":"private","verified":"1"},"website":{"value":"","scope":"private","verified":"0"},"address":{"value":"street 01","scope":"private"},"phone":{"value":"0123456789","scope":"private"},"twitter":{"value":"","scope":"private","verified":"0"}}`

And the icon appears in all fields now.

Newly created accounts don't have this behavior, so by default they have a value per scope item (f.e. "private" or "contacts")
Another old account even has a scope value null, so "scope":null}, weird...

Recently I had installed a fresh nextcloud server 13.0.0 RC2 similar to my live system.
Out of the box the accounts behave OK, so all scope icons visible.
Performing the same test as on 12.0.5, so updating test accounts with a zero or null value for a scope item, I can see similar behavior. The icon disappears.
So in a fresh NC 13 install the issue doesn't appear, but possibly when upgrading from an older install with these older accounts it probably does.

I haven't tested an actual upgrade from 12 to 13 RC2 yet, If I find more time I will test that.
But my guess is that the old accounts won't get corrected during upgrade, and so the issue remains.

## Server configuration detail

**Operating system:** Linux 4.13.13-5-pve #1 SMP PVE 4.13.13-36 (Mon, 15 Jan 2018 12:36:49 +0100) x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.33

**PHP version:** 7.0.22-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.5 - 12.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Probably installed on Nexcloud 9.0.x and upgraded from that until current release with every point release.
Update is always done manually with occ upgrade.

**Where did you install Nextcloud from:** unknown
Manual from zip download.

**Are you using an external user-backend** No

**Comment by rullzer** [comment]
@schiessle

**Comment by mjanssens** [comment]
Upgraded to NC 13.0.0  without issues.
But as expected this issue remains.
For now I corrected the few old accounts manually in the DB by replacing the "" with "contacts" for the affected fields. I guess this is the proper workaround, anyway it appears to be.

**Comment by MorrisJobke** [comment]
As we haven't seen other reports with those faulty entries I would close this ticket for now. Thanks for the feedback anyways. 👍
