### ISSUE TITLE
Filelist not updated in Groupfolder

### ISSUE THREAD

**Issue by mcteefax** [nextcloud/server#8089]
### Steps to reproduce
1. As Admin: Creating a GroupFolder and Assigning wir WRITE and SHARE to GF-Admin
2. As Admin: Create Folderstructure inside the Groupfolder; Share Subfolders to Usergroup (read-only)
3. GF-Admin Creates additional Subolders an saves files there
4. Members of Usergroup can only see the Subfolders, but no files inside.
5. As Admin: Rename the subfolder -> Usergroup can see the files; Same problem deleting files.

### Expected behaviour
The filelist should be updated automatically für Usergroup.

### Server configuration

**Operating system**: CentOS

**Web server:** 
apache

**Database:**
mysql 5.5.56

**PHP version:**
7.1.13

**Nextcloud version:** (see Nextcloud admin page)
12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox, Iron (Chrome)

**Operating system:**
Win 8.1, Win10, Win7

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>

Error: Call to a member function getPath() on null/var/www/html/nextcloud/lib/private/Preview/GeneratorHelper.php - line 53:OC\Preview\GeneratorHelper->getViewAndPath(NULL)/var/www/html/nextcloud/lib/private/Preview/Generator.php - line 162:OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\TXT), Object(OC\Files\Node\File), 2048, 2048)/var/www/html/nextcloud/lib/private/Preview/Generator.php - line 110:OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'text/plain')/var/www/html/nextcloud/lib/private/PreviewManager.php - line 201:OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 29, 29, true, 'fill', 'text/plain')
--

Error | PHP | Undefined offset: 0 at /var/www/html/nextcloud/lib/private/Preview/GeneratorHelper.php#69
-- | -- | --

<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by juliushaertl** [comment]
@mcteefax Is the problem that the file list is not updated live or is it also not updated after reload?

**Comment by mcteefax** [comment]
The file still isn't updated after reload. Same after Logout-Login.

Sory for the late answer.

**Comment by MorrisJobke** [comment]
Fixed by https://github.com/nextcloud/groupfolders/releases/tag/v1.2.0
