### ISSUE TITLE
NC13 Firefox folder drag and drop not working

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#8093]
Drag and drop of folder using FF58 on NC13RC2 does nothing. No error, just nothing. Drag and drop of individual files, or multiple files, works as expected. Chromium works fine.

 FF58 and NC12 folder drag and drop works as expected.

**Comment by juliushaertl** [comment]
Works fine here in FF57

**Comment by juliushaertl** [comment]
Same after updating to FF58. Do you get any UI feedback when attempting to drag the folder?

**Comment by putt1ck** [comment]
Nothing at all. Will update to RC3 and try again.

**Comment by putt1ck** [comment]
ok works in RC3.

**Comment by kayvanaarssen** [comment]
We have this bug again in Nextcloud 16.0.2.1 any idea?

**Comment by fporchiella** [comment]
The same bug (or something similar) is also present in version 16.0.2.
Dragging a folder returns the error "you do not have permission to write...", selecting multiple files the upload work well.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/16238
