### ISSUE TITLE
Adding new user fails

### ISSUE THREAD

**Issue by benhartwich** [nextcloud/server#8098]
### Steps to reproduce
1. Install NC 13 RC3
2. Click on settings/users
3. Try to create an user with username and password

### Expected behaviour
New user should be created

### Actual behaviour
Nothing

### Server configuration

**Operating system**: 
Debian 9

**Web server:**
nginx 1.12.2

**Database:**
MariaDB 10.2

**PHP version:**
7.0.27

**Nextcloud version:**
13.0.0 RC 3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.0.0. RC 2

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - end_to_end_encryption: 1.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_automatedtagging: 1.3.0
  - files_fullnextsearch: 0.3.1
  - files_fulltextsearch: 0.5.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.2.0
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - fullnextsearch_elasticsearch: 0.3.1
  - fulltextsearch: 0.5.1
  - fulltextsearch_elasticsearch: 0.5.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ocdownloader: 1.5.5
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 1.12.40
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_diaspora: 1.0.2
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - spreed: 3.0.1
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_external
  - spreedme
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "beta.speibox.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/beta.speibox.de",
        "dbtype": "mysql",
        "version": "13.0.0.12",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "beta",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "log_type": "syslog",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

</details>

#### Browser log
<details>
<summary>Browser log</summary>
Failed to load resource: the server responded with a status of 403 ()
users.js?v=1b343f99-0:1090 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.<anonymous> (users.js?v=1b343f99-0:1090)
    at j (core.js:2)
    at Object.fireWith [as rejectWith] (core.js:2)
    at x (core.js:4)
    at XMLHttpRequest.<anonymous> (core.js:4)
</details>

**Comment by rullzer** [comment]
Can you post your nginx config?

**Comment by benhartwich** [comment]
```
server {
    	listen 443 ssl;
    	server_name beta.de;
      ssl_certificate /etc/letsencrypt/live/beta.de/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/beta.de/privkey.pem;
     	add_header Strict-Transport-Security "max-age=63072000; preload";
    	add_header X-Content-Type-Options nosniff;
    	#add_header X-Frame-Options "SAMEORIGIN";
    	add_header X-XSS-Protection "1; mode=block";
    	add_header X-Robots-Tag none;
    	add_header X-Download-Options noopen;
    	add_header X-Permitted-Cross-Domain-Policies none;
    	root /var/kunden/nextcloud-beta/httpdocs/nextcloud;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

    	location = /robots.txt {
        	allow all;
        	log_not_found off;
        	access_log off;
    	}

    	location = /.well-known/carddav { return 301
     		$scheme://$host/remote.php/dav; }
    	location = /.well-known/caldav { return 301
     		$scheme://$host/remote.php/dav; }

    	location /.well-known/acme-challenge { }

    	# set max upload size
    	client_max_body_size 5G;
    	fastcgi_buffers 64 4K;
    	gzip off;

    	error_page 403 /core/templates/403.php;
    	error_page 404 /core/templates/404.php;

    	location / {
        	rewrite ^ /index.php$uri;
	}

    	location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        	deny all;
    	}

    	location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
        	deny all;
    	}

    	location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|core/templates/40[34])\.php(?:$|/) {
		fastcgi_split_path_info ^(.+\.php)(/.*)$;
		include fastcgi_params;
        	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        	fastcgi_param PATH_INFO $fastcgi_path_info;
        	fastcgi_param HTTPS on;
        	fastcgi_param modHeadersAvailable true;
        	fastcgi_param front_controller_active true;
        	fastcgi_pass unix:/var/run/php/php7.0-fpm-beta.sock;
        	fastcgi_intercept_errors on;
        	fastcgi_request_buffering off;
    	}

	location ^~ /webrtc {
		proxy_pass http://127.0.0.1:8080;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

		proxy_buffering				on;
		proxy_ignore_client_abort	off;
		proxy_redirect				off;
		proxy_connect_timeout		90;
		proxy_send_timeout			90;
		proxy_read_timeout			90;
		proxy_buffer_size			4k;
		proxy_buffers				4 32k;
		proxy_busy_buffers_size		64k;
		proxy_temp_file_write_size	64k;
		proxy_next_upstream			error timeout invalid_header http_502 http_503 http_504;
	}

    	location ~ ^/(?:updater|ocs-provider)(?:$|/) {
        	try_files $uri/ =404;
        	index index.php;
    	}

    	location ~* \.(?:css|js)$ {
        	try_files $uri /index.php$uri$is_args$args;
        	add_header Cache-Control "public, max-age=7200";
        	add_header X-Content-Type-Options nosniff;
        	add_header X-Frame-Options "SAMEORIGIN";
        	add_header X-XSS-Protection "1; mode=block";
        	add_header X-Robots-Tag none;
        	add_header X-Download-Options noopen;
        	add_header X-Permitted-Cross-Domain-Policies none;
        	access_log off;
    	}

    	location ~* \.(?:svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$ {
        	try_files $uri /index.php$uri$is_args$args;
        	access_log off;
    }
}
```

**Comment by rullzer** [comment]
Remove:

```
   	error_page 403 /core/templates/403.php;
    	error_page 404 /core/templates/404.php;
```

**Comment by benhartwich** [comment]
Thanks, works again.
