### ISSUE TITLE
Add cache buster to images as well

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#81]
We should also add cache busters to images such as our SVG files as well. For example by including `core/img/filetypes/folder-shared.svg?version=9.0.0`. Otherwise after an update still the old images are shown until the user manually clears their cache.

**Comment by LukasReschke** [comment]
FYI @jancborchardt, just experienced this when I migrated https://cloud.nextcloud.com/

**Comment by LukasReschke** [comment]
I wonder if we can easily do this via some Javascript: Parse for all image links in `core/` and append a `?version=`. Mhm…

**Comment by LukasReschke** [comment]
Something like http://www.bennadel.com/blog/2643-cache-busting-css-images-with-less-css.htm would really help. Using http://lesscss.org/#client-side-usage we could also do this so that developers don't need any additional tools and do the compilation as packaging step.

**Comment by LukasReschke** [comment]
Assigning @jancborchardt, either *cough cough* somebody *cough cough* needs to add the version strings manually to all images in the CSS files and change them all the time we change an image…

Or we switch to something like LessCSS that does this for free.

**Comment by ChristophWurst** [comment]
> I wonder if we can easily do this via some Javascript: Parse for all image links in core/ and append a ?version=. Mhm…

I assume that might cause the browser to download the images twice. First, the HTML/CSS is parsed and the browser starts downloading files without any cache buster (the original URL). At some point the JS kicks in and modifies all core image URLs. As the browser might already download some images, those are downloaded a second time as the URL changed.
