### ISSUE TITLE
Error on Update from 12.0.4 to 12.0.5

### ISSUE THREAD

**Issue by webmaisterpro** [nextcloud/server#8107]
Steps to reproduce

Working version 12.0.4, updated through web browser app to 12.0.5

Expected behaviour
Unable to complete update

Detailed logs 

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "[]", "core", "oc.integritycheck.checker"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Operating system:
Ubuntu 16.04 x64

Web server:
apache

Database:
MySQL

PHP version:
7.0

Nextcloud version: (see Nextcloud admin page)
https://synergyencrypt.com/cloud/

Updated from an older Nextcloud
Update via browser

**Comment by webmaisterpro** [comment]
Fixed by changing permission to **occ** to 744

**Comment by juliushaertl** [comment]
> MySQL server has gone away

If there is no server, there is nothing we can do about that. :wink:
