### ISSUE TITLE
Calendar: unable to accept invite to changed event (Spreed invite) which already exists in the calendar: HTTP error code 412

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/server#8110]
For the current calendar app version on cloud.nextcloud.com, and using Evolution on Ubuntu Gnome as client:

### Steps to reproduce
1. create a Spreed.com invite for 9am, send out invitations
2. accept the event in Evolution
3. it gets added to the NC calendar
4. in Spreed, change the event time to 8am, resend the invitation
5. try to accept the event invite again in Evolution

### Expected behaviour
The event should be moved to 8am or at least get accepted as another event without errors.

### Actual behaviour
An error occurs:

`Unable to send item to calendar “Sales”. Cannot receive calendar objects: Failed to put data: HTTP error code 412 (Precondition failed): Sabre\DAV\Exception\PreconditionFailed An If-None-Match header was specified, but the ETag matched (or * was specified). If-None-Match[exception][message][header]
`
![image](https://user-images.githubusercontent.com/295122/35566767-ddce7bb2-05c2-11e8-90e2-6406d5922ef4.png)

**Comment by hno** [comment]
Experienced this with events sent from Outlook/Exchange, using Evolution 3.26.6 caldav connected to Nextcloud 13 official docker installed some days ago.

**Comment by mckea** [comment]
I get this repeatedly as well, for event updates sent from Outlook/Exchange.  I'm also unable to modify the event directly, since I'm not the original event organizer.  Nextcloud 13.0.2.  Evolution 3.28.2 on Fedora 28.

**Comment by mckea** [comment]
Possibly un-stale-ing this?  The problem persists and is more or less crippling my ability to use Nextcloud with my employer's many meeting requests sent from Outlook/Exchange.  

Nextcloud 13.0.6.  Evolution 3.28.5 on Fedora 28.

**Comment by aidan** [comment]
Same for me with Nexcloud 14.0.1 on FreeNAS and Evolution 3.28.5 On Ubuntu 18.04.1

**Comment by rikmeijer** [comment]
Exact same problem occurs in baikal. Seems to be a Sabre problem

**Comment by hubertbanas** [comment]
Experiencing same issue here as well.

Nextcloud 15.0.5
Calendar 1.6.4
Evolution 3.28.5-0ubuntu0.18.04.1


Evolution shows the following:
```
Found the appointment in the calendar “Work”

Unable to send item to calendar “Work”. Cannot receive calendar objects:
Failed to put data: HTTP error code 412 (Precondition failed):
Sabre\DAV\Exception\PreconditionFailed An If-None-Match header was specified,
but the ETag matched (or * was specified). If-None-Match[exception][message][header]
```

**Comment by hubertbanas** [comment]
This may have been Evolution issue; already addressed in 3.31.3+ and 3.30.3+ via
https://gitlab.gnome.org/GNOME/evolution-data-server/commit/e361a1bd9

See
https://gitlab.gnome.org/GNOME/evolution/issues/257

**Comment by logic** [comment]
Same problem here, with Evolution 3.32.1 (Fedora 30).

**Comment by thomasnat** [comment]
Same problem here, with Evolution 3.32.3 (Arch Linux)

**Comment by georgehrke** [comment]
This is / was a bug in Evolution.

Evolution sends an If-None-Match: * header.
If-None-Match means: Only update / create this event, if it doesn't match the provided etag. And since the provided etag is *, it matches any existing event of the same filename.

Meaning: As soon as that file storing the event already exists, the server will reject it.

**Comment by bowlofeggs** [comment]
@georgehrke Do you know if this has been reported to the Evolution project?

**Comment by bowlofeggs** [comment]
@georgehrke Ah nevermind, I now see https://github.com/nextcloud/server/issues/8110#issuecomment-477172310
