### ISSUE TITLE
[Question] - Reset Database?

### ISSUE THREAD

**Issue by Windyo** [nextcloud/server#8113]
Hi,

I swear I've read all the docs and scoured the issues, but I can't find what I want.
Is there a way to reset the Nextcloud File DB ?

The drive the data was on got corrupted, I restored a working backup, now there's quite a few differences between DB and reality, but running occ scan doesn't seem to resolve the issues. 
Symptom: client says "file removed from server"  when it tries to sync, listing older files.

I would really like to just scratch the file DB and let Nextcloud rebuild it.

Thanks

**Comment by tflidd** [comment]
There is also a cleanup option in occ (https://docs.nextcloud.com/server/12/admin_manual/configuration_server/occ_command.html?highlight=occ#file-operations-label). You should try to use these default options, perhaps add `-vvvv` to capture errors during the process. If you clean up manually, you risk to create inconsistencies elsewhere since other apps rely on the filecache table (sharing, tags, ...). If the scanning process is not working properly, it's probably worth to find and fix the issue.  Can you give more details how it fails and why it fails?

**Comment by Windyo** [comment]
Hi !

Scan doesn't fail - it completes successfully, but the sync client still finds files that were "deleted from server" after running it.
Running Cleanup returns ``0 orphaned file cache entries deleted``.

So normally everything should be fine but the client still complains that something doesn't add up...

**Comment by MorrisJobke** [comment]
> Running Cleanup returns 0 orphaned file cache entries deleted.

That's weird if files that are present in the file cache are not there on disk. How did you run the scan command?

cc @icewind1991

**Comment by Windyo** [comment]
I did:
``sudo i-``

``sudo i-``

``cd /var/www/nextcloud/``

``sudo -u www-data php occ files:cleanup``

``sudo -u www-data php occ files:scan Windyo``

All finsihed successfully, with the file scan finding some 40k files, which is about right.


Currently running the latest version of NextCloudPi if that gives you more info.

If you need logs or dumps, ask and you shall receive.

**Comment by FreeMinded** [comment]
I'm experiencing the exact same issue. Some files show in the but are not actually present on the file system. occ files.scan runs through without any errors, occ files:cleanup also run successfully without finding orphaned files.
@Windyo did you find a solution?

**Comment by Windyo** [comment]
@FreeMinded I ended up setting up a new nextcloud instance on another, temporary, server with the same username/passwd... and then getting that fresh database file, copying it over to the old one.

So I "reset" the db by making nextcloud use a brand new db.

**Comment by FreeMinded** [comment]
@Windyo OK, but I'm not sure if I want to try that with 30 LDAP connect users and 100'000 files... :(

**Comment by Windyo** [comment]
Unfortunately that's all I have.

To be fair since hosting Nextcloud it's had its fair share of problems regarding database management, so now I backup the DB every week or so, and I also maintain a "clean" image of setup just after install (not inclding DB and files) which I can reflash if need be.

It's very akin to nuking everything from orbit, but it works and is time-efficient for my needs, so that's what I'm doing ATM...

**Comment by dvergeylen** [comment]
Hi, I'm experiencing the same issue.
@FreeMinded, did you find a solution?

**Comment by FreeMinded** [comment]
@dvergeylen only partially and by manually deleting wrong files entries in the filecache table.
i.e. 
`DELETE from oc_filecache where path LIKE '__groupfolders/2/path/to/file';`
or 
`DELETE from oc_filecache where name LIKE 'filename';`

If you delete to many entries re-running occ files:scan will add them again. But I havn't dared to deleted all filecache entries at once yet.

**Comment by jdownie** [comment]
@FreeMinded , when you say "delete too many entries", you just mean that if you start deleting entries that actually exist on the filesystem the next files:scan will discover them again. You don't mean that there's anything wrong with discovering 500 missing entries and deleting them all at once, right? I'm working on a python script that does just that. I thought that files:clean would do that, but it doesn't seem to be thorough enough. To be fair though i'm using it to share thousands of large files that change frequently. Mine is a very aggressive use case.

**Comment by FreeMinded** [comment]
@jdownie I have limited experience on this, but what I observed back then, was that occ files:scan is good at adding files to the database. But not at all removing them from the DB if the file is gone from the disk. So I guess you should be fine deleting the DB entries and have them re-added by the occ files:scan. But I would also ask the question why does it not work properly the "right way".

**Comment by jdownie** [comment]
This is not as comprehensive as some people might need it to be, but it got me out of trouble. I hope it's of some use to somebody else...
```python
#!/usr/bin/python3

import os
import mysql.connector

mydb = mysql.connector.connect(
  host = os.environ["MYSQL_HOST"],
  user = os.environ["MYSQL_USER"],
  passwd = os.environ["MYSQL_PASSWORD"],
  database = os.environ["MYSQL_DATABASE"]
);
sql = "select f.fileid, concat(replace(s.id, 'home::', ''), '/', f.path) as path from oc_filecache f, oc_storages s where f.storage = s.numeric_id and s.id like 'home::%';"
cur = mydb.cursor(dictionary = True)
cur.execute(sql)
duds = list()
for row in cur:
  fileid = row["fileid"]
  path = row["path"].decode("utf-8")
  if not os.path.exists(os.path.join("/var/www/html/data", path)):
    print("DUD: {0}".format(path))
    duds.append(fileid)
for dud in duds:
  sql = "delete f from oc_filecache f where f.fileid = {0};".format(dud)
  cur.execute(sql)
  mydb.commit()
print("Removed {0} corrupt entries from oc_filecache.".format(len(duds)))
```

**Comment by Arduous** [comment]
The script above allowed me to cleanup massive amounts of dangling references following an hardware failure. Beware, besides doing its intended job, it seems that it removed the sharing property of every objects shared by any user.
