### ISSUE TITLE
NC mistaken PHP-FPM version 5.4.16 as PHP version

### ISSUE THREAD

**Issue by n8v8R** [nextcloud/server#8115]
Apache & Varnish Cache & Nginx Reverse Proxy
CentOS 7.4.1708 (Core) - Kernel 3.10.0-693.17.1.el7.x86_64
Apache/2.4.2
nginx/1.12.2
PHP 5.6.30
PHP-FPM 5.4.16 (fpm-fcgi)
suPHP 0.7.2
Zend Engine v2.6.0 with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured)
MySQL 10.1.30-MariaDB
SEL permitting
Mod Security disabled

NC 12.0.5

Apparently NC is mistaken the PHP-FPM version as actual PHP version. After the successful installation of NC this is being presented
> This version of Nextcloud requires at least PHP 5.6.0
> You are currently running 5.4.16. Please update your PHP version.

The output from
```
?php
echo 'Current PHP version: ' . phpversion();
?>
```
is

> Current PHP version: 5.6.30

**Comment by rullzer** [comment]
We use PHP_VERSION see https://secure.php.net/manual/en/reserved.constants.php#reserved.constants.core

So even php seems to think you are running 5.4.16. This seems like a setup issue.

**Comment by n8v8R** [comment]
Thanks for the feedback. Checking with `php -v` returns however

> PHP 5.6.30 (cli) (built: Jan 28 2017 14:24:05)
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
>     with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.0.8, Copyright (c) 2002-2016, by ionCube Ltd.

Suppose `php -v` is not a predefined constant and returns the actual value.
What I am wondering also is why this turns up only after the installation succeeded and not at the start of the installation, assuming that NC runs a routine to check whether the requirements are met prior installation

**Comment by rullzer** [comment]
well `php -v` isn't going via fpm.

Did you install nextcloud via the command line?

**Comment by n8v8R** [comment]
the webinstaller setup-nextcloud.php

**Comment by rullzer** [comment]
Mmm I should look into that then.

But back to the original issue. If you access a file with

```php
<?php
echo 'Current PHP version: ' . phpversion();
```

from the web. Does it then tell you 5.6.30?

**Comment by n8v8R** [comment]
Yes, you may check it https://vtol.me

**Comment by n8v8R** [comment]
If it matter those are the server settings
# Virtual host file starts here

upstream php-handler {
    server 127.0.0.1:9000;
}

server {
listen ....:80;
return 301 https://$server_name$request_uri;
}

server {
listen ....:443 ssl http2;
access_log /var/log/nginx/access...log;
error_log /var/log/nginx/error....log;
server_name ... www.....;
root /home/.../public_html;
autoindex off;
charset utf-8;
server_tokens off;
gzip   off;

ssl                  on;
ssl_certificate      /etc/pki/tls/certs/.....bundle;
ssl_certificate_key  /etc/pki/tls/private/....key;
ssl_protocols TLSv1.2;
ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305-SHA256:ECDHE-RSA-CHACHA20-POLY1305-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:!DSS;
ssl_prefer_server_ciphers on;
ssl_ecdh_curve secp384r1;
ssl_session_cache shared:SSL:32m;
ssl_session_timeout 60m;
ssl_session_tickets off;
ssl_buffer_size 8K;
ssl_dhparam /etc/pki/tls/certs/dhparam.pem;
ssl_stapling on;
ssl_stapling_verify on;
ssl_trusted_certificate /etc/pki/tls/certs/....bundle;
resolver 209.244.0.4 9.9.9.9 valid=300s;
resolver_timeout 10s;

add_header X-Cache "HIT from Backend";
#add_header Strict-Transport-Security 'max-age=63072000; includeSubDomains;' always;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
add_header X-Frame-Options SAMEORIGIN;
add_header Expect-CT: max-age=86400;
add_header X-Robots-Tag none;
add_header X-Download-Options noopen;
add_header X-Permitted-Cross-Domain-Policies none;

location / {
location ~.*\.(3gp|gif|jpg|jpeg|png|ico|wmv|avi|asf|asx|mpg|mpeg|mp4|pls|mp3|mid|wav|swf|flv|html|htm|txt|js|css|exe|zip|tar|rar|gz|tgz|bz2|uha|7z|doc|docx|xls|xlsx|pdf|iso|woff|ttf|svg|eot|sh)\$ {
expires 7d; #Comment this out if you are using the apache backend cache-control/expires headers.
try_files \$uri \@backend;
}
error_page 405 = \@backend;
error_page 500 = \@custom;
proxy_pass http://...:82;
include proxy.inc;
}
location \@backend {
internal;
proxy_pass http://...:82;
include proxy.inc;
}
location \@custom {
internal;
proxy_pass http://....:82;
include proxy.inc;
}
location ~ .*\.(php|jsp|cgi|pl|py)?\$ {
proxy_pass http://....:82;
include proxy.inc;
}
location ~ /\.ht {
deny all;
}

location = /robots.txt {
allow all;
log_not_found off;
access_log off;
}

    # The following 2 rules are only needed for the user_webfinger app.
    # Uncomment it if you're planning to use this app.
    # rewrite ^/.well-known/host-meta /nextcloud/public.php?service=host-meta
    # last;
    #rewrite ^/.well-known/host-meta.json
    # /nextcloud/public.php?service=host-meta-json last;

    location = /.well-known/carddav {
      return 301 $scheme://$host/nextcloud/remote.php/dav;
    }
    location = /.well-known/caldav {
      return 301 $scheme://$host/nextcloud/remote.php/dav;
    }

    location /.well-known/acme-challenge { }

    location ^~ /nextcloud {

        # set max upload size
        client_max_body_size 512M;
        fastcgi_buffers 64 4K;

        # Enable gzip but do not remove ETag headers
        gzip on;
        gzip_vary on;
        gzip_comp_level 4;
        gzip_min_length 256;
        gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
        gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

        # Uncomment if your server is build with the ngx_pagespeed module
        # This module is currently not supported.
        #pagespeed off;

        location /nextcloud {
            rewrite ^ /nextcloud/index.php$uri;
        }

        location ~ ^/nextcloud/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
        }
        location ~ ^/nextcloud/(?:\.|autotest|occ|issue|indie|db_|console) {
            deny all;
        }

        location ~ ^/nextcloud/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param HTTPS on;
            #Avoid sending the security headers twice
            fastcgi_param modHeadersAvailable true;
            fastcgi_param front_controller_active true;
            fastcgi_pass php-handler;
            fastcgi_intercept_errors on;
            fastcgi_request_buffering off;
        }

        location ~ ^/nextcloud/(?:updater|ocs-provider)(?:$|/) {
            try_files $uri/ =404;
            index index.php;
        }

        # Adding the cache control header for js and css files
        # Make sure it is BELOW the PHP block
        location ~ \.(?:css|js|woff|svg|gif)$ {
            try_files $uri /nextcloud/index.php$uri$is_args$args;
            add_header Cache-Control "public, max-age=15778463";
            # Add headers to serve security related headers  (It is intended
            # to have those duplicated to the ones above)
            # Before enabling Strict-Transport-Security headers please read
            # into this topic first.
            # add_header Strict-Transport-Security "max-age=15768000;
            # includeSubDomains; preload;";
            add_header X-Cache "HIT from Backend";
            #add_header Strict-Transport-Security 'max-age=63072000; includeSubDomains;' always;
            add_header X-Content-Type-Options nosniff;
            add_header X-XSS-Protection "1; mode=block";
            add_header X-Frame-Options SAMEORIGIN;
            add_header Expect-CT: max-age=86400;
            add_header X-Robots-Tag none;
            add_header X-Download-Options noopen;
            add_header X-Permitted-Cross-Domain-Policies none;
            # Optional: Don't log access to assets
            access_log off;
        }

        location ~ \.(?:png|html|ttf|ico|jpg|jpeg)$ {
            try_files $uri /nextcloud/index.php$uri$is_args$args;
            # Optional: Don't log access to other assets
            access_log off;
        }
    }
}

# Virtual host file ends here

**Comment by rullzer** [comment]
The site doesn't work for me. But as stated if your php-fpm even trick php into thinking it is a different version then this is a setup issue. Please use https://help.nextcloud.com maybe somebody there has a clue. But I don't consider this a nextcloud bug.

**Comment by n8v8R** [comment]
The site is up and running working fine in FF, Edge and Vivaldi. 

PHP content is served through 
```
upstream php-handler {
    server 127.0.0.1:9000;
}
```
The site would not display v5.6.0 if tricked by PHP-FPM. It is already posted on forum but there is help.

So, basically you are saying that NC is not conducting a check of system requirements in order prior installation and just forges ahead with the installation in order to surprise the user afterwards?

Understand that you cannot be bothered to consider this an issue of NC. Perhaps until another user pops up with the same trouble. Leaving me to move on to another platform then. Thanks anyway

**Comment by rullzer** [comment]
> So, basically you are saying that NC is not conducting a check of system requirements prior installation and just forges ahead with the installation in order to surprise the user afterwards?

No that is a valid issue. And I have it on my todo to look into it and add a check in that setup as well.

I mean the issue with php-fpm lying about its php version :)

**Comment by rullzer** [comment]
Mmmm I still don't get it... https://github.com/nextcloud/web-installer/blob/master/setup-nextcloud.php#L79-L81 looks like the same check...

**Comment by n8v8R** [comment]
Explains the why the pre-natal check and the installation went ok. What is calling the post installation check, the same code?

**Comment by n8v8R** [comment]
Thought to give a go with PHP7.1.0 and upgraded the server but no such luck and the same outcome as previously with PHP5..6.0

![nc setup 1](https://user-images.githubusercontent.com/13611490/35645521-631dc656-06cc-11e8-901e-de586dde48fc.PNG)

![nc setup 2](https://user-images.githubusercontent.com/13611490/35645532-6cd5a326-06cc-11e8-8538-1b4e8d628775.png)

![nc setup 3](https://user-images.githubusercontent.com/13611490/35645537-75ec1d1e-06cc-11e8-9acb-34285f2abfa4.PNG)

![nc setup 4](https://user-images.githubusercontent.com/13611490/35645544-786ea11a-06cc-11e8-869b-ee78406463e6.png)

**Comment by rullzer** [comment]
could you create an issue in https://github.com/nextcloud/web-installer ?Because the installer should fail as well here indeed.

**Comment by n8v8R** [comment]
@rullzer cross reference https://github.com/nextcloud/web-installer/issues/22

**Comment by n8v8R** [comment]
not sure whether/how this potentially could cause the issue but might be worth noting that the cli bits producing different version output

`php -v` and `php-cgi -v` respectively would always produce the actual installed PHP version, e.g. 7.1.0,whilst `php-fpm -v` always producing it own version 5.4.16

**Comment by n8v8R** [comment]
Out of curiosity removed php-fpm from the server and the NC login page is showing.

After having completed the initial NC setup and logout I put the php-fpm parser/server back to work and the NC login is still showing.

**Comment by n8v8R** [comment]
after update to NC 12.0.5 it is not possible to log into NC. With the php-fpm server _running_ it shows
> This version of Nextcloud requires at least PHP 5.6.0
> You are currently running 5.4.16. Please update your PHP version.

And with the php-fpm server _stopped_ it gets
> 502 Bad Gateway

@rullzer since the issue been created https://github.com/nextcloud/web-installer/issues/22 it seems not garnered any attention. Am I better off to move to another file-sharing platform?
