### ISSUE TITLE
Make opt-out list of incompatible clients for same site cookie protection configurable

### ISSUE THREAD

**Issue by jaltek** [nextcloud/server#8123]
In my use case I had to add a second user agent (in addition to the already existing default entry for the OSX Finder) to the list of incompatible clients for same site cookie protection (ref. [base.php](https://github.com/nextcloud/server/blob/142914608307839dca300a2d410b869b6d2d3444/lib/base.php#L524)).

As I have to change the base.php after each Nextcloud update it would be nice to have this list available as a config value.

I have already prepared a corresponding change: https://github.com/jaltek/server/commit/f416da4f005e9cd8512239432cdcb0a4cfc2860a

What do you think?

**Comment by MorrisJobke** [comment]
cc @nextcloud/security @rullzer  What is your opinion on this? I would like to not introduce something like this because it could affect the security of the system. On the other side there are multiple issues with this and incompatible clients: 

* #3523
* https://github.com/nextcloud/server/pull/1328#issuecomment-275907555
* #1601
* https://github.com/nextcloud/server/issues/223#issuecomment-248592752
* #1603

**Comment by jaltek** [comment]
@MorrisJobke IMHO a configuration variable is much safer than forcing the users / admins to change the lib/base.php. And they **will** change the base.php in order to get the clients and apps working :)

**Comment by rullzer** [comment]
Pfff I'm not a fan of this. But I see the point of @jaltek 

Maybe something where you can put them in `config.php`? And we print a big warning in the admin settings and also set a flag in the logger so that we can log if bad stuff happens with such a weird client?

**Comment by jaltek** [comment]
@rullzer As mentioned I prepared something at that time:

https://github.com/jaltek/server/commit/f416da4f005e9cd8512239432cdcb0a4cfc2860a

So you don't have to touch the base.php every time an issue appears because of weird clients :)
And - by using the config.php - this is optional.

**Comment by rullzer** [comment]
@jaltek cool. Mind to open a PR so we can discuss and get this in?

**Comment by MorrisJobke** [comment]
Fixed by #9772

**Comment by jaltek** [comment]
Awesome! Thx a lot!

Maybe this fixes the above mentioned (https://github.com/nextcloud/server/issues/8123#issuecomment-395422753) issues as well?

**Comment by MorrisJobke** [comment]
> Maybe this fixes the above mentioned (#8123 (comment)) issues as well?

Already checked all of them and they are already closed ;)
