### ISSUE TITLE
share-menu displays different/incorrect permissions

### ISSUE THREAD

**Issue by DJCrashdummy** [nextcloud/server#8125]
### Steps to reproduce
1. login into your nextcloud and open the normal file-app
2. open the share side-panel and create a share either via mail-address or/and via link (it applies to both!)
3. restrict the access to just create/upload files
4. go the gallery-app and open the shared folder
5. open the share-menu via icon in the upper right (including an eventual drop-down) and have a look at the completely different permissions... :open_mouth: 

a picture is worth a thousand words:... between taking these 2 screen shots nothing was changed!!!
![nextcloud - dateien](https://user-images.githubusercontent.com/26110463/35627214-87a0e082-0698-11e8-942f-42020d0a1091.png)
![nextcloud - galerie](https://user-images.githubusercontent.com/26110463/35627226-92723830-0698-11e8-81d2-c62b5f2bbeb0.png)

### Expected behaviour
the share-menu in every app should indicate the same resp. correct permissions!

### Actual behaviour
1. in the gallery app the share via mail-address is displayed with full permissions to edit & delete files.
2. in the gallery app the share via link is just displayed with "allow edit"; a check box for just "allow upload" isn't present at all.

i haven't investigated further (were are the right permissions displayed, when and why do they get overridden by some changes at the other share-menu, etc.) because of lack of time - someone who is familiar with the code can do this 100 times more efficient and gather more/better information than me - and also if the permissions stay what they were set (and "only" displayed wrong), IMHO it already worth a bug-report and fixing. _...to prevent minor heart-attacks when looking at the wrong permissions._ :wink: 

### Server configuration

**Operating system**:
Ubuntu

**Web server:**
Apache

**Database:**
mysql 5.6.38

**PHP version:**
7.0.25

**Nextcloud version:** (see Nextcloud admin page)
12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from nextcloud 11

**Where did you install Nextcloud from:**
hoster-script

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Activity
Auditing / Logging
Comments
Deleted files
External user support
Federation
File sharing
First run wizard
Gallery
Log Reader
Monitoring
Nextcloud announcements
Notifications
Password policy
PDF viewer
Share by mail
Text editor
Update notification
Versions
Video player
Activities for shared file downloads
AppOrder
Calendar
Checksum
Contacts
Impersonate
Keeweb
Metadata
Notes
OPDS catalog
QOwnNotesAPI
Quota warning
Reader (ebook reader)
Social sharing via email
Tasks
Telephone Provider for ContactsMenu
Video calls
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'XXXXXXXXXXXX',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'cloud.example.tld',
  ),
  'datadirectory' => '/www/htdocs/nextcloud/data',
  'overwrite.cli.url' => 'http://example.tld',
  'dbtype' => 'mysql',
  'version' => '12.0.5.3',
  'dbname' => 'XXXXXXXXXX',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'XXXXXXXXXX',
  'mysql.utf8mb4' => false,
  'dbuser' => 'XXXXXXXXXX',
  'dbpassword' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'installed' => true,
  'default_language' => 'de',
  'allow_user_to_change_display_name' => false,
  'skeletondirectory' => '',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{mail.example.tld:993/imap/ssl/novalidate-cert/readonly}INBOX',
        1 => 'example.tld',
      ),
    ),
  ),
  'updater.release.channel' => 'production',
  'loglevel' => 2,
  'customclient_desktop' => 'https://nextcloud.com/install/#install-clients',
  'customclient_android' => 'https://f-droid.org/packages/com.nextcloud.client',
  'customclient_ios' => 'https://itunes.apple.com/us/app/nextcloud/id1125420102',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/www/htdocs/nextcloud/apps_neu',
      'url' => '/apps_neu',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/www/htdocs/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\ArrayCache',
  'theme' => '',
  'filesystem_check_changes' => 1,
  'tempdirectory' => '/www/htdocs/nextcloud/tmp/',
  'maintenance' => false,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Epub',
    5 => 'OC\\Preview\\FB2',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\OpenDocument',
    8 => 'OC\\Preview\\StarOffice',
    9 => 'OC\\Preview\\MSOfficeDoc',
    10 => 'OC\\Preview\\MSOffice2003',
    11 => 'OC\\Preview\\MSOffice2007',
  ),
  'updater.secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
);
```
</details>

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
IMAP

### Client configuration
**Browser:**
Firefox 56

**Operating system:**
Linux Mint 17 (based on Ubuntu 14.04)

**Comment by DJCrashdummy** [comment]
this issue looks similar to me: https://github.com/nextcloud/gallery/issues/109

**Comment by MorrisJobke** [comment]
cc @danxuliu @oparoz @rullzer

**Comment by MorrisJobke** [comment]
We are planning to have a unified sidebar available in Nextcloud 17 that loads then the exact same share code and renders the same content. Then this issue should not happen anymore. Until then we don't plan to overhaul the gallery that much to bring them into the same condition. Sorry for that.
