### ISSUE TITLE
13RC4 drag and drop folder to sub-folder partially fails

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#8139]
Using FF58: drag and drop a folder from your preferred desktop file explorer. Drop folder on sub-folder in NC UI. Get a series of errors "CRSF check not passed" as each file upload is completed. Folder is created within the target sub-folder but not the files the dropped folder contained. 

The files are not present in the server file system, but the upload process suggests they get transferred to the server before the error is encountered - cached somewhere?

Similar experience on 12.04, except the error pop-up is "Unauthorized".

Possibly related to https://github.com/nextcloud/server/issues/7278 (and I've also reported there - started new issue because impacts NC13)

**Comment by putt1ck** [comment]
Issue can also be reproduced in Chromium 63.

**Comment by ChristophWurst** [comment]
Is this still an issue with stable 13 or 14?
