### ISSUE TITLE
logging tab not working in syslog configuration

### ISSUE THREAD

**Issue by cgzones** [nextcloud/server#8140]
### Steps to reproduce
1. switch to syslog logging
2. browse to the logging tab (index.php/settings/admin/logging)

### Expected behaviour
Show the logs

### Actual behaviour
Loading circle and php error (see below)

### Server configuration

**Operating system**: Debian

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** https://nextcloud.com/install/#instructions-server

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
Standard official ones + Calendar + Contacts
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'foo',
  'passwordsalt' => 'bar',
  'secret' => 'foobar',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.mydomain',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'https://mydomain/nextcloud',
  'dbtype' => 'mysql',
  'version' => '12.0.5.3',
  'dbname' => 'nextclouddb',
  'dbhost' => 'localhost:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'foo',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_from_address' => 'postmaster',
  'mail_domain' => 'localhost',
  'mail_smtphost' => '127.0.0.1',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_smtpport' => '25',
  'updater.release.channel' => 'stable',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'tempdirectory' => '/var/www/nextcloud/tmp',
  'log_type' => 'syslog',
  'logfile' => 'nextcloud.log',
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Debian

#### Web server error log
<details>
<summary>Web server error log</summary>

```
nothing
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{PHP} fopen(): Filename cannot be empty at /var/www/sites/nextcloud/apps/logreader/lib/Controller/LogController.php#56
Feb 01 15:24:32 server02 ownCloud[25349]: {index} Exception: {"Exception":"Exception","Message":"Error while opening ","Code":0,"Trace":"#0 \/var\/www\/sites\/nextcloud\/apps\/logreader\/lib\/Controller\/LogController.php(73): OCA\\LogRe
ader\\Controller\\LogController->getLogIterator()\n#1 [internal function]: OCA\\LogReader\\Controller\\LogController->get(50, 0)\n#2 \/var\/www\/sites\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_arra
y(Array, Array)\n#3 \/var\/www\/sites\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\LogReader\\Controller\\LogController), 'get')\n#4 \/var\/www\/sites
\/nextcloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\LogReader\\Controller\\LogController), 'get')\n#5 \/var\/www\/sites\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteAct
ionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\LogReader\\\\C...', 'get', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)
\n#7 \/var\/www\/sites\/nextcloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#8 \/var\/www\/sites\/nextcloud\/lib\/base.php(1004): OC\\Route\\Router->match('\/apps
\/logreader...')\n#9 \/var\/www\/sites\/nextcloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/sites\/nextcloud\/apps\/logreader\/lib\/Controller\/LogController.php","Line":60}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
We should handle this more graceful (@icewind1991)

But we can't show the log if you use syslog.

**Comment by tuxmaster** [comment]
Then it will be better, to show an message about it instant to open an not existing file. 
Because it will only result in php errors messages.

**Comment by LollenJumplan** [comment]
Maybe you could make it possible to log to syslog as well as a logfile and not let them exclude each other.

**Comment by frlan** [comment]
I can reproduce this for NC 15.0.x

**Comment by cgzones** [comment]
Can not reproduce it with NC 16.0.5 or 17 anymore

**Comment by fs1** [comment]
I've the same behaviour with NC 21.0.1
In syslog I see the following, if I load the logging tab:

`May 11 23:04:24 <servername> Nextcloud[20926]: {"reqId":"4OvQpMmwUVJVan6H0lJS","level":3,"time":"2021-05-11T21:04:24+00:00","remoteAddr":"<ip>","user":"root","app":"PHP","method":"GET","url":"/nextcloud/index.php/apps/logreader/get?offset=0&count=50&levels=11111",
"message":"{\"Exception\":\"Error\",\"Message\":\"fopen(/opt/nextcloud/data/nextcloud.log): failed to open stream: No such file or directory at /var/www/<virtualhost_directory>/nextcloud/apps/logreader/lib/Log/LogIteratorFactory.php#52\",\"Code\":0,
\"Trace\":[{\"function\":\"onError\",\"class\":\"OC\\\\Log\\\\ErrorHandler\",\"type\":\"::\",\"args\":[2,\"fopen(/opt/nextcloud/data/nextcloud.log): failed to open stream: No such file or directory\",\"/var/www/<virtualhost_directory>/nextcloud/apps/logreader/lib/Log/LogIteratorFactory.php\",52,{\"levelsString\":\"11111\",\"levels\":[true,true,true,true,true],\"dateFormat\":\"Y-m-d\\\\TH:i:sP\",\"timezone\":\"UTC\",
\"log\":{\"__class__\":\"OC\\\\Log\\\\File\"}}]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/apps/logreader/lib/Log/LogIteratorFactory.php\",\"line\":52,\"function\":\"fopen\",\"args\":[\"/opt/nextcloud/data/nextcloud.log\",\"rb\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/apps/logreader/lib/Controller/LogController.php\",\"line\":61,\"function\":\"getLogIterator\",\"class\":\"OCA\\\\LogReader\\\\Log\\\\LogIteratorFactory\",\"type\":\"->\",\"args\":[\"11111\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":218,\"function\":\"get\",\"class\":\"OCA\\\\LogReader\\\\Controller\\\\LogController\",\"type\":\"->\",\"args\":[50,0,\"11111\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":127,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\LogReader\\\\Controller\\\\LogController\"},\"get\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/lib/private/AppFramework/App.php\",\"line\":157,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\LogReader\\\\Controller\\\\LogController\"},\"get\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/lib/private/Route/Router.php\",\"line\":302,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\",\"args\":[\"OCA\\\\LogReader\\\\Controller\\\\LogController\",\"get\",{\"__class__\":\"OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer\"},
{\"_route\":\"logreader.log.get\"}]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/lib/base.php\",\"line\":993,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\",\"args\":[\"/apps/logreader/get\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/index.php\",\"line\":37,\"function\":\"handleRequest\",\"class\":\"OC\",\"type\":\"::\",\"args\":[]}],\"File\":\"/var/www/<virtualhost_directory>/nextcloud/lib/private/Log/ErrorHandler.php\",\"Line\":92,\"CustomMessage\":\"--\"}",
"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","version":"21.0.1.1"}`

`May 11 23:04:24 <servername> Nextcloud[20926]: {"reqId":"4OvQpMmwUVJVan6H0lJS","level":3,"time":"2021-05-11T21:04:24+00:00","remoteAddr":"<ip>","user":"root","app":"index","method":"GET","url":"/nextcloud/index.php/apps/logreader/get?offset=0&count=50&levels=11111",
"message":"{\"Exception\":\"Exception\",\"Message\":\"Error while opening /opt/nextcloud/data/nextcloud.log\",\"Code\":0,
\"Trace\":[{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/apps/logreader/lib/Controller/LogController.php\",\"line\":61,\"function\":\"getLogIterator\",\"class\":\"OCA\\\\LogReader\\\\Log\\\\LogIteratorFactory\",\"type\":\"->\",\"args\":[\"11111\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":218,\"function\":\"get\",\"class\":\"OCA\\\\LogReader\\\\Controller\\\\LogController\",\"type\":\"->\",\"args\":[50,0,\"11111\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":127,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\LogReader\\\\Controller\\\\LogController\"},\"get\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/lib/private/AppFramework/App.php\",\"line\":157,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\LogReader\\\\Controller\\\\LogController\"},\"get\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/lib/private/Route/Router.php\",\"line\":302,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\",\"args\":[\"OCA\\\\LogReader\\\\Controller\\\\LogController\",\"get\",{\"__class__\":\"OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer\"},
{\"_route\":\"logreader.log.get\"}]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/lib/base.php\",\"line\":993,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\",\"args\":[\"/apps/logreader/get\"]},
{\"file\":\"/var/www/<virtualhost_directory>/nextcloud/index.php\",\"line\":37,\"function\":\"handleRequest\",\"class\":\"OC\",\"type\":\"::\",\"args\":[]}],\"File\":\"/var/www/<virtualhost_directory>/nextcloud/apps/logreader/lib/Log/LogIteratorFactory.php\",\"Line\":59,\"CustomMessage\":\"--\"}",
"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","version":"21.0.1.1"}`
