### ISSUE TITLE
files:scan to allow group folder selection

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#8149]
When running occ files:scan you cannot choose to scan a group folder or group folders, leaving the only option of running --all. In addition it doesn't handle group folders well https://github.com/nextcloud/server/issues/8148

Ideally group folders should be a scan option, both all group folders and individual. This facility would be particularly useful when migrating content in from other systems - administrators could pull the content directly into the file system with its existing structures and then run the group folder scan to populate it into NC

**Comment by rullzer** [comment]
Please submit to https://github.com/nextcloud/groupfolders
