### ISSUE TITLE
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded

### ISSUE THREAD

**Issue by Wondercool** [nextcloud/server#8157]
### Steps to reproduce
1. Install snap on raspberry pi
2. sudo snap install nextcloud
3.Examine daemon.log: every 1 sec this message appears:

Feb  2 13:07:21 charon nextcloud.mysql[24671]: ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
Feb  2 13:07:22 charon nextcloud.mysql[24671]: ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
Feb  2 13:07:23 charon nextcloud.mysql[24671]: ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
Feb  2 13:07:24 charon nextcloud.mysql[24671]: ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
pi@charon:/var/log $ uname -a
Linux charon 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
Raspberry Lite if I remember correctly

**Web server:**
apache2

**Database:**
mysql

**PHP version:**
No idea, it's snapped and not sure how to get the info out

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
New snap install

pi@charon:/var/log $ snap info nextcloud
name:      nextcloud
summary:   Nextcloud Server - A safe home for all your data
publisher: nextcloud
description: |
  Access, share and protect your files, calendars, contacts, communication and
  more at home and in your enterprise.
snap-id: njObIbGQEaVx1H4nyWxchk1i8opy4h54
commands:
  - nextcloud.disable-https
  - nextcloud.enable-https
  - nextcloud.manual-install
  - nextcloud.mysql-client
  - nextcloud.mysqldump
  - nextcloud.occ
services:
  nextcloud.apache:         simple, enabled, active
  nextcloud.mdns-publisher: simple, enabled, active
  nextcloud.mysql:          simple, enabled, active
  nextcloud.nextcloud-cron: simple, enabled, active
  nextcloud.php-fpm:        simple, enabled, active
  nextcloud.redis-server:   simple, enabled, active
  nextcloud.renew-certs:    simple, enabled, active
tracking:                   stable
installed:                  12.0.4snap2 (4953) 183MB devmode
refreshed:                  2018-01-29 17:42:23 +0000 UTC
channels:
  stable:                   12.0.4snap2       (4953) 183MB -
  candidate:                12.0.4snap2       (4953) 183MB -
  beta:                     12.0.4snap2       (4955) 183MB -
  edge:                     master-2018-01-31 (4998) 183MB -
  11/stable:                11.0.6snap1       (4721) 182MB -
  11/candidate:             11.0.6snap1       (4721) 182MB -
  11/beta:                  11.0.6snap1       (4721) 182MB -
  11/edge:                  11-2018-01-31     (5000) 183MB -
  12/stable:                –
  12/candidate:             –
  12/beta:                  –
  12/edge:                  12-2018-02-01     (5018) 185MB -
  13/stable:                –
  13/candidate:             13.0.0-rc2snap1   (4853) 184MB -
  13/beta:                  ↑
  13/edge:                  ↑

**Where did you install Nextcloud from:**
Via snap system

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
pi@charon:/var/log $ snap version
snap      2.30
snapd     2.30
series    16
raspbian  9
kernel    4.9.59-v7+

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

I can't, it's snapped

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
Please submit to https://github.com/nextcloud/nextcloud-snap
