### ISSUE TITLE
 Update 12.0.4 -> 12.0.5 or 13.0.0.beta4: No more 3rdparty Apps from the store? support nc12

### ISSUE THREAD

**Issue by StephaneCouturier** [nextcloud/server#8159]
Hi,
I have found this issue when updating from 12.0.4 to 12.0.5 and tried to update to 13.0.0.4beta to see if it corrects it, but it does not.

https://help.nextcloud.com/t/update-12-0-4-12-0-5-no-more-3rdparty-apps-from-the-store/26787?u=steph38

Thanks.

Nextcloud version (eg, 10.0.2): 12.0.5
Operating system and version (eg, Ubuntu 16.04): unknown linux - shared OVH web host
Apache or nginx version (eg, Apache 2.4.25): 2.4.x
PHP version (eg, 5.6): 7.0

The issue you are facing:
Hi,

I have updated from 12.0.4 -> 12.0.5 but my usual apps, Contacts, Tasks, and Calendars that I use a lot are gone and cannot be found in the “+ Apps” menu.
It actually looks like all the 3rdparty apps are not accessible anymore.

I only see these 4 sub menu on the right, and cannot find Contacts and Calendars in them:

    Your apps
    Enabled apps
    Disabled apps
    App bundles

My user is in the admin group, no change here.

I checked release notes and other things, not sure I missed something, so it looks like a migration bug.
Log error is suggesting this too.

Thank you!

Is this the first time you’ve seen this error? (Y/N):
Yes, in the past the App may having been disable but I could re-enable them. no further action after a migration.

Steps to replicate it:

Note: I have a second hosted web on which I install 13.0.0beta4 after the 12.0.5 > same issue.

The output of your Nextcloud log in Admin > Logging:
many errors such as:

Error	appstoreFetcher	GuzzleHttp\Exception\ConnectException: cURL error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

    /home/xxxx/xxxx/xxxx/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\ConnectException))
    /home/xxxx/xxxx/xxxx/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /home/xxxx/xxxx/xxxx/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)
    /home/xxxx/xxxx/xxxx/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
    /home/xxxx/xxxx/xxxx/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
    /home/xxxx/xxxx/xxxx/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
    /home/xxxx/xxxx/xxxx/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /home/xxxx/xxxx/xxxx/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
    /home/xxxx/xxxx/xxxx/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('https //apps.ne...', Array)
    /home/xxxx/xxxx/xxxx/lib/private/App/AppStore/Fetcher/Fetcher.php - line 99: OC\Http\Client\Client->get('https //apps.ne...', Array)
    /home/xxxx/xxxx/xxxx/lib/private/App/AppStore/Fetcher/AppFetcher.php - line 66: OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
    /home/xxxx/xxxx/xxxx/lib/private/App/AppStore/Fetcher/Fetcher.php - line 162: OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
    /home/xxxx/xxxx/xxxx/lib/private/Installer.php - line 394: OC\App\AppStore\Fetcher\Fetcher->get()
    /home/xxxx/xxxx/xxxx/settings/Controller/AppSettingsController.php - line 333: OC\Installer isUpdateAvailable('user_external', Object(OC\App\AppStore\Fetcher\AppFetcher))
    [internal function] OC\Settings\Controller\AppSettingsController->OC\Settings\Controller\{closure}(*** sensitive parameters replaced ***)
    /home/xxxx/xxxx/xxxx/settings/Controller/AppSettingsController.php - line 338: array_map(Object(Closure), Array)
    [internal function] OC\Settings\Controller\AppSettingsController->listApps('disabled')
    /home/xxxx/xxxx/xxxx/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /home/xxxx/xxxx/xxxx/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\AppSettingsController), 'listApps')
    /home/xxxx/xxxx/xxxx/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\AppSettingsController), 'listApps')
    /home/xxxx/xxxx/xxxx/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'listApps', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /home/xxxx/xxxx/xxxx/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /home/xxxx/xxxx/xxxx/lib/base.php - line 1005: OC\Route\Router->match('/settings/apps/...')
    /home/xxxx/xxxx/xxxx/index.php - line 48: OC handleRequest()
    {main}

The output of your config.php file in /path/to/nextcloud (make sure you remove any identifiable information!):

    <?php
    $CONFIG = array (
      'instanceid' => 'xxxxxxx',
      'passwordsalt' => 'xxxxxxxx',
      'secret' => 'xxxxxx',
      'trusted_domains' => 
      array (
        0 => 'www.xxxxxx.com',
      ),
      'datadirectory' => '/home/xxxxxx/xxxxxx/data',
      'overwrite.cli.url' => 'https://www.xxxxxxx.com/xxxx',
      'dbtype' => 'mysql',
      'version' => '12.0.5.3',
      'dbname' => 'xxxxxx',
      'dbhost' => 'xxxxxxx',
      'dbtableprefix' => 'oc_',
      'dbuser' => 'xxxxxxx',
      'dbpassword' => 'xxxxxxx',
      'logtimezone' => 'UTC',
      'installed' => true,
      'theme' => '',
      'loglevel' => 2,
      'maintenance' => false,
      'memcache.local' => '\\OC\\Memcache\\ArrayCache',
    ); 

The output of your Apache/nginx/system log in /var/log/____:

no access to this (shared host).

**Comment by blizzz** [comment]
Is it still an issue? can your system connect to the Internet (not being connected to)?

**Comment by MorrisJobke** [comment]
No feedback on this one - closing. It looks like your server has no outbound internet connection to download it via our app store.
