### ISSUE TITLE
Idea: Progressive Web App

### ISSUE THREAD

**Issue by joewashear007** [nextcloud/server#8170]
**Thank you for all your hard work, Nextcloud is great!**

Can we make Nextcloud a [progressive web app](https://developer.mozilla.org/en-US/Apps/Progressive)? 

This is where the trend on the web seem to be going. A specific use case is for my dad who has a phone from work that is locked down from installing any apps, It would be nice for him to be able to "install" a PWA and use my hosted version of Nextcloud easily. 

I honestly don't know how much work this would take, but I think it would nice feature. Does this fit into the vision for Nextcloud? 

Thank you, Joseph

**Comment by MorrisJobke** [comment]
This is already working like that mostly. (only the offline part is not working, but usually also not that helpful in our use case)

Just browse to that web page and then add it to your start screen. Then it is available without the browser controls and should work mostly. Obviously background photo upload will not work, but I don't  know if this would even be possible right from the browser.

**Comment by MorrisJobke** [comment]
Let's continue this in specific tickets with problems that have been identified on the way there. Something like the better integration into Chrome PWA #8563

**Comment by alxlg** [comment]
@MorrisJobke  I think the point of PWA is contents being available offline. A PWA-enabled Nextcloud would let you browse files, calendars, contacts etc without being able to download them (of course).

**Comment by bquast** [comment]
https://chromeunboxed.com/chrome-73-mac-os-pwa-support-all-desktops/

**Comment by bleonard252** [comment]
I see this as a way for me to have my installation use my computer's cache to load parts of NextCloud rather than having to wait one minute for it to load every time I switch pages.
