### ISSUE TITLE
NC13 RC4 encryption - missing Users File Recovery Keys Option

### ISSUE THREAD

**Issue by mr-bolle** [nextcloud/server#8171]
### Steps to reproduce
1. Enable server-side encryption
2. select Default encryption module
3. login and logout of the admin user

### Expected behaviour
After successful activation of the encryption, it was possible to create a recovery key. This possibility i can't find into the version 13 RC4 [NC documentation](https://docs.nextcloud.com/server/12/admin_manual/configuration_files/encryption_configuration.html?highlight=encryption#enabling-users-file-recovery-keys)

*Till now there is no Docker Image for the PreRelease version, I have created this myself
**maybe this i dit wrong** ->  [pull request nextcloud/docker](https://github.com/nextcloud/docker/pull/221)*

### Actual behaviour
There is no possibility to enter a recovery key

## Server configuration detail

**Operating system:** Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64

**Webserver:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** sqlite3 3.15.1

**PHP version:** 7.1.13
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, intl, ldap, mcrypt, memcached, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, redis, zip, Zend OPcache

**Nextcloud version:** 13.0.0 RC 3 - 13.0.0.12  | 13.0.0 RC 4 - 13.0.0.13

**Updated from an older Nextcloud/ownCloud or fresh install:** Docker Image

**Where did you install Nextcloud from:** /nextcloud/docker ->  [pull request nextcloud/docker](https://github.com/nextcloud/docker/pull/221)

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - comments: 1.3.0
 - dav: 1.4.6
 - encryption: 2.0.0
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.178.29:813"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/192.168.178.29:813",
    "dbtype": "sqlite3",
    "version": "13.0.0.12",
    "installed": true
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Operating system:** 

## Logs
*no errror log available*

**Comment by rullzer** [comment]
@schiessle

**Comment by schiessle** [comment]
I can reproduce it and will have a look

**Comment by schiessle** [comment]
Ah, OK... You set up encryption from scratch, right? We use by default the master key now, in this case no recovery key is needed. If you switch to per-user-keys via occ or upgrade from a older version with encryption enabled the option is still there.

**Comment by mr-bolle** [comment]
Hi, yes i set the encryption from scratch. And if i disable the master key from the command prompt, and reload the Admin Page i can set the master recovery key. 

many thanks

**Comment by DecaTec** [comment]
@schiessle What's considered as the 'master key' here? Is it the (1st) admins password? If not, how can the master key be obtained?

**Comment by mr-bolle** [comment]
@DecaTec have a look at the post from 5.2.
> occ encryption:disable-master-key

**Comment by DecaTec** [comment]
@mr-bolle Yes, when running this occ command I can see input fields in order to set a recovery password again.

But I don't want to disable the master key, I only want to know what IS the master key (when the occ command was not run).

**Comment by lenusch** [comment]
uhm, i was missing this option too, i was searching for hours... 
Whats the Masterkey then, IF your setup is from scratch? 
(The Keys in Config? Or the Admins first Password?)

**Comment by ShapeShifter499** [comment]
I also have this concern.  I found this post through some online searching
