### ISSUE TITLE
[NC 12.0.5] in User Profil => Security  - Some tooltips don't dissipear

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#8174]
On Nextcloud 12.0.5 production with firefox 58.

Sometimes on the WEBUI in the user profil in the Security section, some tooltips indicating the time will not leave / disappear after the mouse has passed, even if the "session" has been removed.

![bug_capture d ecran_2018-02-04_16-00-58](https://user-images.githubusercontent.com/8572474/35778940-bd8a1a3a-09c5-11e8-8999-0fc2257706d6.png)

In this screenshot, the event is removed but the tooltips is display.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers @nextcloud/javascript

**Comment by szaimen** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
