### ISSUE TITLE
Invalid lang attribute on head element (should be en-GB, not en_GB)

### ISSUE THREAD

**Issue by coliff** [nextcloud/server#8180]
Currently the head tag for en-gb users is:
```
<html class="ng-csp" data-placeholder-focus="false" lang="en_GB">
```

The lang attribute's value is invalid, it should be en-gb (with a dash), not en_gb (with an underscore).

See more at this page: https://www.w3.org/TR/selectors-3/#attribute-selectors

Currently Nextcloud is showing this as an error in the [Google Lighthouse](https://developers.google.com/web/tools/lighthouse/) Accessibility audit - so would be good to fix.

**Comment by rullzer** [comment]
Woeps... fair point. I'll fix this,
