### ISSUE TITLE
Thunderbird constantly Reminds all Alarms since updating Nextcloud

### ISSUE THREAD

**Issue by phlixi** [nextcloud/server#8185]
### Steps to reproduce
1. create a new user in nextcloud (in this example i use "caltestacc")
2. make a new calendar (in this example "cal1")
3. install thunderbird
4. subscribe to "cal1" in my case, i take the displayed url:
https://nc.example.com/remote.php/dav/calendars/caltestacc/cal1/
...which you get by clicking on the "..." in the web ui
(except i obviously use something different than "example.org")
5. in thunderbird create an entry for "cal1" for example for 2018 feb 5th, 17:00. set "remind 15 before" (which is 16:45).

### Expected behaviour
Tell us what should happen
there should pop up a reminder at 16:45 on the 5th feb 2018. 
once dismissed, there should not be any further reminder about this.

### Actual behaviour
the popup comes, but it also comes for all other calendar entries, and it does not only come 16:45 on feb 5th 2018, but from now on everytime thunderbird syncs, default seems to be every 30 minutes.

this is new since i upgraded from owncloud to nextcloud 12. the "actual behaviour"-part, the never ending reminders that can not be dismissed, are new since this upgrade

### Server configuration

**Operating system**:
i dont know

**Web server:**
i guess apache

**Database:**
unclear

**PHP version:**
probably 5.6

**Nextcloud version:** (see Nextcloud admin page)
Version
Nextcloud 12.0.5
(stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
not exactly sure, but was running ownCloud 8.something and followed upgrade howto which afaik was something like nc9, activate card/cal, then maybe nc10, activate card/cal again and the rest i think was automatically

**Where did you install Nextcloud from:**
webinstaller

**Signing status:**
No errors have been found.

**List of activated apps:**

<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

no access. 

however, besides the automatically installed and enabled addons, there is installed and enabled:

Calendar
1.5.7

Contacts
2.0.1


```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

let me know if this is needed. ill paste it then
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
using thunderbird english version Thunderbird Setup 52.6.0

https://www.mozilla.org/en-US/thunderbird/all/?q=English+%28US%29

...no other stuff installed, just a fresh VM with fresh installed thunderbird, current version

**Operating system:**
win 10 freshly patched, no other apps installed (using dedicated VM for this test)
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by dmaroulidis** [comment]
It's probably Thunderbird's problem.

**Comment by phlixi** [comment]
thanks dmaroulidis for looking into this. Would you mind sharing how you come to this conclusion allthogh it started happening after the update of owncloud?

Because i came to the conclusion that this has to be a nextcloud thing. because it started right after updating owncloud.

**Comment by dmaroulidis** [comment]
Ok, so check Thunderbird's preferences for any default values that are similar to what you're experiencing. Otherwise there might be a problem with your Nextcloud installation, which as you've said was an OwnCloud one before your upgrade. Check your server and Nextcloud's logs for any anomally / error. If you don't find anything obvious, then backup your data and do a clean install of Nextcloud 13.

**Comment by danieldietsch** [comment]
I have the same problem, I cannot dismiss reminders on recurring events. 
My Nextcloud installation is fresh, but I did not use Calendar until recently. 
It seems for me the issue is restricted to a) recurring events with reminders and b) calendars that are shared from another user (I can modify them). 

**Client** 
Thunderbird 52.6.0 and Lightning 5.4.6 

**Server**
Nextcloud 13.0 and Calendar 1.6.1
OS: Gentoo with 4.14.11 kernel
Apache 2.4.27-r1 behind HAProxy 1.8.4 
PHP 7.1 
MySQL 5.6.39 

I am not sure what logs could be of interest. Let me know and I can try and provide them.

**Comment by Barben360** [comment]
Same problem here.
