### ISSUE TITLE
Change default permissions on sharebymail

### ISSUE THREAD

**Issue by Cybso** [nextcloud/server#8186]
Please modify ShareByMailProvider.php to ignore 'permissions' for new shares but use PERMISSION_READ by default (method "createMailShare"), or add a configuration option to define a umask for new permissions.

The current behaviour is really unexpected (and possible dangerous) for users that are accustomed with other file sharing services like Dropbox or Google Drive. With this simple change the user would still be able to grant edit permission explicitly.

### Steps to reproduce
1. Create a new "share by mail"

### Expected behaviour
The recipient can download the shared content, but is not able to modify it.

### Actual behaviour
If the user doesn't pay attention the recipient is able to misuse the shared file or directory.

### Server configuration
Doesn't matter.

**Comment by Cybso** [comment]
There is another pull request with a more generic approach: #7363

**Comment by MorrisJobke** [comment]
Fixed by #7363
