### ISSUE TITLE
On the Gallery page, uploading the same file with a completely different prompt box, choosing to keep the new and old files, the Continue button is not available

### ISSUE THREAD

**Issue by HandsomeBoby** [nextcloud/server#8191]
### Steps to reproduce
1.Open the Gallery application and upload an image
2.Upload the same image file again, a dialog box will pop up for file differences
3.Choose to keep new files and old files, click the Continue button below does not reflect

### Expected behaviour
Tell us what should happen
Click to upload, as the list of files upload difference file
![nextcloud](https://user-images.githubusercontent.com/19202505/35838182-09b6ead6-0b25-11e8-8742-4d0cb9486407.png)

### Actual behaviour
Tell us what happens instead
Can not click, can not upload
### Server configuration

**Operating system**:

**Web server:**

**Database:**10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04

**PHP version:**PHP 7.0.22

**Nextcloud version:** (see Nextcloud admin page)14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**fresh install

**Where did you install Nextcloud from:**Nextcloud.zip

**Signing status:**NO

**Comment by HandsomeBoby** [comment]
@blizzz @mnutt  Thanks.

**Comment by HandsomeBoby** [comment]
@blizzz @MorrisJobke @icewind1991 Thanks.

**Comment by MorrisJobke** [comment]
Duplicate of https://github.com/nextcloud/gallery/issues/398
