### ISSUE TITLE
Link to docs.nextcloud.com/server/13/ doesn't work -> File not found

### ISSUE THREAD

**Issue by santasonic** [nextcloud/server#8198]
Hi community,

thank you very much for the great work. I've found some issues around links going to the documentation of version 13. This issue is present on your website as well inside the server-application like https://docs.nextcloud.com/server/13/go.php?to=admin-theming-icons

Kind regards

Carsten

**Comment by rullzer** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
Should work again. Sorry for the trouble.

**Comment by MorrisJobke** [comment]
And thanks for the report @santasonic 👍
