### ISSUE TITLE
some browser can't download files!

### ISSUE THREAD

**Issue by vergessen-lzx** [nextcloud/server#8200]
<?xml version="1.0" encoding="utf-8"?><d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>  <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured</s:message></d:error>

**Comment by stratege1401** [comment]
would you mind to list them ... Opera ? Firefox ? Chrome ?  + versioning would help ... I've never test somebrowser ... a new one ?  !=)

**Comment by MorrisJobke** [comment]
Please fill out the issue template: https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md

**Comment by MorrisJobke** [comment]
No feedback on this one: closing
