### ISSUE TITLE
Error when upgrading spreed from NC 12.0.5 to 13.0.0. - shared hosting

### ISSUE THREAD

**Issue by DaCryptor** [nextcloud/server#8208]
Cannot upgrade to NC13.

NC-upgrade itself worked, but spreed won't update.

Error:

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `HhHvb_talk_rooms` (`name`, `token`, `type`, `password`) VALUES(?, ?, ?, ?)' with params ["", "6634", 3, ""]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6634' for key 'tr_room_token'

What can I do to have this fixed? Already had spreed installed in NC 12.0.5

Please help.

**Comment by MorrisJobke** [comment]
cc @Ivansss @nickvergessen 

This should be reported in the spreed/talk repo: https://github.com/nextcloud/spreed

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/spreed/issues/630
