### ISSUE TITLE
Document support for PHP 7.2 in Changelog

### ISSUE THREAD

**Issue by kbabioch** [nextcloud/server#8210]
Given that there was much discussion about Nextcloud's support of PHP 7.2 before the release (see #7384 #6786), I found it astounding that the [official Changelog][1] does not contain any such reference.

This should be added, so people know whether or not they can finally upgrade PHP. Information like this should **always** be part of the Changelog.

[1]: https://nextcloud.com/changelog/

**Comment by tflidd** [comment]
Good point, you can either make the changes yourself and submit a pull request (https://github.com/nextcloud/nextcloud.com/blob/70d634c05d5c10deb550b0b1fcb8d45051b37b5c/page-changelog.php) or we'll wait for @jospoortvliet

**Comment by MorrisJobke** [comment]
We have it listed already in the 13 admin docs: https://docs.nextcloud.com/server/13/admin_manual/installation/system_requirements.html#recommended-setup-for-running-nextcloud

The 12 docs state that it is not compatible: https://docs.nextcloud.com/server/12/admin_manual/installation/system_requirements.html#recommended-setup-for-running-nextcloud

Maybe we should add the upper limit as well to not run into the same issues as with 12 some time ago.

**Comment by MorrisJobke** [comment]
Fixed by https://github.com/nextcloud/nextcloud.com/pull/786
