### ISSUE TITLE
WebDAV timeout on login

### ISSUE THREAD

**Issue by farbro** [nextcloud/server#8211]
### Steps to reproduce
I installed Nextcloud and had it running flawlessly for a few days. But today Nextcloud only appeared as a blank page, and it appeared mariadb had been shut down for some reason, indicated by the following error in `/var/log/apache2/error.log`:

    PHP Warning:  PDO::exec(): MySQL server has gone away in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 57
    PHP Warning:  PDO::exec(): Error reading result set's header in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 57
    PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused in /var/www/nextcloud/lib/private/DB/Connection.php:61\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/nextcloud/lib/private/DB/Connection.php(148): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doc in /var/www/nextcloud/lib/private/DB/Connection.php on line 61

Clueless on what caused the error, (memory leak?) I restart mariadb and had Nextcloud up and running again. Now when I try to login with new users through any WebDAV client, I get "Internal Server Error" because the server's response to Pound times out.

### Expected behaviour
Login over WebDAV works.

### Actual behaviour
Login over WebDAV times out. Already connected users (all from the same Nextcloud desktop client) are still connected and does sync. If I log one user out, it won't be allowed to login again.

I'm using Pound as reverse proxy, which reports:

    granlund pound: (7fd04bc44700) e500 for 192.168.1.1 response error read from 192.168.1.26:80/PROPFIND /remote.php/webdav/ HTTP/1.1: Connection timed out (30.059 secs)

`/var/log/apache2/access.log:`

    192.168.1.20 - per [06/Feb/2018:22:51:47 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1671 "-" "Mozilla/5.0 (Linux) mirall/2.3.2 (Nextcloud)"

`/var/log/apache2/error.log` shows nothing about this.

### Server configuration

**Operating system**:
Debian 9
**Web server:**
Apache 2.4.25
**Database:**
mariadb 15.1
**PHP version:**
2.0.27
**Nextcloud version:** (see Nextcloud admin page)
12.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-13.0.0.tar.bz2
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - dav: 1.3.1
  - deck: 0.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ochm6m262chv",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xx.xxxx.xx"
        ],
        "datadirectory": "\/nextcloud-data",
        "overwrite.cli.url": "http:\/\/xx.xxxx.xx",
        "dbtype": "mysql",
        "version": "12.0.5.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_type": "syslog",
        "logfile": "",
        "loglevel": "2",
        "trusted_proxies": [
            "192.168.1.20"
        ],
        "overwritehost": "fog.neek.se",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "overwritecondaddr": "^192\\.168\\.1\\.20$"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
nfs
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
</details>

### Client configuration
**Browser:**

**Operating system:**
Linux mint
#### Web server error log
<details>
<summary>Web server error log</summary>

```
`/var/log/syslog` and `/var/log/messages` shows nothing during a failed login.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
(Setup to log to syslog)
```
</details>

**Comment by MorrisJobke** [comment]
> SQLSTATE[HY000] [2002] Connection refused
> MySQL server has gone away

Those two look like your mysql server died or is not running. Please check if there is an issue with your mysql first.
