### ISSUE TITLE
Upgrade from 12.0.4 to 13 fail : Doctrine\DBAL\Schema\SchemaException: An index with name 'idx_e98f2ec48b26c2e9' was already defined on table 'oc_cards'.

### ISSUE THREAD

**Issue by matlem037** [nextcloud/server#8212]
Hello 

I am in trouble with my nextcloud instance : i try to get upgrade from 12.0.4 to 13 from web admin page and the installation fail. 

### Steps to reproduce
1. Launch upgrade from admin page
2. Upgrade Fail
3. Change maintenance mode to false in config.php
4. restart Update from web
5. Upgrade fail with message : Doctrine\DBAL\Schema\SchemaException: An index with name 'idx_e98f2ec48b26c2e9' was already defined on table 'oc_cards'.

### Expected behaviour
Upgrade to v13

### Actual behaviour
Upgrade fail with the message : Doctrine\DBAL\Schema\SchemaException: An index with name 'idx_e98f2ec48b26c2e9' was already defined on table 'oc_cards'.

 sudo -u www-data php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <dav> ...
Doctrine\DBAL\Schema\SchemaException: An index with name 'idx_e98f2ec48b26c2e9' was already defined on table 'oc_cards'.
Update failed
Maintenance mode is kept active
Reset log level

### Server configuration

**Operating system**:Raspbian Stretch

**Web server:**Apache 2.4.25

**Database:**mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2

**PHP version:**PHP 7.0.27-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page) 12.04 to 13

**Updated from an older Nextcloud/ownCloud or fresh install:**upgrading to13

**List of activated apps:**
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.2.0
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.3.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.4.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.2.0
  - survey_client: 1.1.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.2.3
  - unsplash: 1.0.5
  - updatenotification: 1.3.0
  - workflowengine: 1.2.0
Disabled:
  - announcementcenter
  - apporder
  - audioplayer
  - bookmarks
  - bruteforcesettings
  - calendar
  - checksum
  - contacts
  - dashboard
  - deck
  - files_clipboard
  - files_downloadactivity
  - groupfolders
  - keeweb
  - metadata
  - notes
  - quota_warning
  - ransomware_protection
  - spreed
  - tasks
  - twofactor_totp
  - user_external
  - user_ldap
  - weather

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.maisonlemaire.ovh"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.maisonlemaire.ovh",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": true,
        "theme": "",
        "loglevel": 0,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using encryption:** no

Thanks for anyone help
And thanks nextcloud for nextcloud :-)

**Comment by chrone81** [comment]
Same issue here.

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing '
                        UPDATE `oc_filecache`
                        SET `mimetype` = ?
                        WHERE `mimetype` <> ? AND `mimetype` <> ? AND `name` COLLATE utf8mb4_general_ci LIKE ?
                ' with params [false, 6, false, "%.m3u"]:

SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: ''
Update failed

```

**Comment by BandonRandon** [comment]
Same issue :-/

**Comment by matlem037** [comment]
No it was a fresh nexcloud install.

**Comment by matlem037** [comment]
Fixed ! Just drop the index on the table oc_cards !

Hope it will help

**Comment by BandonRandon** [comment]
@matlem037 Thanks for  the update. Let me give dropping the index a go. I do think that even if that works it's more a work around. The upgrade script itself should be checking for the index and either skipping it or dropping it in the script. 

I would recommend opening this issue back up for someone at NextCloud to take a proper look to be able to fix the underlying issue.

**Comment by matlem037** [comment]
Good idea

I reopen the case

**Comment by MorrisJobke** [comment]
cc @georgehrke @nickvergessen

**Comment by lancepatate** [comment]
I just "GRANT ALL PRIVILEGES" to the MySQL nextcloud database owner to solve this issue.

**Comment by nickvergessen** [comment]
Which privileges had you granted before?

**Comment by lancepatate** [comment]
SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES

**Comment by nisses** [comment]
alter table oc_cards drop index idx_e98f2ec48b26c2e9;

this helped in my case.

**Comment by clintidau** [comment]
I encountered this same error while updating from 13.0.3 to 13.0.4

> Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Doctrine\DBAL\Schema\SchemaException: An index with name 'idx_e98f2ec48b26c2e9' was already defined on table 'oc_cards'.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
