### ISSUE TITLE
Upgrade 12.0.4 to 13 failed on shared hosting

### ISSUE THREAD

**Issue by robertronq** [nextcloud/server#8213]
Tried to run upgrade via web. Made it all the way to "Go back to your Nextcloud instance to finish your upgrade" Then got a blank page "HTTP error 500".
Also tried running "php occ upgrade" but im getting this error.  I appreciate any help you can provide. 

> php occ maintenance:repair
> X-Powered-By: PHP/4.4.9
> Content-type: text/html
> 
> <br />
> <b>Fatal error</b>:  main() [<a href='function.require'>function.require</a>]: Failed opening required '__DIR__/console.php' (include_path='.:/usr/lib/php4.4') in <b>/homepages/31/d223016723/htdocs/owncloud/occ</b> on line <b>11</b><br />

Updater.log
[updater.log](https://github.com/nextcloud/server/files/1701955/updater.log)

**Comment by tflidd** [comment]
The errors in the log only state that there was a php.ini and old_php.ini in your `updater` folder. I'm not really sure but it looks like the process continues. Can you check the version number in your `config/config.php`?

> Also tried running "php occ upgrade" but im getting this error.
> X-Powered-By: PHP/4.4.9

You should use a newer php version (5.6 or newer) for that. Your provider has perhaps different php versions and you need to know the name of the binary of a newer version (php5, php5.6, ..), your provider should have this in the documentation or their support should know it.

**Comment by robertronq** [comment]
Thank you for the quick response. 
I removed the php.ini and old_php.ini file and ran the update. My host php version is actually 7.1. 
I've included my config.php, renamed it to config.txt, it doesnt indicate the php version.  

[config.txt](https://github.com/nextcloud/server/files/1702147/config.txt)

**Comment by tflidd** [comment]
Then probably you loaded the code but did not run the actual update (please change your db password, you should not publish it here). Normally, it is the right way to run the upgrade command via terminal, you just need the right php version. For 1&1 try this:
`/usr/bin/php7.1-cli occ upgrade`

**Comment by robertronq** [comment]
Thank you VERY MUCH !!!
That fixed it. Now I have to see if i can update the cli to the newer php version. So I dont have to remember this next time. Thank you again !!!
