### ISSUE TITLE
occ commands for creating new webcal subscriptions / importing calendars

### ISSUE THREAD

**Issue by nkakouros** [nextcloud/server#8222]
I am trying to automate nextcloud installation with ansible and I was wondering if there is an option to add external calendars. I have found the occ dav:create-calendar option to create new calendars.

**Comment by georgehrke** [comment]
If someone wants to go ahead and implement this: 
- take a look at how the [create-calendar command](https://github.com/nextcloud/server/blob/master/apps/dav/lib/Command/CreateCalendar.php) works
- the [iCalendar Splitter](https://github.com/nextcloud/3rdparty/blob/f2974c2e72b2ad5ab7ae745936c4d866405d2b61/sabre/vobject/lib/Splitter/ICalendar.php) comes very handy here to split up an entire calendar into single events

**Comment by georgehrke** [comment]
@tterranigma for the meantime you can probably automate importing calendars with the command line tool `cadaver`

**Comment by arunikayadav42** [comment]
Is anybody working on this issue or can I get started?

**Comment by georgehrke** [comment]
Duplicate of https://github.com/nextcloud/server/issues/564
