### ISSUE TITLE
Load jQuery from a CDN for improved performance

### ISSUE THREAD

**Issue by coliff** [nextcloud/server#8226]
It'd be good if Nextcloud loaded jQuery from a CDN. This would improve performance as by default, web browsers limit the number of active connections for each domain. When the number of resources to download exceeds that limit, users experience slow page load times as downloads are queued - by allowing jQuery to download from a CDN other JS files can download simultaneously.
It'd be possible to have a local fallback too if you didn't want to be 100% reliant on a 3rd party for the site to work... e.g.
```
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script>window.jQuery || document.write('<script src="core/vendor/jquery-2.1.4.min.js"><\/script>')</script>
```
The jQuery CDN is very popular so there is a chance a user already has jQuery in their cache so it won't even need to be downloaded - further improving load time.
If you have a high-traffic site and paying for bandwidth this could save a bit of money over time.

**Comment by MorrisJobke** [comment]
We will not do this, because our project aims for privacy of user data and using a CDN is not helpful here. For the limitations of connections the HTTP 2 standard help a lot and basically removes this problem.

**Comment by wikimas** [comment]
Im not sure how adding a CDN for default jquery would impede on user privacy? You could always make it optional?
