### ISSUE TITLE
Connection to server lost only on Mobile network

### ISSUE THREAD

**Issue by DanLeonelli** [nextcloud/server#8231]
Nextcloud version: 13.0.0
Operating system and version: No idea
Apache or nginx version: Apache 2.2.34
PHP version: 7.0.25

The issue you are facing:

Whenever I try to access the site using WiFi connection, everything works fine for all users accounts. However, when trying to access via mobile network (on smartphone or laptop) nothing works: calendar is stuck on loading and files just shows the error: "Connection to server lost". This only happens when using Mobile network on any kind of browser for everyone.

Is this the first time you've seen this error? YES (Been happening for 4 days)

Steps to replicate it:

1. Make sure you are connected via 4G/3G
2. Access account
3. Go to calendar/files

I would really appreciate some help as nobody can use this on the go anymore and I feel really worried and frustrated.

![img_1871](https://user-images.githubusercontent.com/35517527/35921714-72b75326-0be9-11e8-88bc-0e2e7f157a80.jpg)

**Comment by DanLeonelli** [comment]
Bump

**Comment by blizzz** [comment]
that's a network issue, not one inside our software. this can be several reasons, e.g. dns does not resolve the hostname, or an ipv4/ipv6 mismatch, or…

**Comment by Atom02** [comment]
@DanLeonelli did you solve this? I also experience it on one of my mobile carrier
