### ISSUE TITLE
Feature Request - Hidden users/groups from "collaboration"

### ISSUE THREAD

**Issue by Luticus** [nextcloud/server#8234]
I originally raised this issue with the talk app where it was pointed out that it was just populating the same list as other sharing actions were.  

My situation is this:  I use groups for more than just sharing files, etc.  I have many groups set up so that I can easily enable or disable apps for users, add storage drive access, etc.  I also have accounts that are there for admin purposes, for instance an admin will have user.admin and user accounts.  What I would like is a way to hide specific accounts/groups from the share lists/collaboration so that users cannot attempt to share files with or invite to a call what is essentially a service account/group.

**Comment by mtkraai** [comment]
I found this looking for a solution/bug/whatever after noticing that **disabled** users are included in the user list in the Talk app.

Disabled users should be excluded by default. It would also be very nice to be able to configure the list in some way.

**Comment by army1349** [comment]
> 
> 
> I originally raised this issue with the talk app where it was pointed out that it was just populating the same list as other sharing actions were.
> 
> My situation is this: I use groups for more than just sharing files, etc. I have many groups set up so that I can easily enable or disable apps for users, add storage drive access, etc. I also have accounts that are there for admin purposes, for instance an admin will have user.admin and user accounts. What I would like is a way to hide specific accounts/groups from the share lists/collaboration so that users cannot attempt to share files with or invite to a call what is essentially a service account/group.

If you use LDAP, you can filter out groups using LDAP Query.

**Comment by Luticus** [comment]
> If you use LDAP, you can filter out groups using LDAP Query.

You can only do that with groups made in ldap though.  Not with groups made in Nextcloud that ldap or other users are joined to, of which I have many.  I really don't want users seen drive_rw (a hypothetical group that give some users access to a disk with read/wright privs) groups as possible options in the talk app, for instance.

**Comment by army1349** [comment]
> 
> 
> > If you use LDAP, you can filter out groups using LDAP Query.
> 
> You can only do that with groups made in ldap though. Not with groups made in Nextcloud that ldap or other users are joined to, of which I have many. I really don't want users seen drive_rw (a hypothetical group that give some users access to a disk with read/wright privs) groups as possible options in the talk app, for instance.

I see.

**Comment by clawoflight** [comment]
+1 from me. Similar use-cases includes using groups to manage access to applications.

**Comment by Luticus** [comment]
If anyone can give me some pointers on where the code for something like this should be implemented it would be a huge help.  I'm not really a php coder these days but I'd be willing to give it a shot.  I really want to move to Talk as my primary chat, voice/video solution, but this is a huge blocker.  I definitely have certain groups/users that I don't want real users trying to chat with or share things to.

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
