### ISSUE TITLE
N13 breaks on loading custom background image: line 97 <img src="

### ISSUE THREAD

**Issue by Paradiesgestalter** [nextcloud/server#8243]
Just tried to upgrade from 12.5 to 13.0 but loading of start page breaks at line 97 where the custom background image should be loaded inside div class="logo":
line 97: 										<img src="

My environment: Debian 8.10, Plesk Onyx 17.5.3.40, PHP 7.1.14, MySQL/MariaDB 10.0.32

I use the same background image since Version 10 and any update/upgrade so far went well, never got any message concerning background image.

updater.log has no entry from this update attempt.
nextcloud.log entries all refer to "version":"12.0.5.3" since upgrade has not run yet.
latest entry in nextcloud.log has strange date (year 3003!!): 

3003-02-07 21:43:56 | {"reqId":"xyz...","remoteAddr":"xx.xx.xx.xx","app":"no  app in context","message":"Exception:  {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\SyntaxErrorException\",\"Message\":\"An  exception occurred while executing 'DELETE FROM `oc_reader_bookmarks` b  WHERE b.file_id = ?' with params :\\n\\nSQLSTATE[42000]: Syntax error  or access violation: 1064 You have an error in your SQL syntax; check  the manual that corresponds to your MariaDB server version for the right  syntax to use near 'b WHERE b.file_id = '3003'' at line  1\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/meinservername.tld\\\/httpdocs\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128):   Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An  exception oc...',  Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 ....
-- | --

Am I the only one who uses a custom background image or does it work for anybody else?

**Comment by Paradiesgestalter** [comment]
**Here is the workaround I found to the bug I reported above:**
I opened the database directly in phpMyAdmin and searched for any image setting. Finally found "theming" settings in table oc_appconfig and changed configkey enabled to "no". Then I reloaded the start page and it did the upgrade to 13.0 without any error messages. I logged in and enabled the app themeing again which now gave an error message saying something like "app theming is outdated and needs upgrade". My version of theming is 1.4.1 and I could not find theming app in https://apps.nextcloud.com/?search=theming - 
So my new question is: How do I upgrade the theming app?

**Comment by MorrisJobke** [comment]
> So my new question is: How do I upgrade the theming app?

Usually the theming app is shipped in the server release and thus has the latest code and updates automatically.




> latest entry in nextcloud.log has strange date (year 3003!!):

This is your systems clock ;)



> I use the same background image since Version 10 and any update/upgrade so far went well, never got any message concerning background image.

How did you added the background image? Via the theming app?



> Finally found "theming" settings in table oc_appconfig and changed configkey enabled to "no".

Could you put a "yes" in it and then check if the upgrade page get's triggered and the theming app is updated properly?

**Comment by Paradiesgestalter** [comment]
year 3003: strangely enough, there was just one such line with year 3003, all other log entries had correct years. and the other parts of that date where also correct. Could ther be a tiny bug somewher in an SQL call with this 'b WHERE b.file_id = '3003'' ??
Themeing App: I had uploaded the background image using the theming settings in the admin backend.
I guess the theming app got automatically updated in a seperate run when it gave a message like "theming app needs update - you get redirected in 5 sec" and i clicked that little blue OK button.
I had switched theming on in the admin backend after the upgrade went through. I also upgraded some extra apps later and they all seemed to work fine and also showed that upgrade message with the blue OK button wehn I enabled them in the apps settings.

**Comment by MorrisJobke** [comment]
@Paradiesgestalter Okay - so now everything works? If this is the case there is very little we can do, because we are lacking information about the reason why it failed in the first place :/

The error is also triggered by an app the bookmarks app and need to be analysed with the developers of that app. https://github.com/nextcloud/bookmarks

**Comment by Paradiesgestalter** [comment]
Yes, now everything works.
Maybe it is advisable to switch off theming before upgrade from 12 to 13? 
This is what I recommend, in case anybody else experiences that phennomenon that the start page does break when loading background image after replacing version 12 files with version 13 files in upgrade procedure.
Thanks for your feedback!!!

**Comment by MorrisJobke** [comment]
> Maybe it is advisable to switch off theming before upgrade from 12 to 13?

That's not what we aim for. We like to check if this happens again. :/ Okay - let's close this here then and have a look at maybe other reports for similar phenomenons.

Thanks for your feedback
