### ISSUE TITLE
Logo src url doesn't honor proxy settings

### ISSUE THREAD

**Issue by J0WI** [nextcloud/server#8244]
### Steps to reproduce
1. Setup Nextcloud on a HTTP server
2. Upload a custom logo in your theme settings
3. Use a reverse proxy supporting HTTPS
4. Browse to your NextCloud using HTTPS

The relevant proxy configuration I tried is:

```
# Listen on 443 ssl http2
location / {
	proxy_pass http://192.168.1.20:8888;   
	proxy_set_header Host $host;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Host $host;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-Server $host;
	proxy_set_header X-Real-IP $remote_addr;
}
```

I fixed this by adding `'overwriteprotocol' => 'https'` manually to the NextCloud config.

### Expected behaviour
Logo should load over HTTPS (becuase of `proxy_set_header X-Forwarded-Proto $scheme;`) or relative url.

### Actual behaviour
Logo url is returned as hardcoded HTTP.

### Server configuration

**Operating system**:
Linux/Docker

**Web server:**
nginx/Apache

**Database:**
PostgreSQL

**PHP version:**
7.1.14

**Nextcloud version:** (see Nextcloud admin page)
12.0.5/13.00

**Updated from an older Nextcloud or fresh install:**
fresh (Docker)

**Where did you install Nextcloud from:**
Docker official image

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
unchanged (Docker defaults)

**Nextcloud configuration:**
unchanged (Docker defaults)

### Client configuration
**Browser:**
any

**Operating system:**
any

#### Browser log
<details>
<summary>Browser log</summary>

```
Loading mixed (insecure) display content
```
</details>

**Comment by godfuture** [comment]
Exactly my setup and issue! When I right click in Firefox to show the logo graphics, I see the custom logo. Back on login screen, I see the Nextcloud default.

**Comment by skjnldsv** [comment]
```
/* line 110, /var/www/html/apps/theming/css/theming.scss */
#theming-preview-logo, #header .logo {
  background-image: url("/svg/core/logo/logo?color=fff&v=1");
}
```

background is now set in css, so it will comply with the current used protocol.
