### ISSUE TITLE
Dead link at admin settings panel (Tips&Tricks/Monitoring)

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/server#8247]
The link "extended monitoring" on the admin settings panel "tips&tricks" points to https://docs.nextcloud.com/server/13/go.php?to=admin-monitoring and is redirected to https://docs.nextcloud.com/server/13/admin_manual/operations/considerations_on_monitoring.html.

Your server says "file not found" when clicking on the link.

**Comment by MorrisJobke** [comment]
cc @jospoortvliet @MariusBluem 😉

**Comment by MorrisJobke** [comment]
We did some refactoring in our documentation and cleaned a bit up - thus it is not valid anymore. I removed it from the settings panel: #8252
