### ISSUE TITLE
Cannot add smb shares nor edit existing ones after upgrading to 13.0

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#8248]
Hello! I have an external Samba share I've been mounting to Nextcloud. Upon upgrading today, I stopped being able to configure it, nor can I add a new SMB share. I can still access the files just fine, and I get the green light, but I can't edit or add any more.

I have smbclient, php-smbclient and cifs-utils installed. I have tried various combinations of removing and re-installing the packages. Nothing seems to work!

### Steps to reproduce
1. Go to Settings > External Storage
2. Select the storage dropdown
3. Notice that SMB / CIFS is no longer an option

### Expected behaviour
SMB / CIFS is a selectable option for mounting external storage.

### Actual behaviour
SMB / CIFS is not a selectable option, and existing SMB shares cannot be edited.

### Server configuration

**Operating system**: Debian Sid

**Web server:** lighttpd 1.4.45

**Database:** MySQL 5.7.21

**PHP version:** PHP 7.0.27

**Nextcloud version:** 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded

**Where did you install Nextcloud from:** tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - spreed: 3.0.1
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ssl.aveilleux.us"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "EST",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "defaultapp": "calendar",
        "mail_smtpmode": "smtp",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome 64.0.3282.140

**Operating system:** Windows 10, build 16299.194

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors thrown by lighttpd
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No errors thrown by Lighttpd
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
JQMIGRATE: Migrate is installed, version 1.4.0
/data/.ocdata?t=1518060453442 Failed to load resource: the server responded with a status of 403 (Forbidden)
![extstr](https://user-images.githubusercontent.com/307077/35954179-38e43610-0c56-11e8-90f0-499c118fb92e.png)

```
</details>

**Comment by aveilleux** [comment]
![extstr](https://user-images.githubusercontent.com/307077/35954237-90071f98-0c56-11e8-8cd9-5ca0a089c5fa.png)

**Comment by fischtag** [comment]
I hab problems with SMB-shares after upgrading to 12.0.5. Problem was a new feature, allowing anonymous uusers to login. I had to remove this line:

smbclient_option_set($this->state, SMBCLIENT_OPT_AUTO_ANONYMOUS_LOGIN, false);

in apps/files_external/3rdparty/icewind/smb/src/NativeState.php.
Maybe this is related, hope it helps.

**Comment by ZeikoFr** [comment]
@nickvergessen Hi, is this issue still relevant ? I sadly cannot test is as I do not have a samba share to mount to my nextcloud and since the OP as deleted his account idk if it's still usefull to have the issue open

**Comment by nickvergessen** [comment]
If someone faces it again, they can create a new issue
