### ISSUE TITLE
nextcloud upgrade to 12.0.5 oauth2 problem

### ISSUE THREAD

**Issue by lukonh** [nextcloud/server#8256]
hello, i have problem with upgrade to nextcloud 12.0.5.
i have this error

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'CREATE UNIQUE INDEX oauth2_access_hash_idx ON oc_oauth2_access_tokens (`hashed_code`)': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'oauth2_access_hash_idx'

**Comment by bcutter** [comment]
Same here. Using nextcloud migration tool which uses Nextcloud v12.0.4.

**Comment by nickvergessen** [comment]
Do you have any stack trace for that error or other steps to reproduce?

**Comment by bcutter** [comment]
Nope, sorry - not a developer, only a brave power user. But I have to admit: I only got there trying to migrate from an unsupported OC version (no migration path to NC available yet), see https://github.com/nextcloud/server/issues/6532#issuecomment-366469795.

**Comment by bcutter** [comment]
Regarding https://help.nextcloud.com/t/migrating-from-owncloud-10-x-to-nextcloud-12-x-or-not-and-if-so-how/25002?page=2: I heard about NC v12.0.6 being released in a few days/weeks. So there will be a migration path finally, but I fear ending up in the same - this - issue...

**Comment by bcutter** [comment]
Tried a manual migration from OC v10.0.6.1 to NC v12.0.5 again. This time I disabled the oauth2 app using occ in advance of the migration. During the migration I ran into the same error message again, this time I simply deleted all lines (only 4 of them) of table _oc_oauth2_access_tokens_ and ran occ upgrade again - with success. Will reenable the app and hope to can easily switch to OAuth again.

**Comment by ChristophWurst** [comment]
I'm closing this ticket due to inactivity. From the latest comment I take that the problem was resolved by upgrading Nextcloud.
