### ISSUE TITLE
Visual regression testing

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#8258]
I had a look about what we can do to add some sort of automated visual regression testing so that changes that break the layout somehow can be spotted a bit easier.

Wraith (http://bbc-news.github.io/wraith/) looks like a pretty nice tool for that, and first tests worked fine so far. It would be nice to have some basic diff testing for every pull request and reports there if any of those screenshots differ to much.

Here is an example of the output for the login page, that would have spotted a regression like in https://github.com/nextcloud/server/issues/8035
![screenshot-2018-2-8 screenshot](https://user-images.githubusercontent.com/3404133/35971125-1529ba20-0ccd-11e8-8b0d-cedac0b8fab7.png)

Any toughts about that are welcome @nextcloud/designers @nextcloud/qa Also @danxuliu since you seemed to be the acceptance testing hero in the past :wink:

**Comment by skjnldsv** [comment]
Amazing, I was setting this up not long ago, but with PhantomCss! :D 
Yes, definitely, but this hould not be a merge breaker. Only a big warning :)

**Comment by rullzer** [comment]
yes please!

**Comment by MorrisJobke** [comment]
I just stumbled today over this one here: https://meowni.ca/posts/2017-puppeteer-tests/

**Comment by juliushaertl** [comment]
@MorrisJobke I'll have a look at that as well.

**Comment by juliushaertl** [comment]
Added with #8258
