### ISSUE TITLE
NC13: link to developer manual refers to documentation of NC 12

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/server#8260]
Version NC13.0.0

In the apps-view the last item  "i Developer documentation" refers to the documentation of NC 12 instead of NC13. I assume the source is:
https://github.com/nextcloud/server/blob/12c9bad5b26509feee1527596b2e54b86732c788/settings/templates/apps.php#L32

**Comment by cloud2018** [comment]
Also version number 12 in themes\example\defaults.php and CONTRIBUTING.md

themes\example\defaults.php Line 143: 
return $this->getDocBaseUrl() . '/server/12/go.php?to=' . $key;


CONTRIBUTING.md Line 61: 
[devmanual]: https://docs.nextcloud.org/server/12/developer_manual/
settings\templates\apps.php(32): <a class="app-external icon-info" target="_blank" rel="noreferrer noopener" href="https://docs.nextcloud.org/server/12/developer_manual/"><?php p($l->t('Developer documentation'));?> ?</a>

**Comment by MorrisJobke** [comment]
Dix is in #8263

**Comment by cloud2018** [comment]
Are the version numbers  in themes\example\defaults.php and CONTRIBUTING.md also fixed?
