### ISSUE TITLE
NC13, Cannot edit Files with Collabora in shared folders

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/server#8266]
Hi
I just upgraded to NC13 from NC12.05. No when I try to edit a file inside a folder shared with me by another user, I always get the following error: **Document cannot be saved. Check your permissions or contact the storage server administrator.**
File can be deleted within Nextcloud but cannot be edited within Collabora.
René

**Comment by rgl1234** [comment]
Hello
I just analysed the situation again. Editing of documents does not word, when they are shared with internal NC-Users. When Files/Folders are shared with an external user per e-mail-address, the external user can edit and save the documents.

**Comment by buttle** [comment]
Hi,
Same problem explained here https://help.nextcloud.com/t/collabora-document-inherited-share-permission-problem/27591/1

**Comment by Linkfab** [comment]
Hi, i have the same problem..

**Comment by rgl1234** [comment]
It seems to work when I disable versioning app.....So might this be a bug in the versioning app?

**Comment by Linkfab** [comment]
Thank a lot, disable Versioning app working for me.
Merci.

**Comment by kruchor** [comment]
Hello,

I had the same issue. Turning off versioning app did the trick. It is still a bit annoying as versions are pretty useful.

Thx

**Comment by MorrisJobke** [comment]
cc @schiessle

**Comment by MorrisJobke** [comment]
@rullzer Didn't you worked on something similar for collabora + external storage?

**Comment by juliushaertl** [comment]
There has been a lot of improvements in richdocuments since the bug was reported. I'll close this for now. Please try again with the latest release and feel free to open a new report in the richdocuments repo if the bug still occurs: https://github.com/nextcloud/richdocuments
