### ISSUE TITLE
Update to NC13: "appstore" subfolder was not created

### ISSUE THREAD

**Issue by possebaer** [nextcloud/server#8268]
After the Upgrade from Nextcloud 12.0.4 to Nextcloud 13 via the admin panel, the app store was not showing anymore correctly in the admin “Apps” section – i just saw installed apps and the categories “enabled” and “disabled” but none of the further categories of the app store. I noticed that it tried to load something in the UI section, but nothing ever appeared.

A look into my log showed me this:

>file_put_contents(/var/www/data/appdata_ocuvpurfksvx/appstore/apps.json): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/Files/Storage/Local.php#218

I checked permission on the appdata_ocuvpurfksvx directory which seemed fine, but I noticed that the subdir “appstore” was missing. So I created the dir, and since then the appstore is working again.

**Comment by MorrisJobke** [comment]
cc @rullzer @juliushaertl for tha appdata folder

**Comment by juliushaertl** [comment]
@rullzer Seems to be the same random error that sometimes occurred for the SCSS/JS stuff. :cry: 
I've no idea how this could happen, since the folder should have been created here: https://github.com/nextcloud/server/blob/ac38a3a654df909d2c0c9d7c4d84e8e5ea2c587a/lib/private/Files/AppData/AppData.php#L92

@possebaer Can you check your logs for other errors related to appdata? are there more details to the error message you've posted above?

**Comment by possebaer** [comment]
Hi, 
I digged through the nextcloud.log in my data directory. 

I found out that the appdata folder is actually missing since a previous upgrade, but it never caught my attention. The log entry where the appstore error occured for the first time is
> {"reqId":"8VSxTOkriloWASws7BsK","level":1,"time":"2017-12-26T21:49:17+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"updater","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=FXFbZ      xE48C%2FrAwd72e%2F40x3ABJbyjWaDzwRirusee3s%3D%3AdwcUPyhgwkSfKFAStZ2foFfzXOC3zhzXvHcg%2BIwmFzE%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"activity\" in appstore","userAgen      t":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"11.0.4.1"}{"reqId":"8VSxTOkriloWASws7BsK","level":3,"time":"2017-12-26T21:49:17+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=FXFbZxE48      C%2FrAwd72e%2F40x3ABJbyjWaDzwRirusee3s%3D%3AdwcUPyhgwkSfKFAStZ2foFfzXOC3zhzXvHcg%2BIwmFzE%3D","message":"file_get_contents(\/var\/www\/data\/appdata_ocuvpurfksvx\/appstore\/apps.json): failed to open stream: No       such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#209","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"11.0.4.1"}


So this is not a bug in Nextcloud 13 update per se, (although I think if it was missing, why it cannot just be created, when the www user has all rights on the directory appdata_ocuvpurfksvx ?) but seemed to have appeared in a previous version.

**Comment by rullzer** [comment]
The problem is the database tells us it is there. So the code doesn't think to recreate it.

**Comment by rullzer** [comment]
https://github.com/nextcloud/server/pull/8289 should help with this

**Comment by MorrisJobke** [comment]
> #8289 should help with this

Closing due to this.
