### ISSUE TITLE
Written error Link in Italian

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#8278]
In the personal page where you insert your personal page the wording in the box "Linking https" is wrong because linking bears only one "L" as attached image, link is written with two L

![errore nextcloud](https://user-images.githubusercontent.com/35575744/36026272-9e6bdace-0d96-11e8-88dc-2be7696c7196.png)

**Comment by rullzer** [comment]
Thanks for noticing @tigernero79 

Could I invite you to join transifix? https://www.transifex.com/nextcloud/
That is where we manage our translation that are synced daily.

I'm sure there are other strings that need checking as well :)

**Comment by tigernero79** [comment]
I tried to ask to be helpful for the translation in Italian but they refused me I do not know why ... oh well ...



Your project language request was not     accepted                                                  Unfortunately, your request to add Italian (Italy) to     the project Nextcloud     was not accepted. To learn why this may have happened, please see the     following FAQ answer: Why     was my language request for a project not accepted? | Your project language request was not     accepted                                                  Unfortunately, your request to add Italian (Italy) to     the project Nextcloud     was not accepted. To learn why this may have happened, please see the     following FAQ answer: Why     was my language request for a project not accepted? |   |   |   |  
-- | -- | -- | -- | -- | --
Your project language request was not     accepted                                                  Unfortunately, your request to add Italian (Italy) to     the project Nextcloud     was not accepted. To learn why this may have happened, please see the     following FAQ answer: Why     was my language request for a project not accepted? |   |   |   |

**Comment by rullzer** [comment]
@jospoortvliet @MorrisJobke we already have the italian language right? Do we have a guide on how to join transifex?

**Comment by MorrisJobke** [comment]
I guess it was refused, because we have already Italian and this request was for Italian (Italy).

I just checked the italian team and there is already one member named "tigernero79" - so I guess @tigernero79 is already in it :) I also updated the string to be correct now.

Thanks for your help 👍
