### ISSUE TITLE
Spreed.ME integration

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/server#828]
Let's break down the Spreed.ME integration in work packages. The Spreed.ME app should be in a releasable state after every work packages. And we probably should release it as beta builds to collect feedback.
1. Create a new Spreed.ME app and reimplement the Go server in PHP without functional changes. The Go server should still work for scenarios with a lot of users or weak hardware.
2. Spreed.ME interface cleanup and Nextcloud style harmonizing
3. Move some Spreed.ME settings to Nextcloud personal settings page and Admin page
4. Add TURN and MCU settings to admin Nextcloud Admin page
5. Add contacts and last called groups overview to Spreed.ME app

Independent Nextcloud apps:
1. Contacts Dropdown in Header (https://github.com/nextcloud/server/issues/207)
2. Avatar Popover

**Comment by karlitschek** [comment]
@jancborchardt @icewind1991 @leonklingele @Ivansss

**Comment by karlitschek** [comment]
@LukasReschke

**Comment by jancborchardt** [comment]
According to @longsleep, many of the Spreed.me settings are already taken from Nextcloud where possible. Ideally we should move them all over.

@longsleep also cc'ing you :)

**Comment by longsleep** [comment]
Right, to move all the Settings over to Nextcloud some gear is required to access all the different APIs for user media to get camera and microphone selection into the Nextcloud ui. Also it is important to understand that many of the settings are not bound to the user account alone but also to the exact device and browser and version of that device and browser. So some settings should be stored either per device if to be stored in the database or stored on the device (like we currently do with localStorage).

**Comment by jancborchardt** [comment]
@longsleep what do you think about the other steps @karlitschek listed in the original post? Anything missing there?

**Comment by jancborchardt** [comment]
This has been done as the new app released with Nextcloud 11 https://github.com/nextcloud/spreed and the Contacts menu soon to come :) https://github.com/nextcloud/server/issues/207
