### ISSUE TITLE
Add an occ command to report if updates are available

### ISSUE THREAD

**Issue by tterranigma** [nextcloud/server#8281]
Right now, the option you have from the command line is to run updater.phar and perform any updates. There is no option to only check and report back any updates. An alternative is to have some bash script that constructs the complex url for update checks that update.phar uses or parse webpages and try to extract the information you need. 

It would be handy to have a command like `php occ update:check` to report back the available updates.

**Comment by arunikayadav42** [comment]
Is anybody working ont this issue or can I get started please?
