### ISSUE TITLE
getUsername() fails with user_ldap (using OCS API)

### ISSUE THREAD

**Issue by linuxrrze** [nextcloud/server#8288]
### Steps to reproduce
1. Install nextcloud with LDAP user backend (user_ldap)
2. Use OCS API to list users
   e.g. using curl:

>    curl -v -X GET -u 'Administrator:AdminPW' https://cloud.myserver.de/ocs/v2.php/cloud/users -H "OCS-APIRequest: true"

### Expected behaviour
Users should be listed (as JSON answer)

### Actual behaviour
Nothing is returned, not even a valid JSON answer

### Possible solution:
Applying the proposed fix from this issue solves the problem for me:
https://github.com/nextcloud/server/issues/6785

### Server configuration

**Operating system**:
Ubuntu 16.04.3

**Web server:**
Apache 2.4.18

**Database:**
postgres 9.5.11

**PHP version:**
7.025

**Nextcloud version:** (see Nextcloud admin page)
13.0.0 (also happened in 12.0.4 / 12.0.5)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes: LDAP

#### Web server error log
<details>
<summary>Web server error log</summary>

```
"<IP>","user":"--","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/cloud\/users","message":"Error: Call to a member function getUsername() on null at /\/web\/apps\/nextcloud\/nextcloud-13.0.0\/apps\/user_ldap\/lib\/User_LDAP.php#136","userAgent":"curl\/7.47.0","version":"13.0.0.14"}

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"wPMkVZSzShmTuncYDoDH","level":3,"time":"2018-02-09T19:45:02+01:00","remoteAddr":"<IP>","user":"-
-","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/cloud\/users","message":"Error: Call to a member function getUsername() on null at /\/web\/apps\/nextcloud\/nextcloud-13.0.0\/apps\/user_ldap\/lib\/User_LDAP.php#136","userAgent":"curl\/7.47.0"
,"version":"13.0.0.14"}
```
</details>

**Comment by arunikayadav42** [comment]
Is anybody working on this issue or can I get started?

**Comment by linuxrrze** [comment]
Problem still exists with nextcloud 13.0.1.

Seems like nobody is working on this :-(

**Comment by danielkesselberg** [comment]
@linuxrrze could not reproduce this issue. Does this still happens?

**Comment by linuxrrze** [comment]
When executing:

`curl -v -X GET -u 'Administrator:ocjlP_1701' https://cloud.linux-ng.de/ocs/v2.php/cloud/users -H "OCS-APIRequest: true"
`

nextcloud.log still reports:

> {"reqId":"TpvBMhUobOsjbUP7B3kx","level":3,"time":"2018-09-14T10:42:20+02:00","remoteAddr":"131.188.6.78","user":"--","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/cloud\/users","message":"Error: Call to a member function getUsername() on null at \/proj.stand\/cow\/web\/apps\/nextcloud\/instances\/prod\/nextcloud-latest\/apps\/user_ldap\/lib\/User_LDAP.php#142","userAgent":"curl\/7.58.0","version":"13.0.6.1"}

And no users are returned.
So issue is still there in 13.0.6 (waiting for 14.0.0 release to be available via web update)

**Comment by linuxrrze** [comment]
I just added a few debug statements, and I may have an idea, why this may work with other setups:

In my case the account that causes the above error is "Administrator".

As I'm using a Samba DC as LDAP backend there's a local default user "Administrator" as well as a LDAP based user called "Administrator". Maybe this combination causes the described behaviour?

**Comment by danielkesselberg** [comment]
@linuxrrze I deleted your first comment because you posted a password by mistake. Please consider changing the password and take the required action. Unfortunately the comment was online more than 11 hours. I overlooked that before :disappointed:

**Comment by linuxrrze** [comment]
> @linuxrrze I deleted your first comment because you posted a password by mistake. Please consider changing the password and take the required action. Unfortunately the comment was online more than 11 hours. I overlooked that before

Thanks a lot for that hint!
I checked my log for accesses, and there have been none since my tests on friday. I also changed the password.
