### ISSUE TITLE
copyright in version.php

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/server#829]
Version.php contains the copyright
 @copyright Copyright (c) 2016, ownCloud, Inc 
several questions arise:
- I think this Inc isn't any accountable instance any more, is it?
- shouldn't it be something like nextcloud? or the owncloud GmbH or their foundation?
- did the vendor string already exist in the copyrighted source? I see the vendor string has been added to the OC version as well.

**Comment by LukasReschke** [comment]
> I think this Inc isn't any accountable instance any more, is it?

Not our problem ;-)

> shouldn't it be something like nextcloud? or the owncloud GmbH or their foundation?

Only for new files. Old files are copyrighted by ownCloud Inc. See also the logic in https://github.com/nextcloud/server/blob/master/build/license.php

> did the vendor string already exist in the copyrighted source? I see the vendor string has been added to the OC version as well

It's in ownCloud since today https://github.com/owncloud/core/blob/master/version.php
