### ISSUE TITLE
Installing without database pgsql password impossible

### ISSUE THREAD

**Issue by ygoe** [nextcloud/server#8291]
### Steps to reproduce
1. Switch to the user that owns all web files and runs PHP from the web server
2. Download, extract and delete the nextcloud tarball into the current directory: `tar -xjf nextcloud-13.0.0.tar.bz2 --strip 1`
3. Run the occ install command: `php occ maintenance:install --database "pgsql" --database-name "****" --database-user "****"`

### Expected behaviour
It should install. Even without the database user name.

### Actual behaviour
Without the user name it complains in a more or less friendly way that it is too stupid to use the current system account user name and I should provide it again.

With the user name, it crashes with some red error message telling me that I have provided no database password. Yes, I know, and it's not required. Postgres is smart enough to not require a password for local connections.

```
Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] fe_sendauth: no password supplied
 ->
```

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** PostgreSQL 10.2

**PHP version:** 7.0.25

**Nextcloud version:** 13.0

**Updated from an older Nextcloud/ownCloud or fresh install:** first install ever

**Where did you install Nextcloud from:** Tarball from download page, following the install docs

**Are you using external storage, if yes which one:** not yet, before install

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** None

**Operating system:** None

**Comment by blizzz** [comment]
so the user www-data is able to connect to postgresql locally and create databases there?

**Comment by ygoe** [comment]
No. The user www-data does nothing at all on my system. Each virtual host is run by a separate system account for my users. And they don't have createdb privileges, they can only connect to and use their own databases. Databases are created through a control panel provided by the system.

**Comment by Ekleog** [comment]
I confirm the issue, as I am currently hitting it. For instance, synapse (from matrix.org) handles the situation well.

**Comment by blizzz** [comment]
> A Nextcloud instance configured with PostgreSQL would contain the path to the socket on which the database is running as the hostname, the system username the PHP process is using, and an empty password to access it, and the name of the database. [Source](https://docs.nextcloud.com/server/14/admin_manual/configuration_database/linux_database_configuration.html)

did you try that?

**Comment by Ekleog** [comment]
No indeed, I can confirm it works this way. Somehow I came up on this issue before finding the source, because for some reason other programs (esp. synapse) appear auto-detect the socket path.

Anyway, I guess this could be closed, if it's solved indeed. Thanks!
