### ISSUE TITLE
Two Overlapping Logos in 404 Error Page

### ISSUE THREAD

**Issue by PhoenixPeca** [nextcloud/server#8295]
![image](https://user-images.githubusercontent.com/9730242/36062798-5fad8c6a-0eae-11e8-8024-73fb800b9890.png)

My steps to reproduce:
* I have uploaed my own nextcoud logo in the theme page.
* Then I have shared a public link of my photo galley.
* Then I copied the photo gallery public link URL.
* Then I have disabled the public link of my photo gallery.
* Then I opened the coped link in my browser.
* Then the two overlapping logos appeared.

**Comment by TomTurnschuh** [comment]
I also get a nice effect when I create a new user without password and he clicks on the link in the e-mail to create his own password. The figure has originally equal side length.

![grafik](https://user-images.githubusercontent.com/36013390/36077946-11ff03ae-0f71-11e8-89e6-5516eaab7785.png)

With another logo I get two two figures whereof one is just right while the other one is rotated and stretched by a big factor.

**Comment by MorrisJobke** [comment]
Duplicate of #8035 which is fixed by #8155 and will be available in 13.0.1 😉

**Comment by MorrisJobke** [comment]
Thanks for your feedback anyways 👍
