### ISSUE TITLE
Uploading big files onto slow server with Sync Client

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/server#8296]
### Steps to reproduce
1. Upload big file (several GB, tried with 5.7 GB) using the Windows Sync Client.

### Expected behaviour
Successful upload of big files. ;-)

### Actual behaviour
The sync client uploads the data, but then gets a timeout error.
It seems that the sync client tries to upload the file again before the file on the server has been fully assembled from chunks, resulting in multiple .part files on the server. (There are still developing .part files in the data folder when already new ones shows up after some time.)

#### Temporary solution
The issue can be bypassed by stopping the syncronization in the sync client when the file is uploaded for the first time and the error shows up. After the server side assembly of the file (.part file turning into full file), the sync client synchronization can be resumed.

### Server configuration

**Hardware:** Raspberry Pi 3 B

**Operating system basis:** NextCloudPi v0.46.4 (32 bit)

**Database:** MySQL 10.1.23

**PHP version:** 7.0.27

**Nextcloud version:** 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 12.0.4 -> 12.0.5

**Are you using encryption:** No

### Client configuration

**Windows Sync Client:** 2.3.2

**Comment by tflidd** [comment]
I suppose you are still using a 32-bit system:
https://github.com/nextcloud/nextcloudpi/issues/101#issuecomment-321876278

**Comment by TomTurnschuh** [comment]
> I suppose you are still using a 32-bit system.

That's true, indeed.

**Comment by tflidd** [comment]
At some point, they said to fix large uploads in 32-bit environments for NC13. I don't know if that really happened and it's still an open point for the documentation:
https://github.com/nextcloud/documentation/issues/640

**Comment by TomTurnschuh** [comment]
I assume, thanks to this update it is even possible to upload such big files.
However, if the single chunks (8 MB?) take too long to be put together on the server, the sync client runs into an error state for that file.

I guess, this problem is comparable to issue 234 in the android section.

**Comment by tflidd** [comment]
Yes, for that reason it worked sometimes on 32-bit clients when using the NC client. But it was a problem when the files were also accessed via web-interface.
