### ISSUE TITLE
jQuery UI not affected by Theming

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#830]
LDAP Admin settings appear blue not green, when changing color using with Theming app.

![spectacle xl7604](https://cloud.githubusercontent.com/assets/2184312/17558773/090041ac-5f1c-11e6-971d-cfa86434b9fc.png)

However, I do not remember we use jQuery UI anywhere else and the desire is to get rid of this here, too. Also, it is "only" visible to admins. Thus, maybe not worth to fix, not sure how big the effort would be. 

@nextcloud/designers

**Comment by juliushaertl** [comment]
This should be quite easy to implement, i'll add that to #771.

**Comment by jancborchardt** [comment]
@blizzz @juliushaertl actually the color should be removed from jQuery UI. The tabs should be styled like the tabs in the right Files details sidebar instead.

**Comment by juliushaertl** [comment]
fix was merged in #1090,
new issue for the proposed changes by @jancborchardt  #830
