### ISSUE TITLE
PHP Fatal error with nextcloud 13 and PostgreSQL 10

### ISSUE THREAD

**Issue by xf0e** [nextcloud/server#8300]
### Actual behaviour
Feb 10 21:03:20 host.com nginx[971]: 2018/02/10 21:03:20 [error] 973#973: *57 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /usr/share/webapps/nextcloud/lib/private/DB/Connection.php:64
Feb 10 21:03:20 host.com nginx[971]: Stack trace:
Feb 10 21:03:20 host.com nginx[971]: #0 /usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
Feb 10 21:03:20 host.com nginx[971]: #1 /usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
Feb 10 21:03:20 host.com nginx[971]: #2 /usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
Feb 10 21:03:20 host.com nginx[971]: #3 /usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
Feb 10 21:03:20 host.com nginx[971]: #4 /usr/share/webapps/nextcloud/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
Feb 10 21:03:20 host.com nginx[971]: #5 /usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Co...
Feb 10 21:03:20 host.com nginx[971]: PHP message: PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /usr/share/webapps/nextcloud/lib/private/DB/Connection.php:64

### Server configuration

**Operating system**:
Archlinux

**Web server:**
nginx

**Database:**
postgres 10

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 12
**Where did you install Nextcloud from:**
archlinux repo

**Comment by MorrisJobke** [comment]
> Failed to connect to the database: An exception occured in driver: could not find driver in

This looks like the PHP module is not properly loaded. Please check if the php module is loaded - if you need help for this the forum is the better place to do so: https.//help.nextcloud.com
