### ISSUE TITLE
Custom css-theme- NC theme - flare up/flashing for 3sec if the theme loads

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#8307]
### Steps to reproduce
1. updated to nextcloud 13
2. reactivate my own theme (and fix it)

### Expected behaviour
First should load my own custom theme,
without Nextcloud-css theme loading
if in the config.php theme is specified.
And no half-loading the Nextcloud-theme.

### Actual behaviour
By fix my custom theme have i noticed that the theme always flare up/flashing 
by loading or reloading the pages the Nextcloud-theme for 3sec or 
half of it let show and then it is loading my own theme, 
so i see the blue panel on top ever and ever by load /reload 
the theme with the Nextcloude-icon and then it is reload my custom theme.

### Server configuration
**Operating system**:
OpenMandriva Linux 3.03
**Web server:**
Apache Lamp
**Database:**
mariadb
**PHP version:**
7.XX
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updatet from 12, overcopieed and occ upgrade in console, 
all works normal except the theme

**Where did you install Nextcloud from:**
Orginal official download from Homepage of NC

best regards
Blacky

**Comment by MorrisJobke** [comment]
> First should load my own custom theme,
> without Nextcloud-css theme loading
> if in the config.php theme is specified.
> And no half-loading the Nextcloud-theme.

A theme is always loaded ontop of the existing files. Otherwise you need to redo the whole CSS. So this works as intended.
