### ISSUE TITLE
Just sync changes / delta sync

### ISSUE THREAD

**Issue by ThomasSteinbach** [nextcloud/server#831]
[feature request]

### Steps to reproduce
1. Full syncronize a huge file (e.g. an outlook.pst file)
2. Trigger small changes to the file (e.g. updating you mails in outlook)

### Expected behaviour
Just the _changed blocks of the file_ (whatever that should mean) should be synchronized.

### Actual behaviour
The whole file is synchronized again. Old versions of the file would be stored by making a snaphsot of the whole file. This is much overhead if the change is just 256kb of an 16gb file.

**Comment by LukasReschke** [comment]
Searching for "delta" in the search would easily have spotted https://github.com/nextcloud/server/issues/417

**Comment by ThomasSteinbach** [comment]
OMG - I feel stupid ^^. Started searching for 'partial sync' which leads to no results. Shortly before creating this issue I googled 'partial sync' which leads me to 'delta sync'. But I haven't checked this new term again. Sorry for that.
