### ISSUE TITLE
Disable web app by own cloud interface (NO NEXTCLOUD THEME)

### ISSUE THREAD

**Issue by quentingosset** [nextcloud/server#8310]
Good morning. Hello,
I would like to know if it is possible to disable the nextcloud web interface through our own PHP interface (this is not a nextcloud theme).

My domain is the following cloud.****. be when I go on the links, I am directed to the web interface, I would like to disable this one to put mine. But I have to keep the nextcloud folder because the desktop application searches the status. php file.

Can you help me and have you understood my problem? 

Translated with www.DeepL.com/Translator

**Comment by MorrisJobke** [comment]
You could of course setup rules to forbid access to stuff like `.../apps/files` or `.../apps/contacts` but the clients still need stuff like  `status.php`, `ocs/...`, `remote.php/..` and some more. But in general we do not support this or any problems that would occur when this is used.

On the other side you could also use the files_accesscontrol app and only allow access by user agent (Android, iOS and desktop client have a unique user agent).

**Comment by quentingosset** [comment]
I don't want to deny access to certain applications, I want to redirect the user to my own PHP interface while keeping nextcloud and its necessary files such as status. php.

Example when my client is on cloud.***. be it is directed to the nextcloud login. I would like it to redirect example directly to another directory of my server that is my interface (/myCloud).

**Comment by MorrisJobke** [comment]
> Example when my client is on cloud.***. be it is directed to the nextcloud login. I would like it to redirect example directly to another directory of my server that is my interface (/myCloud).

I know, but we don't support this, because the clients and apps for example now use the web UI to login and need the login page which is already part of the web interface. Also we don't have a full list of URLs that are needed by the client/apps.
