### ISSUE TITLE
Can't find a replacement of getAllSharesbyFileId()

### ISSUE THREAD

**Issue by daita** [nextcloud/server#8313]
I know I have to use IShareManager and I was using Share::getAllSharesByFileId($fileId) until now, but the static method is removed in NC14:
https://github.com/nextcloud/server/commit/71cf31f211af9240f947412e8e94b21a5a559240#diff-dfb2def6044286d5851da15ad6e8b249

Can't find a way a do the samething using the IShareManager. 

I need to have all shares (users, groups, circles, links) from a File (or its Id).

Love,

**Comment by ChristophWurst** [comment]
@daita @rullzer is that still an issue? Have you found a replacement?

If you really need that code in your app you could also just copy-paste and maintain it there.

Closing, but please re-open if still relevant.
