### ISSUE TITLE
Add option to create groups via the command line

### ISSUE THREAD

**Issue by tterranigma** [nextcloud/server#8317]
I might have missed sth but I could not find an option in occ to create user groups. Sth like `php occ group:add`.

**Comment by tterranigma** [comment]
Could someone give me some guidelines on how to approach implementing such a command?

**Comment by EpeR1** [comment]
And please add a group:delete command!

**Comment by blizzz** [comment]
You can use the provisioning API for group creation, e.g. via curl.

**Comment by denismosolov** [comment]
Would like to try this one as my first issse. Is anybody else is working on it?

**Comment by blizzz** [comment]
@denismosolov please assign the issue to you and go ahead :) Due to the freeze the next merge window will be for 15 however.

**Comment by denismosolov** [comment]
@blizzz Thanks!
I'm not sure how to assign the issues. Probably I don't have permissions to do that.

**Comment by blizzz** [comment]
@denismosolov ah, you need to be a member of the org. I invited you :)

**Comment by denismosolov** [comment]
@tterranigma @EpeR1 merged to master https://github.com/nextcloud/server/pull/10334
Will be availbale in Nextcloud 15

**Comment by blizzz** [comment]
14 actually, since we did not branch off stable14 yet
