### ISSUE TITLE
After update to 13.0 (Ticket #459) WebDAV operations are forbidden? 

### ISSUE THREAD

**Issue by ilijoski** [nextcloud/server#8322]
### Actual behaviour
After updating NC to v13.0.0.14 (ticket #459) I have issues with sync on desktop client, when I log on to web interface also receive info "This operation is forbidden", on Log file I have lot of lines
"OCA\DAV\Connector\Sabre\Exception\Forbidden: No read permissions"

After research under old tickets here, i found solution with disable ing some apps, and after that now I dont receive that error. But is it safe now to re-enable the apps? 

Thanks

### Server configuration
Nextcloud 13.0.0.14

Hosted by Hyper-V:

**Operating system**:
Description: Ubuntu 16.04.3 LTS
Release: 16.04
Codename: xenial
Fully updated

**List of activated apps:**
<details>
<summary>App list</summary>
root@cloud:/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_downloadactivity: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - ransomware_protection: 1.1.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - calendar
  - comments
  - contacts
  - encryption
  - files_accesscontrol
  - files_external
  - files_pdfviewer
  - files_videoplayer
  - systemtags
  - updatenotification
  - user_external
  - user_ldap
```
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

**Comment by gurussia** [comment]
what is your php version.

**Comment by ilijoski** [comment]
**php7.0** is selected in Apache Modules.

**Comment by MarcelWaldvogel** [comment]
Which apps did you disable? (Alternatively, what were the old issues that helped you there?)

**Comment by MarcelWaldvogel** [comment]
BTW: What does issue #459 have to do with your upgrade?

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
