### ISSUE TITLE
Arabic i10n is missing

### ISSUE THREAD

**Issue by BoFFire** [nextcloud/server#8325]
Hi,
We understand that there are a a lot spanish selection on NextCloud, we're happy to see this happen.
But can you tell me if it is still worth to carry on translating NextCloud to Arabic on Transifex or should we abandon the project and say that NextCloud is Spanish oriented ?

ar is present here : https://github.com/nextcloud/server/tree/master/lib/l10n
We are not asking to add ar-DZ, ar-TN, ar-EG and ar-who knows, just to have it available in the profile selection so that we can carry on translating.

Thank you.
A NextCloud Localizer.

**Comment by BoFFire** [comment]
Actually I'm looking to the code, I'll do it don't worry I'll submit a pull request.

**Comment by MorrisJobke** [comment]
> We understand that there are a a lot spanish selection on NextCloud, we're happy to see this happen.
> But can you tell me if it is still worth to carry on translating NextCloud to Arabic on Transifex or should we abandon the project and say that NextCloud is Spanish oriented ?

We don't have any focus there, but there is a big spanish community group that does all of those translations and thus there are many different spanish versions.

We obviously like to have all possible languages present in Nextcloud. Currently there are 93 languages that are at least have some translations. We will pull them in once 50% of all available strings in the server is translated.

Also arabic has a total of 30 % translation coverage in our system on transifex. So please join and get it in. Sadly the core components are lacking a bit: 

* core: 35%
* settings: 19%
* lib: 27%

Join us :) https://www.transifex.com/nextcloud/

And thanks for the heads up :)

**Comment by BoFFire** [comment]
Hi,
I understand that there is a % to accept a language. - Can you tell us where this is stated ?

Arabic was present in some last version. I don't rememer which one, why it was delete ?

**Comment by BoFFire** [comment]
Yes I've done a lot of work especially on the NextCloud Android app to arabic, now I'm asking :
Delete all my contributions in the whole project.
Please proceed !

**Comment by BoFFire** [comment]
@MorrisJobke can you read my last message ? ;) proceed.

**Comment by MorrisJobke** [comment]
> I understand that there is a % to accept a language. - Can you tell us where this is stated ?

This is a bit more complex - let's do it anyway:

We fetch the available language codes for core here which is then rendered as the language drop down on the settings page:

https://github.com/nextcloud/server/blob/4ee9315a684d01e8b00f03143588524aa1146315/lib/private/Settings/Personal/PersonalInfo.php#L202

That means that if the language is available in core it will be listed.

The translations are synced by a daily cronjob which executes following code:

https://github.com/nextcloud/docker-ci/blob/master/translations/handleTranslations.sh#L49

I was wrong stating that it is 50 percent, but it actually was changed to 75 and I will create a fix for this to change it back to 50%.


> 
> Arabic was present in some last version. I don't rememer which one, why it was delete ?

It was not deleted, but we updated maybe some source strings and thus the percentage changed. Sorry for that but this is the evolution of software - it sometimes changes




> Yes I've done a lot of work especially on the NextCloud Android app to arabic, now I'm asking :

And we really really appreciate that! :)

> Delete all my contributions in the whole project.
> Please proceed !

Sad to hear this, but this is not easily possible. :/ I'm unsure if transifex allow such a query.

**Comment by BoFFire** [comment]
Thank you,
It is more complexe to delete and create.
It is simple to delete actually, remove all strings where string is created by BoFFire_ and modified only by BoFFire_ this is simple to do.
But simplest is to show me how can I hack the shit and replace one spanish eswhatever.json with ar.json so that that I can see where the strings are ? And how to do it better.
I don't trust NextCloud anymore.
Sorry MorrisJobke

**Comment by MorrisJobke** [comment]
> But simplest is to show me how can I hack the shit and replace one spanish eswhatever.json with ar.json so that that I can see where the strings are ? And how to do it better.

You want to get rid of the spanish stuff? Then just remove the ones from https://github.com/nextcloud/server/tree/master/core/l10n - just drop both - the json and the JS file and the language shouldn't be shown anymore.



> But simplest is to show me how can I hack the shit and replace one spanish eswhatever.json with ar.json so that that I can see where the strings are ? And how to do it better.

Currently the strings are generated via a script and are pushed to transifex. You could run https://github.com/nextcloud/docker-ci/blob/master/translations/handleTranslations.sh locally and adjust the percentage in line 49 to your wished one. Then the arabic translation should show up and there should be POT files in translationfiles/templates as well. But I would still like to see you within in our project.


> I don't trust NextCloud anymore.

What is the reason for this? I just want to know the background and maybe we can do something here to establish some trust again.

**Comment by BoFFire** [comment]
I don't want to get rid off Spanish :)) just a way to follow the advancement of "ar" translation in the project.
I'm blind translator when strings are not included :))
RTL is okay on NextCloud I think I've checked Farsi to compare.

**Comment by BoFFire** [comment]
And by the way, I'm not a company ^-^ just a simple contributor.

**Comment by BoFFire** [comment]
Hi,
Expect 50% for ?
- Core
- Settings
- Lib
These three does not appear on Transifex unless the user clicks on "ressources".

**Comment by BoFFire** [comment]
Challenge done !
You said ?
core: 35%
settings: 19%
lib: 27

Please recheck now.
Best regards,

**Comment by MorrisJobke** [comment]
I just triggered the sync and it should show up within the next 15 minutes in the source code repository here ;)

**Comment by MorrisJobke** [comment]
Thank you so much 👍

**Comment by alimahwer** [comment]
As of today, the translation of Nextcloud into the Arabic language is 100%. However, Nextcloud core is still not supporting RTL.
