### ISSUE TITLE
Internal Server Error (Template not found) when loading Calendar after upgrade to Nextcloud 13.x

### ISSUE THREAD

**Issue by thohai** [nextcloud/server#8326]
### Steps to reproduce
1. Upgrade to Nextcloud 13
2. Upgrade Calendar to 1.6.0
3. Click on the "Calendar" App

### Expected behaviour
Calendar should be shown.

### Actual behaviour
The following Internal Server Error occurs (see Nextcloud Log)

### Server configuration

**Operating system**: Debian Jessie

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 

**Nextcloud version:** 13.0.0.x

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12.x

**Where did you install Nextcloud from:** docker

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Exception: template file not found: template:main
/var/www/html/lib/private/legacy/template.php - line 176: OC\Template\TemplateFileLocator->find('main')
/var/www/html/lib/private/legacy/template.php - line 87: OC_Template->findTemplate('', 'calendar', 'main')
/var/www/html/lib/public/AppFramework/Http/TemplateResponse.php - line 151: OC_Template->__construct('calendar', 'main', 'user')
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 114: OCP\AppFramework\Http\TemplateResponse->render()
/var/www/html/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Calendar\Controller\ViewController), 'index')
/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/lib/base.php - line 998: OC\Route\Router->match('/apps/calendar/')
/var/www/html/index.php - line 37: OC handleRequest()
{main}</details>

**Comment by blizzz** [comment]
how did you upgrade calendar? are the permissions on the filesystem correct?

**Comment by thohai** [comment]
The next update fixed the problem

**Comment by thohai** [comment]
The next update fixed the problem
