### ISSUE TITLE
Web based updater to 13 fails with Exception: Can not get secret from Nextcloud instance 

### ISSUE THREAD

**Issue by pivoj** [nextcloud/server#8329]
### Steps to reproduce
1. Using Web based updater to version 13

### Expected behaviour
Upgrade is completed

### Actual behaviour
```
Update to 13.0.0
Exception: Can not get secret from Nextcloud instance

Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updated "federatedfilesharing" to 1.3.1
Updated "files_pdfviewer" to 1.2.0
Updated "files_texteditor" to 2.5.1
Updated "files_videoplayer" to 1.2.0
Updated "gallery" to 18.0.0
Updated "password_policy" to 1.3.0
Updated "provisioning_api" to 1.3.0
Updated "serverinfo" to 1.3.0
Updated "survey_client" to 1.1.0
Updated "twofactor_backupcodes" to 1.2.3
Updated "updatenotification" to 1.3.0
Updated "federation" to 1.3.0
Updated "lookup_server_connector" to 1.1.0
Updated "oauth2" to 1.1.0
Updated "files" to 1.8.0
Updated "activity" to 2.6.1
[0 / 0]: Fix broken values of calendar objects
Updated "dav" to 1.4.6
Exception: Can not get secret from Nextcloud instance
The update was unsuccessful. Please report this issue to the Nextcloud community.
```
### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7

**Nextcloud version:** 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from 12.0.3 -> 12.0.4 -> 12.0.5
 
**Where did you install Nextcloud from:** nexcloud.com

**Are you using external storage, if yes which one:** lno

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

**Comment by blizzz** [comment]
encryption related @nextcloud/encryption

**Comment by fastlorenzo** [comment]
I have the exact same issue, did you found a solution for this?

**Comment by fastlorenzo** [comment]
Hum, looks like the updater doesn't check which Debian version is installed. I was still on wheezy and thus no PHP7, might be the problem...

**Comment by fastlorenzo** [comment]
Ok, found out the issue.
It looks like the updater did set the encryption key to the 'updater.secret' variable in config and the new updater is looking for 'secret' variable.
I manually copied the 'updater.secret' value to a new 'secret' variable in config.php and now it's working.

**Comment by blizzz** [comment]
@MorrisJobke any idea^?

**Comment by MorrisJobke** [comment]
@blizzz Just to clarify: this is the blue page with the "Upgrade now" button. This is not the part that replaces code. Also this one has a proper check for which PHP version is installed.

Back to the topic: this error is coming from the encryption part and not the updater and thus the key "secret" is correct. It's not the updater.secret and should also not be overwritten. Otherwise you kill your master key encryption secret:

https://github.com/nextcloud/server/blob/38a90130ce425d531a804dff591df4a883de3154/apps/encryption/lib/KeyManager.php#L692-L705

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
