### ISSUE TITLE
Udate Error with mime-type and kdbx registration while upgrading to 13.0.0

### ISSUE THREAD

**Issue by luwimi** [nextcloud/server#8332]
### Steps to reproduce
1. Install KeeWeb
2. Upgrade from 12.0.5 to 13.0.0
3.

### Expected behaviour
The upgrade should succeed.

### Actual behaviour
Following error occours:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_filecache` SET `mimetype` = ? WHERE (`mimetype` <> ?) AND (`mimetype` <> ?) AND (LOWER(`name`) LIKE ?)' with params ["12", "12", "2", "%.\\%.kdbx"]: SQLSTATE[HY000]: General error: 1206 The total number of locks exceeds the lock table size

### Server configuration

**Operating system**:

**Web server:**
Uberspace 6 (U6)
**Database:**
My SQL

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
12.0.0.5 to 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary> Diese Apps werden aktualisiert:

    Activity (activity)
    Comments (comments)
    WebDAV (dav)
    Default encryption module (encryption)
    Federated file sharing (federatedfilesharing)
    Federation (federation)
    Files (files)
    External storage support (files_external)
    PDF viewer (files_pdfviewer)
    File sharing (files_sharing)
    Text editor (files_texteditor)
    Deleted files (files_trashbin)
    Versions (files_versions)
    Video player (files_videoplayer)
    First run wizard (firstrunwizard)
    Gallery (gallery)
    Lookup Server Connector (lookup_server_connector)
    Nextcloud announcements (nextcloud_announcements)
    Notifications (notifications)
    OAuth 2.0 (oauth2)
    Password policy (password_policy)
    Provisioning API (provisioning_api)
    Monitoring (serverinfo)
    Share by mail (sharebymail)
    Usage survey (survey_client)
    Collaborative tags (systemtags)
    Theming (theming)
    Two factor backup codes (twofactor_backupcodes)
    Update notification (updatenotification)
    Files workflow engine (workflowengine)

Diese inkompatiblen Apps werden deaktiviert:

    Keeweb (keeweb)
    News (news)
    Video calls (spreed)
    Two Factor TOTP Provider (twofactor_totp)

</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Orbital-Bit** [comment]
we had similar issues, did you try to run `php occ maintenance:mimetype:update-db --repair-filecache` before the update?

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
