### ISSUE TITLE
Thumbnails on external storage are broken when at external storage root

### ISSUE THREAD

**Issue by rubrik** [nextcloud/server#8333]
Version 13.0.0

Using "External Storage" with local filesystem directory (sharing: enabled, previews: enabled).

* Create new external storage pointing to local filesystem directory
* Ensure sharing is enabled, ensure previews are enabled.
* Copy image to external storage folder
* File view: thumbnail okay, can view large image. Gallery view: thumbnail okay, can view large image.

* Create share link to folder.
* Open link in new private browsing session.
* File view: thumbnail okay, cannot view large image "could not generate a preview of this file". Gallery view: nothing happens. Logging in other browser says "Exception: Could not locate node linked to ID: 22813"

* Create share link to _image_.
* Open link in new private browsing session.
* I can see it (!!!!)

Now I do the same without External Storage: it all works.
Now I do the same again (with External Storage) - but first I create a _sub-directory_: it all works.

This worked fine in NC12.

**Comment by MorrisJobke** [comment]
> I think my issue is a dupe of #7181

Closing then as duplicate.
