### ISSUE TITLE
strange things in nextcloud 13. maybe php7.1 or php7.2

### ISSUE THREAD

**Issue by gurussia** [nextcloud/server#8345]
HI guys. Strange thing happend when nextcloud comment white pages, so i try enable php versions and in one php version i found currious thing. In admin section there was blue color, in passman there was color and lines and now when i change to php7.1 and include i do occ " i don't remembe what occ things " this colors, lines and etc. dissapear . In settings passman is all in white, how i say in begginigs in this message before i start activating php7.2 and was thinking 7.2 was supported but i don't know how it has colors and lines, now there no colors, no lines. So can someone comment if he has the same issue or it can be from php7.1 or php7.2 include comment if circle is workng how develoreps developr to completly work, becouse i put familly in circle and it only comment they names, nothing more. Include i read that somewhere it can be imagick or another modules of php, so if it module missing then someone comment what 100 & are neccesarry for nextcloud work 100%
https://github.com/nextcloud/circles/issues/173

**Comment by MorrisJobke** [comment]
Could you send screenshots of what you see? It could be that this is the same as #8043 and can be fixed by running this as workaround (we fixed it properly in the upcoming 13.0.1):

Ah ... I just realised I already gave you that tip in #8320

Are those issues still happen after you executed https://github.com/nextcloud/server/issues/8320#issuecomment-365218279 ?

**Comment by gurussia** [comment]
HI guys i was 4 hours seeking where to put the photos and i found this site and here i will put feature bugs of nextcloud: https://bgzashtita.es/pisma/profile/peturbg there is photos include in the last minute when i download photos it start create with every download another circle, you are gonna see it on the photos. Now in all photos i make it black line and i put comment in them, there was no good program in linux so result was bad, but it is important what i write. Include maybe it has bug in nextcloud circle app if i found i will put how correctly it has to be seen.

**Comment by gurussia** [comment]
with morris solution it repaired white screen, i want to thanks morris and person who develope the solution, but morris close the thread. in the upper message you are gonna see other bugs. if i remember correctly i was use php7.0 and all was correctly, in settings it was blue colors and lines and now with php71 or php7.2 this design include circles maybe is not working correctly.

**Comment by MorrisJobke** [comment]
> HI guys i was 4 hours seeking where to put the photos and i found this site

You could upload them directly to github as well ;) (sorry the arrow couldn't made be small quickly so it is a bit oversized)

![bildschirmfoto 2018-02-15 um 09 55 19](https://user-images.githubusercontent.com/245432/36248098-941e9c56-1236-11e8-89f3-2f6c4b1cd538.png)



> with morris solution it repaired white screen, i want to thanks morris and person who develope the solution, but morris close the thread. in the upper message you are gonna see other bugs.

Perfect. Nice to hear that it worked fine for you and sorry for the inconvenience. The 13.0.1 will contain a fix that doesn't need manual fixing.

Regarding the pictures:

- nr 1: the one with the blue line: I guess we changed the design here a bit. So I would not worry about this one.
- nr 2: The circles settings look good and we also improved there the look and feel quite a bit from 12 to 13.
- nr 3 & 4: They look okay. Apps can add settings and this seems to be the case
- nr 5, 6 & 7: Those are related to the circles app and I would ask you to report this to the circles app issue tracker and mention @daita (one of the maintainers there) to have a look at it.

Thanks for your detailed report.

**Comment by MorrisJobke** [comment]
> nr 5, 6 & 7: Those are related to the circles app and I would ask you to report this to the circles app issue tracker and mention @daita (one of the maintainers there) to have a look at it.

See https://github.com/nextcloud/circles/issues/173

**Comment by gurussia** [comment]
Is it working. Strange things happend in php7.2. Now i activate php7.2 and when i try yo download something it start download, but circle when was yestarday don't show, include menu download is dissapearing, so if you click one time download there is no second time downloadl, it is white there. In the moment i dont remember what was in other php version, but maybe it was there, so if you download one time you can click again on download and start download other copy. In version php7.2 if you click download and accept download second time download will dissapear.
