### ISSUE TITLE
Files are not shown in Firefox and IE11

### ISSUE THREAD

**Issue by linuxpete** [nextcloud/server#8347]
Firtst I hope I am reporting this in the right place.

I ran into the issue that files are not shown in Firefox (58.0.1/58.0.2) as well in Linux (Ubuntu 14.04) as in Win10, as you can see in next picture. Also IE11 doesn't show the files.

![files_nextcloud_01](https://user-images.githubusercontent.com/7695965/36193014-6ac71a90-1164-11e8-9e24-e0039674656b.png)

I upgraded from NC 12.0.5 to NC13.0.0 yesterday. Everything went smooth apart from upgrading the Full text search app.

As I opened the Files app I didn't see all files and opened up Chrome and saw all my files again. 

### Steps to reproduce
1. Open files app

### Expected behaviour
1. Open files app
2. files are shown like in google Chrome
![files_nextcloud_02](https://user-images.githubusercontent.com/7695965/36193055-9ca79d96-1164-11e8-9334-f0ae7018d4a3.png)

### Actual behaviour
See picture above

## Server configuration detail

**Operating system:** Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64

**Webserver:** nginx/1.10.3 (fpm-fcgi)

**Database:** mysql 5.7.21

**PHP version:** 7.0.25-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - apporder: 0.4.1
 - audioplayer: 2.2.5
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.0
 - checksum: 0.3.5
 - comments: 1.3.0
 - contacts: 2.1.0
 - dav: 1.4.6
 - deck: 0.3.0
 - encryption: 2.0.0
 - end_to_end_encryption: 1.0.2
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_opds: 0.8.8
 - files_pdfviewer: 1.2.0
 - files_reader: 1.2.2
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - fulltextsearch: 0.6.0
 - gallery: 18.0.0
 - gpxedit: 0.0.8
 - gpxmotion: 0.0.6
 - gpxpod: 2.2.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - music: 0.5.5
 - news: 12.0.1
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - qownnotesapi: 17.5.0
 - rainloop: 5.0.6
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.0.1
 - spreedme: 0.3.11
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - files_fulltextsearch
 - fulltextsearch_elasticsearch
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "**website FQDN**"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "**website FQDN**",
    "dbtype": "mysql",
    "version": "13.0.0.14",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "loglevel": 0,
    "defaultapp": "apporder",
    "knowledgebaseenabled": "true",
    "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' data: blob:; frame-src *; img-src *; font-src 'self' data: blob:; media-src *",
    "maintenance": false,
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "data-fingerprint": "5c3098e6911a583ef4c3c8b6ee9c84de",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\Epub",
        "OC\\Preview\\PDF",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\StarOffice",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007",
        "OC\\Preview\\FB2"
    ],
    "mysql.utf8mb4": true
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Trace of network from browser:
![files_nextcloud_03](https://user-images.githubusercontent.com/7695965/36193474-5d2a8726-1166-11e8-98a5-8a2cb40a4df3.png)

![files_nextcloud_04](https://user-images.githubusercontent.com/7695965/36193476-60104340-1166-11e8-8b86-1db982bac094.png)
![files_nextcloud_05](https://user-images.githubusercontent.com/7695965/36193478-63528040-1166-11e8-80b9-f67380827778.png)

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**NO

### Client configuration
**Browser:**
Firefox 58.0.1 / 58.0.2

**Operating system:**
Ubuntu 14.0.4 / Firefox
Win10 / Firefox-IE11

Wh3rmel0_2104
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
access.log by opening files:
213.233.219.200 - - [14/Feb/2018:09:12:56 +0100] "GET /cron.php HTTP/2.0" 200 700 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:12:57 +0100] "GET /apps/apporder/getOrder HTTP/2.0" 200 838 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:12:58 +0100] "GET /apps/theming/icon/activity?v=17 HTTP/2.0" 200 14917 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:12:58 +0100] "GET /apps/encryption/ajax/getStatus HTTP/2.0" 200 702 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:12:58 +0100] "GET /ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0 HTTP/2.0" 200 2353 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:13:05 +0100] "GET /avatar/pieter/21 HTTP/2.0" 200 1501 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:13:28 +0100] "GET /apps/theming/favicon/activity?v=17 HTTP/2.0" 499 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:13:28 +0100] "GET /core/preview.png?file=/OCR_test.jpg&c=ad4287be85464ad931334041a808184b&x=150&y=150 HTTP/2.0" 499 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:13:30 +0100] "GET /apps/theming/favicon/activity?v=17 HTTP/2.0" 200 4492 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:13:34 +0100] "GET /apps/files/ HTTP/2.0" 200 9166 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:13:43 +0100] "GET /apps/encryption/ajax/getStatus HTTP/2.0" 200 700 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:13:43 +0100] "GET /cron.php HTTP/2.0" 200 698 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
213.233.219.200 - - [14/Feb/2018:09:13:44 +0100] "GET /apps/apporder/getOrder HTTP/2.0" 200 836 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
^C

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
Looks like a duplicate of #8043 (we have a fix ready for 13.0.1)

And those steps should help as a workaround:

```
- rm -r data/appdata_*/css/* data/appdata_*/js/*
- occ files:scan-app-data
- reload the page
```

Could you confirm that this helps? (and of course clearing the browser cache after those steps as well).

**Comment by dvzrv** [comment]
@MorrisJobke your suggested fix made things worse for me: firefox only loads the files app now, but still without actual files, chromium is now unable to even login.

In firefox the developer console throws a lot of "OC{,A} is not defined" errors, when trying to load the basic javascript files.
Seems that the above steps reproduced the css files, but not the javascript files.

**Comment by dvzrv** [comment]
However, I can confirm, that after copying back the backup of the javascript files, the files are now shown as intended!

**Comment by MorrisJobke** [comment]
:/ cc @juliushaertl looks weird

**Comment by juliushaertl** [comment]
@linuxpete @dvzrv Can you also provide the Nextcloud log files?

**Comment by linuxpete** [comment]
Hi allemaal, was a des dates off-line, will try tot send thema logging
today of tomorrow Amsterdam time.




Met vriendelijke groet


Pieter Wolters


Deze mail is verstuurd met een PDA en kan om deze reden korter zijn dan
verwacht waarvoor mijn excuses.


This mail was sent with a tablet or telephone and may be somewhat shorter
than expected. My apologies.


Op 17 feb. 2018 14:44 schreef "Julius Härtl" <notifications@github.com>:

@linuxpete <https://github.com/linuxpete> @dvzrv <https://github.com/dvzrv>
Can you also provide the Nextcloud log files?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nextcloud/server/issues/8347#issuecomment-366442345>,
or mute the thread

**Comment by linuxpete** [comment]
@MorrisJobke  if I look at #8043 then my button is on the login screen, it is not this thing I have. 

I tried the said workaround but now the installation is in error. :-( 

first I have redo the upgrade. after that I will send the log files.

**Comment by linuxpete** [comment]
@MorrisJobke  if I look at #8043 then my button is on the login screen, it is not this thing I have. 

I tried the said workaround but now the installation is in error. :-( 

On login I see the arrow duplicated. (see picture)
![schermafbeelding 2018-02-17 om 18 46 00](https://user-images.githubusercontent.com/7695965/36349218-a026f2a8-1481-11e8-8af8-6e98ec532c6d.png)

But the files are still not shown.

**Comment by linuxpete** [comment]
@MorrisJobke 
Hi, here the nexcloud logfile on opening the files-app:
```
{"reqId":"RVQKsDqACpOgRmvlerhc","level":0,"time":"2018-02-18T06:57:25+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"core","method":"GET","url":"\/apps\/files\/","message":"\/apps\/files\/css\/merged.scss compiled and successfully cached","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"RVQKsDqACpOgRmvlerhc","level":0,"time":"2018-02-18T06:57:32+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"core","method":"GET","url":"\/apps\/files\/","message":"\/apps\/files_trashbin\/css\/trash.scss compiled and successfully cached","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"RVQKsDqACpOgRmvlerhc","level":0,"time":"2018-02-18T06:57:40+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"core","method":"GET","url":"\/apps\/files\/","message":"\/apps\/comments\/css\/autocomplete.scss compiled and successfully cached","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"RVQKsDqACpOgRmvlerhc","level":0,"time":"2018-02-18T06:57:44+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"core","method":"GET","url":"\/apps\/files\/","message":"\/apps\/files_sharing\/css\/mergedAdditionalStyles.scss compiled and successfully cached","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"RVQKsDqACpOgRmvlerhc","level":0,"time":"2018-02-18T06:57:50+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"core","method":"GET","url":"\/apps\/files\/","message":"\/core\/css\/systemtags.scss compiled and successfully cached","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"4s0yVjm9umk7TzK7x73l","level":1,"time":"2018-02-18T07:03:30+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"admin_audit","method":"GET","url":"\/logout?requesttoken=79gyYR0Qsk9c2wVbYmLRAI1kx6ypMozX557St8F4oPs%3D%3Anql%2BOU1ehhcPqmEUSQPgZsQFoPrueMOv3vTl0Y0807U%3D","message":"Logout occurred","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"OR1lULB45AlsbhyEwDXO","level":0,"time":"2018-02-18T07:03:36+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/srv\/www\/nc13\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"OR1lULB45AlsbhyEwDXO","level":0,"time":"2018-02-18T07:03:36+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/srv\/www\/nc13\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"OR1lULB45AlsbhyEwDXO","level":0,"time":"2018-02-18T07:03:36+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/srv\/www\/nc13\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"OR1lULB45AlsbhyEwDXO","level":0,"time":"2018-02-18T07:03:36+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/srv\/www\/nc13\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"IKMuYBkKYLaweXTGC42E","level":1,"time":"2018-02-18T07:04:20+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"admin_audit","method":"POST","url":"\/login","message":"Login attempt: \"admin\"","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"IKMuYBkKYLaweXTGC42E","level":1,"time":"2018-02-18T07:04:20+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"admin_audit","method":"POST","url":"\/login","message":"Login successful: \"admin\"","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"axo30j4GsEtePxodqyhO","level":0,"time":"2018-02-18T07:04:23+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"core","method":"GET","url":"\/login\/challenge\/totp","message":"Scss is disabled for \/srv\/www\/nc13\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"axo30j4GsEtePxodqyhO","level":0,"time":"2018-02-18T07:04:23+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"core","method":"GET","url":"\/login\/challenge\/totp","message":"Scss is disabled for \/srv\/www\/nc13\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"axo30j4GsEtePxodqyhO","level":0,"time":"2018-02-18T07:04:23+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"core","method":"GET","url":"\/login\/challenge\/totp","message":"Scss is disabled for \/srv\/www\/nc13\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"axo30j4GsEtePxodqyhO","level":0,"time":"2018-02-18T07:04:23+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"core","method":"GET","url":"\/login\/challenge\/totp","message":"Scss is disabled for \/srv\/www\/nc13\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
```

**Comment by linuxpete** [comment]
I did a clean install which gives no problems, somewhere in the upgrade is something going wrong.
The nextcloud.log doesn't give any messages.

![schermafbeelding 2018-02-19 om 15 20 32](https://user-images.githubusercontent.com/7695965/36387656-d5e84fd6-1599-11e8-8483-e8bf05a729de.png)

Grtz Pieter

**Comment by juliushaertl** [comment]
I see nothing wrong in the logs. Can you check the file integrity after the upgrade with: 
`sudo -u www-data php ./occ integrity:check-core`

**Comment by linuxpete** [comment]
@juliushaertl 
I just did with no error:
```
root@workhorse:/srv/www/nc13#
root@workhorse:/srv/www/nc13# sudo -u www-data php ./occ integrity:check-core
root@workhorse:/srv/www/nc13# `
```

**Comment by linuxpete** [comment]
Hi all

Last weeks I was struggeling with this error when in a test setting I had the same error in the 12.0.5 version.  Then I ran : 

`- sudo -u www-data php occ files:scan-app-data`

but without empty-ing the said directories : 
`rm -r data/appdata_*/css/* data/appdata_*/js/*`
and the error disappeared on the 12.0.5 installation.

After upgrading to 13.0 to the file screen is OK. However after upgrading there still is a thing with the CSS as you can see below. the rendering is slightly off, look for example at the select squares. 

So now I will let run the `scan-app-data` again on the test installation to let it finish and let it run before upgrade on the original installation. 

**Pristine V13 installation**
![screenshot from 2018-03-04 14 41 10](https://user-images.githubusercontent.com/7695965/36946247-3ac2d974-1fba-11e8-9776-63c895e56dea.png)

**Upgraded V13 (from V12-V11-V10-OC10-OC9) installation**

![screenshot from 2018-03-04 14 41 24](https://user-images.githubusercontent.com/7695965/36946258-6216c3f0-1fba-11e8-8fdc-9d0a2597b08d.png)

**Comment by linuxpete** [comment]
OK, I had the styling right on a test installation. 

This after removing the css and js directories of the "files" app (in `data/appdata_*/css/* data/appdata_*/js/*` ). 

Before migrating I ran the command `sudo -u www-data php occ files:scan-app-data`. And it worked like a charm. So consider this problem as "solved".

Grtz and thanks for the input.
