### ISSUE TITLE
Update page doen't get themed

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#835]
We need to load the theming app css file in the update routine.

Somewhere here: https://github.com/nextcloud/server/blob/fa352a81a5d54fb5530c6a17be6d2847025584eb/lib/base.php#L377-L378

**Comment by rullzer** [comment]
Do we really want this?

IMO the updating should be as simple as possible. Enough can go wrong already and I don't think we need theming to mess with that.

**Comment by juliushaertl** [comment]
It would be nice to have, but I think you are right, as loading the theming app and generating the css stuff might have too much potential of breaking something.

**Comment by nickvergessen** [comment]
I agree with @rullzer apps are not loaded in the update for a reason.

**Comment by LukasReschke** [comment]
Closing due to :bomb: 🎐

**Comment by LukasReschke** [comment]
Closing due to :bomb: 😉
