### ISSUE TITLE
Don't throw 404 in /core/preview.png?file= if no preview exists

### ISSUE THREAD

**Issue by jknockaert** [nextcloud/server#8354]
Seems like NC13 is throwing a 404 when requesting preview.png for unsupported mime types. That would be a regression of https://github.com/owncloud/core/issues/24216

**Comment by rullzer** [comment]
Well if the mime type is unsupported we don't have a preview so the 404 is valid.

As far as I can tell the webinterface also does not request previews for files we don't support.

Do you have an example file?

**Comment by jknockaert** [comment]
The access log seems full of preview.png 404s, including for pdf, xls, and other type of files.

**Comment by rullzer** [comment]
We probably should not request them sure.

But the 404 error on the endpoint is perfectly valid.

**Comment by jknockaert** [comment]
Well, it is the endpoint sending code to the client that results in the client generating bogus requests. But you're right that there is no bug at the point where the endpoint generates a 404.
This issue was fixed before, so it is likely a regression.

**Comment by eMPee584** [comment]
Actually, how about merging this pull request?
https://github.com/owncloud/core/pull/27558

**Comment by eMPee584** [comment]
cf. these commits:
https://github.com/owncloud/core/commit/e3790f0275da7e228265cf8d2e7b502c118b5407
https://github.com/owncloud/core/commit/45aef4de9150cec3c25cddd246f7fa357484f427

**Comment by jzahraoui** [comment]
Hello,
I'm using fail2ban to scan the nginx log. The problem is, if they are to many 404 in this log I get banned. I think this rule is good and I don't want to remove it. can you think there is a workaround to make NC and fail2ban happy together ?
I'm using NC v15.0.7

**Comment by bszente** [comment]
> This should be reopened, as it is still somewhat annoying from a server admin's perspective ....
> Isn't [owncloud/core#24216 (comment)](https://github.com/owncloud/core/issues/24216#issuecomment-217778511) a viable solution?

I completely agree with this. It is annoying to see errors in the JS console. It makes the admin think that there are configuration or install issues.

**Comment by RepositoriumCodice** [comment]
Same issue here. I have users complaining and also fail2ban reacting to the 404's. Users don't feel secure if they see errors and they doubt quality of the app. It's not just one error, it could be hundreds.

**Comment by elalann** [comment]
Any news on this? It seems to be already fixed on OwnCloud with serving 204 code and some custom js at the client side.
