### ISSUE TITLE
Login method over LDAP with "samaccountname" and using tokens causes locking the ActiveDirectory account

### ISSUE THREAD

**Issue by sburrey** [nextcloud/server#8360]
Login method over LDAP with "samaccountname" and using tokens causes locking the ActiveDirectory account (affects to Nextcloud 13.0.0 stable)

### Steps to reproduce
1. Enable LDAP integration with login method by 'samaccountname' as the only one (because of using SMB share based on 'Log-in credentials, save in session' method)
2. Create token - the automatic generated username was based on 'samaccountname' (see No. 1)
3. Login with Dektop- or Mobile-Client using the created token (see No. 2) causes locking the ActiveDirectory account

### Expected behaviour
Token username should unlike samaccountname. For Example: combination of LDAP attribute 'givenName' & 'sn' (sureName)

### Actual behaviour
n/a

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
With token I guess refer to the app password? When authenticating at Nextcloud with that, it unwraps the password and should interact with that agains the other backends. cc @ChristophWurst

**Comment by blizzz** [comment]
The loginname as entered is used and passed to the LDAP backend's authentication method, which looks up the DN based on the login filter and does the bind with the found dn and the master password. This mechanism works here.

Is it possible you have changed passwords?

**Comment by sburrey** [comment]
It was a problem of understanding how the machnism of tokens is working.
Case can be closed.

Thank you.

**Comment by sburrey** [comment]
[CLOSED]
