### ISSUE TITLE
News App: Configurable/Dynamic width of the feed list

### ISSUE THREAD

**Issue by svenschn** [nextcloud/server#8361]
Hi,

I filed this issue in the News App project (see https://github.com/nextcloud/news/issues/265) but I was told that it belongs here, so:

I've just updated my installation to Nextcloud 13 and News App 12.0.1. Everything seems to work but there is one issue: The feed list on the left hand side is quite small so that i can only guess which feed it is (text is cropped, see screenshot). Is it possible to change the width manually (I could not find any related setting and there seems to be no "anchor" to move around with the mouse)? If not, could this be implemented? Alternatively, the width could be increased globally, of course.

![grafik](https://user-images.githubusercontent.com/33999906/36072727-e398d072-0f24-11e8-8c43-378c534d91b3.png)

My screen resolution is 1600*900.

Thanks in advance!

## System Information
* News app version: 12.0.1
* Nextcloud version: 13.0.0
* PHP version: 7.1.13
* Browser and version: Firefox 58.0.1

## Contents of Browser Error Console
Nothing but some mixes content warnings due to some non-HTTPS feeds

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by MorrisJobke** [comment]
Ref #6041

**Comment by Anrock** [comment]
Any updates on this? It's a PITA to navigate feeds without names.

**Comment by jancborchardt** [comment]
Some proposals:
- Indent the subentries a bit less. Make the icon left-aligned with the parent folder text
- Use more space to the right (to the unread count)
- Unread count is not clickable so it doesn’t need so much padding to left and right
- Limit unread count to 2 digits
- Only show 3-dot-menu for the active entry

**Comment by floli** [comment]
I am not big into web design and programming, but isn't there a possibility to make the border of the side bar draggable with the mouse?

**Comment by juliushaertl** [comment]
The sidebar has a new width of 300px with NC14 so this should be fixed.

![image](https://user-images.githubusercontent.com/3404133/46666520-2edd8500-cbc7-11e8-94a7-d3dade0fa16c.png)
