### ISSUE TITLE
strange mistake with drag end drop web file interfaces

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#8370]
When I drag a file to upload via the web, it is done correctly but after the finished upload appears a word that tells me:

Unable to create file ""

I do not know what that means when uploading by dragging is done correctly.

made a screenshot to show you,
I circled the banner in red
![immagine](https://user-images.githubusercontent.com/35575744/36251049-116b7b6c-1240-11e8-9bc8-f6b918dbccad.png)

**Comment by tigernero79** [comment]
I noticed that lop error occurs when I enable e2e module and yet the folder is not encrypted

**Comment by MorrisJobke** [comment]
cc @schiessle @danxuliu

**Comment by tigernero79** [comment]
error generated by the problem exposed in # 8379

https://github.com/nextcloud/server/issues/8379

**Comment by schiessle** [comment]
do you have server-side encryption enabled in parallel? Then this should fix it: https://github.com/nextcloud/end_to_end_encryption/pull/61, maybe you can apply this two line change and report back if it solves the issue for you: https://github.com/nextcloud/end_to_end_encryption/pull/61/commits/cb7e3b1ac51d65beb4a8d6bbdbb551ae02982fa7

**Comment by schiessle** [comment]
Should be solved with the End to End Encryption app version 1.0.4 for the Nextcloud Server and the Android client 3.0.2... If not, please open a issue in the corresponding repository
