### ISSUE TITLE
Standardisation summary

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#8374]
You will find all of the standardisation pr/isssues/doc in this thread.
This will be updated in real time.

https://docs.nextcloud.com/server/13/developer_manual/index.html

## DONE
| What | Issue - Pull request | Documentation |
|:------|:-----|:-----|
| Left sidebar navigation | #6399 | nextcloud/documentation#565 |
| Popover menu | #2798 - #3024  | nextcloud/documentation#565 |
| Checkboxes - Radios | #3121 - #3187  | nextcloud/documentation#565 |
| Progress bar | #6669 | nextcloud/documentation#565 |
| App content list | #6612 - #7195 | nextcloud/documentation#638 |
| Public page template | #6553 - #8051 | nextcloud/documentation#697 |
| Top right header | #8373 | _not planned_ |
| Breadcrumbs | https://github.com/nextcloud/server/pull/7051#issuecomment-342940681 - #7051 | _not planned_  |
| New 'xxxx' button in navigation | #7600 | nextcloud/documentation#684 |
| Inputs/form in popover | #8575 | nextcloud/documentation#684 |

## IN PROGRESS
| What | Issue - Pull request | Documentation |
|:------|:-----|:-----|
| Search | #9912  |  |
| Css4 variables | #9723   |  |
| Right sidebar | #10289 | |

## TODO
| What | Issue - Pull request | Documentation |
|:------|:-----|:-----|

**Comment by MorrisJobke** [comment]
@skjnldsv Does this somehow overlap with #10289?

**Comment by skjnldsv** [comment]
@MorrisJobke no, this is for al of the standards we implemented, not just the sidebar ;)

**Comment by skjnldsv** [comment]
Standards is now moved to vue-components for better ease-of-use :)
We will maintain existing standards and bugs from https://docs.nextcloud.com/server/16/developer_manual/design/index.html

Please now migrate to vue components as you will receive further bug fixes and design update simultaneously as everyone else.
