### ISSUE TITLE
Missing email field when admin create/add new user

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#8377]
as an admin, when creating new users, should be able to directly add email.

purpose: when i create users, i want to put a dummy password, and let then connect end retrieve/recreate password themselfs.

Problem: as any emails is created when admin add a new user, this is not possible.

![rrf](https://user-images.githubusercontent.com/8655165/36257976-5936d6bc-1259-11e8-9adc-128f879475c9.png)

**Comment by stratege1401** [comment]
get answer alredy, close please

> > It is possible. With Version 13.0.0 you can display the e-mail field if you select “Settings” (at the buttom on the left side) -> “Send email to new user”.
> 
> Cheers zisuu

**Comment by MorrisJobke** [comment]
Also #7600 will improve this a lot ;)
