### ISSUE TITLE
Nextcloud 13 doesnt show the transfer progress of multiple files

### ISSUE THREAD

**Issue by bitking** [nextcloud/server#8378]
Nextcloud version (eg, 12.0.2): 13.0.0
Operating system and version (eg, Ubuntu 17.04): Ubuntu 16.04
Apache or nginx version (eg, Apache 2.4.25): Apache/2.4.18 (Ubuntu)
PHP version (eg, 7.1): PHP 7.0.22-0ubuntu0.16.04.1

The issue you are facing:

Is this the first time you’ve seen this error? (Y/N): Yes

Steps to replicate it:

Select multiple files i do more then 10, drag them to your nextcloud browser window.
The files gets transferred but the progress bar will dissapear
You still see files getting uploaded but you dont see the progress bar anymore.
The output of your Nextcloud log in Admin > Logging:

Only updater stuff from the update from 12.0.5 to 13.0.0.
The output of your config.php file in /path/to/nextcloud (make sure you remove any identifiable information!):

Not needed.
The output of your Apache/nginx/system log in /var/log/____:

Nothing noteworty.

**Comment by Schmuuu** [comment]
There is another issue opened for that one already:
https://github.com/nextcloud/server/issues/8106

I think this issue here can be closed then. Let's track the progress in the other one.

**Comment by LaurentNEBUT** [comment]
Hello guys,

  I post a solution on #8106 

By
