### ISSUE TITLE
 client not allowed to access end-to-end encrypted

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#8379]
I create folders with files and I can not then delete the newly created files, from log says I do not have permissions to e2e, but folder nn is encrypted in the file. And I cmq inserted codes just because?

OCA\DAV\Connector\Sabre\Exception\Forbidden: client not allowed to access end-to-end encrypted content/web/htdocs/www.pensierando.it/home/Nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php- line 124:OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkUserAgent('Mozilla/5.0 (Li...', '/Nuova cartella...')[internal function]OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/web/htdocs/www.pensierando.it/home/Nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php- line 105: call_user_func_array(Array, Array)/web/htdocs/www.pensierando.it/home/Nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php- line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)/web/htdocs/www.pensierando.it/home/Nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php- line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/web/htdocs/www.pensierando.it/home/Nextcl

**Comment by MorrisJobke** [comment]
cc @schiessle @rullzer @tobiasKaminsky

**Comment by psi-4ward** [comment]
Same here. Latest nextcloud and android app.

**Comment by tobiasKaminsky** [comment]
On android you currently cannot delete an encrypted folder with files. You have to delete the files in it and then you should be able to delete the folder.
There should be some sort of warning "Folder not empty"?

**Comment by tigernero79** [comment]
tobias the problem is that the folder is not encrypted. the problem is that with the module e2e active if I create an unencrypted folder and inside it create a file I can not delete it, it tells me client does not have permissions e2e as an example but neither the folder nor the file is encrypted. if I disable e2e module I can delete files. if I reactivate it, I can delete a folder with files inside but not just files. I'm talking about unencrypted folders

**Comment by tigernero79** [comment]
I create a normal folder, inside I create a TXT file for example, with module e2e active I can delete the folder with the file inside both unencrypted. but if I try to delete the file from inside normal folder I'm wrong I'm told I do not have permission to delete files. but I repeat the folder I did not encrypt it. if you want I can create test accounts to let you try it too. if I disable e2e module I can safely delete the file. Do you understand?

**Comment by tobiasKaminsky** [comment]
Can you create us a test account and send the credentials to android at nextcloud dot com with a reference to this issue?

**Comment by tobiasKaminsky** [comment]
To clarify: you are talking about the android client? Or about which client? Desktop? iOS?

**Comment by tigernero79** [comment]
the problem is presented with both an android application and a web interface, from desktop everything is ok, I have not tested on ios.

leave me here email that I send you the data for testing

**Comment by tobiasKaminsky** [comment]
android at nextcloud dot com

**Comment by tigernero79** [comment]
I just sent you email, via "nero79 at msn dot com"

can you confirm that you have arrived?

**Comment by sysoppl** [comment]
Same here. Im using web interface - cannot delete files after enabling e2e.
I think this is the same as #https://github.com/nextcloud/end_to_end_encryption/issues/47#

**Comment by tigernero79** [comment]
I think there are some bugs in the end to end module, because the error is generated on files that are found in normal unencrypted folders, and both from web and from android application the problem exists.

so we know that you can not delete a file in an encrypted folder not yet at least.

but here we talk about files in normal folders.

if you deactivate the module, you will be able to delete the bug in the e2e server module

**Comment by tobiasKaminsky** [comment]
@schiessle it seems that this is (again) related to server side encryption?

**Comment by tigernero79** [comment]
e-mail of tobias arrived? let me know if you need anything else for testing and when you'll finish

**Comment by tigernero79** [comment]
cc @schiessle @tobiasKaminsky 
I want to clarify that this bug does not allow even to download files from folders via android application, it is as if it denies the module e2e operations on files.

here I am forced to disable module now to work on my files

**Comment by tigernero79** [comment]
@tobiasKaminsky 

if you enter with my credentials now everything works because I have module disabled, if you want to replicate error tell me that reactivate module e2e

**Comment by tobiasKaminsky** [comment]
Thanks for now, @tigernero79.
We have to wait for response from @schiessle.

**Comment by schiessle** [comment]
if you use server-side encryption in parallel, this should fix it: https://github.com/nextcloud/end_to_end_encryption/pull/61, maybe you can apply this two line change and report back if it solves the issue for you: https://github.com/nextcloud/end_to_end_encryption/pull/61/commits/cb7e3b1ac51d65beb4a8d6bbdbb551ae02982fa7

**Comment by tigernero79** [comment]
@schiessle will you release an e2e module update for this fix?

**Comment by schiessle** [comment]
yes, as soon as I know that if fixes the issue

**Comment by tigernero79** [comment]
thank you. I will try to disable server-side data encryption and enable e2e and see if it goes. as soon as the reactivation fix comes out also on the server side.

**Comment by tigernero79** [comment]
@ schiessle just checked, I removed the check on the server side of the data. e2e is enabled. everything is ok. it should only be solved as it says the possibility of having both protections active

**Comment by schiessle** [comment]
@tobiasKaminsky I just released a new version of the end-to-end encryption app. Now we only need to have a update of the Android app to make sure that it sends "Nextcloud" and not "ownCloud" as part of the user argent string.

**Comment by schiessle** [comment]
closed as the server side part should be fixed

**Comment by tobiasKaminsky** [comment]
This is already the case with 3.0.2: it sends Nextcloud UserAgent on all E2E related calls.

**Comment by psi-4ward** [comment]
Uploading works now but only at the root-level on enc folders, uploading to nested folders brings the access denied again.

**Comment by tigernero79** [comment]
But above all, the problem also gives it to unencrypted folders, without deleting the files.

**Comment by schiessle** [comment]
@tobiasKaminsky ahm 3.0.2 was already released. I still have 3.0.1 (f-droid). Then everything should be fine :smiley: 

As I don't have 3.0.2 yet, can you reproduce what @psi-4ward reported?

**Comment by schiessle** [comment]
> But above all, the problem also gives it to unencrypted folders, without deleting the files.

Sorry, I don't understand it. Please give a detailed step by step explanation how to reproduce it and which Nextcloud, e2e app and Android-app version you are using.

**Comment by tigernero79** [comment]
problem reported here https://github.com/nextcloud/android/issues/2247

Android app 3.0.2 
e2e 1.0.2 
Nextcloud 13.0
Server side enabled 
E2e enabled

Error delete file in normal folder

**Comment by tigernero79** [comment]
@schiessle 

seen now update e2e version 1.0.4 I update and I try

**Comment by tigernero79** [comment]
@schiessle e @tobiasKaminsky 

With e2e 1.0.4 everything works now. good. remains the ability to delete e2e folders and to be able to view through the android application the 12 words of encryption as it already happens with ios application

**Comment by AlekseiMarinichenko** [comment]
What if I have nested folders in the encrypted folder? 

I need to remove files in the folder, then remove all files in the nested folders, then to remove files in the nested folders inside nested folders... Excuse me, are you kidding? 

Are there any updates? Is there a fast way to remove the encrypted folder from the web interface or Android app?
