### ISSUE TITLE
Introduce »Updates« navigation section for Apps mgmt instead of confusing notification

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#838]
Currently there’s still the »You have 3 app updates pending« notification which is not really helpful. We need to move from that to a dedicated left navigation entry for »Updates«.

cc @nickvergessen cause you worked on that before.

**Comment by nickvergessen** [comment]
Yeah, will have a look after the new app store thing is done

**Comment by MorrisJobke** [comment]
> Yeah, will have a look after the new app store thing is done

It is done, but I guess it's too late for 12. Moving to 13.

**Comment by jancborchardt** [comment]
@nickvergessen any update about this? :) Would be cool to get this fixed also as the apps management has been overhauled nicely otherwise.

**Comment by juliushaertl** [comment]
Let me dig into this.
