### ISSUE TITLE
Adjust treat model

### ISSUE THREAD

**Issue by rugk** [nextcloud/server#8381]
Sorry that this issue is about your website, but I could not find a better place to report it.

So your threat model at https://nextcloud.com/security/threat-model/ is sometimes a bit outdated as it seems. E.g. AFAIK in NC 11 or 12 you've integrated brute force protection, so 
> we currently expect people to protect their instance using measures such as fail2ban. We do have a native anti-bruteforce protection.

is no longer true.

Same for the Android content provider. I am not sure whether this is the "Open file" -> "Nextcloud" thing, but if it is that, this is also no longer true:
> (since no Content Provider is yet implemented).

Of course, you should describe there that downloaded files are saved on your sd card (or other storage) and are accessible by all apps.

Also as for the NC 13 you might add something about the e2e crypto there. (or link to your whitepaper or whatever)

**Comment by rullzer** [comment]
@jospoortvliet

**Comment by rullzer** [comment]
please fill in https://github.com/nextcloud/nextcloud.com

**Comment by rugk** [comment]
Done: https://github.com/nextcloud/nextcloud.com/issues/847
