### ISSUE TITLE
Can't sync file with tab or newline character in filename

### ISSUE THREAD

**Issue by samtygier** [nextcloud/server#8386]
### Steps to reproduce
1. Set up a sync folder (I am using the desktop client 2.3.3 on Fedora 27 linux)
2. Create a file in the sync'ed folder with a tab or newline character in the filename
3. Wait or force a sync

### Expected behaviour
Allow syncing any file with a valid linux filename
or
A useful suggestion of how to fix it

### Actual behaviour
Error message about invalid filename
... file%0A.txt - server replied: Bad Request (File name contains at least one invalid character)

![screenshot from 2018-02-15 22-11-49a](https://user-images.githubusercontent.com/1113988/36285482-a3a49a50-12a3-11e8-8009-1288da5fd77e.png)

### Server configuration

**Operating system**: Debian 9.

**Web server:**  **Database:** **PHP version:** **Nextcloud version:** (see Nextcloud admin page) Nextcloud snap 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** snap

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - ojsxc
  - user_external
  - user_ldap
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/tmp\/sockets\/redis.sock",
            "port": 0
        },
        "instanceid": "oc8aroz9qcal",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8080",
            "removed.ddns.net"
        ],
        "datadirectory": "\/media\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "dbtype": "mysql",
        "version": "12.0.5.3",
        "dbname": "nextcloud",
        "dbhost": "localhost:\/tmp\/sockets\/mysql.sock",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Files on /media

**Are you using encryption:** https only

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox

**Operating system:** Fedora 27

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> Allow syncing any file with a valid linux filename
> or
> A useful suggestion of how to fix it

We should look into which one is the better approach. First one is preferred of course. cc @icewind1991 for filesystem feedback.

**Comment by icewind1991** [comment]
> Allow syncing any file with a valid linux filename

Will break the moment any other system gets involved.

There isn't really a good way to sync anything but a "safe" set of file names that works across supported platform.

The best option here would probably be the sync client having better handling of the specific error

**Comment by MorrisJobke** [comment]
> There isn't really a good way to sync anything but a "safe" set of file names that works across supported platform.

In the past we always came down to this one.



> The best option here would probably be the sync client having better handling of the specific error

And this is the only way to handle this gracefully. Thus closing here in the server repo.
