### ISSUE TITLE
the not installed encryption app. blockcked the system

### ISSUE THREAD

**Issue by akaro** [nextcloud/server#8393]
### Steps to reproduce
1.Version 13.0.0.14
2.
3.

### Expected behaviour
Tell us what should happen
![blocked](https://user-images.githubusercontent.com/913393/36305125-a18ead4a-1312-11e8-9b2b-7190a3f01012.jpg)

### Actual behaviour
Menu wird mit der Meldung  (\*) geblockt. Keine Anwendung mehr möglich.
The Massage (\*) blocked the App Menu
(\*)Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files.

### Server configuration

**Operating system**:
Ubuntu 16.04.03
**Web server:**
apache2
**Database:**
Mysql
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
see in config.php file
**Updated from an older Nextcloud/ownCloud or fresh install:**
Update since Feb 15 01:27
**Where did you install Nextcloud from:**
Update from 12.03 to 13.0.0.14
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - apporder: 0.4.1
  - audioplayer: 2.2.5
  - bookmarks: 0.10.1
  - calendar: 1.6.0
  - comments: 1.3.0
  - dav: 1.4.6
  - encryption: 2.0.0
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_reader: 1.2.2
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - gpxedit: 0.0.8
  - gpxmotion: 0.0.6
  - gpxpod: 2.2.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.9
  - music: 0.5.5
  - news: 12.0.1
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ocsms: 1.12.2
  - ojsxc: 3.3.2
  - onlyoffice: 1.2.0
  - password_policy: 1.3.0
  - phonetrack: 0.1.1
  - provisioning_api: 1.3.0
  - radio: 0.6.1
  - rainloop: 5.0.6
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - spreedme: 0.3.11
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_u2f: 1.5.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - bruteforcesettings
  - contacts
  - direct_menu
  - gluusso
  - ocr
  - quota_warning
  - richdocuments
  - twofactor_totp
  - user_external
  - user_ldap
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
cd /var/www/nextcloud

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
{
    "system": {
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "2": "next.shtark.org"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "defaultapp": "apporder",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "theme": ""
    }
}

or 

Insert your config.php content here. 
<?php
$CONFIG = array (
  'secret' => '8YEeT/vzN6xiawiUSDt6wr4r11to02h0g58F9WLvT',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    2 => 'next.shtark.org',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'http://localhost',
  'defaultapp' => 'apporder',
  'dbtype' => 'mysql',
  'version' => '13.0.0.14',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'eegh1peeghyaegheipiM6leiy',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'occwqaw',
  'mail_from_address' => 'alex',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'shtark.info',
  'loglevel' => 2,
  'maintenance' => false,
  'theme' => '',
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary> </summary>

```
**as nextcloud.txt**
[nextcloud.txt](https://github.com/nextcloud/server/files/1731025/nextcloud.txt)

Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by tflidd** [comment]
Was the server-side encryption enabled at any time? Were files encrypted and/or keys generated?
You can check in `<data>/<username>/` if there are encryption keys or encrypted files. If neither of them exists, there is just a `files` folder.

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
