### ISSUE TITLE
maintenance:mode produces a warning despite --quiet

### ISSUE THREAD

**Issue by sometoby** [nextcloud/server#8399]
### Steps to reproduce
1. `$ php occ maintenance:mode --on --quiet`
2. `$ php occ maintenance:mode --off --quiet`

### Expected behaviour
Maintenance mode is enabled and disabled. No output is produced unless a fatal error occurs.

### Actual behaviour
```sh
$ php occ maintenance:mode --off --quiet
Nextcloud is in maintenance mode - no apps have been loaded

```
The message is printed regardless of `--quiet` and `--no-warnings`.

This seems like an easily reproducible issue, so I'll take the liberty of omitting further details about my setup.

**Comment by weeman1337** [comment]
I started working on #9949. This issue here may be solved by that.
