### ISSUE TITLE
php7.2 with active apcu something happend: Error index Error: Class '\Icewind\SMB\Exception\InvalidArgumentException' not found 9 minutes ago 

### ISSUE THREAD

**Issue by gurussia** [nextcloud/server#8400]
HI guys.

Today i solve bug in php7.0 and php7.1 and activate php7.2 with apcu. Now when try open nextcloud it poen slow maybe 8 minutes and when i see in log it comment this:

Error	index	Error: Class '\Icewind\SMB\Exception\InvalidArgumentException' not found	9 minutes ago
Error	PHP	include(): Failed opening '/var/www/domain/apps/files_external/3rdparty/composer/../icewind/smb/src/Exception/InvalidArgumentException.php' for inclusion (include_path='/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Translation:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Util:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Nls:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Exception:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Date:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Filter:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Stream:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Socket_Client:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Stream_Wrapper:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Support:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Crypt_Blowfish:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Secret:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Flowed:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Mime:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Idna:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Mail:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_ListHeaders:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Imap_Client:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Smtp:/var/www/domain/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Filter:/var/www/domain/3rdparty/pear/console_getopt:/var/www/domain/3rdparty/pear/pear_exception:/var/www/domain/3rdparty/pear/pear-core-minimal/src:/var/www/domain/3rdparty/pear/archive_tar:/var/www/domain/apps') at /var/www/domain/lib/composer/composer/ClassLoader.php#443

**Comment by gurussia** [comment]
?

**Comment by tflidd** [comment]
Some code in the mail app was not ready for php 7.2 yet:
https://github.com/nextcloud/mail/issues/731

Please use Nextcloud 13, NC 12 is not fully compatible with php 7.2. Can you test again? If the error still exists, please fill out the issue template: https://github.com/nextcloud/server/blob/master/issue_template.md

**Comment by MorrisJobke** [comment]
> Please use Nextcloud 13, NC 12 is not fully compatible with php 7.2. Can you test again? If the error still exists, please fill out the issue template:

As @tflidd wrote: Nextcloud 12 does not support PHP 7.2 - see https://docs.nextcloud.com/server/12/admin_manual/installation/system_requirements.html#supported-platforms

Please use Nextcloud 13 for this.
