### ISSUE TITLE
Error app in context "username"doesn't exist, can't verify user data.

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#8402]
### Steps to reproduce
1. Create user. Log one time that user.
2. As admin, delete user.
3. Log out.
3. Log in. As admin, check loggin.

### Expected behaviour
Shouldn't verify user data if user was delete.

### Server configuration
N 13.0.0 
4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
/ apache 2.4.29 / php 7.0.27 / 10.1.26-MariaDB / mysqlnd 5.0.12 / phpadmin 4.6.6deb4 /
/ Redis server v=3.2.6 / HTTP2 / letsencrypt CA / Fail2ban 0.10.2 / curl 7.52.1-5

reproduce twice:

Error | no app in context | rod3 doesn't exist, can't verify user data. | 2018-02-16T20:49:05+0100
Error | no app in context | rod2 doesn't exist, can't verify user data. | 2018-02-16T20:38:35+0100

**Comment by GitHubUser4234** [comment]
Having the same issue in Nextcloud 13.0.2, seemingly triggered by OC\\Settings\\BackgroundJobs\\VerifyUserData cron job. Is this actually a real error or could it also be of log level 0 or 1?

**Comment by stratege1401** [comment]
Checked #8402 against NC13.0.4  :  was not able to reproduced bug.

One important change in config between feb16 and today, i have update /etc/php/7.0/apache2/php.ini to set memory_limit from `128M `to `6144M` in concordance with my RAM and restarted apache2

**Comment by MorrisJobke** [comment]
Fix is in #9965
