### ISSUE TITLE
psql initialization of database with admin dot in username

### ISSUE THREAD

**Issue by devel0** [nextcloud/server#8403]
### Steps to reproduce
1. create a nextcloud container and a psql database
2. at first connect use an admin name with dot ( eg. "my.admin" )

### Expected behaviour
successful creation of database

### Actual behaviour
error ( from postgres log )

```
[85] ERROR:  syntax error at or near "." at character 17
```

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** nginx

**Database:** postgres 10.0

**PHP version:**

**Nextcloud version:** 12.0.4

**Comment by stratege1401** [comment]
answer from psql-general email list:


> From: | "Roderick A(dot) Anderson" <raanders(at)cyber-office(dot)net>
> -- | --
> PostgreSQL <pgsql-general(at)postgresql(dot)org>
> Valid characters for user/role/group names?
> 2009-02-25 16:50:15
> 49A576C7.3090909@cyber-office.net (view raw, whole thread or download thread mbox)
> 2009-02-25 16:50:15 from "Roderick A(dot) Anderson" <raanders(at)cyber-office(dot)net>  2009-02-25 16:58:48 from Sam Mason <sam(at)samason(dot)me(dot)uk>   2009-02-25 17:05:15 from Tom Lane <tgl(at)sss(dot)pgh(dot)pa(dot)us>  2009-02-25 22:25:45 from "Roderick A(dot) Anderson" <raanders(at)cyber-office(dot)net>     2009-02-25 16:50:15 from "Roderick A(dot) Anderson" <raanders(at)cyber-office(dot)net>
> pgsql-general
> 
> In my continuing quest for multi-tenant ways I'm trying to come up with 
> a method to name roles, users, and groups that will not clash across the 
> cluster.  The plans are to have one database per tenant and place 
> applications in different schema in those databases.  This is working 
> fine so far but I'm now trying to come up with a naming scheme that will 
> allow a dba  account for tenant_1, tenant_2, etc.
>     I found, several months ago, a posting about using the at "@" symbol 
> in a role name so there could be a dba(at)tenant_1, dba(at)tenant_2, etc.  I 
> can't find the article again but I remember there was a reference to 
> possible issues with using the '@' and username entries in pg_hba.conf
>     If the '@' isn't a problem (other than possibly not being valid 
> according to the SQL standard I was going to use an '@tenant_1.txt' 
> entry in pg_hba.conf and place dba(at)tenant_1, bob(at)tenant_1, 
> sally(at)tenant_1 in it.
> 
> But according to
> 
> http://www.postgresql.org/docs/current/interactive/sql-syntax-lexical.html
> 
> "SQL identifiers and key words must begin with a letter (a-z, but also 
> letters with diacritical marks and non-Latin letters) or an underscore 
> (_). Subsequent characters in an identifier or key word can be letters, 
> underscores, digits (0-9), or dollar signs ($). Note that dollar signs 
> are not allowed in identifiers according to the letter of the SQL 
> standard, so their use might render applications less portable. ... "
> 
> I'm wondering what the reference to "non-Latin" letters means.
> 
> Anyone have a solution to this?
> 
> 
> Thanks,
> Rod
> -- 


for me, dot is not listed on valid characters.

**Comment by devel0** [comment]
Sorry I think not expressed fully,
the problem was not specifying a postgres user that contains dot in the name
but creating the initial admin user of nextcloud itself
that is the "uid" column of "oc_users" table that should a character varying(64) allowing dot as a normal string. I suppose the error reported `syntax error at or near "." at character 17` comes from some insert without quoting of the string, but I didn't go so deep and I can't confirm if this could the problem.

**Comment by stratege1401** [comment]
if this can help:

-- phpMyAdmin SQL Dump
-- version 4.6.6deb4
-- Host: localhost:3306
-- Generation Time: Feb 17, 2018 at 02:07 AM
-- Server version: 10.1.26-MariaDB-0+deb9u1
-- PHP Version: 7.0.27-0+deb9u1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `nextcloudDB`
--

-- --------------------------------------------------------

--
-- Table structure for table `oc_users`
--

CREATE TABLE `oc_users` (
  `uid` varchar(64) COLLATE utf8_bin NOT NULL DEFAULT '',
  `displayname` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `password` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Dumping data for table `oc_users`
--

INSERT INTO `oc_users` (`uid`, `displayname`, `password`) VALUES
('admin_alias_here', 'admin_realname_here', '1|crypted password here');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `oc_users`
--
ALTER TABLE `oc_users`
  ADD PRIMARY KEY (`uid`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
