### ISSUE TITLE
Broken contact links in web interface

### ISSUE THREAD

**Issue by Peque** [nextcloud/server#8404]
I recently upgraded to NC 13 and it seems some links in the Contacts app are not working in the web interface.

When I hover the contacts in the contact list (no click) I see 2 different types of links:

1. https://domain.com/apps/contacts/#/Group/e5c9a57f-d84c-4b8c-a59b-ee742e1b42a1
2. https://domain.com/apps/contacts/#/Group/https://User@old.domain.com/remote.php/carddav/addressbooks/User/contacts/2EAF6525-17ADC861-38D6BB1D.vcf

The second link type is broken (i.e.: if I click it, I get redirected to the Group's default page, which is the first contact in the group).

This did not happen before upgrade. Is it a known issue? Is there any way I can fix that?

Please, tell me if you need any further information.

Notes
------

- The contact information is intact and correct (i.e.: no information lost). Only the link is broken.
- Contacts that have the second-type link are older (i.e.: were created maybe long time ago). Contacts that have the first-type link are all more recent contacts.
- The second link contains "old.domain.com" too. The domain change is, however, something I did some time ago, before even upgrading to NC 12. And I didn't have this problem with NC 12.

Some extra information
------------------------

- Server:
  - OS: Ubuntu 16.04.3 LTS (Linux nextcloud 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
  - Web server: Apache
  - PHP version: PHP 7.0.25-0ubuntu0.16.04.1
  - Nextcloud version: 13.0.0
  - Upgraded from: Nextcloud 12 (fully upgraded when 13.0.0 was released)

**Comment by juliushaertl** [comment]
Please report this issue at the contacts app repo https://github.com/nextcloud/contacts

**Comment by Peque** [comment]
@juliushaertl Ok, they say "Migration and CardDAV issues belong in the server repo!" so thought this would belong here. :sweat_smile:

**Comment by Peque** [comment]
Just for the record: https://github.com/nextcloud/contacts/issues/487
