### ISSUE TITLE
Request: Hide Frame around app

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#8413]
I’d like to open my Nextcloud apps in the browser without the Nextcloud frame, but cannot find an option in the documentation.
![63110dc9-7d78-4241-ab4f-81ed243f0cef](https://user-images.githubusercontent.com/1787238/36345481-3705c2be-13e0-11e8-95d9-d185713b343f.png)
![e7d2c86d-93d2-4fd7-8d18-5bf7f4232eff](https://user-images.githubusercontent.com/1787238/36345483-3ce57b20-13e0-11e8-8880-b6e29cfde6d7.png)

**Comment by juliushaertl** [comment]
For app developers it is possible to render pages without the header, but as a user/admin there is no option because it is not supported.
