### ISSUE TITLE
NC 13: Add ownCloud upgrade paths to version.php

### ISSUE THREAD

**Issue by BernieO** [nextcloud/server#8414]
In Nextcloud 13.0.0 the upgrade paths from ownCloud are completely missing. This makes a migration from ownCloud to Nextcloud 13.0.0 impossible. I assume that is not the desired behaviour.

**Comment by nickvergessen** [comment]
Hmm I created https://github.com/nextcloud/server/issues/5901 back then for this.
But seems it was closed by someone, so I didn't keep track of it.

Anyway, you can still migrate to 12 and then update to 13 for now.

**Comment by BernieO** [comment]
Doesnt seem that migration from ownCloud > 10.0.5 to Nextcloud 12.0.5 is possible...
Or am I missing something??

**Comment by MorrisJobke** [comment]
> Doesnt seem that migration from ownCloud > 10.0.5 to Nextcloud 12.0.5 is possible...

Fixed by #8544 - either change it manually in the version.php after replacing the OC code with NC code or wait 2 weeks and we will ship it as a 12.0.6 ;)
