### ISSUE TITLE
{{ 'http.warning' | 'translate' }} on passman start page

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#8415]
Hello Devs.

The issue has been filed a while ago at https://github.com/nextcloud/passman/issues/282. The Dev thinks this is a core issue. So here we go.

Issue still exists on my system:
NC 13, Apache2.4, PHP-7.2.2

thanks and cheers
t.

**Comment by blizzz** [comment]
@skjnldsv @danxuliu an idea?

**Comment by pierrick-openIT** [comment]
Hi, same error for me with passman and NC 13. Somes news ?

**Comment by Githopp192** [comment]
Hi Gents .. same to me .. 
from on of the last hints .. there was a comment to replace personal.php with this code:

<?php
/* Placeholder file */

i did .. but i still get this error .. 

{{ 'http.warning' | 'translate' }}

The nextcloud.log shows  --->

Error	PHP	Method OC\L10N\L10NString::__toString() must return a string value at /var/www/html/nextcloud/lib/private/L10N/L10N.php#88	

Error	PHP	vsprintf(): Too few arguments at /var/www/html/nextcloud/lib/private/L10N/L10NString.php#79

Environment: centos 7.5, php71, nc13.02., mysql  Ver 15.1 Distrib 5.5.56-MariaDB

**Comment by Githopp192** [comment]
Hi Gents .. same to me ..
from one of the last hints .. there was a comment to replace personal.php with this code:

<?php
/* Placeholder file */

This are the corresponding nextcloud.log entries --> 

Error	PHP	Method OC\L10N\L10NString::__toString() must return a string value at /var/www/html/nextcloud/lib/private/L10N/L10N.php#88	Error	PHP	vsprintf(): Too few arguments at /var/www/html/nextcloud/lib/private/L10N/L10NString.php#79 

Environment: centos 7.5, php71, nc13.02., mysql Ver 15.1 Distrib 5.5.56-MariaDB

**Comment by Githopp192** [comment]
Hi Gents .. same to me ..
from one of the last hints .. there was a comment to replace personal.php with this code:
******************************
<?php
/* Placeholder file */
******************************
This are the corresponding nextcloud.log entries --> 
---
Error	PHP	Method OC\L10N\L10NString::__toString() must return a string value at /var/www/html/nextcloud/lib/private/L10N/L10N.php#88	Error	PHP	vsprintf(): Too few arguments at /var/www/html/nextcloud/lib/private/L10N/L10NString.php#79 
----
Environment: centos 7.5, php71, nc13.02., mysql Ver 15.1 Distrib 5.5.56-MariaDB

**Comment by Githopp192** [comment]
Hi Gents .. same to me ..
from one of the last hints .. there was a comment to replace personal.php with this code:
******************************
\<?php
\/* Placeholder file *\/
******************************
_This are the corresponding nextcloud.log entries --> 
---
_Error	PHP	Method OC\L10N\L10NString::__toString() must return a string value at /var/www/html/nextcloud/lib/private/L10N/L10N.php#88	Error	PHP	vsprintf(): Too few arguments at /var/www/html/nextcloud/lib/private/L10N/L10NString.php#79__ 
----
Environment: centos 7.5, php71, nc13.02., mysql Ver 15.1 Distrib 5.5.56-MariaDB

**Comment by Githopp192** [comment]
But you can see .. i still getting the error and the entries into the nextcloud.log

**Comment by schnello** [comment]
Same issue with NC14

**Comment by lowlyocean** [comment]
I am seeing this issue

**Comment by oraclesod** [comment]
Is there any update on this ? Im also seeing this issue

**Comment by kesselb** [comment]
Anything in nextcloud.log?

**Comment by oraclesod** [comment]
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:43:06-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:43:06-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:43:06-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:43:06-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:43:04-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:43:04-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:43:04-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:43:04-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:57-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:57-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:57-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:57-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:54-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:54-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:54-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:54-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:48-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:48-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:48-0800
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69 | 2019-03-04T10:42:47-0800
Error | PHP | Method OC\L10N\L10NString::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#88 | 2019-03-04T10:11:46-0800
Error | PHP | vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/L10N/L10NString.php#79 | 2019-03-04T10:11:45-0800
Error | PHP | Method OC\L10N\L10NString::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#88 | 2019-03-04T10:11:35-0800
Error | PHP | vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/L10N/L10NString.php#79 | 2019-03-04T10:11:35-0800
Error | PHP | Method OC\L10N\L10NString::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#88 | 2019-03-04T10:11:33-0800
Error | PHP | vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/L10N/L10NString.php#79 | 2019-03-04T10:11:33-0800

**Comment by ChristophWurst** [comment]
Sounds like a client-side issue of the app. For some reason the template is not rendered. Maybe it's the CSP. In any case this is nothing the server could fix, hence I'm closing this.

**Comment by oraclesod** [comment]
How exactly did you come to that conclusion ? 

By client side do you mean browser or NextCloud plugin ?

This is happening across many machines (windows and OSX) and a number of browsers

**Comment by ChristophWurst** [comment]
Because that syntax looks like an AngularJS expression. And issue title literarily says it's from the passman app.

Client-side I mean the browser application. It doesn't matter much on which browser you view the page if it's broken.
