### ISSUE TITLE
FTPS cert check trys to match solved DNS (IP) against name in cert

### ISSUE THREAD

**Issue by xEBIx** [nextcloud/server#8417]
Steps to reproduce

Add external FTPS storage with TLS/SSL

Expected behaviour
External FTP storage should connect with TLS/SSL

Actual behaviour
Nextcloud cannot connect to FTPS 

Server configuration
Dockerrized Setup / one Container per Service
PHPFPM 7.1.13, with apcu active
Apache 2.4.x
Redis 
Postgresql

Operating system:
Gentoo Linux

PHP version:
7.1.13

Nextcloud version: (see Nextcloud admin page)
13.0.0

Updated from an older Nextcloud/ownCloud or fresh install:
Fresh install

Where did you install Nextcloud from:
Nextcloud Download site

Are you using external storage, if yes which one: local/smb/sftp/...
I would like to...
Are you using encryption: yes/no
No
Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
No

Operating system:
 Linux 4.12.12-gentoo #3 SMP x86_64 Intel(R) GNU/Linux

Log: 
opendir(): Peer certificate CN=`*.livedrive.com' did not match expected CN=`185.21.109.18' at /var/www/htdocs/apps/files_external/lib/Lib/Storage/StreamWrapper.php#66

**Comment by MorrisJobke** [comment]
cc @icewind1991
