### ISSUE TITLE
Impossible to upgrade the 13.0.0 version

### ISSUE THREAD

**Issue by ValeTzara** [nextcloud/server#8419]
### Steps to reproduce
1. I have downloaded and executed the Nextcloud VM from [https://www.techandme.se/nextcloud-vm/](url)
2. I have connected to Nextcloud
3. The upgrade script of the 13.0.0 version started
Aggiornamento dell'applicazione richiesto
Queste applicazioni saranno aggiornate:
Activity (activity)
Calendar (calendar)
Comments (comments)
Contacts (contacts)
WebDAV (dav)
Federated file sharing (federatedfilesharing)
Federation (federation)
Files (files)
PDF viewer (files_pdfviewer)
File sharing (files_sharing)
Text editor (files_texteditor)
Deleted files (files_trashbin)
Versions (files_versions)
Video player (files_videoplayer)
First run wizard (firstrunwizard)
Gallery (gallery)
Lookup Server Connector (lookup_server_connector)
Nextcloud announcements (nextcloud_announcements)
Notifications (notifications)
OAuth 2.0 (oauth2)
Password policy (password_policy)
Preview Generator (previewgenerator)
Provisioning API (provisioning_api)
Monitoring (serverinfo)
Share by mail (sharebymail)
Usage survey (survey_client)
Collaborative tags (systemtags)
Theming (theming)
Two factor backup codes (twofactor_backupcodes)
Update notification (updatenotification)
Files workflow engine (workflowengine)

4. I click on the upgrade button

### Expected behaviour
Nextcloud should upgrade the 13.0.0 version

### Actual behaviour
The following error occurs:
_Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'oc_cards_properties' AND TABLE_SCHEMA = 'nextcloud_db'': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away_

### Server configuration

**Operating system:** Ubuntu 16.04 LTS

**Web server:** Server web Apache 2.4.18

**Database:** MySQL server 10.2.13

**PHP version:** 7.0.25

**Nextcloud version:** 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ValeTzara** [comment]
I'm beginner of nextcloud and principiant of linux and ubuntu. Please... help me!!!

**Comment by JPLiggett** [comment]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table` FROM INFORMATION_SCHEMA . COLUMNS WHERE TABLE_SCHEMA = ? AND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME <> 'utf8') AND TABLE_NAME LIKE "oc_%"' with params ["pcnyvf5_cloud2"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by JPLiggett** [comment]
on another site - approx same issue - lost conection to MySQL

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "{\"core\":{\"EXTRA_FILE\":{\"phpinfo.php\":{\"expected\":\"\",\"current\":\"99cef6a844150c8ec793f4bf1e880513b9117b860cb95cb28a51dd28f7580457c7137d08bb14f579a8e9bd9e5d741028fb47315bd4a3be8d2eb796f206d9220c\"},\"xLoad\\\/Pcvfa_BOD_20171121_Audio.m4a\":{\"expected\":\"\",\"current\":\"03720c13188acd16ad7419a9024f38f11511a4c24ae2085bb5fcb73f58cd7477641aeb2266f44fb7dda10c01c4497e0f9538118cfc9d15db890e42d1b6a517e8\"},\"php.ini\":{\"expected\":\"\",\"current\":\"e18e769d8fee87b665a7baec76dfb1964cd6a49000f4f54c655d9a3fc73d13e87633df535c4ab9f20fe9d79627cb4b5cb5101f4225daeeee7e801596cc093d02\"}}}}", "core", "oc.integritycheck.checker"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by JPLiggett** [comment]
The autoupdater ran again and finished successfully on one site, the other site received a fresh overwrite and is working on v13

**Comment by MorrisJobke** [comment]
This looks like the Mysql server went offline in the middle - not much we can do here - sorry :/

Also the comments looks like the issue is solved now, is this correct?

I will close the ticket now.
