### ISSUE TITLE
defaultapp configuration ignored on login

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#842]
With Nextcloud 10b1, a user isn't redirected to the defaultapp as configured, but to files. 

After a little digging I found that LoginController:tryLogin doesn't redirect to OC_Util::getDefaultPageUrl(), but to files.view.index.

**Comment by juliushaertl** [comment]
Thanks for your bug report. 

This has already been fixed in https://github.com/nextcloud/server/pull/598 and backported to stable10 in #599.
