### ISSUE TITLE
Unable to login on server v 13 using nextcloud android app

### ISSUE THREAD

**Issue by thdrmz** [nextcloud/server#8421]
Using Nextcloud Android App 3.0.1
or Nextcloud Android App dev 20180214

Nextcloud Server Version 13

All tries login failed, tries are counted on oc_bruteforce_attempts,

### Expected behaviour
App should show directory, like on older server version or when i use owncloud android client.

### Actual behaviour
All ways to login failed on  https://<my-server-name>

## Server configuration detail

**Operating system:** Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64

**Webserver:** nginx/1.13.8 (fpm-fcgi)

**Database:** mysql 10.1.26

**PHP version:** 7.0.27-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, geoip, gettext, gnupg, iconv, igbinary, imap, intl, json, ldap, exif, msgpack, mysqli, pdo_mysql, Phar, posix, readline, recode, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - admin_notifications: 1.0.1
 - apporder: 0.4.1
 - calendar: 1.6.0
 - comments: 1.3.0
 - contacts: 2.1.0
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_automatedtagging: 1.3.0
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.2.0
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - qownnotesapi: 17.5.0
 - quota_warning: 1.2.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - bruteforcesettings
 - checksum
 - encryption
 - files_external
 - gpxedit
 - ownpad
 - richdocuments
 - tasks
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.drillich.net",
        "cloud.ttipvs.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.0.14",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "forcessl": true,
    "theme": "",
    "maintenance": false,
    "loglevel": 3,
    "logfile": "\/var\/log\/nextcloud.log",
    "log_type": "syslog",
    "syslog_tag": "NextCloud",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "trashbin_retention_obligation": "auto, 14",
    "updatechecker": false,
    "overwrite.cli.url": "https:\/\/cloud.drillich.net",
    "mail_smtpauthtype": "PLAIN"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by MorrisJobke** [comment]
cc @tobiasKaminsky @AndyScherzinger Do you have some ideas on this one?

**Comment by thdrmz** [comment]
Not really, I'm using currently the owncloud app to sync files on android. I guess its a problem somewhere in the login procedure, but I don't know how to locate the core of the problem.

**Comment by AndyScherzinger** [comment]
We are currently releasing 3.0.2 which ships login fixes, so that might fix the issue.

**Comment by MorrisJobke** [comment]
> We are currently releasing 3.0.2 which ships login fixes, so that might fix the issue.

Let's close it then. Please give the Android 3.0.2 app a try.

**Comment by tobiasKaminsky** [comment]
@thdrmz if this still happens on 3.0.2 please open up a new issue on android repo:
https://github.com/nextcloud/android/
