### ISSUE TITLE
Check wrong nginx config

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#8422]
Ref: https://github.com/nextcloud/android/issues/2152

Somehow the nginx server was misconfigured, leading to android app not working reliable, this fixes it:

> Especially those lines should be removed: nextcloud/documentation/pull/392/files

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/issues/2152#issuecomment-365916319:

> Doing a HEAD on a non-existing file, should give this:
```
 curl -u "tobi:tobi" http://localhost/nc/remote.php/webdav/12312313123.pdf                                                                                                                       
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name 12312313123.pdf could not be located</s:message>
</d:error>
```

> But for this server I get a real html page, saying the file cannot be found.

**Comment by tobiasKaminsky** [comment]
This was mentioned in original android issue:

> As far as I could trace it from my backups this must come from some very old owncloud setup.
Have checked - at least owncloud 8.0 recommends to have the 403 and 404 lines in the nginx config

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/issues/2510#issuecomment-384058216

a check if header is in one line would be nice.
I remember that we had lots of them already...
(or is this a bug on client side?)

**Comment by MorrisJobke** [comment]
AFAIK we do this in the meantime. It's the check for the header that is referred by @tobiasKaminsky. Thus closing.
