### ISSUE TITLE
thunderbird/lightning not sending calendar notifications

### ISSUE THREAD

**Issue by zyro23** [nextcloud/server#8423]
### Steps to reproduce
1. disable caldav server-side email sending in the admin ui (new option added with 13.0)
2. use thunderbird/lightning to create an appointment and add a participant
3. in the participants tab, the "notify participants" checkbox is greyed out and no notification is sent

### Expected behaviour
checkbox should be enabled and if checked (default), thunderbird/lighnting should ask if i want to send the notification after saving the appointment.

### Actual behaviour
checkbox disabled and thunderbird/lighnting does not ask if i want to send a notification and no notification is sent.

### Server configuration

nextcloud-13.0.0 docker image

### Workaround

i was able to make this work again by commenting out the schedule plugin manually, but @georgehrke mentioned this may lead to undesired side effects, see. https://github.com/nextcloud/server/commit/b958725f78ade3f116001ee6dd66432bffa41748#r27649001

**Comment by myset** [comment]
I can't send invites or cancellation notifications with remote clients (Thunderbird, Google Calendar) to.

My setup is NC 13.0.0 stable channel.

I propose you to introduce per calendar this option between server based invites and remote client based invites or cancellation  notifications.

**Comment by myset** [comment]
**Enhancement proposal**

I propose you to introduce per-calendar option (checkbox) for remote client based invites or cancellation notifications (Ex. External client notification).

**Comment by georgehrke** [comment]
@myset That won't be possible. The property that tells thunderbird that the server sends out emails (or not) is valid for the entire CalDAV server and not applicable to individual calendars.

**Comment by myset** [comment]
Considering this behavior, It is possible to create an instance of CalDAV at the level of calendar to be applicable at the level of calendar ?

**Comment by dugite-code** [comment]
In a recent update I had to comment out `$this->server->addPlugin(new \OCA\DAV\CalDAV\Schedule\Plugin());` in `/var/www/nextcloud/apps/dav/lib/Server.php` as well in order to allow thunderbird to send invites

**Comment by myset** [comment]
Doesn't work for me with Thunderbird 52.8. No invites emails are sent.

**Comment by myset** [comment]
Yes. It works with unsubscribe and re-subscribe in Thunderbird.
Thank you.

**Comment by myset** [comment]
I propose you to introduce an option (checkbox) at the level of servers settings (Ex. External client notification) in order to maintain /var/www/nextcloud/apps/dav/lib/Server.php "commented line behavior" across NexcloudServer updates.

**Comment by MorrisJobke** [comment]
@georgehrke Haven't you worked on this recently?

**Comment by georgehrke** [comment]
It seems like Thunderbird sometimes checks if the schedule plugin is enabled. 
So I guess we should change the option from `disable email sending` to `disable any server side scheduling`, but we also have to properly communicate the consequences like no Free/Busy, etc.

**Comment by MorrisJobke** [comment]
@georgehrke I moved it out of 14.

**Comment by myset** [comment]
On NC 14.0.1 it work as expected (without commenting calendar scheduler line in apps/dav/lib/Server.php) and using client side option for scheduling or not emails.
Eg. Thunderbird caldav with "Prefer client-side email scheduling"

Thank you for your great work.

**Comment by georgehrke** [comment]
See https://github.com/nextcloud/server/issues/2800#issuecomment-531480243
