### ISSUE TITLE
Allow apps to opt-out of any shipped javascript libraries

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#8425]
From https://github.com/nextcloud/server/issues/7738 

> My idea here was to maybe provide a set of building blocks, that are not shipped within Nextcloud itself, but within the app via NPM/yarn/whatever modules, that the app itself need to ship.
> Should we make this a breaking change or require apps to opt-in by using a special info.xml flag like <ships-core-assets />?
> EDIT: we could also make the transition slowly by:
> 
> opt-in using <ships-core-assets /> in Nextcloud 14
> opt-out using <requires-core-assets /> in Nextcloud 15
> have a breaking change with Nextcloud 16

Those are the components we should try to migrate away from jQuery, so we don't have a dependency on that for normal app pages (feel free to add stuff I might have forgotten):

- [ ] App menu
- [x] Notifications (should already be fine since it is a webpack bundled app)
- [ ] Contacts menu
- [ ] Popover handling
- [ ] Search
- [ ] avatar plugin
- [ ] placeholder plugin
- [ ] heartbeat
- [ ] cron
- [ ] tooltips
- [ ] l10n (uses $.get)

@nextcloud/javascript

**Comment by georgehrke** [comment]
Alternatively we could also use https://api.jquery.com/jquery.noconflict/ 
So instead of abolishing jQuery completely from the server, we just don't advertise it as `window.$` or `window.jQuery`, but `window.serverJQuery` or similar.

**Comment by juliushaertl** [comment]
@georgehrke Oh that looks interesting, so we just need to adjust the code to use the serverJQuery version.

**Comment by skjnldsv** [comment]
Should we add there the to-be-created components as well?

**Comment by rullzer** [comment]
Some of those should maybe have their legacy (jquery) variant lying around for a few releases. Like the avatar and placeholder. Make sure their original is still their so it works for everybody.

Add some warnings or whatever to tell devs to move to the new stuff.

**Comment by juliushaertl** [comment]
Closing as we are slowly deprecating the shipped global libraries now and https://github.com/orgs/nextcloud/projects/31 provides a much better overview of what is still legacy js.
