### ISSUE TITLE
Suggestion : security : adding a log-in max duration and disabling multiple log-in

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#8427]
nextcloud 13
Windows 10 + chrome + firefox + opera + edge
Asus zen android 7.1.1 + chrome 
One plus 5 + chrome 

1- Once users are log-in like my admin account, there is no maximum time set to stay log-in and it can be set like this forever until connection machine is reboot.
2- Closing browser do not close log-in. Restart Chrome, go back to nextcloud and voila, you're log-in again.
3- Multiple parallel log-in allowed in same time.
machine 1 network 1 -->ok ( local net )
machine 2 network 1 -->ok ( local net )
machine 3 network 2 -->ok ( 4G net 1 )
machine 4 network 3 -->ok ( 4G net 2 )
Let's imagine you have a admin log-in from your smartphone browser ( or tablet ) and you loose/be stole it ... access will be granted unless stolen hardware is reboot or you change password. 
   
This is a severe security issue !
security should be fix on server side, not user side with cookie/cache deletion or whatsoever witch are easy fix, but impossible to manage for a 50+ users based with no physical access to all hardware used in networks ( around 140+ machines ).

**Comment by rullzer** [comment]
> 1- Once users are log-in like my admin account, there is no maximum time set to stay log-in and it can be set like this forever until connection machine is reboot.

Only if you leave the browser open. But after 30 minutes of your last auth you need to enter your password for a lot of actions agan.

> 2- Closing browser do not close log-in. Restart Chrome, go back to nextcloud and voila, you're log-in again.

Chrome has the habit of keeping running in the background. If you fully shut down chrome and did not tick the 'stay logged in' box you will be logged out.

> 3- Multiple parallel log-in allowed in same time.
machine 1 network 1 -->ok ( local net )
machine 2 network 1 -->ok ( local net )
machine 3 network 2 -->ok ( 4G net 1 )
machine 4 network 3 -->ok ( 4G net 2 )
Let's imagine you have a admin log-in from your smartphone browser ( or tablet ) and you loose/be stole it ... access will be granted unless stolen hardware is reboot or you change password.

You can kill sessions from the security tab in the settings.

**Comment by stratege1401** [comment]
> > 1- Once users are log-in like my admin account, there is no maximum time set to stay log-in and it can be set like this forever until connection machine is reboot.
> 
> Only if you leave the browser open. But after 30 minutes of your last auth you need to enter your password for a lot of actions agan.

Well, NOPE !!! I let my system tunning all night long, on w10 and android. None of them asked for any king of re-auth ( no password, no TOTP )
- W10 pro + chrome latest update
- Android 8.0 + firefox

> Chrome has the habit of keeping running in the background. If you fully shut down chrome and did not tick the 'stay logged in' box you will be logged out.
-tried. I was log-off from my google account, but not from n13

> You can kill sessions from the security tab in the settings.
HAPPY ME !!! I have so far 50+ users generating 140+ hardware connection from desktop, laptop, smartphones, tablettes.
For fun, just spend the last minute to "kill" connexion for fun. Approx 8s per connexions, witch are recreated a soon as the users reconnect.... 
Unfortunately, i have others works to do, like counting coffee beans for my boss expresso ( 86, no more no less ) and unroll the toilet paper for guest convenience ...

**Comment by rullzer** [comment]
> Well, NOPE !!! I let my system tunning all night long, on w10 and android. None of them asked for any king of re-auth ( no password, no TOTP )

It depends on the action. Try adding a new user. Or chaning your password.

> -tried. I was log-off from my google account, but not from n13

Are you sure you did not check the stay logged in button? I just tried it here and it works for me on 4 different browsers on 2 machines. So it seems your chrome then somehow remembers the sessions. Which is not something we can fix.

> HAPPY ME !!! I have so far 50+ users generating 140+ hardware connection from desktop, laptop, smartphones, tablettes.
For fun, just spend the last minute to "kill" connexion for fun. Approx 8s per connexions, witch are recreated a soon as the users reconnect....
Unfortunately, i have others works to do, like counting coffee beans for my boss expresso ( 86, no more no less ) and unroll the toilet paper for guest convenience ...

Your sarcasm isn't needed and won't make anybody look at your issue faster.

If you just use username and password. Well yes of course the session will just be regrated by the clients. Then either use app passwords (so you can still revoke them) or change the password. But I would assume you want to change the password anyway if the device is compromised and has the password stored.

**Comment by stratege1401** [comment]
It is not sarcasm. It s call humour. The strange action of opening our mouth and exalhing air with loud sound and having fun... Like ha ha ha

**Comment by MorrisJobke** [comment]
Is this really something we want to implement? I still don't see the full use case here. Maybe something like the remote wipe #3456 makes a lot more sense here.

cc @nextcloud/security @nickvergessen @karlitschek for opinions

**Comment by karlitschek** [comment]
I have my doubts to be honest. This mainly annoys users without any 'real' security benefit. IMHO
