### ISSUE TITLE
Username with space

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/server#8429]
### Steps to reproduce
1. Configure a new user with space on username es. marino faggiana
2.
3.

### Expected behaviour
Tell us what should happen

The UserdID : must be without space 

### Actual behaviour
Tell us what happens instead

The UserID is "marino faggiana"

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
What you propose is not a solution. You need to be able to handle userID's with spaces. Because we can't migrate old user ids.

What is the problem you are facing with userids with spaces?

**Comment by marinofaggiana** [comment]
<?xml version="1.0"?><d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:basicsearch><d:select><d:prop><d:getlastmodified /><d:getetag /><d:getcontenttype /><d:resourcetype/><d:getcontentlength /><oc:fileid/><oc:id/><oc:permissions /><oc:size /><oc:favorite/><nc:is-encrypted/></d:prop></d:select><d:from><d:scope><d:href>**/files/123%20456**</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:like><d:prop><d:displayname/></d:prop><d:literal>%Doc%</d:literal></d:like></d:where></d:basicsearch></d:searchrequest>

return Error ..

<?xml version="1.0"?><d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:basicsearch><d:select><d:prop><d:getlastmodified /><d:getetag /><d:getcontenttype /><d:resourcetype/><d:getcontentlength /><oc:fileid/><oc:id/><oc:permissions /><oc:size /><oc:favorite/><nc:is-encrypted/></d:prop></d:select><d:from><d:scope><d:href>/files/123 456</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:like><d:prop><d:displayname/></d:prop><d:literal>%Doc%</d:literal></d:like></d:where></d:basicsearch></d:searchrequest>

return No files found ..

**Comment by marinofaggiana** [comment]
`<?xml version="1.0"?><d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:basicsearch><d:select><d:prop><d:getlastmodified /><d:getetag /><d:getcontenttype /><d:resourcetype/><d:getcontentlength /><oc:fileid/><oc:id/><oc:permissions /><oc:size /><oc:favorite/><nc:is-encrypted/></d:prop></d:select><d:from><d:scope><d:href>/files/123%20456</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:like><d:prop><d:displayname/></d:prop><d:literal>%Doc%</d:literal></d:like></d:where></d:basicsearch></d:searchrequest>`

return error

`<?xml version="1.0"?><d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:basicsearch><d:select><d:prop><d:getlastmodified /><d:getetag /><d:getcontenttype /><d:resourcetype/><d:getcontentlength /><oc:fileid/><oc:id/><oc:permissions /><oc:size /><oc:favorite/><nc:is-encrypted/></d:prop></d:select><d:from><d:scope><d:href>/files/123 456</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:like><d:prop><d:displayname/></d:prop><d:literal>%Doc%</d:literal></d:like></d:where></d:basicsearch></d:searchrequest>`

return file not found

**Comment by rullzer** [comment]
Ok I'll look into it

**Comment by rullzer** [comment]
Your second example works just fine on master. I'll try stable13 tomorrow.

**Comment by rullzer** [comment]
It returns records just fine here.

**Comment by rullzer** [comment]
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/files/123%20456/doc/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Tue, 20 Feb 2018 20:51:20 GMT</d:getlastmodified>
        <d:getetag>"5a8c8a4874555"</d:getetag>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <oc:fileid>110</oc:fileid>
        <oc:id>00000110oc02qh89cd7d</oc:id>
        <oc:permissions>RGDNVCK</oc:permissions>
        <oc:size>0</oc:size>
        <oc:favorite>0</oc:favorite>
        <nc:is-encrypted>0</nc:is-encrypted>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <d:getcontenttype/>
        <d:getcontentlength/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/files/123%20456/a%20Doc%20A/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Tue, 20 Feb 2018 20:51:25 GMT</d:getlastmodified>
        <d:getetag>"5a8c8a4d0895a"</d:getetag>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <oc:fileid>111</oc:fileid>
        <oc:id>00000111oc02qh89cd7d</oc:id>
        <oc:permissions>RGDNVCK</oc:permissions>
        <oc:size>0</oc:size>
        <oc:favorite>0</oc:favorite>
        <nc:is-encrypted>0</nc:is-encrypted>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      <d:prop>
        <d:getcontenttype/>
        <d:getcontentlength/>
      </d:prop>
      <d:status>HTTP/1.1 404 Not Found</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

**Comment by marinofaggiana** [comment]
ok @rullzer, I have found the issue on old driver ownCloud (iOS). thanks !
