### ISSUE TITLE
nextcloud login not possbile/ webinterface stuck after rollback

### ISSUE THREAD

**Issue by oneiros66** [nextcloud/server#8434]
Hi,

I tried to update nextcloud to version 13, which failed because of keylength-problems - nothing new and no big deal. 
I updated my mysql server to prevent this issue in future.
I rolled my installation back (put old database, files in place) and rearranged the database mimetypes and updated the filecache via: 
maintenance:mimetype:update-db 
I also tried to repair the installation via maintenance:repair. 

The deal is, that systems with cookies + cache in browser from visiting nextcloud before, it's actually woking fine and also the windows client connects. 

All other systems/browser can't even login (login button does nothing) or the interface gets stucked right at home (Screenshot: https://i.imgur.com/Z1bK5Ts.png)

Nextcloud is running on Debian 9.1, mysql/mariadb 10.1.26, apache 2.4.25, php 7.1

I turned off redis / apcu and filelocking just to assure, the problem isn't located there.

Cause to the fact it's working with windows app and on the systems with the old cache / cookies, I doubt, it's not the biggest problem with the installation itself - still got no idea, how to solve this...

Thanks for your help!

**Comment by MorrisJobke** [comment]
> I rolled my installation back (put old database, files in place) and rearranged the database mimetypes and updated the filecache via:
> maintenance:mimetype:update-db
> I also tried to repair the installation via maintenance:repair.

That is not how you restore a backup. You need to put in the old code, old database dump and the old filesystem structure to do so. We have a guide how to properly roll back to a old state: https://docs.nextcloud.com/server/13/admin_manual/maintenance/restore.html - the "maintenance:data-fingerprint" is a crucial part for the apps to get noticed about the rollback.
