### ISSUE TITLE
Exception while scanning AND occ files:scan doesn't fix it

### ISSUE THREAD

**Issue by Yeru-314** [nextcloud/server#8437]
Hi all!
Long time ago, I got a federated share, named "Video Elbbrücken". Kind of like [#3763](https://github.com/nextcloud/server/issues/3763) and [#3766](https://github.com/nextcloud/server/issues/3766) - except: `occ files:scan` doesn't fix it.

### Steps to reproduce
just an **idea**: get a federated share. Then move the federated instance to another domain.

### Expected behaviour
Synchro should yield no errors when synchronising federated files.
`occ files:scan` should detect orphaned files and remove them.

### Actual behaviour
Desktop Client yields "Video Elbbrücken, nextCloud,Error downloading https://cloud.poeltls-kuehlschrank.de/remote.php/dav/files/Dominik/Video Elbbrücken - server replied: Service Unavailable
"

`occ files:scan` yields "Exception during scan: cURL error 51: SSL: no alternative certificate subject name matches target host name 'vkhh.my-wan.de'"
vkhh.my-wan.de is the federated instance.
Here's the whole log from 'occ files:scan'
<details>
Starting scan for user 1 out of 1 (Dominik)
Exception during scan: cURL error 51: SSL: no alternative certificate subject name matches target host name 'vkhh.my-wan.de'
#0 /var/www/virtual/yeru/html/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(104): GuzzleHttp\Exception\RequestException::wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
#1 /var/www/virtual/yeru/html/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#2 /var/www/virtual/yeru/html/owncloud/3rdparty/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
#3 /var/www/virtual/yeru/html/owncloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#4 /var/www/virtual/yeru/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#5 /var/www/virtual/yeru/html/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(135): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
#6 /var/www/virtual/yeru/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
#7 /var/www/virtual/yeru/html/owncloud/3rdparty/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
#8 /var/www/virtual/yeru/html/owncloud/lib/private/Http/Client/Client.php(138): GuzzleHttp\Client->get('https://vkhh.my...', Array)
#9 /var/www/virtual/yeru/html/owncloud/apps/files_sharing/lib/External/Storage.php(272): OC\Http\Client\Client->get('https://vkhh.my...', Array)
#10 /var/www/virtual/yeru/html/owncloud/apps/files_sharing/lib/External/Storage.php(292): OCA\Files_Sharing\External\Storage->testRemoteUrl('https://vkhh.my...')
#11 [internal function]: OCA\Files_Sharing\External\Storage->remoteIsOwnCloud()
#12 /var/www/virtual/yeru/html/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(501): call_user_func_array(Array, Array)
#13 [internal function]: OC\Files\Storage\Wrapper\Wrapper->__call('remoteIsOwnClou...', Array)
#14 [internal function]: OC\Files\Storage\Wrapper\Availability->remoteIsOwnCloud()
#15 /var/www/virtual/yeru/html/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(501): call_user_func_array(Array, Array)
#16 /var/www/virtual/yeru/html/owncloud/apps/files_sharing/lib/External/Scanner.php(40): OC\Files\Storage\Wrapper\Wrapper->__call('remoteIsOwnClou...', Array)
#17 /var/www/virtual/yeru/html/owncloud/apps/files_sharing/lib/External/Scanner.php(40): OCA\Files_Trashbin\Storage->remoteIsOwnCloud()
#18 /var/www/virtual/yeru/html/owncloud/lib/private/Files/Utils/Scanner.php(242): OCA\Files_Sharing\External\Scanner->scan('', true, 3)
#19 /var/www/virtual/yeru/html/owncloud/apps/files/lib/Command/Scan.php(161): OC\Files\Utils\Scanner->scan('/Dominik')
#20 /var/www/virtual/yeru/html/owncloud/apps/files/lib/Command/Scan.php(234): OCA\Files\Command\Scan->scanFiles('Dominik', '/Dominik', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false)
#21 /var/www/virtual/yeru/html/owncloud/3rdparty/symfony/console/Command/Command.php(256): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/virtual/yeru/html/owncloud/core/Command/Base.php(161): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/virtual/yeru/html/owncloud/3rdparty/symfony/console/Application.php(818): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/virtual/yeru/html/owncloud/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/virtual/yeru/html/owncloud/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/virtual/yeru/html/owncloud/lib/private/Console/Application.php(170): Symfony\Component\Console\Application->run(NULL, NULL)
#27 /var/www/virtual/yeru/html/owncloud/console.php(100): OC\Console\Application->run()
#28 /var/www/virtual/yeru/html/owncloud/occ(11): require_once('/var/www/virtua...')
#29 {main}

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 213     | 2236  | 00:00:17     |
+---------+-------+--------------+
</details>

### Server configuration
regarding  **Operating system**, **Web server:**, **Database:**: I use [Uberspace](https://wiki.uberspace.de/) <- link to their (German) wiki.

**PHP version:** php-5.6.32

**Nextcloud version:** 13.0

**Updated from an older Nextcloud/ownCloud or fresh install:** OC 9.x -> ... -> OC 10.0.4 -> NC 12.

**Where did you install Nextcloud from:** via setup-owncloud.php and then the migration/updater index.php

**Signing status:**
<details>
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- templateeditor
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- theme-example
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- market
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [templateeditor] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

    [theme-example] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

    [market] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)
</details>

**List of activated apps:**
<details>
-  federatedfilesharing: 1.3.1
-  federation: 1.3.0
-  files: 1.8.0
-  files_external: 1.4.1
-  files_pdfviewer: 1.2.0
-  files_sharing: 1.5.0
-  files_texteditor: 2.5.1
-  files_trashbin: 1.3.0
-  files_versions: 1.6.0
-  files_videoplayer: 1.2.0
-  firstrunwizard: 2.2.1
-  logreader: 2.0.0
-  lookup_server_connector: 1.1.0
-  nextcloud_announcements: 1.2.0
-  notifications: 2.1.2
-  oauth2: 1.1.0
-  password_policy: 1.3.0
-  provisioning_api: 1.3.0
-  serverinfo: 1.3.0
-  workflowengine: 1.3.0
</details>

**Nextcloud configuration:**
<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "yeru.nunki.uberspace.de",
            "www.yeru.nunki.uberspace.de",
            "www.poeltls-kuehlschrank.de",
            "www.poeltls-kuehlschrank.de\/owncloud",
            "www.owncloud.poeltls-kuehlschrank.de",
            "cloud.poeltls-kuehlschrank.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/yeru.nunki.uberspace.de\/owncloud",
        "dbtype": "sqlite3",
        "version": "13.0.0.14",
        "logtimezone": "UTC",
        "installed": true,
        "overwriteprotocol": "https",
        "overwritereboot": "\/cloud.poeltls-kuehlschrank.de",
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** none
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** Webdav, only for Desktop Clients and CalDAV access

#### LDAP configuration (delete this part if not used)
<details>
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.
</details>

#### Nextcloud log (data/nextcloud.log)
only the part concerning the federated file.
<details>
{"reqId":"fmmRvmjaD73zSlIgzTw8","level":4,"time":"2018-02-03T11:32:49+00:00","remoteAddr":"195.202.50.125","user":"Dominik","app":"webdav","method":"GET","url":"\/remote.php\/dav\/files\/Dominik\/Video%20Elbbr%C3%BCcken","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChild('Video Elbbr\\\\xC3\\\\xBCck...')\\n#1 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(621): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/Dominik\\\/V...')\\n#2 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(196): Sabre\\\\DAVACL\\\\Plugin->getCurrentUserPrivilegeSet('files\\\/Dominik\\\/V...')\\n#3 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/DavAclPlugin.php(46): Sabre\\\\DAVACL\\\\Plugin->checkPrivileges('files\\\/Dominik\\\/V...', '{DAV:}read', 1, false)\\n#4 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(889): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\DavAclPlugin->checkPrivileges('files\\\/Dominik\\\/V...', '{DAV:}read')\\n#5 [internal function]: Sabre\\\\DAVACL\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#8 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/virtua...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/yeru\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":216}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"12.0.4.3"}
</details>

**Comment by blizzz** [comment]
was the scan aborted or did it run until the end? If SSL errors are found, it' correct that they are reported instead of deleting anything arbitrarily.

**Comment by Yeru-314** [comment]
Hey blizzz, thx for taking a look.
I included the whole output of `files:scan` under **Actual behaviour**.

Long story short: scan ends with prompting the table listing folders, files and elapsed time.
```
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
|   213   | 2236  |   00:00:17   |
+---------+-------+--------------+
```

**Comment by blizzz** [comment]
Then it works as it should. Would be sad to remove a share just because your pal forgot to extend the SSL cert, for instance. Scanning continues to run fine further on, as I interpret it. → closing
