### ISSUE TITLE
Instant Upload Icon on the Server Version

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/server#8438]
Hi,

If you choose a folder for instant upload on the mobile apps, the folder icon changes in this way* so you can easily notice it in many files on the phone.

This may be working in the local database in iOS version but nice idea.
Can we see this icon in the server version?

![icon*](https://user-images.githubusercontent.com/297968/36394035-02515434-15bb-11e8-9f03-565a12d3afad.png)

**Comment by MorrisJobke** [comment]
> Can we see this icon in the server version?

We don't know of this concept on the server. There could also be multiple apps that do instant upload to different folders.

Nevertheless I would like this. cc @nextcloud/designers for feedback on this.

**Comment by MorrisJobke** [comment]
Technically I would solve this by attributes that can be set via WebDAV and only need to be send by the mobile apps accordingly.

**Comment by juliushaertl** [comment]
Maybe we can make this a bit more generic, so that for example the groupfolders/external storage folders can also be shown like that in the clients. GVFS for example just uses a icon attribute that can be set, we could add something similar to the WebDAV interface:

```
$ gvfs-info ~/Pictures 
...
  standard::icon: folder-pictures, folder
```

**Comment by jancborchardt** [comment]
Seems good to me. We already have special icons for shared folders, so we could do this with folders named "Pictures" (or attributes mentioned before) as well.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
