### ISSUE TITLE
Allow deep file structures with more than 255 chars overall length

### ISSUE THREAD

**Issue by Koffeinfriedhof** [nextcloud/server#8439]
### Steps to reproduce
1. Create a deep folder structure with more than 255 chars on an ext4-device (via terminal or whatever you want to use)
2. Sync this structure with the desktop-client on a target system
3. Get error message that filenames are too long

### Expected behaviour
nextcloud should accept the length of 255 chars per file/folder and not reduce it to its combined length.

### Actual behaviour
Throwing error message that files/folders could not be synchronized due to its length

### Server configuration

**Operating system**:
Ubuntu 16.04 Server
**Web server:**
Apache2
**Database:**
MySQL
mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper
**PHP version:**
PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )
**Nextcloud version:** (see Nextcloud admin page)
13 (13.0.0.14)
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from last 12.X
**Where did you install Nextcloud from:**
git cloned 12.1
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```Enabled:
  - activity: 2.6.1
  - apporder: 0.4.1
  - audioplayer: 2.2.5
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - checksum: 0.3.5
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.1.0
  - dav: 1.4.6
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_reader: 1.2.2
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mood: 0.3.3
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ojsxc: 3.3.2
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dms.ck",
            "192.168.16.50",
         ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/dms.ck\/nextcloud",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "updater.release.channel": "beta",
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 2592000
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no (I'm using sshfs in general, but not for the nextcloud-instance)
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Qupzilla, Chromium, QuteBrowser
**Operating system:**
arch linux / Kubuntu 18.04

The server-logs do not contain any information about the sync-client (just a few login failures). The client-log (nextcloud desktop sync client) only says: filename too long

**Comment by KB7777** [comment]
@Koffeinfriedhof Is it Windows client? If yes see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by Koffeinfriedhof** [comment]
No, Clients were Arch and Kubuntu. Seems to be fixed anyway, there are no more error messages showing up since Nextcloud 13, I think.

**Comment by blizzz** [comment]
>  Seems to be fixed anyway

thx for the feeback → closing
