### ISSUE TITLE
OwnCloud 9.1.7 migration 

### ISSUE THREAD

**Issue by elmussol** [nextcloud/server#8441]
Using the migrate tool downloaded from https://download.nextcloud.com/server/installer/migrator/index.php and following instructions in https://nextcloud.com/migration/ I tried to migrate my up-to-date ownCloud 9.1.7 to Nextcloud 10.0.x.

On running the migrate tool I get the following:

Initializing
Current version is 9.1.7.
Could not determine migration path to Nextcloud.

I expected to be able to migrate to 10.0.6.

I have (unsuccessfully) asked for guidance at https://help.nextcloud.com/t/owncloud-9-1-7-migration-fail/27723 and said the following there:

"Is this because the latest in this series is NC 10.0.6 (August 7 2017) and 10.0.7 is pending (or possibly not coming)? It seems others have had success with manually editing version numbers in the config.php for migrating from OC 9.1.6, but I am a bit wary having not seen any reports with OC 9.1.7."

I am happy to provide any details required.

**Comment by stratege1401** [comment]
well , maybe it is time to backup and fresh install nc13

**Comment by sdellenb** [comment]
Since nothing else worked and I had a **backup**, I did this:
1. Hack config.php from version `9.1.7.2` to `9.1.6.0`
1. Migrate to nextcloud 10.0.6
1. Upgrade to nextcloud 11.0.7
1. Upgrade to nextcloud 12.0.5
1. Upgrade to nextcloud 13.0.0
1. Backup config dir, clean install of nextcloud 13.0.0

I haven't encountered any issues at all, my ownCloud installation was pretty vanilla.

**Comment by elmussol** [comment]
Thank you for your reply. I didn't do the config hacking, but went for a clean install of 13 instead. Very nice too.

**Comment by MorrisJobke** [comment]
> Thank you for your reply. I didn't do the config hacking, but went for a clean install of 13 instead. Very nice too.

Okay - what @sdellenb should work as well.

Good that you managed to migrate successfully and sorry for the issues :/
