### ISSUE TITLE
MariaDB as packaged by Ubuntu does not prompt for a password on install

### ISSUE THREAD

**Issue by devosb** [nextcloud/server#8442]
### Steps to reproduce
1. On Ubuntu 16.04 desktop (The manual mention server, I would not have thought that would make a difference)
2. apt-get install apache2 mariadb-server libapache2-mod-php7.0 (taken from https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#example-installation-on-ubuntu-16-04-lts-server Yes, I know this is the older version, but it is what I followed before v13 came out, and the v13 docs seem to have the same text).
3. MariaDB does not prompt to create a root password on install.

### Expected behaviour
The MariaDB package would prompt the user to create a root password. Since there is no prompt, the user does not have a database password to give to the Installation Wizard

### Actual behaviour
The Installation Wizard cannot run, as it does not have a password to the database engine.

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS x86_64

**Web server:** Apache2 version 2.4.18-2ubuntu3.5 (from dpkg -l)

**Database:** MariaDB as packaged by Ubuntu, version 10.0.33-0ubuntu0.16.04.1 (from dpkg -l)

**PHP version:** 7.0.25-0ubuntu0.16.04.1

**Nextcloud version:** (see Nextcloud admin page) 12

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Compressed tarball and a manual install

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Default list of apps plus contacts and calendar.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'foo',
  'passwordsalt' => 'bar',
  'secret' => 'qux',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'example.com',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'https://example.com/nextcloud',
  'htaccess.RewriteBase' => '/nextcloud',
  'dbtype' => 'mysql',
  'version' => '12.0.5.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_quux',
  'dbpassword' => 'foobar',
  'installed' => true,
);
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Google Chrome 64.0.3282.167

**Operating system:** Ubuntu 16.04.3 LTS x86_64

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Requested logs are too old.
```
</details>

### Work around
To overcome the lack of a root password to the database engine I ran
`sudo mysql_secure_installation`
which is mentioned at https://mariadb.com/kb/en/library/mysql_secure_installation/

I then ran
`sudo mysql -u root`
and entered the following SQL statements (this is my first time writing SQL, so corrections are most welcome)
```
CREATE USER 'root2'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'root2'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
```
This was mentioned at https://ubuntuforums.org/showthread.php?t=2275033

Learning from from  and modifying the SQL found at https://docs.nextcloud.com/server/12/admin_manual/configuration_database/linux_database_configuration.html for MariaDB maybe the `GRANT` line above should have been
```
GRANT ALL PRIVILEGES ON *.* TO 'root2'@'localhost' IDENTIFIED BY 'password';
```

I needed to create the `root2` user, even though I had set the password for the `root` user as Ubuntu has configured MariaDB with an additional authentication method (`auth_socket.so`) and when running
`sudo systemctl status mysql`
there is a warning message that says
```
[Warning] 'user' entry 'root@localhost' has both a password and an authentication plugin specified. The password will be ignored.
```

This difference is described at https://mariadb.com/kb/en/library/differences-in-mariadb-in-debian-and-ubuntu/ This page also mentions that `utf8mb4` is configured by Ubuntu. So I am not sure if that would affect the backup and restore procedures for Nextcloud.

**Comment by blizzz** [comment]
Well, this is how the MariaDB install works now on Ubuntu, that's nothing we can influence in the Nextcloud server. → Closing. Check some Ubuntu-related sources, e.g. https://askubuntu.com/questions/798181/not-prompted-to-input-the-root-password-when-installing-mariadb-server-on-ubuntu

**Comment by devosb** [comment]
Even if there is no code change in Nextcloud, I would have thought an update to the Nextcloud installation instructions could be done. I suspect, but have not checked that MariaDB, as packaged by the MariaDB project, on Ubuntu would be fine. The issue comes up with MariaDB, as packaged by Debian/Ubuntu, on Ubuntu, has the issue I mention.

**Comment by blizzz** [comment]
The documentation repo is here: https://github.com/nextcloud/documentation/ you can file an issue there or directly improve the instructions :)
