### ISSUE TITLE
Request: allow comments on one time passwords under Personal Settings

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#8443]
There is currently no way for users to leave comments about one time passwords they've generated within Personal Settings/Security.  It would be useful if we could leave comments on our one time passwords, but an optional description field (ideally available upon creation) could also work.

![7d9dda27-5997-40b6-9ce1-323125b360e7](https://user-images.githubusercontent.com/1787238/36402686-2084cfa6-1595-11e8-8420-c35d7f81faf7.png)

**Comment by farrahD** [comment]
Can I try to work on this issue?

**Comment by farrahD** [comment]
I am pretty new at this. Could I be pointed in the direction of the file and folder I would be looking in to work on this?

**Comment by liamdennehy** [comment]
I've worked on backend changes to the model and controller, and related unit tests. Comments are stored as varchar(250), with truncation at the setter and tests confirm truncation has occurred.
Wanting a good random string to test I used code from StackOverflow with attribution.
[Issue 8443 Backend](/liamdennehy/nextcloud-server/tree/8443/tokencomment)
Shall I PR now or wait for 14 release to finish?

Implemented db changes by hand since I can't find any documentation on a migration generator.

**Comment by juliushaertl** [comment]
From my POV the app name field should already be fine for that, we should just make sure that the text is editable so additional information can be added for tokens that are added there using the flow auth. cc @nextcloud/desigers

**Comment by liamdennehy** [comment]
Some environments (especially in large organisations) could benefit from being able to add metadata to entries, e.g. documentation, designs, change requests, security waivers etc. I don't think we want to clutter the UI with an overly-large "name" field, though I have only worked on the back-end. This does feel like we should have a more generic metadata/comment/description approach for lots of different Entity types.

**Comment by liamdennehy** [comment]
PR #10075

**Comment by liamdennehy** [comment]
PR #10075

**Comment by violoncelloch** [comment]
> From my POV the app name field should already be fine for that, we should just make sure that the text is editable so additional information can be added for tokens that are added there using the flow auth. cc @nextcloud/designers

@juliushaertl should we close this then in favour of #6717

**Comment by juliushaertl** [comment]
@violoncelloch Yes, let's go for the editing approach and avoid adding a separate field.
