### ISSUE TITLE
wo befindet sich der private Schlüssel

### ISSUE THREAD

**Issue by akaro** [nextcloud/server#8444]
Fehlermeldung:
Falscher privater Schlüssel für die Verschlüsselungs-App. Bitte aktualisiere Deinen privaten Schlüssel in Deinen persönlichen Einstellungen um wieder Zugriff auf die verschlüsselten Dateien zu erhalten.

**Comment by rullzer** [comment]
Please report issues in English

**Comment by marneu** [comment]
From: apps/encryption/l10n/de.js
"Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files."
I'm having the same problem after update from 12.6 to 13.06

The question is how can I restore the the former status?

**Comment by nerdoc** [comment]
this is a dupe of #8546.
