### ISSUE TITLE
After Upgrade to 13.0.0. some Users get warning everything will be deleted. (from desktop client)

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#8446]
Hello Devs.

After upgrading our company server to 13.0.0 some (not all) users get a warning from the desktop client all files will be deleted. Obviousely the users clicked "keep data".  Is this a know bug?

Desktop Client 2.3.2 MacOS Sierra
Server Nextcloud 13.0.0 coming from 12.0.4
PHP 7.1.14

thanks and cheers

**Comment by himbeere** [comment]
![screenshot](https://user-images.githubusercontent.com/631865/36416959-ebfdf492-162a-11e8-83bd-bc9ea100ce29.jpg)

**Comment by thejulian** [comment]
Had the same Problem. Some but not all clients lost their config what to sync. Had to configure everything again. NC13 with UP-TO-Date Clients on Windows.

**Comment by himbeere** [comment]
Interesting. Thanks for the heads up.

**Comment by thejulian** [comment]
I couldn't find the problem ... but it looked like that (i think it is) sync_db client side got messed up - because some folder were unchecked but the files still existed in the filesystem on the client - but then checking the folder again made the client sync again after restart :-)

**Comment by himbeere** [comment]
Actually this looks like a serious bug because it can lead to data loss. Thanks again @thejulian

**Comment by jisse44** [comment]
Same here.
Migration and desktop client on W7 is all good, but with my Fedora 27 and Nextcloud client I had the notification window, and I synchronized everything again.

Client 2.3.3.1 on W7, Client 2.3.3 on Fedora
Server Debian 9  upgrade 12.0.4 to 13.0.0
PHP 7.0.27-0+deb9u1
Zend OPcache v7.0.27-0+deb9u1
mariadb  Ver 15.1 Distrib 10.1.26-MariaDB
