### ISSUE TITLE
change name nextcloud is not handled well

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#8447]
If I change the name to the nextcloud theme entry it changes header on the internet page bar only for the setting item, if I go in the other menus such as applications item, on the bar will always return the old name name I had given to nextcloud and not that of the change just made.

![immagine](https://user-images.githubusercontent.com/35575744/36417730-fcbea5b8-162c-11e8-8a23-c9a682437261.png)

as you can see from the screenshots

nextcloud R.P.I which is the name changed in the theme section
it is not kept in the header if I open a different menu,
as the old name (nextcloud S.C.S.P.) returns as a header

![immagine2](https://user-images.githubusercontent.com/35575744/36417731-fcdc93fc-162c-11e8-9206-268fe35cd894.png)

![immagine3](https://user-images.githubusercontent.com/35575744/36417890-6c522e54-162d-11e8-8a66-29a05fbcb84e.png)

**Comment by MorrisJobke** [comment]
> nextcloud R.P.I which is the name changed in the theme section
> it is not kept in the header if I open a different menu,
> as the old name (nextcloud S.C.S.P.) returns as a header

I don't see "Nextcloud" in the screenshots. What exactly do you mean? On the second screenshot it properly prefixes the page with another title - in this case "Apps" and then puts the remaining title properly there "S.C.S.P ~ RPi"

**Comment by tigernero79** [comment]
you did not read RPI after entry rpi application here is my oversight. we can apologize
