### ISSUE TITLE
Database crash when downloading large image files 

### ISSUE THREAD

**Issue by doganoo** [nextcloud/server#8449]
### Steps to reproduce

1. upload large image file to Nextcloud
2. download via app

### Expected behaviour
Trying to download picture with 6,7 MB in Nextcloud App. App should download large file. Issue occurred for the first time with the iOS client: https://github.com/nextcloud/ios/issues/503

### Actual behaviour

Server crashes, MySQL database restarts and log file says:

### Server configuration

**Operating system**:

Ubuntu 16.04.3 LTS Xenial

**Web server:**

Server version: Apache/2.4.18 (Ubuntu)
Server built: 2017-09-18T15:09:02
AWS t2.micro instance

**Database:**

mysql Ver 14.14 Distrib 5.7.21, for Linux (x86_64)

**PHP version:**

PHP 7.1.13-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jan 5 2018 13:26:45) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)

12.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

updated

**Where did you install Nextcloud from:**

last update via updater, first installation by downloading zip file and following instructions on UI

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
 - activity: 2.5.2
  - admin_audit: 1.2.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.1.0
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.2
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.6
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - recommendation_assistant
  - user_external
  - user_ldap
**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**

Safari

**Operating system:**
macOS High Sierra

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>
{"reqId":"TuYLOH86k5Lfg6TIuSbY","level":0,"time":"2018-02-17T11:10:40+00:00","remoteAddr":"xxx","user":"xxx","app":"core","method":"GET","url":"/index.php/apps/files/api/v1/thumbnail/128/128/Bilder/IMG_0249.JPG","message":"OC_Image->fixOrientation() Orientation: 1","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.1","version":"12.0.5.3"}
{"reqId":"K9oXYEN0j1bptRRvCKeM","level":0,"time":"2018-02-17T11:10:40+00:00","remoteAddr":"xxx","user":"xxx","app":"core","method":"GET","url":"/index.php/apps/files/api/v1/thumbnail/128/128/Bilder/IMG_0250.JPG","message":"OC_Image->fixOrientation() Orientation: 1","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.1","version":"12.0.5.3"}
{"reqId":"FlY94Pok8tnuKj1lmYBu","level":3,"time":"2018-02-17T11:10:41+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/index.php/apps/files/api/v1/thumbnail/128/128/Bilder/IMG_0248.JPG","message":"Error while sending QUERY packet. PID=2897 at /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.1","version":"12.0.5.3"}
{"reqId":"YzyNtggxGkGZotoS7gz5","level":3,"time":"2018-02-17T11:10:41+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/index.php/apps/files/api/v1/thumbnail/128/128/Bilder/IMG_0247.JPG","message":"Error while sending QUERY packet. PID=2692 at /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.1","version":"12.0.5.3"}
{"reqId":"pq748a57EVoC4irh3CKb","level":3,"time":"2018-02-17T11:10:41+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/index.php/apps/files/api/v1/thumbnail/128/128/Bilder/IMG_0246.JPG","message":"Error while sending QUERY packet. PID=2894 at /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.1","version":"12.0.5.3"}
{"reqId":"Hqv3C7LQIiNs9oS1vwsj","level":3,"time":"2018-02-17T11:10:41+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/index.php/apps/files/api/v1/thumbnail/128/128/Bilder/IMG_0251.JPG","message":"Error while sending QUERY packet. PID=3047 at /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.1","version":"12.0.5.3"}
{"reqId":"TuYLOH86k5Lfg6TIuSbY","level":3,"time":"2018-02-17T11:10:42+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/index.php/apps/files/api/v1/thumbnail/128/128/Bilder/IMG_0249.JPG","message":"Error while sending QUERY packet. PID=3056 at /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.1","version":"12.0.5.3"}
{"reqId":"K9oXYEN0j1bptRRvCKeM","level":3,"time":"2018-02-17T11:10:42+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/index.php/apps/files/api/v1/thumbnail/128/128/Bilder/IMG_0250.JPG","message":"Error while sending QUERY packet. PID=3055 at /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91","userAgent":"Mozilla/5.0 (iOS) Nextcloud-iOS/2.20.1","version":"12.0.5.3"}
#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by doganoo** [comment]
@schiessle as discussed

**Comment by mtan93** [comment]
Did you ever get to the bottom of this?

**Comment by doganoo** [comment]
nope, I did not. I guess it is due to the less power of an AWS t2.micro instance, but I am not sure.
