### ISSUE TITLE
Use underscore.min.js

### ISSUE THREAD

**Issue by coliff** [nextcloud/server#8450]
underscore.js is bundled in `vendor/core.js` but it's the unminified version. Can we replace it with the minified version? The file size is a lot smaller.
REF:
http://underscorejs.org/
http://underscorejs.org/underscore-min.js

**Comment by MorrisJobke** [comment]
@rullzer @juliushaertl Don't we do minification? Or is this only done for CSS?

**Comment by coliff** [comment]
`vendor/core.js` currently has 16 scripts bundled (can be viewed at: https://github.com/nextcloud/server/blob/master/core/js/core.json).

Of these, 7 of them are unminified. Would like to see minified versions used where possible. The GitHub repos of the relevant scripts do have minified versions in most cases.

**Comment by juliushaertl** [comment]
I see no reason not to use the minified versions there, but we need to be careful about if we have custom patches applied to those libraries.

At least for snap.js it seems that @danxuliu patched it manually: https://github.com/nextcloud/server/commit/de4028336aca79ab243fc0d1ad3a904d4cc72299#diff-e9221806a4bb9536ac5ca2f140e8f1c0

**Comment by rullzer** [comment]
I don't minify myself. The only thing I do for the scripts is append them into 1 bug one ;)

**Comment by coliff** [comment]
The `vendor/core.js` scripts which are unminified are:
```
"underscore/underscore.js"
"bootstrap/js/tooltip.js"
"backbone/backbone.js"
"es6-promise/dist/es6-promise.js"
"davclient.js/lib/client.js"
"snapjs/dist/latest/snap.js"
"select2/select2.js"
```

Minified versions are available here:
```
https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
https://cdn.jsdelivr.net/gh/twbs/bootstrap@3.3.7/js/tooltip.min.js
https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.3/backbone-min.js
https://cdnjs.cloudflare.com/ajax/libs/es6-promise/2.3.0/es6-promise.min.js
https://cdn.jsdelivr.net/gh/owncloud/davclient.js@0.1.2/lib/client.min.js
https://cdn.jsdelivr.net/gh/jakiestfu/snap.js@2.0.0-rc1/dist/2.0.0-rc1/snap.min.js
https://cdnjs.cloudflare.com/ajax/libs/select2/3.4.8/select2.min.js
```
If someone wants to update them in a PR. Please let me know if I can assist.

**Comment by MorrisJobke** [comment]
Done via #13156
