### ISSUE TITLE
Internal server error for uid with slash (/)

### ISSUE THREAD

**Issue by soumplis** [nextcloud/server#8453]
Nextcloud does not handle correcly user ids with slashes and throws HTTP Error 500. If a user has a slash in the uid while logging on, nextcloud throws Internal Server Error and no actions on the user are effective through the administration panel  for users. The user can only be deleted or managed through the cli.

In our scenario we use the user_saml plugin and the uid with the slashes is automatically generated for random users due to the computedid function we use on the IdP (the SHA1 result of the username with a salt)

### Steps to reproduce
1. Use the user_saml app and map the uid attribute to a computedid attribute released from your idp
2. Choose a user that the computedid includes a / value
3. Login to your nextcloud installation
4. The user is redirected to the idp, authenticates successfully and when returns to the nextcloud gets an internal server error
5. Check the nextcloud log file
{"reqId":"ctzyfLMCeapVPqvb4e9i","level":3,"time":"2018-02-20T09:33:04+00:00","remoteAddr":"10.113.13.11","user":"wXHHqYbG\/zM16zmnKGOk1A5gNng=","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"userId\\\" for route \\\"core.avatar.getAvatar\\\" must match \\\"[^\\\/]++\\\" (\\\"wXHHqYbG\\\/zM16zmnKGOk1A5gNng=\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/docroot\\\/owncloud.domain.tld\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(136): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'core.avatar.get...', 1, Array, Array)\\n#1 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/Route\\\/Router.php(337): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('core.avatar.get...', Array, 1)\\n#2 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('core.avatar.get...', Array, false)\\n#3 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/URLGenerator.php(79): OC\\\\Route\\\\CachingRouter->generate('core.avatar.get...', Array)\\n#4 \\\/docroot\\\/owncloud.domain.tld\\\/core\\\/templates\\\/layout.user.php(114): OC\\\\URLGenerator->linkToRoute('core.avatar.get...', Array)\\n#5 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/docroot\\\/owncloud.s...')\\n#6 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/docroot\\\/owncloud.s...', NULL)\\n#7 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/legacy\\\/template.php(204): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC_Template->fetchPage()\\n#9 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#10 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(114): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#11 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#12 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#15 \\\/docroot\\\/owncloud.domain.tld\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#16 \\\/docroot\\\/owncloud.domain.tld\\\/index.php(37): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/docroot\\\/owncloud.domain.tld\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":163}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/63.0.3239.132 Safari\/537.36","version":"13.0.0.14"}

### Expected behaviour
Login to nextcloud 

### Actual behaviour
Internal Server error

### Server configuration

**Operating system**:
CentOS 7

**Web server:**
Apache 2.4

**Database:**
MySQL
**PHP version:**
Php 5.4
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from owncloud 10

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - admin_audit: 1.3.0
  - apporder: 0.4.1
  - calendar: 1.6.0
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.2
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - polls: 0.8.1
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - ransomware_protection: 1.1.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - user_external: 0.4
  - user_saml: 1.4.2
  - user_usage_report: 1.0.1
  - weather: 1.5.1
  - workflowengine: 1.3.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "box.domain.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/box.domain.tld",
        "overwritehost": "box.domain.tld",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "mail_smtpauthtype": "LOGIN",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "memcache01.domain.tld",
                11211
            ],
            [
                "memcache02.domain.tld",
                11211
            ]
        ],
        "knowledgebaseenabled": false,
        "allow_user_to_change_display_name": false,
        "skeletondirectory": "",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "filesystem_check_changes": 1,
        "enable_previews": true,
        "preview_max_filesize_image": 150,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ]
    }
}
</details>

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
SAML

**Comment by blizzz** [comment]
Slashes are not allowed within the user name in nextcloud. anyhow, can you please reopen at the [saml app](https://github.com/nextcloud/user_saml/)? Ty!
