### ISSUE TITLE
Upgrade procedure failed from version 12 to 13 (2013 Lost connection to MySQL)

### ISSUE THREAD

**Issue by bambita** [nextcloud/server#8460]
### Steps to reproduce
1. Upgrade procedure from 12 to 13
2. Both via Web Updater and command libe

### Expected behaviour
Upgrade procedure to be completed

### Actual behaviour
Upgrade procedure failed with error

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing '
                        UPDATE `oc_filecache`
                        SET `mimetype` = ?
                        WHERE `mimetype` <> ? AND `mimetype` <> ? AND `name` COLLATE UTF8_general_ci LIKE ?
                ' with params ["87", 2, "87", "%.gpx"]:

SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query
Update failed
```

### Server configuration

**Operating system**: debian 8.0

**Web server:** nginx/1.6.2

**Database:** mysql  Ver 14.14 Distrib 5.5.59

**PHP version:** PHP 5.6.33-0+deb8u1

**Nextcloud version:** (see Nextcloud admin page) 12.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:** couple of regular updates via web updater

**Where did you install Nextcloud from:** nexcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud
```
</details>

**Comment by blizzz** [comment]
I guess something happened with your database server during upgrade. would check with system logs. Therre's not much we can do in that case. → use backup and retry.

**Comment by MorrisJobke** [comment]
No feedback since 2 months -> closing
