### ISSUE TITLE
Web update 12.0.3 to 12.0.5 via symlinked directory

### ISSUE THREAD

**Issue by dirigit** [nextcloud/server#8461]
### Steps to reproduce
1. Have a running instance of NC 12.0.3 accessible via http(s)://server/nc which is a symlink (Apache host, i.e. /some/dir/for/nc symlinked to /var/www/htdocs/nc or any other sub directory in your webroot)
2. Run Web Updater

### Expected behaviour
Update should run well

### Actual behaviour
Update fails, blank page or page update needed is shown. Running occ via shell in symlinked directory does not complete update as well.

Running web updater directly (direct access to real installation directory via Apache without symlink) updater works.

NC itself works fine via symlink like expected (12.0.3 as well as 12.0.5).

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** mysql

**PHP version:** 7.0.x

**Nextcloud version:** (see Nextcloud admin page) 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** website

**Comment by MorrisJobke** [comment]
Could you check the nextcloud.log and updater.log in your data directory?

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
