### ISSUE TITLE
Where to be put this: When xmpp client nextcloud app is enabled nextlcoud work slow and when nextcloud talk make video call or write message in nexcloud talk application nextcloud work slow.

### ISSUE THREAD

**Issue by gurussia** [nextcloud/server#8481]
Guys

this is seriuos matter. When i enable xmpp client application or nextcloud talk and write message nextcloud is working slow and when xmpp or nextcloud talk are disabled nextcloud work fast. So what happening. what php modules need to be installed, some times i see  jbd2/sda1-8 is using 100 % how to disable it, how much RAM there is need to make nextcloud work everything fast. Do user need to have 128 gb. ram, i can't have 128 gb. ram it is very much money. 3xx euros for 128 gb. ram. Guys remember servers motherboard don't have 128 gb. ram and they programs works like a charm. ibm and etc. include server motherboard come with less graphics cards some 128 mb. of ram

**Comment by gurussia** [comment]
update 1: it disabled nextcloud talk and nextcloud return work fast.

**Comment by MorrisJobke** [comment]
Nextcloud in small instances with a few users should be totally fine with 1-2 GB of RAM for everything (DB, webserver, PHP, redis, etc). No need to for for that much RAM unless you want to host a really big instance.

I have no idea about the XMPP app - reach out the maintainer of this app to know about this. Also the talk app is not part of the server repo. usually the talk app require quite some amount of connections for the signaling, but nothing that should be too much for a DB with a few hundred MB of RAM available. Check the IO stats of you system and maybe ask in the forums for help with the actual setup.


https://help.nextcloud.com

We don't see any big performance problems with the server and the talk app itself, so this is very likely related to the setup (maybe too few web server connections or database connections configured?).

**Comment by MorrisJobke** [comment]
XMPP app: https://github.com/nextcloud/jsxc.nextcloud
Talk app: https://github.com/nextcloud/spreed
