### ISSUE TITLE
files_external:notify

### ISSUE THREAD

**Issue by addaitrs** [nextcloud/server#8487]
### Steps to reproduce
1. Mount the SMB shares as normal using the "Log-in credentials, save in database" method
2. sudo -su www-data ./var/www/nextcloud/occ files_external:notify 17

### Expected behaviour
It starts to monitor the SMB share for changes

### Actual behaviour
[Icewind\SMB\Exception\ConnectionException]
Connection not valid

### Server configuration

Installed from .OVF
Ubuntu 12.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
17.0.25

**Nextcloud version:** (see Nextcloud admin page)
13.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
official .OVF

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
feels like smb does not like the credentials… can you provide the nextcloud log file?

**Comment by addaitrs** [comment]
Hi yes, indeed that was it

I had to use DOMAIN/user to connect.

But I now receive the following 

 [Icewind\SMB\Exception\RevisionMismatchException]              
  Notify is not supported with the used smb version

**Comment by addaitrs** [comment]
Closing issue, now resolved with using the Domain with the username.
