### ISSUE TITLE
I have to keep deleting the .steps file for updated to work

### ISSUE THREAD

**Issue by andreicociuba** [nextcloud/server#8493]
hi, i am on a daily release channel, and this keeps ahppening to me:

![image](https://user-images.githubusercontent.com/3407201/36523216-38409560-17a9-11e8-89b1-8cde6ce2f892.png)

now i did find somewhere around here the solution: deleting the .steps file, but i am curious: Where should i look for the cause of WHY it doesnt get deleted automagically?

## Server configuration detail

**Operating system:** Linux 4.13.0-19-lowlatency #22-Ubuntu SMP PREEMPT Mon Dec 4 12:49:12 UTC 2017 i686

**Webserver:** Apache/2.4.27 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.21

**PHP version:** 7.1.11-0ubuntu0.17.10.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, smbclient, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache, xdebug

**Nextcloud version:** 13.0.0 Build:2018-02-16T23:01:27+00:00 964b511b39a19d7837714fc3dc4f95986dd56e75 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 12.something....

**Where did you install Nextcloud from:**
github

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_notifications: 1.0.1
 - apporder: 0.4.1
 - audioplayer: 2.2.5
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.0
 - caniupdate: 0.1.2
 - circles: 0.13.6
 - cms_pico: 0.9.7
 - comments: 1.3.0
 - contacts: 2.1.0
 - dav: 1.4.6
 - external: 3.0.2
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.0
 - files_reader: 1.2.2
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - flowupload: 0.0.7
 - gallery: 18.0.0
 - gpxpod: 2.2.2
 - impersonate: 1.0.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - metadata: 0.6.0
 - music: 0.5.6
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ocsms: 1.12.2
 - passman: 2.1.4
 - password_policy: 1.3.0
 - phonetrack: 0.2.0
 - polls: 0.8.1
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - registration: 0.3.1
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_facebook: 1.0.2
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - unsplash: 1.0.5
 - updatenotification: 1.3.0
 - weather: 1.5.1
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - deck
 - encryption
 - files_clipboard
 - folderplayer
 - gpxmotion
 - ojsxc
 - onlyoffice
 - sensorlogger
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cociubaandrei.ddns.net:8082",
        "cociubaandrei.ddns.net",
        "192.168.0.230"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/cociubaandrei.ddns.net:8082\/nextcloud",
    "dbtype": "mysql",
    "version": "13.0.0.14",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "maintenance": false,
    "updater.release.channel": "daily",
    "loglevel": 0,
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**no

### Client configuration
**Browser:** CHrome

**Operating system:** Windows 10

#### Web server error log
<details>
none that i deem relevant, but if requested i can provide.

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
none that i deem relevant, but if requested i can provide.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
none that i deem relevant, but if requested i can provide.

```
</details>

**Comment by blizzz** [comment]
Sorry, what exactly is the issue?

**Comment by andreicociuba** [comment]
@blizzz  when i enter the updater, some steps are pre-checked and updating doesnt work.

i figured from around here that is because the .step file used during updating is not deleted during update. 

point is, i am tired of logging into ssh to delete it every day.....

**Comment by blizzz** [comment]
did you try running ``php occ maintenance:repair``? There seems to be a related repair step.

**Comment by andreicociuba** [comment]
i ran it yesterday, but i havent had any daily updates show up yet to see if it is a permanent fix.

i'll monitor this for the next two daily updates and let you know.

**Comment by andreicociuba** [comment]
unfortunately, i have to run the maintencance:repair again, since the problem persists.

is this normal? to have to run it every time you update?
if so, can it be simply attached to the update script?

**Comment by andreicociuba** [comment]
i just put occ maintenance:repair in a cron job that runs every night.

good enough for me.

**Comment by MorrisJobke** [comment]
> is this normal? to have to run it every time you update?

No - usually this is automatically run during the exection of `occ upgrade` to clean up. The step files nevertheless are cleaned up as a background job to be sure, that the upgrade itself worked. So you need to run the `cron.php` at least once after an upgrade to remove the step file. This should normally be the case.

Thanks for the feedback that you solved it now - closing.
