### ISSUE TITLE
Include "nextcloud" in status.php 

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#850]
For distinguishing between Nextcloud and ownCloud we (android dev team, https://github.com/nextcloud/android/issues/188) need a proper way.
I suggest to add this to status.php.

Remaining problem is, that this will only work for new server versions and not for existing ones.

**Comment by LukasReschke** [comment]
Thoughts, @rullzer for the desktop client perspective? Does the client properly parse the status.php or does it do some magic? ;)

**Comment by rullzer** [comment]
Yes it parses it. Since there are checks for the version with regards to sharing stuff.

**Comment by AndyScherzinger** [comment]
@LukasReschke @rullzer still leaves us with the problem that we can't distinguish between oC and Nc instances :(

**Comment by LukasReschke** [comment]
Well. You gotta start at some point, at the moment you simply can't. But in the future you can ;)

**Comment by rullzer** [comment]
I'm fine adding this. Just let me know what and where. Altough I prefer to also have nice capabilities for stuff instead of relying on version number magic.

**Comment by AndyScherzinger** [comment]
Uuuhh :) True Feature detection as in getting a list of available features that can be utilized by the client would be way nicer. Also looking even further in a way that installed apps could then also register features :D (I am probably going to far with this...)

**Comment by rullzer** [comment]
Apps can already register capabilities:

see: <SERVER>/ocs/v2.php/cloud/capabilities

**Comment by rullzer** [comment]
Also see https://github.com/nextcloud/server/pull/855

**Comment by MorrisJobke** [comment]
Done `{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"12.0.0.12","versionstring":"12.0 alpha","edition":"","productname":"Nextcloud"}`

**Comment by MorrisJobke** [comment]
Was added in 11 - #1160
