### ISSUE TITLE
CSS element width for name and slogan

### ISSUE THREAD

**Issue by alenkovich** [nextcloud/server#851]
width should be set to 100%

Currently it's not centered if you have longer text.

Nextcloud 9.0.53

**Comment by Bugsbane** [comment]
On what page are you referring to? I don't see the name and slogan anywhere but the login page, where it already appears to be centred on my install.

**Comment by alenkovich** [comment]
Yes, it's only on login page and defalut text is ok.. but if you add a bit more text you'll see it stretches to the right.

**Comment by Bugsbane** [comment]
OK, yes, I see what you mean now. I'll take a look into it.

**Comment by Bugsbane** [comment]
@juliushaertl - This issue is fixed without any noticeable side effects that I can see just by removing lines 266 and 441 of styles.css in the CSS-fixes branch. Can I commit this directly, or should I be doing the whole branch/PR thing?

**Comment by juliushaertl** [comment]
@Bugsbane Those changes should work. :+1: 

Direct committing to master isn't possible, but if you mean direct editing right on GitHub, you can do that. There should be the option to create a pull request right there in the user interface.

**Comment by Bugsbane** [comment]
By direct committing, I meant direct committing to another branch like theming-fixes, or is it normal to create a new branch for almost every PR?

**Comment by juliushaertl** [comment]
OK, now i understand. I'd say this is something for a new branch, even
though it is a very small change.

**Comment by Bugsbane** [comment]
OK. Will do. I'm still getting the hang of figuring out what does and what doesn't justify a new branch. Thanks for your help.

**Comment by juliushaertl** [comment]
@Bugsbane are you still up for this? :wink:

**Comment by juliushaertl** [comment]
Fix is in #2325
