### ISSUE TITLE
Per user bruteforce detection

### ISSUE THREAD

**Issue by RalphBariz** [nextcloud/server#8510]
Situation:
The nextcloud instance is in a container behind an apache proxy running on host, therefore all access attemps have the same IP, the IP of container host.

Observed:
When bruteforce lock is triggered, all users are blocked.

Expected:
Switching system to a per user lock instead of a per IP lock.

BR
Ralph

**Comment by MorrisJobke** [comment]
This is already supported. The behaviour you described looks like the proxy server doesn't properly forward the IP addresses of the clients. We have a dedicated documentation page for this, that lists the steps that you need to take to accomplish this.

https://docs.nextcloud.com/server/13/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by RalphBariz** [comment]
Thanks a lot
