### ISSUE TITLE
Not playing video when use PHP 7 on shared links

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/server#852]
Recommended by tflidd to open this bug to ask to backport the fix from owncloud:

https://help.nextcloud.com/t/official-app-video-player-cannot-play-external-links/2198/3

https://github.com/owncloud/core/issues/25483

**Comment by tflidd** [comment]
I just checked the code, and this fix was already implemented here: https://github.com/nextcloud/server/commit/4f904471507865e12597c7ba906249efe43dfd37
You probably need to wait for the next release and apply the patch manually. Sorry, that I didn't check this out before.
