### ISSUE TITLE
Can't use app data after upgrade to 13.0.0

### ISSUE THREAD

**Issue by detly** [nextcloud/server#8526]
For a while I've been running a script based on [`pyocclient`](https://github.com/owncloud/pyocclient) that manipulates data in the app data store to keep track of what it's doing. Since upgrading to Nextcloud 13.0.0, it's suddenly started failing. I've reduced it down to this single example Python script. You need to do `pip install pyocclient` to be able to run it (or however you want to install dependencies). Put in the appropriate credentials and execute it to test.

```python
#!/usr/bin/env python3

import owncloud

DOMAIN = "https://nextcloud.../"
USER = ""
PASSWORD = ""
APP_NAME = 'some-test-app'

oc = owncloud.Client(DOMAIN)
oc.login(USER, PASSWORD)
attrs = oc.get_attribute(APP_NAME)

from pprint import pprint
pprint(attrs)
```

With a Nextcloud server <= 12, this script runs fine — even if you have no data stored for `APP_NAME`, you'll just get an empty list back. Just to be clear, `APP_NAME` is made up, it doesn't have to correspond to any installed app to work.

Under 13, the script throws an exception ending in:

```text
owncloud.owncloud.OCSResponseError: OCS error: 998
```

What's changed that might cause this? I realise that this is an *Own*cloud library, not a *Next*cloud library, but I think they're similar enough for this to make sense.

**Comment by detly** [comment]
By the way, as far as I could tell this data was just stored in the `oc_privatedata` table. It was usually empty unless my script had put anything there.

**Comment by detly** [comment]
Looking through the source, it looks like the route for the `privatedata` key-value store is `ocs/v2.php/privatedata/`, whereas [`pyocclient` uses](https://github.com/owncloud/pyocclient/blob/master/owncloud/owncloud.py#L300) `ocs/v1.php/privatedata/`. Monkey patching the script with the line:

```python
oc = owncloud.Client(DOMAIN)
oc.OCS_BASEPATH = 'ocs/v2.php/'
oc.login(USER, PASSWORD)
attrs = oc.get_attribute(APP_NAME)
```

...turns the response 998 into a response 200. I'm not sure what this means either, but I'll keep looking.

**Comment by rullzer** [comment]
Mmm we moved this to an app. Please see https://github.com/nextcloud/privatedata

I will look into it.

**Comment by detly** [comment]
I actually looked for an app named "private" anything, but got nothing
(this is via the admin account, apps, ctrl f). Do I need to enable or
install it in some particular way?

**Comment by detly** [comment]
Oh I see, the route is different. Instead of `/ocs/vX.php/...` it's `/privatedata`. I'll change the patching in my script and see what happens.

**Comment by rullzer** [comment]
Ah mmmit is not in the appstore indeed. I guess we forgot some steps when we moved it to an app.

@MorrisJobke shall I put it in the appstore? Or do we want to ship it by default?

**Comment by MorrisJobke** [comment]
> @MorrisJobke shall I put it in the appstore? Or do we want to ship it by default?

Ship it, or what to do here? Because it is a core feature of OCS, right?

**Comment by detly** [comment]
What's the outcome of this? Should I wait for a separate app in the app store, or an update to core?

**Comment by detly** [comment]
If it's a core feature, isn't this more serious than an "enhancement"? Or is there a workaround?

**Comment by tflidd** [comment]
It is a broken feature, so it's a regression, isn't it?

**Comment by detly** [comment]
I would have thought so. But should the bug be in the other project or here?

**Comment by detly** [comment]
I'd love to help with this, but I don't know what the intent is. Is it a core function that needs to be fixed, or a separate app that needs to be published, or something else? Where should I start?

**Comment by detly** [comment]
I see 14 is ready for beta testing but this is still missing. If private data is deprecated I'll need to find an alternative. Is it likely to be restored in the future?

**Comment by tflidd** [comment]
@rullzer @MorrisJobke What is the status? The pyocclient can also be very useful for some testing on Nextcloud setups.

**Comment by detly** [comment]
Hi @rullzer @MorrisJobke — it's been six months, and another major version, since we had any update on this. Could you, or any other dev, please just give some suggestion of what someone needs to do to restore this functionality? Even just where to start? I might have the time to help with something straightforward, but I definitely don't have the time to learn NextCloud's inner workings from scratch and reverse engineer what's going on here.

**Comment by MorrisJobke** [comment]
@rullzer Is this the app you want to release in the appstore? https://github.com/nextcloud/app-certificate-requests/pull/163

**Comment by MorrisJobke** [comment]
We released the app now: https://apps.nextcloud.com/apps/privatedata

Just install this app and then the API is available.

**Comment by detly** [comment]
I cannot find this in the apps directory within Nextcloud, and there's no way to search all apps. What category is it in?

**Comment by detly** [comment]
Sorry, "integration", found it.

**Comment by MorrisJobke** [comment]
> I cannot find this in the apps directory within Nextcloud, and there's no way to search all apps. What category is it in?

We fixed this in 14.

**Comment by detly** [comment]
It's in 13.x as well. I can confirm that my test script now works, thanks. Note that the route modification I [suggested earlier](https://github.com/nextcloud/server/issues/8526#issuecomment-368210245) is not necessary. Thanks for fixing.

**Comment by detly** [comment]
Broken again! See https://github.com/nextcloud/privatedata/issues/2
