### ISSUE TITLE
is imap still supported on nextcloud 13? 

### ISSUE THREAD

**Issue by albjeremias** [nextcloud/server#8527]
Hi,

it's a freshed installed nextcloud... I want the users to connect to the nextcloud using IMAP, is it still working on nextcloud 13? 

I saw there were some commits:
https://github.com/nextcloud/server/commit/57fb37151a6c29d857733c78e3b00909aabaf413

This is my config.php:
```
'user_backends' => array(
          array(
                  'class' => 'OC_User_IMAP',
                  'arguments' => array('{imap.example.org:143/imap/ssl}INBOX')
          )
  ),
);
```

And this is the error I get:
"User backend OC_User_IMAP not found."

![image](https://user-images.githubusercontent.com/26681446/36630932-526c6c30-196f-11e8-89d7-20a4a2dc158f.png)

**Comment by albjeremias** [comment]
I searched for the string:

```
$ grep -rHn "OC_User_IMAP" .
./server/config/config.sample.php:260: * IMAP (OC_User_IMAP), SMB (OC_User_SMB), and FTP (OC_User_FTP).
./server/config/config.sample.php:264:		'class' => 'OC_User_IMAP',

```

**Comment by blizzz** [comment]
Not part of the server. You need to get it from here it seems: https://github.com/nextcloud/apps/tree/master/user_external But according to its appinfo NC 13 is supported.
