### ISSUE TITLE
Notify the share owner when another user downloads a shared file

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#853]
## Use Case

1. User A shares a file with User B.
2. User B downloads the file via Web/desktop client/mobile.
3. User A is notified that User B has downloaded the file and via which method - Web, desktop client or mobile.

All activity will be tracked in the Activity app, but it's also possible to retrieve the information via apps or external tools.

## Caveats

* The desktop client downloads all files, so we can only tell that the user has synchronised that folder and that it is now stored locally
* If someone shares a file with a hundred users, there will be lots of activity in the stream and in the sidebar. Filtering will be required at some point

## Status

- [x] The activity stream of User A shows that User B has downloaded the file
- [x] The method used to retrieve the file (Web, desktop client or mobile) is listed in the stream
- [x] The data can easily be extracted via SQL commands or via an external logging app such as Elastic Search, Mattermost or Slack

### PRs

* https://github.com/nextcloud/server/pull/854
* https://github.com/nextcloud/activity/pull/19

### Global stream

![global_activities](https://cloud.githubusercontent.com/assets/323220/14109530/c0f18f78-f5c2-11e5-87b7-d7b6a3ccf9d0.png)

### File stream

![client_used](https://cloud.githubusercontent.com/assets/323220/14140336/ae7ec9b2-f678-11e5-9f1a-8a2168929351.png)

### Desktop client stream

![desktop_activities](https://cloud.githubusercontent.com/assets/323220/14109545/d309137a-f5c2-11e5-81d9-16ef18e6ec21.png)

### Desktop client export

```
            NSA@localhost:4443,      Wed Mar 30 11:06:53 2016 GMT,/Governments/oC_WD_Pidrive_backdoor.txt,        Shared file Governments/oC_WD_Pidrive_backdoor.txt was downloaded by DGSI via the web client,                                                       
            NSA@localhost:4443,      Wed Mar 30 11:06:53 2016 GMT,/Governments/iOS hacking toolbox.jpg,           Shared file Governments/iOS hacking toolbox.jpg was downloaded by DGSI via the web client,                                                       
            NSA@localhost:4443,      Wed Mar 30 11:06:52 2016 GMT,/Governments/Social_Media_Application_DOJ.pdf,  Shared file Governments/Social_Media_Application_DOJ.pdf was downloaded by DGSI via the web client,    
```

###  OCS REST API

```
      {
        "id": 1936,
        "subject": "Shared file Contracts/Governments/4G pineapple.jpg was downloaded by BND via the Web client",
        "message": "",
        "file": "/Contracts/Governments/4G pineapple.jpg",
        "link": "https://localhost:4443/files/index.php?dir=%2FContracts%2FGovernments",
        "date": "2016-03-30T15:06:57+00:00"
      },
```

### CSV export from phpMyAdmin

```
"1979","1459519926","30","remote_download","GCHQ","admin","files_sharing","shared_file_downloaded","[{""56063"":""\/Contracts\/Governments\/QC_Android6_rootkit.rar""},""GCHQ"",""Web""]",,"[]","/Contracts/Governments/QC_Android6_rootkit.rar","https://localhost:4443/files/index.php?dir=%2FContracts%2FGovernments","files","56063"
```

### Report from phpMyAdmin

![plenty_of_formats](https://cloud.githubusercontent.com/assets/323220/14210053/9ad32ce0-f827-11e5-8411-18d107e972fd.png)

| Date | Information |
|:---:	|:-------: |
| 2016-03-30 16:10:48 | [{&quot;56063&quot;:&quot;\/Contracts\/Governments\/QC_Android6_rootkit.rar&quot;},&quot;BND&quot;,&quot;Web&quot;] |
| 2016-03-30 16:11:32 | [{&quot;56051&quot;:&quot;\/Contracts\/Governments\/iOS hacking toolbox.jpg&quot;},&quot;BND&quot;,&quot;Web&quot;] |
| 2016-03-30 17:06:57 | [{&quot;56050&quot;:&quot;\/Contracts\/Governments\/4G pineapple.jpg&quot;},&quot;BND&quot;,&quot;Web&quot;] |

**Comment by oparoz** [comment]
@derekblankmccoy - This features will now be tracked here. We'll make sure it works with LDAP.

**Comment by derekblankmccoy** [comment]
I guess this didn't make it to 9.1?

**Comment by oparoz** [comment]
> Just found an issue with this. It doesn't seem to work with shared folders.

@derekblankmccoy - It's by design. The idea is to be able to monitor who has downloaded/read a file. It makes much less sense for folders which can contain dozens or even hundreds of files and which won't be all read at the same time.

**Comment by derekblankmccoy** [comment]
Cool, We're looking at Nextcloud as it is. No, I mean If I download a file inside a folder, it doesn't seem record the action in activity. Like this:

1. User A creates a folder with files inside
2. User A shares the folder with User B
3. User B downloads file inside folder

**Comment by nickvergessen** [comment]
The feature was implemented as a new app:
https://github.com/nextcloud/files_downloadactivity

**Comment by popomoc** [comment]
Hello,
is possible to isnall the app in nextcloud 11 ? i tryed but there is an error message: 

This app has no minimum Nextcloud version assigned. This will be an error in the future.

This app cannot be installed because the following dependencies are not fulfilled:

    Server version 9.2 or lower is required.

If i try to change max version in xml also not hels me :(

Thank you
BR
tom

**Comment by nickvergessen** [comment]
Will handle the issue in https://github.com/nextcloud/files_downloadactivity/issues/3

**Comment by oparoz** [comment]
@derekblankmccoy If you're now using Nextcloud, you should move the bounty to this issue as there is little development taking place in ownCloud.
