### ISSUE TITLE
No Home access after moving shared folders

### ISSUE THREAD

**Issue by MrNoname33** [nextcloud/server#8534]
Somebody shared folders with me and moved them to a group folder. After that I cant get access to my home in the web gui anymore. When I click on "shared with me" or something else left then I get access but never on the home symbol. The person who shared that folder with me and moved it into the group folder cant get access his home too.

What is to do to solve this situation?

**Comment by MorrisJobke** [comment]
Could you fill out the issue template? https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md

Thanks

**Comment by MrNoname33** [comment]
Pardon me. I filled it out and release it there: [](https://github.com/nextcloud/groupfolders/issues/94)

**Comment by MrNoname33** [comment]
I solved the problem on the mysql console:
`delete from oc_share where uid_owner='name1' and share_with='name2';`

But it would be very helpful if anybody could confirm this bug or if is an error that only come up on my machine.

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing @icewind1991

**Comment by rullzer** [comment]
We probably should forbid moving shared folders inside of groupfolders... (or the other way around)

**Comment by MrNoname33** [comment]
Is it an absolute path to a folder like this? Could it be a solution to work with an index number?

And why can't I access my home folder if there is a broken path there? This way it is possible that I prevent myself as admin from working with Nextcloud. And when I am not able to understand the tables in the Nexcloud database so that I can't delete the broken links like I did, then it is a real great problem.

**Comment by MorrisJobke** [comment]
We fixed something related to this lately. The upcoming 15.0.6 will have those fixes - #14689, #14690 and #14691. Thus I will close this here for now.
