### ISSUE TITLE
migration from oc 10.0.6.1 to nc 12 fails

### ISSUE THREAD

**Issue by rschitz** [nextcloud/server#8542]
I know this version is not yet supported by the migrator but since the 10.0.6 is a small hotfix [https://github.com/owncloud/core/pull/30265](url) i wonder if there is any trick to void the 

> Exception: Updates between multiple major versions and downgrades are unsupported.

thanks

**Comment by MorrisJobke** [comment]
Thanks - fix is in #8544.

You could replace the code with Nextcloud 12.0.5 and do the changes in the linked PR to get the upgrade running.

Will be available with 12.0.6 for normal packages. Or should we do a 12.0.5b for the OC migration only? @nickvergessen @rullzer

**Comment by rschitz** [comment]
it works with the new version.php file, thanks!

**Comment by nickvergessen** [comment]
12.0.6 sounds fine, should be due in 2-3 weeks anyway?
