### ISSUE TITLE
Profile picture is wrong with surname starting with É

### ISSUE THREAD

**Issue by biva** [nextcloud/server#8556]
### Steps to reproduce
1. Change your name and write "Ésomething"
2. Look at your personal picture: it is a circle with a capital "Ã" instead of a "É"

### Expected behaviour
The circle should show a "É". Not sure what happens with other accentuated capital letter.

This issue did not exist with NC12 and former versions.

### Server configuration

**Operating system**: Debian 9
**Nextcloud**: NC 13

**Comment by MorrisJobke** [comment]
Duplicate of #8468

**Comment by MorrisJobke** [comment]
And #8451 - fixed with the upcoming 13.0.1
