### ISSUE TITLE
ban user from ftp-server code java ?

### ISSUE THREAD

**Issue by Stronglover** [nextcloud/server#8558]
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Scanner;
import org.apache.commons.net.ftp.FTPClient;
import org.apache.ftpserver.ftplet.FtpException;

public class Client {

    public static void main(String[] args) throws FtpException, IOException, Exception {

        String server = "localhost";
        int port = 2221;
        String user = "user1";
        String pass = "pass1";
        Scanner sc = new Scanner(System.in);
        FTPClient client = new FTPClient();
        client.connect(server, port);
        boolean login = client.login(user, pass);
        boolean connect=true;

        if (login == true) {

            System.out.println("Login success...");

            System.out.println("files on server directory :");
            //Show the files in server directory
            String[] file = client.listNames();
            if (file != null && file.length > 0) {
                for (String aFile : file) {
                    System.out.println(aFile);
                }
            }

            String Option;
            String Upload = "upload";
            String Download = "download";
            System.out.println("Take your choice to UPLOAD File to server |or| DOWNLOAD File from server !!!");
            Option = sc.next();

            if (Option.equals(Upload)) {
                // upload
                try {
                    System.out.println("Start UPLOADING ......");
                    String name_client_file = "file_from_client.txt";// name field to upload
                    String client_path = "C:\\Ftpserver\\UP\\";// user directory
                    FileInputStream fileinputstream = new FileInputStream(client_path + name_client_file);
                    boolean upload = client.storeFile(name_client_file, fileinputstream);

                    if (upload == true) {
                        System.out.println("successfully done !!");
                        fileinputstream.close();
                    } else {
                        System.out.println("something wrong !!");
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
             else if (Option.equals(Download)) {
                // download
                try {
                    System.out.println("DOWNLOADING file ............");
                    String name_server_file = "from_server.txt";// name of field to downlod
                    String local_path = "C:\\Ftpserver\\";// downold directory
                    FileOutputStream fileoutputstream = new FileOutputStream(local_path + name_server_file);
                    boolean Downlod = client.retrieveFile(name_server_file, fileoutputstream);

                    if (Downlod == true) {
                        System.out.println("successfully done !!");
                        fileoutputstream.close();
                    } else {
                        System.out.println("something wrong !!");
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            }

                    boolean logout = client.logout();
                    if (logout == true) {
                        System.out.println("Logout from FTP server...");
                    }

                } else {
                    System.out.println("Login fail...");
                }

                client.disconnect();

            }

        }

**Comment by MorrisJobke** [comment]
I don't know what you want to tell us with this. 😕 

We are first a PHP project and if you look into a way to protect users: we have built in bruteforce detection which adds a time penalty to requests from an IP if multiple failed login happened. Beside that you can also disable users in the user management.
