### ISSUE TITLE
How to make auto login in nextcloud iframe integration 

### ISSUE THREAD

**Issue by anujku123** [nextcloud/server#8560]
We want integrate nextcloud's iframe in our website and auto login in nextcloud server. For this we are using following iframe .
 
<iframe   style="height: 700px ; width: 1100px"
       src="xxxxxxxxxxxxxxx/index.php/login?user=userName&amp;pass=password" ></iframe>

But it is not working . it show me error in console as Below :-1: 

en_GB.js:1 Uncaught ReferenceError: OC is not defined
    at en_GB.js:1
previewplugin.js:122 Uncaught ReferenceError: OCA is not defined
    at previewplugin.js:122
viewer.js:15 Uncaught ReferenceError: OC is not defined
    at viewer.js:15
fileinfo.js:147 Uncaught ReferenceError: OC is not defined
    at fileinfo.js:147
client.js:839 Uncaught ReferenceError: OC is not defined
    at client.js:839
contactsmenu.js:537 Uncaught ReferenceError: OC is not defined

### Expected behaviour
 User should auto login in nextcloud server's iframe 

### Actual behaviour
   User does not auto login in nextcloud with this approach . instead of it show me login page of nextcloud server . 

 Please anyone help me how can i integrate auto login in nextcloud using iframe . Thanks in advance .

**Comment by MorrisJobke** [comment]
> <iframe style="height: 700px ; width: 1100px" src="xxxxxxxxxxxxxxx/index.php/login?user=userName&pass=password" ></iframe>

This is not really supported and I doubt that we will add such support. Maybe have a look at the login flow, but this "automatic fill of credentials" looks weird to me. :/

cc @nickvergessen @rullzer @LukasReschke @nextcloud/security

**Comment by rullzer** [comment]
This is not supported.

Can I ask what the use case is?

**Comment by anujku123** [comment]
@rullzer  @MorrisJobke 
 I want to  iframe integration of next cloud  in our website As well  auto login in nextcloud server when i login in my application .

**Comment by rullzer** [comment]
This is not supported in the way you describe. (I'm not even sure if iframing nextcloud will really work well).

For the auto login you could look at https://github.com/nextcloud/loginviapost

**Comment by MorrisJobke** [comment]
Closing as it is unlikely that we will provide this feature in the future. Just redirect and use a proper single sign on if you want to have flawless integration into other services.

**Comment by Aldo-f** [comment]
I have done this:
* create an app
https://apps.nextcloud.com/developer/apps/generate 
* pass the userId and additional data with your nextcloud-app
id passed 3 vars: the cookie (``oc_sessionPassphrase``), the userId and the appName
``http://example.com/api/login?c=cookie&u=userId&n=appName``
* EXTRA: create a cookie (same cookie that you passed in the url) for the website domain for a short period of time (1s is sufficient) 
check if these are the same (on the child site)  before continuing 
* on the child website, get the vars (userId, cookie, appName)
* get user data from nextcloud
``curl -sS -H "OCS-APIRequest: true" -X GET http://admin:secret@example.com/nextcloud/ocs/v1.php/cloud/users/userId``
* get the userId groups, and give the user based on these groups a login on the child site
``$userGroups = (array) $output->data->groups->element;``

Good luck
