### ISSUE TITLE
The icon in Security about sync client is missing like linux,mac and windows.

### ISSUE THREAD

**Issue by supermanlinux** [nextcloud/server#8571]
The icon in Security about sync client is missing like linux,mac and windows.
![image](https://user-images.githubusercontent.com/34739130/36765285-6c64bba2-1c6b-11e8-8adc-5d37413bae2a.png)

### Expected behaviour
All can see the icon.

### Actual behaviour
Sync client icons is missing like linux,mac and windows.

### Server configuration
Database:10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04
PHP version:PHP 7.0.22
cloud server:Nextcloud
cloud version: 14.0.0.1 alpha

**Comment by MorrisJobke** [comment]
Let me check that.

**Comment by MorrisJobke** [comment]
Fix is in #8582
