### ISSUE TITLE
Errors when uploading large files via files drop

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#8583]
### Steps to reproduce
1. Install nextcloud
2. Upload .tiff format image file that is 300mb

### Expected behaviour
Tell us what should happen

If it errors out, it should provide some information as to what happened. Nextcloud logs show nothing.

### Actual behaviour
When uploading, it just just displays an exclamation and that's all. Here is a video:

**Video:**
https://streamable.com/txfab

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
Nginx 1.10.3
**Database:**
MariaDB 10.2.13
**PHP version:**
PHP 7.2
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Access.Log**
https://hastebin.com/icifozuyig.log
**Error.Log**
https://hastebin.com/atayoyubey.log
**Nextcloud Config**
https://hastebin.com/ovafuceyuw.php
**Nextcloud Logs**
Blank, nothing in there.

**Comment by MorrisJobke** [comment]
We plan to add a progress bar - see #4164 - and also plan to add chunked public upload - see #4109. A combination of both should fix the problems you have here (low feedback and then a failure).

@nextcloud/designers Could we also make the failure not a popup but show it inline beside the filename?

**Comment by c0fe** [comment]
@MorrisJobke ok but how do I resolve the upload issue? It should still be able to handle the upload, no?

**Comment by MorrisJobke** [comment]
> @MorrisJobke ok but how do I resolve the upload issue? It should still be able to handle the upload, no?

Yes - what is shown for the upload request when you open the web developer tools in your browser and upload the file? The access log doesn't show any upload request :/

**Comment by c0fe** [comment]
@MorrisJobke https://i.imgur.com/nlauigt.jpg

**Comment by skjnldsv** [comment]
@c0fe you're uploading a file too big for your server. You need to increate you client_max_body_size setting in nginx.

**Comment by c0fe** [comment]
@skjnldsv the file size is 300MB the client_max_body_size was set for 512M but it still failed.

**Comment by c0fe** [comment]
@MorrisJobke @skjnldsv ok so this is error message after changing from 512M to 900M:

https://i.imgur.com/PBGG55Z.jpg

**Comment by skjnldsv** [comment]
@c0fe Now you need to increase your php max_execution_time (also check your php max filesize

```
upload_max_filesize = 2M 
;or whatever size you want

max_execution_time = 60
; also, higher if you must - sets the maximum time in seconds

```

**Comment by c0fe** [comment]
@skjnldsv adding this into the nginx.conf comes up to an error:

`root@cloud-mega:/etc/nginx# nginx -s reload
nginx: [emerg] unknown directive "upload_max_filesize" in /etc/nginx/nginx.conf:13`

Nginx Version: 1.12.2

**Comment by skjnldsv** [comment]
@c0fe This is a php config, not nginx :)

**Comment by c0fe** [comment]
@skjnldsv i swear i need more coffee. i am testing this now.

**Comment by c0fe** [comment]
@skjnldsv ok i got this error now:

https://i.imgur.com/AMFNR9V.jpg

**Comment by skjnldsv** [comment]
Same issue, you need to increase max_execution_time again, you set the value at 90 right?

**Comment by c0fe** [comment]
@skjnldsv its some crazy number 90000

**Comment by skjnldsv** [comment]
90 seconds? Not that big :)
You need to have a number bigger than your upload time. I'm not an expert though, maybe it's not the ideal :/

**Comment by c0fe** [comment]
Ok I increased it further:

`; Note: This directive is hardcoded to 0 for the CLI SAPI
max_execution_time = 900000000000000000
`

**Comment by skjnldsv** [comment]
Hum, now this is absolutely crazy, I thought you said you entered 90 (so 90000 ms), but you're supposed to put the value in second, soooo, maybe your number isn't really the best idea ^^'

**Comment by c0fe** [comment]
@skjnldsv the error is now:

https://i.imgur.com/kXQXvlM.jpg

**Comment by skjnldsv** [comment]
You must have another setting that is conflicting with your setup. Or maybe you have an unstable connection :/ @MorrisJobke ?

**Comment by c0fe** [comment]
@skjnldsv anyway i can test the stability of the connection I have?

**Comment by c0fe** [comment]
@skjnldsv @MorrisJobke also whether or not this matters but I am behind a UBNT security gateway

**Comment by c0fe** [comment]
Making a local upload results in the following error:

`core.js?v=dcbba4d1-5:4 PUT https://nextcloud.domain/public.php/webdav/test2.txt 413 (Request Entity Too Large)`

**Comment by MorrisJobke** [comment]
Maybe also a problem in your reverse proxy setup. (see #8695) As this works on many instances out there I would like to get the setup ruled out first. For more help please reach out in the forums first, because this is the bug tracker for real reproducible bugs and not setup issues.

The forum is the perfect place to exchange setup experiences and look into them: https.//help.nextcloud.com

Thanks

**Comment by c0fe** [comment]
@MorrisJobke I have added the items into config but the uploading problem continues to persist:

**config.php:**

https://hastebin.com/adovirolor.php

**site file on reverse proxy:**

https://hastebin.com/lugazojoge.nginx

**Comment by MorrisJobke** [comment]
I haven't seen this connection reset in a reverse proxy setup yet. Maybe something else is interfering here? Could you try without the reverse proxy in front?

**Comment by c0fe** [comment]
@MorrisJobke tried it but it still fails, i have set 9G and 90G in the php.ini file for max size. 300MB file will be fine 700MB fails. I did restart all necessary services and then restarted the whole machine for good measure.

**Comment by MorrisJobke** [comment]
> @MorrisJobke tried it but it still fails, i have set 9G and 90G in the php.ini file for max size. 300MB file will be fine 700MB fails. I did restart all necessary services and then restarted the whole machine for good measure.

post_max_size as well as upload_file_size? We have a few thousand instances out there that work just fine with large files. This needs to be a setup issue. Could you please seek for help in the forums?

**Comment by c0fe** [comment]
@MorrisJobke i can but last few times I did not get a single response, waited about 2 weeks or so before i just gave up hope.

**Comment by c0fe** [comment]
FYI @MorrisJobke I feel that the documentation on the Nextcloud website is outdated, the most obvious appearance is that it has double quotes " and not single quote ' which is in the current version 13 config file.

I would also feel like it can be improved, I would submit a draft but not sure how.
