### ISSUE TITLE
Enable/disable birthday information for auto-generation on server

### ISSUE THREAD

**Issue by oresch** [nextcloud/server#8584]
In the contact app there should be a possibility to enable/disable the birthday information for the server to generate/or not the calendar event.

In my case I got a lot of birthday information in my address book. But I don't want them all to be used for event generation by the server.
Maybe the [closed issue 473](https://github.com/nextcloud/contacts/issues/473) and [504](https://github.com/nextcloud/contacts/issues/504) are pointing in the same direction.

My proposal: add a flag to the birthday field (e.g. on/off) which than afterwards shall be taken into account by the server while generating the calendar events.

**Comment by MorrisJobke** [comment]
This was implemented in 13 by @georgehrke #6884
