### ISSUE TITLE
Moving file/folder: folders in target window sorted different than normal view

### ISSUE THREAD

**Issue by Diamundo** [nextcloud/server#8597]
### Steps to reproduce
1. Have two folders in root, one starting with an underscore
2. Have a file in a folder (not important which one)
3. Press ... on the file
4. Press Move

### Expected behaviour
I expect the folder list to be sorted the same as when I view the folders, i.e. folders starting with an _ underscore in their name to be sorted on the top, sorted alphabetically before without an underscore.
Ex:
- _Admin
- _Organisation
- Admin
- Organisation

### Actual behaviour
When I view the folders normally, the underscored folders are at the top (sorted earlier than without an underscore).  When I move a file, I see the underscored folders at the bottom (sorted later than without an underscore)
Ex:
- Admin
- Organisation
- _Admin
- _Organisation

### Server configuration

**Operating system**:
Ubuntu 16.04 LTS

**Web server:**
Apache

**Database:**
MySQL (?)

**PHP version:**
PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install a few months back, haven't touched it since

**Where did you install Nextcloud from:**
Don't remember.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Could not open input file: occ
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => 'oc2nm2yksvt6',
  'passwordsalt' => 'snip',
  'secret' => 'snip',
  'trusted_domains' =>
  array (
    0 => 'mywebsite.domain',
  ),
  'datadirectory' => '/mnt/hdd/nextcloud',
  'overwrite.cli.url' => 'http://mywebsite.domain/nextcloud',
  'dbtype' => 'mysql',
  'version' => '12.0.4.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_NextAdmin',
  'dbpassword' => 'snip',
  'installed' => true,
);

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 7 64b

**Comment by MorrisJobke** [comment]
Somebody in @nextcloud/javascript could have a look at this? Maybe the sorting in JS and PHP are slightly differently implemented.

**Comment by MorrisJobke** [comment]
We fixed the sorting in the file picker lately. Could you still reproduce this with a newer version?

Works here:

![Bildschirmfoto 2019-03-25 um 14 16 38](https://user-images.githubusercontent.com/245432/54922525-a8182c80-4f08-11e9-8e28-a1f65cd1ad21.png)
