### ISSUE TITLE
Show a message if no secret is set and the user wants to use encryption

### ISSUE THREAD

**Issue by bjo81** [nextcloud/server#8598]
Hi,

I had several issues with the default encryption module because no secret was set (unfortunately NC overwrote config.php with an emply file and I created the config from another install). 

NC shows a lot of warnings about possible problems like missing opcache etc., so maybe it would be great if it would show a warning if somebody tries to enable Server-Side Encryption and no secret is set.

**Comment by shadadougha** [comment]
Are you having issues as seen in #8393 & #8546 ? Just wanting to confirm and consolidate as I'm going through the issues section now.

**Comment by MorrisJobke** [comment]
> I had several issues with the default encryption module because no secret was set (unfortunately NC overwrote config.php with an emply file and I created the config from another install).
> 
> NC shows a lot of warnings about possible problems like missing opcache etc., so maybe it would be great if it would show a warning if somebody tries to enable Server-Side Encryption and no secret is set.

Then those problems should be fixed first and then we can have a look at this. Thus I will close this. If the issue with the encryption still happens, have a look if they are the ones that @molotovkazic linked.

Thanks
