### ISSUE TITLE
Smtp auth failure when sharing a file does not update the sharing list

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#8608]
### Steps to reproduce
1. have an invalid php email set in the additional settings
2. share a directory with a user

### Expected behaviour
- The sharing list is immediately updated and an error message is shown saying 'share added but there was an issue sending the mail'

### Actual behaviour
- Loading icon during 15 sec
- Error saying no mail has been sent 
- Shares list not updated despite the fact that the share has been set

### Server configuration

**Operating system**: Arch

**Web server:** Nginx

**Database:** mariadb

**PHP version:** 7.2

**Nextcloud version:** 13

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

Request log:
`{"ocs":{"meta":{"status":"failure","statuscode":403,"message":"Failed to authenticate on SMTP server with username \"xxxxxxx@xx.xxx\" using 1 possible authenticators"},"data":[]}}`

**Comment by MorrisJobke** [comment]
We shouldn't leak this via our API 🙈 cc @rullzer @nickvergessen

**Comment by MorrisJobke** [comment]
@ChristophWurst

**Comment by nickvergessen** [comment]
For me the API returns `'Failed to send share by mail'`
The named message is only in the logs, which I think is fine.
Relevant code:
https://github.com/nextcloud/server/blob/b93aa586f4636c3863745056ccf0f498fe61ab7f/apps/sharebymail/lib/ShareByMailProvider.php#L346-L374

**Comment by nickvergessen** [comment]
Code is also like this in stable13+ so I'm closing this one year old issue.
Feel free to reopen when you have other steps to reproduce
