### ISSUE TITLE
Save apps state (multitasking)

### ISSUE THREAD

**Issue by sprnza** [nextcloud/server#861]
Hi there!
Thank you for your job and such a great product!
I'd like to propose some feature that would improve NC experience a lot. 
It would be great if NC saves apps state between switches among them. Let's say I'm composing an email in the Mail app, but then suddenly I decide that I need to jot down a note in the Note app, when I switch back to the Mail app I don't have my previous view, but I'd like to have it to be in the same state as it was (email editing or mail queue scroll position restored in the Mail app, or last folder opened in the Files app, or last view in the Calendar app etc).
Especially regarding the Music plugin, if it plays to music I'd like it to proceed doing this through all apps I have. It's pointless to have it without this feature I think.
Just an idea to think of.

Kind regards from Dennis.

**Comment by MorrisJobke** [comment]
This is something that needs to be implemented per application and the server sadly can't do much here -> thus closing this in the server repo.
