### ISSUE TITLE
Moving group folders breaks desktop app sync

### ISSUE THREAD

**Issue by fcovecino** [nextcloud/server#8613]
### Steps to reproduce
1. Install the desktop sync app on Windows 10
2. Sync a group folder
3. Within the group folder create FolderA and FolderB, put some files in FolderB
4. Wait for a successfull sync
5. Move FolderB into FolderA

### Expected behaviour
The subfolder within the group folders should move without issues.

### Actual behaviour
Sync breaks in the Desktop App (locked files error) and the move doesn't occur on the server.
Issue stops if 'filelocking.enabled' => false, is included in config.php
### Server configuration

**Operating system**: 
Shared Hosting (Infomaniak)

**Web server:**
Apache 2.4.25

**Database:**
MySQL 5.7

**PHP version:**
7.1.10
**Nextcloud version:** (see Nextcloud admin page)
13.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:** **Where did you install Nextcloud from:**
Used the eeb Installer from https://nextcloud.com/install/#instructions-server, and updated to 13.0.0 right away.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>
Activity 
2.6.1
Oficial 
Brute-force settings 
1.0.3
Calendar 
1.6.0
Collaborative tags 
1.3.0
Oficial 
Comments 
1.3.0
Oficial 
Contacts 
2.1.1
Deleted files 
1.3.0
Oficial 
File sharing 
1.5.0
Oficial 
Group folders 
1.2.0
Impersonate 
1.0.2
Log Reader 
2.0.0
Oficial 
Monitoring 
1.3.0
Oficial 
Nextcloud announcements 
1.2.0
Oficial 
Notifications 
2.1.2
Oficial 
Password policy 
1.3.0
Oficial 
Passwords 
2018.2.1
PDF viewer 
1.2.0
Oficial 
RainLoop 
5.0.6
Share by mail 
1.3.0
Oficial 
Text editor 
2.5.1
Oficial 
Theming 
1.4.1
Oficial 
Update notification 
1.3.0
Oficial 
Usage survey 
1.1.0
Oficial 
Versions 
1.6.0
Oficial 
Video player 
1.2.0
Oficial 

</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

<?php
$CONFIG = array (
  'instanceid' => 'ocuibez3bb2k',
  'passwordsalt' => ,
  'secret' => ,
  'trusted_domains' => 
  array (
    0 => ,
  ),
  'datadirectory' => '/home/clients/6e8d22f5e2b17bb66c0a929188182f19/NubeXubium/data',
  'overwrite.cli.url' => ,
  'dbtype' => 'mysql',
  'version' => '13.0.0.14',
  'dbname' => '',
  'dbhost' => '',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'updater.release.channel' => 'stable',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'no-reply',
  'mail_domain' => '',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.infomaniak.com',
  'mail_smtpport' => '587',
  'mail_smtpname' => '',
  'mail_smtppassword' => ,
  'mail_smtpsecure' => 'tls',
  'default_language' => 'es',
);


</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no


### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 10
### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>


</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
[nextcloud.log](https://github.com/nextcloud/server/files/1772591/nextcloud.log)


</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
@icewind1991 @rullzer

**Comment by rullzer** [comment]
The desktop client doesn't care if something is a group folder or not (there is no notion of group folder in the desktop code). It just performs a webdav move.

Can you reproduce the issue on the web?

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Comment by fcovecino** [comment]
Hello. The issue stopped happening after an update. Sorry I didn't mention it here.
Best regards.
