### ISSUE TITLE
Github Issue Template: documenation outdated?

### ISSUE THREAD

**Issue by christian-weiss** [nextcloud/server#8620]
When i file an issue at github a template text is displayed. This texts points to external documenation:
https://apps.nextcloud.com/apps/issuetemplate
which states that there is a "Issue Reporting" navigation menu entry for nextcloud admins. But this menu item is missing in nextcloud 13.0.0.

Please update the documentation.

**Comment by christian-weiss** [comment]
![adminsettings](https://user-images.githubusercontent.com/1694741/36890483-51e093e8-1dfe-11e8-9bd8-5f1d3a534160.JPG)

**Comment by juliushaertl** [comment]
Did you install the issuetemplate app from the app store? It works fine here on NC13. Anyway this is more an issue for the app repo at: https://github.com/nextcloud/issuetemplate
