### ISSUE TITLE
Can not to upload avatar after upload one picture right now ,must reload the page first.

### ISSUE THREAD

**Issue by supermanlinux** [nextcloud/server#8623]
### Steps to reproduce
1.go to personal settings page
2.click the upload button and select an image
3.after the image is complete
4.if you want to change avatar,if you don't reload page first,you can't upload image,the upload buttoon is disabled.If you click the delete button,then you click the upload button,it's the same.

### Server configuration
Database:10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04
PHP version:PHP 7.0.22
cloud server:Nextcloud
cloud version: 14.0.0.1 alpha

**Comment by ChristophWurst** [comment]
Hey, @supermanlinux!

@LEDfan has submitted a pull request at https://github.com/nextcloud/server/pull/10833. Could you check that out and test if it fixes your issue? Thanks :v:
