### ISSUE TITLE
External storage (FTP): Many errors when encryption enabled

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/server#8624]
### Steps to reproduce
1. Enable encryption
2. Enable external storage support
3. Add external storage (FTP) with encryption enabled. I use an FTP server of the German webhoster All-Inkl.
4. Try to upload file to external storage

### Expected behaviour
The upload should work without any problems.

### Actual behaviour
The upload is very slow.
The actual problem is, that many error messages are logged ("fseek(): stream does not support seeking..."). The upload of only one file produced a log file of ~380KB. The error message is always the same, so I only pasted some line of the log (see below).
The upload succeeds somehow and I can open the file (jpeg), the preview is shown, etc., but everything is very slow.

When I mount the external FTP storage with encryption disabled, everything works as expected, so the issue seems somehow related to different handling when encryption is enabled on external storage.

## Server configuration detail

**Operating system:** Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64

**Webserver:** nginx/1.13.9 (fpm-fcgi)

**Database:** mysql 10.2.13

**PHP version:** 7.0.25-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Fresh install

**Where did you install Nextcloud from:** 
Official homepage (https://download.nextcloud.com/server/releases/nextcloud-13.0.0.tar.bz2)

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - comments: 1.3.0
 - dav: 1.4.6
 - encryption: 2.0.0
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.178.60"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/192.168.178.60\/nextcloud",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "13.0.0.14",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "logtimezone": "Europe\/Berlin",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    }
}
```
</details>

**Are you using external storage, if yes which one:** 
FTP

**Are you using encryption:** 
Yes

**Are you using an external user-backend, if yes which one:**
No

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Operating system:** 
Win10

## Logs

<details><summary>Webserver log</summary>
No webserver logs showing any related issues.

</details>

<details><summary>Nextcloud log</summary>

{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"zHTAWWrNIGmyNON8bEcX","level":3,"time":"2018-03-02T11:25:36+01:00","remoteAddr":"192.168.178.113","user":"Admin","app":"PHP","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/FTP\/IMG_20180226_174412.jpg","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}

</details>

**Comment by tflidd** [comment]
Similar error with SMB external storage: https://github.com/nextcloud/server/issues/3691
FTP and other external storage: https://help.nextcloud.com/t/fseek-stream-does-not-support-seeking-at/14268

**Comment by DecaTec** [comment]
Yes, I already found these, but there it seems to be related to SMB somehow. The suggestions there are to wait for NC 12.0.3 and 13 (I'm on 13 right now) and to use something like `sudo apt-get install php-smbclient`. 
Im my case this wouldn't help with external FTP storage.

The question now is: Is it a general problem? See the commend by @icewind1991 [here](https://github.com/nextcloud/server/issues/3691):

> fseek should be avoided where possible since multiple external storage backends to do not support seeking on streams.

This is only my (fresh) test installation of NC 13, so if I can support in any way (code changes to test, etc.), just tell me. I would be happy if external FTP storage would work with encryption enabled.

**Comment by tflidd** [comment]
@icewind1991 @schiessle ideas? More information from user needed?
