### ISSUE TITLE
CalDav: Label "Personal" not translated wenn new calendar added to sharees

### ISSUE THREAD

**Issue by daCaPo** [nextcloud/server#8626]
### Steps to reproduce
1. Create a new user (calendar "Personal" gets automatically created, labeld "Persönlich" in the German UI)

2. Share this calendar with another user or group with a German/non-English UI language

### Expected behaviour
The sharee should see the calendar title translated just like the owner (e. g., "Persönlich (Name)" in German)

### Actual behaviour
The calendar is shown as "Personal (Name)", wich might be misleading when using NextCloud in a company that runs an HR department ;-)

### Server configuration

**Database:**
MySQL

**PHP version:**
7.0

**Server version:** (see your admin page)
13.0.0

**Calendar version:** (see the apps page)
1.6.0

**Comment by juliushaertl** [comment]
Not sure if that is possible from the current implementation. Maybe @georgehrke has an idea.

**Comment by georgehrke** [comment]
It should be, because the server only stores the displayname "Personal" and replaces it on the fly with the localized version for the owner.
