### ISSUE TITLE
SVG-logos provided via theming can not be rendered in mail-clients

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#8627]
https://github.com/nextcloud/server/issues/4647 fix is not working if you have provided your own SVG-logo via `theming`-app.

As discussed @juliushaertl 😉

**Comment by MorrisJobke** [comment]
@juliushaertl Do we already render the custom logos as PNG?

**Comment by juliushaertl** [comment]
@MorrisJobke No, we need to store a PNG version of the logo and serve that if requested.

**Comment by MorrisJobke** [comment]
> @MorrisJobke No, we need to store a PNG version of the logo and serve that if requested.

Should be possible with something like the preview stuff that @rullzer did. ;)
