### ISSUE TITLE
Cannot dismiss'invalid private key for encryption app' dialog

### ISSUE THREAD

**Issue by brylie** [nextcloud/server#8637]
When the *default encryption app* is enabled  and a user changes their password, a message is displayed along the top of the screen:

> Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files.

# Steps to reproduce
1. enable the *default encryption app*
2. create a test user
3. change the test user's password (e.g. from an administrative use)
4. log in with the test user on a small device
5. try to navigate around the platform

# Expected behaviour
One or more of these conditions should happen:

- when changing the user password, the *private key for the Encryption App* should also be updated
- clicking or touching the dialogue should take the user to the settings field for the *private key for the Encryption App*
- the user should somehow be able to dismiss the notification message, so they can navigate the portal

# Actual behaviour
The displayed message does not contain a link to the settings page, nor can it be dismissed. It actually blocks the menu bar on smaller displays, making it impossible to access parts of the platform.

# Server configuration

**Operating system**: Ubuntu 16.04

**Nextcloud version:** 13.0.0

**Comment by MorrisJobke** [comment]
> @brylie looks to be a duplicate of #8546 as I too am seeing the same behavior.

Let's close it as duplicate of #8546
