### ISSUE TITLE
Add a name for authenticating device

### ISSUE THREAD

**Issue by tushevorg** [nextcloud/server#8639]
### Steps to reproduce
1. Install iOS app
2. Log in with OAuth? (the first option, not by application password)
3. Go to Settings -> Security in browser

### Expected behaviour
I'd like to specify a name for the device, i.e. 'Hanna's iPhone' on the authentication screen, like it is possible when creating app password.

### Actual behaviour
I see lots of 'iOS Client Nextcloud' devices and it's hard to figure which one exactly should I remove (if necessary to do so).

### Server configuration

**Nextcloud version:** 13.0.0

**Comment by splitt3r** [comment]
I´m doing this at db level. But the problem is that the user agent is used to show the device icon in Nc 14.

**Comment by e-alfred** [comment]
It would be great if it contains more information like IP address, Client type/OS, etc. no just for iOS.

**Comment by MorrisJobke** [comment]
@rullzer Didn't you had the idea of better readable names as well as having a type as well as a name and not only the user agent stored in the DB?

**Comment by ChristophWurst** [comment]
Another reason to upgrade to Nextcloud 16: https://github.com/nextcloud/server/pull/13702 :rocket:
