### ISSUE TITLE
Errors from MailPlugin.php when trying to share files

### ISSUE THREAD

**Issue by jthomasdewald** [nextcloud/server#8641]
### Steps to reproduce
1. Log into web-client
2. Use File browser
3. Use the Share Icon to share a file (any file)
4. Begin to type the name of a user to share the file with

### Expected behaviour
The name / email lookup from MailPlugin.php should find users without errors

### Actual behaviour
My logs are littered with ERRORS from PHP, specifically:

- Undefined index: FN at /var/www/owncloud/lib/private/Collaboration/Collaborators/MailPlugin.php#163
- Undefined index: FN at /var/www/owncloud/lib/private/Collaboration/Collaborators/MailPlugin.php#150

Those two lines are looking for a key/value 'FN' presumably from IManager.php
My best guess is that I have (many) contacts that don't have a Full Name in their contact cards, and MailPlugin is throwing a fit. Is this intended?

### Server configuration

**Operating system**:
Raspbian Jessie

**Web server:**
Apache/2.4.25

**Database:**
MySQL

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
13.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Repository

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
No errors have been found.

**List of activated apps:**
  - activity: 2.6.1
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_frommail: 0.1.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0

**Nextcloud configuration:**
{
    "system": {
        "updatechecker": "true",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "1ni.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/1ni.org\/owncloud",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Los_Angeles",
        "installed": true,
        "loglevel": 2,
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "filesystem_check_changes": 1,
        "filelocking.enabled": true,
        "session_lifetime": 3600,
        "session_keepalive": false,
        "check_for_working_htaccess": true,
        "log_rotate_size": 5242880,
        "enable_previews": true,
        "preview_max_x": 256,
        "preview_max_y": 256,
        "preview_max_scale_factor": 1,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": true,
        "theme": "",
        "updater.release.channel": "stable"
    }
}


**Are you using external storage, if yes which one:** local/smb/sftp/...
Local

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox

**Operating system:**
Win 10

#### Browser log
<details>
<summary>Browser log</summary>

**Comment by blizzz** [comment]
@georgehrke @schiessle is it possible having a contact card without FN? In the local addressbook.

**Comment by georgehrke** [comment]
Yes, if the displayname is not set 
https://github.com/nextcloud/server/blob/d1fb939e863a6f476d3a0a49d6d9717ff0d713a0/apps/dav/lib/CardDAV/Converter.php#L80

**Comment by blizzz** [comment]
Fix in https://github.com/nextcloud/server/pull/8822, @jthomasdewald can confirm it's fixing it?

**Comment by jthomasdewald** [comment]
@blizzz Thanks for the update. will re-enable sharing via email address this weekend and report back

**Comment by jthomasdewald** [comment]
@blizzz no issues with the fix. Able to share files (via email) with contacts and no errors in the log.

**Comment by blizzz** [comment]
@jthomasdewald thanks for testing :)

**Comment by Commifreak** [comment]
Excuse me, but this is still the case for me:

NC 18.0.7:

`Undefined index: FN at /var/www/html/lib/private/Collaboration/Collaborators/MailPlugin.php#157`. Anything I can check?
