### ISSUE TITLE
Show warning if memory limit is below 512 MB (on CLI and setup check)

### ISSUE THREAD

**Issue by Temtaime** [nextcloud/server#8642]
### Steps to reproduce
1. run sudo -u nginx ./occ files:scan --all

### Expected behaviour
It should pass OK. Or warn if memory limits are too low.

### Actual behaviour
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 37748736 bytes) in /var/www/html/lib/private/Lock/DBLockingProvider.php on line 77
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes) in /var/www/html/lib/private/Lock/DBLockingProvider.php on line 268

### Server configuration

**Operating system**:
CentOS

**PHP version:**
7.1 with default 128M memory limit

**Nextcloud version:** (see Nextcloud admin page)
13.0

**Comment by realies** [comment]
following

**Comment by MorrisJobke** [comment]
> It should pass OK. Or warn if memory limits are too low.

Yes - will add a warning in the admin settings and a warning in the occ output.

**Comment by weeman1337** [comment]
I'm now trained in doing setup checks :) and will have a look.
