### ISSUE TITLE
Request: allow app installations / credentials to be federated

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#8643]
[As mentioned here on the Nextcloud Help forum.](https://help.nextcloud.com/t/radical-idea-for-federated-apps-add-app-via-remote-credentials-rather-than-install-locally/28054) 

**What?**
I’d like to deduplicate and add existing remote applications to my local instance of Nextcloud.
![c1df7e1b-7d4d-4403-bcd4-8e97a4aea891](https://user-images.githubusercontent.com/1787238/36947920-735e93aa-1f87-11e8-8e0d-8fa8c1b54fcf.png)

It could also make sense to run multiple instances of the same app (such as activity) with different credentials on the same instance.
![50bb093a-7bd1-4577-9c1e-fbb4ee8fd76b](https://user-images.githubusercontent.com/1787238/36947942-d5fb9ddc-1f87-11e8-906d-ea2cdd616477.jpeg)

**Why?**
I administer multiple instances with hosted apps (Bookmarks, Tasks, Calendars) that I’d like accessible within my localhost only instance.

Instead of regular installation and setup, I can just add my remote account url, user name and password credentials in the appstore for the specific app. Passwords could easily be generated as one time. Header displayed will still appear to be that of my local instance. Has this been discussed?

- Some admins would might want to be able to revoke app access remotely
- others would want to mirror apps locally to guarantee uptime and allow access in a localhost environment should overall internet access be unavailable.

**Why?**
Right now [I’m mounting the external instance app as a url within External Sites app as explained in CustomCSS Issue #5 ](https://github.com/juliushaertl/theming_customcss/issues/5)and hoping to flesh it out with [the possibly less desirable issue #82 that would allow unprivileged users to mount their own external pages](https://github.com/nextcloud/external/issues/82).  Then [I’m adding the relevant icon manually as described in External Sites App Issue #81](https://github.com/nextcloud/external/issues/81), but this is just a hack as shown in Server Issue #8413

**Comment by marcelklehr** [comment]
> I administer multiple instances with hosted apps (Bookmarks, Tasks, Calendars) that I’d like accessible within my localhost only instance.

What advantage do you see with accessing an app on a different instance in another instance?

**Comment by MorrisJobke** [comment]
sounds super complex. May I have feedback from @schiessle @nickvergessen @rullzer @karlitschek @blizzz ?

**Comment by nickvergessen** [comment]
Yeah, also mostly impossible with apps, as soon as they listen to hooks and stuff...

I don't think we want to federate one server into multiple... federation we have now is already complicated enough.

**Comment by Mannshoch** [comment]
similar:
https://help.nextcloud.com/t/setting-up-a-main-controlling-nextcloud-when-you-have-multiple-servers-with-multiple-apps/143374
