### ISSUE TITLE
Ability to decrypt files from external storages (Dropbox)

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#8644]
Hello!

I was guided here from the official forums (https://help.nextcloud.com/t/decrypt-dropbox-files/28189).

Some time ago, Dropbox dropped its support for OAuth v1. If there was encrypted data stored on the Dropbox, it is, as of now, not possible to (easily) recover these files.

There should be a decryption tool integrated into Nextcloud that is capable of decrypting encrypted files, even if the Nextcloud server was updated or it is not possible to mount the external storage into Nextcloud itself.

Regards,
xenophil90

**Comment by MorrisJobke** [comment]
cc @nextcloud/encryption

**Comment by jknockaert** [comment]
I have been thinking before that there should be a standalone decryption tool, perhaps in the format of a php script that can be run in a command line environment.

**Comment by MorrisJobke** [comment]
> I have been thinking before that there should be a standalone decryption tool, perhaps in the format of a php script that can be run in a command line environment.

@schiessle DIdn't you looked into something like that?

**Comment by the-sane** [comment]
@MorrisJobke @schiessle the tool being discussed here now exists:

@yahesh has recently created a php script that decrypts individual files: https://github.com/syseleven/nextcloud-tools/blob/master/decrypt-file.php

Maybe it can be integrated?

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
