### ISSUE TITLE
System requirements regarding database contradict themselves

### ISSUE THREAD

**Issue by mauricemeyer** [nextcloud/server#8645]
This is not an issue within the software itself (maybe not), but with either the documentation or the requirements:

# System Requirements
[The system requirements for version 13](https://docs.nextcloud.com/server/13/admin_manual/installation/system_requirements.html#database-requirements-for-mysql-mariadb) specify:

- Disabled or BINLOG_FORMAT = MIXED configured Binary Logging
- “READ COMMITED” transaction isolation level

# MySQL manual
[The MySQL 5.7 manual](https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-isolation-levels.html) (I'm using percona, but the same applies here) states:
"If you use READ COMMITTED, you must use row-based binary logging. "

So, is there an error in the NextCloud 13 requirements or are the instructions indeed contradictory?

Specifically, is Nextcloud specifying to use MIXED binary logging simply to increase performance on statements where row logging would cause a significant amount of binlog entries or is there an actual technical necessity to it?

**Comment by MorrisJobke** [comment]
cc @nickvergessen @oparoz

**Comment by nickvergessen** [comment]
READ COMMITED is required, that's what I know.

The other thing was in the manual before, but I don't know any reason...

**Comment by mauricemeyer** [comment]
Then we should definitely change the documentation to have the correct BINLOG_FORMAT.

**Comment by mauricemeyer** [comment]
Closing this as per merge of https://github.com/nextcloud/documentation/pull/703
