### ISSUE TITLE
shared with you - should include the sharer's name or a folder for each sharer.

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#8646]
12.0.5
in the "shared with you" folder all folders and files shared from other users are displayed.
It would be helpful to be able to see immediately the sharer either by
- adding the sharers name to the file/folder name or
- creating a folder for each sharer.

thank you

---
sorry I didn't see the sharer on the very right side of the screen - IMO it should be more visible 

The Linux client does not show the sharer at all - so having a sub folder for each share would solve this problem

**Comment by MorrisJobke** [comment]
This was done in 13 (see #7222):

<img width="964" alt="bildschirmfoto 2018-03-05 um 10 23 06" src="https://user-images.githubusercontent.com/245432/36967335-bb546800-205f-11e8-8649-bcbd89cfe359.png">

**Comment by ferdiga** [comment]
sorry, this does not help for the client sync - hence I suggest a folder for each sharer

**Comment by MorrisJobke** [comment]
> sorry, this does not help for the client sync - hence I suggest a folder for each sharer

This was about the web UI, because the "shared with you" is only shown there. The client does not know about this page. For this other feature: please open a separate feature request.

**Comment by ferdiga** [comment]
IMO the structure on the server WEB-UI and the client - sync should be the same.

**Comment by MorrisJobke** [comment]
> IMO the structure on the server WEB-UI and the client - sync should be the same.

But those are filtered views. The main file view is actually the same.

**Comment by ferdiga** [comment]
in the root directory I have a "shared" folder, and in this shared folder all shared files are listed here,
my suggestion would be to create a sub-folder for each sharer - this would work for web and client sync

**Comment by MorrisJobke** [comment]
> in the root directory I have a "shared" folder, and in this shared folder all shared files are listed here,
> my suggestion would be to create a sub-folder for each sharer - this would work for web and client sync

Please open a new ticket with this feature request, because this ticket was about adding the shared with owner information.
