### ISSUE TITLE
When using autoconfiguration, the first person to access the instance gets admin access to it

### ISSUE THREAD

**Issue by mauricemeyer** [nextcloud/server#8653]
When using the autoconfiguration, at the first page visit, the configuration is executed, the database tables are created and the setup is finished. 

The first visitor then gets automatically logged in as the created administrative user.

### Steps to reproduce
1. Download nextcloud and extract it
2. Deploy the nginx configuration as described in [the documentation](https://docs.nextcloud.com/server/13/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx)
3. Create and autoconfig file according to [the documentation](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/automatic_configuration.html#all-parameters)
4. Access the nextcloud instance.

If there is need for any more information, I can reproduce this in instants as the installation is executed by ansible.

### Expected behaviour
nextcloud should be automatically configured and after configuration present the login screen to all visitors.

### Actual behaviour
nextcloud runs the configuration, configures its database and then logs the visitor in as the created admin user - which in my opinion is a security issue.

Also, there are file integrity warnings for `.htaccess` and index.html` as seen below. Those do not occur when I don't create the `autoconfig.php` and set the values manually.

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** nginx 1.10.3

**Database:** Percona, percona-server-server 5.7.21-20-1.xenial

**PHP version:** PHP-FPM 7.2.2-3+ubuntu16.04.1+deb.sury.org+1

**Nextcloud version:** Nextcloud 13.0.0 (autogenerated config says `13.0.0.14`)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-13.0.0.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- index.html
	- EXTRA_FILE
		- appdata_ocvmu4gxuvnn/appstore/apps.json

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => da8e0075f23227b107fc705aa1b20378107d3a1c195d96ed13e5f4f25c38d6c660aab75be183ae5799a4ff7eae0ea739a14c944430ee8bb9e9a824235aa136eb
                            [current] => 0b1e075e4007b72ef73e0d464aefd0c6528cd58820b4db7e11c1a8db0aeb01f9237c197fccfe41d54337d7744fb7e64ab71f57130d5e89faa8ee42a69af423a5
                        )

                    [index.html] => Array
                        (
                            [expected] => 27792cd8c483a51322e0d2b91668af80ea0943711cdfc57d7d13a91165e6a9e3f3c7d7a0b62e5eec37ce2799efe8363a7a9b31087e7b7e2ddf0d84af8b1997c8
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [appdata_ocvmu4gxuvnn/appstore/apps.json] => Array
                        (
                            [expected] => 
                            [current] => fa7a749508eac6a07638baf666fe3580ce7892f79697102f8ba98462ff8a41f21278d4400fc9d4d7b7dfb089441895164ef86920f130dc43b9285fb2042e0be9
                        )

                )

        )

)

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUVE***",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[log is empty]
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[log is empty]
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
[nothing relevant]
```
</details>

#### autoconf.php
<details>
<summary>autoconf.php file</summary>

```
<?php
$AUTOCONFIG = array(
  "dbtype"        => "mysql",
  "dbname"        => "kuha_space",
  "dbuser"        => "kuha_space",
  "dbpass"        => "***REDACTED***",
  "dbhost"        => "10.0.0.10",
  "dbtableprefix" => "",
  "adminlogin"    => "maurice",
  "adminpass"     => "***REDACTED***",
  "directory"     => "/var/www/kuha.space/nextcloud",
);

``` 
</details>

**Comment by MorrisJobke** [comment]
This is by intention. The first user in the web installer is always admin. If you don't want this, then use the `occ maintenance:install` command to install the instance and provision the users accordingly.
