### ISSUE TITLE
Allow admin to create device tokens on behalf of users

### ISSUE THREAD

**Issue by K-spacer** [nextcloud/server#8658]
It would be nice if an administrator could create device passwords on behalf of users, to facilitate automounting of the webdav space across shared systems, e.g. a compute cluster.

Cheers,
Ben

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @rullzer @nickvergessen is this even possible? We need the password of the user, right?

cc @nextcloud/security

**Comment by nickvergessen** [comment]
Not really I think, because we need the actual user password.
That is also the reason why it doesn't work with impersonate atm

**Comment by rullzer** [comment]
yep you need the password.

**Comment by K-spacer** [comment]
Aha ... so changing your password in an LDAP backend breaks device passwords. Is this intended behaviour?

**Comment by ChristophWurst** [comment]
Yes, it is. App passwords get invalidated when the login password changes.

**Comment by nickvergessen** [comment]
Closing as per above

**Comment by K-spacer** [comment]
OK. Thanks for clarifying!
