### ISSUE TITLE
shared with me - folder for each sharer

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#8660]
12.0.5
in the root directory I have a "shared" folder, and in this shared folder all shared files are listed,
my suggestion would be to create a sub-folder for each sharer - this would work for web and client sync
in the web client you can see the sharer 
https://github.com/nextcloud/server/issues/8646

the linux client syncs the "share with you" in ONE folder - I suggest to have a sub folder for each sharer.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers Would this make sense?


cc @nextcloud/sharing for input as well.

**Comment by MorrisJobke** [comment]
Basically extending the `share_folder` setting in config.php to also include the user display name. Something like `Shared/Morris Jobke` for all shares from me and `Shared/Roeland Douma` for all shares from Roeland.

**Comment by ferdiga** [comment]
suggestion would be good
to discuss
* change of display name - better use login name? - it's unique, but sometimes not user friendly!
* how to handle already synced shared files/folders or display name
  these must be moved to the new location/name.

**Comment by jancborchardt** [comment]
Design-wise it doesn't really make sense. How about group shares where there's no real owner (only an original creator)? We highlight this creator far too much even though shares are often topic-based.

**Comment by MorrisJobke** [comment]
> change of display name - better use login name? - it's unique, but sometimes not user friendly!

Not at all - if you have connected an LDAP it's basically a random number/character string.



> Design-wise it doesn't really make sense. How about group shares where there's no real owner (only an original creator)? We highlight this creator far too much even though shares are often topic-based.

I fully agree here.

**Comment by ferdiga** [comment]
probably it would be helpful to label or tag shares to allow the user to set where these should show up related to HIS organisation of topics. (like linux links)

**Comment by jancborchardt** [comment]
Sorry, all of these requests sound very specific and we would need to introduce a bunch of specific settings here.

Currently you can already filter shares via the left navigation. To have the person-filter, it might be nice to have an entry in the user popover to "Show shares with `name`".

**Comment by ferdiga** [comment]
well I try to suggest a solution which works for the client sync - 
the file system on the desktop PC should indicate the sharer.

**Comment by jancborchardt** [comment]
Closing this as we won’t proceed with the suggested solution. We could possibly integrate with the Contacts menu, or Contacts app itself, to show shares with people there.
