### ISSUE TITLE
[BUG] Login without Chat Remains - Minor

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#8665]
### Steps to reproduce
1. Install Nextcloud Talk chat app via browser and as admin
2. Remove Nextcloud Talk chat app
3. Logout

### Expected behaviour
The link "Login without chat" should be removed after Nextcloud Chat is removed

### Actual behaviour
Link remains

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
NGiNX 1.10.3
**Database:**
10.2.x
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
zip
**Browser**
Chrome 64.0.3282.186 (latest as of posting). I also did clear cache and everything in the browser.
**Screenshot**
https://i.imgur.com/sMmveoj.png

**Comment by MorrisJobke** [comment]
This seems to be a problem of the JSXC chat app - please report there https://github.com/nextcloud/jsxc.nextcloud/issues

Could be related to #5832 nevertheless and I will have a look at this ticket now.

**Comment by elvisef** [comment]
It is also very similar to https://github.com/nextcloud/jsxc.nextcloud/issues/97 though.
