### ISSUE TITLE
AD/LDAP sharing only in group not working.

### ISSUE THREAD

**Issue by djwho** [nextcloud/server#8694]
I noticed that after update to nextcloud 13 sharing menu(autocompletion works fine) shows only users in logged user group but only respect local groups if user is in AD/LDAP it shows all users. Also if i put whole name i can share file with any user (no difference local or LDAP) how to prevent this? This reveal users names to logged user (you can try few user names to check if user is part of nextcloud instance), but shouldn’t show user that is not part of the group even whole name is typed.
I think LDAP group problem is because any user is in Domain Users group and option to exclude group from Domain Users not working.
How to fix this? Cheers and thanks for any support.

**Comment by blizzz** [comment]
> I noticed that after update to nextcloud 13 sharing menu(autocompletion works fine) shows only users in logged user group but only respect local groups if user is in AD/LDAP it shows all users

Do I understand correctly, that the share dialogue shows all users belonging to the groups of the logged in user? This is how it should be.

>  Also if i put whole name i can share file with any user (no difference local or LDAP) how to prevent this?

There we have an exact match and this would be a bug indeed. Can I ask you to try again with 13.0.1 (should be out now) since we had some fixes in this area since.

> I think LDAP group problem is because any user is in Domain Users group and option to exclude group from Domain Users not working.

The group must be excluded through per LDAP configuration.

**Comment by djwho** [comment]
1. Yes it works but only for local groups not LDAP groups
2. Ok I'll try updated 13.0.1
3. What do You mean  per LDAP, where? Wy excluding Domain Group from shareing in Nextcloud doesn't work?

**Comment by blizzz** [comment]
1. why wouldn't it, it goes through the same API
2.  keep us posted :)
3. the group tab https://docs.nextcloud.com/server/13/admin_manual/configuration_user/user_auth_ldap.html#groups-tab If you include the "Domain Users" group and essentially every user is inside there, it's effectively like unlimited sharing.

**Comment by djwho** [comment]
Nextcloud 13.0.1

Logged as someuser that is not in the same group as otheruser:
- seems now if i put exact name *e.g. otheruser) no user is displayed   - this is now good 
- but if i put a name as an email format/with domain (e.g. otheruser@mydomain.com) nextcloud shows this like this is found (with logo/avatar) this could be misleading that we can share with this user
-this happens also if i put nonexistinguser@mydomain.com 

If
specialuser is in domain users and othergroup 
- i can share even if domain users excluded form sharring (because user is in othergroup not excluded from sharring)
- but if then i remove specialuser form othergroup (in ActiveDirectory backend) need to reenable excluding from domain users to get it work other wise still sharing button is visible, if i reenable excluding sharing button disapears (after next specialuser logon)

Also sadly I still don't understand why excluding domain user group from sharing is not excluding this group from sharing as mentioned, isn't this misleading?
Also link You provide describes what groups are available in nexcloud not which are able to share. 
Maybe i'm missing something if so can You please give me an example how configure this?
At this GROUP tab i can't exclude group only include but i need just exclude one group and include many many groups. Thanks in advance for any help.

**Comment by blizzz** [comment]
> but if i put a name as an email format/with domain (e.g. otheruser@mydomain.com) nextcloud shows this like this is found (with logo/avatar) this could be misleading that we can share with this user
-this happens also if i put nonexistinguser@mydomain.com

sounds like mail-/federated shares as they basically validate by pattern. Is there anything in brackets at the end of the shown name/address?
