### ISSUE TITLE
[BUG] Clean Nextcloud Install No Logos or Theming

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#8695]
### Steps to reproduce
1. Install Nextcloud

### Expected behaviour
Logo and background (installed by default) should appear

### Actual behaviour
Nothing appears

### Server configuration

**Operating system**:
Ubuntu 16.04 LTS

**Web server:**
NGiNX 1.12.2
**Database:**
MariaDB 10.2.13
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
Zip

**Browser:**
Chrome 64.0.3282.186

**Screenshots:**

https://i.imgur.com/gmdi3So.png
https://i.imgur.com/2szR7iR.png
https://i.imgur.com/MRcZ0x6.png

**Installation Commands:**

https://hastebin.com/yanekocifa.exp

**NGiNX Access Log:**

https://hastebin.com/ihozucaqix.log

**NGiNX Error Log:**

https://hastebin.com/cakasoqedo.vbs

**Nextcloud Log:**

Empty

**Chrome Dev Tools**

https://hastebin.com/nanukatesa.log

**Comments**

It would appear that this is blocked for some reason by the browser.

**Comment by MorrisJobke** [comment]
Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".

login:1 Refused to load the image 'http://nextcloud.domain.com/core/img/background.png?v=0' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".

**Comment by MorrisJobke** [comment]
Is the instance served via https? And maybe the overwrite URL in the config.php is set wrongly to the http version. Please provide the config.php values.

**Comment by c0fe** [comment]
@MorrisJobke https://hastebin.com/geyulofifa.php

**Comment by MorrisJobke** [comment]
> @MorrisJobke https://hastebin.com/geyulofifa.php

And how do you browse the website? Via http or https?

**Comment by MorrisJobke** [comment]
Just seen it in a screenshot: it's https - then update this line and it should work again: "'overwrite.cli.url' => 'http://nextcloud.domain.com'," (should be https instead of http).

**Comment by c0fe** [comment]
@MorrisJobke a reverse proxy converts it to HTTPS

**Comment by MorrisJobke** [comment]
For more details which config options need to be set in a reverse proxy setup: https://docs.nextcloud.com/server/13/admin_manual/configuration_server/reverse_proxy_configuration.html

For this kind of stuff the forum at https://help.nextcloud.com is a better place, because this is not a bug but a configuration issue.

Thanks :)

**Comment by c0fe** [comment]
@MorrisJobke but i have one nextcloud instance that didn't run into this issue and one that did, both using the same reverse proxy config. what did i do wrong?

**Comment by MorrisJobke** [comment]
> @MorrisJobke but i have one nextcloud instance that didn't run into this issue and one that did, both using the same reverse proxy config. what did i do wrong?

As pointed out: you are missing the setup for the reverse proxy. Read the linked document page for more details. Also your reverse proxy should set the correct headers (also listed in this document).

This is also the bug tracker for reproducible bugs in the software. Sorry that I need to send you over to the forums, but we need to keep the bug tracker in a shape to be able to work on bugs and not to answer questions about setup details. We also try to include as many feedback right into the software.

I hope you understand this.

**Comment by c0fe** [comment]
@MorrisJobke sure but I did follow that instructions and it just resulted in errors. But Ok.
