### ISSUE TITLE
need a group or folder for all user

### ISSUE THREAD

**Issue by Cathgao** [nextcloud/server#8698]
everytime create a new account i have to put the new user into a group to let him see the folder i share. it is too boring!
i want to creat some folder that everyone can see without adding to a group by me.

**Comment by MorrisJobke** [comment]
Basically a share to everyone? I don't know if that makes sense at all. Maybe ask in the group folder app if this can be integrated, but in the servers core this does not really fit into our sharing model (share by user, group, circle, email, link, ...).

The group folders app can be found here: https://github.com/nextcloud/groupfolders

And it would make most sense to integrate it there.
