### ISSUE TITLE
[search] X overlap search phrase

### ISSUE THREAD

**Issue by hoellen** [nextcloud/server#8701]
### Steps to reproduce
1. Go to any app that support search
2. Search with a very long search phrase (e.g. "very long search phrase")

### Expected behaviour
The entered text is complete readable. 

### Actual behaviour
The "X" (to delete the entered text) overlaps the entered search phrase.
 
![grafik](https://user-images.githubusercontent.com/11299996/37076962-0709c78e-21d9-11e8-8ae8-d27f8b8068b2.png)

### Server configuration

**Nextcloud version:** 13.0.0

**Firefox version:** 58.0.2

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers
