### ISSUE TITLE
"Your apps" does not show available updates

### ISSUE THREAD

**Issue by boldt** [nextcloud/server#8703]
I am running the docker-container with version 13.0.0.
Wrt. to #6740, "Your apps" should show, that updates are available.

Right now, I am missing my calendar and my contacts app, and now updates are shown.

![bildschirmfoto vom 2018-03-07 09 31 47](https://user-images.githubusercontent.com/750793/37081655-70abd72a-21ea-11e8-971c-c344887f68ba.png)

**Comment by boldt** [comment]
If I click on "Office & text", it shows me the available updates:

![bildschirmfoto vom 2018-03-07 09 38 15](https://user-images.githubusercontent.com/750793/37082033-ac2a2800-21eb-11e8-8566-a3ba12d365b1.png)
:

**Comment by MorrisJobke** [comment]
Fixed with #9565
