### ISSUE TITLE
LDAP Authentication using start_tls

### ISSUE THREAD

**Issue by MaxNoe** [nextcloud/server#8704]
We are currently migrating to a new LDAP Instance that requires `start_tls`. E.g. `ldapsearch -ZZ`

Using Nextcloud 13.0 it seems there is no option to use `start_tls`. 

Is it possible to use start_tls for the nextcloud LDAP authentication?

**Comment by MorrisJobke** [comment]
See #5476

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
@MaxNoe should be auto-discovered and used if available. `php occ ldap:show-config  | grep ldapTLS` (the name is confusing, sorry) should be set to 1 of it is used. You can force it by setting it to `php occ ldap:set-config "$CONFIGID" ldapTLS 1`.

**Comment by MaxNoe** [comment]
I have another follow up question.

The first thing seemed to be a certificate question, after adapting /etc/ldap/ldap.conf the first tab (Server) no reports a succesfull connection and the `Test Base DN` button reports 204 entries for my base dn, so far so good.

On the second tab (`Users`), I get a `Could not connect to LDAP` immediately. All options are greyed out.

**Comment by blizzz** [comment]
@MaxNoe that's more a config question, please ask it on the [forums](help.nextcloud.com) (or talk to sales for support ;) )

**Comment by MaxNoe** [comment]
> @MaxNoe that's more a config question, please ask it on the forums (or talk to sales for support ;) )

That looks clearly like a bug to me. 

If it works on the first tab of the settings but not on the second, there is something fishy

**Comment by blizzz** [comment]
@MaxNoe then please open a new issue utilizing the [template](https://raw.github.com/nextcloud/core/master/issue_template.md)

**Comment by wernerfred** [comment]
> I have another follow up question.
> 
> The first thing seemed to be a certificate question, after adapting /etc/ldap/ldap.conf the first tab (Server) no reports a succesfull connection and the `Test Base DN` button reports 204 entries for my base dn, so far so good.
> 
> On the second tab (`Users`), I get a `Could not connect to LDAP` immediately. All options are greyed out.

@MaxNoe did you find a solution to that problem? I am facing the exact same behaviour right now. Everything is working like expected except for the "auto-discover" features. That makes it really annoying for admins that are not that deep into ldap to manually create filters etc.

Do you (or anyone else) have a link to a forum/thread/issue that solves that problem? 

Cheers

**Comment by MaxNoe** [comment]
Unfortunately the solution was exactly the manual creation of these filters.
