### ISSUE TITLE
Combined JS re-generation is not fully triggered

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#8705]
* run `occ maintenance:repair` to delete the compiled JS files
* having `debug` in `config.php` set to `false`
* open any page
* actual: broken, because merged js files return with 404
* expected: JS is re-generated
* hints: setting `debug` to `true` then regenerates all assets
* versions: master (yesterday I have also seen this on a 12.0.5)

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen Potential blocker for the maintenance releases.

@juliushaertl Could you have a look at this?

**Comment by MorrisJobke** [comment]
> @rullzer @nickvergessen Potential blocker for the maintenance releases.

It's a blocker for 13.0.1 only, because there it is executed by default: #8144 - I experienced it yesterday on an instance where I removed manually the JS and CSS files from app data and then did a files scan on the app data (there is a command for this).

**Comment by MorrisJobke** [comment]
Most likely we need to clear the depsCache as well:

https://github.com/nextcloud/server/blob/b87e5a0f2e158d7aad91ba8e58b246e3666f6cbf/lib/private/Template/JSCombiner.php#L109

**Comment by juliushaertl** [comment]
The depsCache is actually cleared already in https://github.com/nextcloud/server/blob/b87e5a0f2e158d7aad91ba8e58b246e3666f6cbf/lib/private/Template/JSCombiner.php#L238

**Comment by MorrisJobke** [comment]
Doesn't seem to be the case over here. I ran the command. set the break point and then requested http://localhost:8000/index.php/js/core/merged-template-prepend.js?v=b2f9666b-0

This is the content of the folder and the state of the debugger:

<img width="754" alt="bildschirmfoto 2018-03-07 um 10 52 23" src="https://user-images.githubusercontent.com/245432/37085611-c522d820-21f5-11e8-9a56-b91ef9d30080.png">
<img width="1668" alt="bildschirmfoto 2018-03-07 um 10 52 31" src="https://user-images.githubusercontent.com/245432/37085612-c5419c60-21f5-11e8-964b-596ca7ab99da.png">

**Comment by rullzer** [comment]
@MorrisJobke can you set a breakpoint at https://github.com/nextcloud/server/blob/master/lib/private/Repair/ClearFrontendCaches.php#L64 and run the repair steps again. And see if it actually clears the cache?

**Comment by rullzer** [comment]
Or we do it the easyway and just check if the file actually exists... This will come at an aditional costs but it should just be querying the db...
