### ISSUE TITLE
two Logos on lostpassword/setpassword Site

### ISSUE THREAD

**Issue by invgit** [nextcloud/server#8706]
Steps to reproduce
1. upload a own Logo in format SVG
2. create a new User with email and without a password fo automatic sending a email
3. check email an click on set passwod
4. Site has two logos
5. same two logos when click on login site lost password

Nextcloud Version 13.0.0

Thx

**Comment by MorrisJobke** [comment]
Fixed in 13.0.1 with #8286

**Comment by invgit** [comment]
Thank you !
