### ISSUE TITLE
Passwort reset link on main page does not work correctly wiht external readonly user base 

### ISSUE THREAD

**Issue by technikphil** [nextcloud/server#8709]
### Steps to reproduce
1. Set Nextcloud up with LDAP-User-Backend
2. Set 'lost_password_link' in config.php to external link
3. Go to main Nextcloud page and click link "Forgot Password?" without first trying to login.

### Expected behaviour
Redirektion to specified external link

### Actual behaviour
Password-field disappaears; User is asked to input username
If using brower-context-menue (right click) and then open link, it work correct.
Also when trying to login with wrong password once, then link works as expected.

### Server configuration

**Operating system *ubuntu 10.04*:

**Web server:*apache 2.4.18*

**Database:*mysql 14.14*

**PHP version:*7.0.25*

**Nextcloud version:*13.0.0*

**Updated from an older Nextcloud/ownCloud or fresh install:*update*

**Where did you install Nextcloud from:*Web-Install*

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

### Client configuration
**Browser:*Firefox *

**Operating system:*Ubuntu 16.04 and Windows 10*

**Comment by blizzz** [comment]
@nickvergessen

**Comment by kesselb** [comment]
Is this still relevant? Code looks fine to me.

**Comment by technikphil** [comment]
Works fine in current version
