### ISSUE TITLE
occ files_external:notify adds / bevore $path if you share root / on CIFS share

### ISSUE THREAD

**Issue by Githubber000** [nextcloud/server#8717]
### Steps to reproduce
1. Add CIFS Share to External Storages with Empty or / in Remote Subfolder.
2. occ files_external:notify $mount_id --user administrator -p XXXX -vvv
3. Change some Files

### Expected behaviour
It should list the files that are changed like this so that it can be found in database, output should look like this:
modified 2018
added 2018/hulla
and then it shoud found in by scanner and also reportet to Client
This works if you use an Subfolder inside of the CIFS Share

### Actual behaviour
It lists the Files like this:
like this:
modified /2018
added /2018/hulla
and nobody gets the new,changed or removed Files

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** Apache 2.4

**Database:** mariadb-server-10.0

**PHP version:**7.0

**Nextcloud version:** 13

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from OwnCloud,NC10,NC11,NC12

**Where did you install Nextcloud from:** Nextcloud Website

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
```
/settings/integrity/failed :

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - admin_audit: true
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: true
  - password_policy: true
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: true
Disabled:
  - encryption
  - user_external

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "updatechecker": false,
        "supportedDatabases": [
            "mysql",
            "pgsql",
            "oci"
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.250.100.2",
            "cloud.tldplan.com",
            "213.252.16.138"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.tldplan.com",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "log_type": "nextcloud",
        "logfile": "\/var\/log\/oc\/nextcloud.log",
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_smtpport": "25",
        "firewall.debug": 2,
        "firewall.rules": "[{\"name\":\"*\",\"rules\":[{\"id\":\"systemTag\",\"field\":\"systemTag\",\"type\":\"integer\",\"operator\":\"equal\",\"value\":6}]}]",
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "trashbin_retention_obligation": "7, 8",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                                                    |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                                  |
| hasPagedResultSupport         |                                                                                                                                                                                    |
| homeFolderNamingRule          |                                                                                                                                                                                    |
| lastJpegPhotoLookup           | 0                                                                                                                                                                                  |
| ldapAgentName                 | CN=cloud.ad,CN=Users,DC=***,DC=int                                                                                                                                                 |
| ldapAgentPassword             | ***                                                                                                                                                                                |
| ldapAttributesForGroupSearch  |                                                                                                                                                                                    |
| ldapAttributesForUserSearch   |                                                                                                                                                                                    |
| ldapBackupHost                | ***studc.***.int                                                                                                                                                                   |
| ldapBackupPort                | 389                                                                                                                                                                                |
| ldapBase                      | DC=***,DC=int                                                                                                                                                                      |
| ldapBaseGroups                | DC=***,DC=int                                                                                                                                                                      |
| ldapBaseUsers                 | DC=***,DC=int                                                                                                                                                                      |
| ldapCacheTTL                  | 10                                                                                                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                                                                                                  |
| ldapDefaultPPolicyDN          |                                                                                                                                                                                    |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                                    |
| ldapEmailAttribute            | mail                                                                                                                                                                               |
| ldapExperiencedAdmin          | 0                                                                                                                                                                                  |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                                    |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                                    |
| ldapExpertUsernameAttr        | *************                                                                                                                                                                      |
| ldapGidNumber                 | gidNumber                                                                                                                                                                          |
| ldapGroupDisplayName          | cn                                                                                                                                                                                 |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=_U_ALLE)(cn=_U_FFM1)(cn=_U_GL)(cn=_U_TEAMLEITUNG)(cn=_U_TEAMASSISTENZ)(cn=_U_ZEICHNER)(cn=_U_GL_ASSISTENTZ)(cn=_U_FACHPLANER)(cn=_U_PROJEKTLEITER))) |
| ldapGroupFilterGroups         | _U_ALLE;_U_FFM1;_U_GL;_U_TEAMLEITUNG;_U_TEAMASSISTENZ;_U_ZEICHNER;_U_GL_ASSISTENTZ;_U_FACHPLANER;_U_PROJEKTLEITER                                                                  |
| ldapGroupFilterMode           | 0                                                                                                                                                                                  |
| ldapGroupFilterObjectclass    | group                                                                                                                                                                              |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                             |
| ldapHost                      | ***rzdc01.***.int                                                                                                                                                                  |
| ldapIgnoreNamingRules         |                                                                                                                                                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(|(memberof=CN=_U_ALLE,CN=Users,DC=***,DC=int)(primaryGroupID=2125))))(|(samaccountname=%uid)(|(userPrincipalName=%uid))))                              |
| ldapLoginFilterAttributes     |                                                                                                                                                                                    |
| ldapLoginFilterEmail          | 0                                                                                                                                                                                  |
| ldapLoginFilterMode           | 1                                                                                                                                                                                  |
| ldapLoginFilterUsername       | 0                                                                                                                                                                                  |
| ldapNestedGroups              | 0                                                                                                                                                                                  |
| ldapOverrideMainServer        |                                                                                                                                                                                    |
| ldapPagingSize                | 3000                                                                                                                                                                               |
| ldapPort                      | 389                                                                                                                                                                                |
| ldapQuotaAttribute            |                                                                                                                                                                                    |
| ldapQuotaDefault              |                                                                                                                                                                                    |
| ldapTLS                       | 0                                                                                                                                                                                  |
| ldapUserDisplayName           | displayName                                                                                                                                                                        |
| ldapUserDisplayName2          |                                                                                                                                                                                    |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=_U_ALLE,CN=Users,DC=***,DC=int)(primaryGroupID=2125))))                                                                                  |
| ldapUserFilterGroups          | _U_ALLE                                                                                                                                                                            |
| ldapUserFilterMode            | 1                                                                                                                                                                                  |
| ldapUserFilterObjectclass     | person                                                                                                                                                                             |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                               |
| ldapUuidUserAttribute         | auto                                                                                                                                                                               |
| turnOffCertCheck              | 0                                                                                                                                                                                  |
| turnOnPasswordChange          | 0                                                                                                                                                                                  |
| useMemberOfToDetectMembership | 1                                                                                                                                                                                  |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Crome, Cromium Firefoa
**Operating system:**
Ubuntu, MAC, Windwos

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
@icewind1991

**Comment by sm8ps** [comment]
Fighting #10097, I was confronted with the following entry in nextcloud.log:
`{"reqId":"mU4GtnlWBF0faaEf6lDI","level":3,"time":"2018-07-03T23:26:00+02:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"is_dir(): open_basedir restriction in effect. File(\/var\/nextcloud_data\/local_external_storage\/syncthing\/stefan\/.nc_test_file.txt\/) is not within the allowed path(s): (\/var\/www\/:\/tmp\/:\/var\/nextcloud_data\/:) at \/var\/www\/nextcloud\/apps\/files_inotify\/lib\/Storage\/NotifyHandler.php#130","userAgent":"--","version":"13.0.4.0"}`
The error message seems confusing at first because the file seems to be in the open_basedir path. However, the file name contains a trailing slash which makes it a non-existing directory and per PHP's logic such a one does not lie in the path (cf. https://stackoverflow.com/questions/11603156/php-open-basedir-allowed-path).
The error happens in line 130 of NotifyHandler.php:
`if (is_dir($path . '/')) {`

**Comment by theroch** [comment]
See my patch in #3524

**Comment by skjnldsv** [comment]
Closing as #10192 is closed. See comments there
