### ISSUE TITLE
When switching to Comments tab, focus »New comment« input

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#8718]
So that you can directly start typing. This should happen whenever you switch to the Comments tab. (Also when it’s opened externally, like currently when clicking on »Details« from the file action menu.)

Same as for the Talk app https://github.com/nextcloud/spreed/issues/689

**Comment by arunikayadav42** [comment]
can I please work on this issue @jancborchardt :)

**Comment by nickvergessen** [comment]
@arunikayadav42 just go ahead ;)
