### ISSUE TITLE
Same file in files drop overwrite with no warning

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#8719]
### Steps to reproduce
1. Create a ~~dropbox~~ files drop link
2. Upload file "letter.doc"
3. Upload a different file also named "letter.doc"

### Expected behaviour
If the same file already exists it should block the upload unless it is set in the options by the admin to overwrite.

### Actual behaviour
The existing file is overwritten

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
NGiNX 1.10
**Database:**
MariaDB 10.2.13
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
Zip

**Comment by MorrisJobke** [comment]
@nextcloud/sharing Wasn't there a collision detection and alternative naming on upload?

**Comment by rullzer** [comment]
I just tested this on 13 and the file gets renamed for me......

**Comment by rullzer** [comment]
Can you post detailed steps or a screencast of what you are doing? Maybe I'm doing something slightly different.

**Comment by c0fe** [comment]
@rullzer ok I will get something done over the weekend and post it on Monday. 

I used the Windows utility to generate two test files of variable sizes for this though.

**Comment by MorrisJobke** [comment]
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.
