### ISSUE TITLE
 Delete associated devices at once

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#8720]
In the (personal) security section it is not possible to delete all connected devices in one go 
but they must be eliminated individually, 
this becomes penalizing when with tests made you find yourself eliminating 25 and passing devices,
 
![immagine](https://user-images.githubusercontent.com/35575744/37108946-ed8a8c34-2238-11e8-968b-e92716cc06ef.png)

you can implement the possibility to remove the associated devices all together?

sometimes I find the same device associated multiple times for testing

**Comment by MorrisJobke** [comment]
cc @nickvergessen @ChristophWurst

**Comment by nickvergessen** [comment]
Well I could imagine a checkbox way of deleting, but not sure it's worth the effort.

**Comment by tigernero79** [comment]
something like all selects, like box check and delete.

**Comment by MorrisJobke** [comment]
> Nextcloud/00009 CFNetwork/811.5.4 Darwin/16.6.0

Looks like the macOS system (CalDAV or CardDAV integration in macOS itself9 :/ Seems it doesn't store the cookie and thus creates a new session on every check.

**Comment by ChristophWurst** [comment]
So this is a bug, although we check if a client does support cookies here: https://github.com/nextcloud/server/blob/eedfb0d8a419b121b655a2fa0957bdf2a0c30764/lib/private/User/Session.php#L433

**Comment by schadom** [comment]
Same issue here. Seems to be caused by MacOS/iOS CalDAV and CardDAV.
At least having an option in Nextcloud to prune out all the old sessions would be nice.
