### ISSUE TITLE
[BUG] Invalid PHP Settings Being Displayed

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#8721]
### Steps to reproduce
1.  Install Nextcloud
2. Increase the upload size in php.ini

### Expected behaviour
The monitoring page should report the accurate file size permissions allowed.

### Actual behaviour
Instead it displays a much lower amount that can be uploaded.

512MB is the default but it continues to display that after having manually changed the permitted file size to be 16G and have uploaded a file that is 700MB in size.

**_Screenshot:_**
https://i.imgur.com/yuALRoc.png

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
NGiNX 1.10
**Database:**
MariaDB 10.2.13
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
7.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
Zip

**Comment by MorrisJobke** [comment]
> Increase the upload size in php.ini

What did you do and what does phpinfo says? Create a file `info.php` with this content:

```
<?php

phpinfo();
```

and open it served from your web server in your browser.

**Comment by c0fe** [comment]
@MorrisJobke https://i.imgur.com/DGgBJ7k.png

**Comment by MorrisJobke** [comment]
It just reads this value: https://github.com/nextcloud/serverinfo/blob/master/lib/PhpStatistics.php#L50

**Comment by MorrisJobke** [comment]
No idea what goes wrong there, but please report it in the serverinfo repo: https://github.com/nextcloud/serverinfo/issues
