### ISSUE TITLE
nextcloud support crowd  sso?

### ISSUE THREAD

**Issue by dzhyw** [nextcloud/server#8724]
SAML SSO for Crowd is fully supported,  Does nextcloud support crowd , how to integrate？

thanks

**Comment by MorrisJobke** [comment]
> SAML SSO for Crowd is fully supported, Does nextcloud support crowd , how to integrate？

Then use the same IdP and configure it also in Nextcloud's user_saml app to authenticate against this IdP as well. It's then not that we authenticate Crowd, but we authenticate against the same SSO identity provider (IdP) which should solve the problem for you.
