### ISSUE TITLE
Enhancement suggestion: LibreOffice edit online

### ISSUE THREAD

**Issue by ebogaard** [nextcloud/server#873]
This is an enhancement suggestion, not a bug.

LibreOffice (LO) has native support for webdav(s). It would be a nice feature to be able to open documents from Nextcloud directly in the LO applications. We did this for another file service and there it works quite well.
This would make the Web interface even more usable, especialle for people who can't or won't install the desktop client.

LO has two custom URI handlers, called:

* 'vnd.sun.star.webdavs' for https-connections
* 'vnd.sun.star.webdav' for http-connections

What you can do is create a link to a file as follows:
vnd.sun.star.webdavs://domain.ext/remote.php/webdav/document.odt

So this breaks do in 2 parts:

1. protocol: The webdav(s) URI that LO supports, depending on the protocol that's used to access the Nextcloud webdav-feature - In this example: 'vnd.sun.star.webdavs://'
2. webdav-path: the 'ordinary' webdav-uri, without the protocol - In this example: 'domain.ext/remote.php/webdav/document.odt'

I suggest this link to be added to the app-sidebar, for example by adding an extra button with LO-icon, or making the document name a link.

To be able to open an this link from LO in Windows, it might be necessary to add this URI to the registry. See attached file.

[libreoffice-webdav-handler-x86opx64-v5.x.reg.txt](https://github.com/nextcloud/server/files/417928/libreoffice-webdav-handler-x86opx64-v5.x.reg.txt)

**Comment by Bugsbane** [comment]
While I like the idea of being able to do this for myself, I have some concerns. Specifically, if we need to add stuff to the registry for Windows, then wouldn't that mean having to either have users install the Desktop client anyway or mess around with manually editing their registry (dangerous and potentially confusing for less technical users).

If we skip enabling this for Windows users, then we need to accurately detect windows users (who may have browser useragents hidden/modified) or risk having an interface element that appears to be broken. Even if we do accurately detect the operating system, then we have an interface that and functionality is inconsistent across platforms. Just imagine the "fun" of trying to walk a less technical user, over the phone, through opening a Nextcloud file up in LO if you didn't realize that they didn't actually have the same button on their screen that you have on yours... or the confusion of a user used to accessing NC from an OS where this does work, when suddenly it doesn't work on another computer...

Maybe this would be better implemented as an app, with a prominent warning, although even that doesn't really address the issues, but just shift the responsibility of blame away from NC. ;)

**Comment by ebogaard** [comment]
I understand your reluctance to implement this as a core feature.
It might indeed be a good trade off to implement this as a separate app... or just have the users install the client app.
It would be a nice feature though, if you don't want to make online information locally available (secity-wise, etc). But that might just go against the NC-way of thinking.

I'll close this issue as it's not fitting as core functionality.

**Comment by Bugsbane** [comment]
Don't get me wrong, I personally would use this functionality if it existed, but then, I'm a technical user, comfortable with editing the Windows registry and personally I only use Linux anyway. Similarly, If the admin is using NC just for themselves and they're on Linux or are a technical Windows user, then great, no harm in installing this as an app.

It's just that providing a consistently working interface across platforms is important, and we can't rely on a wide variety of users doing technically dangerous operations, or having the desktop client installed, to make it happen. Thanks for understanding!

I'm sure an app doing this though, with adequate warnings, would be welcomed.
