### ISSUE TITLE
PHP errors (libpng)

### ISSUE THREAD

**Issue by janipewter** [nextcloud/server#8740]
### Actual behaviour
Nextcloud logs show loads of these errors:

imagecreatefrompng(): gd-png: fatal libpng error: invalid block type at /var/www/nextcloud/lib/private/legacy/image.php#582

### Expected behaviour
Not this error
 
### Steps to reproduce
1. Upload png files
2. ???
3. Profit

### Environment data
Ubuntu 16.04 ESXi virtual machine
Nextcloud server version: 13.0

#### Web server error log
```
Nothing interesting
```

#### Nextcloud log (data/nextcloud.log)
```
See top of post
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by MorrisJobke** [comment]
Could you provide us one of these PNGs?

**Comment by janipewter** [comment]
I don't know which PNGs it is failing on. All of the PNG files in my NC server are screenshots from my Android phone and they all seem to have working thumbnails. How do I clear the log?

**Comment by MorrisJobke** [comment]
> How do I clear the log?

Open the file and remove the files you want to have cleared. Or remove/rename the whole file. (Default location is `nextcloud.log` in your data dir)

**Comment by blizzz** [comment]
any update?

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
