### ISSUE TITLE
Files: Order activities in file details view

### ISSUE THREAD

**Issue by RailsViceRoads** [nextcloud/server#8744]
Possible not a bug, but a feature request: Activities in file details dialog should be ordered chronological

### Steps to reproduce
1. Share a file with a other user
2. Do several things with this share at the next days
3. Open file-details view / activities

### Expected behaviour
Activities should listed in chronological order. The last activity on top
![grafik](https://user-images.githubusercontent.com/36618192/37197272-65e1680a-237a-11e8-8d13-b8a89bd259aa.png)

### Actual behaviour
Activities are in random (?) order

### Server configuration
Version: 
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** NC 13.0.0.14

**Comment by MorrisJobke** [comment]
@nickvergessen something went wrong here o.O

**Comment by nickvergessen** [comment]
Seems like the list was grabbed twice

**Comment by MorrisJobke** [comment]
> Seems like the list was grabbed twice

Ah ... correct 🤔

**Comment by RailsViceRoads** [comment]
I have done some additional tests:

* on Admin's normal files-view the activities will displayed only one
* on Carlos normal files-view also.
* but on Admin's "shared with others" view * (German: "Von Dir geteilt") the activities displayed twice.
* on Carlos "shared from others" view * (German "Mit Dir geteilt") also

*) sorry, I use German language in NC. I don't know exactly the English names of all Items in left menue.

**Comment by nickvergessen** [comment]
@danxuliu maybe you can have a look.
It seems like sidebar tabs are loaded twice for "Shared with you" and "Shared with others" tabs.

**Comment by MorrisJobke** [comment]
As there is no report since a while and we can't reproduce the issue anymore I will close this ticket. If this is still happening please feel free to reopen.
