### ISSUE TITLE
Nextcloud server is not cleaning old uploads entries

### ISSUE THREAD

**Issue by marcos-guerrero** [nextcloud/server#8753]
### Steps to reproduce
1. Start to upload a big file (around 1Gb) thru the desktop client and see how a new dir entry in the user /user/uploads is created (you can confirm this using a sniffer to see which MKCOL is issued by the client 
2. Kill the client while the upload is not finished and confirm that the dir entry remains there
3.Wait 1 / 2 / 3 days with the OC server up and running

### Expected behaviour
As I don't have configured 'cache_chunk_gc_ttl' it defaults to 1 day as doc says https://docs.nextcloud.com/server/13/admin_manual/configuration_server/config_sample_php_parameters.html ,
so the folder created by the client in the uploads folder should be erased one day after creation

### Actual behaviour
The folder remains there after a week,

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.

**Database:** MariaDB 10.2

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12.0.4

**Where did you install Nextcloud from:** downloaded from downloads.nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.101.4",
            "localhost",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/192.168.101.4\/owncloud",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "updatechecker": false,
        "has_internet_connection": false,
        "asset-pipeline.enabled": true,
        "enable_previews": false,
        "filesystem_check_changes": 0,
        "trashbin_retention_obligation": "1, 2",
        "versions_retention_obligation": "1, 2",
        "skeletondirectory": "",
        "maintenance": false,
        "loglevel": 2,
        "logfile": "\/disco_datos0\/logs\/owncloud.log",
        "htaccess.RewriteBase": "\/owncloud",
        "singleuser": false
    }
}

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** NO

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
Yeah as far as I know you have to actively login (so just logout and login via the web).

We don't have a proper job for this yet I think :S

**Comment by marcos-guerrero** [comment]
sorry, I didn't understand very well your first sentence.... Do you mean that if I login via web with the user credentials of the the desktop client that is creating the stale uploads subdirs ... then the "magic" happens and the old uploads subdirs are deleted?

**Comment by rullzer** [comment]
yes. well it also happens if you login and logout in the desktop client. But the web is usually easier.

**Comment by marcos-guerrero** [comment]
ok. Thanks for the info. I'll test it.
So,if the logout / login is not easy and for the sake of automate the task ... I think I could delete the folders and then ./occ files:scan --path="/user/uploads" ...Don't you think so?

Thanks again!

**Comment by MorrisJobke** [comment]
> So,if the logout / login is not easy and for the sake of automate the task ... I think I could delete the folders and then ./occ files:scan --path="/user/uploads" ...Don't you think so?

I would not do that. Let the proper cleanup script handle this.

**Comment by MorrisJobke** [comment]
> Ok. I'll try to find out how to proceed. On my system, the users only access nextcloud via desktop client , so there's no way to login via web. And ask the users to close session in the desktop client every day ... to open it again won't work, because they simply won't do it...
> Thank you again for your help and advice! Will report back on monday if the login cleanup script is handling this properly (as I'll test it with some users)

We should move this to a background job: #8759.

I will close this one here in favor or #8759 - this here are only the symptoms that should be properly fixed at the root. @marcos-guerrero I hope this is okay?

**Comment by marcos-guerrero** [comment]
Perfect! Thanks

**Comment by marcos-guerrero** [comment]
Hello!
So, I tested the logout / login via web and nothing happens. Last friday I left one partial upload on the server and today was still there, so I logged via web ui with the user credentials used on for the partial upload, and no cleanup happens... the folder with the files 00000000, 00000001 and 00000002 is still there

**Comment by presianbg** [comment]
I'm having the same problem - almost 20Gb in uploads dir, which is not cleaned for the last 10 days.

**Comment by thibaultmol** [comment]
same, but is it different when I tried to upload a large file through Chrome instead of the desktop client (or something)? @MorrisJobke

**Comment by MorrisJobke** [comment]
> I'm having the same problem - almost 20Gb in uploads dir, which is not cleaned for the last 10 days.



> same, but is it different when I tried to upload a large file through Chrome instead of the desktop client (or something)? @MorrisJobke

Did you try to login into a new web session? Is it then cleared properly?

**Comment by presianbg** [comment]
Is I tried to loging/logout/clear browser cache/cookies with no avail.

**Comment by mathisxy** [comment]
I now have this issue, is there a solution for this?

> 
> 
> Is I tried to loging/logout/clear browser cache/cookies with no avail.

I cant decipher this...
