### ISSUE TITLE
White page / Error 500 after Upgrade from Nextcloud 12.0.4 to 13 

### ISSUE THREAD

**Issue by stothew** [nextcloud/server#8754]
Sorry i saw other posts about this, but they are related on beta so i don´t know if it is the same or a new one.

### Steps to reproduce
1. feel like "today i´m gonna upgrade"
2. press the button to the web updater
3. press Update
4. see all things go green
5. press no (as recomended) for no maintinace mode
6. press "Go back to your Nextcloud instance to finish the update"
7. Now you have a white blank page with no error mesage at all 

### Expected behaviour
Upgarade to Nextcloud 13 and all working fine

### Actual behaviour
white blank page on webinterface, can´t connect with clients anymore.

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** 
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02

**Database:**
Server version: 10.0.34-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:**
PHP 7.0.22-0ubuntu0.16.04.1 

**Nextcloud version:** (see Nextcloud admin page)
Upgrade from 12.0.4 to 13

**Updated from an older Nextcloud/ownCloud or fresh install:**
12.04 was fresh install. so this was the first upgrade

**Where did you install Nextcloud from:**
direct wget from nextcloud homepage

**Signing status:**
<details>
<summary>Signing status</summary>
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_notifications: 1.0.1
  - announcementcenter: 3.1.1
  - apporder: 0.4.1
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.8
  - caniupdate: 0.1.2
  - circles: 0.13.6
  - cms_pico: 0.9.7
  - comments: 1.2.0
  - contacts: 2.1.2
  - dav: 1.3.1
  - deck: 0.3.0
  - drawio: 0.8.9
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_snapshots: 0.1.1
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.9
  - metadata: 0.6.0
  - mood: 0.3.3
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notes: 2.3.2
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ojsxc: 3.3.2
  - password_policy: 1.2.2
  - polls: 0.8.1
  - provisioning_api: 1.2.0
  - registration: 0.4.0
  - richdocuments: 2.0.3
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.3
  - spreed: 2.0.2
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.6
  - theming: 1.3.0
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - dashboard
  - encryption
  - files_clipboard
  - files_external
  - files_frommail
  - lsd
  - user_external
  - user_ldap
  - w2g2
  - workin2gether

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "85.214.152.76",
            "box.leitsinn.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/85.214.152.76",
        "dbtype": "mysql",
        "version": "12.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

### Client configuration
**Browser:**
On Firefox "white blank page"
On Chromium "error 500"

**Operating system:**
Windows 7 / Linux Mint 18.3
### Logs
#### Web server error log
<details>
<summary>Webserver log</summary>

```
[Thu Mar 08 21:11:02.472744 2018] [mpm_prefork:notice] [pid 960] AH00163: Apach$
[Thu Mar 08 21:11:02.472757 2018] [core:notice] [pid 960] AH00094: Command line$
[Fri Mar 09 10:03:34.746812 2018] [:error] [pid 10136] [client 217.243.247.178:$
[Fri Mar 09 10:04:04.090663 2018] [:error] [pid 10186] [client 217.243.247.178:$
[Fri Mar 09 10:05:02.684383 2018] [:error] [pid 8144] [client 217.243.247.178:6$
[Fri Mar 09 10:10:52.827696 2018] [:error] [pid 10137] [client 217.243.247.178:$
[Fri Mar 09 10:12:21.715032 2018] [:error] [pid 8144] [client 217.243.247.178:6$
[Fri Mar 09 10:19:01.974348 2018] [:error] [pid 10187] [client 217.243.247.178:$
[Fri Mar 09 10:33:19.835928 2018] [:error] [pid 8142] [client 217.243.247.178:6$
[Fri Mar 09 10:33:26.114414 2018] [:error] [pid 10186] [client 217.243.247.178:$
[Fri Mar 09 10:57:44.344220 2018] [:error] [pid 8142] [client 178.2.226.114:512$
[Fri Mar 09 10:57:45.892103 2018] [:error] [pid 10186] [client 178.2.226.114:51$
[Fri Mar 09 10:57:47.131709 2018] [:error] [pid 10138] [client 178.2.226.114:51$
[Fri Mar 09 10:57:48.163790 2018] [:error] [pid 10136] [client 178.2.226.114:51$
[Fri Mar 09 10:57:49.253372 2018] [:error] [pid 10189] [client 178.2.226.114:51$
[Fri Mar 09 10:57:50.044877 2018] [:error] [pid 10187] [client 178.2.226.114:51$
[Fri Mar 09 10:57:50.828045 2018] [:error] [pid 8144] [client 178.2.226.114:512$
[Fri Mar 09 10:57:51.613037 2018] [:error] [pid 10206] [client 178.2.226.114:51$
[Fri Mar 09 10:57:53.371496 2018] [:error] [pid 10136] [client 178.2.226.114:51$
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"K2bgL0T2vxbMiuv52YkQ","level":3,"time":"2018-02-02T10:31:47+00:00","r$
{"reqId":"K2bgL0T2vxbMiuv52YkQ","level":3,"time":"2018-02-02T10:31:57+00:00","r$
{"reqId":"K2bgL0T2vxbMiuv52YkQ","level":2,"time":"2018-02-02T10:31:57+00:00","r$
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by stothew** [comment]
OK, sorry for the fast post. the other soulution now worked for me.

https://help.nextcloud.com/t/http-error-500-after-update-to-nc-13/27001

**Comment by MorrisJobke** [comment]
> OK, sorry for the fast post. the other soulution now worked for me.

Don't worry - closing then.
