### ISSUE TITLE
E2EE Causing none E2EE files to become locked and then fail to sync

### ISSUE THREAD

**Issue by mannp** [nextcloud/server#8756]
I don't know how these file locks occur but they are getting more and more in v13 when I had very few to none in v12.

I have recently changed to redis and followed the howto's on deleting entries from the locks table in the db, none of which has worked.

[howto that doesn't work for me](https://help.nextcloud.com/t/file-is-locked-how-to-unlock/1883)

I have today changed from local memchache and redis file locks to redis memchache and file locks, but files are still locked.

My NC13 has come to a standstil due to these locks and I am one sole using the server, so it really should not be locking and keeping these files locked as it it.
 

> Fatal | webdav | OCA\DAV\Connector\Sabre\Exception\FileLocked: file is locked[internal function] OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/config/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466:  Sabre\Event\EventEmitter->emit('beforeMethod', Array)/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/config/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80:  Sabre\DAV\Server->exec()/config/www/nextcloud/remote.php - line 164:  require_once('/config/www/nex...'){main}

I understand lock management is coming, but it doesn;t help me today when I have so many files locked.

Fatal | webdav | OCA\DAV\Connector\Sabre\Exception\FileLocked: file is locked[internal function] OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/config/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/config/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/config/www/nextcloud/remote.php - line 164: require_once('/config/www/nex...')

**Comment by rullzer** [comment]
This aren't the normal files lock. This is the E2E encryption app.

@schiessle

**Comment by mannp** [comment]
@rullzer you are too fast for me, I posted to save the post, just updating with current log locks

**Comment by mannp** [comment]
Fatal | webdav | OCA\DAV\Connector\Sabre\Exception\FileLocked: file is locked[internal function] OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/config/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466:  Sabre\Event\EventEmitter->emit('beforeMethod', Array)/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/config/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80:  Sabre\DAV\Server->exec()/config/www/nextcloud/remote.php - line 164:  require_once('/config/www/nex...')
-- | -- | --

**Comment by rullzer** [comment]
Still it seems the E2E app is throwing theses errors ;)

**Comment by mannp** [comment]
@rullzer you are correct and thank you for the prompt insight.

I have updated the thread as I have no disabled the latest E2EE app and all 12 files have synced to all machines and all clients green and happy again :+1: 

That said @schiessle is this related to the [wrong user agent string](https://github.com/nextcloud/end_to_end_encryption/issues/65#issuecomment-371210269)
