### ISSUE TITLE
Run cleanup of old upload parts in background job

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#8759]
Currently the cleanup of the upload folder is run as a login hook:

https://github.com/nextcloud/server/blob/20f1f757c4fc5ae41d41381f199113295ddd9cbc/lib/base.php#L808-L834

We should do this as a background job.

@icewind1991 @rullzer @nickvergessen Opinions?

Should issues like #8753

**Comment by rullzer** [comment]
Yes we should!

**Comment by MorrisJobke** [comment]
The problem with this is that it is required to be on login to have a valid user session as it sets up the view.

@icewind1991 Is there a way to set this up without the current session? Could you point me at some code that does this so I can come up with a first draft of the fix. Would love to have this fixed in 14 finally.

**Comment by Santobert** [comment]
I noticed a user with more than 20 GB of used space and a quota of 5 GB. The folder username/uploads takes about 20 GB. The commands `[...] occ files:clean` doesn't change anything.

After deleting most of the users files (he knows about it ;) ), his personal files take about 40 MB. The uploads folder shrink to 15 GB.

 Is this situation related to this ticket? How can I clean the uploads-folder?

**Comment by MorrisJobke** [comment]
> Does this situation have anything to do with this ticket? How can I clean up the upload folder?

The user should logout and login again. Then a cleanup is triggered.

**Comment by MorrisJobke** [comment]
> Most of this is addressed in #12227

Let's close it as it is now.

**Comment by krakazyabra** [comment]
Hello. Are there any news about this issue? I'm using S3 and, seems, unfinished uploads persist even after logout/login.

**Comment by gonzalo** [comment]
Sorry for reposting but I find that probably here is a more accurate place to ask about help:

Similar problem here. Using Nextcloud 25.0.1.1

Uploading through web UI a big file (1.7 GB)
during the process I set the maintenance mode on with occ
after a few seconds the UI informs that maitenance mode has been set
check with du "du -sh /xxxxx/xxxxx/userXXXX/uploads/" that folder has 541MB
after cron execution nothing changes, the chuncks remain here
occ file:cleanup has no effect.

This is especially worrying issue for us as we want to schedule a daily maintenance window for backups and it can collide with user uploads. There's no procedure set up in system to prevent this issue?

There is some manual operation that we can run to prevent wasting our filesystem? (I mean, with occ, not using our shell)
