### ISSUE TITLE
mysql timeout during file upload via https (not via http)

### ISSUE THREAD

**Issue by ownhardy** [nextcloud/server#8762]
### Steps to reproduce
1. use a fresh install of NextCloud 12.0.5 with a MySQL database
2. set the php.ini such that file uploads of 100MB and 30 minutes work properly
3. set the MySQL database timeout to 6 minutes (I think this is the wait_timeout variable, it defaults to very much longer). This is what my provider of shared hosting does.
4. log into the web frontend via https (notice the final s)
5. upload a big file (70MB in my case) from there, big in the sense that the upload takes more time than the MySQL timeout value (10 to 15 minutes in my case).

### Expected behaviour
After the progress bar finished, I expect the file to appear in the files section of the web frontend.

### Actual behaviour
The uploaded file does appear in the file system of the webserver. It has some ".part" file ending.
But it never appears in the web frontend. Instead I see a small "pop up" with "server error" after the upload finishes. And in the nextcloud.log I find the following:

"fatal, Webdav, Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = -1, `ttl` = ? WHERE `key` = ? AND `lock` = 1' with params [1520465492, "files\/cf5500d1774e4e43b253e6e39e11fbd6"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away"

The Apache error lock says something similar:

"PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /home/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /home/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)\n#1 /home/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1006): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /home/www/owncloud/lib/private/DB/Connection.php(213): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#3 /home/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\\DB\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#4 /home/www/owncloud/lib/private/DB/QueryBuilder/QueryBuilder.php(213): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 /home/www/owncloud/lib/private/Lock/DBLockingProvider.php(278): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 [internal function]: OC\\Lock\\DBLockingProvider->releaseAll() in /home/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 116"

### Probably helpful hints
1. When I use the web frontend via http (without the s this time!), then this file upload also works perfectly fine.
2. When I get my web hoster to increase the timeout value of his MySQL database to some longer value (20 minutes in my case), then the file upload also works fine. (Unfortunatelly I could not convince him to keep the longer timeout value permanently.) I think he change the value of wait_timeout.
3. When I do the very same (same webserver, same settings, same ssl, ...) with OwnCloud (not Nextcloud this time) then this works fine. (OC version was 9.1.6.2 to be precise, and a lot of version before.)

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.1.13

**Nextcloud version:** 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** official web installer (for shared web hosting)

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

default app list

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => '1234',
  'passwordsalt' => 'abcd',
  'secret' => '1234xyz,
  'trusted_domains' => 
  array (
    0 => 'nextcloud.myserver.de',
  ),
  'datadirectory' => '/home/www/nextcloud/data',
  'overwrite.cli.url' => 'http://nextcloud.myserver.de',
  'dbtype' => 'mysql',
  'version' => '12.0.5.3',
  'dbname' => 'db2',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => dbuser_2',
  'dbpassword' => 'secret',
  'installed' => true,
  'updater.release.channel' => 'production',
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**no

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu linux

#### Web server error log
<details>
<summary>Web server error log</summary>

see above

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

see above

</details>

#### Browser log
<details>
<summary>Browser log</summary>

no log here

</details>

**Comment by blizzz** [comment]
@rullzer haven't you wondering once to see db go away unexpectedly? that might be thing actually, that just a timeout kicks in. We've had similar with an LDAP server, if there were longer operations between server calls. solved it by trying to reconnect once.

**Comment by MorrisJobke** [comment]
> @rullzer haven't you wondering once to see db go away unexpectedly? that might be thing actually, that just a timeout kicks in. We've had similar with an LDAP server, if there were longer operations between server calls. solved it by trying to reconnect once.

Yes - we should try to figure out how to solve this properly - let's continue with those weird mysql server issues in #8863.
