### ISSUE TITLE
LDAP : New account created after renaming an OU, or the CN of a user

### ISSUE THREAD

**Issue by GillesMocellin** [nextcloud/server#8764]
I use LDAP for authentication et user management in Nextcloud 12.0.5.
I choose _samAccounName_ as the user name and internal ID for Nextcloud.
When an OU was renamed, all users in it see their client saying that all their files have been removed from the server, and asked wether they want to keep the existing local files.
In fact all account have been duplicated user1 with a new name user1_1234 and new empty datadir. 

The table _oc_ldap_user_mapping_ keep the full LDAP DN of a user, if something change (OU, CN) in the DN, it considers that it's a new user, and create another one, with a suffix for _owncloud_name_, to avoid collision.

### Steps to reproduce
1. Install LDAP user and groups application
2. Configure your LDAP/AD
3. Create or use an LDAP account into a specific OU
4. Connect to Nextcloud with this account, put some files
4. Rename the OU
5. Connect with the account again, all files are gone

### Expected behaviour
The entry in oc_ldap_user_mapping should have been updated instead of duplicated, creating a new account.

### Actual behaviour
A new user account is created, loosing files, shares...

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Nginx 1.3

**Database:**
MariaDB 10.2

**PHP version:**
7.

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0.5-fpm Docker container

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 11.

**Where did you install Nextcloud from:**
Official Docker image, with my own Ansible role and playbook

#### LDAP configuration (delete this part if not used)
Will update on monday...

**Comment by rullzer** [comment]
@blizzz

**Comment by blizzz** [comment]
Changes  in the DN are detected by looking for the UUID (or if it is overridden then that attribute).

**Comment by GillesMocellin** [comment]
In my case, the UUID (samaccountname) has not changed, only an OU has changed.
What I think should have been done is:
- update the DN field of the existing entry in _oc_ldap_user_mapping_ for that UUID
Instead of:
- create another entry with the new DN, and to allow the duplicate, rename the _owncloud_name_ field with a suffix

**Comment by blizzz** [comment]
well that's whats happening.

Please check the oc_ldap_user_mapping table for the original user and its UUID value.

**Comment by GillesMocellin** [comment]
I've just tested in v13, it works indeed !
I had the problem with 11.0.5 and I thought I had reproduced it in 12.0.5.
But I tried again, and I did not reproduce it in 12.0.5...

So perhaps only on v11, where I can't test, I only have one left, in production.

**Comment by blizzz** [comment]
I don't recall any code changes in this scope. I suspect (sorta out of the blue) an outdated UUID value perhaps due to a config change while the user was already mapped. Since it works on recent versions, let me close this. nevertheless, thanks for reporting!
