### ISSUE TITLE
Caldav 

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/server#8766]
Hello

I have davdroid syncing my contacts and calender using webdav. 

Everything was working but last days stop syncing. No errors are sent 

Is there any reason for this on the server side?

**Comment by tflidd** [comment]
Can you give us more information? What did you change in the last days? Any updates (client, server)? Did you increase the logging level? In the trouble shooting guide, you'll find some indicators where to find more information:
https://docs.nextcloud.com/server/13/admin_manual/issues/general_troubleshooting.html

Please fill out the issue template, we don't even know what version of Nextcloud you are using.

**Comment by MorrisJobke** [comment]
No feedback on this ticket - closing for now.
