### ISSUE TITLE
css: collabora: top menu not hidden correctly

### ISSUE THREAD

**Issue by lordg2009** [nextcloud/server#8771]
### Steps to reproduce
1. installing nextcloud 13.0 and collabora docker (code pulled at 10.03.2018)
2. opening a document for editing with collabora in an internet browser

### Expected behaviour
The top menu of the file viewer (home symbol, path, adding new file) should vanish. The top menu of collabora should be completely visible

### Actual behaviour
The top menu of the file viewer is not hidden and on top of the collabora menu. Because of that, collabora top menu isn't visible nor usable.

### Server configuration

**Operating system**: debian stretch

**Web server:** apache2

**Database:** mariadb

**PHP version:** php 5.6.30-0.deb8ul

**Nextcloud version:** (see Nextcloud admin page) nextcloud 13.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12.x

**Where did you install Nextcloud from:** web updater

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - calendar: 1.6.0
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - impersonate: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 1.12.39
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.0.1
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - bruteforcesettings
  - checksum
  - encryption
  - files_external
  - news
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 1,
        "theme": "",
        "maintenance": false,
        "updatechecker": false,
        "trashbin_retention_obligation": "7, 30",
        "htaccess.RewriteBase": "\/",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls"
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox 58.0.2

**Operating system:** windows 10

### Logs
no needed

### workaround
I noticed that the top menu of the file viewer with the id="controls" has the class="hidden" when opening a document through collabora. However the class="hidden" is not taking into account because display: flex; is added to the id #controls which has a higher priority. I added !important to /var/www/nextcloud/core/css/global.scss on line 28
```
27 .hidden {
28 	display: none !important;
29 }
```

**Comment by blizzz** [comment]
That was fixed a long while ago , iirc. Tried to clear you browser cache? cc @skjnldsv

**Comment by skjnldsv** [comment]
Hum, I don't recall, fixing this, @danxuliu ? @juliushaertl ?

**Comment by blizzz** [comment]
well, for me it works™

**Comment by juliushaertl** [comment]
Has been fixed with https://github.com/nextcloud/richdocuments/pull/153

@lordg2009 Updating the richdocuments app should fix the issue for you.
