### ISSUE TITLE
Update app(s) using command line

### ISSUE THREAD

**Issue by masupilamie** [nextcloud/server#8773]
Create a new occ app command (e.g. `occ app:update [--all|<app_name>]`) to update all or a single app.

This to allow full command line updating (of both apps and Nextcloud server code). Right now Nextcloud server code can be updated through the command line, but app updates still require the use of the admin web interface.

Duplicate of #1947, which is closed because of #1599, which only talks about installing (not updating). See also forum threat https://help.nextcloud.com/t/installing-and-updating-apps-from-the-command-line-occ/4622

**Comment by MorrisJobke** [comment]
cc @nickvergessen @blizzz @rullzer

**Comment by masupilamie** [comment]
@MorrisJobke Thank you, I've updated the issue to only talk about a occ app command.

**Comment by nickvergessen** [comment]
:+1:

**Comment by nachoparker** [comment]
This would be great. I just tested NextCloudPi's autoupgrade to NC14.0.1 and the only thing missing for the whole process to be transparent to the user is a command that I can place at the beginning/end of the upgrade process to bump all apps to NC14 compatibility automatically.

This, or make it part of `occ upgrade`, but probably  better to keep it separate.

Keep up the good work!

**Comment by GieltjE** [comment]
The updater.phar appears to update plugins when upgrading to a new version, but it's inaccesible without a new nextcloud version to update to.

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/pull/11053 (added for nextcloud 15)
