### ISSUE TITLE
Nextcloud cannot login

### ISSUE THREAD

**Issue by t-walker-wei** [nextcloud/server#8776]
### Expected behaviour
I cannot login nextcloud.When login, this error showed:https://my-domain/index.php/apps/ojsxc/settings 412 (Precondition failed).And then redirect to the login page.
### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:Centos7

**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
11.02
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Comment by MorrisJobke** [comment]
Please disable the OJSXC app (this is the XMPP chat app) and try again. If this does not work, please provide nextcloud.log and the remaining details of the issue template:https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md

Thanks
