### ISSUE TITLE
Password expiration

### ISSUE THREAD

**Issue by KB7777** [nextcloud/server#8785]
Hello.

It would be nice to have possibility to set local users password expiration after x days.
Usage -- if user wouldn't change password after 30 days the account is locked until the user change his password (AD like).

Need it to pass Security Department requirements.

Regards.

**Comment by rullzer** [comment]
If you want something like this I suggest you setup LDAP where you already can configure a policy like that.

Having said that. Password expiration is a bad idea. Even the NIST agrees on that. If you want people to use strong passwords having them change it periodically is a bad idea.

**Comment by KB7777** [comment]
Yes, I know about NIST suggestions, but at enterprise and financial organizations it take more time to be up-to-date :) Many more time aven :)

We have two instances with LDAP setup, but now there is a need for externals accounts for our business financial clients and it has to be accounts out of our AD's.

**Comment by MorrisJobke** [comment]
May be also related to the forced password change: #1262

**Comment by MorrisJobke** [comment]
> May be also related to the forced password change: #1262

In combination with an API for the forced password change this could be done completely from the outside and doesn't require to have the logic of when it should happen inside Nextcloud itself, which makes a lot of sense to me.

**Comment by rullzer** [comment]
Yes please. Because else we have to implement this deep in our code base. And we are bound to miss something. I'd rather we are NIST compliant. And all other policies should be handled somewhere else.

**Comment by MorrisJobke** [comment]
I added it to that ticket and will close this one here in favor of #1262
