### ISSUE TITLE
quota API design flaw - unlimited and >1TB can't be detected

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#879]
### Steps to reproduce
1. set a quota for <user> to 2TB
2. call ```/ocs/v1.php/cloud/users/<user>```
3. --> ```<free>1103360991232</free><used>118102553</used><total>1103479093785</total>```
4. set quota for <user2> to 1GB
5. set a quota for <user> to unlimited
6. call ```/ocs/v1.php/cloud/users/<user>```
7. --> ```<free>1103360991232</free><used>118102553</used><total>1103479093785</total>```
8. set quota for <user2> to unlimited
9. call ```/ocs/v1.php/cloud/users/<user2>```
10. --> ```<free>1103356682240</free><used>714783</used><total>1103357397023</total>```

### Expected behaviour
3. _if_ I set the quota for a user to 2TB I want this information, right now the quota is always ~1TB, e.g. for 1TB, 2TB, unlimited. 
7. _if_ the quota is set to unlimited I want to get this information so I can detect _if_ the quota for a user is set.
10. _if_ the quota for _all_ existing users has been set to unlimited I want this information on all users being available (not the ~1TB info again...)

**We try to use this for https://github.com/nextcloud/android/pull/204 and obviously want to hide the quota display when none is set, which isn't working because of the described API behavior above.**

### Actual behavior
1TB, 2TB, Unlimited always set ~1TB in the quota tags...

### Server configuration
**Operating system**: 
-

**Web server:** 
-

**Database:** 
MySQL

**PHP version:** 
7

**Nextcloud version:** (see Nextcloud admin page) 
9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgrade from 9.0.52

**Where did you install Nextcloud from:**
Nc website download (zip file)

**Signing status:**
<details>
<summary>Signing status</summary>
0_o
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
NO ACCESS
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => ''***',
  'passwordsalt' => ''***',
  'secret' => ''***',
  'trusted_domains' => 
  array (
    0 => '***.net',
  ),
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\Preview\Image',
    1 => 'OC\Preview\MP3',
    2 => 'OC\Preview\TXT',
    3 => 'OC\Preview\Movie',
    4 => 'OC\Preview\MarkDown',
  ),
  'datadirectory' => '/homepages/'***/data',
  'overwrite.cli.url' => ''***',
  'dbtype' => 'mysql',
  'version' => '9.0.52.0',
  'dbname' => ''***',
  'dbhost' => ''***',
  'dbtableprefix' => 'oc_',
  'dbuser' => ''***',
  'dbpassword' => ''***_',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'updater.release.channel' => 'stable',
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** FF 48.0

**Operating system:** Win7 Enterprise

**Comment by nickvergessen** [comment]
Well quota is a number as well, but it seems to be missing from this endpoint, maybe we can add it as well.

**Comment by AndyScherzinger** [comment]
@nickvergessen atm it is 
```
<quota>
  <free>1103360991232</free>
  <used>118102553</used>
  <total>1103479093785</total>
</quota>

**Comment by nickvergessen** [comment]
Yeah, but inside this quota, the following values could exist:
https://github.com/nextcloud/server/blob/0215b004da6af887b3e3efa28c425d41a1c76b9b/lib/private/legacy/helper.php#L626-L634
