### ISSUE TITLE
Moving file to home directory results in inaccessible file.

### ISSUE THREAD

**Issue by rendhalver** [nextcloud/server#8790]
### Steps to reproduce
1. Open web interface
2. Create a new text file
2. Copy that file to your home directory
3. Open file the file in it's destination

### Expected behaviour
Tell us what should happen

I would have expected the file to have been copied properly and be accessible at it's new location.

### Actual behaviour
Tell us what happens instead

When opening the file from the new location this error message pops up:

<img width="222" alt="screen shot 2018-03-12 at 08 30 09" src="https://user-images.githubusercontent.com/1026337/37298780-b61b211a-25f7-11e8-815c-70833698b7b2.png">

When the next sync run happens this error pops up.
<img width="330" alt="screen shot 2018-03-12 at 08 33 57" src="https://user-images.githubusercontent.com/1026337/37283972-4259102e-25d0-11e8-8203-8becdd1fe7b9.png">

And these errors exist in the logs:

fopen(https://s3-gm-storage.powerhrg.com/nextcloud-default/urn%3Aoid%3A2971593): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
 at /var/www/nextcloud/lib/private/Files/ObjectStore/S3ObjectTrait.php#66

The file is created in the NextCloud default directory which is also on S3 but it's not the file NextCloud thinks it is.
I found this file with the contents of the file I moved: urn/oid/2971658

So NextCloud seems to be getting confused somewhere and not using the right file in the S3 bucket.

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache 2.4

**Database:**
Percona Mysql 5.6.24-72.2-1.trusty

**PHP version:**
PHP 7.0.17-2+deb.sury.org~trusty+1 (cli) (built: Mar 15 2017 09:38:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.17-2+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 12.0.4

**Where did you install Nextcloud from:**
We used the installer downloaded from the website.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - comments
  - encryption
  - files_pdfviewer
  - files_videoplayer
  - notifications
  - sharebymail
  - survey_client

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

{
    "system": {
        "instanceid": "oc6v523cGhjE",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.powerhrg.com"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.powerhrg.com",
        "dbtype": "mysql",
        "version": "12.0.5.3",
        "dbname": "nextcloud",
        "dbhost": "db.powerhrg.com",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "powerhrg.com",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nextcloud-default",
                "autocreate": false,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "s3-hq-storage.powerhrg.com",
                "use_ssl": true,
                "use_path_style": true
            }
        },
        "loglevel": 1,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "redis-13764.production-rediscluster-powercloud.powerhrg.com",
            "port": "13764"
        },
        "versions_retention_obligation": "auto",
        "logfile": "\/var\/log\/nextcloud.log",
        "updater.release.channel": "production",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.powerhrg.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/data\/mnt\/nitrocloud_tmp\/cache",
        "updatechecker": false
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.5.2",
            "types": "filesystem"
        },
        "activitylog": {
            "enabled": "yes",
            "installed_version": "0.0.1",
            "types": ""
        },
        "admin_notifications": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "1"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.3",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.7",
            "types": ""
        },
        "comments": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "no",
            "installed_version": "1.5.3",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1487004847.4135",
            "lastcron": "1520857802",
            "lastupdateResult": "[]",
            "lastupdatedat": "1520857214",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "a012855888790a0ee4eae3b35f42e762",
            "umgmt_show_backend": "false",
            "umgmt_show_storage_location": "false",
            "updater.secret.created": "1519321813",
            "vendor": "nextcloud"
        },
        "dav": {
            "OCA\\DAV\\Migration\\ValueFixInsert_ran": "true",
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": "filesystem"
        },
        "direct_menu": {
            "enabled": "no",
            "installed_version": "0.10.2",
            "ocsid": "169148",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "1000",
            "default_quota": "1 GB",
            "enabled": "yes",
            "installed_version": "1.7.2",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "no",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,dropbox,googledrive,swift,smb,\\OC\\Files\\Storage\\SFTP_Key,\\OC\\Files\\Storage\\SMB_OC"
        },
        "files_markdown": {
            "enabled": "no",
            "installed_version": "1.0.1",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "no",
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "no",
            "installed_version": "1.1.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "17.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "levels": "00000",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "no",
            "installed_version": "0.6.2",
            "ocsid": "169914",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.1",
            "notification_groups": "[]",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "no",
            "installed_version": "2.3.1",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "no",
            "installed_version": "2.0.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.2.2",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "1.1.25",
            "types": "prevent_group_restriction",
            "wopi_url": "https:\/\/office.powerhrg.com"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "spreedme": {
            "enabled": "no",
            "installed_version": "0.3.7",
            "types": ""
        },
        "survey_client": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "last_report": "{\"id\":\"oc6v523cGhjE\",\"items\":[[\"server\",\"version\",\"12.0.2.0\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"memcache.distributed\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.0.17\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",1048576000],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"5.6.26\"],[\"database\",\"size\",243105792],[\"apps\",\"activity\",\"2.5.2\"],[\"apps\",\"activitylog\",\"0.0.1\"],[\"apps\",\"admin_notifications\",\"disabled\"],[\"apps\",\"bruteforcesettings\",\"1.0.2\"],[\"apps\",\"calendar\",\"1.5.3\"],[\"apps\",\"comments\",\"1.2.0\"],[\"apps\",\"contacts\",\"disabled\"],[\"apps\",\"dav\",\"1.3.0\"],[\"apps\",\"direct_menu\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.2.0\"],[\"apps\",\"federation\",\"1.2.0\"],[\"apps\",\"files\",\"1.7.2\"],[\"apps\",\"files_external\",\"1.3.0\"],[\"apps\",\"files_markdown\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"1.1.1\"],[\"apps\",\"files_sharing\",\"1.4.0\"],[\"apps\",\"files_texteditor\",\"2.4.1\"],[\"apps\",\"files_trashbin\",\"1.2.0\"],[\"apps\",\"files_versions\",\"1.5.0\"],[\"apps\",\"files_videoplayer\",\"1.1.0\"],[\"apps\",\"firstrunwizard\",\"2.1\"],[\"apps\",\"gallery\",\"17.0.0\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"lookup_server_connector\",\"1.0.0\"],[\"apps\",\"mail\",\"disabled\"],[\"apps\",\"nextcloud_announcements\",\"1.1\"],[\"apps\",\"notes\",\"disabled\"],[\"apps\",\"notifications\",\"2.0.0\"],[\"apps\",\"oauth2\",\"1.0.5\"],[\"apps\",\"password_policy\",\"1.2.2\"],[\"apps\",\"provisioning_api\",\"1.2.0\"],[\"apps\",\"richdocuments\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.2.0\"],[\"apps\",\"sharebymail\",\"1.2.0\"],[\"apps\",\"spreed\",\"disabled\"],[\"apps\",\"spreedme\",\"disabled\"],[\"apps\",\"survey_client\",\"1.0.0\"],[\"apps\",\"systemtags\",\"1.2.0\"],[\"apps\",\"theming\",\"1.3.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.1.1\"],[\"apps\",\"updatenotification\",\"1.2.0\"],[\"apps\",\"user_external\",\"0.4\"],[\"apps\",\"user_ldap\",\"1.2.1\"],[\"apps\",\"workflowengine\",\"1.2.0\"],[\"stats\",\"num_files\",37329],[\"stats\",\"num_users\",56],[\"stats\",\"num_storages\",6222],[\"stats\",\"num_storages_local\",2],[\"stats\",\"num_storages_home\",2032],[\"stats\",\"num_storages_other\",4188],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",115],[\"files_sharing\",\"num_shares_user\",66],[\"files_sharing\",\"num_shares_groups\",1],[\"files_sharing\",\"num_shares_link\",48],[\"files_sharing\",\"num_shares_link_no_password\",48],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_1\",\"47\"],[\"files_sharing\",\"permissions_3_15\",\"1\"],[\"files_sharing\",\"permissions_0_17\",\"23\"],[\"files_sharing\",\"permissions_1_17\",\"1\"],[\"files_sharing\",\"permissions_0_19\",\"2\"],[\"files_sharing\",\"permissions_0_23\",\"3\"],[\"files_sharing\",\"permissions_0_31\",\"38\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1517932806",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "theming": {
            "backgroundMime": "image\/jpeg",
            "cachebuster": "12",
            "color": "#005B8C",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "logoMime": "image\/png",
            "name": "PowerCloud",
            "slogan": "Power cloud storage and collaboration",
            "types": "logging",
            "url": "https:\/\/cloud.powerhrg.com"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "updatenotification": {
            "activitylog": "0.0.1",
            "admin_notifications": "1.0.0",
            "bruteforcesettings": "1.0.3",
            "calendar": "1.5.8",
            "contacts": "1.5.3",
            "core": "12.0.5.3",
            "direct_menu": "0.10.1",
            "enabled": "yes",
            "files_markdown": "1.0.1",
            "installed_version": "1.2.0",
            "mail": "0.6.2",
            "notes": "2.2.0",
            "notify_groups": "[]",
            "types": "",
            "update_check_errors": "0"
        },
        "user_external": {
            "enabled": "yes",
            "installed_version": "0.4",
            "types": "authentication,prelogin"
        },
        "user_ldap": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "s01has_memberof_filter_support": "1",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "uid",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_base": "dc=powerhrg,dc=com",
            "s01ldap_base_groups": "ou=groups,dc=powerhrg,dc=com",
            "s01ldap_base_users": "ou=users,dc=powerhrg,dc=com",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_default_ppolicy_dn": "",
            "s01ldap_display_name": "displayName",
            "s01ldap_dn": "cn=diradmin,dc=powerhrg,dc=com",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "mail",
            "s01ldap_experienced_admin": "1",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_gid_number": "gidNumber",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "(&(objectclass=posixGroup))",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_group_member_assoc_attribute": "memberUid",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "posixGroup",
            "s01ldap_host": "ldap.powerhrg.com",
            "s01ldap_login_filter": "(&(objectclass=posixAccount)(uid=%uid))",
            "s01ldap_login_filter_mode": "1",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "389",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_turn_on_pwd_change": "0",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "1",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "posixAccount",
            "s01ldap_userlist_filter": "(&(objectclass=posixAccount)(mail=*@powerhrg.com))",
            "s01use_memberof_to_detect_membership": "0",
            "types": "authentication"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
S3

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP.

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox
**Operating system:**
MacOS
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
@rendhalver Could you still reproduce this with 15.0.5? We improved the object storage integration quite a bit and ironed out some bugs lately.

**Comment by rendhalver** [comment]
Thanks @MorrisJobke I will let the team know this may be fixed.

**Comment by MorrisJobke** [comment]
> Thanks @MorrisJobke I will let the team know this may be fixed.

Thanks for the feedback - let me close this ticket then for now. We can reopen if this is still an issue.
