### ISSUE TITLE
appinfo/preupdate.php not run before app upgrade

### ISSUE THREAD

**Issue by leonklingele** [nextcloud/server#880]
1. Create an `update.php` and `preupdate.php` for your app and do some random logging in them
2. Increase the version of your app in `info.xml`
3. Do an upgrade via the web interface / occ command
4. Check the log: Only `update.php` was run, `preupdate.php` didn't run at all. :(

**Comment by LukasReschke** [comment]
As per https://github.com/owncloud/core/pull/23879 preupdate.php is a very old magic, can you try to use a [pre-migration](https://github.com/owncloud/core/blob/5a058f6c0ef64ff0272fcdb58478f9c6611d6819/lib/private/App/InfoParser.php#L81-L89) step?

https://github.com/nextcloud/server/blob/97c8232b9f87146e0d7cf9da8696979489329eca/apps/dav/appinfo/info.xml#L23-L30 has some examples, the class basically just implements \OCP\Migration\IRepairStep then.

**Comment by LukasReschke** [comment]
Also update.php is deprecated :)

**Comment by leonklingele** [comment]
> Also update.php is deprecated :)
What to use instead? A check in `app.php`?

**Comment by LukasReschke** [comment]
Either a `post-migration` or `live-migration` step: https://github.com/nextcloud/server/blob/97c8232b9f87146e0d7cf9da8696979489329eca/apps/dav/appinfo/info.xml#L23-L30 (https://github.com/nextcloud/server/blob/813f0a0f40dd42b28cd35d91616f3f87ef400861/apps/dav/lib/Migration/GenerateBirthdays.php#L32-L32)

**Comment by LukasReschke** [comment]
Order is:

1. pre-migration
2. DB is updated
3. post-migration

A live-migration is executed unpredictable by the Nextcloud cron. So if the change is not required to work and just "nice to have" that is the best choice performance wise. 

https://github.com/owncloud/core/blob/53f492d71de460f691b93ca3cc1cd2356f103d04/lib/private/legacy/app.php#L1198-L1203 has the logic

**Comment by leonklingele** [comment]
I tried the migration steps, but I'm still running into problems.
Here's what I try to achieve:

The [nextcloud-spreedme](https://github.com/strukturag/nextcloud-spreedme) app requires you to create to config files:

1. `cp config/config.php.in config.php`
2. `cp extra/static/config/OwnCloudConfig.js.in extra/static/config/OwnCloudConfig.js`.

Somehow we want to keep these files when using the app-updater (web interface).
The migration via info.xml seems to execute the `pre-migration` step of the freshly downloaded app, not the old one.

Can you help?

**Comment by LukasReschke** [comment]
What you're trying to do here is not possible currently. Neither preupdate.php nor pre-migration catch this and won't in the future.

Your best chance is to store the data in the database instead and read it out from there.
