### ISSUE TITLE
NC 13.0 (Webinterface) File Locking

### ISSUE THREAD

**Issue by ExaconAT** [nextcloud/server#8801]
Is it possible to mark open Files in the Webinterface as being currently edited or maybe lock the file??

**Comment by DBJRdev** [comment]
We are using the app "W2G2" from the app store. It serves exactly your desired purpose and does its job well.

**Comment by ExaconAT** [comment]
On one of our Servers the following Error appears.

![see](https://user-images.githubusercontent.com/33482537/37348997-b71dcd04-26d5-11e8-9799-bc25d06a444b.png)

The picture says: "Error: This app can not be activated because it makes the server unstable."

**Comment by DBJRdev** [comment]
Which release, release channel, PHP? We're on 13.0, stable release channel, and PHP 7.1, and don't get this error message.

**Comment by ExaconAT** [comment]
Looks like its an SQL Error: 

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE table oc_locks_w2g2(name varchar(255) PRIMARY KEY,created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,locked_by varchar(255))': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

13.0 stable, 7.0.22-0ubuntu0.16.04.1

on the newest Servers it works. Thank you!

**Comment by MariusBluem** [comment]
If you have more trouble with the `W2G2`-app please ask for help over here:
https://github.com/newroco/W2G2
