### ISSUE TITLE
 [Error] desktop client won't sync to server

### ISSUE THREAD

**Issue by rusty-genius** [nextcloud/server#8803]
i am experiencing some trouble with my nextcloud client on linux. each time when i boot up my pc and nexcloud autostarts, it can’t connect with my server. it always shows me “can’t connect to … operation cancelled”. after i delete my account and set up the same account again, it works flawlessly.

the same goes for my wifes account and for my arch laptop (i use mint on my main machine by the way)
this is the logfile:
03-11 10:52:13:699 5343 unknown: custom style sheet is disabled
03-11 10:52:13:743 5343 OCC::Account::resetNetworkAccessManager: Resetting QNAM
03-11 10:52:13:744 5343 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
03-11 10:52:13:744 5343 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
03-11 10:52:13:778 5343 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
03-11 10:52:13:779 5343 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for “https://www.spacepirate.de” + “status.php” "OCC::ConnectionValidator"
03-11 10:52:15:199 5343 OCC::CheckServerJob::finished: status.php returns: QMap((“edition”, QVariant(QString, “”))(“installed”, QVariant(bool, true))(“maintenance”, QVariant(bool, false))(“needsDbUpgrade”, QVariant(bool, false))(“productname”, QVariant(QString, “SpacePirate”))(“version”, QVariant(QString, “13.0.0.14”))(“versionstring”, QVariant(QString, “13.0.0”))) QNetworkReply::NetworkError(NoError) Reply: QNetworkReplyHttpImpl(0x560ccc6b6830)
03-11 10:52:15:201 5343 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found: QUrl(“https://www.spacepirate.de/status.php”) with version “13.0.0” ( “13.0.0.14” )
03-11 10:52:15:201 5343 OCC::ConnectionValidator::setAndCheckServerVersion: QUrl(“https://www.spacepirate.de”) has server version “13.0.0.14"
03-11 10:52:15:202 5343 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change: “Undefined” -> “Credentials Wrong"
03-11 10:52:15:203 5343 OCC::HttpCredentials::fetchFromKeychain: -------- -----> QSslCertificate(””, “”, “1B2M2Y8AsgTpgAmY7PhCfg==”, (), (), QMap(), QDateTime(Invalid), QDateTime(Invalid)) QSslKey(PrivateKey, OPAQUE, -1)
03-11 10:52:15:204 5343 OCC::AccountState::setState: AccountState state change: “Getrennt” -> "Konfigurationsfehler"
03-11 10:52:15:205 5343 OCC::FolderMan::slotAccountStateChanged: Account “tim@www.spacepirate.de” disconnected or paused, terminating or descheduling sync folders
03-11 10:52:15:273 5343 OCC::Account::resetNetworkAccessManager: Resetting QNAM
03-11 10:52:15:274 5343 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
03-11 10:52:15:274 5343 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
03-11 10:52:15:276 5343 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
03-11 10:52:15:277 5343 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for “https://www.spacepirate.de” + “status.php” "OCC::ConnectionValidator"
03-11 10:52:16:495 5343 OCC::CheckServerJob::finished: status.php returns: QMap((“edition”, QVariant(QString, “”))(“installed”, QVariant(bool, true))(“maintenance”, QVariant(bool, false))(“needsDbUpgrade”, QVariant(bool, false))(“productname”, QVariant(QString, “SpacePirate”))(“version”, QVariant(QString, “13.0.0.14”))(“versionstring”, QVariant(QString, “13.0.0”))) QNetworkReply::NetworkError(NoError) Reply: QNetworkReplyHttpImpl(0x560cccb68150)
03-11 10:52:16:496 5343 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found: QUrl(“https://www.spacepirate.de/status.php”) with version “13.0.0” ( “13.0.0.14” )
03-11 10:52:16:497 5343 OCC::ConnectionValidator::setAndCheckServerVersion: QUrl(“https://www.spacepirate.de”) has server version "13.0.0.14"
03-11 10:52:16:498 5343 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
03-11 10:52:16:499 5343 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for “https://www.spacepirate.de” + “/” "OCC::ConnectionValidator"
03-11 10:52:17:323 5343 OCC::PassiveUpdateNotifier::backgroundCheckForUpdate: virtual void OCC::PassiveUpdateNotifier::backgroundCheckForUpdate()
03-11 10:52:17:324 5343 OCC::OCUpdater::backgroundCheckForUpdate: virtual void OCC::OCUpdater::backgroundCheckForUpdate() checking for available update
03-11 10:52:18:641 5343 OCC::PassiveUpdateNotifier::versionInfoArrived: Client is on latest version!
03-11 10:52:43:716 5343 OCC::AbstractNetworkJob::slotTimeout: virtual void OCC::AbstractNetworkJob::slotTimeout() OCC::PropfindJob(0x7f283c00cfa0) Timeout QUrl(“https://www.spacepirate.de/remote.php/webdav/”)
03-11 10:52:43:716 5343 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(OperationCanceledError) “Operation canceled” QVariant(Invalid)
03-11 10:52:43:717 5343 OCC::PropfindJob::finished: PROPFIND request not successful, http result code is 0 ""
03-11 10:52:43:717 5343 unknown: QIODevice::read (QNetworkReplyHttpImpl): device not open
03-11 10:52:43:717 5343 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change: “Credentials Wrong” -> "Timeout"
03-11 10:52:43:718 5343 OCC::AccountState::setState: AccountState state change: “Konfigurationsfehler” -> "Netzwerkfehler"
03-11 10:52:43:718 5343 OCC::AccountSettings::showConnectionLabel: “Keine Verbindung zu Nextcloud auf https://www.spacepirate.de\nOperation canceled"
03-11 10:52:43:719 5343 OCC::FolderMan::slotAccountStateChanged: Account "tim@www.spacepirate.de” disconnected or paused, terminating or descheduling sync folders
03-11 10:52:45:714 5343 OCC::Account::resetNetworkAccessManager: Resetting QNAM
03-11 10:52:45:715 5343 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
03-11 10:52:45:716 5343 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
03-11 10:52:45:718 5343 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
03-11 10:52:45:719 5343 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for “https://www.spacepirate.de” + “status.php” "OCC::ConnectionValidator"
03-11 10:52:46:916 5343 OCC::CheckServerJob::finished: status.php returns: QMap((“edition”, QVariant(QString, “”))(“installed”, QVariant(bool, true))(“maintenance”, QVariant(bool, false))(“needsDbUpgrade”, QVariant(bool, false))(“productname”, QVariant(QString, “SpacePirate”))(“version”, QVariant(QString, “13.0.0.14”))(“versionstring”, QVariant(QString, “13.0.0”))) QNetworkReply::NetworkError(NoError) Reply: QNetworkReplyHttpImpl(0x560cccb2c160)
03-11 10:52:46:916 5343 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found: QUrl(“https://www.spacepirate.de/status.php”) with version “13.0.0” ( “13.0.0.14” )
03-11 10:52:46:917 5343 OCC::ConnectionValidator::setAndCheckServerVersion: QUrl(“https://www.spacepirate.de”) has server version "13.0.0.14"
03-11 10:52:46:917 5343 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
03-11 10:52:46:918 5343 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for “https://www.spacepirate.de” + “/” “OCC::ConnectionValidator”

**Comment by rullzer** [comment]
I see some:

`03-11 10:52:15:202 5343 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change: “Undefined” -> “Credentials Wrong"`

and

`03-11 10:52:43:717 5343 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change: “Credentials Wrong” -> "Timeout"`

So probably you are trying a wrong password. And probably you are hitting bruteforce protection. Is login via the web also slow?

**Comment by rusty-genius** [comment]
yes, the web login is pretty slow. i always thought this is due to a slow server connection speed (the server is at my friends house in another city)

i already asked for help in the nextcloud forum and tried some things that a helpful guy told me too. without effect. see here: https://help.nextcloud.com/t/desktop-client-linux-no-connect-after-updating-android-app-to-3-0-3/28508/4

**Comment by rusty-genius** [comment]
> I see some:

>03-11 10:52:15:202 5343 OCC::AccountState::slotConnectionValidatorResult: AccountState connection >status change: “Undefined” -> “Credentials Wrong"

>and

>03-11 10:52:43:717 5343 OCC::AccountState::slotConnectionValidatorResult: AccountState connection >status change: “Credentials Wrong” -> "Timeout"

>So probably you are trying a wrong password. And probably you are hitting bruteforce protection. Is login >via the web also slow?

any other ideas what i could do to fix the problem?

**Comment by tflidd** [comment]
Perhaps try to disable the bruteforce-plugin. If you have a few failed logins, it takes a long time to login.

**Comment by polo123qwe** [comment]
I'm facing the same issue the same logs in the client on my latop and main rig both running Arch. Disabling the bruteforce-plugin does not seem to fix the issue. The problem triggers on the restart of the program, it doesn't have to be necessarily the whole system. I haven't found a solution yet

**Comment by tflidd** [comment]
Can you try to use the sync client with a test setup in order to find out if the problem is create client- or server-side:
https://help.nextcloud.com/t/demo-instances-of-9-10-11-and-12-now-live/8709

**Comment by polo123qwe** [comment]
The instances seem down for a few days, I have not been able to test it.

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
