### ISSUE TITLE
Typo in german notification to sharer

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#8805]
### Steps to reproduce
1. have german localization and password policy set
2. share a directory to an email address
3. receive an email

### Expected behaviour
Text of that email should be correct

### Actual behaviour
German text of that email contains a typo and misses a whitespace:

> Du hast »DIRECTORY« mit EMAIL-ADDRESS geteilt. Die Freigabe wurde an den Empfenger gesandt. Aufgrund der Sicherheits-Richtlinien die vom Administrator von Nextcloud von SERVERNAMEvorgegeben wurden, benötigt jede Freigabe einen Passwortschutz und es ist nicht zulässig, ein Passwort direkt an den Empfänger zu versenden. Aus diesem Grund musst Du das Passwort selbst an den Empfänger senden.

- The first "Empfenger" is spelled wrongly, should read "Empfänger" (as repeated twice correctly afterwards.
- After SERVERNAME (custom string set in prefs), there should be a whitespace.

**Comment by MariusBluem** [comment]
Translations are handled via Transifex: https://www.transifex.com/nextcloud

**Comment by MariusBluem** [comment]
Translations are handled via Transifex: https://www.transifex.com/nextcloud

**Comment by nursoda** [comment]
The above URL yields 404, correct URL is https://www.transifex.com/nextcloud/nextcloud/dashboard/
However, I cannot find the proper resource, and I seem to be too dumb to search it.

**Comment by nursoda** [comment]
Found it by browsing an guessing:
https://www.transifex.com/nextcloud/nextcloud/translate/#de/sharebymail/111703636
However, I cannot change it, only save a suggestion. Who ist going to review/accept it?
