### ISSUE TITLE
Quota Exceeding - Upload large file, Delete then Restore files.

### ISSUE THREAD

**Issue by phlbrz** [nextcloud/server#8812]
### Steps to reproduce
1. Have a quota like 1GB
2. Upload large files less than your quota
3. Delete large files (they go to the deleted files)
4. Upload more large files or something that is less than your quota
5. Restore files from deleted files.

### Expected behaviour
Quota limit reached and don't alow to restore the deleted files.

### Actual behaviour
The user has the quota limit greater than it's allowed.

### Server configuration

**Nextcloud version:** Docker image latest version - Nextcloud 13.
Updated from an older Nextcloud/ownCloud or fresh install: Fresh

**Where did you install Nextcloud from:** Docker hub.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
None
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
None
```
</details>

**Are you using external storage, if yes which one:** nfs

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
None
```
</details>

### Client configuration
**Browser:** Chrome

**Operating system:** Linux Debian 9

#### Web server error log
<details>
<summary>Web server error log</summary>

```
None
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Can't get yet.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
None
```
</details>

**Comment by MorrisJobke** [comment]
Duplicate of #504
