### ISSUE TITLE
Feature Request: Path-independent link which opens file if method available

### ISSUE THREAD

**Issue by bodangren** [nextcloud/server#8814]
Running NC13 on Ubuntu 16.04 / Apache

Sharing the URL of a file doesn't work unedited unless the recipient's path matches my own (often not the case), but deleting the path from the URL and leaving the fileid allows the recipient to open the containing folder consistently. 

Steps to reproduce:
1. Copy file URL
2. Send to the recipient which has rights on that file
3. Recipient opens link
4. Link fails if the recipient's path doesn't match my own

Workaround
1. Copy URL
2. Paste URL
3. Manually delete all path information, leaving fiileid
4. Recipient clicks and can open the folder containing that file

Request
1. Click "Share by fileid" in Sharing
2. Paste URL and send
3. Recipient clicks and can open or view the file itself (instead of the containing folder) if Nextcloud knows how to do this via app.

**Comment by blizzz** [comment]
There's a nice icon that copies a path-independent share url into your clipboard

![screenshot_20180314_101430](https://user-images.githubusercontent.com/2184312/37393117-7df9c41a-2770-11e8-94e6-7e5e3dd94334.png)
