### ISSUE TITLE
Admin Account Restriction

### ISSUE THREAD

**Issue by Oz246** [nextcloud/server#8817]
Hello,

First of all, sorry for my english translator.

I want to create an Administrator user with restricted rights in section "Administration"

I explain myself I use the application Group folders which can not be limited to a group

I would like a user to access the "Group Folder" section in "Administration"

**Comment by MorrisJobke** [comment]
Please report this in the groupfolder repo: https://github.com/nextcloud/groupfolders/issues

cc @icewind1991
