### ISSUE TITLE
Show consistency of in-folder and out-of-folder search results

### ISSUE THREAD

**Issue by HandsomeBoby** [nextcloud/server#8819]
### Steps to reproduce
1.Upload the same file in different folders, such as 1116.txt
2.Select the search box and search for "116"
![image](https://user-images.githubusercontent.com/19202505/37398145-7ecee148-27b8-11e8-9486-eeabb5c0d140.png)

3.Some errors occurred when I continued to search for "1166"
![image](https://user-images.githubusercontent.com/19202505/37398194-ab8030ac-27b8-11e8-92a5-a035c1e7e82d.png)

### Expected behaviour
Tell us what should happen
Disappear together with the top or exist at the same time
### Actual behaviour
Tell us what happens instead
The top does not exist, but the following has been displayed
### Server configuration

**Operating system**:

**Web server:**Nextcloud 13.

**Database:**MariaDB

**PHP version:**PHP 7.0.22-0ubuntu0.16.04.1 

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by HandsomeBoby** [comment]
@MorrisJobke  @blizzz  I need some help. Thanks.

**Comment by blizzz** [comment]
Not sure what you mean with expected and actual behaviour. Do you want the whitespace to be gone?

**Comment by HandsomeBoby** [comment]
@blizzz I think search results should disappear at the same time, but now is a disappearance, a presence.

**Comment by skjnldsv** [comment]
@HandsomeBoby still happening?
I don't understand your last comment.

**Comment by skjnldsv** [comment]
@HandsomeBoby it will be fixed by #9917
The global search needs to move. Nonetheless searching for files should also appear in the same location as the others file, I agree.
This will probably be fixed in 15 as well.

**Comment by MorrisJobke** [comment]
Let's move it to 17.

**Comment by skjnldsv** [comment]
Fixed nc20
