### ISSUE TITLE
Display issues when creating a new text file

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [nextcloud/server#8823]
### Steps to reproduce
1. Enter a folder via the web interface of nextcloud
2. Select "+" > "New text file"
3. Enter a name (e.g. "Test.txt")
4. Confirm with enter/return
5. Close the editor windows opened by the previous action

### Expected behaviour
The file list will show a new file named "Test.txt".

### Actual behaviour
The file list will show two files named "/path/to/the/folder/Test.txt"

![image](https://user-images.githubusercontent.com/4992119/37409108-d157526c-279d-11e8-8a56-08253dc5f58c.png)

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated several times

**Where did you install Nextcloud from:** Web updater

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
    [
            "apps",
            "activity",
            "disabled"
        ],
        [
            "apps",
            "audioplayer",
            "2.2.5"
        ],
        [
            "apps",
            "bruteforcesettings",
            "1.0.3"
        ],
        [
            "apps",
            "comments",
            "disabled"
        ],
        [
            "apps",
            "conversations",
            "disabled"
        ],
        [
            "apps",
            "dav",
            "1.4.6"
        ],
        [
            "apps",
            "federatedfilesharing",
            "1.3.1"
        ],
        [
            "apps",
            "federation",
            "disabled"
        ],
        [
            "apps",
            "files",
            "1.8.0"
        ],
        [
            "apps",
            "files_gpxviewer_extended",
            "disabled"
        ],
        [
            "apps",
            "files_locking",
            "disabled"
        ],
        [
            "apps",
            "files_pdfviewer",
            "1.2.0"
        ],
        [
            "apps",
            "files_sharing",
            "1.5.0"
        ],
        [
            "apps",
            "files_texteditor",
            "2.5.1"
        ],
        [
            "apps",
            "files_trashbin",
            "1.3.0"
        ],
        [
            "apps",
            "files_versions",
            "disabled"
        ],
        [
            "apps",
            "files_videoplayer",
            "1.2.0"
        ],
        [
            "apps",
            "files_videoviewer",
            "disabled"
        ],
        [
            "apps",
            "firstrunwizard",
            "disabled"
        ],
        [
            "apps",
            "gallery",
            "18.0.0"
        ],
        [
            "apps",
            "galleryplus",
            "disabled"
        ],
        [
            "apps",
            "gpxpod",
            "2.2.2"
        ],
        [
            "apps",
            "logreader",
            "2.0.0"
        ],
        [
            "apps",
            "lookup_server_connector",
            "1.1.0"
        ],
        [
            "apps",
            "metadata",
            "0.6.0"
        ],
        [
            "apps",
            "nextcloud_announcements",
            "disabled"
        ],
        [
            "apps",
            "notifications",
            "disabled"
        ],
        [
            "apps",
            "oauth2",
            "1.1.0"
        ],
        [
            "apps",
            "ownnote",
            "disabled"
        ],
        [
            "apps",
            "password_policy",
            "disabled"
        ],
        [
            "apps",
            "previewgenerator",
            "disabled"
        ],
        [
            "apps",
            "provisioning_api",
            "disabled"
        ],
        [
            "apps",
            "radio",
            "0.6.1"
        ],
        [
            "apps",
            "serverinfo",
            "1.3.0"
        ],
        [
            "apps",
            "sharebymail",
            "disabled"
        ],
        [
            "apps",
            "sharerenamer",
            "disabled"
        ],
        [
            "apps",
            "survey_client",
            "1.1.0"
        ],
        [
            "apps",
            "systemtags",
            "disabled"
        ],
        [
            "apps",
            "tasks",
            "0.9.6"
        ],
        [
            "apps",
            "templateeditor",
            "disabled"
        ],
        [
            "apps",
            "theming",
            "1.4.1"
        ],
        [
            "apps",
            "twofactor_backupcodes",
            "1.2.3"
        ],
        [
            "apps",
            "updatenotification",
            "1.3.0"
        ],
        [
            "apps",
            "updater",
            "disabled"
        ],
        [
            "apps",
            "workflowengine",
            "1.3.0"
        ],
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 64.0.3282.186

**Operating system:** Windows 10 1709

#### Browser log
<details>
<summary>Browser log</summary>
merged.js?v=1e745403-67:20307 Uncaught Error: ace.edit can't find div #sidebar_editor
    at Object.exports.edit (merged.js?v=1e745403-67:20307)
    at Object.<anonymous> (merged.js?v=1e745403-67:752)
    at Object.<anonymous> (core.js?v=1e745403-67:2)
    at j (core.js?v=1e745403-67:2)
    at Object.fireWith [as resolveWith] (core.js?v=1e745403-67:2)
    at x (core.js?v=1e745403-67:4)
    at XMLHttpRequest.<anonymous> (core.js?v=1e745403-67:4)
exports.edit @ merged.js?v=1e745403-67:20307
(anonymous) @ merged.js?v=1e745403-67:752
(anonymous) @ core.js?v=1e745403-67:2
j @ core.js?v=1e745403-67:2
fireWith @ core.js?v=1e745403-67:2
x @ core.js?v=1e745403-67:4
(anonymous) @ core.js?v=1e745403-67:4
XMLHttpRequest.send (async)
send @ core.js?v=1e745403-67:4
ajax @ core.js?v=1e745403-67:4
getFileContent @ merged.js?v=1e745403-67:788
handlePreview @ merged.js?v=1e745403-67:743
loadPreview @ merged-index.js?v=1e745403-67:8555
render @ merged-index.js?v=1e745403-67:9025
setFileInfo @ merged-index.js?v=1e745403-67:8982
(anonymous) @ merged-index.js?v=1e745403-67:9267
_.each._.forEach @ core.js?v=1e745403-67:166
setFileInfo @ merged-index.js?v=1e745403-67:9266
_updateDetailsView @ merged-index.js?v=1e745403-67:4674
showDetailsView @ merged-index.js?v=1e745403-67:4623
(anonymous) @ merged-index.js?v=1e745403-67:6853
(anonymous) @ core.js?v=1e745403-67:781
setTimeout (async)
_.delay @ core.js?v=1e745403-67:780
executeBound @ core.js?v=1e745403-67:714
bound @ core.js?v=1e745403-67:746
scrollTo @ merged-index.js?v=1e745403-67:6852
add @ merged-index.js?v=1e745403-67:5572
(anonymous) @ merged-index.js?v=1e745403-67:6671
(anonymous) @ core.js?v=1e745403-67:2
j @ core.js?v=1e745403-67:2
fireWith @ core.js?v=1e745403-67:2
e.(anonymous function) @ core.js?v=1e745403-67:2
(anonymous) @ client.js?v=1e745403-67:598
Promise.then (async)
getFileInfo @ client.js?v=1e745403-67:595
addAndFetchFileInfo @ merged-index.js?v=1e745403-67:6665
(anonymous) @ merged-index.js?v=1e745403-67:6541
j @ core.js?v=1e745403-67:2
fireWith @ core.js?v=1e745403-67:2
e.(anonymous function) @ core.js?v=1e745403-67:2
(anonymous) @ client.js?v=1e745403-67:679
Promise.then (async)
putFileContents @ client.js?v=1e745403-67:676
createFile @ merged-index.js?v=1e745403-67:6531
actionHandler @ merged.js?v=1e745403-67:690
(anonymous) @ merged-index.js?v=1e745403-67:1732
dispatch @ core.js?v=1e745403-67:3
r.handle @ core.js?v=1e745403-67:3
preview.png:1 GET https://<HOST>/core/preview.png?file=%2FTemp%2FTest.txt&c=3553b3c15d7fd2c93ec60fcef46ef23d&x=32&y=32&forceIcon=0 404 ()
Image (async)
lazyLoadPreview @ merged-index.js?v=1e745403-67:6052
_renderRow @ merged-index.js?v=1e745403-67:5645
add @ merged-index.js?v=1e745403-67:5556
(anonymous) @ merged-index.js?v=1e745403-67:6671
(anonymous) @ core.js?v=1e745403-67:2
j @ core.js?v=1e745403-67:2
fireWith @ core.js?v=1e745403-67:2
e.(anonymous function) @ core.js?v=1e745403-67:2
(anonymous) @ client.js?v=1e745403-67:598
Promise.then (async)
getFileInfo @ client.js?v=1e745403-67:595
addAndFetchFileInfo @ merged-index.js?v=1e745403-67:6665
(anonymous) @ merged-index.js?v=1e745403-67:6541
j @ core.js?v=1e745403-67:2
fireWith @ core.js?v=1e745403-67:2
e.(anonymous function) @ core.js?v=1e745403-67:2
(anonymous) @ client.js?v=1e745403-67:679
Promise.then (async)
putFileContents @ client.js?v=1e745403-67:676
createFile @ merged-index.js?v=1e745403-67:6531
actionHandler @ merged.js?v=1e745403-67:690
(anonymous) @ merged-index.js?v=1e745403-67:1732
dispatch @ core.js?v=1e745403-67:3
r.handle @ core.js?v=1e745403-67:3
preview.png:1 GET https://<HOST>/core/preview.png?file=%2FTemp%2FTest.txt&c=1521171646&x=32&y=32&forceIcon=0 404 ()
```
</details>

**Comment by supermanlinux** [comment]
Have you solved this questions? I have the same question with you.

**Comment by arevindh** [comment]
Same here, any solutions?
