### ISSUE TITLE
Display code coverage

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#883]
To prevent major problems such as https://github.com/nextcloud/server/pull/882 again we _MUST_ display the code coverage somewhere so that we can notice such…

cc @MorrisJobke

**Comment by rullzer** [comment]
Yes! But please once we have drone .5 so we can run the tests in parallel...

**Comment by MorrisJobke** [comment]
Yes. I will look into this after the release

**Comment by MorrisJobke** [comment]
Fixes via #1561
