### ISSUE TITLE
Password policy not checked on passwords created with 'share by link'

### ISSUE THREAD

**Issue by ArjanDeVries** [nextcloud/server#8834]
**Steps to reproduce:**
This is not so easy because generated passwords are not always wrong.
But the idea is that you share a folder by supplying an e-mail.

**Expected behaviour:**
You would expect that the user that is receiving the link gets also a password that matches the password policy.

**Actual behaviour:**
It seems that passwords generated by the autoGeneratePassword function in the ShareByMailProvider.php script are not checked on complexity.

It uses this function to generate a password:
$password = $this->secureRandom->generate($passwordLength, $passwordCharset);

So the outcome of the password could be a very simple password although the Charset can contain many complex chars.

**Nextcloud version:**
We are running on Nextcloud version 12.0.4

Regards,
Arjan de Vries

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing

**Comment by rullzer** [comment]
Well the password policy app has no function to handle this yet. Anyway in 13 we also add special chars if needed.

But having said all that. NIST actually suggest to only use length for a password. So lets assume we are only using lowercase, uppercase and digits. An a length of 8 (again as suggested by NIST). This already gives us 62^8 possible passwords. That is 218340105584896 possible passwords. This already seems more than secure enough to me ;)

**Comment by ArjanDeVries** [comment]
It's not only about the complexity but users reported also that the password did not work. So i suspect that it causes more problems.

**Comment by rullzer** [comment]
Well that is a different issue and should be fixed.

My point was that just because it doesn't use fancy weird chars doesn't mean it is insecure ;)

**Comment by szaimen** [comment]
I think this was fixed in the meantime. Please reopen I should be wrong
