### ISSUE TITLE
Where is my trashbin?

### ISSUE THREAD

**Issue by LaTecnologia24** [nextcloud/server#8836]
After update to 13.0.1 if delete file this is permanent deleted and recycle say: Empty.

/index.php/apps/files/?dir=/&view=trashbin

'trashbin_retention_obligation' => 'auto',

**Comment by ChristophWurst** [comment]
Any updates, @LaTecnologia24? Could you resolve this somehow?

**Comment by LaTecnologia24** [comment]
> 
> 
> Any updates, @LaTecnologia24? Could you resolve this somehow?

Sorry i have delete it, too complicated and less stable for me..
