### ISSUE TITLE
Return free disk space if quota is set to unlimited

### ISSUE THREAD

**Issue by KopfKrieg** [nextcloud/server#8838]
Currently, if there's no quota set (alias "unlimited"), users don't know how much free space is available on the server.

It would be nice, if nextcloud would return the free space if the quota is set to unlimited. Currently, this can be simulated by setting the quota > disk space.

**Comment by MorrisJobke** [comment]
The propfind will always return the quota type like this:

```xml
<d:quota-available-bytes>-3</d:quota-available-bytes>
```

But if you query the users API `https://HOST/ocs/v1.php/cloud/user` for example you will get the remaining bytes:

```xml
<?xml version="1.0"?>
<ocs>
	<meta>
		<status>ok</status>
		<statuscode>100</statuscode>
		<message>OK</message>
		<totalitems></totalitems>
		<itemsperpage></itemsperpage>
	</meta>
	<data>
		<enabled>true</enabled>
		<id>admin</id>
		<quota>
			<free>145686192128</free>
			<used>164</used>
			<total>145686192292</total>
			<relative>0</relative>
			<quota>-3</quota>
		</quota>
		<email/>
		<phone></phone>
		<address></address>
		<website></website>
		<twitter></twitter>
		<groups>
			<element>admin</element>
		</groups>
		<language>en</language>
		<display-name>admin</display-name>
	</data>
</ocs>
```

@icewind1991 @rullzer would it make sense to add this to the PROPFIND as well?
