### ISSUE TITLE
Support of contact photo image sources from LDAP

### ISSUE THREAD

**Issue by ingoj** [nextcloud/server#8840]
Hi!

In NC everyone can upload a contact photo to own profile. 

In enterprise environments contact photos can also be stored in LDAP/AD or be a URI stored in a LDAP/AD attribute. 

For example when using Cisco Jabber we use in our enterprise environment the AD attribute "url" to store an URI from where Cisco Jabber downloads the contact photo. 
Basically there are 3 different contact photo sources: 
1) photo stored as binary in AD
2) photo URI substitution: an URI is expanded by substituting a place holder in an URI, like sAMAccountName in the URI http://example.org/contactphotos/%%sAMAccountName%%.jpg
3) photo URI pointing directly to a photo on a webserver (each photo can be located on a different webserver, which is very handy for very large, multiple company enterprises), e.g. http://example.org/photo/user_1.jpg and http://anotherexample.com/users/user_2.png

I think this would be best supported in the LDAP user backend as an configurable option. When set properly NC should then download and display the contact photos from the configured source. 
This way enterprise users will get a consistent experience of contact photos.

**Comment by MorrisJobke** [comment]
This is already possible AFAIK - cc @nextcloud/ldap

**Comment by MorrisJobke** [comment]
> photo stored as binary in AD

That's what I meant.

**Comment by ingoj** [comment]
Well, stored as binary in AD is not possible in our enterprise enviroment. The AD size would be too large to sync to every tree in the AD forest over satellite links, especially because we have regular changes in contact photos for hundreds or thousands of employees, when the crew on board of our ships is changing.

**Comment by MorrisJobke** [comment]
Thanks for the background details. It is now listed as enhancement but not on the roadmap anytime soon as far as I see.

If you want to have this feature in a short period of time Nextcloud GmbH offers consulting work for features like this. Feel free to contact the sales team for example here: https://nextcloud.com/enterprise/buy/

**Comment by awesome-manuel** [comment]
Just for info: https://docs.nextcloud.com/server/13/admin_manual/configuration_user/user_auth_ldap.html#nextcloud-avatar-integration

**Comment by MorrisJobke** [comment]
Let's close this for now. As I have written above already: it's not on the roadmap. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
