### ISSUE TITLE
Avatar replacement character for accentuated letter is not centered

### ISSUE THREAD

**Issue by biva** [nextcloud/server#8841]
NC 13.0.1 includes https://github.com/nextcloud/server/pull/8468 that does correct https://github.com/nextcloud/server/issues/8451 but the avatar is not centered correctly. The accent should not be taken into account to position the letter in the circle.

For example the bottom bar of "É" should be on the same horizontal level as "E". And it's not, because the accent is taken into account to position the letter in the circle. Unexpected result: "É" is positionned too low.

![image](https://user-images.githubusercontent.com/9964305/37485204-e35338ba-289b-11e8-8c30-f0336946b959.png)

**Comment by MorrisJobke** [comment]
We fetch the bounding box of the character here: 

https://github.com/nextcloud/server/blob/f83aa58d1f82beee86d3e91f390efb48b98a52e0/lib/private/Avatar.php#L277

If somebody want to look into this: feel free

**Comment by MorrisJobke** [comment]
Naive approach: having a set of replacement characters that is used to fetch the bounding box. Best would be to base everything on the baseline of the font, but I don't know if this is somehow extractable with the library.

**Comment by MeCias** [comment]
Those without accent doesn't look centered either. Slightly too much right.

![f](https://user-images.githubusercontent.com/4476171/37520869-fd77769c-291e-11e8-888b-cc79faaefb99.jpg)
