### ISSUE TITLE
Links to pull requests in changelog are wrong

### ISSUE THREAD

**Issue by jones1008** [nextcloud/server#8845]
I just noticed that the links to the pull request under "Changes" in the nextcloud changelog have a typo in it.
changelog: https://nextcloud.com/changelog/
wrong link example:
`https://github.com/nextcloud/server/pulls/8045`
correct link should be:
`https://github.com/nextcloud/server/pull/8045`

The typo is just a `s` after the word pull...

the wrong link performs a search in the pull request section with the parameters:
`is:open is:pr author:8045 `

The links are only wrong under the Changes of Version 13.0.1 and 12.0.6.

**Comment by MorrisJobke** [comment]
Fixed with https://github.com/nextcloud/nextcloud.com/pull/828

Thanks for the heads up
