### ISSUE TITLE
 Problem with shared url preview

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#8848]
I noticed that when I share a nextcloud url via telegram or whatsapp and various 
it generates a preview with the nextcloud logo 
and does not resume instead the site's "favicon" logo is normal?

then even if it is nextcloud in Italian
the words "a safe home for all your data" will always remain in English 
in the preview as you can see from the attached image.

![immagine](https://user-images.githubusercontent.com/35575744/37512759-524f23a2-2903-11e8-8f78-3a05c08026dd.png)

**Comment by tigernero79** [comment]
in the picture is telegram. but with whatsapp same thing. sharing leaves written in English and not in the set language of nectcloud. option to force the language is in the config file?

**Comment by rullzer** [comment]
yes; https://github.com/nextcloud/server/blob/master/config/config.sample.php#L179

I think telegram and whatsapp do the same then. They probably send english as the default requested language or something.

**Comment by rullzer** [comment]
This is indeed telegram and whatsapp by default requesting in english. So force_language is the only option else we break it all..
