### ISSUE TITLE
Public Theming API

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#885]
We need a public API for theming 🎨 ... This would make it possible that external apps can use the theme values. We've already discussed the use-case (e.g. for the android app) here: https://github.com/nextcloud/android/pull/213

cc @juliushaertl @AndyScherzinger @Bugsbane @nextcloud/designers

**Comment by Bugsbane** [comment]
Totally agree. This is necessary for consistency of branding, especially for more enterprise style use.

**Comment by MorrisJobke** [comment]
Implemented in #1272
