### ISSUE TITLE
Copymove has a question

### ISSUE THREAD

**Issue by HandsomeBoby** [nextcloud/server#8851]
### Steps to reproduce
1.Create a folder and create a file in the folder (optional), add a favorite to this file
![image](https://user-images.githubusercontent.com/19202505/37515470-e3a4cfc2-2945-11e8-9348-19ad3f61318e.png)
2.In the Recent(Favorites) list, an error occurred while moving or copying the file
![image](https://user-images.githubusercontent.com/19202505/37515603-3d125c14-2946-11e8-9053-46e2bf9ff538.png)
![image](https://user-images.githubusercontent.com/19202505/37515620-4c4c9d02-2946-11e8-90ea-697e60c70761.png)
3.Copy is the same mistake

### Expected behaviour
Tell us what should happen
Can Copy/Move
### Actual behaviour
Tell us what happens instead
do not Copy/Move
### Server configuration

**Operating system**:

**Web server:**Nextcloud13

**Database:**MariaDB

**PHP version:**PHP 7.0.22-0ubuntu0.16.04.1

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**fresh install

**Where did you install Nextcloud from:**github

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by HandsomeBoby** [comment]
@MorrisJobke @blizzz Thanks!

**Comment by blizzz** [comment]
Anything in your nextcloud and/or browser log?

**Comment by HandsomeBoby** [comment]
@blizzz  
No，In the my nextcloud server log,I did not find any log information.This makes me very confused.

**Comment by HandsomeBoby** [comment]
@MorrisJobke @blizzz @nextcloud/sharing @skjnldsv @danxuliu
I need some help.

**Comment by MorrisJobke** [comment]
Could you provide a test account (send it to the mail address on my GitHub page)

**Comment by skjnldsv** [comment]
@HandsomeBoby we need your browser network log :)

**Comment by supermanlinux** [comment]
@MorrisJobke @skjnldsv I have the same problems.The test account I have sent to MorrisJobke's  mail address.Thanks for help.

**Comment by skjnldsv** [comment]
@supermanlinux you can also paste here a screenshot of the network request tab when your error occurs :)

(F12 -> Network (and if there is a red failed request: -> click on it and copy/paste the response tab here)

**Comment by MorrisJobke** [comment]
Request: `COPY remote.php/webdav/fdf.ods` but the files is in `learn/fdf.ods`.
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name fdf.ods could not be located</s:message>
</d:error>
```

Path seems to be wrong on the filtered views. Hovering the file shows the correct path set in the link itself:

<img width="294" alt="bildschirmfoto 2018-03-22 um 14 38 33" src="https://user-images.githubusercontent.com/245432/37773780-c4c4df50-2dde-11e8-934f-a237d000f03c.png">
