### ISSUE TITLE
Using files_external on s3, no indication of the file being uploaded is displayed

### ISSUE THREAD

**Issue by davideapvd** [nextcloud/server#8859]
### Steps to reproduce
1. create an external storage on s3
2. upload a big file on that directory

### Expected behaviour
Possibility to display file upload progress and cancel the file upload

### Actual behaviour
The file is first uploaded to the local tmp directory and the frontend displays the progress, when the file is fully uploaded to the remote tmp directory the progress and possibility to cancel the upload disappears, now the file beging being uploaded to the remote s3 storage.

### Server configuration

**Nextcloud version:**  13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Comment by MorrisJobke** [comment]
Fixed by #9124 and #9085 in 13.0.2
