### ISSUE TITLE
Suggestion: Add a boolean config for web gui: show right side panel

### ISSUE THREAD

**Issue by winstonford** [nextcloud/server#8860]
In the web gui, add a boolean config parameter to show the right side panel by default.

Perhaps add another level: If show side panel is true, show: comments, share, OR activity.

https://help.nextcloud.com/t/how-to-config-web-gui-to-show-right-side-panel-by-default/29060

**Comment by rullzer** [comment]
Not more options please. If this is a good idea just do it.

**Comment by juliushaertl** [comment]
It would make sense to at least show it by default on large screens where there is enough space.

**Comment by skjnldsv** [comment]
@juliushaertl there's already an issue for that I believe! :)

**Comment by juliushaertl** [comment]
Found it https://github.com/nextcloud/server/issues/7138

**Comment by rullzer** [comment]
Then lets continue there.
