### ISSUE TITLE
Popup for last login in user management misaligned

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#8862]
* activate the "last login" column in the settings of the user management
* hover over the date

<img width="245" alt="bildschirmfoto 2018-03-15 um 10 02 04" src="https://user-images.githubusercontent.com/245432/37542884-f4e28616-295f-11e8-9817-0b4ff7d57ffc.png">

Maybe from @nextcloud/designers could have a look.

This is on 13.0.1

**Comment by KeroroLulu** [comment]
I would like to work on it, where should I start ?

**Comment by skjnldsv** [comment]
I'll fix it on the new users page
