### ISSUE TITLE
Update to 13.0.1 via web updater failed: unable to write in ocs

### ISSUE THREAD

**Issue by Wenzel** [nextcloud/server#8866]
### Steps to reproduce
1. start the update process via web updater
2. web updater reports that it cannot write to some locations in `updater/../console.php`, etc...
3. fix the permissions by giving write access to `www-data`
4. run the updater again
5. everything is fine until the step after `extracting`
6. the updater reports permissions denied in `ocs/v1.php`

### Expected behaviour
The updater should have finished the update process without any issue.

### Actual behaviour
At first it failed checking for write permissions.
I fixed the permissions by doing a `chmod 660` on the files in `updater/../` (`*.php, index.html, .user.ini, .htaccess`)
At the next attempt it failed on the step after `extracting` (i can't remember the name of the step)
because it cannot write into the `ocs` directory

**My Nextcloud is broken at the moment because of this**
`update in process` is all that is returned.

The web updater can break instances and needs to be improved.

### Server configuration

**Operating system**: Debian stretch

**Web server:** Nginx

**Database:** Postgresql

**PHP version:** 7.0.27-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page) 13, but i can't access my nextcloud now

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** zip archive

```
I cannot access my nextcloud instance anymore
it says "update in process"
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - spreed
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.wzl.ovh"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.wzl.ovh",
        "dbtype": "pgsql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using encryption:** no

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2018/03/17 16:09:26 [error] 23247#23247: *128094 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/var/www/nextcloud/updater/../ocs/v1.php): failed to open stream: Permission denied in /var/www/nextcloud/updater/index.php on line 807" while reading response header from upstream, client: 185.159.158.100, server: cloud.wzl.ovh, request: "POST /updater/index.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "cloud.wzl.ovh"
```
</details>

My nextcloud is broken now ...
Please help me repair it :(

**Comment by Wenzel** [comment]
I trashed my broken nextcloud instance, and downloaded a new one from the zip.
It's still an issue thought, and i'm not going to use this web updater anymore.

**Comment by MorrisJobke** [comment]
> the updater reports permissions denied in ocs/v1.php

The question here is why it has problems with the permissions. We will integrate an improved check for permissions especially with symlinks and problems with permissions in the root folder.  See https://github.com/nextcloud/updater/pull/165 for example

For further problems: please report them to https://github.com/nextcloud/updater/issues
