### ISSUE TITLE
MP3 and FLAC modified after transfer via nextcloud webinterface

### ISSUE THREAD

**Issue by sankayop** [nextcloud/server#8868]
### Steps to reproduce
1. drag and drop a .mp3 or .flac file from your local computer to the nextcloud file interface 
2. If you click on the file inside the interface, it will run properly (the music is playing correctly)
3. I have minidlna 1.2.1-1 running on the same server, having access to the nextcloud folder containing the musics => service minidlna stop / rescan => FLAC metadata not recognized in the /var/log/minidlna.log and no comment concerning mp3 file except the file exists => +/- ok
4. Files visible via upnp client but when the song is selected for playing, nothing is playing.
5. If the same file is being transfered by scp (terminal) to the same nextcloud folder, the file is being read/played properly.

In summary, problem is not correlated to music file type (both mp3 and flac) And problem occurs when transfer via nextcloud webinterface and not via scp terminal transfer.

### Expected behaviour
The music file should be played by minidlna the same way it is by nextcloud.

### Actual behaviour
The file is found by minidlna but for both mp3 and flac, the file can not be played via minidlna.

### Server configuration
**Operating system**:
FreeBSD 11.1-RELEASE-p4 FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

**Web server:**
nginx 1.12.2

**Database:**
mysql 5.6.39

**PHP version:**
php 7.1.15

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from Owncloud 8.0, ... Nextcloud all versions...

**Where did you install Nextcloud from:**
from the included updater

**Signing status:**
<details>
<summary>Signing status</summary>
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Done:
"No errors have been found."
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
.../nextcloud$ sudo -u www php occ app:list
PHP Warning:  Module 'session' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'json' already loaded in Unknown on line 0
PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0
PHP Warning:  Module 'mysqli' already loaded in Unknown on line 0
PHP Warning:  Module 'redis' already loaded in Unknown on line 0
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - audioplayer: 2.2.5
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_rightclick: 0.3.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - gpxpod: 2.2.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - onlyoffice: 1.2.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - ransomware_protection: 1.1.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - files_clipboard
  - spreed
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe",
        "installed": true,
        "loglevel": 3,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false,
        "theme": "",
        "auth.bruteforce.protection.enabled": false,
        "updater.release.channel": "stable",
        "app.mail.imaplog.enabled": true,
        "app.mail.smtplog.enabled": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
webdav i think?! at least for the tablets and smartphones' access.
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.  
</details>

### Client configuration
**Browser:**
Firefox 58.0.2 (64-bit) for linux mint 1.0
**Operating system:**
Linux Mint 18.3 Cinnamon 64-bit (Cinnamon 3.6.7)
Linux 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
#### Minidlna error log
<details>
<summary>Minidlna error log</summary>
[2018/03/18 15:43:29] minidlna.c:1051: warn: Starting MiniDLNA version 1.2.1.
[2018/03/18 15:43:29] minidlna.c:347: warn: Creating new database at .../miniDlnaDB/files.db
[2018/03/18 15:43:29] minidlna.c:1101: warn: HTTP listening on port 8200
[2018/03/18 15:43:29] scanner.c:731: warn: Scanning .../nextcloud/data/xmen/files/us_Music/test
[2018/03/18 15:43:29] tagutils/tagutils-flc.c:41: error: Cannot extract tag from .../nextcloud/data/xmen/files/us_Music/test/01 - Unknown.flac [FLAC__METADATA_SIMPLE_ITERATOR_STATUS_NOT_A_FLAC_FILE]
[2018/03/18 15:43:29] scanner.c:820: warn: Scanning .../nextcloud/data/xmen/files/us_Music/test finished (2 files)!
[2018/03/18 15:43:29] playlist.c:135: warn: Parsing playlists...
[2018/03/18 15:43:29] playlist.c:269: warn: Finished parsing playlists.
[2018/03/18 15:49:52] minidlna.c:156: warn: received signal 15, good-bye
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
xmen@xmenServer:~$ cat nextcloud.log.copy 
{"reqId":"fIrWvqktQraRnP7l6RM1","level":3,"time":"2018-03-18T15:06:06+01:00","remoteAddr":"x.x.x.x","user":"xmen","app":"PHP","method":"GET","url":"\/apps\/gallery\/config?extramediatypes=1","message":"Module 'redis' already loaded at Unknown#0","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"7ilcwKXsvC1r5MJkq5OL","level":3,"time":"2018-03-18T15:48:59+01:00","remoteAddr":"x.x.x.x","user":"xmen","app":"PHP","method":"GET","url":"\/core\/preview.png?file=%2Fus_Music%2Ftest%2Fplop.mp3&c=36fc5b0b2964081fc50cbf1313eb281a&x=32&y=32&forceIcon=0","message":"fopen(...\/nextcloud\/data\/xmen\/files\/us_Music\/test\/plop.mp3): failed to open stream: No such file or directory at ...\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#282","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"7ilcwKXsvC1r5MJkq5OL","level":3,"time":"2018-03-18T15:48:59+01:00","remoteAddr":"x.x.x.x","user":"xmen","app":"PHP","method":"GET","url":"\/core\/preview.png?file=%2Fus_Music%2Ftest%2Fplop.mp3&c=36fc5b0b2964081fc50cbf1313eb281a&x=32&y=32&forceIcon=0","message":"unlink(): No such file or directory at ...\/nextcloud\/lib\/private\/Preview\/MP3.php#47","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"hse129KDz69TA99CU77t","level":3,"time":"2018-03-18T15:49:02+01:00","remoteAddr":"x.x.x.x","user":"xmen","app":"PHP","method":"GET","url":"\/core\/preview.png?file=%2Fus_Music%2Ftest%2Fplop.mp3&c=36fc5b0b2964081fc50cbf1313eb281a&x=32&y=32&forceIcon=0","message":"fopen(\...\/nextcloud\/data\/xmen\/files\/us_Music\/test\/plop.mp3): failed to open stream: No such file or directory at ...\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#282","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"hse129KDz69TA99CU77t","level":3,"time":"2018-03-18T15:49:02+01:00","remoteAddr":"x.x.x.x","user":"xmen","app":"PHP","method":"GET","url":"\/core\/preview.png?file=%2Fus_Music%2Ftest%2Fplop.mp3&c=36fc5b0b2964081fc50cbf1313eb281a&x=32&y=32&forceIcon=0","message":"unlink(): No such file or directory at ...\/nextcloud\/lib\/private\/Preview\/MP3.php#47","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
{"reqId":"xfviQH7zrEqeYP7jqBLJ","level":3,"time":"2018-03-18T16:32:39+01:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Module 'redis' already loaded at Unknown#0","userAgent":"--","version":"13.0.0.14"}
```
</details>

**Comment by sankayop** [comment]
Problem still remaining...

**Comment by MorrisJobke** [comment]
> [2018/03/18 15:43:29] tagutils/tagutils-flc.c:41: error: Cannot extract tag from .../nextcloud/data/xmen/files/us_Music/test/01 - Unknown.flac [FLAC__METADATA_SIMPLE_ITERATOR_STATUS_NOT_A_FLAC_FILE] [2018/03/18 15:43:29]

Okay - this is weird. I'm pretty sure we don't do anything to the file, but ...

> Are you using encryption: yes/no
> yes

... you use encryption. What do you expect? The file is encrypted - no chance that any external service can read it -> closing works as expected.

**Comment by sankayop** [comment]
Thanks for the answer.
Indeed, I never thought of it...
Sorry for the wasted time although.
