### ISSUE TITLE
13.01 does not update to 13.02 if "apps2" is present

### ISSUE THREAD

**Issue by x86dev** [nextcloud/server#8869]
First of all, I'm aware of issue #6723, but I still get the error when wanting to upgrade from 13.01 to 13.02.

My config is as follows:
```
    0 => 
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
```

Can anybody shed some light on the issue? What's the recommended config for those cases to use the internal updater?

**Comment by MorrisJobke** [comment]
There is no 13.0.02 released yet. We released 13.0.1 last week

**Comment by MorrisJobke** [comment]
> #6723

Should be fixed by https://github.com/nextcloud/updater/pull/107


The URL of `apps2` seem to miss the `nextcloud/` in front. Otherwise it looks good.

**Comment by jjholv** [comment]
Hello, reporting that I see this on a fresh install of 14.0.1 when trying to update to 14.0.2

My stock config.php:
```
    0 =>
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
```
Changing  `'path' => '/apps2',` to `'path' => '/nextcloud/apps2',` fixes the issue.
