### ISSUE TITLE
Error when uploading files. (FileInUseException)

### ISSUE THREAD

**Issue by KoenJonguh** [nextcloud/server#8873]
Hi!

**Actual behaviour**
Users that are using my cloud are often getting an error when they upload a file.

**Server configuration**
Operating system: Ubuntu 17.10.1 lts

Web server: Apache3

Database: Mariadb

PHP version: 7.0

Nextcloud version: 13.01

Updated from an older Nextcloud/ownCloud or fresh install: Fresh

Where did you install Nextcloud from:
https://download.nextcloud.com/server/releases/nextcloud-13.0.1.zip

Signing status:

List of activated apps:

App list
Nextcloud configuration:

**Config report:**

I removed the usernames in the images.

![alt text](http://koensweers.com/error-nextcloud/2.png)

![alt text](http://koensweers.com/error-nextcloud/3.png)

![alt text](http://koensweers.com/error-nextcloud/1.png)

**Comment by casKd-dev** [comment]
Check if file permissions are correct, if not tis should need some further investgation.

**Comment by KoenJonguh** [comment]
Hey thanks, Could you tell me how to check the file permissions please?
