### ISSUE TITLE
client "Mozilla/5.0 (Android) ownCloud-android/3.0.3" is not allowed to access end-to-end encrypted content

### ISSUE THREAD

**Issue by hillebr** [nextcloud/server#8884]
### Steps to reproduce
1. create Folder with mobile app and mark it as encrypted
2. try to open this folder and it is showing the encryption passphrase
3. followed by the error: The key could not have been saved. Please try again.

### Expected behaviour
Upload files

### Actual behaviour
I'm not able to open this folder - steps 2 & 3 above are constantly repeating

### Server configuration

**Operating system**: Debian 8.10

**Web server:** Apache 2.4.10

**Database:** MAriaDB 10.1.31

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page) 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud sources

**Are you using external storage, if yes which one:** local only

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
OCA\DAV\Connector\Sabre\Exception\Forbidden: client "Mozilla/5.0 (Android) ownCloud-android/3.0.3" is not allowed to access end-to-end encrypted content
/var/www/html/nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 125: OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkUserAgent('Mozilla/5.0 (An...', '/Test')
[internal function] OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()
/var/www/html/nextcloud/remote.php - line 164: require_once('/var/www/html/n...')
{main}

nextcloud.log:
{"reqId":"nZtT5eNDXMky7EhckuBV","level":4,"time":"2018-03-19T15:22:05+01:00","remoteAddr":"212.211.165.68","user":"rene","app":"webdav","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/Test\/","message":"Exception: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"client \\\"Mozilla\\\/5.0 (Android) ownCloud-android\\\/3.0.3\\\" is not allowed to access end-to-end encrypted content\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php(125): OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkUserAgent('Mozilla\\\/5.0 (An...', '\\\/Test')\\n#1 [internal function]: OCA\\\\EndToEndEncryption\\\\Connector\\\\Sabre\\\\LockPlugin->checkLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/end_to_end_encryption\\\/lib\\\/Connector\\\/Sabre\\\/LockPlugin.php\",\"Line\":170}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.0.3","version":"13.0.1.1"}

**Comment by MorrisJobke** [comment]
cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
> followed by the error: The key could not have been saved. Please try again.

I think this is the root cause and the later error is only because we use the new user agent on encrypted files/folders only.

Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by hillebr** [comment]
...account created & mail sent
with the new created account everything works flawlessly.
Do I have to recreate my account?
Is is an admin account - maybe that`s the Problem?


Thank you!

**Comment by tobiasKaminsky** [comment]
If it is working with your new account, then we "only" have to figure out what the problem is with your existing admin account, so you can delete the test account.

Have you tried e2e previously with the same account, maybe on an early preview?

**Comment by hillebr** [comment]
...yes, I tried e2ee with this account earlier.
After upgrading to 13.0.0 for the first time!
The upgrade was done by switching to beta channel, upgrading and then switching back to stable as it was recommended in the release blog post.

**Comment by hillebr** [comment]
...first test was done with Android 8.1 and the version of Nextcloud app which was the most recent on 13.0.0 release date.

**Comment by tobiasKaminsky** [comment]
There was a bug when the username is not userid, so maybe this is the problem here.
@schiessle do you have any idea how to manually circumvent this user id problem?

**Comment by willofr** [comment]
Hi,
is there any solution to this problem ? Got the same behavior with NC 13.0.4 and 3.1.0 NC Android client.
Works fine only with a new account.

Thanks !
