### ISSUE TITLE
Fresh Install NC 13.0.1 Ubuntu Server, cannot change Theme, nothing happens

### ISSUE THREAD

**Issue by mairsebastian** [nextcloud/server#8888]
hi, 

just installed fresh nc 13.0.1, cannot set theming, colour, background image => nothing happens

have a nc13.0 installation running, where this does not happen.

any ideas?

sebi

**Comment by mairsebastian** [comment]
nobody the same problem??? i love nextcloud, can´t find any information at the logs.

**Comment by JorgeGNL** [comment]
Same issue here, with new installation,(Centos 7, php7.2) I see that Nextcloud demo also have the same issue (https://demo.nextcloud.com/)

**Comment by rullzer** [comment]
@nextcloud/theming

**Comment by skjnldsv** [comment]
I can reproduce! :)
@juliushaertl values are sent and saved, but css is not regenerated :)

**Comment by juliushaertl** [comment]
I'll look into it.

**Comment by juliushaertl** [comment]
Regression due https://github.com/nextcloud/server/pull/8716

Fix is in https://github.com/nextcloud/server/pull/8983
