### ISSUE TITLE
Can't save Richdocuments on external storage not mounted for user

### ISSUE THREAD

**Issue by AlexMaj** [nextcloud/server#8889]
Hi,
I'm not sure if it's a Collabora issue or Nextcloud.
Whenever an office document is shared on an external storage with a user who has not that storage available/mounted, that user can open the file, type in it, but can't save (Message "the document can't be saved")

If you share a simple text document on the same storage everything's ok, user can open, edit and save.

If you mount that storage (available) for the second user then everything's ok.

I've tried with docker version, packaged version, compiled version, every time same behavior.
I've tried with OnlyOffice it works (but force user to convert files... that's why I prefer Collabora)

### Steps to reproduce

1. Create an external storage (Local or smb) named ExtStorage, make it available for Group1
2. Log in with User1 (who is in Group1)
3. Create a spreadsheet.ods in ExtStorage and share it (full access) with User2 (who is not in Group1)
4. Log in with User2, you see spreadsheet.ods, open it and edit it, try to save your work

### Expected behaviour
file should be saved

### Actual behaviour
file is not saved

### Server configuration

**Operating system**:
Debian
**Web server:**
Apache
**Database:**
MariaDb
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
13.0 + Collabora
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - announcementcenter: 3.2.1
  - bruteforcesettings: 1.0.3
  - circles: 0.13.6
  - comments: 1.3.0
  - dav: 1.4.6
  - drawio: 0.8.9
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - impersonate: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.3
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - admin_notifications
  - calendar
  - encryption
  - onlyoffice
  - user_external
  - user_saml
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "docs.nancy.archi.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/docs.nancy.archi.fr",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
both, local and smb
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory

### Client configuration
**Browser:**
Firefox, Edge
**Operating system:**
WIndows 7, 10
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Error | index | Error: Call to a member function getId() on boolean/var/www/nextcloud/apps/files_versions/lib/Hooks.php - line 61:  OCA\Files_Versions\Storage  store('/**ExtStorage**...')/var/www/nextcloud/lib/private/legacy/hook.php - line 106:  OCA\Files_Versions\Hooks  write_hook(Array)/var/www/nextcloud/lib/private/Files/View.php - line 611:  OC_Hook  emit('OC_Filesystem', 'write', Array)/var/www/nextcloud/lib/private/Files/View.php - line 653:  OC\Files\View->emit_file_hooks_pre(true, '/**User1**/files/...', true)/var/www/nextcloud/lib/private/Files/Node/File.php - line 64:  OC\Files\View->file_put_contents('/**User1**/files/...', Resource id #108)/var/www/nextcloud/apps/richdocuments/lib/Controller/WopiController.php - line 274:  OC\Files\Node\File->putContent(Resource id #108)[internal function] OCA\Richdocuments\Controller\WopiController->putFile('568', '8h4ud53ldvdJG9Y...')/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161:  call_user_func_array(Array, Array)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91:  OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\WopiController), 'putFile')/var/www/nextcloud/lib/private/AppFramework/App.php - line 115:  OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\WopiController), 'putFile')/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:  OC\AppFramework\App  main('OCA\\Richdocumen...', 'putFile', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/nextcloud/lib/private/Route/Router.php - line 297:  call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/nextcloud/lib/base.php - line 998:  OC\Route\Router->match('/apps/richdocum...')/var/www/nextcloud/index.php - line 37:  OC  handleRequest(){main}
-- | -- | --

</details>

**Comment by rullzer** [comment]
Please fill in https://github.com/nextcloud/richdocuments
