### ISSUE TITLE
Add "addVendorScript/Style" to public interface Utility class

### ISSUE THREAD

**Issue by janis91** [nextcloud/server#889]
### Steps to reproduce

1 . Use a vendorscript or vendorstyle in your own app:

```
OC_Util::addVendorScript('select2/select2');
OC_Util::addVendorStyle('select2/select2');
```

2 . `./occ app:check-code $APP_NAME -c private -c strong-comparison`
### Expected behaviour

app check should return without errors
### Actual behaviour

> OC_Util - Static method of private class must not be called
### Server configuration

**Operating system**:
Ubuntu 14.04
**Web server:**
ncdev php test server
**Database:**
postgre
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
11.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
no
**Where did you install Nextcloud from:**
ncdev (git)

I think it would be a improvement to add the addVendorScript and addVendorStyle functions to the OCP\Util public interface, such that the app:check of occ isn't crying anymore.
Or do you know another way to include vendor script and style which is not harming the code check?

If the extension of the OCP\Util is the best solution, I could contribute...

**Comment by rullzer** [comment]
I'm still not really a fan of those static functions. Maybe we can add them to the template response or something?

**Comment by janis91** [comment]
something like an array of scripts and styles as input for the constructor?

**Comment by janis91** [comment]
any progress with this?

**Comment by rullzer** [comment]
Not currently we are busy with getting NC10 in shape.
But let me target this for NC 11

**Comment by janis91** [comment]
Alright. If you have any ideas how do this the best, I could also try to contribute it.. But I don't know the way you prefer.

**Comment by rullzer** [comment]
@janis91 that would be very much appriciated :smile: 

I think best would be to extend the TemplateResponse (\OCP\AppFramework\Http\TemplateResponse).

**Comment by ChristophWurst** [comment]
2019 update: you shouldn't use such helpers as globally loaded scripts are *pretty bad*. They cause conflicts with other apps and pollute the global namespace. I would suggest to just go with a decent asset bundler like webpack and ship a bundled version of your scripts/styles. This is what we do for apps and the server now.
