### ISSUE TITLE
PHP fatal error in PHP7/7.1 Undefined class constant 'PDO::FETCH_ASSOC'

### ISSUE THREAD

**Issue by podkilla** [nextcloud/server#8892]
### Steps to reproduce
1. Switch from PHP 5.6 to PHP 7/7.1
2.
3.

### Expected behaviour
It should just work

### Actual behaviour
errors in apache error log, cloud application is not responding any more

### Server configuration

**Operating system**:
gentoo

**Web server:**
apache 2.4

**Database:**
mysql 10.1.31

**PHP version:**
php7/7.1

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
tried both

**Where did you install Nextcloud from:**
manual installation from tar.gz

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxx.xx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.xxx.xx",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "default_language": "en",
        "defaultapp": "calendar",
        "enable_previews": true,
        "trashbin_retention_obligation": "auto, D30",
        "knowledgebaseenabled": false,
        "enable_avatars": true,
        "allow_users_to_change_display_name": true,
        "asset-pipeline.enabled": true,
        "session_lifetime": 14400,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "logfile": "nextcloud.log",
        "loglevel": 2,
        "log_type": "owncloud",
        "log_authfailip": true,
        "maintenance": false,
        "singleuser": false,
        "theme": "",
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using encryption:** no

### Client configuration
**Browser:**
chromium

**Operating system:**
archlinux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Tue Mar 20 03:12:26.766886 2018] [mpm_event:notice] [pid 21005:tid 140311627331456] AH00493: SIGUSR1 received.  Doing graceful restart
[Tue Mar 20 03:12:26.914137 2018] [mpm_event:notice] [pid 21005:tid 140311627331456] AH00489: Apache/2.4.29 (Unix) OpenSSL/1.0.2n PHP/7.1.15 configured -- resuming normal operations
[Tue Mar 20 03:12:26.914171 2018] [core:notice] [pid 21005:tid 140311627331456] AH00094: Command line: '/usr/sbin/apache2 -D SSL -D PHP -D SECURITY -D XSENDFILE -d /usr/lib64/apache2 -f /etc/apache2/httpd.conf'
zend_mm_heap corrupted
[Tue Mar 20 05:25:32.729818 2018] [core:notice] [pid 21005:tid 140311627331456] AH00052: child pid 29256 exit signal Segmentation fault (11)
zend_mm_heap corrupted
[Tue Mar 20 05:33:34.994766 2018] [php7:error] [pid 906:tid 140310969526016] [client x.x.x.x:19299] PHP Fatal error:  Uncaught Error: Undefined class constant 'PDO::FETCH_ASSOC' in /var/www/nextcloud/htdocs/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php:172\nStack trace:\n#0 /var/www/nextcloud/htdocs/nextcloud/lib/private/DB/ConnectionFactory.php(152): Doctrine\\DBAL\\DriverManager::getConnection(Array, Object(Doctrine\\DBAL\\Configuration), Object(Doctrine\\Common\\EventManager))\n#1 /var/www/nextcloud/htdocs/nextcloud/lib/private/Server.php(628): OC\\DB\\ConnectionFactory->getConnection('mysql', Array)\n#2 /var/www/nextcloud/htdocs/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#3 /var/www/nextcloud/htdocs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\\Container->offsetGet('OCP\\\\IDBConnecti...')\n#4 /var/www/nextcloud/htdocs/nextcloud/lib/private/ServerContainer.php(132): OC\\AppFramework\\Utility\\SimpleContainer->query('OCP\\\\IDBConnecti...')\n#5 /var/www/nextcloud/htdocs/nextcloud/lib/private/AppFramework/Utility/SimpleContainer in /var/www/nextcloud/htdocs/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php on line 172
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Sounds like you didn't install all necessary php modules, check this list:
https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation

**Comment by podkilla** [comment]
thanks for your help, but i dont think that is the issue, since it is working perfect with php5.6

**Comment by schmidicom** [comment]
Try to disable opcache in php.ini and all other cache in config.php

Since Version 13 is on my system (same config as you; Gentoo, PHP 7.1, Apache 2.4, MariaDB 10.1.31) impossible to enable it without an "Internal Server Error"

**Comment by YenzRanger** [comment]
With php5.6 it would also fail if you haven't installed the required PDO module. So please take a look at the docs which were linked by @nickvergessen and make sure you have installed the database connectors.

**Comment by nickvergessen** [comment]
> thanks for your help, but i dont think that is the issue, since it is working perfect with php5.6

Well some of the modules need to be installed per php version:
```
$ sudo apt install php7.0-
php7.0-bcmath     php7.0-common     php7.0-enchant    php7.0-imap       php7.0-ldap       php7.0-odbc       php7.0-pspell     php7.0-soap       php7.0-xml        
php7.0-bz2        php7.0-curl       php7.0-fpm        php7.0-interbase  php7.0-mbstring   php7.0-opcache    php7.0-readline   php7.0-sqlite3    php7.0-xmlrpc     
php7.0-cgi        php7.0-dba        php7.0-gd         php7.0-intl       php7.0-mcrypt     php7.0-pgsql      php7.0-recode     php7.0-sybase     php7.0-xsl        
php7.0-cli        php7.0-dev        php7.0-gmp        php7.0-json       php7.0-mysql      php7.0-phpdbg     php7.0-snmp       php7.0-tidy       php7.0-zip 
```

So check back with the requirements if you installed all php7.1-* modules that are necessary

**Comment by podkilla** [comment]
maybe you dont know gentoo, but the USE flags are set globally so php5.6 is compiled with the same modules as php7.1 or php7.0
switching php versions has never been an issue before.

anyway, here are my php modules:
[PHP Modules]
apc
apcu
bz2
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
imap
intl
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
readline
redis
Reflection
session
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by rullzer** [comment]
This is not the fault of Nextcloud. PDO is a php module. Please use https://help.nextcloud.com for this kind of issues.

**Comment by wizdude** [comment]
just a tip for anyone googling this as I had the same problem with Slackware64 14.2 running PHP 7.1.16. the issue turned out to be APCu. I had done a fresh install following my notes when I was running PHP 5.6 and although I installed the latest compatible APCu this was the fault. disabled this and nextcloud performed with no issues.

i have since followed recommendations of using redis as a memory cache and this appears to have resolved my problems.

**Comment by amin007** [comment]
i have same problem in xampp php 7.1 for windows

**Comment by nickvergessen** [comment]
Sorry Nextcloud is not supported to run on windows anyway

**Comment by kurdtpage** [comment]
I have the same problem using PHP 7.0.13. The problem is not there when using PHP 5.6.19 or 7.2.15
