### ISSUE TITLE
User backends (apps) using private constants from OC\User\Backend

### ISSUE THREAD

**Issue by klada** [nextcloud/server#8895]
**Note**: This is not a functional bug but rather an issue with the current code structure and interfaces.

### Description

Nextcloud apps which provide authentication/user backends need to define which actions they can actually provide. This is required by the **public** interface `\OCP\UserInterface->implementsActions`.

The constants which need to be checked in `implementsActions` reside in the **private** backend `\OC\User\Backend` class, which is also pointed out in the comment of the interface (see `implementsActions`). This forces app developers to access parts of the Nextcloud API which is considered private (by namespace). 

### Expected behaviour

The constants mentioned above (namely `CREATE_USER`, `SET_PASSWORD`, `CHECK_PASSWORD`, `GET_HOME`, `GET_DISPLAYNAME`, `SET_DISPLAYNAME`, `PROVIDE_AVATAR`, `COUNT_USERS`) should be defined somewhere in the public namespace.

They could be defined in the interface (which is not perfect, but probably okay as the constants are rather static) or in a **public** abstract backend class.

I'll create a PR with the first approach.

### Affected apps

Currently these apps make use of the private API:

- user_ldap
- user_saml
- probably many other non-official apps

**Comment by rullzer** [comment]
Closing with #8935
