### ISSUE TITLE
Update  notification: Description of stable is not suitable

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#8897]
https://github.com/nextcloud/server/blob/99abe3bc8e853a4b7ea9577b6cc15531a84bfe3e/apps/updatenotification/js-src/components/root.vue#L190

It names the word "production" for stable channel. 

When to use the production channel?

That will confuse the user.

**Comment by rakekniven** [comment]
@MorrisJobke Could you help here?

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers 

Production is basically from .2 ... stable will always update to the next major version. It's stable ... production is just the more defensive way of handling.

**Comment by jancborchardt** [comment]
Maybe we should then just reword the description of stable to remove the word »production«, right?

@rakekniven do you want to prepare a small pull request doing that? Basically it could change to »It is suited for regular use …« (regular instead of production)

**Comment by MorrisJobke** [comment]
@rakekniven Github will automatically close tickets once a PR is merged, that contains "Fixes #NUMBER" 😉

**Comment by rakekniven** [comment]
Yes, hopefully all devs are using ist ;-)

**Comment by jancborchardt** [comment]
Good stuff @rakekniven – thanks a lot for fixing it! :)
