### ISSUE TITLE
Upload API TIMEOUT

### ISSUE THREAD

**Issue by OsamaRadwan** [nextcloud/server#8907]
I'm using NextCloud Upload API 

When uploading on this url :

`PUT remote.php/dav/files/user/path/to/file`

The request takes about 1min then the server responsd with this status code `504 GATEWAY_TIMEOUT`

Is there any headers i have to send to make the server respond without it TimesOut ? If not then what is the solutation ?

**Comment by MorrisJobke** [comment]
Thats a setup issue with your web server. Configure your web server to not time out. If you want help about this: check the forums: https://help.nextcloud.com
