### ISSUE TITLE
Upgrade from 12.0.6 to 13.0.1 failed

### ISSUE THREAD

**Issue by octogene** [nextcloud/server#8912]
### Steps to reproduce
1. From admin panel go to updater
2. Start update
3. Use Web updater

### Expected behaviour

Update completes without error.

### Actual behaviour

![screenshot-2018-3-21 nextcloud](https://user-images.githubusercontent.com/4295352/37703776-0c11192a-2cf7-11e8-84e8-af6ca701d20d.png)

### Server configuration

**Operating system**: Debian Stretch

**Web server** : Apache 2.4.25-3+deb9u3

**Database** : MariaDB 10.1.26

**PHP version** : PHP 7.0.27-0+deb9u1

**Nextcloud version:** 12.0.6

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.8
  - contacts: 2.1.2
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.2
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.2
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - qownnotesapi: 17.5.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - tasks: 0.9.6
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - news
  - passman
  - systemtags
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "version": "12.0.6.1",
        "installed": true,
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "loglevel": 1,
        "log_authfailip": true,
        "aauth.bruteforce.protection.enabled": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": true,
        "forcessl": true,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "asset-pipeline.enabled": false,
        "trusted_domains": [
            "owncloud.hadaly.fr",
            "nuage.lm7.fr"
        ],
        "share_folder": "\/Shared",
        "appcodechecker": false,
        "integrity.check.disabled": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, 180",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Epub"
        ],
        "overwrite.cli.url": "https:\/\/owncloud.hadaly.fr",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "activity": {
            "enabled": "no",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "admin_export": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "appframework": {
            "enabled": "no",
            "installed_version": "0.104",
            "ocsid": "162405",
            "types": ""
        },
        "atnotes": {
            "enabled": "no",
            "installed_version": "1.0",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "1659"
        },
        "bogdan": {
            "documents": "save_path"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "0.11.0",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.3",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.8",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": "logging"
        },
        "configreport": {
            "enabled": "no",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "signed": "true",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "cron",
            "backgroundjobs_step": "regular_tasks",
            "backgroundjobs_task": "",
            "global_cache_gc_lastrun": "1436338806",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1339684543.9656",
            "lastcron": "1521623709",
            "lastupdateResult": "{\"version\":\"13.0.1.1\",\"versionstring\":\"Nextcloud 13.0.1\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-13.0.1.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/13\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"autoupdater\":\"1\",\"eol\":\"0\",\"signature\":\"AG3egWHJkQaqCraVLiRq5Q7GvqArmBgVv8PNAfVYTOXPN6xWmw8cbUeBvBZ3OS1\\\/\\nbup1ktLDwTLDjWm1XMBUhhQCxVDLtEd3A6WfaVJz9BWoz1MyxUGlaIJSzTHLoEfz\\nnFVUdoGH0mAdq8WtxRQSNwQWeKn+iF1jpbtIbDc29POtWvvzEgT\\\/KW8MDzeidx6s\\nW78tH4vldR0\\\/aBn1D3hwnkQEQ8+Kz+Y4ItjHHi6XpJEfRQzYD0j9T+VTQ9IX4Xf\\\/\\nXqTrcaUCqwOlSC4pM7aUUzgaePPcYU2zrRDRaEgLma9eSkVMzkkc4kfM3izBG0Iv\\nSTb5hZFB2HMLyJxuj1l05w==\"}",
            "lastupdatedat": "1521624153",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_host-meta": "\/apps\/user_webfinger\/host-meta.php",
            "public_shorty_qrcode": "shorty\/qrcode.php",
            "public_shorty_query": "shorty\/query.php",
            "public_shorty_relay": "shorty\/relay.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "public_webfinger": "\/apps\/user_webfinger\/webfinger.php",
            "remote_ampache": "media\/remote.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_contactthumbnail": "contacts\/thumbnail.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "797708eec1b6dc555f5e88418e6a1429",
            "updater.secret.created": "1521624165",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.13.1",
            "ocsid": "168711",
            "types": "",
            "unstable": "false"
        },
        "external": {
            "enabled": "no",
            "installed_version": "1.2",
            "ocsid": "166046",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "52913",
            "backgroundwatcher_previous_folder": "48986",
            "cronjob_scan_files": "500",
            "default_quota": "5 GB",
            "enabled": "yes",
            "installed_version": "1.7.2",
            "types": "filesystem"
        },
        "files_archive": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": "filesystem"
        },
        "files_imageviewer": {
            "enabled": "no",
            "installed_version": "1.0"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_meta": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "files_mv": {
            "enabled": "no",
            "installed_version": "0.5.1b",
            "types": "filesystem"
        },
        "files_odfviewer": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "files_opds": {
            "cover-x": "200",
            "cover-y": "200",
            "enabled": "no",
            "feed_subtitle": "ownCloud OPDS catalog",
            "google-key": "",
            "installed_version": "0.8.2",
            "isbndb-key": "",
            "ocsid": "168132",
            "thumb-x": "36",
            "thumb-y": "36",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_streamer": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "files_svgedit": {
            "enabled": "no",
            "installed_version": "0.2-beta7",
            "types": ""
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_textviewer": {
            "enabled": "no",
            "installed_version": "0.3"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.1",
            "types": "logging"
        },
        "fluxx_compensator": {
            "enabled": "no",
            "installed_version": "0.2.6",
            "ocsid": "157091",
            "types": "base"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "17.0.0",
            "types": ""
        },
        "gsync": {
            "enabled": "no",
            "installed_version": "0.4.2",
            "types": ""
        },
        "journal": {
            "enabled": "no",
            "installed_version": "0.3.2",
            "ocsid": "154637",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "no",
            "installed_version": "0.2.1",
            "ocsid": "169914",
            "types": ""
        },
        "media": {
            "enabled": "no",
            "installed_version": "0.4.3",
            "types": ""
        },
        "news": {
            "enabled": "no",
            "installed_version": "11.0.5",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.1",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "ocsms": {
            "enabled": "yes",
            "installed_version": "1.12.2",
            "ocsid": "167289",
            "types": ""
        },
        "ownnote": {
            "enabled": "no",
            "installed_version": "1.07",
            "ocsid": "168512",
            "types": ""
        },
        "passman": {
            "enabled": "no",
            "installed_version": "2.1.4",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.2.2",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "qownnotesapi": {
            "enabled": "yes",
            "installed_version": "17.5.0",
            "ocsid": "173817",
            "signed": "true",
            "types": ""
        },
        "remoteStorage": {
            "enabled": "no",
            "installed_version": "0.6"
        },
        "roundcube": {
            "enabled": "no",
            "installed_version": "2.5.4",
            "ocsid": "151523",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "shorty": {
            "backend-default": "none",
            "backend-static-base": "",
            "enabled": "no",
            "id-alphabet": ,
            "installed_version": "0.3.30",
            "ocsid": "150401",
            "types": "internet,bookmark"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "last_report": "{\"id\":\"507be2dcc6850\",\"items\":[[\"server\",\"version\",\"12.0.6.1\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.0.27\"],[\"php\",\"memory_limit\",-1],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.1.26\"],[\"database\",\"size\",183582720],[\"apps\",\"activity\",\"disabled\"],[\"apps\",\"admin_export\",\"disabled\"],[\"apps\",\"appframework\",\"disabled\"],[\"apps\",\"atnotes\",\"disabled\"],[\"apps\",\"bookmarks\",\"0.11.0\"],[\"apps\",\"bruteforcesettings\",\"1.0.3\"],[\"apps\",\"calendar\",\"1.5.8\"],[\"apps\",\"comments\",\"disabled\"],[\"apps\",\"configreport\",\"disabled\"],[\"apps\",\"contacts\",\"2.1.2\"],[\"apps\",\"dav\",\"1.3.1\"],[\"apps\",\"documents\",\"disabled\"],[\"apps\",\"external\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.2.0\"],[\"apps\",\"federation\",\"disabled\"],[\"apps\",\"files\",\"1.7.2\"],[\"apps\",\"files_archive\",\"disabled\"],[\"apps\",\"files_external\",\"disabled\"],[\"apps\",\"files_imageviewer\",\"disabled\"],[\"apps\",\"files_locking\",\"disabled\"],[\"apps\",\"files_meta\",\"disabled\"],[\"apps\",\"files_mv\",\"disabled\"],[\"apps\",\"files_odfviewer\",\"disabled\"],[\"apps\",\"files_opds\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"1.1.1\"],[\"apps\",\"files_sharing\",\"1.4.0\"],[\"apps\",\"files_streamer\",\"disabled\"],[\"apps\",\"files_svgedit\",\"disabled\"],[\"apps\",\"files_texteditor\",\"2.4.1\"],[\"apps\",\"files_textviewer\",\"disabled\"],[\"apps\",\"files_trashbin\",\"1.2.0\"],[\"apps\",\"files_versions\",\"1.5.0\"],[\"apps\",\"files_videoplayer\",\"1.1.0\"],[\"apps\",\"files_videoviewer\",\"disabled\"],[\"apps\",\"firstrunwizard\",\"2.1\"],[\"apps\",\"fluxx_compensator\",\"disabled\"],[\"apps\",\"gallery\",\"17.0.0\"],[\"apps\",\"gsync\",\"disabled\"],[\"apps\",\"journal\",\"disabled\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"lookup_server_connector\",\"1.0.0\"],[\"apps\",\"mail\",\"disabled\"],[\"apps\",\"media\",\"disabled\"],[\"apps\",\"news\",\"disabled\"],[\"apps\",\"nextcloud_announcements\",\"1.1\"],[\"apps\",\"notes\",\"2.3.2\"],[\"apps\",\"notifications\",\"2.0.0\"],[\"apps\",\"oauth2\",\"1.0.5\"],[\"apps\",\"ocsms\",\"1.12.2\"],[\"apps\",\"ownnote\",\"disabled\"],[\"apps\",\"passman\",\"disabled\"],[\"apps\",\"password_policy\",\"1.2.2\"],[\"apps\",\"provisioning_api\",\"1.2.0\"],[\"apps\",\"qownnotesapi\",\"17.5.0\"],[\"apps\",\"remoteStorage\",\"disabled\"],[\"apps\",\"roundcube\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.2.0\"],[\"apps\",\"sharebymail\",\"1.2.0\"],[\"apps\",\"shorty\",\"disabled\"],[\"apps\",\"survey_client\",\"1.0.0\"],[\"apps\",\"systemtags\",\"disabled\"],[\"apps\",\"tal\",\"disabled\"],[\"apps\",\"tasks\",\"0.9.6\"],[\"apps\",\"templateeditor\",\"disabled\"],[\"apps\",\"theming\",\"1.3.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.1.1\"],[\"apps\",\"twofactor_totp\",\"1.3.1\"],[\"apps\",\"updatenotification\",\"1.2.0\"],[\"apps\",\"updater\",\"disabled\"],[\"apps\",\"user_ldap\",\"disabled\"],[\"apps\",\"user_openid\",\"disabled\"],[\"apps\",\"user_webfinger\",\"disabled\"],[\"apps\",\"workflowengine\",\"1.2.0\"],[\"stats\",\"num_files\",28439],[\"stats\",\"num_users\",3],[\"stats\",\"num_storages\",7],[\"stats\",\"num_storages_local\",2],[\"stats\",\"num_storages_home\",5],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",2],[\"files_sharing\",\"num_shares_user\",1],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",1],[\"files_sharing\",\"num_shares_link_no_password\",1],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_1\",\"1\"],[\"files_sharing\",\"permissions_0_17\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1521506716",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": "logging"
        },
        "tal": {
            "enabled": "no",
            "installed_version": "0.2.2",
            "ocsid": "154632",
            "types": ""
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.6",
            "ocsid": "164356",
            "signed": "true",
            "types": ""
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "7",
            "color": "#53BAFF",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging",
            "url": "https:\/\/owncloud.hadaly.fr"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "updatenotification": {
            "bookmarks": "0.11.0",
            "bruteforcesettings": "1.0.3",
            "calendar": "1.5.8",
            "contacts": "2.1.2",
            "core": "13.0.1.1",
            "enabled": "yes",
            "files_pdfviewer": "1.1.2",
            "installed_version": "1.2.0",
            "notes": "2.3.2",
            "ocsms": "1.12.2",
            "qownnotesapi": "17.5.0",
            "tasks": "0.9.6",
            "types": "",
            "update_check_errors": "0"
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_ldap": {
            "enabled": "no",
            "installed_version": "0.2"
        },
        "user_openid": {
            "enabled": "no",
            "installed_version": "0.1.1"
        },
        "user_webfinger": {
            "enabled": "no",
            "installed_version": "0.3"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        }
    }
}
</details>

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 58.0.2

**Operating system:** Opensuse Tumbleweed

**Comment by MorrisJobke** [comment]
```
base table or view already exists: 1050 table ...
```

**Comment by MorrisJobke** [comment]
Looks like #8431 -> let's continue there.
