### ISSUE TITLE
Can't upload videos when sent email.

### ISSUE THREAD

**Issue by supermanlinux** [nextcloud/server#8913]
### Steps to reproduce
An error occurred while uploading videos in new mail.
![image](https://user-images.githubusercontent.com/34739130/37705353-b7c94488-2d36-11e8-86b8-39906a625901.png)

### Expected behaviour
when sent an email,upload videos successfully.

### Actual behaviour
An error occurred while uploading videos in new mail.

### Server configuration

Operating system:

**Web server:**Nextcloud13

**Database:**MariaDB

**PHP version:**PHP 7.0.22-0ubuntu0.16.04.1

Nextcloud version: (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**fresh install

**Where did you install Nextcloud from:**github

**Comment by MorrisJobke** [comment]
@supermanlinux Is this about the outlook plugin? Or what email client are you using and what is the integration there?

**Comment by supermanlinux** [comment]
Thanks,I solved this problem,it occured with maximum upload size.

![11](https://user-images.githubusercontent.com/34739130/37756146-5fcdde6c-2de3-11e8-855c-888c805391e4.png)
