### ISSUE TITLE
iCloud does not recognise new events, whereas Google does

### ISSUE THREAD

**Issue by atxcowboy** [nextcloud/server#8916]
### Steps to reproduce
1. Send invitation for an event A to a Google  account
2. Send invitation for an event B to an iCloud account

### Expected behaviour
With a Google account, the event invitation is recognised by the calendar.app, with the iCloud account it is not recognised.

### Actual behaviour
The iCloud account gets an email with an attachment event.ics. After a double click, the event is added to the calendar

### Server configuration

**Operating system**: CentOS Linux release 7.4.1708 (Core) 

**Web server:** nginx (openresty/1.13.6.1)

**Database:** 10.1.31-MariaDB

**PHP version:** 7.1.15

**Server version:** 13.0.1

**Calendar version:** 1.6.1

**Updated from an older installed version or fresh install:** Upgrade

**Signing status (ownCloud/Nextcloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

  - activity: 2.6.1
  - admin_audit: 1.3.0
  - announcementcenter: 3.2.1
  - apporder: 0.4.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - deck: 0.3.1
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - impersonate: 1.0.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***""
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/cloud.hakuhodo.de",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**no

### Client configuration
**Browser:** Safari / Chrome / Firefox

**Operating system:** OS X 10.13

**CalDAV-clients:**
OSX-Kalender (Version 10.0 (2195.2.1)

```

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by georgehrke** [comment]
Please provide more detailed reproduction steps as I asked for in the calendar issue ......

**Comment by blizzz** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
