### ISSUE TITLE
Disabled Users not visible for the Administrator

### ISSUE THREAD

**Issue by ajeoc** [nextcloud/server#8917]
The same issue as in #6809 . But there somehow declared as not the same issue...
So this is a new ticket:

### Steps to reproduce
1. Log in as Admin (Full Admin not Group Admin)
2. Go to Users and Disable an existing User
3. On the left pane select the Group "Disabled"

### Expected behaviour
The Group "Disabled" should list disabled User Accounts

### Actual behaviour
The Group "Disabled" doesn't list the disabled Users. The amount (number) of disabled Users is visible.

### Server configuration

**Operating system**: CentOS Linux release 7.4.1708 (Core)

**Web server:** Apache/2.4.6 (CentOS)

**Database:** 5.5.56-MariaDB MariaDB Server

**PHP version:** 7.1.14

**Nextcloud version:** 12.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** oC8.0 --> oC8.1 --> oC8.2 --> oC9.0 --> nC9.0 --> nC10.0 --> nC11.0 --> nC12.0 --> nC12.0.6

**Where did you install Nextcloud from:** 

**Signing status:** No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - firstrunwizard
  - gallery
  - theming
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "ocnibw9w9uqp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.200.15",
            "xxx"
        ],
        "datadirectory": "\/home\/share\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "12.0.6.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "share",
        "mail_domain": "xxx",
        "mail_smtphost": "192.168.200.14",
        "mail_smtpport": "25",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "loglevel": 2,
        "default_language": "en",
        "allow_user_to_change_display_name": false,
        "updatechecker": false,
        "check_for_working_htaccess": true,
        "logtimezone": "Europe\/Zurich",
        "maintenance": false,
        "theme": "xxx",
        "singleuser": false,
        "trashbin_retention_obligation": "30, 31",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "production",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.5.2",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "24"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.3",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "no",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "global_cache_gc_lastrun": "1468834201",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1435670744.6259",
            "lastcron": "1521636302",
            "lastupdateResult": "[]",
            "lastupdatedat": "1521636337",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "bb083d930fd63c4c89c5b4b3219dfd46",
            "shareapi_allow_mail_notification": "no",
            "shareapi_allow_public_notification": "no",
            "shareapi_default_expire_date": "no",
            "shareapi_enforce_links_password": "no",
            "shareapi_exclude_groups": "no",
            "shareapi_exclude_groups_list": "[\"\"]",
            "shareapi_only_share_with_group_members": "yes",
            "umgmt_send_email": "false",
            "umgmt_show_email": "false",
            "umgmt_show_last_login": "true",
            "umgmt_show_storage_location": "false",
            "updater.secret.created": "1521632343",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federation": {
            "autoAddServers": "0",
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.7.2",
            "types": "filesystem"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.4.0",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "0.6.1",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "levels": "00111",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.1",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceNumericCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.2.2",
            "minLength": "12",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "last_report": "{\"id\":\"ocnibw9w9uqp\",\"items\":[[\"server\",\"version\",\"12.0.3.3\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"5.6.31\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",8589934592],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"5.5.56\"],[\"database\",\"size\",146227200],[\"apps\",169116,\"disabled\"],[\"apps\",\"activity\",\"2.5.2\"],[\"apps\",\"admin_audit\",\"1.2.0\"],[\"apps\",\"bruteforcesettings\",\"1.0.2\"],[\"apps\",\"comments\",\"1.2.0\"],[\"apps\",\"configreport\",\"disabled\"],[\"apps\",\"dav\",\"1.3.0\"],[\"apps\",\"federatedfilesharing\",\"1.2.0\"],[\"apps\",\"federation\",\"1.2.0\"],[\"apps\",\"files\",\"1.7.2\"],[\"apps\",\"files_locking\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"1.1.1\"],[\"apps\",\"files_sharing\",\"1.4.0\"],[\"apps\",\"files_texteditor\",\"2.4.1\"],[\"apps\",\"files_trashbin\",\"1.2.0\"],[\"apps\",\"files_versions\",\"1.5.0\"],[\"apps\",\"files_videoplayer\",\"1.1.0\"],[\"apps\",\"files_videoviewer\",\"disabled\"],[\"apps\",\"firstrunwizard\",\"disabled\"],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"lookup_server_connector\",\"1.0.0\"],[\"apps\",\"nextcloud_announcements\",\"1.1\"],[\"apps\",\"notifications\",\"2.0.0\"],[\"apps\",\"oauth2\",\"1.0.5\"],[\"apps\",\"password_policy\",\"1.2.2\"],[\"apps\",\"provisioning_api\",\"1.2.0\"],[\"apps\",\"serverinfo\",\"1.2.0\"],[\"apps\",\"sharebymail\",\"1.2.0\"],[\"apps\",\"survey_client\",\"1.0.0\"],[\"apps\",\"systemtags\",\"1.2.0\"],[\"apps\",\"templateeditor\",\"disabled\"],[\"apps\",\"theming\",\"disabled\"],[\"apps\",\"twofactor_backupcodes\",\"1.1.1\"],[\"apps\",\"updatenotification\",\"1.2.0\"],[\"apps\",\"workflowengine\",\"1.2.0\"],[\"stats\",\"num_files\",70137],[\"stats\",\"num_users\",134],[\"stats\",\"num_storages\",168],[\"stats\",\"num_storages_local\",2],[\"stats\",\"num_storages_home\",146],[\"stats\",\"num_storages_other\",20],[\"stats\",\"num_comments\",2],[\"stats\",\"num_comment_markers\",1],[\"stats\",\"num_systemtags\",1],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",3814],[\"files_sharing\",\"num_shares_user\",18],[\"files_sharing\",\"num_shares_groups\",4],[\"files_sharing\",\"num_shares_link\",3792],[\"files_sharing\",\"num_shares_link_no_password\",3792],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_0_1\",\"1\"],[\"files_sharing\",\"permissions_3_1\",\"3689\"],[\"files_sharing\",\"permissions_0_15\",\"6\"],[\"files_sharing\",\"permissions_3_15\",\"103\"],[\"files_sharing\",\"permissions_0_19\",\"2\"],[\"files_sharing\",\"permissions_0_31\",\"9\"],[\"files_sharing\",\"permissions_1_31\",\"4\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1507545233",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "updatenotification": {
            "bruteforcesettings": "1.0.3",
            "core": "13.0.1.1",
            "enabled": "yes",
            "files_pdfviewer": "1.1.2",
            "installed_version": "1.2.0",
            "types": "",
            "update_check_errors": "0"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "169116": {
            "enabled": "no"
        }
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** IE11, Firefox 59.0.1

**Operating system:** Windows 7 64-bit

**Comment by ajeoc** [comment]
@hubertbanas @MattyShires @supremesyntax @m-blc
Did you got it fixed?

**Comment by hubertbanas** [comment]
Nope. In my case I see
Disabled (9)
but on the right I have only 4 users listed/visible. This is on 12.0.6 as full nextcloud admin.

![nextcloud_bug-8917](https://user-images.githubusercontent.com/2602582/37720635-134b5c6c-2cfe-11e8-8892-650e1c4d915f.png)

**Comment by skjnldsv** [comment]
Maybe the new users list will fix this. We'll see.

**Comment by hubertbanas** [comment]
FYI,
I'm still experiencing this issue after upgrading from 12.0.6 to 13.0.1.

**Comment by michag86** [comment]
@hubertbanas How much users do you have? More than 50?

@MorrisJobke 
I can confirm this. The problem is the the way the request is handled:
https://domain/settings/users/users?offset=0&limit=50&gid=_disabledUsers

It seems, that the result is first limited to 50 users, than the filter for disabled users is applied.

If you have an environment with more than 50 users, you can hit or miss the disabled users.

As workaround you can search for the disabled user if you know the username.

**Comment by hubertbanas** [comment]
Yes, I have more than 50 users.

**Comment by MorrisJobke** [comment]
cc @skjnldsv aren't you working on this right now? cc @nickvergessen

**Comment by skjnldsv** [comment]
@MorrisJobke yes :)

> skjnldsv commented 9 days ago
> Maybe the new users list will fix this. We'll see.

**Comment by MorrisJobke** [comment]
> Maybe the new users list will fix this. We'll see.

See #8824
