### ISSUE TITLE
Public link download button does not work

### ISSUE THREAD

**Issue by Peac** [nextcloud/server#8925]
### Steps to reproduce
1. Upload a file/folder
2. Share it via link
3. Log off from Nextcloud
4. Go on the link
5. Click on the "button" on the upper right corner or the 3 dots

### Expected behaviour
The file/folder should be downloaded.

### Actual behaviour
Nothing happens.

### Server configuration

**Operating system:** Ubuntu Server 16.04.4

**Web server:** Apache 2.4.18

**Database:** MariaDB 10.0.34

**PHP version:** 7.0.28

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - audioplayer: 2.2.5
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - checksum: 0.3.5
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.3
  - serverinfo: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.xxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/xxx.xxx",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "check_for_working_webdav": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font",
            "OC\\Preview\\Movie"
        ],
        "cipher": "AES-256-CFB",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "versions_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "loglevel": 2,
        "maintenance": false,
        "theme": ""
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla Firefox 59.0.1

**Operating system:** Windows 7

### Logs
None

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing @skjnldsv @danxuliu

**Comment by danxuliu** [comment]
I can not reproduce.

On 13.0.1 if I click on the _Download_ "button" in the upper right corner a menu is shown (in Nextcloud 14 it directly downloads the file, but in 13 it shows the menu); that menu includes a _Download_ entry, and clicking on it downloads the file as expected.

**Comment by MorrisJobke** [comment]
@Peac  Is there anything in the web developer console in the web dev tolls of your browser? (Open it before repeating the steps)

**Comment by skjnldsv** [comment]
Same, working fine here :)

**Comment by Peac** [comment]
Thank you all for the fast feedback.

I tried it with another browser and it worked. After some testing I disabled uBlock in Firefox and it worked again.

Sorry for the inconvenience, next time I will test a "bug" with another browser first :)
