### ISSUE TITLE
Enable multithreaded downloads

### ISSUE THREAD

**Issue by vlldk** [nextcloud/server#8927]
An option to download files from Nextcloud with multiple threads. Downloaders like jDownloader would be able to take advantage of this especially with big files.

**Comment by MorrisJobke** [comment]
Nextcloud uses webdav and our implementation already supports range requests ... so technically it should be possible. What API is needed for this?

**Comment by vlldk** [comment]
Are you looking for something like this:
https://stackoverflow.com/questions/7099952/how-can-i-download-multiple-parts-of-a-file-in-parallel-with-phps-curl-library
https://gist.github.com/wingsuitist/ecd294cd08a92f60a60abb5f9b74b309 ?

I did some Googling but I'm not sure what to search for...

**Comment by MorrisJobke** [comment]
> Are you looking for something like this:
> https://stackoverflow.com/questions/7099952/how-can-i-download-multiple-parts-of-a-file-in-parallel-with-phps-curl-library

Exactly - you specify in the HTTP header a range of bytes you want to have `Range: 1234-1236` and then the client needs to do the split into those ranges and later assemble the parts again.

**Comment by MorrisJobke** [comment]
Let's close this for now as this would be the way to accomplish this and the server already provides the underlying features.

**Comment by vlldk** [comment]
Cool will look into it - but shouldn’t it be implemented by default?

**Comment by MorrisJobke** [comment]
> Cool will look into it - but shouldn’t it be implemented by default?

Don't know if some download managers need something special to indicate that it works. Would be nice to know the exact problems.
