### ISSUE TITLE
external folder can not be shared with delete permissions

### ISSUE THREAD

**Issue by fafische** [nextcloud/server#8931]
### Steps to reproduce
1. configure external folder (e.g. local folder)
2. share the folder with an user
3. try to set permission "can delete"

### Expected behaviour
It is is possible to allow file deletion within the share of an external folder.

### Actual behaviour
Permission "can delete" is not visible when sharing the external folder itself and can not be granted to the share-partner. When sharing a subfolder of an external folder it is possible to grant permission for file deletion. It is possible within webinterface to create and delete files within root of external folder.

### Server configuration

**Operating system**:
Arch Linux

**Web server:**
Apache/2.4.29

**Database:**
mysql  Ver 15.1 Distrib 10.1.31-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 7.2.3 (cli) (built: Mar  1 2018 16:50:09) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from long history of prior versions.

**Where did you install Nextcloud from:**
Updated within webinterface.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.3
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 10485760,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": "",
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "overwritewebroot": "\/owncloud",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable"
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Firefox 59.0.1
**Operating system:**
Windows 7

**Comment by MorrisJobke** [comment]
> Permission "can delete" is not visible when sharing the external folder itself and can not be granted to the share-partner. When sharing a subfolder of an external folder it is possible to grant permission for file deletion. It is possible within webinterface to create and delete files within root of external folder.

@icewind1991 I guess this is because the mount point itself is not deletable.

cc @nextcloud/sharing

**Comment by rullzer** [comment]
I think this is fixed by my fixes for https://github.com/nextcloud/server/pull/8564 as well

**Comment by MorrisJobke** [comment]
Fixed in #8564

**Comment by fafische** [comment]
Unfortunately the problem still exists in 13.0.2.

**Comment by rullzer** [comment]
Well yes. Because it was only merged against master (which will be NC14)
