### ISSUE TITLE
Cannot use Android client: ClientMapper does not exist

### ISSUE THREAD

**Issue by jose1711** [nextcloud/server#8933]
### Steps to reproduce
1. install Nextcloud or NextCloud Talk
2. enter server URL to connect

### Expected behaviour
User should be prompted for credentials

### Actual behaviour
Receive an internal error message

### Server configuration

**Operating system**: Alpine linux

**Web server:** nginx

**Database:** mariadb

**PHP version:** php5-5.6.34-r0

**Nextcloud version:** nextcloud-13.0.1-r0

**Updated from an older Nextcloud/ownCloud or fresh install:** update

**Where did you install Nextcloud from:** official repository (edge)

### Server log ###
Output of the same error triggered by running ```links https://URL/index.php/login/flow```

```
"reqId":"XXX","level":3,"time":"2018-03-21T22:36:28+00:00","remoteAddr":"192.168.0.119","user":"--","app":"index","method":"GET","url":"\/index.php\/login\/flow","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OC\\\\Core\\\\Controller\\\\ClientFlowLoginController! Class OCA\\\\OAuth2\\\\Db\\\\ClientMapper does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(118): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OC\\\\\\\\Core\\\\\\\\Control...')\\n#1 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(465): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OC\\\\\\\\Core\\\\\\\\Control...')\\n#2 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(438): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->queryNoFallback('OC\\\\\\\\Core\\\\\\\\Control...')\\n#3 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(102): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('OC\\\\\\\\Core\\\\\\\\Control...')\\n#4 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ClientFlowLogin...', 'showAuthPickerP...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#7 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/login\\\/flow')\\n#8 \\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":103}","userAgent":"Links (2.14; Linux 4.15.10-1-ARCH x86_64; GNU C 7.1.1; text)","version":"13.0.0.14"}
```

**Comment by MorrisJobke** [comment]
cc @tobiasKaminsky @mario

**Comment by mario** [comment]
@MorrisJobke sounds like a server/configuration issue? All we do is open a website.

**Comment by MorrisJobke** [comment]
> @MorrisJobke sounds like a server/configuration issue? All we do is open a website.

🙈 Sorry for the noise Android people ... you are right fully server related.

**Comment by MorrisJobke** [comment]
@joar Could you check if `core/Controller/ClientFlowLoginController.php` exists?

Maybe also run the CLI command `occ integrity:check-core` to verify that all files are correct.

**Comment by MorrisJobke** [comment]
Maybe also try to upgrade to 13.0.1 and test again.

**Comment by jose1711** [comment]
thank you, there's been a progress after installing nextcloud-oauth2. i am now able to log in using server-generated tokens. i will add more details later.

**Comment by MorrisJobke** [comment]
if you are able to login this ticket is solved. For followup problems, please open new tickets. Thanks

**Comment by vasyugan** [comment]
I am seeing the same here. When an android client or the next nextcloud desktop sync client tries to authenticate via oauth I see an "internal server error" and the log says: Message":"Could not resolve OC\\Core\\Controller\\ClientFlowLoginController! Class OCA\\OAuth2\\Db\\ClientMapper does not exist". But this class is supposed to be part of the Nextcloud core, isn't it?

**Comment by vasyugan** [comment]
When I grep for "ClientMapper" I only find it in core/Controller/ClientFlowLoginController.php , where it says:
use OCA\OAuth2\Db\ClientMapper;
Where is all this OCA\OAuth2 stuff supposed to be defined in the first place?
