### ISSUE TITLE
In 'Activity' files changes about 'Favorites' is error.

### ISSUE THREAD

**Issue by supermanlinux** [nextcloud/server#8934]
In 'Activity' files changes about '**Favorites**' is error.
![image](https://user-images.githubusercontent.com/34739130/37746089-67c60ca0-2db3-11e8-9f78-8b2e8e4e5c1c.png)
But in 'All activities' the describe about files in 'favorites' is correct.
![image](https://user-images.githubusercontent.com/34739130/37746322-9cd7ab64-2db4-11e8-8bc4-edba7c1b5270.png)

### Steps to reproduce
1.upload files.
2.**add** files to **favorites.**
3.**remove** files frim **favorites**.

### Expected behaviour
The files in '**Activity**'  about  '**Favorites** 'describe is correct and exactly.

### Actual behaviour
Files about **favorites** is error,it is created files  or deleted files, it should be  removed *** from your favorites or add *** to your favorites.

### Server configuration
Operating system:

**Web server:Nextcloud 14.0.0 alpha

**Database:MariaDB

**PHP version:PHP 7.0.22-0ubuntu0.16.04.1

Nextcloud version: Nextcloud 14.0.0 alpha
**Updated from an older Nextcloud/ownCloud or fresh install:**fresh install

**Where did you install Nextcloud from:github

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by MorrisJobke** [comment]
In general: best to be opened in https://github.com/nextcloud/activity/issues

**Comment by nickvergessen** [comment]
The favorites filter is behaving like the `Limit notifications about creation and changes to your favorite files` option.
So it shows the stories about your favorite files, not the (un)favoriting actions.
