### ISSUE TITLE
NC 13.0.1 - problem updating an app which is part of the base package

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#8938]
## Expected behavior
If a new version of e.g. the PDF Viewer app is displayed on the list of apps to be updated, it should be possible to update it as it is possible for other apps too.

## Current behavior
If the App menu is opened, a new version of the PDF Viewer app (**v1.2.1**) is disabled as to be updatable. If you click on the update button the app is installed and removed from the list. If you now reselect the Apps menu the same app is shown again as to be updateble.

## My own analysis
First I've checked if the new PDF Viewer app v1.2.1 has correctly been downloaded and extracted. This step has successfully been finished and I found the files in the `apps2/files_pdfviewer` directory. Due to the fact that this app is usally part of the Nextcloud base package I checked the `apps` directory where indeed the old version of the app still exists. For testing purposes I deleted the app from that directory and kicked-off the update procedure which succeeds.
My assumption is, that the problem arised because a base app should be updated and the original app version wasn't removed from the `apps` directory after it has been stored in the `apps2` directory, or the app wasn't replaced in the original `apps` directory due to the fact the writable flag for this direcotry has been set to **false**, as recommended in the installation instructions.

### Steps to reproduce
1. Open the Apps menu.
2. Check if a new version of the PDF Viewer app is shown and select to update it.
   Result: The PDF Viewer app reappears on the list of updatable apps.

#### Server Configuration
OS: Linux 3.16.54
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.34
Nextcloud version: 13.0.1
News app version: 12.0.1

#### Client Configuration
Browser: Mozilla Firefox 59.0.1
Operating system: Windows 10

**Comment by nickvergessen** [comment]
Let's continue in #8929
