### ISSUE TITLE
On Mobile: Bad utilization of space for Folder/File Names on Website

### ISSUE THREAD

**Issue by johnyb0y** [nextcloud/server#8940]
![photo_2018-03-22_11-05-27](https://user-images.githubusercontent.com/12081528/37764398-e5e4ae26-2dc1-11e8-9260-5d98bdd7b755.jpg)

### Steps to reproduce
1. Visit your Nextcloud Website via an iOS Device. Tested on iPhone 7,iOS 11.2.6. Have not tested on iPad or Android devices.

### Expected behaviour
The names of Folders and Files should not be cut off with so much free space available. 

### Actual behaviour
They get cut off. Makes it very hard to navigate if you don't know the folder structure.

### Server configuration

**Operating system**: Debian 9.4

**Web server:** Apache2 Debian Stable

**Database:** MariaDB Debian Stable

**PHP version:** PHP7 Debian Stable

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Kept up-to-date since Nextcloud 10

**Where did you install Nextcloud from:** offical tar package

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
</details>

**Are you using external storage, if yes which one:** One external storage, SMB

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Any iOS Browser, they all use the same engine. Probably also Android, haven't tested it.

**Comment by tflidd** [comment]
@nextcloud/designers

**Comment by jancborchardt** [comment]
Can confirm this happening on Android too, it seems to be a regression. @nextcloud/designers

**Comment by MorrisJobke** [comment]
Wanted to bisect this: It was already present in 12.0.0 :/

It seems to originate in 5c7ad6d3ec91ee81012b2888017b95fccafea422 :/ The parent of this commit still works: 7e95837097

I would say that the re-ordering broke it.

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/server/pull/3972/files#r182583037

Maybe @skjnldsv or @juliushaertl want's to look into this

**Comment by juliushaertl** [comment]
I cannot reproduce the issue on android or using the webinspector. Maybe @skjnldsv 

![screenshot_20180419-113539](https://user-images.githubusercontent.com/3404133/38984233-7069dd4a-43c6-11e8-9f60-6dace30453aa.png)

**Comment by MorrisJobke** [comment]
happens ins safari and chrome for example:

<img width="1346" alt="bildschirmfoto 2018-04-19 um 13 54 18" src="https://user-images.githubusercontent.com/245432/38990064-3046af00-43d9-11e8-8119-2f54921076c6.png">

**Comment by juliushaertl** [comment]
Ah, I was missing that it is mainly happening on public shared links. I'll have a look.
