### ISSUE TITLE
Automatically activate expiration date  via email address

### ISSUE THREAD

**Issue by Oz246** [nextcloud/server#8941]
Hello everyone,

Is it possible to automatically activate each share via email address an expiration date (7 days) as the picture attached
<a href='http://www.casimages.com/i/180322122730709343.jpg.html' title='CLOUDED' target='_blank'><img src='http://nsa39.casimages.com/img/2018/03/22/mini_180322122730709343.jpg' border='0' alt='CLOUDED' /></a>

**Comment by tflidd** [comment]
You can already set default expiration dates for shares. You want explicitly one only applying for shares via mail (link)?

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing @nextcloud/designers Does that make sense?

**Comment by skjnldsv** [comment]
I don't really know :/
Don't we already have a default expire share?

**Comment by juliushaertl** [comment]
You can set a default expiration in the sharing settings. I see no point in adding another option for email shares since the current setting already applies to link shares in gerneral and the usecase for a separate setting for email shares is really small.
