### ISSUE TITLE
Automatic email sending for shared folder sends users main password!

### ISSUE THREAD

**Issue by kevinsm** [nextcloud/server#8944]
### Steps to reproduce
1. setup a normal user
2. create a shared folder, enter email for invitee and set password. Select filedrop only. Select password protect and enter password again
3. click other places to "commit"

### Expected behaviour
destination email should receive a link of filedrop with temporary password 

### Actual behaviour
destination email receives 2 emails one with temporary password and another with the NextCloud user's main password

### Server configuration

**Operating system**: centos 7

**Web server:** Apache

**Database:** SQLLite

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page) 13

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** official site

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
@kevinsm Do you store your password in your browser?

**Comment by MorrisJobke** [comment]
> yes. But besides there is no warning its going to do it. The email leaves silently.

Thanks - we are looking into it.

**Comment by MorrisJobke** [comment]
We can't reproduce your issue here and as this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

Maybe something in the overall setup of how emails are handled on that system is off a bit.
