### ISSUE TITLE
Internal Sites App

### ISSUE THREAD

**Issue by Megatronic79** [nextcloud/server#8950]
Hi Devs,

Is there any possibility (road mapped?) of an App to be included that will publish Internal Sites via Nextcloud when extrernal to the host network? Much like the external sites App works but securely shows internal sites such as an Intranet? Document Management systems? etc..

Cheers

Stephen

**Comment by tflidd** [comment]
You would have to use Nextcloud as a proxy (browser interface-app within Nextcloud) ...., a proper way I could imagine, to build apps on Nextcloud that connect to your internal services via api.

If it is just a proxy, I don't know if it is easy to do this in a secure manner. Especially if there is already a dedicated solution for this which is well tested: VPN.

@jospoortvliet @LukasReschke can probably tell you if that can be expected soon or if it is very likely/unlikely.

**Comment by MorrisJobke** [comment]
There is the external sites app, but it does not proxy to not cause a security problem in your network (attackers could use the admin account to activate that in the external sites app to access data that is only accessible by Nextcloud).

Thus this will not be implemented by the external sites app. You could write your own app that does this, but it is not on any roadmap from our side.
