### ISSUE TITLE
Uploading large files fails

### ISSUE THREAD

**Issue by realies** [nextcloud/server#8954]
Uploading large files fails with
```
172.17.0.1 - aaxjDd3W5Dkn8xm [22/Mar/2018:19:18:19 +0200] "PUT /public.php/webdav/PSC_1718_PMW2_1777.MXF HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"

172.17.0.1 - aaxjDd3W5Dkn8xm [22/Mar/2018:19:31:10 +0200] "PUT /public.php/webdav/PSC_1718_PMW2_1777.MXF HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
```

Latest stable Nextcloud. PHP upload limit is set to 128GB and file-size is 20GB. Nothing in the error or `nextcloud.log` files. What can be done to aid this?

**Comment by casKd-dev** [comment]
**Depending on the web server you may use (Apache/Nginx/etc.) you may need to set up also the web server configuration.**

- For Apache it shouldn't be a problem if you configured your nextcloud settings and the php.ini correctly.
- For Nginx add these to your configuration(s):
`client_max_body_size xGB; ## x being the limit in GB`

**Comment by realies** [comment]
@casKd-dev, Nginx's relevant server sections is set to `client_max_body_size 0;` to [disable checking of client request body size](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size).

Docker container Nginx config: http://ix.io/127A
Container port 443 mapped to host container port 420
Public facing Nginx config: http://ix.io/127J

PHP upload limit set to 128GB from within Nextcloud.

**Comment by CHazz** [comment]
php is very very bad for upload big files .. eating lots of memory ... how much ram have ? for 20gb file must have maybe 32gb ram ...  maybe try app flow upload its maybe java .. bud not known ...

**Comment by MorrisJobke** [comment]
Starting with Nextcloud 13 also the web UI when users are logged in is using chunked upload which should make the upload of large files a lot more stable. Thus I will close this for now.

https://github.com/nextcloud/server/pull/7056
