### ISSUE TITLE
App password invalidated if IMAP auth server not accessible

### ISSUE THREAD

**Issue by dugite-code** [nextcloud/server#8958]
### Steps to reproduce
1. Use IMAP external Auth + App password
2. Take IMAP server offline (Maintenance/ Network issue)
3. Attempt to connect with app password (i.e. with DavDroid

### Expected behaviour
App should fail to connect but once IMAP server available again be able to connect

### Actual behaviour
App fails to connect and that specific app password is now permanently invalidated.

### Server configuration

**Operating system**:
Debian 9

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
PHP 7.0 fpm

**Nextcloud version:** (see Nextcloud admin page)
13.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
12.0

**Comment by tflidd** [comment]
@LukasReschke is this a wanted behavior or a bug?

**Comment by dugite-code** [comment]
I'm now using imapproxy to mitigate the issue a bit. My email server is very low spec so it sometimes takes a while to respond properly.

**Comment by internethering** [comment]
> is this a wanted behavior or a bug?

In my opinion it's a bug cause it confuses users: I know one who typed in his password everytime. Like maintaince mode apps should go simply offline and online again, if IMAP Server is back online.
