### ISSUE TITLE
Gray-out relevant configuration options when config_is_read_only is set

### ISSUE THREAD

**Issue by Tsuroerusu** [nextcloud/server#8960]
I run a server that hosts Nextcloud instances for my customers, and as the server admin, I enforce various settings such as SMTP settings, trashbin retention etc. Because of that, I have a read-only configuration file, so that the SMTP settings cannot be changed and so on.

I just noticed that when 'config_is_read_only' is enabled, what happens right now is that the options in the Settings appear as they would with a writeable configuration, and if one tries to change them it just hangs at "Saving...". That might confuse users into thinking they did something wrong or something is not working.

I would like to propose that either when either 'config_is_read_only' or a secondary option related to it is set, the options in the Settings that now cannot be altered through the web UI be grayed out. This would be similar to how Nextcloud grays out PHP-related settings that are not alterable through the web UI, for example the maximum upload size listed under "Additional settings".

### Steps to reproduce
1. Set 'config_is_read_only' in config.php
2. Look through the web UI and try to change settings that are stored in config.php
3. Notice how it just stays at "Saving...".

### Expected behaviour
The settings that cannot be changed after setting the 'config_is_read_only' option should be grayed out similarly to how settings that relate to PHP or the server in general are grayed out of the relevant configuration files are not writeable.

### Actual behaviour
The settings appear alterable, and one can actually try to edit them, but when it then tries to save the change it just says "Saving..." in red, and nothing happens as  far as the user is concerned.

**Comment by MorrisJobke** [comment]
Those are the related settings:

* email settings
* updater channel
* log level

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
