### ISSUE TITLE
Can't upload conflicts pictures in 'gallery'.

### ISSUE THREAD

**Issue by supermanlinux** [nextcloud/server#8961]
In **Gallery**, upload an **conflict picture**,in conflict dialog, the **continue** button is **disabled**, click have no effects. I have no ideas with this problem,but in files list,that is ok.
![33](https://user-images.githubusercontent.com/34739130/37824996-5a261aba-2ec9-11e8-8928-e4fcc3e1ab0a.png)

### Steps to reproduce
1.goto the gallery and upload pictures.
2.in the conflict dialog,choose new files and already existing files.
3.click the continue button.

### Expected behaviour
After click the continue button,new files and already existing files can upload.

### Actual behaviour
The continue button is disabled. Can't upload pictures.

### Server configuration
Database:10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04
PHP version:PHP 7.0.22
cloud server:Nextcloud
cloud version: 13.0.0.4

**Comment by tflidd** [comment]
For my understanding, you have to choose which version you consider to be the correct one (the other version will be named as conflict-file. If it is like that, the interface should not allow to select both at the same time.

And: It would be great to detect identical files, in many cases it is just the modification date that is different.

**Comment by supermanlinux** [comment]
@tflidd  I know you speak.But in '**files**' page, the continue button is active, new files and already existing files **can upload**.
![112](https://user-images.githubusercontent.com/34739130/37876375-19c0ddc8-307e-11e8-8dc6-c0fe1677b86a.jpg)
 So if it is like that, the interface should not allow to select both at the same time.But the 'files' page can.
I am very confused,thanks for help.

**Comment by MorrisJobke** [comment]
cc @skjnldsv @danxuliu this is more a gallery app thing isn't it?

**Comment by MorrisJobke** [comment]
Duplicate of https://github.com/nextcloud/gallery/issues/398
