### ISSUE TITLE
Alpine installation failed 

### ISSUE THREAD

**Issue by iGlaedr** [nextcloud/server#8963]
### Steps to reproduce
1. Setup Alpine
2. Install NGINX PHP7 MariaDB with all dependencies 
3. Execute the setup script to download nextcloud 

### Expected behaviour
Tell us what should happen

Setup Page (after using the setup-nextcloud.php script)

### Actual behaviour
Tell us what happens instead

Error Page 

Internal Server Error
The server was unable to complete your request.

### Server configuration

**Operating system**: Alpine in a VM on ESXI

**Web server:** NGINX

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** download by setup script 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data  ba
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes nfs share

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
 cat nextcloud.log 
{"reqId":"Rk15oJOeFxx6ulcWiVoJ","level":3,"time":"2018-03-23T12:41:38+00:00","remoteAddr":"192.168.1.5","user":"--","app":"base","method":"GET","url":"\/","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"call_user_func_array() expects parameter 1 to be a valid callback, function 'session_name' not found or invalid function name\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(2, 'call_user_func_...', '\\\/var\\\/www\\\/cl0ud\\\/...', 175, Array)\\n#1 \\\/var\\\/www\\\/cl0ud\\\/lib\\\/private\\\/Session\\\/Internal.php(175): call_user_func_array('session_name', Array)\\n#2 \\\/var\\\/www\\\/cl0ud\\\/lib\\\/private\\\/Session\\\/Internal.php(48): OC\\\\Session\\\\Internal->invoke('session_name', Array)\\n#3 \\\/var\\\/www\\\/cl0ud\\\/lib\\\/base.php(436): OC\\\\Session\\\\Internal->__construct('oc5cpxdqajkw')\\n#4 \\\/var\\\/www\\\/cl0ud\\\/lib\\\/base.php(663): OC::initSession()\\n#5 \\\/var\\\/www\\\/cl0ud\\\/lib\\\/base.php(1080): OC::init()\\n#6 \\\/var\\\/www\\\/cl0ud\\\/index.php(35): require_once('\\\/var\\\/www\\\/cl0ud\\\/...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/cl0ud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":151}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit\/604.1.38 (KHTML, like Gecko) Version\/11.0 Safari\/604.1.38","version":""}
glugga:/var/www/cl0ud/data# 
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Wieke** [comment]
I had the same issue, turns out the installation instructions of php7 on the alpine wiki omits the php7-session package, which is required for session_name to work. These are the additional packages I ended up installing:

```
apk add php7-session php7-mbstring php7-xmlwriter php7-simplexml php7-zlib
```

**Comment by blizzz** [comment]
Closing, not an NC issue, and @Wieke kindly posted some advice.
