### ISSUE TITLE
update from 13 to  13.01 NextCloud not working anymore

### ISSUE THREAD

**Issue by kevinsm** [nextcloud/server#8965]
### Steps to reproduce
1. Update via we
2. restarts web
3. nothing

### Expected behaviour
Tell us what should happen
Next Cloud working

### Actual behaviour
Tell us what happens instead
Nothing. Nothing in errorlogs. All silent. URL does not work anymore and I do not know why

### Server configuration

**Operating system**:
centos 7

**Web server:**
Apache

**Database:**
SQLlite

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
13.01

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from 13

**Where did you install Nextcloud from:**
nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kevinsm** [comment]
OK sorry my bad. Log says

"message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(337): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(79): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(190): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(187): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(34): OCP\\\\Defaults->getLogo()\\n

**Comment by kevinsm** [comment]
OK so after trying to restore to 13.0 and failed and go back to original its started to work! Maybe its an ownership problem. Anyway after upgrade I lost all apps I had added and the group folder!

**Comment by kevinsm** [comment]
OK so apps where disabled and I had to re-enable all

No idea what happened there during the upgrade. Would appreciate a comment at your earliest for next time

Thanks

**Comment by MorrisJobke** [comment]
> {"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"theming.Theming.getLogo\" as such route does not

Looks like something like https://github.com/nextcloud/server/pull/5890

No idea why it failed all out of a sudden and then worked, but nice that it works again.
