### ISSUE TITLE
Error updating web\command line 13.0.0 to 13.0.1

### ISSUE THREAD

**Issue by LeandroLouvem** [nextcloud/server#8967]
Steps to Reproduce
1. web update
2
3

### Expected behavior
update

### Real Behavior
check verify nexcloud.log

### Server Configuration

** Operational system **:
ubuntu running on Hyper-V on windows server 2012

** Web server: **

**Data base:**

** PHP Version: **

** Nextcloud version: ** (see the Nextcloud administration page)
13.0.0

** Updated from a Nextcloud / ownCloud or recent installation: **

** Where you installed Nextcloud from: **

https://shop.techandme.se/index.php/product/nextcloud-vm-microsoft-hyper-v-vhd/

** Signature Status: **
<details>
<summary> Signature status </ summary>

(For example
Log in to the admin user in your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
(For example
</ details>

** List of activated applications: **
<details>
<summary> Application List </ summary>

(For example
If you have access to your command line
sudo -u www-data php occ app: list
from within your Nextcloud installation folder
(For example
</ details>

** NextCloud Configuration: **
<details>
<summary> Configuration Report </ summary>

(For example
If you have access to your command line
sudo -u www-data php occ config: list system
from within your Nextcloud installation folder

or

Enter your config.php content here.
Be sure to remove any confidential content, such as passwords. (for example, database password, passwordsalt, secret, smtp password, ...)
(For example
</ details>

** You are using external storage, if yes what: ** local / smb / sftp / ...

** You are using encryption: ** yes / no

** You are using an external user backend, if so which: ** LDAP / ActiveDirectory / Webdav / ...

#### LDAP Configuration (delete this part if not used)
<details>
<summary> LDAP config </ summary>

(For example
With access to your command line
sudo -u www-data php do occ ldap: show-config
from within your Nextcloud installation folder

Without access to your command line, download the data / owncloud.db to your location
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE`appid` = 'user_ldap';

Eventually, replace sensitive data such as the name / IP address of your server or LDAP groups.
(For example
</ details>

### Client Configuration
** Browser: **

** Operational system: **

#### Web Server Error Log
<details>
<summary> Web server error logging </ summary>

(For example
Enter your web server log here
(For example
</ details>

#### NextCloud Log (data / nextcloud.log)
<details>
<summary> Next Log Log </ summary>

{"reqId": "LKhxiPqdWeb2JMPNRYIv", "level": 2, "time": "March 23, 2018 15:57:20", "remoteAddr": "177.137.232.3", "user": "-" "app": "core", "method": "PROPFIND", "URL": "\ / remote.php \ / dav \ / files \ /leandro.louvem \ / TI \ / e & L \ / backup \ "Mozilla \ /5.0 (Windows)", "userAgent", "message": "Login failed: 'leandrolouven@gmail.com' (Remote IP: '177.137.232.3')" mirall \ / 2.3.3 (build 1) (Nextcloud) "," version ":" 13.0.0.14 "}
{"reqId": "LKhxiPqdWeb2JMPNRYIv", "level": 0, "time": "March 23, 2018 15:57:20", "remoteAddr": "177.137.232.3", "user": "leandro.louvem "" app ":" WebDAV "," method ":" PROPFIND "," URL ":" \\ remote.php \ / DAV \ / \ files /leandro.louvem \ / TI \ / e & L \ / backup \ "Exception: {\" exception \ ": \" Knowledge \\\\ DAV \\\\ Exception \\\\ NotFound \ ", \" message \ Can not be located \ ", \" Code \ ": 0, \" Trace \ ": \" \ 0 \\\ / var \\\ / www \\\ / nextcloud \\\ / 3rdparty \\\ / sabre \\\ / DAV \\\ / lib \\\ / DAV \\\ / Tree.php (76): OCA \\\\ DAV \\ \\ \\\\\\\\\\\\\\\\\\\\\\\\\ Saber \\\\ Directory-> getChild ('TI') \\ n # 1 \\\ / var \\\ / www \\\ / nextcloud \\\ / 3rdparty \\\ / Saber \\\\ DAV \\\\ Tree-> getNodeForPath ('files \\\ / leandro. l ') \\ n # 2 \\\ / var \\\ / www \\\ / nextcloud \\\ / 3rdparty \\\ / saber \\\ / dav \\\\\\\\\\\\\\\\\\\\\ Tree.php (71): Saber \\\\ DAV \\\\ Tree-> getNodeForPath ('files \\\ / leandro.l ...') \\ n # 3 \\\ / var \\\ / www \\\ / nextcloud \\\ / 3rdparty \\\ / sabre \\\ / DAV \\\ / lib \\\ / DAV \\\ / Tree .php (71): Saber \\\\ DAV \\\\ Tree-> getNodeForPath ('files \\\ / leandro.l ...') \\ n # 4 \\\ / var \\\ / www \\\ / nextcloud \\\ / 3rdparty \\\ / sabre \\\ / DAV \\\ / lib \\\ / DAV \\\ / Tree.php (71): Saber \\\\ DAV \\\ \ Tree-> getNodeForPath ('files \\\ / leandro.l ...') \\ n # 5 \\\ / var \\\ / www \\\ / nextcloud \\\ / 3rdparty \\\ / saber \\\ / DAV \\\ / lib \\\ / DAV \\\ / Server.php (967): Saber \\\\ DAV \\\\ Tree-> getNodeForPath ('files \\\ / leandro

**Comment by Orbital-Bit** [comment]
hi, 
as far as i know techandme.se images do not use/run the web updater.
you must run an update script (sudo bash /var/scripts/update.sh) or manually update as described in the Nextcloud documentation.

**Comment by MorrisJobke** [comment]
If this is not the VM then we highly recommend the built-in updater: https://docs.nextcloud.com/server/13/admin_manual/maintenance/update.html

Beside that: what @Orbital-Bit said is true.
