### ISSUE TITLE
theming app not working after update from 12.0.6 to 13.0.1

### ISSUE THREAD

**Issue by profhccaesar** [nextcloud/server#8969]
### Steps to reproduce
1. Update Nextcloud from 12.0.6 to 13.0.1 ("stable" update channel)
2. Now the login screen background, title bar and folder icons appears in an ugly brown color
3. Login as admin, go to settings -> theming and change the color
4. Folder icons uses now that color, but the login screen background and title bar still use that brown color
5. Go to settings -> theming again and upload a background image
6. Logout
7. The background image is not used

### Expected behaviour
Setting a color in the theming app should change the background and title bar color as well as folder icon color.
Uploaded background image should be used on the login screen.

### Actual behaviour
Setting a color in the theming app changes only the color of the folder icons, nothing else.
Setting a background image has no effect.

### Server configuration

**Operating system**:
Ubuntu Linux 16.04.3 x86_64 Server

**Web server:**
Apache 2.4.18

**Database:**
MySql Server 5.7.21

**PHP version:**
7.0.28

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
12.0.6

**Where did you install Nextcloud from:**
Integrated Web Updater

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - admin_audit: 1.3.0
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - contacts: 2.1.2
  - dav: 1.4.6
  - drawio: 0.8.9
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - weather: 1.5.1
  - workflowengine: 1.3.0
Disabled:
  - activity
  - comments
  - encryption
  - external
  - federation
  - files_external
  - files_retention
  - keeweb
  - systemtags
  - user_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "web01",
            "web01.hoelle-online.de",
            "web01.dmz.hoelle-online.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/dmzlx01.dmz.hoelle-online.de\/nextcloud",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "log_type": "syslog",
        "log_authfailip": true,
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "updater.release.channel": "stable",
        "maintenance": false,
        "loglevel": 2,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "preview_max_x": 1280,
        "preview_max_y": 1280,
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\PNG",
            "1": "OC\\Preview\\JPEG",
            "2": "OC\\Preview\\GIF",
            "11": "OC\\Preview\\Illustrator",
            "12": "OC\\Preview\\Postscript",
            "13": "OC\\Preview\\Photoshop",
            "14": "OC\\Preview\\TIFF"
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN"
    }
}

</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+--------------------------------------------------------------------------------------+
| Configuration                 |                                                                                      |
+-------------------------------+--------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                      |
| hasPagedResultSupport         |                                                                                      |
| homeFolderNamingRule          |                                                                                      |
| lastJpegPhotoLookup           | 0                                                                                    |
| ldapAgentName                 | cn=restricted,dc=int,dc=xxx,dc=de                                          |
| ldapAgentPassword             | ***                                                                                  |
| ldapAttributesForGroupSearch  |                                                                                      |
| ldapAttributesForUserSearch   |                                                                                      |
| ldapBackupHost                |                                                                                      |
| ldapBackupPort                |                                                                                      |
| ldapBase                      | dc=int,dc=xxx,dc=de                                                        |
| ldapBaseGroups                | dc=int,dc=xxx,dc=de                                                        |
| ldapBaseUsers                 | dc=int,dc=xxx,dc=de                                                        |
| ldapCacheTTL                  | 600                                                                                  |
| ldapConfigurationActive       | 1                                                                                    |
| ldapDefaultPPolicyDN          |                                                                                      |
| ldapDynamicGroupMemberURL     |                                                                                      |
| ldapEmailAttribute            | mail                                                                                 |
| ldapExperiencedAdmin          | 0                                                                                    |
| ldapExpertUUIDGroupAttr       |                                                                                      |
| ldapExpertUUIDUserAttr        |                                                                                      |
| ldapExpertUsernameAttr        |                                                                                      |
| ldapGidNumber                 | gidNumber                                                                            |
| ldapGroupDisplayName          | cn                                                                                   |
| ldapGroupFilter               | (&(|(objectclass=posixGroup))(|(cn=nextcloud)))                                       |
| ldapGroupFilterGroups         | nextcloud                                                                             |
| ldapGroupFilterMode           | 0                                                                                    |
| ldapGroupFilterObjectclass    | posixGroup                                                                           |
| ldapGroupMemberAssocAttr      | memberUid                                                                            |
| ldapHost                      | ldap                                                                                 |
| ldapIgnoreNamingRules         |                                                                                      |
| ldapLoginFilter               | (&(|(objectclass=posixAccount))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                      |
| ldapLoginFilterEmail          | 1                                                                                    |
| ldapLoginFilterMode           | 0                                                                                    |
| ldapLoginFilterUsername       | 1                                                                                    |
| ldapNestedGroups              | 0                                                                                    |
| ldapOverrideMainServer        |                                                                                      |
| ldapPagingSize                | 500                                                                                  |
| ldapPort                      | 389                                                                                  |
| ldapQuotaAttribute            |                                                                                      |
| ldapQuotaDefault              |                                                                                      |
| ldapTLS                       | 0                                                                                    |
| ldapUserDisplayName           | displayName                                                                          |
| ldapUserDisplayName2          |                                                                                      |
| ldapUserFilter                | (|(objectclass=posixAccount))                                                        |
| ldapUserFilterGroups          |                                                                                      |
| ldapUserFilterMode            | 0                                                                                    |
| ldapUserFilterObjectclass     | posixAccount                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                 |
| ldapUuidUserAttribute         | auto                                                                                 |
| turnOffCertCheck              | 0                                                                                    |
| turnOnPasswordChange          | 0                                                                                    |
| useMemberOfToDetectMembership | 1                                                                                    |
+-------------------------------+--------------------------------------------------------------------------------------+

</details>

### Client configuration
**Browser:**
Any (tested Firefox, Chrome, Opera, IE)

**Operating system:**
Any (tested Linux, Windows)

#### Web server error log
<details>
<summary>Web server error log</summary>
No errors.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

(empty file)

</details>

#### Browser log
<details>
<summary>Browser log</summary>
No errors.
</details>

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming

**Comment by juliushaertl** [comment]
@profhccaesar Is this still an issue with 13.0.2?

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
