### ISSUE TITLE
Moodle : When using File Picker in Moodle, Login into Nextcloud shows up nextcloud webpage instead of files in nextcloud

### ISSUE THREAD

**Issue by pkmkrishnakumar** [nextcloud/server#8973]
### Steps to reproduce
1. Log in into moodle and select file picker
![image](https://user-images.githubusercontent.com/29704829/37871948-44b7b034-3019-11e8-9ff2-eee885a227d4.png)

2.  Click on Login in to your account

![image](https://user-images.githubusercontent.com/29704829/37871949-4efd9108-3019-11e8-9c5b-c01beda95654.png)

3.Click on Grant Access

![image](https://user-images.githubusercontent.com/29704829/37871950-564beacc-3019-11e8-9848-5f52d1c65839.png)

4.  When login into the nextcloud via popup window ,it logs into nextcloud and not showing the files in file picker.

![image](https://user-images.githubusercontent.com/29704829/37871953-60a327f6-3019-11e8-8da8-260ad18965a4.png)

### Expected behaviour

It show up the files in Nextcloud in Moodle File Picker Dialog box

![image](https://user-images.githubusercontent.com/29704829/37872013-14d4a2d0-301b-11e8-8117-45b1a5ba1a49.png)

### Actual behaviour
Pop window opened for Login, show the default window of nextcloud.

![image](https://user-images.githubusercontent.com/29704829/37872015-25039594-301b-11e8-907d-d86052d8f38d.png)

Configurations for moodle-repository_owncloud App in Moodle & Nextcloud:

![image](https://user-images.githubusercontent.com/29704829/37871985-76c2a060-301a-11e8-8725-703f05b89109.png)
![image](https://user-images.githubusercontent.com/29704829/37871986-79820b56-301a-11e8-9ffe-9d1190ed49de.png)
![image](https://user-images.githubusercontent.com/29704829/37871987-7ca4f64a-301a-11e8-8eb9-20ea5f01c446.png)

Nextcloud OAuth 2.0 Client settings:

![image](https://user-images.githubusercontent.com/29704829/37871989-81089840-301a-11e8-884d-121d7a381769.png)

Previously I created issue with " learnweb/moodle-repository_owncloud" App
Link to Issue: https://github.com/learnweb/moodle-repository_owncloud/issues/31

But from various discussions it is found that nextcloud is not redirecting properly

Please help me out sort this problem

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP 7.0

Enable Apps:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - apporder: 0.4.1
  - audioplayer: 2.2.5
  - bookmarks: 0.11.0
  - calendar: 1.6.1
  - circles: 0.13.6
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_reader: 1.2.3
  - files_rightclick: 0.3.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - limit_login_to_ip: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - music: 0.5.6
  - news: 12.0.1
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_external: 0.4
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - firstrunwizard
  - survey_client

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "lms-jit",
            "10.10.1.150"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/lms-jit\/fcloud",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "production",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0,
        "maintenance": false,
        "theme": "",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        }
    }
}

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

**Comment by MorrisJobke** [comment]
@rullzer Haven't you fixed the Moodle integration?

**Comment by pkmkrishnakumar** [comment]
still i am facing the issue, is there any fix or suggestion to sort it out?

**Comment by skjnldsv** [comment]
Still happening @pkmkrishnakumar ?
