### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable php 7.2

### ISSUE THREAD

**Issue by si458** [nextcloud/server#8975]
### Steps to reproduce
1. setup latest apache and php from ondrej and latest mysql from mysql apt
2. install
3. shows errors inside logging under settings

### Expected behaviour
Tell us what should happen
no errors relating to count change in php 7.2

### Actual behaviour
Tell us what happens instead

count(): Parameter must be an array or an object that implements Countable at /var/www/html/apps/ojsxc/lib/newcontentcontainer.php#36
count(): Parameter must be an array or an object that implements Countable at /var/www/html/apps/ojsxc/lib/Controller/HttpBindController.php#181

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.29

**Database:** MySQL 5.7.21

**PHP version:** PHP 7.2.3

**Nextcloud version:** (see Nextcloud admin page) 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install 

**Where did you install Nextcloud from:** off your website using zip file

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - bookmarks: 0.11.0
  - calendar: 1.6.1
  - caniupdate: 0.1.2
  - checksum: 0.3.5
  - comments: 1.3.0
  - contacts: 2.1.2
  - dashboard: 4.0.6
  - dav: 1.4.6
  - dicomviewer: 0.0.2
  - drawio: 0.8.9
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ojsxc: 3.3.2
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_external: 0.4
  - user_ldap: 1.3.1
  - user_usage_report: 1.0.1
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - w2g2
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.68.249"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/192.168.68.249",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
</details>

**Are you using external storage, if yes which one:** not at the moment

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Active Directory by LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                              |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                            |
| hasPagedResultSupport         |                                                                                                                              |
| homeFolderNamingRule          |                                                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                                                            |
| ldapAgentName                 | CN=Administrator,CN=Users,DC=fth,DC=com                                                                                      |
| ldapAgentPassword             | ***                                                                                                                          |
| ldapAttributesForGroupSearch  |                                                                                                                              |
| ldapAttributesForUserSearch   |                                                                                                                              |
| ldapBackupHost                |                                                                                                                              |
| ldapBackupPort                |                                                                                                                              |
| ldapBase                      | DC=fth,DC=com                                                                                                                |
| ldapBaseGroups                | DC=fth,DC=com                                                                                                                |
| ldapBaseUsers                 | DC=fth,DC=com                                                                                                                |
| ldapCacheTTL                  | 600                                                                                                                          |
| ldapConfigurationActive       | 1                                                                                                                            |
| ldapDefaultPPolicyDN          |                                                                                                                              |
| ldapDynamicGroupMemberURL     |                                                                                                                              |
| ldapEmailAttribute            |                                                                                                                              |
| ldapExperiencedAdmin          | 0                                                                                                                            |
| ldapExpertUUIDGroupAttr       |                                                                                                                              |
| ldapExpertUUIDUserAttr        |                                                                                                                              |
| ldapExpertUsernameAttr        |                                                                                                                              |
| ldapGidNumber                 | gidNumber                                                                                                                    |
| ldapGroupDisplayName          | cn                                                                                                                           |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=StaffGroup)))                                                                                  |
| ldapGroupFilterGroups         | StaffGroup                                                                                                                   |
| ldapGroupFilterMode           | 0                                                                                                                            |
| ldapGroupFilterObjectclass    | group                                                                                                                        |
| ldapGroupMemberAssocAttr      | member                                                                                                                       |
| ldapHost                      | 192.168.68.xxx                                                                                                               |
| ldapIgnoreNamingRules         |                                                                                                                              |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=StaffGroup,OU=Staff,DC=fth,DC=com)(primaryGroupID=1116))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                              |
| ldapLoginFilterEmail          | 0                                                                                                                            |
| ldapLoginFilterMode           | 0                                                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                                                            |
| ldapNestedGroups              | 0                                                                                                                            |
| ldapOverrideMainServer        |                                                                                                                              |
| ldapPagingSize                | 500                                                                                                                          |
| ldapPort                      | 389                                                                                                                          |
| ldapQuotaAttribute            |                                                                                                                              |
| ldapQuotaDefault              |                                                                                                                              |
| ldapTLS                       | 0                                                                                                                            |
| ldapUserDisplayName           | displayname                                                                                                                  |
| ldapUserDisplayName2          |                                                                                                                              |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=StaffGroup,OU=Staff,DC=fth,DC=com)(primaryGroupID=1116))))                         |
| ldapUserFilterGroups          | StaffGroup                                                                                                                   |
| ldapUserFilterMode            | 0                                                                                                                            |
| ldapUserFilterObjectclass     | person                                                                                                                       |
| ldapUuidGroupAttribute        | auto                                                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                                                         |
| turnOffCertCheck              | 0                                                                                                                            |
| turnOnPasswordChange          | 0                                                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                                                            |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------+
</details>

### Client configuration
**Browser:** ANY

**Operating system:** ANY

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"4qB1YrK25mApPQcYcgJ5","level":3,"time":"2018-03-25T14:51:54+00:00","remoteAddr":"192.168.68.254","user":"41629FFE-703F-4B32-ADE1-FB438BDDF563","app":"PHP","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/html\/apps\/ojsxc\/lib\/Controller\/HttpBindController.php#181","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"4qB1YrK25mApPQcYcgJ5","level":3,"time":"2018-03-25T14:51:54+00:00","remoteAddr":"192.168.68.254","user":"41629FFE-703F-4B32-ADE1-FB438BDDF563","app":"PHP","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/html\/apps\/ojsxc\/lib\/newcontentcontainer.php#36","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"6rcNm6Gldo4fE3huNhyt","level":3,"time":"2018-03-25T14:52:05+00:00","remoteAddr":"192.168.68.254","user":"41629FFE-703F-4B32-ADE1-FB438BDDF563","app":"PHP","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/html\/apps\/ojsxc\/lib\/Controller\/HttpBindController.php#181","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"6rcNm6Gldo4fE3huNhyt","level":3,"time":"2018-03-25T14:52:05+00:00","remoteAddr":"192.168.68.254","user":"41629FFE-703F-4B32-ADE1-FB438BDDF563","app":"PHP","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/html\/apps\/ojsxc\/lib\/newcontentcontainer.php#36","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"plzMF668SSpKSlrTTNqZ","level":3,"time":"2018-03-25T14:52:16+00:00","remoteAddr":"192.168.68.254","user":"41629FFE-703F-4B32-ADE1-FB438BDDF563","app":"PHP","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/html\/apps\/ojsxc\/lib\/Controller\/HttpBindController.php#181","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"plzMF668SSpKSlrTTNqZ","level":3,"time":"2018-03-25T14:52:16+00:00","remoteAddr":"192.168.68.254","user":"41629FFE-703F-4B32-ADE1-FB438BDDF563","app":"PHP","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/html\/apps\/ojsxc\/lib\/newcontentcontainer.php#36","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"hBcKTQ7TD6AI6X37fYCg","level":3,"time":"2018-03-25T14:52:27+00:00","remoteAddr":"192.168.68.254","user":"41629FFE-703F-4B32-ADE1-FB438BDDF563","app":"PHP","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/html\/apps\/ojsxc\/lib\/Controller\/HttpBindController.php#181","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"hBcKTQ7TD6AI6X37fYCg","level":3,"time":"2018-03-25T14:52:27+00:00","remoteAddr":"192.168.68.254","user":"41629FFE-703F-4B32-ADE1-FB438BDDF563","app":"PHP","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/html\/apps\/ojsxc\/lib\/newcontentcontainer.php#36","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"vqGhpM24DvLF5CuRkRiM","level":3,"time":"2018-03-25T14:52:38+00:00","remoteAddr":"192.168.68.254","user":"41629FFE-703F-4B32-ADE1-FB438BDDF563","app":"PHP","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/html\/apps\/ojsxc\/lib\/Controller\/HttpBindController.php#181","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
{"reqId":"vqGhpM24DvLF5CuRkRiM","level":3,"time":"2018-03-25T14:52:38+00:00","remoteAddr":"192.168.68.254","user":"41629FFE-703F-4B32-ADE1-FB438BDDF563","app":"PHP","method":"POST","url":"\/index.php\/apps\/ojsxc\/http-bind","message":"count(): Parameter must be an array or an object that implements Countable at \/var\/www\/html\/apps\/ojsxc\/lib\/newcontentcontainer.php#36","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>
</details>

**Comment by ChristophWurst** [comment]
> count(): Parameter must be an array or an object that implements Countable at /var/www/html/apps/ojsxc/lib/newcontentcontainer.php#36

Please report that at the `ojsxc` app's issue tracker.
