### ISSUE TITLE
copying shared files on server-side-encrypted setup broken

### ISSUE THREAD

**Issue by himbeere** [nextcloud/server#8989]
### Steps to reproduce
1. create a new file (test.txt)
2. share file with someone (test.txt)
3. copy that shared file to another folder via webinterface
4. open that copied file

### Expected behaviour
File opens.

### Actual behaviour
Error message occurs: Wrong Signature!

### Server configuration

**Operating system**: Linux (Ubuntu 16.04)

**Web server:** Apache 2.4

**Database:** 5.7.21

**PHP version:** 7.0.28/

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 13.0.0

**Where did you install Nextcloud from:** Zip File

**Signing status:**

```
No errors have been found.
```

**List of activated apps:** Talk, Deck

```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - deck: 0.3.1
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_antivirus: 1.2.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - ransomware_protection: 1.1.0
  - registration: 0.4.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - files_clipboard
  - files_external
  - user_external
  - user_ldap
root@nextcloud:/
```

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.dev.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.dev.de",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***"
    }
}


**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

**Comment by himbeere** [comment]
Just figured this happens only with text or office documents.

**Comment by himbeere** [comment]
additionally i guess i saw the webserver replies "400 Bad Request". And this is how it looks in the Webconsole:
![bildschirmfoto 2018-03-26 um 17 03 02](https://user-images.githubusercontent.com/631865/37914681-10c89b6c-3118-11e8-8853-a191afdb78af.png)

**Comment by schiessle** [comment]
I tried it but I can't reproduce it. Can you reproduce it with the steps mentioned above reliable?

You share the single file, right. Who moves it afterwards to a folder, the owner or the recipient of the share?

**Comment by himbeere** [comment]
thanks for your answer @schiessle 

Did your text file had content? The error does not occur with empty files. And yes i can reproduce this error 100% with the four steps mentioned. I can give you temporary access to my dev server. Or I can make a screencast or something.

thanks and cheers
t.

**Comment by schiessle** [comment]
@himbeere yes, the text file had some content. I created it with the internal text editor. Can you please answer the other question as well, who moves the file in your scenario? The owner or the recipient of the share?

**Comment by himbeere** [comment]
In my scenario the owner copies the file which he previousely shared with someone. But further testing shows if the recipient of that shared file tries to copy + open that copied file it fails with the same error.

My use case is: An employee shares a file read only. The other employee can copy that file to his own document folder and now can edit the file.

thanks and cheers

**Comment by schiessle** [comment]
Now I see what might be the difference. I moved the file but you copied it. I will try again...

> My use case is: An employee shares a file read only. The other employee can copy that file to his own document folder and now can edit the file.

But in this case it is not the owner but the recipient of the file. As soon as the recipient copied the file the copy is of course independent from the original. I will try both...

**Comment by schiessle** [comment]
I could reproduce it now, fix is here https://github.com/nextcloud/server/pull/9018

**Comment by himbeere** [comment]
Thank you very much @schiessle. According to your PR this has nothing to do with sharing the file first? Interesting.

**Comment by schiessle** [comment]
@himbeere yes, this issue happens to me whether the file is shared or not
