### ISSUE TITLE
Extend installer UI to include Primary Storage options

### ISSUE THREAD

**Issue by spacemonkey** [nextcloud/server#8990]
Raising a hand to make it easy for folks using AWS to immediately point all of their storage to S3, as opposed to the current default (EBS, which is _not persistent_). We've made it dead simple to get up and running with AMIs, docker containers, droplets, and such - but none are pointing at a safe place to store all these files, which is a shame. Getting this hooked up to the installer takes Nextcloud in the right direction, which is decoupling the file storage from the web stack (as it should be). This is also critical for folks using above means to install Nextcloud, if I want to update to a newer AMI image for example, I have to worry about losing all my data if my container assumes local storage and I haven't taken steps to mitigate that. The database is great, as I can point at an RDS or standalone server for that, but the files people, this should be all about the files!

As it is a few lines of `config.php` values, it should easily fit in the "Storage and Database" section of the installer. Could also start with a dropdown for whatever object storage engines are supported (S3, ceph maybe?) and then provide the relevant field elements for settings specific to that engine. Should also be pretty easy to check permissions/access so folks don't fat-finger their AWS keys and whatnot - "These keys do not work" or "This S3 bucket does not exist or is inaccessible."

What can I do to make this happen, can I buy somebody a drink or write some code or something? :-) Wanting to coordinate with the project up front so whatever I end up doing doesn't go to waste.

**Comment by spacemonkey** [comment]
Bumping one last time to see if anyone else wants to help with this - my current install is using an EFS mount point as a very ugly, poor-performing short term solution but the experience is, to use a technical term created by my son, "doo-doo flakes."

I'm happy on the code side (php, sql, backend) if anyone is interested in helping with the frontend stuff (html, javascript). Any takers?

**Comment by ChristophWurst** [comment]
Although this sounds like a nice feature, the number of requests for this are quite low. Currently there a no plans to implement such a feature, hence I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

Thank you :v:
