### ISSUE TITLE
Send Apptoken via Qr Code

### ISSUE THREAD

**Issue by 8sd** [nextcloud/server#8992]
I recently added some nextcloud apps on my smartphone.
Is it some how possible to send the app token as qr code?
It is very inconvenient to type the token.

**Comment by BornToBeRoot** [comment]
JUst had the same idea ^^ scan your monitor with the nextcloud & Talk app to log in. No one wants to type this long passwords...

Something like the initial WhatsApp Web setup would be great...

**Comment by GoetheG** [comment]
This idea never occured to me. Yes. Inalso find this very interesting.

**Comment by MorrisJobke** [comment]
cc @ChristophWurst didn't you wanted to look into something like this? Or was it @rullzer ?

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/server/issues/429.

**Comment by Wikinaut** [comment]
@ChristophWurst Question:is this now implemented? I **cannot** find a QR code when creating a new App token. However, using the nc://login/user=.....syntax I found elsewhere, I can generate a QR which connects and login my Android Nextcloud app.

**Comment by kesselb** [comment]
See #429. Coming to you with nextcloud 16.

**Comment by Wikinaut** [comment]
@kesselb I was puzzled because #429 was closed, but is apparently not implemented in the current version (I do see the milestone marker).
