### ISSUE TITLE
Data folder log file name

### ISSUE THREAD

**Issue by dIELEKTRIc** [nextcloud/server#8997]
### Steps to reproduce
1. Install Nextcloud Windows client app 2.3.3
2. Connect to server and leave defaults on sync setting
3. Open data folder (C:/Users/<user>/Nextcloud)
4. Show hidden files
5. See ".owncloudsync.log" in root of the data folder

### Expected behaviour
.nextcloudsync.log

### Actual behaviour
.owncloudsync.log

**Comment by Orbital-Bit** [comment]
this is a client issue, should probably be opened in / moved to that repo.

**Comment by blizzz** [comment]
Please open it in the [client tracker](https://github.com/nextcloud/client/issues), though perhaps it won't be changed for backwards compatibility.
