### ISSUE TITLE
Hash character in URL breaks SSL

### ISSUE THREAD

**Issue by doitux** [nextcloud/server#8998]
### Steps to reproduce
1. Start with a default NC URL and login (URL https://mycloud.mydomain.de/index.php/apps/files/  <-- SSL OK)
2. Select News App (URL https://mycloud.mydomain.de/index.php/apps/news/ <-- SSL OK)
3. After loading the news APP the URL changes to: https://mycloud.mydomain.de/index.php/apps/news/#/items <-- SSL broken!

It looks like the hash character in the URL breaks the SSL

The certificate is an let's encrypt one.

## Server configuration detail

**Operating system:** FreeBSD 10.3-RELEASE-p17 hostBSD 10.3-RELEASE-p17 #6: Mon Mar 13 00:47:05 CET 2017     root@fbsd10clone1.han-solo.net:/usr/obj/usr/src/sys/DMRKERNEL amd64

**Webserver:** Apache/2.4.25 (FreeBSD) OpenSSL/1.0.2k mod_fcgid/2.3.9 (cgi-fcgi)

**Database:** mysql 5.6.35

**PHP version:** 7.0.16
Modules loaded: Core, date, libxml, pcre, Reflection, SPL, hash, session, cgi-fcgi, standard, apcu, calendar, ctype, curl, dom, fileinfo, filter, ftp, gd, gettext, mysqlnd, iconv, intl, imagick, imap, json, mbstring, mcrypt, mysqli, openssl, PDO, posix, SimpleXML, sqlite3, tokenizer, xml, xmlwriter, zip, zlib, pdo_mysql, pdo_sqlite, Phar, soap, xmlreader, xsl, ionCube Loader, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.2
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - news: 12.0.1
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - activity
 - admin_audit
 - encryption
 - files_external
 - gallery
 - ojsxc
 - phonetrack
 - theming
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "mycloud.mydomain.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/mycloud.mydomain.de",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mysql.utf8mb4": true,
    "loglevel": 0,
    "memcache.local": "\\OC\\Memcache\\APCu"
}
```

**Comment by MorrisJobke** [comment]
> After loading the news APP the URL changes to: https://mycloud.mydomain.de/index.php/apps/news/#/items <-- SSL broken!

This could not be the case. This is a different layer and thus could not affect the SSL itself. There needs to be a different problem in your setup. As we have tens of thousands of instances running Nextcloud out there and nearly all of them run via HTTTPS it's most likely not related to Nextcloud itself.

Best would be to describe the problem in the forums, as there are many people with experience regarding different kind of setups.

Thanks
Morris
