### ISSUE TITLE
White on white icons on app page in FireFox

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#900]
The filter magic introduced in https://github.com/nextcloud/server/pull/834 does not work on FireFox

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/45821/17732874/3916b4e0-6474-11e6-9391-cb53a1a4e93f.png)

FF:
![ff](https://cloud.githubusercontent.com/assets/45821/17732882/3d123844-6474-11e6-956f-55b320aa68bd.png)

Since it is backported to stable10 (https://github.com/nextcloud/server/issues/897) we should fix this ASAP!

@raghunayyar @MorrisJobke @jancborchardt

**Comment by rullzer** [comment]
Ok step closer... now it looks like 
![ff2](https://cloud.githubusercontent.com/assets/45821/17734116/7790381c-647a-11e6-8403-6d422d96a683.png)

**Comment by rullzer** [comment]
Ah apparently it is failing because the icons don't have a viewbox defined.

**Comment by rullzer** [comment]
ah no... browsers...

**Comment by LukasReschke** [comment]
Can you also test with IE and Edge?

**Comment by MorrisJobke** [comment]
> Can you also test with IE and Edge?

I will do so

**Comment by MorrisJobke** [comment]
- Edge all icons look good, except the "default encryption app" one - there the icon is not properly centered
- IE 10 - the app management only shows the first app and no other ones (but also without any icon or space for that icon)

**Comment by MorrisJobke** [comment]
Fixed and backported to stable10
