### ISSUE TITLE
Admin settings restructuring

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#9003]
Right now we have 3 pages in the admin settings that contain somehow identical content. To make them more obvious I propose we do the following restructuring:

- Introduce Overview page that will give administrators a quick view of how the state of their instance is. If there is anything wrong from a configuration point, they can immediately see it there. It should include:
	- System checks
	- Update check

- Merge additional settings into basic settings 
	- Move cron settings to the server settings (there is no need to have it on the front page since is most likely only made once) Anyhow we should have a status check on the overview page to show if something is wrong with the background jobs.
	- Move additional settings (caldav, file handling, email server) to the basic settings section (extension of #4600)

- Show additional settings just for apps that use legacy settings and don't provide their own section

Feedback and further ideas are welcome @nextcloud/designers @jancborchardt

**Comment by rullzer** [comment]
Sounds good to me!

**Comment by skjnldsv** [comment]
Agreed with above! :)

**Comment by jancborchardt** [comment]
@juliushaertl great stuff, yes! :)

**Comment by GoetheG** [comment]
Definitely a good idea in order to make Nextcloud easier to use and more like Slack.

**Comment by jancborchardt** [comment]
cc @karlitschek for info
