### ISSUE TITLE
Nextcloud 12.0.6 Design issue when uploading file

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/server#9007]
### Steps to reproduce
1. Change the color in the theming app to FFFFFF
2. Upload a (large) file

### Expected behaviour
The text should be readable

### Actual behaviour
![image](https://user-images.githubusercontent.com/16019165/38013349-292fec16-3265-11e8-92df-70bb1abafa84.png)

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 12.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from OwnCloud

**Where did you install Nextcloud from:** nextcloud.com / zip-file

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming

**Comment by juliushaertl** [comment]
I can reproduce on 12. It is fixed on 13/master.

**Comment by BornToBeRoot** [comment]
Yeah the text is fixed in 13.0.1, but now you don't see a progress with color `#FFFFFF`. Maybe make it grey, like the buttons?!

![image](https://user-images.githubusercontent.com/16019165/38928299-a7b64a86-4308-11e8-94ba-7613b9619c3a.png)

**Comment by skjnldsv** [comment]
Fixed already
