### ISSUE TITLE
Nextcloud move folder - bad folder sorting when use external storage

### ISSUE THREAD

**Issue by tomtomas99911** [nextcloud/server#9011]
When I want to move folder to another and I want to choose directory I see that list of target directories is not sorted alphabeticly...

Screen: http://tinypic.com/r/152ks4k/9

Any advice please?

### Steps to reproduce
1. Use local storage as external storage
2. Try to move folder
3. You will se bad sorted folders

### Expected behaviour
Alphabetical sorted folders

### Actual behaviour
Strange sorted folders

### Server configuration

**Operating system**:
Debian 9
**Web server:**
Apache2
**Database:**
mysql
**PHP version:**
PHP 7
**Nextcloud version:** (see Nextcloud admin page)
13

**Comment by MorrisJobke** [comment]
Related: #8820

**Comment by MorrisJobke** [comment]
We improved the file picker to be sortable as well. Thus closing for now.
