### ISSUE TITLE
Add option to disable audio player for shared files.

### ISSUE THREAD

**Issue by n00bundercover** [nextcloud/server#9026]
Nextcloud 13 offers an audio player by default, which is great! However, it would be nice to have an option to disable it for shared files, feg. when there is another app offering similar functionality, like the Music app (https://github.com/owncloud/music/issues/630).

**Comment by MorrisJobke** [comment]
cc @icewind1991 @skjnldsv Looks like something similar to the video player app. We include it automatically as a native HTML element.

This is the code we are talking about:

https://github.com/nextcloud/server/blob/83873e3da1535e02b3eac72e212f7ba0e251b7b9/apps/files_sharing/templates/public.php#L38-L44

**Comment by skjnldsv** [comment]
I'm not convinced. Why would someone want to disable it?
If someone is authorized to download it, he/she should be able to preview it directly in the browser?

@n00bundercover can you provide a use case in favor of disabling this player?

**Comment by skjnldsv** [comment]
@MorrisJobke shouldn't this be done on the 'better' app then?

**Comment by MorrisJobke** [comment]
> @MorrisJobke shouldn't this be done on the 'better' app then?

but it still contains then the code of the server which is not needed to be also included.

**Comment by n00bundercover** [comment]
> I don't know, it feel strange to add an option for a feature another app is providing :)

No, to be clear: The option would be to disable the nextcloud in-built player! Not the 3rd party one!
Imo, this would fit in nicely in the admin settings for sharing files.

If / how the app developer adds support to disable a feature of his app is another question.

**Comment by skjnldsv** [comment]
@n00bundercover Yes, I understood properly :)
But the only use for someone to disable the built int player would be to have the other player.
So my vision of it would be to leave the third party app handle the suppression of our current player.

**Comment by n00bundercover** [comment]
@skjnldsv 

> But the only use for someone to disable the built int player would be to have the other player.

This is just the reason it would be a nice feature in my case. I cloud come up with some other possible issues for audio and video preview and why you might want to have the option to disable it:

There might be a bug in later versions of a preview.

You have a rather big installation and offer free accounts. You are afraid of your cloud being used as public video streaming service for illegal material.

Or you have a small private cloud for friends and family, and your server upload rate might not be able to handle hq video streams, so you rather not have your users try, but download files instead.
(Those reasons apply to videos more than to audio, but I am just coming up with them right now :-) )

But in the end, in my case, the current situation is just a small, tiny annoyance to me, and really not that big of an issue. I could _imagine_ other reasons why you would want to disable file preview features like audio and video player in general, but that might just as well not be the case!

**Comment by skjnldsv** [comment]
@jancborchardt @MorrisJobke 
I'll go with whatever you guys decide! :)

**Comment by jancborchardt** [comment]
This should not be done via a setting of course, but automatically, if at all.

When you have the "better" app enabled, it should overwrite the built-in player wherever it can. (Needs to be don either in the "better" app, or in the core app part?)

**Comment by Rello** [comment]
Hello, regarding the Audio Player: we removed the previous used 360-Player because in our opinion, as much stock-features as possible is best going forward.

Audio Player will not mess with the newly integrated HTML5 player introduced by NC.
Only thing we add is the ID3 Metadata below the cover if the title was indexed with AP.

**Comment by MorrisJobke** [comment]
Okay - so this works as it should. Let's close the ticket then.
