### ISSUE TITLE
How to hide index.php in URI?

### ISSUE THREAD

**Issue by ky0ncheng** [nextcloud/server#9027]
https://www.google.com/search?newwindow=1&safe=off&ei=xuy8WqK-LYf7vASOjb_ICA&q=nextcloud+index.php+remove+nginx&oq=next&gs_l=psy-ab.3.1.35i39k1l2j0i67k1l2j0i131k1l2j0l4.1308694.1309400.0.1311101.4.4.0.0.0.0.115.288.2j1.3.0....0...1c.1.64.psy-ab..1.3.285....0.DcQ1dQAEW8w

The result in google search no one can works.

I use nginx, https://github.com/nextcloud/docker/issues/126

Official doc is not work too.

Thanks for your answer.

**Comment by tflidd** [comment]
If I remember correctly, it was said to work with the current configuration example in the docs. If it is about the created links, then check your `config/config.php` file if the settings are complete:

```
'overwrite.cli.url' => 'https://example.org',
'htaccess.RewriteBase' => '/',
```

I'm not sure if that is enough. Possible that we need to add some more stuff to the documentation....

**Comment by tflidd** [comment]
Let's stick to this topic where there was already some activity:
https://github.com/nextcloud/server/issues/8971
