### ISSUE TITLE
Share API: create federated share, remove it, but it remains accessible via API

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#9028]
I found this via our automated tests on android, using share API on master branch:
(all handled via android-library calls)
- upload a file 
- create federated share from test@localhost/nc to admin@localhost/nc13 with no password
- remove file
- get shares
-> see created share, but directs to "/" instead of previous file.

Screenshot of (via android library) created & shared file:

![screenshot_20180329_165452](https://user-images.githubusercontent.com/5836855/38096188-8e3dd448-3372-11e8-8339-90c5d645097a.png)

Showing result of share API:
![screenshot_20180329_165630](https://user-images.githubusercontent.com/5836855/38096187-8e1d3dd2-3372-11e8-82cb-a66e17e09d8c.png)

"Shared with others" on web UI:
![image](https://user-images.githubusercontent.com/5836855/38096248-b5e406fc-3372-11e8-81b7-5a61e99b948c.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing

**Comment by rullzer** [comment]
who removes the file @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
The test case with the same credentials via android library.

**Comment by MorrisJobke** [comment]
> The test case with the same credentials via android library.

I guess he meant if this was removed by the owner or a different person ;)

**Comment by tobiasKaminsky** [comment]
All is done by the same user:
- upload a file 
- create federated share from test@localhost/nc to admin@localhost/nc13 with no password
- remove file
- get shares

**Comment by rullzer** [comment]
Fix in #9070

**Comment by tobiasKaminsky** [comment]
Working :+1:
