### ISSUE TITLE
Richdocuments has some question

### ISSUE THREAD

**Issue by HandsomeBoby** [nextcloud/server#9033]
### Steps to reproduce
1.installation Richdocuments
2.Do not configure the richdocuments server 
![image](https://user-images.githubusercontent.com/19202505/38121300-06f738a0-3401-11e8-987d-c6b636c69d9a.png)
3.When creating odt file is not visible, refresh the page, this file will appear in the file list
![image](https://user-images.githubusercontent.com/19202505/38121334-31b5b81e-3401-11e8-9b3c-7b3b4ba50a5f.png)
file does not exist
![image](https://user-images.githubusercontent.com/19202505/38121391-6a37de1a-3401-11e8-9686-8665b6aec968.png)
loading,this file will appear in the file list
![image](https://user-images.githubusercontent.com/19202505/38121419-8f786c76-3401-11e8-83aa-b780c8c45870.png)

### Expected behaviour
Tell us what should happen
After the creation of the file is visible, do not need to refresh
### Actual behaviour
Tell us what happens instead
After refreshing, the file is visible
### Server configuration

**Operating system**:Nextcloud 13.

**Web server:**Apache2

**Database:***MariaDB

**PHP version:**PHP 7.0.22-0ubuntu0.16.04.1

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**update

**Where did you install Nextcloud from:**github

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by onny** [comment]
Doesn't this bug report belong to the richdocuments app? I understand your point that Nextcloud doesn't update the files list if something has changed in the background but in this particular case the third party app has to fix this.
For example, I'm using the Onlyoffice Nextcloud extension and I can see the file appearing exactly after creating it.

**Comment by blizzz** [comment]
I guess richdocuments shouldn't try to start when no collabora online server is given. Please reopen in [richdocuments app](https://github.com/nextcloud/richdocuments/issues).
