### ISSUE TITLE
[QUESTION] Is Nextcloud going to support Phoenix

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#9035]
I came across this project on Owncloud:

https://github.com/owncloud/phoenix

I liked the design but was wondering if Nextcloud was going to be supporting this. I am not sure if there is any divergence from the Owncloud project.

**Comment by MorrisJobke** [comment]
It should™ work as far as it uses the WebDAV and OCS apis. the only difference is that they introduced a new way to handle authentication.  But as this project is in a very early stage we will not (yet) put any effort into it to support it. Also it would remove many features from Nextcloud itself as they are not present like that in ownCloud (some sharing mechanisms, notifications, some file filters, other apps than "files" - just to name some).

Maybe we will have a look at this later, but for now it's not on the roadmap.
