### ISSUE TITLE
Deny access if weak password

### ISSUE THREAD

**Issue by FathiBenNasr** [nextcloud/server#9037]
Hello,

I am new to nextcloud and have just installed v13 with ldap/AD backend auth. I would like nextcloud to deny user access if provided password is weak even before checking it agaisnt AD for correctness so to force users to update their passords with a good one if they want to use this new system (nextcloud).

TIA

**Comment by c0fe** [comment]
@FathiBenNasr If you login into as the admin and go to Settings --> Security you will see you can setup a password policy.

**Comment by FathiBenNasr** [comment]
I think password policy is to check password quality when setting new passwords, either local passwords or (maybe) those of other backends like AD/LDAP.
What I would like is to deny access for valid users if supplied passwords are weak before checking if the password is correct and this is for when they are not enforced by AD/LDAP backends to setup strong passwords.

**Comment by tflidd** [comment]
You can perhaps fork the password-policy-app and tell it to check the passwords during login.

It would be better to check the password policies in your LDAP backend when people create their password. As a general app it is not very handy to see that your password is not good enough, then you need to change it in a different backend and do some sort of trial and error until your password is good enough.

**Comment by MorrisJobke** [comment]
> It would be better to check the password policies in your LDAP backend when people create their password. As a general app it is not very handy to see that your password is not good enough, then you need to change it in a different backend and do some sort of trial and error until your password is good enough.

Yes - I also see this as a problem of the user backend and it should not be prompted during login. Maybe it could be a separate app like the password policy, but not during creation, but during the check. On the other side this is only valid for user backends that actually support updating the password. For link shares with password it would not make sense as well as for LDAP setups that don't allow nextcloud to update the password. I will close this ticket here, as this should be implemented as a separate app and not inside the server itself. The server provides already the needed hook (postLogin should be the name) to accomplish this.
