### ISSUE TITLE
[FATAL ERROR] Webdav Error

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#9038]
### Steps to reproduce
1. Setup Nextcloud Desktop on Windows 10
2. Place files into shared folder

### Expected behaviour
Tell us what should happen
No error
### Actual behaviour
Tell us what happens instead
Error occurs:

`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params ["files\/93038fb9f1be0b9ad3f4883c845a80e9", 1, 1522364815, "files\/93038fb9f1be0b9ad3f4883c845a80e9"]: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction`
### Server configuration

**Operating system**:
Server: Ubuntu 16.04
Desktop: Windows 10
**Web server:**
NGiNX 1.10
**Database:**
MariaDB 10.2 (MariaDB Repo)
**PHP version:**
PHP 7.2
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh INstall
**Where did you install Nextcloud from:**
Zip
**Nextcloud Logs:**
https://paste.ubuntu.com/p/nXR4knCHjb/

**Comment by MorrisJobke** [comment]
Duplicate of #6899 and #6187
