### ISSUE TITLE
need folder information enhacement

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#9041]
we need more info, like files numbers, subfolders numbers ...
![folderinfo1](https://user-images.githubusercontent.com/8655165/38157221-14e57ca4-3485-11e8-8efc-1de34efece81.JPG)

After uploading a folders +files and subfolders, how do you want to be sure you did successfully upload via a browser ( see bug https://github.com/nextcloud/server/issues/9040 )

**Comment by GoetheG** [comment]
Ounyes, if you guys would add that, that would just be great. Thank you in advance, Nextcloud developer team!

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
