### ISSUE TITLE
Use external storage CPU usage high

### ISSUE THREAD

**Issue by StarKfeirchris** [nextcloud/server#9042]
**CPU**: Intel Core i3-8100

**Operating system**: CentOS 7.4

**Web server:** nginx 1.12.2

**Database:** MariaDB 10.2.13

**PHP version:** 7.2.2

**Nextcloud version:** (see Nextcloud admin page) 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** yes, version 13.0.0

My server has samba & nextcloud installed at the same time, same place
I use samba with external storage for nextcloud
However, 100% CPU usage occurs when upload/download files through the nextcloud web page.
Later, when trying to use SFTP on external storage, the same situation occurs.
There have also been attempts to downgrade the kernel, or the upgrade has not improved.
The current Kernel version is 4.15.10, thanks!

**Comment by Hadessohn** [comment]
I have the same problem and I figured out that the ssh tunnel to my database server generates there also a high cpu load.

I found repeating queries in the sql log:
48 Query     SELECT * FROM oc_filecache WHERE name = '__groupfolders' AND path = '__groupfolders'
48 Query     SELECT * FROM oc_filecache WHERE fileid = NULL
48 Query     SELECT * FROM oc_filecache WHERE fileid = NULL
48 Query     SELECT * FROM oc_locks_w2g2 WHERE file_id = NULL

I hope this is helpful, but I also have a lot of plugins in usage.

**Comment by bluewhitetobi** [comment]
Hello, i have the same problem. 
When i include the external samba storage in my personal settings, the cpu usage get high.

**Comment by dohlin** [comment]
Can confirm I'm seeing the exact same issue.  Ubuntu 16.04, NC 13.0.2, External Storage 1.4....if I disable the external storage app and monitor via "top", CPU usage goes down to normal...but the moment I re-enabled it my 'mysqld' process absolutely starts shredding whatever is left of my CPU - anywhere between 60% to >100% (dual core).  Something is not right here and I'm not certain when it started happening but I'm thinking it's fairly recent.

**Comment by Hadessohn** [comment]
I also had W2G2 installed and I can confirm that after I disabled the app I can use external storage without the CPU having a high load.
Thanks you @dohlin for discovering this.

**Comment by dohlin** [comment]
@Hadessohn Glad it wasn't just me and that it worked for you!  Also, thanks for creating that issue report as well.  I updated it with the version info so hopefully that will help them narrow down the likely source of the issue.

**Comment by StarKfeirchris** [comment]
@dohlin Thanks for your test, it seems that my problem is different from yours,  
because my W2G2 default not enable, my problem looks more like php-fpm.
![](https://i.imgur.com/q10OBB5.png)

**Comment by dohlin** [comment]
Interesting...ok yeah looks like similar results but different root causes.  Sorry I couldn't help more!

**Comment by Javinator9889** [comment]
Actually facing this issue on Nextcloud 15.0.1 with PostgreSQL and PHP-7.3FPM on SFTP external storage
