### ISSUE TITLE
All uploaded files on S3 external storage are copied to data/(user)/files_versions

### ISSUE THREAD

**Issue by berho** [nextcloud/server#9044]
### Steps to reproduce
1. Add S3 external storage (region eu-central-1)
2. copy files to external storage
3. take a look at  data/(user)/files_versions and on the bill !!!!

### Expected behaviour
Only changed Files should be versioned

### Actual behaviour
all files uploaded are downloaded to files_versions directory

## Server configuration detail

**Operating system:** Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 5.5.59

**PHP version:** 7.1.15
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, session, intl, json, mbstring, mcrypt, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, imap, shmop, SimpleXML, soap, pdo_mysql, exif, tidy, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip, mysqli, cgi-fcgi, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** download page

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - apporder: 0.4.1
 - audioplayer: 2.2.5
 - bookmarks: 0.11.0
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - caniupdate: 0.1.2
 - comments: 1.3.0
 - contacts: 2.1.3
 - dav: 1.4.6
 - encryption: 2.0.0
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.2.1
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - end_to_end_encryption
 - files_rightclick
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxxx.yy"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "\/homepages\/19\/d663084385\/htdocs\/CloudData\/skeleton",
    "overwrite.cli.url": "https:\/\/xxxx.yy",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "php",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "maintenance": false,
    "theme": "",
    "loglevel": 1,
    "updater.release.channel": "stable",
    "app.mail.smtp.timeout": 5,
    "app.mail.transport": "php-mail",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** S3

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

**Comment by MorrisJobke** [comment]
cc @schiessle @icewind1991 @rullzer 🙈

**Comment by MorrisJobke** [comment]
> all files uploaded are downloaded to files_versions directory

That is how files_version is currently implemented.

**Comment by berho** [comment]
:flushed: Why double the space (and increase the costs) if not necessary? Very very bad concept :scream_cat:
Copy of file should be done if new version is uploaded!!!

**Comment by rullzer** [comment]
I believe we fixed something here in master @icewind1991 right?

**Comment by icewind1991** [comment]
Yes, I think https://github.com/nextcloud/server/pull/8725 should fix this

**Comment by MorrisJobke** [comment]
That means it is fixed in 13.0.1 and master -> closing

**Comment by MorrisJobke** [comment]
> Nextcloud version: 13.0.1 - 13.0.1.1

🤔 Are you sure it happens with this version or was it a previous one? Because then we need to check again if something was missing.

**Comment by berho** [comment]
You are right! I uploaded with 13.0.0 and then upgraded to 13.0.1. I have tested now to upload files and the files does not appear in the files_versions folder :smiley: 

Thanks! :bouquet:
