### ISSUE TITLE
Protocol "" is unknown

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/server#9046]
The Nextcloud started to give the protocol a error.
I can not upload files from the web interface & client but If I access it with local IP, I can upload files without problems.

![asdas](https://user-images.githubusercontent.com/297968/38163536-e6cda264-34fd-11e8-89eb-eb1e05d5c27a.gif)

I checked SSL and I did not encounter any problems.. What could be the problem?
Thank you.

## Server configuration detail

**Operating system:** Linux 4.13.16-1-pve #1 SMP PVE 4.13.16-43 (Fri, 16 Mar 2018 19:41:43 +0100) x86_64

**Webserver:** Apache/2.4.6 (CentOS) PHP/7.1.16 (apache2handler)

**Database:** mysql 5.6.39

**PHP version:** 7.1.16
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqlnd, PDO, apcu, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apc, igbinary, smbclient, zip, Phar, redis, libsmbclient, Zend OPcache

**Nextcloud version:** 13.0.1 Build:2018-03-30T23:01:25+00:00 b6cb092bc6eb8dc1439d7d68ee5e88d0e15a6dd9 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - admin_audit: 1.3.0
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - files: 1.8.0
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_trashbin: 1.3.0
 - files_videoplayer: 1.2.0
 - gallery: 18.0.0
 - impersonate: 1.0.3
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - provisioning_api: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - activity
 - comments
 - encryption
 - federation
 - files_external
 - files_texteditor
 - files_versions
 - firstrunwizard
 - nextcloud_announcements
 - password_policy
 - serverinfo
 - sharebymail
 - survey_client
 - systemtags
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "debug": true,
    "trusted_domains": [
        "example.com"
    ],
    "htaccess.RewriteBase": "\/",
    "asset-pipeline.enabled": true,
    "auth.bruteforce.protection.enabled": false,
    "default_language": "tr",
    "logtimezone": "UTC",
    "knowledgebaseenabled": false,
    "appstore.experimental.enabled": true,
    "trashbin_retention_obligation": "disabled",
    "versions_retention_obligation": "disabled",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/192.168.1.124",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "loglevel": 0,
    "updater.release.channel": "daily",
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

## Console

If I want to upload a file on Web interface, console log:

> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: ;undefined.
> files:1
> JQMIGRATE: Migrate is installed, version 1.4.0
> jquery-migrate.min.js:2:542
> GETXHR
> https://example.com/core/search/templates/part.results.html
> [HTTP/1.1 200 OK 4ms]
> GETXHR
> https://example.com/ocs/v2.php/apps/notifications/api/v2/notifications
> [HTTP/1.1 200 OK 75ms]
> GETXHR
> https://example.com/index.php/apps/gallery/config
> [HTTP/1.1 200 OK 52ms]
> PROPFINDXHR
> https://example.com/remote.php/webdav/
> [HTTP/1.1 207 Multi-Status 61ms]
> GETXHR
> https://example.com/index.php/apps/files/ajax/getstoragestats.php
> [HTTP/1.1 200 OK 38ms]
> PUTXHR
> https://example.com/remote.php/webdav/background_24.jpg
> [HTTP/1.1 302 Moved Temporarily 4ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 4ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 4ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 6ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 5ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 3ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 9ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 9ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 9ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 8ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 8ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 8ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 8ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 9ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 9ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 11ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 9ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 7ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 12ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 9ms]
> PUTXHR
> https://example.com/@custom
> [HTTP/1.1 302 Moved Temporarily 6ms]
> TypeError: response is undefined[Learn More]
> file-upload.js:981:8
> GETXHR
> https://example.com/index.php/apps/files/ajax/getstoragestats.php
> [HTTP/1.1 200 OK 49ms]

## Proxy

http://192.168.1.124 -> Nextcloud VPS
```
	ProxyPass / http://192.168.1.124/
	ProxyPassReverse / http://192.168.1.124/
```

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
