### ISSUE TITLE
Nextcloud 13.0.1 say Certificate is not valid what i can do ?

### ISSUE THREAD

**Issue by KundrixHD** [nextcloud/server#9047]
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- direct_menu
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [direct_menu] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)

**Comment by stratege1401** [comment]
Hello,

my question will sound trivial, but WHAT certificats ??
The server https certificats, the webinstaller certificats, ... the calendar certificat like in #500 ...

could you be more explicit

**Comment by tflidd** [comment]
Which version of Nextcloud are you using? Since NC 12 this is part of core and the app is no longer needed. Just disable this app or delete it from the apps-folder manually.

**Comment by MorrisJobke** [comment]
> Which version of Nextcloud are you using? Since NC 12 this is part of core and the app is no longer needed. Just disable this app or delete it from the apps-folder manually.

Correct and this is the signature of that app. Please reach out to the app developer to get this fixed, because it seems that there happened something during the signing process of the app. For this app it's not really needed anymore as we integrated this into the server itself.
