### ISSUE TITLE
@ in foldername cause VLC not to access the media when I sync with current nextcloud client for Android

### ISSUE THREAD

**Issue by awolff64** [nextcloud/server#9048]
### Steps to reproduce
1. Install VLC and nextcloud on yor android.
2. Sync some music via nextcloud.
3. Try to play it in VLC - VLC won't find it.
4. Rename the folder user@owncloud.url to to userowncloud.url
5. Try again to play it in VLC - VLC will find it.

### Expected behaviour
VLC should find the new media.

### Actual behaviour
VLC does not find it.

### Server configuration
Default.

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Playstore

**Comment by awolff64** [comment]
Sorry only just seen that this if the server ...

**Comment by MorrisJobke** [comment]
> Rename the folder user@owncloud.url to to userowncloud.url
> Try again to play it in VLC - VLC will find it.

This will not work. Also you need to specify username and password in the URL otherwise Nextcloud will refuse to load the file.

If you have further questions in that regard raise them in the forums as this is the better place to discuss such topics: https://help.nextcloud.com
