### ISSUE TITLE
Cannot cancel sharing in Chrome

### ISSUE THREAD

**Issue by xiaotan828** [nextcloud/server#9049]
Problems showed in gifs
In chrome, I press the tick and it works in one second. But in the next second, it automatically goes back. Both password protect and the link sharing button do not work. In Firefox it is OK currently, but I don't know if anything will be wrong in the future. I can't even change the password. The password of the sharing is the password I used to login in.
![nextcloud](https://user-images.githubusercontent.com/33599274/38170339-e3d116e6-35b5-11e8-99fa-366884c29d83.gif)

second problem is when I try to update the pdfviewer app, it shows update successfully. But when I refresh the page, the version number just goes back and informs me to update again. This problem occurs in any browser.

**Comment by tflidd** [comment]
Can you open the developer console to check for errors. Any 3rd-party apps blocking content? And the server logs if they have important information, and finally the versions you are using.

Can you reproduce the behavior on the demo instances?

**Comment by rullzer** [comment]
Am I correct in assuming this is on version 12?
