### ISSUE TITLE
No mail notification sent when a shared file is downloaded

### ISSUE THREAD

**Issue by dachary** [nextcloud/server#9050]
### Steps to reproduce
1. install [nextCloud 13.0.1 via Docker](https://github.com/nextcloud/docker) (I don't think it is docker specific but that's what I did so, here it is)
2. set the admin user email
3. send a test email from /settings/admin/additional and verify it works
4. set the *sharing notifications via email* in settings/user/additional and ask that notifications are sent as soon as possible
   
![a](https://user-images.githubusercontent.com/433594/38195732-61a6b552-367f-11e8-93dd-7d14dce2b9ad.png)
5. Share **Nextcloud.mp4** via link
6. From another browser use the link to download **Nextcloud.mp4**
7. Check the **Activity** and verify the file has been downloaded
![b](https://user-images.githubusercontent.com/433594/38195841-fdeddc74-367f-11e8-8573-b02e730a5638.png)

### Expected behaviour
A notification email is received to inform the user that the shared file was downloaded

### Actual behaviour
No notification email is received to inform the user that the shared file was downloaded

### Server logs

Here are the server logs when the user downloads the file using the shared link:

<pre>
$ sudo docker-compose logs -f app
...
app_1                    | 172.19.0.2 - - [02/Apr/2018:12:15:25 +0000] "GET /s/ygF7KJoccZgDXeM HTTP/1.1" 200 5017 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
app_1                    | 172.19.0.2 - - [02/Apr/2018:12:15:25 +0000] "GET /cron.php HTTP/1.1" 200 879 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
app_1                    | 172.19.0.2 - - [02/Apr/2018:12:15:28 +0000] "GET /s/ygF7KJoccZgDXeM/download HTTP/1.1" 200 463357 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36"
app_1                    | 172.19.0.2 - - [02/Apr/2018:12:15:31 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 689 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
</pre>

**Comment by tflidd** [comment]
Can you verify on your admin page that the cron jobs run properly?

**Comment by dachary** [comment]
> Can you verify on your admin page that the cron jobs run properly?

The **settings/admin** page shows

![b](https://user-images.githubusercontent.com/433594/38247051-2e38d1da-3744-11e8-87b8-2a03f08fbf49.png)

Which looks good to me but ... maybe not?

**Comment by MorrisJobke** [comment]
> A notification email is received to inform the user that the shared file was downloaded

cc @nickvergessen 

I guess this is provided by the download activity app, right?

**Comment by dachary** [comment]
Is there anything I could do to get more information about what is **not** done? I realize this is a trick question ;-)

**Comment by MorrisJobke** [comment]
@dachary Check out this app: https://github.com/nextcloud/files_downloadactivity https://apps.nextcloud.com/apps/files_downloadactivity

That should solve your problem IMO.

**Comment by dachary** [comment]
@MorrisJobke I'm afraid it does not fix the problem. I'm also unsure why such an app would be needed when the **Activity** app that is installed by default already has a notification set and shows activities when a shared link is downloaded (this is what the message of this bug report shows) ?

After installing the [Activities for shared file downloads](https://github.com/nextcloud/files_downloadactivity) app, the settings of the user are modified as expected:

# Before

![disabled](https://user-images.githubusercontent.com/433594/38865236-7c6a5118-423d-11e8-886b-bacef5855b62.png)

# After

![enabled](https://user-images.githubusercontent.com/433594/38865244-82f32a28-423d-11e8-8c63-8388c0d5adf6.png)

However no email is sent.

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by dachary** [comment]
@MorrisJobke I confirm that this bug report cannot be fixed by the recommended application because [it does not have the same scope](https://github.com/nextcloud/files_downloadactivity/issues/32). Thanks for the creative idea though, much appreciated!

**Comment by nickvergessen** [comment]
@dachary there was a bug with "As soon as possible":
https://github.com/nextcloud/activity/pull/249 + https://github.com/nextcloud/activity/pull/254

So it will be fixed with 13.0.2

**Comment by dachary** [comment]
@nickvergessen thanks for the update. I'm afraid this bug report is with 13.0.1 ... there must be some other problem.

**Comment by nickvergessen** [comment]
Well the difference is that ajax is only done once for each request, I guess your backlog of cron jobs was just too big. You need to visit your NC regularly if you are using ajax cron.

**Comment by dachary** [comment]
@nickvergessen please do not close the bug just yet. I came to the same conclusion you describe. In order to confirm that was the root cause of the problem, I did the following:

* After running manually `php -f cron.php` I reverted to using Ajax
* Downloaded a file using the same link that triggered a notification when running `php -f cron.php`
* Reloaded the nextcloud page manually 20 times to run cron.php 20 times
* Got no notification

Would you mind trying to reproduce the problem as described? I think you will find it is real. If it turns out to not be real, it is at the very least quite confusing and deserves some explaining.

**Comment by dachary** [comment]
please?

**Comment by nickvergessen** [comment]
Well if your cron is not called often enough, that is nothing we can fix. We recommend to switch to system cron or webcron then.

**Comment by dachary** [comment]
> Well if your cron is not called often enough

But it is called often enough, that's my point ;-)

**Comment by nickvergessen** [comment]
Well 
> Reloaded the nextcloud page manually 20 times to run cron.php 20 times
Got no notification

This did not work, because the activity background job is only set to run 15mins after it ran the last time ;)

**Comment by dachary** [comment]
**dang**

**Comment by dachary** [comment]
So... the Ajax cron job should work fine if there is at least one page loaded every minute. Right?

**Comment by nickvergessen** [comment]
I'd guess so, but it depends on your usage, if you create a lot of versions for a lot of different files and move them to the trash all the time it might not be enough.

We always wanted to show the backlog size in the admin settings, so you can see if it grows or shrinks
