### ISSUE TITLE
After upgrade to 13.0.1 getting permission denied using logging app

### ISSUE THREAD

**Issue by whositwhatnow** [nextcloud/server#9051]
When using the logging app in the admin panel, I get a spinning circle and when I look at my apache logs it gives the following error:

[Mon Apr 02 08:45:37 2018] [error] [client ] {"reqId":"Kj0LxKBlNBkMvCtHhAtB","level":3,"time":"2018-04-02T07:45:37-05:00","remoteAddr":"x.x.x.x","user":"admin","app":"PHP","method":"GET","url":
"\\/nextcloud\\/index.php\\/apps\\/logreader\\/get?offset=0&count=50","message":"fopen(\\/var\\/log\\/nextcloud.log): failed to open stream: Permission denied at \\/var\\/www\\/html\\/nextcloud\\/apps\\/logreade
r\\/lib\\/Controller\\/LogController.php#56","userAgent":"Mozilla\\/5.0 (X11; Linux x86_64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/64.0.3282.186 Safari\\/537.36","version":"13.0.1.1"}

the permissions on that file is:

-rw-r--r-- 1 apache apache 6005 Mar 28 21:06 LogController.php

im assuming it needs the execute permission as well, but am not 100% sure.

I did the upgrade via teh command line using occ.

**Comment by MorrisJobke** [comment]
The parent folders need the executable bit set as well for the apache user. Most likely you need to set it for the world permissions for /var and /var/log.

**Comment by francescor** [comment]
world permissions for /var and /var/log, mmh ?

I solved it by moving the log file to a dedicated directory

```
sudo mkdir /var/log/nextcloud
sudo chown www-data.root /var/log/nextcloud
cp /var/log/nextcloud/nextcloud.log /var/log/nextcloud
chown www-data.root /var/log/nextcloud/nextcloud.log
```
then update settings (or just adding the new line) in /var/www/nextcloud/config/config.php to get:
```
<   'logfile' => '/var/log/nextcloud/nextcloud.log',
---
>   'logfile' => '/var/log/nextcloud.log',
```

then reboot
