### ISSUE TITLE
cannot login from weblogin nor cannot SSH in but can enter via webdav

### ISSUE THREAD

**Issue by wayneoutthere** [nextcloud/server#9054]
### Steps to reproduce
1. try to ssh - fail
2.try to go to box login page (with any user) - fail
3. try to logiin via ubuntu nautilus via davs:// and... able to log in

### Expected behaviour
should be able to ssh in and login via regular browser login

### Actual behaviour
see above

### Server configuration

**Operating system**: 
ubuntu 17.10

**Web server:**
nextcloudpi

**Database:**
don't know
**PHP version:**
don't know
**Nextcloud version:** (see Nextcloud admin page)
don't know (can't log in)
**Updated from an older Nextcloud/ownCloud or fresh install:**
no.
**Where did you install Nextcloud from:**
ownyourbits.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local, HDD, WD my passport
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
don't know. don't think so
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by wayneoutthere** [comment]
update: now I cannot enter by webdav either.  It now sends a 'http' service unavailable message :(

**Comment by MorrisJobke** [comment]
This looks more like a setup issue. For ssh we can't do anything as this is completely unrelated software. And the login needs to give you some hints (like wrong password or internal server error). I would say this is better suited to be asked in the forums to resolve the setup problems first: https://help.nextcloud.com
