### ISSUE TITLE
share-internal / calendar-task-note file attached 

### ISSUE THREAD

**Issue by bjarkan** [nextcloud/server#9055]
Not issue, more a request for new functionality.

What if I need to add a file or folder to a task, or a calendar appointment, or any other internal app?

One solution that i think will be valid is a kind-of share for a file. A kind of share that is internal to the same user that created it. So you can copy a link and add it to the note, calendar text, or description in a task, or even in a kanban. 

Clicking that "special share link" will open the specified file, folder or whatever it points to. But without exposing that "share" to any other user, just for internal use, allowing to refer a file or folder in the text.

That could be a very tricky way to attach files to task, calendar, notes, kanban or whatever future functionality implemented.

Could be more fashion, if you could manage them as in email app, with attachments... But this approach is less heavy in terms of usability and processing time when a file is claim to be download.

In my opinion it will be so easy to add to the table a new field, even a boolean one, "private" for example, in the table where all the shared links reside. Adding a check in the part that read the link and give the interface if the link is only possible with the same user that created or just anyone.

This change could be very easy to do. But in terms of usability is several orders of magnitude more useful for final user. In the other hand, just checking true/false before giving an interface to download the file will give the user the privacy of sharing only internal with apps, but not exposing the file to malicious GETs to the webserver.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers (for the UX) @juliushaertl (deck app stuff that does this) @karlitschek (for the vision)

**Comment by jancborchardt** [comment]
Yes, the Deck app does exactly this already. Other apps can simply utilize a filepicker to attach files to other elements like Contacts, Calendar events etc.

Of course as always, there needs to be the need for this (for Deck there was, so it’s in there) and someone who implements it. :) So any contribution is welcome.

**Comment by skjnldsv** [comment]
@juliushaertl so, this is similar to collections, right?

**Comment by juliushaertl** [comment]
Yes, @bjarkan you might want to check out Nextcloud projects https://nextcloud.com/blog/nextcloud-16-allows-you-to-link-resources-to-keep-track-of-your-projects/

Calendars are currently not supported but afaik @georgehrke was already looking into that. :wink:
