### ISSUE TITLE
System address book registered in contacts manager may lead to data leakage

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#9058]
As discovered in the [mail app](https://github.com/nextcloud/mail/issues/848), the dav app registers the system users address book for the contacts manager. If any app queries this manager, all personal and system-wide contacts can be retrieved, even if sharing options are configured to not suggest any other system users.

Ref https://github.com/nextcloud/mail/issues/848#issuecomment-377014982

https://github.com/nextcloud/server/blob/7b4e51dbc71c1112663b65c08b14eed44dcb50a3/lib/private/ContactsManager.php#L41-L54
https://github.com/nextcloud/server/blob/7b4e51dbc71c1112663b65c08b14eed44dcb50a3/apps/dav/lib/CardDAV/ContactsManager.php#L55-L59

cc @rullzer

**Comment by rullzer** [comment]
Right. This fell off my radar.

I think the address book is doing what is was intended to do. You are not sharing files but want to send e-mails and if people have their e-mail address set to be shared within this instance it should show up.

Of course once could argue that if the admin sets sharing to disabled to suggest other users this should be disabled as well.


I guess the quick fix here would be to just not register the system address book if suggestion are disabled.

**Comment by rullzer** [comment]
As discussed with @ChristophWurst 

This is fixed in the mail app now. Apps should use the IContactsStore to obtain contacts. I'll see if disable enumeration as well on the dav
