### ISSUE TITLE
Error exe on database

### ISSUE THREAD

**Issue by IPlayForHer** [nextcloud/server#9065]
**Operating system**:ubuntu 16.04.1

**Web server:**apache2

**Database:**mysql

**PHP version:**php7.0

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**0.12

**Where did you install Nextcloud from:** install php file

![image](https://user-images.githubusercontent.com/21272351/38280733-4fb22c8e-37ea-11e8-98ee-ee6bc24911e6.png)

![image](https://user-images.githubusercontent.com/21272351/38280841-e76c813c-37ea-11e8-8f8b-ab319c7740f7.png)

**Comment by MorrisJobke** [comment]
Looks again like the `Mysql server has gone away` problem we also noticed in #8863.

This time it's:

`ALTER TABLE oc_authtoken CHANGE id id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL`

and


`ALTER TABLE oc_admin_settings CHANGE id id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL`


Let's continue this in #8863
