### ISSUE TITLE
The log  reports the same error on the time!Anybody  helps me? 

### ISSUE THREAD

**Issue by duanego** [nextcloud/server#9067]
**The first error:**
Invalid argument supplied for foreach() at /home/wwwroot/nextcloud/lib/private/L10N/Factory.php#200

**The second error:**
scandir() has been disabled for security reasons at /home/wwwroot/nextcloud/lib/private/L10N/Factory.php#198

The above two errors just be reported by the log again and again with no interrupt!
![image](https://user-images.githubusercontent.com/33107702/38289820-c16272f6-380a-11e8-9bd4-6adfc4902146.png)

**Comment by MorrisJobke** [comment]
This means that `scandir` is blacklisted in the `disable_functions` settings in your php.ini. We need this method to fetch available languages from the available files.

See https://secure.php.net/manual/en/ini.core.php#ini.disable-functions for the PHP documentation for this method. Please adjust it to allow `scandir` to be executed.
