### ISSUE TITLE
Multiple fatal errors in the nextcloud.conf 13 instructions

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/server#9079]
Multiple fatal errors in the nextcloud.conf 13 instructions found at https://www.c-rieger.de/nextcloud-13-installation-guide/

Linux Ubuntu Xenial/Mate, PHP 7.2, NextCloud 13, Nginx version 1.13.6

nginx: [emerg] unknown log format "main" in /etc/nginx/conf.d/nextcloud.conf:18
access_log /var/log/nginx/nextcloud.access.log main;
nginx: configuration file /etc/nginx/nginx.conf test failed

There doesn't appear to be any 'main' subtag on the log command at all, eliminating that clears out the fatal error
access_log /var/log/nginx/nextcloud.access.log

All the mp4 references appear to also be entirely unknown and fatal errors are kicked out on those three entrys, cleared out by commenting those three mp4 lines out.

mp4;
nginx: [emerg] unknown directive "mp4" in /etc/nginx/conf.d/nextcloud.conf:42
nginx: configuration file /etc/nginx/nginx.conf test failed
nginx: [emerg] unknown directive "mp4_buffer_size" in /etc/nginx/conf.d/nextcloud.conf:43

This fatal error doesn't appear to have the proper syntax?
location / {
rewrite ^ /index.php$uri;
}
nginx: [emerg] duplicate location "/" in /etc/nginx/conf.d/nextcloud.conf:37
nginx: configuration file /etc/nginx/nginx.conf test failed

cleared up by providing
location = / {
rewrite ^ /index.php$uri;
}

**Comment by MorrisJobke** [comment]
Please report this to Carsten Rieger: https://www.c-rieger.de/impressum/
