### ISSUE TITLE
Get rid of svg scaling hack for Firefox in the apps management

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#908]
* introduced with #905
* see https://github.com/nextcloud/server/blob/1444c1d3456b1f9b7179d1be2c7496a84bbc8fdd/settings/js/apps.js#L237-L241

cc @rullzer @juliushaertl @Bugsbane @raghunayyar @mar1u5

**Comment by juliushaertl** [comment]
Hmm, bad that we had such a bug :cry: 

I guess we should get rid of the svg filter inversion completely to avoid such side-effects. At first it looked like an easy way to use this, but it wasn't.

My idea would be to add some IconController to core that will just read the svg from the app replace color codes and return a new svg image.(just similar to what is done https://github.com/nextcloud/server/pull/840/files#diff-55c944adbad26e06ef3fc9b2b219f281R275) 
Then we could just go with the default <img>-tag that works everywhere.
What do you think about that?

**Comment by rullzer** [comment]
While that would be the 'easy' solution. Something that we can do client side scales a lot better.

**Comment by rullzer** [comment]
Ok it was the viewBox thing that was missing. This basically made FF (and others) say I don't know how to scale it.

It is fixed now.

**Comment by MorrisJobke** [comment]
> It is fixed now.

In #905
