### ISSUE TITLE
Array to String conversion in QueryBuilder#groupBy (typo in master branch)

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#9080]
### Steps to reproduce
1. Use QueryBuilder#groupBy() with a single array argument

### Expected behaviour
groupBy should work as in previous versions.

### Actual behaviour
Array to string conversion.

### Cause
The cause is a superfluous dollar sign which makes PHP compute a dynamic variable name and interpret the parameter as a string.

See https://github.com/nextcloud/server/commit/afbad7e15ea1dc578d2af171b820d35c34899eb4#diff-9e0e47ec61035c057fd8fbcc51952bdeR816

**Comment by rullzer** [comment]
@marcelklehr thanks for noticing. I'll take care of it.
In the future feel free to open a PR :)

**Comment by marcelklehr** [comment]
@rullzer Thanks for taking care of this. I would've whipped up a pr myself, but tight schedule and all..

Cheers :)
