### ISSUE TITLE
 server replied: Internal Server Error (Could not rename part file to final file)

### ISSUE THREAD

**Issue by killmasta93** [nextcloud/server#9091]
Hi,
I was wondering if someone else has had the same issue?
Currently have Nextcloud 12.03 with NGINX. Recently using the windows application to sync my files. I had to add 

    ``'filelocking.enabled' => false,

but now if i work on a document then save it im getting constant

              `` server replied: Internal Server Error (Could not rename part file to final file)

Thank you

**Comment by MorrisJobke** [comment]
> ``'filelocking.enabled' => false,

Disabling this should not be done. If you run into performance issues, then use a memory cache like redis for this.



> `` server replied: Internal Server Error (Could not rename part file to final file)

Then there should be some logs in the nextcloud.log file inside your data directory.

**Comment by killmasta93** [comment]
Thanks for the reply when you say that this should not be done the file locking? As for the redis could not get a really good tutorial on configuring redis with NGINX most of them are with APACHE

**Comment by MorrisJobke** [comment]
> not get a really good tutorial on configuring redis with NGINX most of them are with APACHE
> I dont remember installing redis

It's basically installing the package like `apt-get install redis-server` and then use the default. This should be all for the small instances.

**Comment by MorrisJobke** [comment]
For setup questions please go to the forums: https://help.nextcloud.com
