### ISSUE TITLE
Up/Download Queue

### ISSUE THREAD

**Issue by PsychotherapistSam** [nextcloud/server#9098]
Hello,
This is just a request.
It would be nice, if you clould add a down / upload queue.

Thanks.

**Comment by tflidd** [comment]
Via web interface, like this app?
https://apps.nextcloud.com/apps/flowupload

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. See the provided app for further details on an upload queue

**Comment by PsychotherapistSam** [comment]
Umm, sorry for no feedback. Should I just open a new ticket?
