### ISSUE TITLE
Versions - Shared Folder - Collabora Online Problem

### ISSUE THREAD

**Issue by ThePatzen** [nextcloud/server#9103]
Hi!

It seems Versions App breaks Groupfolder & Collabora Online.

### Steps to reproduce
1. Create a Group-Folder and share a folder inside this with a user.
2. Open it using Collabora Online as one of the "shared with-users"
3. Try save it

### Expected behaviour
File should get saved

### Actual behaviour
The Document can't get saved.

Error | index | Error: Call to a member function getId() on boolean

If i disable the Versions app everything work's fine!!

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** NGINX

**Database:** MySQL

**PHP version:** 7.0.27

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** From an older one

**Where did you install Nextcloud from:** Source

<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - admin_notifications: 1.0.1
  - apporder: 0.4.1
  - calendar: 1.6.1
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - drawio: 0.8.9
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.5
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - checksum
  - encryption
  - external
  - files_downloadactivity
  - files_external
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.jacoby-gm.at",
            "192.168.199.91",
            "192.168.199.90",
            "185.45.233.54"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.jacoby-gm.at",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauthtype": "PLAIN",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 1,
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Chrome latest

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"0hyLzHyGBmu9rjzCdmIo","level":3,"time":"2018-04-06T09:18:10+00:00","remoteAddr":"172.17.0.2","user":"BEnglisch","app":"index","method":"POST","url":"\/index.php\/apps\/richdocuments\/wopi\/files\/31518_ocwjcwrzsq2e\/contents?access_token=GDRRULr96YXB3InM3QJiO6ceVac52mn5&access_token_ttl=0&permission=edit","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getId() on boolean\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/Hooks.php(61): OCA\\\\Files_Versions\\\\Storage::store('\\\/EDV-Intern\\\/Dok...')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/hook.php(106): OCA\\\\Files_Versions\\\\Hooks::write_hook(Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(611): OC_Hook::emit('OC_Filesystem', 'write', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(653): OC\\\\Files\\\\View->emit_file_hooks_pre(true, '\\\/0C44972C-2C19-...', true)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(64): OC\\\\Files\\\\View->file_put_contents('\\\/0C44972C-2C19-...', Resource id #8)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/richdocuments\\\/lib\\\/Controller\\\/WopiController.php(282): OC\\\\Files\\\\Node\\\\File->putContent(Resource id #8)\\n#6 [internal function]: OCA\\\\Richdocuments\\\\Controller\\\\WopiController->putFile('31518', 'GDRRULr96YXB3In...')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Richdocuments\\\\Controller\\\\WopiController), 'putFile')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Richdocuments\\\\Controller\\\\WopiController), 'putFile')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Richdocumen...', 'putFile', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/apps\\\/richdocum...')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php\",\"Line\":184}","userAgent":"LOOLWSD WOPI Agent 3.1.0","version":"13.0.1.1"}
</details>

Best Regards from austria!
David

**Comment by ThePatzen** [comment]
No comment?^^

**Comment by MorrisJobke** [comment]
Group folders don't support versions yet - see https://github.com/nextcloud/groupfolders/issues/50

Thus closing this as duplicate of https://github.com/nextcloud/groupfolders/issues/50
