### ISSUE TITLE
How to get the Deleted Items (trash bin) to permanantly delete

### ISSUE THREAD

**Issue by whositwhatnow** [nextcloud/server#9110]
Using SMB/Cifs shares for storage, not using the internal files storage (on the nextcloud server).

I want to be able to have files stay deleted once they are deleted.  the documentation 'trashbin_retention_obligation'  options only show to keep files, but i want to have them permanently deleted, we have shadow copies enabled on the smb/cifs share.

**Comment by BornToBeRoot** [comment]
If i understand your issue right, you just have to disable the app "Deleted files".

**Comment by MorrisJobke** [comment]
> If i understand your issue right, you just have to disable the app "Deleted files". Then the files will be deleted and not moved to the "deleted files" folder.

Correct. Disabling the trash bin will delete them permanently.

**Comment by niyeaux** [comment]
Sorry to revive this issue again, but the answer given isn't actually much of an answer. There's no obvious way to "disable the trash bin" in either the GUI or in the config.php settings.

I want to have all deleted files just get permanently deleted without hitting the "Deleted files" trash bin at all. Is this possible?

**Comment by kesselb** [comment]
@niyeaux please visit https://help.nextcloud.com for such questions. Trash bin is developed as app for nextcloud and enabled by default. You can disable the trash bin app in the apps management section.
