### ISSUE TITLE
Improve loginflow text

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#9113]
Currently when using the new login flow for the clients we open a window and directly show:

![aut1](https://user-images.githubusercontent.com/45821/38440102-8acc52c0-39e0-11e8-9a4a-edd21f6438ba.png)

After pressing the 'Grant access' button you login. And then directly you are taken to the redirect page.

All of this feels a bit weird to me.
Also it might scare users as this big grant access warning before they even logged in.

Now just switching the two screens also is weird. Because the users just gets to see a login screen without any context so I would propose:

So what I would propose 3 pages:

1. Explaining you are going to connect 
  * with a button: "Login"
2. The login page to login
3. The grant access page
  * The grant access button that does the redirect with the apptoken

I'm just not sure how to word it all properly.

@tobiasKaminsky @nextcloud/designers @MorrisJobke @nickvergessen @skjnldsv @juliushaertl any suggestions?

**Comment by skjnldsv** [comment]
You see the grant access BEFORE the login?
Indeed, we need to go login-grant-redirect :)

**Comment by rullzer** [comment]
@skjnldsv if you use the android app and it just shows you to login it feels weird I think.

So we need some page that explains what is about to happen I think.

**Comment by skjnldsv** [comment]
Ah okay, I misunderstood!
Yes, we need a simple sentence like "Please login before adding a new device to your account" :)

**Comment by rullzer** [comment]
K let me prepare something

**Comment by jancborchardt** [comment]
I’m not sure if I understand correctly. It is fine that it’s only one step, that’s exactly how it works with Github and Twitter etc. What we need to fix is that super technical user agent string. Instead of that, we should say:
- Nextcloud desktop client
- Nextcloud Android app
- Nextcloud iOS app

**Comment by rullzer** [comment]
The point is that we first ask for permission before the login. This is strange.
