### ISSUE TITLE
Is the app schema still up to date?

### ISSUE THREAD

**Issue by brantje** [nextcloud/server#9126]
Hi,
Recently i've found the info.xml schema at `https://apps.nextcloud.com/schema/apps/info.xsd`.
However, it's reporting the following as invalid:
```
<personal>\OCA\NextNote\Settings\PersonalSettings</personal>
<personal-section>\OCA\NextNote\Settings\PersonalSection</personal-section>
```
The xml parser reports the following:
Element `personal` is not allowed here
Element `personal-section` is not allowed here

But, it works, i get a personal settings section and a personal settings page.
Also i've seen more apps using this.

So my question is, can i use the elements?

**Comment by nickvergessen** [comment]
Remove the leading slashes.

If that doesn't help, please post a link to your full source code.

**Comment by brantje** [comment]
That didn't work. My `info.xml` is [here](https://github.com/brantje/nextnote/blob/master/appinfo/info.xml)

**Comment by nickvergessen** [comment]
You were missing some required items before:
https://github.com/brantje/nextnote/pull/85

Also see https://nextcloudappstore.readthedocs.io/en/latest/developer.html#app-metadata for docs.
