### ISSUE TITLE
How to debug one-way calendar sync issue?

### ISSUE THREAD

**Issue by kramer65** [nextcloud/server#9133]
### Description
I installed Nextcloud on an Ubuntu 16.04 server using the snap (following [these steps](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-16-04)). I then tried syncing to the calendar to both my Ubuntu 18.04 desktop and to my Android phone using DavDroid. The syncing works, but only one way. New calendar items I create in the browser (on the nextcloud server) are synced to both my desktop and my Android phone. But items I create on either my phone or on my desktop are not synced to the nextcloud server. Since the problem is the same from both my desktop and my phone I presume the problem lies in my Nextcloud installation.

I created an issue about this [on help.nextcloud.com here](https://help.nextcloud.com/t/nextcloud-only-syncs-one-way-with-gnome-calendar/29725/2), but the only suggestion I get is to check the logs. The problem is that I have no idea where the nextcloud logs are.  I checked out `snap logs nextcloud`, but that only logs some letsencrypt stuff.

I'll fill in the questions below, but my main questions are; 

1. Does anybody know what the problem might be?
2. If not; where can I find the logs from the snap to debug this?

### Steps to reproduce
1. Install the latest nextcloud with snap on Ubuntu 16.04
2. Try to sync from Ubuntu desktop and from Android phone

### Expected behaviour
I expect the calendar to sync both ways.

### Actual behaviour
The calendar only syncs one way; items are synced from the server to my desktop and phone, but items are NOT synced from  my phone or desktop to the Nextcloud server.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** I guess it uses apache in the snap? Didn't check that though.

**Database:** I guess mysql? Whatever comes with the snap install

**PHP version:** Whatever comes with the snap install

**Nextcloud version:** 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** snap

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** not sure, but I don't think so

**Are you using an external user-backend, if yes which one:** not that I know of, so I guess not.

### Client configuration
**Browser:** Chrome/Firefox

**Operating system:** Ubuntu 18.04 and Android

### Logs
The only log I know how to get are these:
```
$ snap logs -f -n=2000 nextcloud
2018-04-01T16:17:31Z nextcloud.renew-certs[2109]: Cert not yet due for renewal
2018-04-01T16:17:31Z nextcloud.renew-certs[2109]: -------------------------------------------------------------------------------
2018-04-01T16:17:31Z nextcloud.renew-certs[2109]: Processing
2018-04-01T16:17:31Z nextcloud.renew-certs[2109]: /var/snap/nextcloud/current/certs/certbot/config/renewal/cloud.mydomain.nl.conf
2018-04-01T16:17:31Z nextcloud.renew-certs[2109]: -------------------------------------------------------------------------------
2018-04-01T16:17:31Z nextcloud.renew-certs[2109]: The following certs are not due for renewal yet:
2018-04-01T16:17:31Z nextcloud.renew-certs[2109]:   /var/snap/nextcloud/current/certs/certbot/config/live/cloud.mydomain.nl/fullchain.pem (skipped)
2018-04-01T16:17:31Z nextcloud.renew-certs[2109]: No renewals were attempted.
2018-04-01T16:17:31Z nextcloud.renew-certs[2109]: No hooks were run.
```

**Comment by wjwieland** [comment]
You may wish to check the setting on your clients (the phone and laptop)  I recall on my android phone that there is a setting with determines how syncing takes place.  Hope that is helpful.
wjw

**Comment by kramer65** [comment]
Ok, found the issue. Turns out I had two calendars called "Personal". One was synced, the other one wasn't. I was simply adding items in the wrong calendar.

Thanks anyway!
