### ISSUE TITLE
Can not sync files produced by DevonThink program

### ISSUE THREAD

**Issue by jiyosub** [nextcloud/server#9138]
### Steps to reproduce
1. Install DevonThink knowledge management program: https://www.devontechnologies.com/products/devonthink/overview.html
2. Create several files in the program without an extension.
3. Explore the contents of the DevonThink database.  It will create files corresponding to the files in the program without extensions n the 'Files.noindex/*' directory.
4. Try to sync DevonThink database to Nextlcoud

### Expected behaviour
Database should sync

### Actual behaviour
Database files are rejected because of * in path.

### Server configuration

**Operating system**:
Mac
**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Log Output**
``
OCA\DAV\Connector\Sabre\Exception\InvalidPath: File name is a reserved word/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1178: OCA\DAV\Connector\Sabre\Directory->getChild('*')/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 590: Sabre\DAV\Server->createCollection('Freethinker Dri...', Object(Sabre\DAV\MkCol))[internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/var/www/html/remote.php - line 164: require_once('/var/www/html/a...'){main}
``

</details>

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer

**Comment by jiyosub** [comment]
Please note, syncing using webdav in this case.

**Comment by MorrisJobke** [comment]
As there is no report since a while and we can't reproduce the issue I will close this ticket.
