### ISSUE TITLE
Missing hints in code and documentation

### ISSUE THREAD

**Issue by OderDochNicht** [nextcloud/server#9140]
### Steps to reproduce
1. New install of NextCloud
2. Klick on the "Banner" with warnings
3. Klick to the list of security warnings
4. Read warning concerning HSTS: The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the security tips."
5. Klick link "security tips"
6. Try to find the related topic (It's the last one in the list.)
6. Browser search funktion for "HSTS"
7. read article
8. Copy, that you're out of the game if you don't have access to Apache config files. At least what the next cloud documentation tells you.
9. Google for .htaccess and HSTS.

### Expected behaviour
For those who like to install NextCloud on other ressources than a root-server it would be nice to know that it wouldn't be necessary to get into the main config files of apache to improve the security. Googling brings a solution for .htaccess:
Header always add Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"

### Actual behaviour
A warning and an article documentation which, in parts, is not helpful for a group of users.

### Server configuration

**Operating system**:
some Linux
**Web server:**
Apache 2
**Database:**
MySQL/MariaDB 5.5.38
**PHP version:**
7.2.3
**Nextcloud version:** (see Nextcloud admin page)
13.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
zip-file from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
admin
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
n/a
**List of activated apps:**
<details>
<summary>App list</summary>
no additional apps - just clean installation
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
no root server, sorry

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
no root server, sorry
or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

hey, it's just a clean installation. I uploaded the unpacked files via ftp to the rented server. I pointed FireFox to the Address oft he webspace. NextCloud brought up the config-screen for first login, I inserted the credentials and database information. The first I got was the banner with the warnings.

**Comment by MorrisJobke** [comment]
Could I ask you to report this in our documentation repo? https://github.com/nextcloud/documentation/issues

Thanks for the feedback
