### ISSUE TITLE
Fix cursor in empty comment input in Safari 

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#9150]
Followup to #7800

See https://github.com/nextcloud/server/pull/7800#discussion_r178874708

The empty input has a too big cursor in Safari:

![bildschirmfoto 2018-04-03 um 17 47 53](https://user-images.githubusercontent.com/245432/38260459-f13594d4-3767-11e8-825e-62fe2cc8c221.png)

See also this thread https://stackoverflow.com/a/9132362

I could also not figure out how to enforce this without the `display: block;`, `font-size`, `line-height`and `height` all didn't worked out :/

cc @Abijeet

**Comment by Abijeet** [comment]
Hi @MorrisJobke, 

Please find the merge request here - https://github.com/nextcloud/server/pull/9184. I reproduced the issue on BrowserStack - Safari 7.1 and verified that the fix I've made works (at-least there).
