### ISSUE TITLE
Unable to use SCSS for apps which operate on the login screen

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#9154]
I was confused when I locally switched to SCSS for the [Unsplash app](https://apps.nextcloud.com/apps/unsplash) because it stopped working. Seems like we don’t load the ability to use SCSS on the log in page, neither do we load the variables.scss for example.

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
I'm not sure, I thought it was because we can't be sure the server is installed properly and therefore our scss compiler is working. Does that generate any error in the logs?

**Comment by juliushaertl** [comment]
We also use a scss file in the theming app that is loaded on the login screen so it should work fine. We just cannot use it on the install page. @jancborchardt can you push the branch that has the broken behavior?

**Comment by MorrisJobke** [comment]
Duplicate of #9251
