### ISSUE TITLE
[Feature Request] Lengthen Trusted Domain variable to accept new v3.0 Tor Url Lengths

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/server#9155]
[Feature Request] Lengthen Trusted Domain variable to accept new v3.0 Tor Url Lengths

The Onion Router has undergone further security measures and this has also resulted in greatly extending the length of the new v3 nextgen tor .onion address. NextCloud's trusted domain variable size works with the old v2.0 tor .onion addresses for a Nextcloud tor hidden service.
http://asmithti65rvrwev.onion (30 character total length).

However NextCloud does not accept the new v3.0 Tor Url (70 character total length) for the needed Trusted Domain variable
http://tascloud7ndnfnyr7c6jd54wxj5gni5jkmxnfjsfgfoc337bi4szwdyd.onion

In the span of the next 12 months, the majority of all .onion websites will have shifted over to the v3.0 Tor Url length, its important for the developers to enable the v3.0 .onion address length in the Nextcloud's trusted domain variable.

Found on Nextcloud v12.5, Linux Ubuntu/Mint Xenial/Mint 18.3 LTS, PHP 7.2, Mysql,Mariadb

**Comment by MorrisJobke** [comment]
Where is a limit in the length of this setting? This is just a config option inside the `config.php` and there is usually no limit on them. Could you send the error message that disallows this?

I also tried it and it works fine:


![bildschirmfoto 2018-05-31 um 15 09 35](https://user-images.githubusercontent.com/245432/40784040-a849f210-64e4-11e8-9c0d-6d6eb7fdceaf.png)
