### ISSUE TITLE
Details row for left navigation entries

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#9156]
it would be nice to have the option to specify details for a navugation entry. E.g. in the Talk app we would use it to show the last chat message of a conversation etc.

cc @jancborchardt @skjnldsv

**Comment by jancborchardt** [comment]
@nickvergessen you mean app-navigation (the left one), _not_ sidebar (right side), correct?

**Comment by nickvergessen** [comment]
yws

**Comment by skjnldsv** [comment]
@nickvergessen what are we talking about here, what would the 'details' looks like? :)

**Comment by nickvergessen** [comment]
Something like lightgrey text below the current text item.
Similar to WhatsApp, we want to show the last chat message bellow the room name in the talk app.

**Comment by skjnldsv** [comment]
Ah yes, I remember! :)

**Comment by jancborchardt** [comment]
So I agree with this. Visually we should do it much like the app-content-list in Mail or Contacts, where the second-line is for additional info, and the icon is vertically centered with both lines.

**Comment by MorrisJobke** [comment]
Let's move it to 17.

**Comment by nickvergessen** [comment]
Done via vue since some time
