### ISSUE TITLE
IPv6 in mysql address

### ISSUE THREAD

**Issue by genofire** [nextcloud/server#9157]
there could be more then one `:` in it, so `explode` is no solution for it.

```
php > print_r (explode(":","[::1]:3306",2));
Array
(
    [0] => [
    [1] => :1]:3306
)
```

https://github.com/nextcloud/server/blob/01482b32a171bb8529bc8baacbe764107e52e14c/lib/private/DB/ConnectionFactory.php#L198

**Comment by genofire** [comment]
Maybe ` list($portOrSocket, $host) = array_map('strrev',explode(":",strrev($host),2));` is a solution:
```
php > print_r (array_map('strrev',explode(":",strrev("[::1]:3306"),2)));
Array
(
    [0] => 3306
    [1] => [::1]
)
php > print_r (array_map('strrev',explode(":",strrev("unix:/socket"),2)));
Array
(
    [0] => /socket
    [1] => unix
)
```

**Comment by tflidd** [comment]
@nickvergessen

**Comment by genofire** [comment]
@cwiedmann this was the test if it is still possible with my idea of a fix. (and it work also with a path)
```
php > print_r (array_map('strrev',explode(":",strrev("/var/run/postgresq"),2)));
Array
(
    [0] => /var/run/postgresq
)

```

---

Nothing matter it is not possible to use a IPv6-Address for a `dbhost` like `[::1]:3306` i got a error `:1]:3306 is no valid port` - because my mention lines did not split host and port on a correct way.
That what this issue is about.

**Comment by cwiedmann** [comment]
@genofire
Your code is also not working if you omit the port.

Well, splitting  the port from a hostname/ip is easy if you know it's not a path. So there is just the path case. And the manual shows two different example (have to use "localhost:/path" vs. "/path").

**Comment by cwiedmann** [comment]
just an example how you can solve the problem:
```
$host = $this->config->getValue('dbhost', '');
if ((0 === strpos($host, '/')) ||
	(false !== strpos($host, ':/'))) {
	$connectionParams['unix_socket'] = $host;
} else {
	$portOrSocket = parse_url('tcp://' . $host);
	$connectionParams['port'] = (isset($portOrSocket['port'])) ? $portOrSocket['port'] : null;
	$connectionParams['host'] = $portOrSocket['host'];
}
```

**Comment by nickvergessen** [comment]
Can you test this change:
lib/private/DB/ConntectionFactory.php
find:
```php
			if (strpos($host, ':')) {
				// Host variable may carry a port or socket.
				list($host, $portOrSocket) = explode(':', $host, 2);
				if (ctype_digit($portOrSocket)) {
					$connectionParams['port'] = $portOrSocket;
				} else {
					$connectionParams['unix_socket'] = $portOrSocket;
				}
			}
```
replace with:
```php
			$matches = [];
			if (preg_match('/^(.*):([^\]:]+)$/', $host, $matches)) {
				// Host variable carries a port or socket.
				$host = $matches[1];
				if (is_numeric($matches[2])) {
					$connectionParams['port'] = (int) $matches[2];
				} else {
					$connectionParams['unix_socket'] = $matches[2];
				}
			}
```
