### ISSUE TITLE
Individual Home-Directories for Users

### ISSUE THREAD

**Issue by Adrian-Voelker** [nextcloud/server#9160]
### Server configuration

**Operating system**: Debian 9

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 13.0.1

Hello Community,

first of all, thank you for this great piece of software. I love using it. And I'd like to participate making it even better. Not only by programming but also by giving new ideas based on daily business.

When using the "external storage" app an user or an admin can include external folders/storages. But can you include a folder as Root-Directory for a certain user?

So that you don't have to click on the external folder and then copy/paste files, but rather use this external folder as Root and directly save all user files there?

This functionality can help System-Administrators to move new Users to other Servers when the storage is full. If this isn't implemented yet, it could be a nice new feature. 

If it is already possible, then please show me how to do it.

**Comment by MorrisJobke** [comment]
> When using the "external storage" app an user or an admin can include external folders/storages. But can you include a folder as Root-Directory for a certain user?

Set the folder to `/` and it should work.
