### ISSUE TITLE
Tarball shipping lots of hidden files/directories

### ISSUE THREAD

**Issue by javierllorente** [nextcloud/server#9161]
The current tarball (nextcloud-13.0.1.tar.bz) is shipping many hidden files/directories, such as .github or .gitignore.

For more details see https://build.opensuse.org/package/live_build_log/server:php:applications/nextcloud/openSUSE_Leap_42.3/x86_64

IMO, at least .git* files/directories shouldn't be shipped, so that the tarball is cleaner. Currently, packagers cannot delete them themselves due to Nextcloud integrity checks.

Possible fix:
```
find . -name .github -type d -prune -exec rm -r {} \;
for file in .gitkeep .gitignore; do
  find . -type f -name $file -delete
done
```

**Comment by Escubaer** [comment]
Reminds me: Where are the sources for the build script for the tar, so we can fix this?

**Comment by rullzer** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
I just updated it and now the `.gitkeep` and `.gitignore` files are also not shipped anymore. Also the other directories were removed already in the past.

It now looks like that: https://gist.github.com/MorrisJobke/ecd8d3e8fefc2dd47ccddb124e30386e (in the revisions you can see the diff between 13.0.1, daily master today and after the latest changes.
