### ISSUE TITLE
New in Nextcloud changelog display - for admins

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#9163]
Users and admins should have a brief info on what's new in an available Nc release, and the possibility to have a direct link to a Changelog.

* [x] for each new release have a short info (3 bullet points) with the most important changed (@jospoortvliet can you do that when writing a summary?)
* [x] have this available when fetching info from the update server https://github.com/nextcloud/updater_server/pull/116
* [x] Show a "What's new?" label on the admin page when an update is available. On click a popup is shown with that info, and a link to the changelog. #9705
* [ ] ~~A "What's new" section on the personal settings shows the same short info (with version and date) after update. Entries only younger than 3(?) months will be shown there, older ones are expunged. (This section will be also used by https://github.com/nextcloud/server/issues/9165)~~ Show a popup in files app instead, cf. last item in https://github.com/nextcloud/server/issues/9165#issuecomment-395445072

@jancborchardt

**Comment by MorrisJobke** [comment]
> Show a "What's new?" label on the admin page when an update is available. On click a popup is shown with that info, and a link to the changelog.
>  A "What's new" section on the personal settings shows the same short info (with version and date) after update. Entries only younger than 3(?) months will be shown there, older ones are expunged.

I'm unsure if those two should be the same. Admin news and user news are kind of different. A user should not care about "enhanced LDAP performance" or stuff like that.

**Comment by nickvergessen** [comment]
As mentioned in the hackweek, admin and user stuff should be separated.

User "what's new" should also be available for apps. So on an Talk update, we can display:
* You can use the following shortcuts in a call: (a)udio, (v)ideo, (c)hat and (p)articipant list
* You can now chat in mutliple rooms at the same time (using different windows/tabs)

This should not come from our updater server or be hardcoded in the server code.

For admins this might also be interesting, but the admin info should mostly refer to technical stuff, as discussed in the hackweek?

**Comment by blizzz** [comment]
> User "what's new" should also be available for apps. 

https://github.com/nextcloud/server/issues/9165

**Comment by blizzz** [comment]
on a discussion on IRC today,  split messages for users / admins (also relevant for #9165 ) were suggested. Some different (additional) info might be useful for admins, when it effects infrastructure. The provided example was:

```
## Talk

### Admin
 * Improved HTTP2 support
 * STUN server is now included by default

### User
 * You can use the following shortcuts in a call: (a)udio, (v)ideo, (c)hat and (p)articipant list
 * You can now chat in mutliple rooms at the same time (using different windows/tabs)
```

Personally I am not entirely convinced, because if there is a technical issues/desire and the admin is waiting for x or y, she would look up the changelog anyhow, wouldn't she? Also, responisble admin always looks at the changelog and will now have a nice link to click :p the idea really is having something light and tasty for quick consumption. Otherwise there's probably not much interest.

@nextcloud/designers for further opinions?

**Comment by skjnldsv** [comment]
I guess we should aim for simplicity? So I won't mind something like above :)

But if we want to aim for a nice visual display like some websites do with some kind of intro/guide "
> Hey! A lot has change since your last visit, want to know what's new ?

And then an introduction step by step etc etc... Not sure if we have the time nor the volonteer people to do that :)

**Comment by blizzz** [comment]
Since https://github.com/nextcloud/server/issues/9165#issuecomment-392538325 we're going to get separate content targeted for admins and users here as well

**Comment by jancborchardt** [comment]
Regarding the separate content, see my comment at https://github.com/nextcloud/server/issues/9165#issuecomment-393237469

**Comment by juliushaertl** [comment]
One thing that just came to my mind regarding:

> Show a "What's new?" label on the admin page when an update is available. On click a popup is shown with that info, and a link to the changelog.

We probably need the app store to parse the info.xml then for the what's new entry, since we don't have the info.xml file available on the server. The release will only be downloaded if the user clicks the update button.

**Comment by blizzz** [comment]
@MorrisJobke the admin part is essentially done, just a merge away. It is "just" the user part that is missing. I was hoping to get this done, perhaps with bending the freeze a little bit 🙊

**Comment by MorrisJobke** [comment]
> @MorrisJobke the admin part is essentially done , just a merge away. It is "just" the user part that is missing. I was hoping to get this done, perhaps with bending the freeze a little bit 🙊

Moved it out to #10050 - let's close this ticket here then as #9705 is in.
