### ISSUE TITLE
Seperate Audit Log file

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#9166]
Make it possible to write to a seperate audit log file, instead of the nextcloud log

Rough overview of tasks:

* [x] put reusable parts of `\OC\Log\File` to the public namespace (e.g. as trait or abstract class)
* [ ] extend the rotate logic to accept other log files (or also move parts to public space)
* [x] implement an ILogger for admin_audit (perhaps having parts of \OC\Log in public space makes sense, to evaluate).
* [x] add appconfig options for admin_audit to override the log location (and type), defaulting to the main log file location.

**Comment by blizzz** [comment]
Limitation: contents of the custom audit log file won't be visible in Admin → Logging (same behaviour as if using Syslog, e.g.).

**Comment by MorrisJobke** [comment]
Fixed in #9293
