### ISSUE TITLE
Fix NULL users?

### ISSUE THREAD

**Issue by Shinrai** [nextcloud/server#9169]
See pull request #8765 for details.

The pull request was closed without a reference to a fix.

**Comment by ChristophWurst** [comment]
This is the (not yet implemented) fix: https://github.com/nextcloud/server/pull/8765#issuecomment-380752660

**Comment by MorrisJobke** [comment]
> This is the (not yet implemented) fix: #8765 (comment)

Correct we should fix the root and not the symptoms.

**Comment by blizzz** [comment]
Fixed by https://github.com/nextcloud/server/pull/10296
