### ISSUE TITLE
Theming app breaks uploaded SVG logo in Firefox

### ISSUE THREAD

**Issue by Bebef** [nextcloud/server#9173]
When using the theming app to upload a SVG logo, embedded fonts won't work any more in Firefox, IE and Edge; Chrome still works. Copying the svg file to `core/img/logo.svg` instead works as expected.

File used: [bbf.zip](https://github.com/nextcloud/server/files/1906695/bbf.zip)

### Steps to reproduce
1. Go to theming app (index.php/settings/admin/theming)
2. Upload `bbf.svg` as logo
3. Open main page in FF

### Expected behaviour
The SVG file shouldn't be touched

### Actual behaviour
Something happens to the SVG file; the embedded font isn't displayed correctly in FF

### Workaround
Upload the SVG to the server instead and replace `core/img/logo.svg` by hand

### Server configuration

**Operating system**: Ubuntu 16.04.4 LTS

**Web server:** nginx version: nginx/1.10.3 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper

**PHP version:** PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )

**Nextcloud version:** 12.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Manually / Download Nextcloud Server > Download > Archive file for server owners

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.8
  - caniupdate: 0.1.2
  - contacts: 2.1.3
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.9
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - gallery
  - survey_client
  - systemtags
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc0n9lcmdbgw",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.domain"
        ],
        "datadirectory": "\/var\/opt\/nextcloud\/data\/",
        "overwrite.cli.url": "https:\/\/my.domain\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.6.1",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "my.domain",
        "defaultapp": "calendar",
        "updater.release.channel": "production",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 

### Client configuration
**Browser:** Firefox 59.0.2 (64-bit)

**Operating system:** Windows 10

**Comment by blizzz** [comment]
@nextcloud/theming

**Comment by juliushaertl** [comment]
The theming app just delivers the file as it was uploaded. I'd assume this is a browser bug and recommend you to just draw the text as path for the logo. Maybe it is also an issue with the embedded font, which looks like it is only provided in ttf format, so that could also cause some issues with different browsers.

For me the font is not rendered properly in any browser, even if I copy it to the core/img/logo.svg file.
