### ISSUE TITLE
unfortunate notification wording when removing share

### ISSUE THREAD

**Issue by SimJoSt** [nextcloud/server#9180]
On our Nextcloud installation, we have a share for all users, matching the name of the url `cloud.example.com`. It contains all data about the installation and the finances for transparency purposes.
While reordering the files, we removed everyone from that share following the logic from the code below, everybody got an email saying `Admin removed your from cloud.example.com`:

https://github.com/nextcloud/server/blob/da6c2c9da1721de7aa05b15af1356e3511069980/apps/files_sharing/lib/Activity/Providers/Users.php#L95

Many of our users thought their accounts have been deleted or deactivated.

An improvement in wording is desirable. Something like `{actor} removed you from the share named {file} `. Preferably referencing the specific share entity (file or folder) to be more clear.
I know all translations would need to updated as well (we had the problem in German), but I believe it's important to give the users more clarity about whats happening.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers 

IMO this makes sense 👍

**Comment by skjnldsv** [comment]
I agree!  :)

**Comment by juliushaertl** [comment]
Yes :+1:

@SimJoSt Could you create a pull request for the wording change? That would be great.

**Comment by kevgathuku** [comment]
Hello 👋 
Do you mind if I go ahead and submitting a Pull Request to update the wording?
Seems this is still pending 😄
