### ISSUE TITLE
Upgrade from 11.0.5 to 13.0.1 fails on oc_share table

### ISSUE THREAD

**Issue by Air-Global** [nextcloud/server#9183]
### Steps to reproduce
1. Have an existing install on 11.0.5
2. Create a new install 13.0.1
3. Connect the new install to the DB of the 11.0.5 install (or a cloned DB to prevent faults, etc.)
4. execute 'occ upgrade'

### Expected behaviour
Upgrade to be succesful

### Actual behaviour
````
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.3.1
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 1.2.0
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.5.1
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.2.0
Updating <gallery> ...
Updated <gallery> to 18.0.0
Updating <password_policy> ...
Updated <password_policy> to 1.3.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.3.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.3.0
Updating <survey_client> ...
Updated <survey_client> to 1.1.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.2.3
Updating <updatenotification> ...
Updated <updatenotification> to 1.3.0
Updating <federation> ...
Updated <federation> to 1.3.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.1.0
Updating <files> ...
Updated <files> to 1.8.0
Updating <activity> ...
Updated <activity> to 2.6.1
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [>---------------------------]   0%
Updated <dav> to 1.4.6
Updating <files_external> ...
Updated <files_external> to 1.4.1
Updating <files_sharing> ...
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'UPDATE `oc_share` SET `password` = `share_with` WHERE (`share_type` = ?) AND (`share_with` IS NOT NULL)' with params [3]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'password' in 'field list'
Update failed
Maintenance mode is kept active
Reset log level
````

### Server configuration
11.0.5 system:
**Operating system**: CentOS

**Web server:** Apache

**Database:** mysql 5.1.73

**PHP version:** 5.6.35

**Nextcloud version:** 11.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded from lots and lots of versions.

**Where did you install Nextcloud from:** ?

13.0.1 system:
**Operating system**: Docker install (https://hub.docker.com/_/nextcloud/)

**Web server:** Docker install (https://hub.docker.com/_/nextcloud/)

**Database:** MariaDB

**PHP version:** Docker install (https://hub.docker.com/_/nextcloud/)

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Yes, that is the issue

**Where did you install Nextcloud from:** Docker install (https://hub.docker.com/_/nextcloud/)

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

`<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'xxxxxxxxxxx',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://xxxxxxxxxx',
  'dbtype' => 'mysql',
  'version' => '13.0.1.1',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'nextcloud_mariadb.docker.xxxxxxxxx',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxxxxxxxxx',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => true,
);
`
</details>

**Are you using external storage, if yes which one:** NFS

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

**Comment by Christmi** [comment]
Hi,
Do you have now two installations? And each installation has its own database?
Do you remember the database encoding?
Run the installation on a virtual host like vmware?

**Comment by tflidd** [comment]
You can't skip a major release, you have to upgrade your db to NC 12 first.

**Comment by MorrisJobke** [comment]
> Create a new install 13.0.1
> Connect the new install to the DB of the 11.0.5 install (or a cloned DB to prevent faults, etc.)

This is not how upgrades work. You need to also copy the config and apps dirs for example (as well as the data dir). Best is to follow the guide in our documentation. Also from 11 you first need to upgrade to 12 and then to 13.

https://docs.nextcloud.com/server/13/admin_manual/maintenance/upgrade.html
