### ISSUE TITLE
Use https from web installer on a web-hosting server failed

### ISSUE THREAD

**Issue by Sigmun** [nextcloud/server#9187]
### Steps to reproduce
1. install nextcloud 13 from the web install on your favorite web hosting service (ovh for me)
2. add " 'overwriteprotocol' => 'https', " to your config/config.php
3. log in
4. enable any apps (I've tried Calendar, Contact, External storage)

### Expected behaviour
App to be activated

### Actual behaviour
No app activated. I've got the following message each time :
"Connection to server lost" at the top of the screen
"Error: This app can not be enabled because it makes the server unstable" close to the "enable" button

If http is used (comment the overwriteprotocol line in the config.php), everything is working as expected.

### Server configuration

**Operating system**:

**Web server:**
apache

**Database:**
sqlite

**PHP version:**
5.6 but also 7.2

**Nextcloud version:** (see Nextcloud admin page)
12.0.4 / 13.0.0 / 13.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
web installer

**Signing status:**

<details>
<summary>Signing status</summary>
No errors have 
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Only default
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
    <?php
    $CONFIG = array (
      'instanceid' => '...',
      'passwordsalt' => '...',
      'secret' => '...',
      'trusted_domains' => 
      array (
        0 => 'www.exemple.fr',
      ),
      'datadirectory' => '/home/domainedng/www/nextcloud/data',
      'overwriteprotocol' => 'https',
      'overwrite.cli.url' => 'http://www.exemple.fr/nextcloud',
      'dbtype' => 'sqlite3',
      'version' => '13.0.1.1',
      'installed' => true,
      'htaccess.RewriteBase' => '/nextcloud',
      'memcache.local' => '\\OC\\Memcache\\ArrayCache',
      'maintenance' => false,
    'debug' => true,
    );
     
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox
**Operating system:**
CentOS6/macOS 10.13.3

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
