### ISSUE TITLE
VERIMI Identity Service usable for NextCloud

### ISSUE THREAD

**Issue by petrk94** [nextcloud/server#9188]
Hello dear Community,

I want to ask, whether someone already has plans to realize a connection to VERIMI.
VERIMI is a young Identity Service made in Germany and has the target to be a Identity Service for europe and to connect customers with businesses and eGovernment Services. You create one Account and can login with it to another services by selecting which information you want to share with this service.

https://verimi.de/sandbox/html/sdk.html

I hope someone is already working on it and how to integrate it to NextCloud.
Im working currently in a community where we need something like this to make the another services working about one account together and this make it more easier, instead of using LDAP, etc.

Thanks

**Comment by MorrisJobke** [comment]
There is nothing like this on the roadmap. If somebody want to pick this up we are happy to help. It would be best to be realized as an app, like all the other user backends do.
