### ISSUE TITLE
Change own quota as group admin

### ISSUE THREAD

**Issue by Hadessohn** [nextcloud/server#9191]
### Steps to reproduce
1. Create a user
2. Make that user a group admin
3. Go to the users settings as that user
4. Change own quota

### Expected behaviour
Should be able to change quotas of other users, but not the own.

### Actual behaviour
Able to change the own quota.

### Server configuration

**Operating system:** Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-112-generic x86_64)

**Web server:** nginx/1.10.3

**Database:** 10.0.34-MariaDB-0ubuntu0.16.04.1

**PHP version:** PHP 7.0.28-0ubuntu0.16.04.1

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 13.0.0, but not sure if issue was available previously

**Where did you install Nextcloud from:** Web-Installer from nextcloud.com / Upgrade Tool

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.6.1
  - admin_notifications: 1.0.1
  - apporder: 0.4.1
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - checksum: 0.4.0
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - mindmaps: 0.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - passman: 2.1.4
  - password_policy: 1.3.0
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - rainloop: 5.0.6
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - twofactor_u2f: 1.5.1
  - updatenotification: 1.3.0
  - user_usage_report: 1.0.1
  - w2g2: 2.0.5
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - firstrunwizard
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.tkleinert.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.tkleinert.de",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

</details>

**Are you using encryption:** yes

### Client configuration
**Browser:** Google Chrome 65.0.3325.181

**Operating system:** Windows 10 - 1709 (Build 16299.192)

**Comment by skjnldsv** [comment]
It makes sense!

**Comment by skjnldsv** [comment]
Fixed by #8824

**Comment by ajeoc** [comment]
I disagree with the Expected behaviour.
Only the Admin, should be able to change ANY quota.
See #7429
