### ISSUE TITLE
W2G2 update problem

### ISSUE THREAD

**Issue by sbrodriguez** [nextcloud/server#9193]
Hello everybody.

I have updated some plugins and the W2G2 chrased showing the next message:

Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_locks_w2g2` (`file_id` BIGINT UNSIGNED NOT NULL, `locked_by` VARCHAR(255) NOT NULL, `created` DATETIME DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(`file_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created'

Any idea?

regards

**Comment by DekoLP** [comment]
Hey, I have the same problem :/ I hope it get fixed

**Comment by StuartJMackintosh** [comment]
I have what I believe is a related issue with the database during an upgrade.

After clicking on "Update" for the W2G2 app in the apps list, the Nextcloud server reported an error (which I did not capture). Following this, the server switched to upgrade mode and now presents the following message:

```
App update required
These apps will be updated:

    W2G2 (w2g2)

Please make sure that the database, the config folder and the data folder have been backed up before proceeding. 
```

When 'Start Upgrade' is pressed, the following message is displayed:
```

Update to 13.0.0

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP INDEX "primary"': SQLSTATE[42704]: Undefined object: 7 ERROR: index "primary" does not exist

Detailed logs

Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP INDEX "primary"': SQLSTATE[42704]: Undefined object: 7 ERROR: index "primary" does not exist
```

I don't have access to the back-end server today so can't get any logs etc from the docker container.

The server is a demonstrator so it has not caused any operational impact for me but this would be a major issue for anyone experiencing this on a Nextcloud that they rely on as it rendered the server unusable.

**Comment by DekoLP** [comment]
So do we need to wait for the fix?

**Comment by StuartJMackintosh** [comment]
I did find a suggestion [on the forum](https://help.nextcloud.com/t/broken-after-update-to-12-0-5/26300/2) that might help of anyone is stuck:
`sudo -u www-data php occ app:disable w2g2`
I have not tried it myself.

**Comment by DekoLP** [comment]
This will not work with a webspace

**Comment by MorrisJobke** [comment]
Please report this in the W2G2 issue tracker: https://github.com/newroco/W2G2/issues

Thanks
