### ISSUE TITLE
Lazy loading of file list in publicly shared folder broken

### ISSUE THREAD

**Issue by steav** [nextcloud/server#9195]
### Steps to reproduce
1. Share a folder via link containing many single files (20+)
2. View the shared folder via link

### Expected behaviour
All files should be visible, at least after scrolling down.

### Actual behaviour
Only the first x files are shown.
When sorting by name desc., only the last x files are shown.

### Server configuration

**Operating system**:
alpine 3.5

**Web server:**
nginx 1.10

**Database:**
mariadb 10

**PHP version:**
7.0.29

**Nextcloud version:** (see Nextcloud admin page)
13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from NC 10 to 11 to 12 to 13 to 13.0.1

**List of activated apps:**
<details>
<summary> 
activity: 2.6.1
admin_audit: 1.3.0
announcementcenter: 3.2.1
bruteforcesettings: 1.0.3
calendar: 1.6.1
comments: 1.3.0
dav: 1.4.6
deck: 0.3.1
defaultgroup: 0.3.0
federatedfilesharing: 1.3.1
files: 1.8.0
files_markdown: 2.0.4
files_pdfviewer: 1.2.1
files_sharing: 1.5.0
files_texteditor: 2.5.1
files_trashbin: 1.3.0
files_versions: 1.6.0
files_videoplayer: 1.2.0
gallery: 18.0.0
groupfolders: 1.2.0
logreader: 2.0.0
lookup_server_connector: 1.1.0
nextcloud_announcements: 1.2.0
notifications: 2.1.2
oauth2: 1.1.0
onlyoffice: 1.3.0
password_policy: 1.3.0
piwik: 0.3.2
previewgenerator: 1.0.9
provisioning_api: 1.3.0
serverinfo: 1.3.0
sharebymail: 1.3.0
sharerenamer: 1.3
spreed: 3.1.0
twofactor_backupcodes: 1.2.3
updatenotification: 1.3.0
workflowengine: 1.3.0
</summary>
</details>

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 56, Safari 11.1

**Operating system:**
OSX + iOS, same behavior

#### Browser log
No JS errors / warnings.

**Comment by MorrisJobke** [comment]
Also this works totally fine for me in 13.0.4:

![bildschirmfoto 2018-07-05 um 12 07 30](https://user-images.githubusercontent.com/245432/42317234-10fd9186-804c-11e8-9c7f-e42eb06c56b5.png)
