### ISSUE TITLE
Wrong Text on Download Button at Public Shares

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/server#920]
NC 9.0.53

ownCloud or Nextcloud?

![bildschirmfoto vom 2016-08-18 07-26-24](https://cloud.githubusercontent.com/assets/3857906/17763081/807b64dc-6516-11e6-9a32-b90ba8cdd00a.png)

**Comment by LukasReschke** [comment]
In what view? Gallery view?

**Comment by Huster-at-github** [comment]
Yes, gallerie view. In normal view it looks like this:

![bildschirmfoto vom 2016-08-18 19-32-57](https://cloud.githubusercontent.com/assets/3857906/17783930/a7a57a2a-657a-11e6-95dc-6496656af28e.png)


I have enabled Gallery+

**Comment by Huster-at-github** [comment]
Sooooorry: Not Gallery+!!!!!

I have enabled  Gallery 14.5.0

**Comment by rullzer** [comment]
CC: @oparoz

**Comment by MorrisJobke** [comment]
Fixed and backported to stable9 and stable10: https://github.com/nextcloud/gallery/pull/6
