### ISSUE TITLE
Nextcloud installed as snap uses way too much RAM and is extremelly slow

### ISSUE THREAD

**Issue by wUFr** [nextcloud/server#9201]
### Steps to reproduce
1. Install nextcloud through Snap
2. Open web interface or download/upload any files through desktop client

### Expected behaviour
Less RAM usage? Faster loading?

### Actual behaviour
Loading of web interface is sometimes extremelly slow (even up to 20 seconds), mostly on first load. Generating previews of images is super slow too and whole nextcloud uses ALL the ram it has most of the time (10GB atm), which compared to others being able to run it on RasPi and similar low-end hardware seems a bit weird at least.

### Server configuration

**Operating system**: Ubuntu server 16.04.4

**Web server:** Whatever nextcloud snap installs
**Database:** Whatever nextcloud snap installs
**PHP version:** Whatever nextcloud snap installs

**Extra info:** Hyper-V VM with 8 threads assigned from AMD FX-8300, 10GB DDR3 ram, 250GB HDD

**Nextcloud version:** 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install of both Ubuntu and nextcloud

**Where did you install Nextcloud from:** Snap (following this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-16-04)

... i would fill in remaining info, but this occured even after clean install of Nextcloud through snap and im trying to find out, if others have similar issues.

I think i will just reinstall whole VM and do good old manual install of apache, mariaDB and nextcloud itself, becouse it looks like Snap itself is the hardware hog :'(

**Comment by tflidd** [comment]
Did you consider posting it in the snap-repo?
https://github.com/nextcloud/nextcloud-snap/issues

**Comment by wUFr** [comment]
aha, did not notice there is snap repo :D guess i could

**Comment by rullzer** [comment]
Yep please open in https://github.com/nextcloud/nextcloud-snap/issues thnx :)
