### ISSUE TITLE
Nextcloud upgrade to version 13.0.1

### ISSUE THREAD

**Issue by Jannik2017** [nextcloud/server#9204]
Operating System Debian 7
PHP Version 7.0
When i would like to install the upgrade i get an error like this

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table` FROM INFORMATION_SCHEMA . COLUMNS WHERE TABLE_SCHEMA = ? AND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME <> 'utf8') AND TABLE_NAME LIKE 'oc_%'' with params ["nc01"]: SQLSTATE[HY000]: General error: 1030 Got error 28 from storage engine

**Comment by Germano0** [comment]
Disclaimer: I am not a Nextcloud developer
I see that you completely ignored the ticket template you get when you fill a new issue. I think nobody will take care of this ticket

**Comment by MorrisJobke** [comment]
Looks like your disk runs out of space: https://stackoverflow.com/a/13728466

**Comment by Jannik2017** [comment]
no there is enourh free space

**Comment by MorrisJobke** [comment]
> no there is enourh free space

Then check your DB log for more details. If the DB responds with "1030 Got error 28 from storage engine" we can't do much 😢
