### ISSUE TITLE
Rename group display names

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/server#9209]
![image](https://user-images.githubusercontent.com/16019165/38854144-dab6ed08-421f-11e8-8e01-57798fbac595.png)

Add an edit button next to the delete button to rename groups?!

Currently i have to create a new group, add everyone to the group, delete the old one...

**Comment by MorrisJobke** [comment]
Group display names were implemented in #8255 - @nickvergessen it should be possible now to also implement the renaming, right?

**Comment by nickvergessen** [comment]
Well only displaying them. For 14 we should make it possible to store the displayname in the database.

**Comment by violoncelloch** [comment]
something for 15 milestone?

**Comment by DerTomm** [comment]
... or 16 maybe? ;-)

**Comment by redtux** [comment]
What is needed for this to be implemented? It would really be great to be able to rename groups/roles. :+1:

**Comment by violoncelloCH** [comment]
@redtux would you want to help out here?

@nickvergessen are the display names already stored in the database?

**Comment by redtux** [comment]
@violoncelloCH Depends on what needs to be done, as I am not a developer. Is this still related to #8255? (Is renaming possible in OwnCloud, so that I could have a look there?)

**Comment by nickvergessen** [comment]
No, there is currently only one column:
https://github.com/nextcloud/server/blob/master/core/Migrations/Version13000Date20170718121200.php#L253-L261

So the steps would be:
1. Add a migration to add a column to the `oc_groups` table
2. Copy the ID value to the name column
3. Adjust lib/private/Groups/ accordingly

The group object already has a dedicated method which should be used correctly everywhere.

**Comment by marshalleq** [comment]
Just registering my vote for this too.  The original poster actually missed out some things from his steps obviously.  Most importantly the need to copy the files into the new group and delete the old files.  Not a very nice method.

**Comment by putt1ck** [comment]
Is this stalled?

**Comment by nickvergessen** [comment]
Well the backend is already done, it's just missing someone to pick up the task to add it to the frontend

**Comment by tigattack** [comment]
It would be great if this could be added 🙂

**Comment by fenvarien** [comment]
With many schools successfully using Nextcloud, and with more and more schools starting to use it during the pandemic, we really need this feature usable and accessible from the frontend. Otherwise the end of the school year could become quite problematic and a disappointing experience for many teachers who convinced their colleagues and principal to use Nextcloud.

**Comment by b3** [comment]
Is there anyway to financially sponsor the work (paying Nextcloud to implement the frontend access to group renaming)?

**Comment by ArcticFall** [comment]
I would be willing to work on it, because my organization needs this feature.

I was thinking to add an edit button (same as the user edit button)  left of the delete button and open a popover where the new name can be typed. 

But I'm completely new to contributing to nextcloud and am not too farmiliar with Vue. So any pointers would be nice!

**Comment by redtux** [comment]
@ArcticFall Great news, I think that what @nickvergessen wrote in a comment above is still a good starting point. See https://github.com/nextcloud/server/issues/9209#issuecomment-513785890

**Comment by ArcticFall** [comment]
The backend functionality mentioned in https://github.com/centic9/jgit-cookbook/issues/5#issuecomment-51084491 is already implemented. I think only the frontend needs to be altered.

**Comment by ArcticFall** [comment]
I think I found the right places to address this. See 23c6e9494134d1b42a243690b2d794d0753bd4f0 and a6eebf41c29be0a1545a64c1ee84f9f1234cb47a.
But these changes aren't showing in my development instance of nextcloud. Do I need to do something first to see those changes?

**Comment by nickvergessen** [comment]
Make sure you have node14 and npm7 installed and then follow this part of the readme to compile the src folder into the new js files
https://github.com/nextcloud/server#working-with-front-end-code-

**Comment by ArcticFall** [comment]
I figured out the frontend and js stuff and got it working until the point I actually have to make a request to the backend to change it.
But I have not been able to figure out, where to find the API documentation for that or where I would have to implement an endpoint. If anybody could help me out, that would be great. 

I looked at the [OCS](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/index.html) documentation, but the user/group related stuff seems to be undocumented.

**Comment by ArcticFall** [comment]
@nickvergessen could you give me a pointer? I wasn't able to find anything and nobody answered on the forum either...

**Comment by nickvergessen** [comment]
Group and user stuff is in the admin docs
https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/instruction_set_for_groups.html

But also there the rename is missing.

https://github.com/nextcloud/server/blob/master/apps/provisioning_api/appinfo/routes.php#L44

Its a put agains the group endpoint
Parameters are `key=displayname` and `value=THe Input`
https://github.com/nextcloud/server/blob/master/apps/provisioning_api/lib/Controller/GroupsController.php#L269

**Comment by ArcticFall** [comment]
Thanks! I got everything working.
Now just making sure that everything looks good frontend wise and I can make a pull request.

**Comment by kdoteu** [comment]
I'm new to the Nextcloud release cycle. When will this feature propably in the beta or specially in the stable channel?

**Comment by nickvergessen** [comment]
Beta in 2 days, stable in roughly 6 weeks
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
