### ISSUE TITLE
App icons disappear when searching?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#922]
### Steps to reproduce
1. Open the app management
2. Search for "Fe"

### Expected behaviour
Federation app shows **an** icon

### Actual behaviour
Federation app shows **no** icon

### Client configuration
**Browser:** Firefox 48

**Operating system:** Linux Mint 18

**Comment by nickvergessen** [comment]
@MorrisJobke a problem with tonights session?

**Comment by MorrisJobke** [comment]
Let me retry this...

**Comment by MorrisJobke** [comment]
Weird. When scrolling to "Federation" the icon is visible. When searching for "Fe" the icon is still visible, but when searching for "Fed" it is gone:

![bildschirmfoto 2016-08-18 um 10 27 27](https://cloud.githubusercontent.com/assets/245432/17767017/781b330e-652e-11e6-8f56-442a34ee6d81.png)


![bildschirmfoto 2016-08-18 um 10 27 31](https://cloud.githubusercontent.com/assets/245432/17767025/7cb35fae-652e-11e6-8ffe-fdda126e2a10.png)

**Comment by MorrisJobke** [comment]
This is chrome

**Comment by MorrisJobke** [comment]
I just inspected the DOM before the icon disappears and afterwards and it's exactly the same (of the federation app section).

**Comment by MorrisJobke** [comment]
@rullzer any idea what this could have caused?

**Comment by MorrisJobke** [comment]
Happens in chrome only for some icons and in firefox for most of the icons

**Comment by rullzer** [comment]
I think I know why. Let me test this...
