### ISSUE TITLE
ImageMagick error does not say which file it can't read

### ISSUE THREAD

**Issue by joekerna** [nextcloud/server#9221]
### Steps to reproduce
1. Open broken file (I don't know what happened to my PDF files but the encryption module somehow broke them)
2. Log in Browser says 

> ImageMagick says: Failed to read the file

3. nextcloud.log provides information which file it couldn't read

### Expected behaviour
List the actual filename in the browser log

> ImageMagick says: Failed to read the file: **KinoGutschein.pdf**

### Actual behaviour
It doesn't say, which file it could not read

> ImageMagick says: Failed to read the file

### Server configuration

**Operating system**: Windows 10, OSC

**Web server:** Nginx 1.12

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** Nextcloud Website

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```{"reqId":"OxBjG01L8GPZomYmBlFh","level":3,"time":"2018-04-18T10:16:08+02:00","remoteAddr":"89.245.149.18","user":"matthias","app":"core","method":"GET","url":"\/core\/preview.png?file=%2FKinoGutschein.pdf&c=603894dc4e8120a96a779f023e388780&x=32&y=32&forceIcon=0","message":"ImageMagick says: Failed to read the file","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}```
</details>

**Comment by Sanookmakmak** [comment]
Call your updater script with parameter **-vvv**, e.g.

`php occ preview:generate-all -vvv`

**Comment by joekerna** [comment]
I tried it and as expected, it regenerated all previews. But how does that show me, which PDF files it could not read?
Or do I have to pipe its output to a file and then search for error mesages there?

**Comment by MorrisJobke** [comment]
> ImageMagick says: Failed to read the file

I could not find any part of this in our code base. Where is this shown? Could you maybe post a screenshot so we have a reference where it was printed?

**Comment by joekerna** [comment]
![2018-06-28 10_42_16-einstellungen - nextcloud](https://user-images.githubusercontent.com/23077594/42023822-1251e1b2-7ac1-11e8-87e8-32ede876ff4e.png)

[Kühlschrank Gebrauchsanleitung.pdf](https://github.com/nextcloud/server/files/2144457/Kuhlschrank.Gebrauchsanleitung.pdf)

This is the screenshot (probably not very helpful?) and one of the pdf documents that cause the error.

**Comment by MorrisJobke** [comment]
> This is the screenshot (probably not very helpful?) and one of the pdf documents that cause the error.

Could you go to the data directory on your server (or press the "Download logs" button in the three dots menu in the screenshot) and send over the actual log line, because there are even more information about the request for example. ;)

**Comment by MorrisJobke** [comment]
> Could you go to the data directory on your server (or press the "Download logs" button in the three dots menu in the screenshot) and send over the actual log line, because there are even more information about the request for example. ;)

Ah - it was already there:

```json
{
    "reqId": "OxBjG01L8GPZomYmBlFh",
    "level": 3,
    "time": "2018-04-18T10:16:08+02:00",
    "remoteAddr": "89.245.149.18",
    "user": "matthias",
    "app": "core",
    "method": "GET",
    "url": "/core/preview.png?file=%2FKinoGutschein.pdf&c=603894dc4e8120a96a779f023e388780&x=32&y=32&forceIcon=0",
    "message": "ImageMagick says: Failed to read the file",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:59.0) Gecko/20100101 Firefox/59.0",
    "version": "13.0.1.1"
}
```

**Comment by MorrisJobke** [comment]
Fix is in #10036

**Comment by joekerna** [comment]
That was fast. Thanks! I'll give it a try once I can

**Comment by joekerna** [comment]
I have a similar fatal error. Supposivle the filesize of a certain file is wrong. I can't figure out, which file it is. Is this also already fixed?

Thanks...

> Sabre\DAV\Exception\BadRequest: expected filesize 10000000 got 7913472
> /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:  OCA\DAV\Connector\Sabre\File->put(Resource id )
> /var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php - line 39:  OCA\DAV\Connector\Sabre\Directory->createFile('00000035', Resource id )
> /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:  OCA\DAV\Upload\UploadFolder->createFile('00000035', Resource id )
> /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 529:  Sabre\DAV\Server->createFile('uploads/matthia...', Resource id , NULL)
> [internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
> /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)
> /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:  Sabre\Event\EventEmitter->emit('method PUT', Array)
> /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
> /var/www/nextcloud/apps/dav/lib/Server.php - line 287:  Sabre\DAV\Server->exec()
> /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:  OCA\DAV\Server->exec()
> /var/www/nextcloud/remote.php - line 164:  require_once('/var/www/nextcl...')
> {main}

**Comment by MorrisJobke** [comment]
> Sabre\DAV\Exception\BadRequest: expected filesize 10000000 got 7913472

There are already a lot of those issues in here: https://github.com/nextcloud/server/search?q=BadRequest+expected+filesize&type=Issues have a look at them
