### ISSUE TITLE
CTRL + click on file  app navigation opens in the same window

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#9223]
Not sure if that is on porpoise or not, but for me it feels weird.

If I `CTRL + click` on any link, I expect a new tab to be opened, but the navigation of the files app opens the content in the very same window. Same happens for activity and talk; settings app works "correctly".

cc @nextcloud/designers

**Comment by MorrisJobke** [comment]
> If I CTRL + click on any link, I expect a new tab to be opened, but the navigation of the files app opens the content in the very same window. Same happens for activity and talk; settings app works "correctly".

I guess this is because the click is handled via JS 🙈 #ohWonderfulJSWorld

**Comment by nickvergessen** [comment]
```js
			if (ev.ctrlKey) {
				return;
			}
```

helps, but it opens a new tab with the current content, because there is no `a href` set on the links, that's also easy fixable. So I guess fixing is fine?

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Comment by skjnldsv** [comment]
Fixed on 28
