### ISSUE TITLE
Multiple apps sharing the same setting section

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#924]
We have mutliple workflow apps (and may have more in the future).
It would be nice to have a "Workflow" section for their admin settings.

The problem with the current implementation is, they can not use a common section.
We could add it to the workflow engine itself, but then the section is always there, even if no workflow app is enabled.

Now it would be nice when all apps could register the workflow section, but it is only displayed once (basically unique by section id), atm it doesn't look like this is possible.

The other idea would be to hide empty sections, then the section could be provided be the workflow engine (always enabled)

**Comment by nickvergessen** [comment]
@blizzz any input on this?

**Comment by blizzz** [comment]
Two possibilities:

* If there was a "master" workflow app that would be always enabled (or required) it could register the section.
* We create a built-in section, and ensure that it is not shown if not app registered to it.

**Comment by nickvergessen** [comment]
There is the "workflowengine" app always enabled and shipped and required anyways.
But the "hiding when no app is registered" part is important.

**Comment by nickvergessen** [comment]
Fixed via https://github.com/nextcloud/server/pull/995
