### ISSUE TITLE
TLS library problem

### ISSUE THREAD

**Issue by AquaL1te** [nextcloud/server#9249]
### Steps to reproduce
1. Setup email in Settings --> Additional Settings
2. Configure StartTLS
3. Press "Send email"
4. Gives as output: "A problem occurred while sending the email. Please revise your settings. (Error: Unable to connect with TLS encryption)"

```
In the server log it states:
Apr 19 20:22:28 server postfix/smtpd[17679]: connect from client_ip
Apr 19 20:22:28 server postfix/smtpd[17679]: SSL_accept error from client_ip: -1
Apr 19 20:22:28 server postfix/smtpd[17679]: warning: TLS library problem: error:1417D102:SSL routines:tls_process_client_hello:unsupported protocol:../ssl/statem/statem_srvr.c:974:
Apr 19 20:22:28 server postfix/smtpd[17679]: lost connection after STARTTLS from client_ip
Apr 19 20:22:28 server postfix/smtpd[17679]: disconnect from client_ip ehlo=1 starttls=0/1 commands=1/2
```
Both Postfix and Dovecot enforce the use of TLS 1.2, downgrading isn't possible. I suspect that Nextcloud isn't able to handle TLS 1.2.

OS: Raspbian Stretch
Apache: 2.4.25-3+deb9u4
MariaDB: 10.1.23-9+deb9u1
Dovecot: 2.2.27-3+deb9u2
Postfix: 3.1.8-0+deb9u1
PHP: 7.0+49
Nextcloud: 13.0.1

Log from nextcloud.log.
`{"reqId":"WtjeYwoBAAEAADva7gcAAAMA","level":3,"time":"2018-04-19T18:22:28+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"POST","url":"\/settings\/admin\/mailtest","message":"stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version at \/var\/www\/nextcloud\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Transport\/StreamBuffer.php#94","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.181 Safari\/537.36","version":"13.0.1.1"}
`

**Comment by MorrisJobke** [comment]
> Both Postfix and Dovecot enforce the use of TLS 1.2, downgrading isn't possible. I suspect that Nextcloud isn't able to handle TLS 1.2.

We use `stream_socket_enable_crypto()` from PHP and thus it is an issue in the PHP configuration. Could you check that first, because we don't do the crypto part ourselves, but use the implementation that is provided by PHP methods.
