### ISSUE TITLE
Security & setup warnings fails with 2 times the same header

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/server#9250]
### Steps to reproduce
1. put Nextcloud behind reverse proxy
2. configure `X-Frame-Options` at the reverse proxy level
or:
`X-Content-Type-Options`
`X-XSS-Protection `
3. in the response you'll get 2 times the response header `X-Frame-Options`

### Expected behaviour
go to https://scan.nextcloud.com/ or Security & setup warnings and the security test should pass

### Actual behaviour
the test fails

**Comment by MorrisJobke** [comment]
Duplicate of #8207 - we try to document it in https://github.com/nextcloud/documentation/pull/674
