### ISSUE TITLE
Wrong page rendering

### ISSUE THREAD

**Issue by psankar** [nextcloud/server#9252]
I wanted to try nextcloud and so clicked the trial page. While navigating, I got a wrongly rendered page. Attached the image below.

<img width="1422" alt="screen shot 2018-04-20 at 4 35 00 pm" src="https://user-images.githubusercontent.com/353037/39047826-f5fb365a-44b8-11e8-9e01-5ef9e7e93cdc.png">

Instead of rendering the HTML, the html sources are rendered as plain text.

**Comment by MorrisJobke** [comment]
cc @nextcloud/gallery @danxuliu

**Comment by MorrisJobke** [comment]
Unfortunately we can't reproduce this issue. If this is still happening please feel free to reopen.
