### ISSUE TITLE
Internal Server Error following Collabora/CODE installation on NextCloud 13

### ISSUE THREAD

**Issue by tallship** [nextcloud/server#9262]
### Steps to reproduce

Following the documentation here: https://nextcloud.com/collaboraonline/ I installed CODE on the same server of mine as a nextcloud install (latest version - 13.0.1)

### Expected behaviour

When attempting to open an odt file, It is expected that Collabora will open the file in the browser

### Actual behaviour
When I attempt to open an odt file, I get the following error:

Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Here's a screenie of that error:

https://www.screencast.com/t/tC5xSG4Uq8Q

at https://<nextcloud>/index.php/settings/admin/logging, I get the following errors:

<snip>
Error	richdocuments	GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to office.northtech.us port 9980: Connection refused
at https://<nextcloud>/index.php/settings/admin/logging, I get the following errors:

<snip>
Error	richdocuments	GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to nextcloud.mydomain.com port 9980: Connection refused

    /var/www/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 104: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\ConnectException))
    /var/www/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/owncloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)
    /var/www/owncloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
    /var/www/owncloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
    /var/www/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 135: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
    /var/www/owncloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/owncloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
    /var/www/owncloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('https //office....', Array)
    /var/www/owncloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 84: OC\Http\Client\Client->get('https //office....')
    /var/www/owncloud/apps/richdocuments/lib/WOPI/Parser.php - line 41: OCA\Richdocuments\WOPI\DiscoveryManager->get()
    /var/www/owncloud/apps/richdocuments/lib/TokenManager.php - line 133: OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')
    /var/www/owncloud/apps/richdocuments/lib/Controller/DocumentController.php - line 168: OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)
    [internal function] OCA\Richdocuments\Controller\DocumentController->index('32')
    /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
    /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
    /var/www/owncloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
    /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('DocumentControl...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/owncloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/owncloud/lib/base.php - line 998: OC\Route\Router->match('/apps/richdocum...')
    /var/www/owncloud/index.php - line 37: OC handleRequest()
    {main}
</snip>

### Server configuration

Here's my uname output:

Linux hammer 4.4.0 #1 SMP Mon Jan 11 22:25:06 CST 2016 x86_64 Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz GenuineIntel GNU/Linux

**Operating system**:

Slackware 14.2

**Web server:**

Server version: Apache/2.4.18 (Unix)

**Database:**

mariadb-10.0.24-x86_64-2

**PHP version:**

PHP 5.6.19 (cli) (built: Mar  4 2016 23:12:14)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.0.8, Copyright (c) 2002-2016, by ionCube Ltd.
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)

13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

upgraded continuously from Owncloud 9.0.1 to Nextcloud 10.0.4, then  11.0.2, then 12.0.0, and now 13.0.1

**Where did you install Nextcloud from:**

From tarred sources, downloaded from the NextCloud site's repo and installed by hand. 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - deck: 0.3.1
  - drawio: 0.8.9
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
- logreader: 2.0.0                                                    [12/234]
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.8
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_diaspora: 1.0.2
  - socialsharing_email: 1.0.3
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0

Disabled:
  - admin_audit
  - bruteforcesettings
  - calendar
  - encryption
  - files_external
  - files_opds
  - files_reader
  - files_texteditor
  - lsd
  - socialsharing_facebook
  - spreed
  - user_external
  - user_ldap

</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**Nextcloud configuration:**
<details>
<summary>sudo -u apache php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.mydomain.com",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls"

</summary>

```


```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

```


### Client configuration
**Browser:**

Chrome, Firefox, and Opera on Linux and Win10/64

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```

ssl_error_log:
[Sat Apr 21 05:15:27.299595 2018] [ssl:info] [pid 21490:tid 140133189752576] [client 174.222.4.10:9416] AH01998: Connection closed to child 80 with abortive shutdown (server nexcloud.mydomain.com:443)

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
# tail -f nextcloud.log
{"reqId":"J4mgNCda2viqesayIZFD","level":0,"time":"2018-04-21T12:01:16+00:00","remoteAddr":"63.143.42.245","user":"--","app":"core","method":"HEAD","url":"\/index.php\/login","message":"Scss is disabled for \/var\/www\/nextcloud.mydomain.com\/owncloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0+(compatible; UptimeRobot\/2.0; http:\/\/www.uptimerobot.com\/)","version":"13.0.1.1"}
{"reqId":"J4mgNCda2viqesayIZFD","level":0,"time":"2018-04-21T12:01:16+00:00","remoteAddr":"63.143.42.245","user":"--","app":"core","method":"HEAD","url":"\/index.php\/login","message":"Scss is disabled for \/var\/www\/nextcloud.mydomain.com\/owncloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0+(compatible; UptimeRobot\/2.0; http:\/\/www.uptimerobot.com\/)","version":"13.0.1.1"}
{"reqId":"vgpP9jqQFXDf01Z7T9c1","level":0,"time":"2018-04-21T12:06:16+00:00","remoteAddr":"63.143.42.245","user":"--","app":"core","method":"HEAD","url":"\/index.php\/login","message":"Scss is disabled for \/var\/www\/nextcloud.mydomain.coms\/owncloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0+(compatible; UptimeRobot\/2.0; http:\/\/www.uptimerobot.com\/)","version":"13.0.1.1"}
{"reqId":"vgpP9jqQFXDf01Z7T9c1","level":0,"time":"2018-04-21T12:06:16+00:00","remoteAddr":"63.143.42.245","user":"--","app":"core","method":"HEAD","url":"\/index.php\/login","message":"Scss is disabled for \/var\/www\/nextcloud.mydomain.com\/owncloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0+(compatible; UptimeRobot\/2.0; http:\/\/www.uptimerobot.com\/)","version":"13.0.1.1"}
{"reqId":"vgpP9jqQFXDf01Z7T9c1","level":0,"time":"2018-04-21T12:06:16+00:00","remoteAddr":"63.143.42.245","user":"--","app":"core","method":"HEAD","url":"\/index.php\/login","message":"Scss is disabled for \/var\/www\/nextcloud.mydomain.com\/owncloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0+(compatible; UptimeRobot\/2.0; http:\/\/www.uptimerobot.com\/)","version":"13.0.1.1"}
{"reqId":"vgpP9jqQFXDf01Z7T9c1","level":0,"time":"2018-04-21T12:06:16+00:00","remoteAddr":"63.143.42.245","user":"--","app":"core","method":"HEAD","url":"\/index.php\/login","message":"Scss is disabled for \/var\/www\/nextcloud.mydomain.com\/owncloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0+(compatible; UptimeRobot\/2.0; http:\/\/www.uptimerobot.com\/)","version":"13.0.1.1"}
{"reqId":"RGtRTFz3aquSO7T61s52","level":0,"time":"2018-04-21T12:11:16+00:00","remoteAddr":"63.143.42.245","user":"--","app":"core","method":"HEAD","url":"\/index.php\/login","message":"Scss is disabled for \/var\/www\/nextcloud.mydomain.com\/owncloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0+(compatible; UptimeRobot\/2.0; http:\/\/www.uptimerobot.com\/)","version":"13.0.1.1"}
{"reqId":"RGtRTFz3aquSO7T61s52","level":0,"time":"2018-04-21T12:11:16+00:00","remoteAddr":"63.143.42.245","user":"--","app":"core","method":"HEAD","url":"\/index.php\/login","message":"Scss is disabled for \/var\/www\/nextcloud.mydomain.com\/owncloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0+(compatible; UptimeRobot\/2.0; http:\/\/www.uptimerobot.com\/)","version":"13.0.1.1"}
{"reqId":"RGtRTFz3aquSO7T61s52","level":0,"time":"2018-04-21T12:11:16+00:00","remoteAddr":"63.143.42.245","user":"--","app":"core","method":"HEAD","url":"\/index.php\/login","message":"Scss is disabled for \/var\/www\/nextcloud.mydomain.com\/owncloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0+(compatible; UptimeRobot\/2.0; http:\/\/www.uptimerobot.com\/)","version":"13.0.1.1"}
{"reqId":"RGtRTFz3aquSO7T61s52","level":0,"time":"2018-04-21T12:11:16+00:00","remoteAddr":"63.143.42.245","user":"--","app":"core","method":"HEAD","url":"\/index.php\/login","message":"Scss is disabled for \/var\/www\/nextcloud.mydomain.com\/owncloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0+(compatible; UptimeRobot\/2.0; http:\/\/www.uptimerobot.com\/)","version":"13.0.1.1"}
{"reqId":"YojNgQU0pPdkI8fjQM9t","level":0,"time":"2018-04-21T12:15:29+00:00","remoteAddr":"174.222.4.10","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 14","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"YojNgQU0pPdkI8fjQM9t","level":0,"time":"2018-04-21T12:15:29+00:00","remoteAddr":"174.222.4.10","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Invalidating session tokens older than 2018-04-20T12:15:29+00:00","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"YojNgQU0pPdkI8fjQM9t","level":0,"time":"2018-04-21T12:15:29+00:00","remoteAddr":"174.222.4.10","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Invalidating remembered session tokens older than 2018-04-06T12:15:29+00:00","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"YojNgQU0pPdkI8fjQM9t","level":0,"time":"2018-04-21T12:15:29+00:00","remoteAddr":"174.222.4.10","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 14 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko\/20100101 Firefox\/59.0","version":"13.0.1.1"}
{"reqId":"lgsj8olCrrkxbp8wgNBB","level":3,"time":"2018-04-21T12:15:35+00:00","remoteAddr":"174.222.4.10","user":"jschmoe","app":"richdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/index?fileId=32&requesttoken=4fIdBLv4wanf9RhOqX0iG71Sga7Bs1jtEIdyTX74ODc%3D%3Aq4YqaO2P6sGawEw86E4SSds798es4juhQs8gHRSoXF8%3D","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ConnectException\",\"Message\":\"cURL error 7: Failed to connect to office.mydomain.com port 9980: Connection refused\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud.mydomain.com\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(104): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\ConnectException))\\n#1 \\\/var\\\/www\\\/nextcloud.mydomain.com

</details>

**Comment by tallship** [comment]
Judging by the connection refused errors, is this some kind of special firewall or routing issue? The docker container is running on the same host as the nextcloud installation, and as per the instructions, nothing else special was required since everything is on localhost.

    {"reqId":"lgsj8olCrrkxbp8wgNBB","level":3,"time":"2018-04-21T12:15:35+00:00","remoteAddr":"174.222.4.10","user":"jschmoe","app":"richdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/index?fileId=32&requesttoken=4fIdBLv4wanf9RhOqX0iG71Sga7Bs1jtEIdyTX74ODc%3D%3Aq4YqaO2P6sGawEw86E4SSds798es4juhQs8gHRSoXF8%3D","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ConnectException\",\"Message\":\"cURL error 7: Failed to connect to office.mydomain.com port 9980: Connection refused\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud.mydomain.com\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(104): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\ConnectException))\\n#1 \\\/var\\\/www\\\/nextcloud.domain.com

and...

    [Sat Apr 21 05:15:27.299595 2018] [ssl:info] [pid 21490:tid 140133189752576] [client 174.222.4.10:9416] AH01998: Connection closed to child 80 with abortive shutdown (server nexcloud.mydomain.com:443)

Firewall rules have this (Do I even need the UDP rule? Are these rules correct?

<snip>
~# cat /etc/rc.d/rc.firewall |grep 9980
$IPT -A tcp_inbound -p TCP -s 0/0 --destination-port 9980 -j ACCEPT
$IPT -A udp_inbound -p TCP -s 0/0 --destination-port 9980 -j ACCEPT
</snip>

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by jonidimo** [comment]
Did you solve this? I had the same problem installing CODE:

https://i.imgur.com/wQtfyB2.jpg

Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

**Comment by ApertureSecurity** [comment]
I have the same problem 
Trying to edit a ODT document. I have encryption enabled and Collabora as soon as I open the ODT file I am met with this bug.

**Comment by fdmsh** [comment]
You'll laugh out loud, but i have the same issue in 2026!
