### ISSUE TITLE
[FEATURE REQUEST] Add support for .MOV format

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#9264]
I would like to request a feature request to support .MOV to play within the browser. I have tried this with Google Chrome and Firefox all updated to their latest versions and with or without Quicktime installed but this never worked. Downloading the files and opening them on the computer resulted in this working just fine.

**Comment by MorrisJobke** [comment]
This highly depends on the installed plugins in your browser. You need to install a plugin that supports the decoding of those mov files. Usually this is not installed. Typically this is a codec package or comes with some video players.

Please check first to run the mov file directly in the browser without Nextcloud in between. For this usually a drag and drop into an empty browser tab should do the trick. If it downloads, then there is no codec available. If it plays back, please open a ticket in the video player app: https://github.com/nextcloud/files_videoplayer

**Comment by abctaylor** [comment]
Hi all! I have made automation to solve this problem: https://https://github.com/abctaylor/nextcloud-mov-2-mp4

It is a script I wrote to search for `.mov` files in your storage, convert them to `.mp4`, re-index nextcloud and clean up.

Andrew
