### ISSUE TITLE
Comments with mentions look broken in the comments view

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#9273]
## Activity view
> ![bildschirmfoto von 2018-04-23 12-33-43](https://user-images.githubusercontent.com/213943/39121794-ff63ea84-46f2-11e8-88c4-e278ca07ffc6.png)

## Comments view
> ![bildschirmfoto von 2018-04-23 12-33-47](https://user-images.githubusercontent.com/213943/39121810-0cf55552-46f3-11e8-81cc-8bbf139aead4.png)

It seems to be broken, because the author information row uses the same CSS classes as the inline mentions. (width 100%, etc.), see Nextcloud 13 for help how it should look

cc @nextcloud/designers

**Comment by danxuliu** [comment]
[Avatars are going to be removed from mentions in comments](https://github.com/nextcloud/server/pull/7514#issuecomment-355607368) (and then I guess that we should remove them from the activity view too) so that should implicitly fix this issue.

**Comment by MorrisJobke** [comment]
Fixed by #10288 

![bildschirmfoto 2018-07-25 um 14 32 01](https://user-images.githubusercontent.com/245432/43200989-8b205d10-9017-11e8-8a0c-eca77df1eaad.png)
