### ISSUE TITLE
NextCloud Desktop Client does not scale correctly for high resolution displays

### ISSUE THREAD

**Issue by iduno** [nextcloud/server#9285]
I have a Lenovo Yoga 2 pro laptop with a QHD+ (3200 x 1800) display.
The scaling is set to 250%

When the Desktop Client is open, it opens the window 250% of the 250% scaling (ie 625% scaling), so it is impossible to see the full window.
The only workaround is to reduce the scaling to 100% when updating the settings and revert back once complete.

**Comment by MorrisJobke** [comment]
Please report this in the client repo: https://github.com/nextcloud/client
