### ISSUE TITLE
13.0.1: bad signature after webdav-copying a textfile that was created within the webinterface

### ISSUE THREAD

**Issue by Af0x** [nextcloud/server#9294]
Hello,
if you 

1. create a new text document via the webinterface
2. copy and paste that document with a webdav-client so that there are two duplicates "test.txt" and "test(1).txt"
3. try to open the duplicate "test(1).txt"

it gives you a bad signature error.

Nextcloud 13.0.1, Default encryption module 2.0.0
webdav-client: Fedora 27

Regards,
Af0x

**Comment by MorrisJobke** [comment]
cc @nextcloud/encryption

**Comment by MorrisJobke** [comment]
Duplicate of #8989 - fixed in the upcoming 13.0.2
