### ISSUE TITLE
What about the 1736 open issues from the old repo, will they be fixed?

### ISSUE THREAD

**Issue by knutschneider** [nextcloud/server#93]
What about the 1736 open issues from the old repo: https://github.com/owncloud/core/

Will they be fixed in this project? How are these issues tracked?
Should all issues be re-filed for this project?

**Comment by LukasReschke** [comment]
We don't automatically copy any of the existing issues and feedback requests since some are not applicable and it doesn't provide any bigger advantage right now except flooding the issues here.

> Should all issues be re-filed for this project?

No. If there is a bug that is also applicable to Nextcloud it should be filed here however.

**Comment by knutschneider** [comment]
Definitely a good way to get rid of hundreds of issues at an instant 👎 
How many issues are no longer applicable? 5%?

**Comment by mar1u5** [comment]
...this is **not** the reason for that 😒 It is simply a question who would handle all the feature requests, bugs, ... . Nobody is able to organize that 😁 If you want to see some features in Nextcloud - you are able to open issues here or discuss them in the forums 😉
