### ISSUE TITLE
When user shares reshared item via link and then unshares it, no one can remove the link

### ISSUE THREAD

**Issue by jirutka** [nextcloud/server#9303]
### Steps to reproduce

1. As user A, share folder to user B.
2. As user B, share the folder via public link.
3. As user B, remove the folder.

### Expected behaviour

* Link should be disabled after user B removed the folder.
* The owner should be IMO always able to remove particular reshares of the items (s)he shared.

### Actual behaviour

The link is still active and no one can remove (disable) it. User B doesn’t have access to the folder anymore and user A (the owner) cannot remove it, (s)he only see that B shared the folder via link, but since it’s not shared to B anymore, there’s no way how to remove the link, except deleting the folder (or sharing it to B again and letting him to remove the link).

### Server configuration

**Operating system**: Linux

**Web server:** nginx

**Database:** PostgreSQL

**PHP version:** 7.1.16

**Nextcloud version:** 12.0.6

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing - I guess this can be resolved properly by integrating the share links into the upper list and not have it available as a separate element. See #5336

**Comment by rullzer** [comment]
This is actually already in NC13 I believe

![share](https://user-images.githubusercontent.com/45821/39292608-fcbb9bf6-4936-11e8-91c6-819fa670fe9f.png)

Also when I unshare from user0 the link share is deleted as well here...

**Comment by MorrisJobke** [comment]
Ah ... correct. Tested and works indeed. The link share is properly removed.
