### ISSUE TITLE
Encrypted mode registration flow should be less confusing

### ISSUE THREAD

**Issue by CySlider** [nextcloud/server#9311]
### Steps to reproduce
1. Install NC13
2. Enable default encryption module
3. Enable "Show emails" on users page as admin
4. Enable "Send email to new user" on users page as admin
5. Create user without setting password

### Expected behaviour
Email with registration link
Registration dialog that asks for password
Registration finishes/user is logged in

### Actual behaviour
Email with registration link
Password reset dialog shows (confusing already should show "Choose password" or similar)
Scary warning about data loss shows (User can not have any data yet)
Registration finishes/user is logged in

### Server configuration

**Nextcloud version:** 
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Fresh install

**Comment by MorrisJobke** [comment]
cc @nextcloud/encryption

**Comment by melkon** [comment]
I added a PR to remove the warning and improve the wording a bit. Not sure if it will make it in time before the code freeze, especially because it's my first PR for nextcloud.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
