### ISSUE TITLE
Add Support for Link headers

### ISSUE THREAD

**Issue by tbe** [nextcloud/server#9316]
To make use of the server push feature of HTTP/2, there is needed some kinds of mechanism to tell the webserver which files should be pushed.

The common method is to use the `Link` header.

The `addStyle`, `addScript`, ... functions may do this.

Example of a Link header:
```
Link </xxx.css>;rel=preload, </xxx.js>; rel=preload
```

https://httpd.apache.org/docs/current/howto/http2.html#push

**Comment by Glandos** [comment]
Duplicate of #6214.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
