### ISSUE TITLE
The tooltip hides the password when you click on "show password" icon on personal settings

### ISSUE THREAD

**Issue by xh3n1** [nextcloud/server#9317]
### Steps to reproduce
1.Click on the "show password" icon
2.Write the new password

### Expected behaviour
I should be able to see the password while writing.

### Actual behaviour
The tooltip hides the password.
![photo_2018-04-26_16-58-28](https://user-images.githubusercontent.com/9008509/39314043-a472368e-4973-11e8-84e0-a07edc753a37.jpg)

**Comment by marc0s** [comment]
I was going to pick up this issue as a first one, but it's not happening in NC13 with Firefox 59

![2018-05-04-173610_319x215_scrot](https://user-images.githubusercontent.com/273769/39636882-c4ebf784-4fc1-11e8-8a6e-99e9774462ca.png)

**Comment by moritz31** [comment]
Tried to reproduce, not happening on Chrome 66 nor Firefox 61 
@xh3n1 what browser do you use?

**Comment by xh3n1** [comment]
@moritz31 I can't reproduce this issue anymore.
