### ISSUE TITLE
Add revision number

### ISSUE THREAD

**Issue by johnosull** [nextcloud/server#9320]
In addition to the time/date stamp, it would be useful if NextCloud had a file revision number displayed for each file, that behaves as follows:

- New file created/uploaded = revision 1
- File is subsequently edited and saved, or a new version is uploaded should increment the revision number sequentially (to 2, 3, etc. each time the file changes)
- Revision number should display on both the main file view (next to the current filename) and also on the 'Revisions' subtab within the Details tab so that each revision has a unique number

Currently, the only way of tracking which revision of a file is which is by time/date stamp (which isn't unique since it only goes to the minute and not the second), or by using the 'Checksum' addon, which is unique for each file revision, but the problem with this is that there are 5 algorithm options, and you can't guarantee that everyone will use the same algorithm as a reference. A number would be easier and more intuitive for users as a reference for a particular revision of a file.

If possible, this could propagate upwards to folder level, i.e.

- File changes - increment file revision number
- If file(s) within a folder are up-revved - increment this folder's revision number and the revision number of any parent folders

**Comment by MorrisJobke** [comment]
> If file(s) within a folder are up-revved - increment this folder's revision number and the revision number of any parent folders

That could lead very easily to a very big number that is not helpful for a human to memorize. We have something similar which is the ETAG and is used for change detection. It only shows that something has changed, but does not hold information about the when.

cc @nextcloud/designers for feedback.
cc @rullzer @nickvergessen @icewind1991 @schiessle @blizzz for opinions on this

**Comment by johnosull** [comment]
I appreciate the quick reply Morris. 

 

The folder revision was a ‘nice-to-have’ anyway, and you’re right - it probably would result in a large folder revision number very quickly if it changes every time a file within a folder/subfolder changes and the revision cascades upwards from the file to parent folder(s).

The functionality I really need is file revision (a unique, human-readable id showing every time a file changes) so if etags do the job, great. However, I can’t find any documentation on etags, and can’t see any etag field in my current setup (Nextcloud 13 server).


Can you point me in the right direction please?

 

Thanks

**Comment by blizzz** [comment]
@johnosull what is the general use case? Also, numbers are nice, but likely no one will remember what the last change was wherever. What might be related would be https://github.com/nextcloud/server/issues/1213 perhaps?

**Comment by johnosull** [comment]
We’re using NextCloud for document/file management during creation of e-learning content (scripts, videos, etc). 

*         A writer could prepare a piece of content in a file and signoff that they’re happy with v1.

*         V1 gets sent to SME for review, SME suggests changes to v1.

*         Writer updates with SME requests, making a new v2 file, which the SME then re-reviews and approves.

*         V2 is then sent to QC, who suggest further changes, creating v3.

*         Writer fixes the issues, creating v4.

*         V4 is sent for client review. Client requests their own set of changes. 

*         V5 is created to implement client changes, and sent back to client for approval. V5 is client approved and locked from further editing.


At each point/each signoff, we want traceability/audit trail of which version of the file was reviewed/approved by whom. We have a separate system for tracking this, so all we need in NextCloud is an easily visible numeric reference for each revision. 

 

A numeric reference on the main Files view would ensure:

a)      Easy visibility of a version that isn’t buried away in a hover-over on a subtab (like time/datestamp or checksum)

A)     That the revision number increments even for minute by minute changes, which timestamp currently doesn’t show – developers/QC can identify immediately if any changes are made to a version because the number will have incremented 

 

Thanks

**Comment by blizzz** [comment]
essentially this would be covered by #1213, only that this one is lot of work and only on the backlog. As a workround, those involved can leave status updates a Comments to the file after each step.

**Comment by johnosull** [comment]
But the comments only go on the latest file, not on each revision?

**Comment by blizzz** [comment]
The comments are independent from the file version/revision. It's certainly not a fancy or overly comfortable way to do it. just something that could be utilized now.

or @schiessle has some idea in the context of file versions?

**Comment by johnosull** [comment]
Thanks again.

Just a suggestion, but I think an auto-incrementing revision number would be far easier to implement than #1213 <https://github.com/nextcloud/server/issues/1213> , and would essentially achieve the same effect.

**Comment by MorrisJobke** [comment]
> Just a suggestion, but I think an auto-incrementing revision number would be far easier to implement than #1213 <#1213> , and would essentially achieve the same effect.

I would not say so and it also feels like a weird hack to accomplish the same. Let's better add a proper feature instead of a quick hack.

**Comment by johnosull** [comment]
OK, probably right…I was just hoping for a quicker fix.

So just to get back to etags as a possible currently available solution, is there documentation available on how to utilize these?

 

From: John O'Sullivan [mailto:john.osullivan@longboat.com] 
Sent: Friday 27 April 2018 13:17
To: 'nextcloud/server' <reply@reply.github.com>; 'nextcloud/server' <server@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [nextcloud/server] Add revision number (#9320)

 

Thanks again.

Just a suggestion, but I think an auto-incrementing revision number would be far easier to implement than #1213 <https://github.com/nextcloud/server/issues/1213> , and would essentially achieve the same effect.

**Comment by skjnldsv** [comment]
@MorrisJobke so, too complicated or not?
Shall we keep opened?

**Comment by MorrisJobke** [comment]
> @MorrisJobke so, too complicated or not?
> Shall we keep opened?

At least it is nothing we will have implemented in the next version or plan to do at all. So closing makes sense. If this is something we want to do additionally to the existing etag then we can reopen and continue the discussion.
