### ISSUE TITLE
Add parent index to oc_shares table

### ISSUE THREAD

**Issue by dtygel** [nextcloud/server#9327]
### Steps to reproduce
1. Have more than 100 shared files to circles in a directory A
2. Go to apps/files and go to directory A

### Expected behaviour
See the list of files in a reasonable time

### Actual behaviour
It takes ages to load the files' list. Looking at long queries in mysql log, it's because the field _parent_ is not indexed.

We've tested locally, and had an increase in performance from 1.8s for the query to 0.4s, a huge improvement by just adding the field _parent_ as a normal index.

We don't know how to add the index to the core tables. If we can  get some reference on how to do this (table _oc_shares_), we can submit a simple Pull Request.

**Comment by MorrisJobke** [comment]
Could you run `occ db:add-missing-indices` and check if this already helps with your problem? Otherwise @rullzer can also have a look at this.

**Comment by rullzer** [comment]
I'll take care of this!
