### ISSUE TITLE
Fatal webdav Doctrine\DBAL\Exception\DriverException:

### ISSUE THREAD

**Issue by mesro09** [nextcloud/server#9328]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
i cant mount my installation on windows 
i did other test installation on virtual ubuntu and just same configuration only diferent domain for test and i can also mount drive etc.
### Server configuration

**Operating system**:
Ubuntu
**Web server:**
apache 2.4.33
**Database:**
postgresql 9.6
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13.02
**Updated from an older Nextcloud/ownCloud or fresh install:**
13.01
**Where did you install Nextcloud from:**
installed on my own  cpu it has 8gb ram and core i7 3th
**Signing status:**
<details>
<summary>Signing status</summary>
i have 2 diferent domain in the same server but only this installation gave this error 
both instalation and app as same as only domain name is diferent
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ocdownloader: 1.5.6
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - ransomware_protection: 1.1.0
  - registration: 0.4.2
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - unsplash: 1.1.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - onlyoffice
  - phonetrack
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
?php
$CONFIG = array (
  'instanceid' => 'Sensitive data',
  'passwordsalt' => 'Sensitive data',
  'secret' => 'Sensitive data',
  'trusted_domains' => 
  array (
    0 => 'cloud.Sensitivedata',
  ),
  'datadirectory' => '/NasHdd/sensitive_Data',
  'overwrite.cli.url' => 'https://cloud.Sensitive data',
  'dbtype' => 'pgsql',
  'version' => '13.0.2.1',
  'dbname' => 'Sensitive data',
  'dbhost' => '127.0.0.1:5432',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'Sensitive data',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'mail_smtpdebug' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'webmaster',
  'mail_domain' => 'Sensitive data',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.Sensitive_data',
  'mail_smtpport' => '26',
  'mail_smtpname' => 'webmaster@Sensitive_data',
  'mail_smtppassword' => 'Sensitive data',
  'maintenance' => false,
  'htaccess.RewriteBase' => '/',
  'updater.secret' => 'Sensitive datas......',
  'theme' => '',
  'loglevel' => 4,
);

<details>

<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Google Chrome
**Operating system:**
Ubuntu 17.10 Server (without graphic interface)
### Logs
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT "fileid", "storage", "path", "parent", "name", "mimetype", "mimepart", "size", "mtime", "storage_mtime", "encrypted", "etag", "permissions", "checksum" FROM "oc_filecache" "file" WHERE ("storage" = ?) AND ((("mimepart" = ?) OR ("mimepart" = ?)) AND ("mtime" >= ?))' with params [17, 5, 7, -62104252760]: SQLSTATE[22003]: Numeric value out of range: 7 ERROR: value "-62104252760" is out of range for type integer
/var/www/html/nexcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
/var/www/html/nexcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 855: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT "fileid"...', Array)
/var/www/html/nexcloud/lib/private/DB/Connection.php - line 195: Doctrine\DBAL\Connection->executeQuery('SELECT "fileid"...', Array, Array, NULL)
/var/www/html/nexcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 206: OC\DB\Connection->executeQuery('SELECT "fileid"...', Array, Array)
/var/www/html/nexcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214: Doctrine\DBAL\Query\QueryBuilder->execute()
/var/www/html/nexcloud/lib/private/Files/Cache/Cache.php - line 697: OC\DB\QueryBuilder\QueryBuilder->execute()
/var/www/html/nexcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 233: OC\Files\Cache\Cache->searchQuery(Object(OC\Files\Search\SearchQuery))
[internal function] OC\Files\Cache\Wrapper\CacheWrapper->searchQuery(Object(OC\Files\Search\SearchQuery))
/var/www/html/nexcloud/lib/private/Files/Node/Folder.php - line 245: call_user_func_array(Array, Array)
/var/www/html/nexcloud/lib/private/Files/Node/Folder.php - line 201: OC\Files\Node\Folder->searchCommon('searchQuery', Array)
/var/www/html/nexcloud/apps/dav/lib/Files/FileSearchBackend.php - line 158: OC\Files\Node\Folder->search(Object(OC\Files\Search\SearchQuery))
/var/www/html/nexcloud/3rdparty/icewind/searchdav/src/DAV/SearchHandler.php - line 75: OCA\DAV\Files\FileSearchBackend->search(Object(SearchDAV\XML\BasicSearch))
/var/www/html/nexcloud/3rdparty/icewind/searchdav/src/DAV/SearchPlugin.php - line 123: SearchDAV\DAV\SearchHandler->handleSearchRequest(Array, Object(Sabre\HTTP\Response))
[internal function] SearchDAV\DAV\SearchPlugin->searchHandler(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/nexcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/html/nexcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method SEARCH', Array)
/var/www/html/nexcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/nexcloud/apps/dav/lib/Server.php - line 283: Sabre\DAV\Server->exec()
/var/www/html/nexcloud/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()
/var/www/html/nexcloud/remote.php - line 164: require_once('/var/www/html/A...')
{main}

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
