### ISSUE TITLE
Upgrade from 13.0.1 to 13.0.2 not possible

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/server#9329]
### Steps to reproduce
1. Clicking "Update" on the Admin settings panel

### Expected behaviour
Update process starts smoothly

### Actual behaviour
The following strange site appears:
![update_fail](https://user-images.githubusercontent.com/29654384/39375553-04b5be86-4a4f-11e8-9930-807f97895564.png)
No update is possible (clicking on continue does nothing but switching to the "end" of the upgrade process ("Go back to your nextcloud instance...")

## Server configuration detail

**Operating system:** Linux 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.1.23

**PHP version:** 7.0.27-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.3
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "logtimezone": "Europe\/Berlin",
    "log_type": "owncloud",
    "log_authfailip": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "htaccess.RewriteBase": "\/",
    "singleuser": true,
    "loglevel": 2,
    "updater.release.channel": "stable",
    "theme": "",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0

**Operating system:** 

Does anybody else have this problem?
Updates in the past all went fine :)

**Comment by jschuck** [comment]
My Problem is similar but might be related.
I'm usually using the occ upgrade cli command to perform upgrades.
While it has always worked in the past, this time it failed rather spectacularly.

It performs all the steps, and finishes. I wondered why my desktop client wouldn't connect and checked the web interface, which showed the starting page for a new installation. Turns out, after the installation went through the config file was still present, but completely empty. Filesize 0B empty.

Replacing it with the backup just started the upgrade cycle up again, leaving me in 10/10 tests with an empty configuration.

Same result trying to use the web interface for an upgrade.

**Comment by MorrisJobke** [comment]
Looks like the `.step` file was not properly deleted after the previous update. Could you remove the file `DATADIR/updater-INSTANCEID/.step` and try the update again? Usually this file is removed during the upgrade process as a repair step.



> when I update, it shows
> Check for write permissions
> The following places can not be written to:
> /www/wwwroot/mydomain/updater/../.user.ini
> 
> so where is the .user.ini？

It is at `/www/wwwroot/mydomain/updater/../.user.ini` - or shortened at `/www/wwwroot/mydomain/.user.ini`
