### ISSUE TITLE
where is updater/../.user.ini? update 13.0.1 to 13.0.2

### ISSUE THREAD

**Issue by zhanggaoxuan** [nextcloud/server#9331]
### Steps to reproduce
1.update on the website
2.check the write permission
3.

### Expected behaviour
Tell us what should happen
finish update

### Actual behaviour
Tell us what happens instead
shows The following places can not be written to:
/www/wwwroot/mydomain/updater/../.user.ini
### Server configuration

**Operating system**:
centos7
**Web server:**
nginx
**Database:**
mariadb
**PHP version:**
php7.0
**Nextcloud version:** (see Nextcloud admin page)
13.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
no
**Where did you install Nextcloud from:**
server
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/9329

**Comment by ChristophWurst** [comment]
Whoops now, two different users commented in https://github.com/nextcloud/server/issues/9329 and I confused the avatars …

**Comment by Schmuuu** [comment]
> The following places can not be written to:
> /www/wwwroot/mydomain/updater/../.user.ini

Have you checked, if the updater could actually modify the file?
I mean, what is the output of
`ls -l /www/wwwroot/mydomain/updater/../.user.ini`

By the way, the .user.ini can be found under:
`/www/wwwroot/mydomain/.user.ini`

You could have asked this question in the forum first:
[https://help.nextcloud.com](https://help.nextcloud.com)

**Comment by MorrisJobke** [comment]
> Have you checked, if the updater could actually modify the file?
> I mean, what is the output of
> ls -l /www/wwwroot/mydomain/updater/../.user.ini
> 
> By the way, the .user.ini can be found under:
> /www/wwwroot/mydomain/.user.ini
> 
> You could have asked this question in the forum first:
> https://help.nextcloud.com

@Schmuuu is correct here - the file is at `/www/wwwroot/mydomain/updater/../.user.ini` - or shortened at `/www/wwwroot/mydomain/.user.ini`.
