### ISSUE TITLE
Security Issue while login

### ISSUE THREAD

**Issue by m3sm3r0** [nextcloud/server#9333]
### Steps to reproduce
1.  On login screen:
2. Try to login using existing account but wrong password
3. The error message should be different than current.

### Expected behavior
I should says: 'Login or password incorrect' or something similar not to tell that user already exists.

### Actual behavior
When I'm trying to login to Nextcloud using wrong credentials it says: "Wrong password. "  when the login is OK. It could be easier to brute-force when attacker knows login or attacker could block account of existing user.

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** SQlite

**PHP version:** php7

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12

**Where did you install Nextcloud from:** dockerhub

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Schmuuu** [comment]
It also says "wrong password" when the user name is wrong, too ;) (NC 13.0.2)
So there is no real indication right now, if you mistyped the username and/ or the password. Therefor no security issue in my opinion, but rather confusing for users who really have a typo in their username.

**Comment by MorrisJobke** [comment]
> It also says "wrong password" when the user name is wrong, too ;) (NC 13.0.2)
> So there is no real indication right now, if you mistyped the username and/ or the password. Therefor no security issue in my opinion, but rather confusing for users who really have a typo in their username.

Yep - just tested and it says in both cases "Wrong password".
