### ISSUE TITLE
Question about trash

### ISSUE THREAD

**Issue by javey222** [nextcloud/server#9336]
Hello

This is actually a question if this is a mistake.

I have NextCloud 13.0.2 with PHP7.1 running on Ubuntu 16.04.
And I have the encryption of all data posted.

Question:
If I delete or change data, there is no version history so snaps and they do not load into a trash when deleting synonymous.
Is this normal when casting or is it a fatal error ?!

Thank you!

LG

**Comment by MorrisJobke** [comment]
cc @nextcloud/encryption

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
