### ISSUE TITLE
Login via Magic Link

### ISSUE THREAD

**Issue by 8sd** [nextcloud/server#9342]
I'm currently using slack frequently. Slack has a feature to use a 'Magic Link' in a Mail to authenticate for a channel.
It would be quite convenient to use this feature for the Nextcloud login.

The link contains a random hash and maybe the password: `https://cloud.com/login?user=username&hash=D42D19F83413D064A1A4C2B5FCA58EE2ADF437A5C6383369B8CA4514A9E40653` 
The back end has to check whether the the username and the hash fit to the hash earlier created by the back end.

**Comment by rullzer** [comment]
This is not something we can support. There are operations in Nextcloud where we need access to your password (for example for external storage). However if we generate such a link there is no way for the server to know your password as your password is never stored unhashed/unencrypted on the server.

**Comment by MorrisJobke** [comment]
cc @ChristophWurst

**Comment by 8sd** [comment]
It might be possible to use this as log in for the (Web)app.
If the password is required for any special access one can still ask for it.

**Comment by ChristophWurst** [comment]
> If the password is required for any special access one can still ask for it.

We don't currently support that. There's just too much going on behind the scenes that you as a user don't see. But for example "just the web interface" also might mean you create an app password for your devices and those might access APIs where the password is required. We can't ask for it there. Moreover there are many tasks that are executed asynchronously in the background (cron) where no password request is possible.

I'd say this is out of scope for our current authentication architecture. You can already generate URLs where the user ID is prefilled on the login page.

I'm closing this therefore.
