### ISSUE TITLE
Unsecured kibana server on Your Infrastructure

### ISSUE THREAD

**Issue by Roottrader** [nextcloud/server#9343]
Hello,

I am a white hat security researcher. While searching for in secured servers i have found one which belongs to your organization. The URL of the server
is "https://88.122.139.18/app/kibana"

I am able to see all your logs in detail, important data  without any authentication.
I Hope that you will patch the server soon and hope you award me some bounty for this responsible disclosure.

Many Thanks,
Roottrader

**Comment by rullzer** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
This is not our infrastructure. This is a private nextcloud instance - please contact the admin of that server.

I will remove the sensible information from your post.
