### ISSUE TITLE
Change URL with overwrite.cli.url

### ISSUE THREAD

**Issue by serverhack74** [nextcloud/server#9350]
NC: 13.0.0
Apache 2.4.18
Mysql 5.7.21
PHP 7.0.28

Hi everybody, I've been changing values for overwrite.cli.url, but I'm not sure if its function is as I undestand.

is it possible to change the URL for the shared links? I mean, if I share a file by link it is accessible through www.domain.com/index.php/s/HHGRTESS (p.e.), i’d like to change the domain part for every link to www.domainalternative.com/index.php/s/HHGRTESS

I thought this was accomplished via the overwrite.cli.url, but it's not, the URL for the shared link is built from the accesed domain.

Is it that possible? I’ve been googling for a while but I cannot find any actual way.

Thanks!!!

**Comment by MorrisJobke** [comment]
Use the config options `overwritehost` and `overwriteprotocol` to accomplish this in the web UI. the `overwrite.cli.url` is only used for the CLI based URL generation.
