### ISSUE TITLE
problem with updater 

### ISSUE THREAD

**Issue by bah0071** [nextcloud/server#9356]
hello

i am using updater and when it does its checks i get the following error (extra files have been found ,

what is the file "," what do i do

Initializing
Current version is 13.0.1.
Update to Nextcloud 13.0.2 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-13.0.2.zip
Retry update
Check for expected files
The following extra files have been found:
,

**Comment by MorrisJobke** [comment]
> what is the file "," what do i do

Check the root folder of your nextcloud installation. It seems that there is a file/folder called `,` - remove it or move it out of this folder to make the updater continue it's job.

**Comment by bah0071** [comment]
thanks it worked!!!

**Comment by bah0071** [comment]
i just did the update and now nextcloud is broken when i wanted to turn off maintenanc mode
Keep maintenance mode active?
Maintenance mode will get disabled.
Parsing response failed. <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>500 Internal Server Error</title> </head><body> <h1>Internal Server Error</h1> <p>The server encountered an internal error or misconfiguration and was unable to complete your request.</p> <p>Please contact the server administrator at webmaster@mvapower.com to inform them of the time this error occurred, and the actions you performed just before this error.</p> <p>More information about this error may be available in the server error log.</p> </body></html>
