### ISSUE TITLE
nextcloud desktop app not connection

### ISSUE THREAD

**Issue by bah0071** [nextcloud/server#9357]
Hello

I am trying to set up my nextcloud destop sync app with my nextcloud instance but when using the wizard i get blocked at the user credentials part

after i enter the login details it gives me

the authenticated request to this server was redirected to "http://(my domain)/(my cloud folder)/index.php/apps/files/" the url is bad, the server is misconfigured...

When using the mobile app i have no problem

HELP!!!

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
