### ISSUE TITLE
Calendar Invitations classified as SPAM

### ISSUE THREAD

**Issue by janharms** [nextcloud/server#9361]
### Steps to reproduce
1. Invite user (isnotspam.org) to meeting
2. Check spam score

### Expected behaviour
Mail should not be classified as spam

### Actual behaviour
Mail is classified as spam

### Server configuration

**Operating system**:
Debian 8

**Web server:**
nginx 1.14

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated over the years

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### isnotspam
<details>
<summary>isnotspam log</summary>
* 3.5 BAYES_99 BODY: Bayes spam probability is 99 to 100% [score: 1.0000]<br/>
* -0.0 SPF_PASS SPF: sender matches SPF record<br/>
* -0.0 RP_MATCHES_RCVD Envelope sender domain matches handover relay domain<br/>
* 0.2 BAYES_999 BODY: Bayes spam probability is 99.9 to 100% [score: 1.0000]<br/>
* 0.1 HTML_MESSAGE BODY: HTML included in message<br/>
* -0.1 DKIM_VALID_AU Message has a valid DKIM or DK signature from author's domain<br/>
* 0.1 DKIM_SIGNED Message has a DKIM or DK signature, not necessarily valid<br/>
* -0.1 DKIM_VALID Message has at least one valid DKIM or DK signature X-Spam-Status: Yes, hits=3.7 required=-20.0 tests=BAYES_99,BAYES_999, DKIM_SIGNED,DKIM_VALID,DKIM_VALID_AU,HTML_MESSAGE,RP_MATCHES_RCVD,SPF_PASS autolearn=no autolearn_force=no version=3.4.0<br/>
X-Spam-Score: 3.7<br/>
</details>

**Comment by tflidd** [comment]
> 3.5 BAYES_99 BODY: Bayes spam probability is 99 to 100% [score: 1.0000]

This is a trained filter on your mail server. It means that the invitation from Nextcloud is too close to spam you have received in the past (or the spam used to train your spam filter). Not sure what Nextcloud could do, if the wording of these mails is not great, we could improve it. Except for that, no HTML mails?

In your case, you could train your mail filter with Nextcloud invitations. Or add an exception for mailserver which is sending out the invitations.

**Comment by janharms** [comment]
I assume editing the invitation template or switching to text only mails could be a solution. As this is the bayes database of isnotspam.org I cannot take influence on this.
Is it possible to edit the tempaltes or switch to text invitations?
Regards

**Comment by MorrisJobke** [comment]
> Is it possible to edit the tempaltes or switch to text invitations?

We added the text-only option to 13.0.2: #9205

**Comment by janharms** [comment]
Thank you. Create timing.
