### ISSUE TITLE
Error when Delete > Restore > Delete again

### ISSUE THREAD

**Issue by olinox14** [nextcloud/server#9362]
Hello,

I had this error with nextcloud v13.0.2:

1. Delete a file or directory via the web interface
2. Go to the trashbin, restore the deleted file or diretory
3. Delete this file / directory again

An error is raised: 'error when deleting the file'

To avoid his error, I had to rename the directory before deleting it.

**Comment by tflidd** [comment]
I tried the demo instance on https://demo13.nextcloud.bayton.org (user/pw: admin/admin) and I could not reproduce this error. So you have to provide a bit more information about your setup and potential logfiles. You might try the demo server yourself, perhaps I did it differently...

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
