### ISSUE TITLE
Share link password error no message

### ISSUE THREAD

**Issue by patricksebastien** [nextcloud/server#9365]
NextCloud 13.2 stable

When sharing a link and entering a very simple password like "fjsdihei" an user is shown a red border with the label Error, but not telling him why (maybe the password is too simple).

![image](https://user-images.githubusercontent.com/441764/39528610-8ead4a0e-4df2-11e8-9bba-a9b70194f871.png)

**Comment by MorrisJobke** [comment]
Works here fine on 13.0.4 if I enforce password protection for links.

![bildschirmfoto 2018-07-04 um 10 08 59](https://user-images.githubusercontent.com/245432/42264948-6ea34824-7f72-11e8-99b1-c8b42a87aa52.png)


If this still happens for you could you please check the nextcloud.log and the web browser console for errors and hints. We are then happy to look into this.
