### ISSUE TITLE
API: vCard group tag X-ADDRESSBOOKSERVER-MEMBER is overwritten (vCard3)

### ISSUE THREAD

**Issue by labor4** [nextcloud/server#9369]
I found that a formerly Apple-specific vCard tag was not well supported in the API of NC.
While filling the array in the search() call, these **identical** properties **overwrite** the preceding.
With it, an API call could also handle full vCard groups.
I thought maybe this should be handled by the official release.

**I get my contacts like:**
$cm = \OC::$server->getContactsManager();
$result = $cm->search("", array("FN"));
return $result;

### Expected behaviour
**I wish NC to maintain multiple "X-ADDRESSBOOKSERVER-MEMBER" entries in an array:**
(stupid example, but is more or less the raw vCard)

    [16] => stdClass Object
        (
            [URI] => 11aceea3-ed03-45ac-8fbc-2143338b08d4.vcf
            [VERSION] => 3.0
            [PRODID] => -//Apple Inc.//AddressBook 10.0//EN
            [N] => MyGroupName
            [FN] => MyGroupName
            [X-ADDRESSBOOKSERVER-KIND] => group
            [X-ADDRESSBOOKSERVER-MEMBER] => urn:uuid:-----UUID1-----
            [X-ADDRESSBOOKSERVER-MEMBER] => urn:uuid:-----UUID2-----
            [X-ADDRESSBOOKSERVER-MEMBER] => urn:uuid:-----UUID3-----
            [REV] => 2017-04-16T19:45:36Z
            [UID] => 11aceea3-ed03-45ac-8fbc-2143338b08d4
            [addressbook-key] => 4
        )

### Actual behaviour
**Instead it is overwritten by the foreach loop of $cm->search()**

    [16] => stdClass Object
        (
            [URI] => 11aceea3-ed03-45ac-8fbc-2143338b08d4.vcf
            [VERSION] => 3.0
            [PRODID] => -//Apple Inc.//AddressBook 10.0//EN
            [N] => MyGroupName
            [FN] => MyGroupName
            [X-ADDRESSBOOKSERVER-KIND] => group
            [X-ADDRESSBOOKSERVER-MEMBER] => urn:uuid:-----JUSTONEUUID-----
            [REV] => 2017-04-16T19:45:36Z
            [UID] => 11aceea3-ed03-45ac-8fbc-2143338b08d4
            [addressbook-key] => 4
        )

**Nextcloud version:** 
13

**vCard3/vCard4**
I read that the repetition of X-ADDRESSBOOKSERVER-MEMBER is for vCard3, 
whereas for vCard4 it is an array called MEMBER
Seen [here](https://www.davdroid.com/manual/supported-contact-fields/)
(Search for "X-ADDRESSBOOKSERVER-MEMBER")

greetings
manu

**Comment by labor4** [comment]
I found this issue to be not server, but the DAV app.
Responsibe function is vCard2Array() in "AddressBookImpl.php".
Would this easy fix be acceptable?

My modified function looks like this, I added an IF clause for "X-ADDRESSBOOKSERVER-MEMBER"

	protected function vCard2Array($uri, VCard $vCard) {
		$result = [
			'URI' => $uri,
		];

		foreach ($vCard->children() as $property) {
			if ($property->name === 'PHOTO' && $property->getValueType() === 'BINARY') {
				$url = $this->urlGenerator->getAbsoluteURL(
					$this->urlGenerator->linkTo('', 'remote.php') . '/dav/');
				$url .= implode('/', [
					'addressbooks',
					substr($this->addressBookInfo['principaluri'], 11), //cut off 'principals/'
					$this->addressBookInfo['uri'],
					$uri
				]) . '?photo';

				$result['PHOTO'] = 'VALUE=uri:' . $url;

			} else if ($property->name === 'X-SOCIALPROFILE') {
				$type = $this->getTypeFromProperty($property);

				// Type is the social network, when it's empty we don't need this.
				if ($type !== null) {
					if (!isset($result[$property->name])) {
						$result[$property->name] = [];
					}
					$result[$property->name][$type] = $property->getValue();
				}

			} else if ($property->name === 'X-ADDRESSBOOKSERVER-MEMBER') {
				$type = $this->getTypeFromProperty($property);

				// Type is the social network, when it's empty we don't need this.
				if ($type !== null) {
					if (!isset($result[$property->name])) {
						$result[$property->name] = [];
					}
					$result[$property->name][$type] = $property->getValue();
				}

			// The following properties can be set multiple times
			} else if (in_array($property->name, ['CLOUD', 'EMAIL', 'IMPP', 'TEL', 'URL'])) {
				if (!isset($result[$property->name])) {
					$result[$property->name] = [];
				}

				$result[$property->name][] = $property->getValue();

			} else {
				$result[$property->name] = $property->getValue();
			}
		}

		if ($this->addressBookInfo['principaluri'] === 'principals/system/system' &&
			$this->addressBookInfo['uri'] === 'system') {
			$result['isLocalSystemBook'] = true;
		}
		return $result;
	}

**Comment by MorrisJobke** [comment]
cc @georgehrke @rullzer

**Comment by labor4** [comment]
BTW:
Same Function: Some $property have a TYPE. In the case of TEL it is something like "WORK,Pref" or "HOME"
My suggestion is foremost, to relate this whole string without going deep, to the $property->name.
I use the following code for my app, but a loose "append" to the array is probably not at all failsafe. better use a fixed index.
this code below produces:
`
"TEL" = array("123456","7890123");
"TEL-TYPES" = array("WORK","HOME");
`
I dont know the use of this function in your system, it may be hooked strongly, so I didn't try to investigate a complete rewrite.


			} else if (in_array($property->name, ['CLOUD', 'EMAIL', 'IMPP', 'TEL', 'URL', 'X-ADDRESSBOOKSERVER-MEMBER'])) {
				if (!isset($result[$property->name])) {
					$result[$property->name] = [];
				}
				$result[$property->name][] = $property->getValue();

				$type = $this->getTypeFromProperty($property);
				if ($type !== null) {
					$result[$property->name ."-TYPES"][] = $type;
				}

			} else {

**Comment by georgehrke** [comment]
@labor4 Would you mind sending a pull-request for your suggested change please?
That makes discussing diffs much easier. Thx! :)

**Comment by labor4** [comment]
second enhancement via #13186 makes this question obsolete
