### ISSUE TITLE
autocompletion not working when sharing with zimbra drive user

### ISSUE THREAD

**Issue by andreasmalta** [nextcloud/server#9380]
### Steps to reproduce
1. Setup server with Zimbra Drive and add Zimbra users
2. You will see in the user list that the usernames are listed with a long UUID string
3. Using web-interface, try to share a file/folder with a zimbra user, start typing the name

### Expected behaviour
the search autocomplete should suggest possible matches after typing a few letters

### Actual behaviour
It says "No users or groups found for ..."
Users are only listed in the search if I enter the full name or UUID

### Server configuration
**Operating system:** Centos7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.1 (ius)

**Nextcloud version:** 13.0.2

**Where did you install Nextcloud from:** https://download.nextcloud.com

**Signing status:** No errors have been found.

**List of activated apps:** Zimbra Drive

**Are you using an external user-backend, if yes which one:** Zimbra Drive

**Comment by blizzz** [comment]
Please open the issue at the app's repo: https://github.com/ZeXtras/zimbra-drive
