### ISSUE TITLE
Encryption Error 14.0.0.2

### ISSUE THREAD

**Issue by blehmonster** [nextcloud/server#9398]
### Steps to reproduce
1. Upgrade to 14.0.0.2
2. Attempt to manipulate any file or directory
3.

### Expected behaviour
Nextcloud should sync properly

### Actual behaviour
Nextcloud produces the following error on all changed files:

{"reqId":"WuyevZGCz5ZYE3b3oOXDWQAAAAk","level":3,"time":"2018-05-04T17:56:13+00:00","remoteAddr":"96.28.110.155","user":"jim","app":"remote","method":"PUT","url":"\/nextcloud\/remote.php\/dav\/files\/jim\/Etc\/18-04-16%2007-55-47%201664.jpg","message":{"Exception":"Error","Message":"Call to undefined method OC\\Files\\Stream\\Encryption::isDirectoryHandle()","Code":0,"Trace":[{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/lib\/private\/Files\/Stream\/Encryption.php","line":181,"function":"wrapSource","class":"OC\\Files\\Stream\\Encryption","type":"::","args":[null,null,"ocencryption","OC\\Files\\Stream\\Encryption","wb"]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php","line":464,"function":"wrap","class":"OC\\Files\\Stream\\Encryption","type":"::","args":[null,"files\/Etc\/18-04-16 07-55-47 1664.jpg.ocTransferId466239734.part","\/jim\/files\/Etc\/18-04-16 07-55-47 1664.jpg.ocTransferId466239734.part",{"oc_encryption_module":"OC_DEFAULT_MODULE","cipher":"AES-256-CTR","signed":"true"},"jim",{"__class__":"OCA\\Encryption\\Crypto\\Encryption"},{"__class__":"OC\\Files\\Storage\\Home"},{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OC\\Files\\Storage\\Wrapper\\Encryption"},{"__class__":"OC\\Encryption\\Util"},{"__class__":"OC\\Encryption\\File"},"wb",0,0,8192,true]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":298,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":["files\/Etc\/18-04-16 07-55-47 1664.jpg.ocTransferId466239734.part","wb"]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","line":159,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Etc\/18-04-16 07-55-47 1664.jpg.ocTransferId466239734.part","wb"]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1130,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":513,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["files\/jim\/Etc\/18-04-16 07-55-47 1664.jpg",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/XXX\/nextcloud\/remote.php\/dav\/files\/jim\/Etc\/18-04-16%2007-55-47%201664.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/XXX\/nextcloud\/remote.php\/dav\/files\/jim\/Etc\/18-04-16%2007-55-47%201664.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/XXX\/nextcloud\/remote.php\/dav\/files\/jim\/Etc\/18-04-16%2007-55-47%201664.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/XXX\/nextcloud\/remote.php\/dav\/files\/jim\/Etc\/18-04-16%2007-55-47%201664.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/apps\/dav\/lib\/Server.php","line":281,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/remote.php","line":165,"args":["\/home\/jim\/public_html\/XXX\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/home\/jim\/public_html\/XXX\/nextcloud\/lib\/private\/Files\/Stream\/Encryption.php","Line":198,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.3.3 (build 84) (Nextcloud)","version":"14.0.0.2"}

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** mariadb 10.1

**PHP version:** 7.2.5

**Nextcloud version:** 14.0.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** git

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Integrity checker has been disabled. Integrity cannot be verified.
```
</details>

**List of activated apps:**
<details>
<summary>Enabled:
  - comments: 1.4.0
  - dav: 1.5.2
  - encryption: 2.1.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_sharing: 1.6.1
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - lookup_server_connector: 1.2.0
  - oauth2: 1.2.0
  - provisioning_api: 1.4.0
  - sharebymail: 1.4.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.0
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - files_external
  - testing
  - user_ldap</summary>

</details>

**Nextcloud configuration:**
<details>
<summary>{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "airdrawn.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "14.0.0.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2
    }
}</summary>

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** NA

**Operating system:** Mac OSX

#### Web server error log
<details>
<summary>[04/May/2018:14:13:03 -0400] XX.28.110.155 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "PROPFIND /nextcloud/remote.php/dav/files/jim/ HTTP/1.1" 501
[04/May/2018:14:13:14 -0400] XX.28.110.155 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "PROPFIND /nextcloud/remote.php/dav/files/jim/ HTTP/1.1" 557</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>{"reqId":"WuyevZGCz5ZYE3b3oOXDWQAAAAk","level":3,"time":"2018-05-04T17:56:13+00:00","remoteAddr":"96.28.110.155","user":"jim","app":"remote","method":"PUT","url":"\/nextcloud\/remote.php\/dav\/files\/jim\/Etc\/18-04-16%2007-55-47%201664.jpg","message":{"Exception":"Error","Message":"Call to undefined method OC\\Files\\Stream\\Encryption::isDirectoryHandle()","Code":0,"Trace":[{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/lib\/private\/Files\/Stream\/Encryption.php","line":181,"function":"wrapSource","class":"OC\\Files\\Stream\\Encryption","type":"::","args":[null,null,"ocencryption","OC\\Files\\Stream\\Encryption","wb"]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php","line":464,"function":"wrap","class":"OC\\Files\\Stream\\Encryption","type":"::","args":[null,"files\/Etc\/18-04-16 07-55-47 1664.jpg.ocTransferId466239734.part","\/jim\/files\/Etc\/18-04-16 07-55-47 1664.jpg.ocTransferId466239734.part",{"oc_encryption_module":"OC_DEFAULT_MODULE","cipher":"AES-256-CTR","signed":"true"},"jim",{"__class__":"OCA\\Encryption\\Crypto\\Encryption"},{"__class__":"OC\\Files\\Storage\\Home"},{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OC\\Files\\Storage\\Wrapper\\Encryption"},{"__class__":"OC\\Encryption\\Util"},{"__class__":"OC\\Encryption\\File"},"wb",0,0,8192,true]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":298,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":["files\/Etc\/18-04-16 07-55-47 1664.jpg.ocTransferId466239734.part","wb"]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","line":159,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Etc\/18-04-16 07-55-47 1664.jpg.ocTransferId466239734.part","wb"]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1130,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":513,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["files\/jim\/Etc\/18-04-16 07-55-47 1664.jpg",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/XXX\/nextcloud\/remote.php\/dav\/files\/jim\/Etc\/18-04-16%2007-55-47%201664.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/XXX\/nextcloud\/remote.php\/dav\/files\/jim\/Etc\/18-04-16%2007-55-47%201664.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/XXX\/nextcloud\/remote.php\/dav\/files\/jim\/Etc\/18-04-16%2007-55-47%201664.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/XXX\/nextcloud\/remote.php\/dav\/files\/jim\/Etc\/18-04-16%2007-55-47%201664.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/apps\/dav\/lib\/Server.php","line":281,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/home\/jim\/public_html\/XXX\/nextcloud\/remote.php","line":165,"args":["\/home\/jim\/public_html\/XXX\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/home\/jim\/public_html\/XXX\/nextcloud\/lib\/private\/Files\/Stream\/Encryption.php","Line":198,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.3.3 (build 84) (Nextcloud)","version":"14.0.0.2"}</summary>

</details>

**Comment by MartB** [comment]
How did you fix that i ran into the exact same issue on 14.0.2 beta?

**Comment by blehmonster** [comment]
I didn’t, unfortunately. I had to delete the entire installation and reinstall. Worst upgrade bug I’ve ever encountered in any software as it rendered the entire platform useless.

**Comment by MartB** [comment]
#10430 i found the culprit, just temporarily revert the commit i referenced there (or simply edit the file back to the old version)

Someone simply forgot to push a function (stuff happens).

**Comment by TecJon** [comment]
14.0.0.13 produces the same error

**Comment by MorrisJobke** [comment]
cc @nextcloud/encryption

**Comment by TecJon** [comment]
NC 14 beta 4 solved this for me

**Comment by tflidd** [comment]
> NC 14 beta 4 solved this for me

@blehmonster can you confirm and close this issue?

**Comment by blehmonster** [comment]
I cannot confirm as I am no longer running that alpha.  I will defer to TecJon since he's the only other reporter of this issue, and NC14 Beta 4 solved it for him.
