### ISSUE TITLE
Exclude folder/pictures from Gallery

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#9400]
As a privacy enhancement, It would be nice to have an option to exclude a folder/pictures from the gallery image building.

**Comment by monsterpit-daggertooth** [comment]
If you make a file named `.nomedia` in the folder you want to hide, the Gallery app will skip it.

<sup>**Note**: This won't stop Files from creating thumbnails when browsing through it.</sup>

**Comment by stratege1401** [comment]
thx. will do.
