### ISSUE TITLE
How many users can nextcloud create at most?

### ISSUE THREAD

**Issue by xiaoandxiao** [nextcloud/server#9408]
How many users can nextcloud create at most? thanks!

**Comment by MorrisJobke** [comment]
Depends highly on the setup of underlying hardware. The software itself has no limitation build in.

**Comment by tflidd** [comment]
There are large setups:
https://nextcloud.com/blog/tu-berlin-halves-database-load-by-migrating-22k-users-to-nextcloud/

And it should be possible to go beyond that. Here they talk about special prices for subscription plans up to 10 million users: https://nextcloud.com/pricing/

**Comment by bayusangaji** [comment]
May i know about Nextcloud, if i want to use for 100 users its free or not? Thanks

**Comment by yehudaclinton** [comment]
> May i know about Nextcloud, if i want to use for 100 users its free or not? Thanks

if you have you're server the software is free. if you use their hosting there doesn't seem to be a free plan
