### ISSUE TITLE
Faster DAV classification migration

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#941]
https://github.com/owncloud/core/pull/25638

Someone should have a look if we have this.

**Comment by blizzz** [comment]
> Someone should have a look if we have this.

Someone says we do not have these changes incorporated in master.

**Comment by blizzz** [comment]
The original contribution was apprently a direct commit to master :eyes: https://github.com/owncloud/core/commit/e06693e8e72bdc4a540c6f2594c1ea0f87e8e2f4 or do I oversee anything?

**Comment by nickvergessen** [comment]
Well they remove migrations on master, because they dont support version jumping

**Comment by nickvergessen** [comment]
No, the commit is not in master, because they dropped the migration in master:
9.1 is https://github.com/owncloud/core/pull/25638
Master removal is https://github.com/owncloud/core/pull/25654

**Comment by blizzz** [comment]
OK, thanks for clarifying

**Comment by MorrisJobke** [comment]
> OK, thanks for clarifying

That means what? Do we need it or not? Still something we need in 10.0.1 or is 10.0.2 fine with this? What is the impact?

**Comment by LukasReschke** [comment]
=> Without this updates are slow => https://help.nextcloud.com/t/upgrade-issues-with-ldap-enabled/3727/1

**Comment by nickvergessen** [comment]
Yeah for me with 2 users the update already took 3minutes on this repair step

**Comment by MorrisJobke** [comment]
Not an issue anymore with master -> closing
