### ISSUE TITLE
Weird timestamp behavior

### ISSUE THREAD

**Issue by SoulReav0r** [nextcloud/server#9413]
Hi there,

I noticed a very weird behavior on timestamps from files:

Case 1:

### Steps to reproduce
1. Upload a file via Nextcloud-Client

### Expected behaviour
Timestamp should be current time from upload

### Actual behaviour
Timestamp is set to last modified date of the file

Case 2:

### Steps to reproduce
1. Upload a file via Browser

### Expected behaviour
Timestamp should be current time from upload

### Actual behaviour
Timestamp is set 2h in future

Case 3:

### Steps to reproduce
1. Create a file via Browser

### Expected behaviour
Timestamp should be current time from upload

### Actual behaviour
Timestamp is set 2h in future

Server and PHP time are set to UTC. Via ssh "date" shows the correct timestamp.

### Server configuration

**Operating system**:
Ubuntu-Server 4.4.0-122-generic newest apt updates (07.05.2018)

**Web server:**
Apache2 
**Database:**
MariaDB 10.2.14
**PHP version:**
PHP Version 7.0.28-0ubuntu0.16.04.1

**Nextcloud version:** (see Nextcloud admin page)
13.0.2 stable channel
**Updated from an older Nextcloud/ownCloud or fresh install:**
nope
**Where did you install Nextcloud from:**
apt sources

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
</details>

**Nextcloud configuration:**
<details>
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => '***',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'overwrite.cli.url' => '***',
  'dbtype' => 'mysql',
  'version' => '13.0.2.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '****',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'fsr_ei',
  'mail_domain' => '***,
  'mail_smtphost' => '***',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '***',
  'mail_smtppassword' => '***',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 0,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'logtimezone' => 'UTC',
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
nope
**Are you using encryption:** yes/no
nope
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...



### Client configuration
**Browser:**
Chromium 65.0.3325.181 (Offizieller Build) Built on Ubuntu , running on Ubuntu 16.04 (64-Bit)
Firefox 59.0.2 (64-Bit)
**Operating system:**
Ubuntu 16.04.03 Xenial

**Comment by MorrisJobke** [comment]
> Timestamp is set to last modified date of the file

Actually this is the correct behavior. It's the last modified timestamp. Syncing is not modifying the file.

**Comment by MorrisJobke** [comment]
> Timestamp is set 2h in future

Seems that the time zone is wrongly configured somewhere :/
