### ISSUE TITLE
Not possible to post multi line comments anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#942]
Since https://github.com/nextcloud/server/pull/714
Neither `Enter` nor `Shift` + `Enter` work.
Would be nice to get that back @jancborchardt 

The design changes look really good btw.

**Comment by rullzer** [comment]
Yep I noted that in the issue as well.
Maybe we could just catch `CTRL+enter` and then convert to a textarea?

Altough that might be great cross browser fun.

**Comment by jancborchardt** [comment]
It was intentionally changed to single-line comments because it’s intended to be a quick comment function, not writing a whole bunch of text.

**Comment by nickvergessen** [comment]
This is odd, apps that use comments for "longer" context now have to use a different style then the server feature?

**Comment by jancborchardt** [comment]
Right, good point. If you’d like to change it then a few things would be good:

- don’t make it too high, 3 rows maximum
- use https://github.com/jackmoore/autosize so the input field automatically resizes, and remove the resize handle (like we do in the mail app)
- have the icon-confirm button float in the bottom right of the textarea like it does now in the input field
- make Ctrl-Enter submit the comment

Does that sound good?

**Comment by nickvergessen** [comment]
Sounds good :+1:
