### ISSUE TITLE
Set up Global categories as DAV item

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#9422]
- Edit Category global
- Allow to upgrade a Category to a DAV Item (Calendar/Address book)
- Allow other App to add their app there to (e.g. https://github.com/nextcloud/mail could maybe use it for Virtual IMAP-Direcory)
 - Affected Issues:
   - contact: [171](https://github.com/nextcloud/contacts/issues/171)
   - contact: [212](https://github.com/nextcloud/contacts/issues/212)
   - calendar: [708](https://github.com/nextcloud/calendar/issues/708)
   - calendar: [806](https://github.com/nextcloud/calendar/issues/806)
## Mockup
![nextcloudservergroup](https://user-images.githubusercontent.com/7795891/39761189-ba09f2f8-52d7-11e8-8e3c-5dde367d48e6.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/contacts  @nextcloud/calendar Does this make sense?

**Comment by georgehrke** [comment]
> Set up Global Contacts as DAV item

Do you mean categories? 

What's the use-case for this?
Would the admin see all events of a certain category of all users? If yes, that's an absolute no-go. Admins are not supposed to see user's calendars just like that.

**Comment by Mannshoch** [comment]
The idea is not an Admin and User one. It's more a how I would Like to distribute my calendar and contacts.
See my description from [calendar/#806](https://github.com/nextcloud/calendar/issues/806) :

> I use Nextcloud to manage some Familiemembers and their calendar. The crowd of Calendars grow more and more. We also got some Problems with Busines data which should not been shared with third persons.
> The Davdroid accounts on smart-phone and thunder-bird is growing and growing. Now there is the big question to not include all company info on Dates because of data security and privacy or to find a way to include only the interesting data like the availability. Also we got some Problems with Calendar colours. It's got more and more chaotic to identify your own calendar/category entries among the others.

Also you have sometimes to duplicate calendar entries into different calendars because you share your calendar with two people which should only see entries they need to know about but you have calendar entries both are interested in. I plan to share my calendar with my wife. 

Same her also for contacts. If I have a Club with Nextcloud,  I obviously have subscribed their contact list. But some are contacts which are also in the address book from my wife and also, maybe, my child is also in this club, so I have him and other People twice in my list. 

**Categorizing a contact/calendar entry should in my opinion set-up which People have which kind of access to data I own.**

**Comment by georgehrke** [comment]
This is a really specialized feature request, with a very rare use case. Too special imo.

Nextcloud is extensible with it's app system. Nextcloud provides APIs to the calendar and contacts data via it's CalDAV / CardDAV interface + the php Contacts / Calendar API, that allow you to search contacts / events with filters. 

If you really need this, please write your own app for it.

**Comment by PackElend** [comment]
I had a similar request, see #111, what could be solved by this approach as well.
