### ISSUE TITLE
"pages" files are shown as directories.

### ISSUE THREAD

**Issue by danysz** [nextcloud/server#943]
### Steps to reproduce
1. Add a "pages" file to your cloud.
2. On the cloud it will look as a directory.

### Expected behaviour
It should be a "file"

### Actual behaviour
It's acting as a directory.

### Server configuration
**Operating system**: Linux

**Web server:** apache

**Database:** mysql

**PHP version:**

**Nextcloud version:** Nextcloud 9.0.53 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh first time install

**Where did you install Nextcloud from:** official..using the "web installer"

**Signing status:**

**List of activated apps:**

**The content of config/config.php:**

**Are you using external storage, if yes which one:**  not relevant

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** safari / firefox

**Operating system:** Mac OS

**Comment by LukasReschke** [comment]
This is because pages files are in some cases actually directories. See https://support.apple.com/en-us/HT202887

There's not much that we can do. You need to make sure to configure your iWork to use the single file format.

**Comment by danysz** [comment]
Closing the issue before checking is not a nice way .. Anyway my "Pages" application and my specific document is in "Single file" mode already.
