### ISSUE TITLE
Public Sharing

### ISSUE THREAD

**Issue by stone212** [nextcloud/server#9434]
This is either a feature request or a stupid question.

How do I share a document with all users of my server?  I know I can generate a share link and share that.  But is there a way to make a folder Public.  Ideally it would show under ever user's Shared folders under some kind of "Public Shares" subheading.

Thank you.

**Comment by paescuj** [comment]
You might want to take a look at [group folders](https://apps.nextcloud.com/apps/groupfolders).

I'm not sure if this is the right place for such question. I would rather use the [forum](https://help.nextcloud.com/)

**Comment by stone212** [comment]
@paescuj Group Folders does not solve the Issue.  It is basically a feature request for Public Folders as I described.  Feature Reqests are Issues not support tasks so I think this is a better place than the forum.  Do you agree that Feature Requests are Issues?

**Comment by paescuj** [comment]
Just wanted to check out whether group folders would also cover your request. In that case it seems like a real feature request. I agree with you that feature request are issues and think this is the right place. However please consider that I'm not involved in this project.

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low and group folders solves most of the issues many people have. Currently there a no plans to implement this feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
