### ISSUE TITLE
App passwords become invalid when changing main password

### ISSUE THREAD

**Issue by TheAssassin** [nextcloud/server#9439]
### Steps to reproduce
1. Create one or more app passwords
2. Change account password
3. Try to use existing app password

### Expected behaviour

App passwords should continue to work.

### Actual behaviour

They don't work any more, and one is spammed with authentication error message boxes, e.g., when trying to use CardDAV/CalDAV endpoints, or the apps. You need to remove all the passwords manually, then create new ones, and enter them into any device (or, in case of the app, log into Nextcloud again on the device). This is far from user friendly.

### Server configuration

**Nextcloud version:** 13.0.1

Note: I have 2FA activated for my account.

### Details

I could understand that when the main password is changed, all the app passwords are invalidated for security reasons.

However, the user should be told about this, and ideally, the ones that don't work any more are highlighted in some way (e.g., red font color, ...). Deleting them immediately is not a good idea, as the list can be used to see where to update the tokens.

Personally, I don't think a password change should invalidate all the passwords by default. I might for example paste the password I use to log into Nextcloud on some website by accident, so that it is no longer confidential. However, that doesn't mean that the app passwords are insecure. I could simply continue to use the old ones, but change my main password.

But as I don't know how the app passwords are stored and whether they're linked to the main password in some kind, it'd be helpful if you could provide some details on that.

**Comment by brunt82** [comment]
See #2581
