### ISSUE TITLE
[Feature Request] Virtual Directories / Symbolic Links

### ISSUE THREAD

**Issue by fabianfrz** [nextcloud/server#9440]
### Expected behaviour

If I have a directory of images, I would like to be able to share only a subset of images or share files from different directories in a single share so I don't have to create multiple link shares each one protected with a password and valid time. This feature is required to protect personal data while keeping it comfortable for users. It is more or less something like a symbolic link feature.

### Actual behaviour

Multiple shares are needed.

### Server configuration

**Operating system**: Arch Linux

**Web server:** NGINX

**Database:** sqlite

**PHP version:** 7.2

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** Nextcloud Website

```yaml
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - bookmarks
  - checksum
  - encryption
  - files_retention
  - survey_client
  - user_external
  - user_ldap

```

### Client configuration
**Browser:** Firefox 59 (Linux)

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

Just some ideas what needs to be thought of in this regard: it's not as trivial as it seems - starting with the UI, how to handle links to/from shares or external storages and how to avoid loops and other stuff.
