### ISSUE TITLE
Wrong translation affects Activity app

### ISSUE THREAD

**Issue by fgsl** [nextcloud/server#9443]
### Steps to reproduce
1. Install Nextcloud 14
2. Install [Activity](https://github.com/nextcloud/activity) app 
3. Upload a file
4. Share file with a user
5. Open Activity view (icon of a ray like Flash of fourties)

### Expected behaviour
To see a line like: You shared {file} with {user}

### Actual behaviour
You don't see anything

**Nextcloud version:** 14

**Language**: Portuguese/Brazil

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Github master

I described problem in Transifex:

https://www.transifex.com/nextcloud/nextcloud/translate/#pt_BR/files_sharing/101548770?q=text%3A%27You+shared+{file}+with+{user}%27

**Comment by tflidd** [comment]
@rakekniven

**Comment by rakekniven** [comment]
Fixed at Transifex
