### ISSUE TITLE
Accessing a single public share via WebDAV does not work (Internal server error)

### ISSUE THREAD

**Issue by dragetd** [nextcloud/server#9449]
Latest NC 13.
Latest Ubuntu 16.04
PHP: 7.0+35ubuntu6.1

Documentation: https://docs.nextcloud.com/server/13/user_manual/files/access_webdav.html#accessing-public-shares-over-webdav

### Steps to reproduce
Sharing a directory via a link, either setting a password or not setting one.

Trying to access it via WebDAV (testing kio webdavs://<id>@cloud.foo.com/public.php/dav  or uploading using curl -T -u <id>: https://cloud.foo.com/public.php/dav or using -u <id>:<PW>)

Instead of WebDAV access, I get an internal server error.

Accessing users files via WebDAV works.

The internal NC log is spamend with 'Exception: App not installed: 0. {main}'. (Please also improve the logging, this messages does not tell you much at all. And why is so much information hidden? Downloading the log reveals at least *some* insight)
 {"reqId":"DrNuTyusygeHwa2LJKs6","level":3,"time":"2018-05-10T17:26:03+00:00","remoteAddr":"XXX","user":"--","app":"public","method":"PROPFIND","url":"\/public.php\/dav\/","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"App not installed: \",\"Code\":0,\"Trace\":\"#0 {main}\",\"File\":\"\\\/srv\\\/www\\\/cloud.XXX.de\\\/public.php\",\"Line\":72}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) KHTML\/5.43.0 (like Gecko) Konqueror\/5 KIO\/5.43","version":"13.0.2.1"}

**Comment by rullzer** [comment]
It has to be `https://cloud.foo.com/public.php/webdav` I believe... seems the docs lie

**Comment by dragetd** [comment]
Oh dear… you have no idea how much hours I have burned trying to fix/debug this myself. Thank you very much!

I will throw in a PR to fix the docs!

**Comment by rullzer** [comment]
The `/webdav` is the old URL. We don't have a fancy new once for the public endpoint yet (we might at some point).

If you could shoot in a PR for the docs that is appreciated! THNX!
