### ISSUE TITLE
Allow Activity registers actions of share and unshare for circles

### ISSUE THREAD

**Issue by fgsl** [nextcloud/server#9451]
### Steps to reproduce
1. Install Nextcloud 
2. Install Activity App
3. Install Circles App

### Expected behaviour
When a file is shared or unshared for a circle, Activity view must show these actions.

### Actual behaviour
Activity view doesn't show actions of share and unshare for circles.

**Nextcloud version:** 14
**Activity version:** 2.6.1
**Circles version:** 0.13.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install.

**Where did you install Nextcloud from:** Github master.

It's clear that actions won't be registered if Circles app doesn't emit signals for sharing and unsharing and Activity doesn't capture these signals, but this issue will be sent to backlogs of Activity and Circles.

**Comment by MorrisJobke** [comment]
As of https://github.com/nextcloud/server/pull/9463#issuecomment-391456470 this should be implemented inside the circles app itself.
