### ISSUE TITLE
Virtual Hosting?

### ISSUE THREAD

**Issue by kousu** [nextcloud/server#9456]
Is there a way to set up virtual hosting with NextCloud? That is, one install, multiple domains with their own separate data? It seems in theory that, since config.php can specify `datadirectory` as well as the DB credentials, it should be possible to set /var/nextcloud/site{1,2,3}.com/config.php respectively pointing at /var/nextcloud/site{1,2,3}.com/data/ and mysql://localhost/nextcloud_site{1,2,3}, while keeping only a single copy of the codebase in /usr/share/nextcloud/.

My reason for asking is that I installed NextCloud [from Arch](https://www.archlinux.org/packages/community/any/nextcloud/), installing itself to /usr/share/webapps/nextcloud/, and that is great because NextCloud will update itself along with the rest of my system updates now, but I can't see how to have more than one domain running on it. Am I stuck? Do I need to maintain multiple installs manually XOR run multiple servers? Or is only docker supported for this kind of set up?

Does my question make any sense at all? I can see that apps could make it tricky because they would/might be co-managed amongst domain owners. Even if it doesn't make sense now, is there a roadmap to enabling this?

Thanks, and thanks for making NextCloud and helping us all take back our data!

**Comment by rullzer** [comment]
There is the 'NEXTCLOUD_CONFIG_DIR' enviroment variable.

However this is not really supported.
Also note that you have to upgrade all your instances in sync. And if one of them has incompatible apps with a new versions you can't upgrade the others as well.
