### ISSUE TITLE
Remove ownCloud reference from the list of supported backend for files external

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#946]
This page should be fixed to remove all references to ownCloud.
https://github.com/nextcloud/server/blob/master/apps/files_external/lib/Lib/Backend/OwnCloud.php

Unless we need it to connect to very old instances, in which case there should maybe be some additional info such as "(legacy)"

**Comment by LukasReschke** [comment]
https://github.com/nextcloud/server/pull/906 will fix that

**Comment by MorrisJobke** [comment]
Merged and added to the backport -> closing
