### ISSUE TITLE
Does nextcloud support Browser-Based Uploads when using S3?

### ISSUE THREAD

**Issue by C0reFast** [nextcloud/server#9465]
through this api: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingHTTPPOST.html

the files can upload directly to Amazon S3, so it can cause less bandwidth to the server.

**Comment by MorrisJobke** [comment]
As of now this is not supported. Neither in the primary storage nor in external storage. It also would involve a lot of checks if this is possible at all. An example: if you enable server side encryption this feature need to be disabled to have the encryption do it's job.

Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
