### ISSUE TITLE
Can't config memory limt bigger than 512M

### ISSUE THREAD

**Issue by kzhui125** [nextcloud/server#9466]
### Config value

memory limt 2048M
![image](https://user-images.githubusercontent.com/11925432/39969014-9142f5e2-5708-11e8-913d-2799bfbadf17.png)

### Actual behaviour
memory limt is still 512M
![image](https://user-images.githubusercontent.com/11925432/39969001-64aafd86-5708-11e8-93c5-2bc941463485.png)

### Server configuration

**Operating system**: Centos7

**Web server:** apache

**Database:** mysql

**PHP version:** 7.0

**Nextcloud version:**  13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** download from homepage

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.3
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - music: 0.5.6
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'sensitive',
  'passwordsalt' => 'sensitive',
  'secret' => 'sensitive',
  'trusted_domains' =>
  array (
    0 => '192.168.100.104',
    1 => 'sensitive',
  ),
  'datadirectory' => '/var/www/html/nextcloud-data',
  'overwrite.cli.url' => 'http://192.168.100.104/nextcloud',
  'dbtype' => 'mysql',
  'version' => '13.0.2.1',
  'dbname' => 'sensitive',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'sensitive',
  'installed' => true,
  'maintenance' => false,
  'loglevel' => 2,
  'memcache.local' => '\OC\Memcache\APCu',
  'filesystem_check_changes' => 1,
);
```
</details>

**Are you using external storage** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** I have used Webdav

### Client configuration
**Browser:** Chrome

**Operating system:** Win10

**Comment by zorn-v** [comment]
Check `.htaccess` and `php.ini` in nextcloud dir

**Comment by zorn-v** [comment]
You can set it in admin page of nextcloud BTW (if webserver have write access to those files)

**Comment by kzhui125** [comment]
Thank you @zorn-v , it works after changing the .htaccess file.
