### ISSUE TITLE
CSRF in showAuthPickerPage function should be suppressed

### ISSUE THREAD

**Issue by gbrault** [nextcloud/server#9467]
While "you" say 
https://github.com/nextcloud/server/blob/05df524472a93da00fb13c3fd735bf21b0c726ea/core/Controller/ClientFlowLoginController.php#L151
You actually implement it in the body of the function
https://github.com/nextcloud/server/blob/05df524472a93da00fb13c3fd735bf21b0c726ea/core/Controller/ClientFlowLoginController.php#L167

It means web based apps can't use this service, which is "domage"...

Do you have a specific reason to do that or could you suppress it (CSRF test)

Thx

"you" means the Nextcloud programming team: Bravo for the tremendous work!

**Comment by blizzz** [comment]
@gbrault that's not the same thing. The logic only requires  that you set a request header "OCS-APIREQUEST" to "true".

**Comment by rullzer** [comment]
This is done this way because clients and oauth requests need to access that page. But users directly accessing makes no sense.

So all is good.
