### ISSUE TITLE
It'll be nice to have "disable password confirm" option

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/server#9474]
I have app in which users does not know their passwords (nobody knows) - sociallogin. In that app user can be created with generated password.
But sometimes users need to change some options (like email for "forgot password" BTW). In my instance of nexcloud IT IS OK to not ask password for such things.
Why it is compulsorily ?

**Comment by MorrisJobke** [comment]
The social login app then needs to "fake disable" this behavior. As of now this is simply a server timestamp and the app then needs to fake this on every request so that the popup is never triggered because nextcloud thinks the login happened just now and doesn't ask for the password again. I would not allow an admin to disable this, but this needs to be done in the app itself.

Please report it in the repo of that app.

**Comment by zorn-v** [comment]
> Please report it in the repo of that app.

I'm author, but thanks for idea.

**Comment by MorrisJobke** [comment]
I just noticed that for user_saml we disabled this in the server: #7487

cc @schiessle @rullzer @blizzz Should we add this for the social login as well?

**Comment by blizzz** [comment]
As commented there already, i don't like that the backend name is hard coded. We should introduce an interface for this, and than any backend can use it.

**Comment by zorn-v** [comment]
I implemented this option in personal settings in my app. But I think it should be in core.

**Comment by zorn-v** [comment]
Hardcoded check of hardcoded interfaces. 
What I should do if I don't need implement that interface (example - sociallogin app) ?

**Comment by rullzer** [comment]
@zorn-v we improved the user backend handling (see https://github.com/nextcloud/server/tree/master/lib/public/User/Backend)

Probably if we'd add a new interface here. Which doesn't have any functions to implement. But it can tell the server 'ok this backend doesn't support this' then we can take action accordingly.

**Comment by rullzer** [comment]
Well that should work as well I guess... :see_no_evil:

**Comment by zorn-v** [comment]
Yep 😉
