### ISSUE TITLE
[documentation] occ log:file

### ISSUE THREAD

**Issue by y0va** [nextcloud/server#9477]
There is an error in the documentation:

https://docs.nextcloud.com/server/13/admin_manual/configuration_server/occ_command.html#logging-commands

It should read
> sudo -u www-data php occ log:file

instead of

> sudo -u www-data php occ log:owncloud

**Comment by MorrisJobke** [comment]
cc @MariusBluem

**Comment by MorrisJobke** [comment]
Fixed in https://github.com/nextcloud/documentation/pull/801
