### ISSUE TITLE
An internal server error occurred. Please try again later when logging in as AD user but not for local user

### ISSUE THREAD

**Issue by FathiBenNasr** [nextcloud/server#9478]
Hello,
I have an issue, whenever I connect as an Active Directory, I get an "An internal server error occurred. Please try again later." I have yo retry several times or more to get connected, while I could connect from the first attempt as a local user. My AD has ~ 5K users but is an oversized server (rapid raid discs, plenty of ram and cpu waiting for requests); I also tweaked my ldap query to return less than 800 users (those who have opened a domain session in the last three months). But, neither my apache log nor my nextcloud logs contains errors. I would like to increase ldap timeouts to see if this is the problem but don't know how. I also use Redis and APCu as caches, so ldap resuluts should be cached after the first attempt. I don't really know where is the problem and would like some hints for debugging.
TIA

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

But maybe @blizzz can give a little advice upfront.

**Comment by blizzz** [comment]
> "An internal server error occurred. Please try again later." 

Should always create output log. if nothing is in nextcloud.log, the webserver's error.log could be a place, but I would not expect that. The forums, as @MorrisJobke pointed to, is the proper place to discuss it. Or paid support ;)
