### ISSUE TITLE
Update to Nextcloud 10 RC1 shows ownCloud 10 RC1

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/server#948]
I think there is any issue/pr about that already, but i could not find it here 😁 ...or is it a bug with the german translation?!

<img width="603" alt="owncloud_instead_of_nextcloud" src="https://cloud.githubusercontent.com/assets/19711361/17789335/21bea572-6592-11e6-9d08-a9979833ee27.png">

cc @MorrisJobke @LukasReschke

**Comment by blizzz** [comment]
Possibly wrong within the German translation.

**Comment by rullzer** [comment]
Nope just something we did not change properly on stable10. PR incomming.

**Comment by mar1u5** [comment]
Fixed in #957 :facepunch: THX @rullzer
