### ISSUE TITLE
Collabora Online,edit error

### ISSUE THREAD

**Issue by qq8554650** [nextcloud/server#9486]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
enable Collabora Online with app
click doc or create new doc,nextcloud.log log that(then apache log no error) 
web display
内部服务器错误
服务器不能完成你的请求。

如果再次发生，请在下方将技术详情发送给服务器管理员。

更多细节可以在服务器日志中找到.

技术细节
远程地址: 114.242.94.218
请求 ID: Wvvje55EtLxkjamk6tXjwgAAAAM

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:centos7.5

**Web server:http://218.93.116.208:11080/

**Database:sqlite

**PHP version:PHP 7.1.17(7.2.5)

**Nextcloud version:13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:fresh install

**Where did you install Nextcloud from:download zip from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>{"reqId":"Wvvf7JqGJFJTHA9DF4P14QAAAAQ","level":3,"time":"2018-05-16T07:38:21+00:00","remoteAddr":"114.242.94.218","user":"user1","app":"richdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/public?shareToken=2ZXXr37z25kJ4mx&fileName=%E5%BA%94%E8%81%98%E9%A1%B9%E7%9B%AE%E6%80%BB%E7%9B%91%E7%86%8A%E6%B0%B8%E8%BF%9B.doc&requesttoken=8OVLRZRF1H3eE8AzRDWnEdJc4RaxKpzfjcpCpYHXqMY%3D%3Axa8zM9ARjhXva5BUCwLkSKQzhT3CeayYzL8U4%2FmEkbU%3D&fileId=%7BfileId%7D","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\RequestException\",\"Message\":\"cURL error 3: <url> malformed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(103): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\RingException))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(*** sensitive parameters replaced ***)\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/var\\\/www\\\/html\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/var\\\/www\\\/html\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/var\\\/www\\\/html\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/var\\\/www\\\/html\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(138): GuzzleHttp\\\\Client->get('\\\/hosting\\\/discov...', Array)\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/richdocuments\\\/lib\\\/WOPI\\\/DiscoveryManager.php(84): OC\\\\Http\\\\Client\\\\Client->get('\\\/hosting\\\/discov...')\\n#10 \\\/var\\\/www\\\/html\\\/apps\\\/richdocuments\\\/lib\\\/WOPI\\\/Parser.php(41): OCA\\\\Richdocuments\\\\WOPI\\\\DiscoveryManager->get()\\n#11 \\\/var\\\/www\\\/html\\\/apps\\\/richdocuments\\\/lib\\\/TokenManager.php(133): OCA\\\\Richdocuments\\\\WOPI\\\\Parser->getUrlSrc('application\\\/msw...')\\n#12 \\\/var\\\/www\\\/html\\\/apps\\\/richdocuments\\\/lib\\\/Controller\\\/DocumentController.php(243): OCA\\\\Richdocuments\\\\TokenManager->getToken(*** sensitive parameters replaced ***)\\n#13 [internal function]: OCA\\\\Richdocuments\\\\Controller\\\\DocumentController->publicPage('2ZXXr37z25kJ4mx', '\\\\xE5\\\\xBA\\\\x94\\\\xE8\\\\x81\\\\x98\\\\xE9\\\\xA1\\\\xB9\\\\xE7\\\\x9B\\\\xAE\\\\xE6\\\\x80\\\\xBB...', '{fileId}')\\n#14 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Richdocuments\\\\Controller\\\\DocumentController), 'publicPage')\\n#16 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Richdocuments\\\\Controller\\\\DocumentController), 'publicPage')\\n#17 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Richdocumen...', 'publicPage', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#20 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/richdocum...')\\n#21 \\\/var\\\/www\\\/html\\\/index.php(37): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":51}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.140 Safari\/537.36 Edge\/17.17134","version":"13.0.2.1"}
</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
This seems to be a problem in the collabora app - please report there: https://github.com/nextcloud/richdocuments/issues
