### ISSUE TITLE
Customizable scheme for login flow

### ISSUE THREAD

**Issue by neben** [nextcloud/server#9487]
It would be nice to be able to customize the scheme for the login flow [1]. Currently, it is fixed to the `nc` scheme. This prevents any web app from using this login flow, as web browsers prevent arbitrary scheme registrations [2]. Only schemes starting with `web+` or from a whitelist are allowed.

[1] https://docs.nextcloud.com/server/13/developer_manual/client_apis/LoginFlow/index.html  
[2] https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

**Comment by juliushaertl** [comment]
@rullzer

**Comment by mario** [comment]
@rullzer perhaps we move to web+nc, that way we've solved the problem? :)

**Comment by neben** [comment]
@mario that would be great!

**Comment by neben** [comment]
Any progress on this? Is there anything I can do to help?

**Comment by skjnldsv** [comment]
What is the status here? Does it still make sense?
Do we want to do that?

cc @tobiasKaminsky :)

**Comment by tobiasKaminsky** [comment]
This is independent from me/client.
For regular NC we do not need this.
For branding we could change this, if needed, but never did it.

@neben what is your desired use case?
It should be possible to catch the url from redirect header, if you want to receive the nc:// url within your web app.

**Comment by skjnldsv** [comment]
@tobiasKaminsky ok! And do you have an opinion on this? Do you think it make sense? :)

**Comment by tobiasKaminsky** [comment]
Not sure as I do not fully understand the use case…

**Comment by neben** [comment]
> @neben what is your desired use case?
> It should be possible to catch the url from redirect header, if you want to receive the nc:// url within your web app.

Our use case is to have OAuth-like functionality, so our client-side web app can integrate NextCloud  file storage (to offer our users an alternative to Dropbox and Google Drive, which we support via OAuth 2/OpenID Connect). The login flow looked like an alternative, but has several drawbacks.

1. We have a web app, running in a browser. The NextCloud login flow redirects to the `nc://` URL scheme, which cannot be registered by a web app. So I'm not sure if I understand you correctly about catching the URL, @tobiasKaminsky, because I don't think it's possible.
2. IMO the NextCloud login flow is (or at least can be) insecure on mobile devices. Any app can register custom URL schemes, and  then steal the credentials (see for example [this Usenix talk](https://www.usenix.org/sites/default/files/conference/protected-files/usenixsecurity17_slides_gang_wang.pdf)). Also if I'm not mistaken, the [HTML standard](https://html.spec.whatwg.org/multipage/system-state.html#security-and-privacy) itself forbids the use of custom URL schemes delivering credentials to handler sites: 
> Leaking credentials. User agents must never send username or password information in the URLs that are escaped and included sent to the handler sites. User agents may even avoid attempting to pass to Web-based handlers the URLs of resources that are known to require authentication to access, as such sites would be unable to access the resources in question without prompting the user for credentials themselves (a practice that would require the user to know whether to trust the third-party handler, a decision many users are unable to make or even understand).

So summarizing, I think the best option would be to drop the login flow and replace it with a standard-conform OAuth2/OpenID Connect Flow.

**Comment by tobiasKaminsky** [comment]
> 2\. O the NextCloud login flow is (or at least can be) insecure on mobile devices. Any app can register custom URL schemes, and  then steal the credentials (see for example [this Usenix talk](https://www.usenix.org/sites/default/files/conference/protected-files/usenixsecurity17_slides_gang_wang.pdf)).

We use this in an own webView that does not expose the link to any other app. For this it would have been sent as an intent so that other apps can receive it.
Also we do not cache/store anything related to this webview.

**Comment by tobiasKaminsky** [comment]
Also weblogin flow is not only about oAuth/openId, but you can use with that 2fa or any other NC supported auth system without having to implement this is in all clients.

**Comment by tobiasKaminsky** [comment]
@rullzer security wise

**Comment by rullzer** [comment]
@neben as @tobiasKaminsky pointed out the login flow was written for the clients. There they limit the url handler to the webview that is shown (so even if another app register it).

We do support OAuth2. And you can register your apps in the admin security panel.
Note that we do not support the implict grant type (as it is deprecated and should not longer be used)

I am looking into support PKCE properly. Which could at some point serve as replacement of the login flow.

The main issue I'm facing is that we do not have a list of known client ids.
So lets say I want to link up your webapp to my nextcloud. I do not first want to generate a client id send that to you to use etc.

The idea I had was to enforce the client id to be equal to the domain the redirect is send to. So I would see 

'Grant https://awesome.app access to your data'

And in the overview of clients I would see 'https://awesome.app'

But this is for now all still thoughts in my head instead of concrete code.

**Comment by neben** [comment]
@rullzer Just to sum up what we talked about at NextCloud Conf, ATM we're fine with the login flow v2. Once PKCE is implemented in NextCloud, we'll be happy to switch to that and give feedback.

**Comment by juliushaertl** [comment]
@neben I guess this can be closed then?

**Comment by neben** [comment]
@juliushaertl sure, thanks!
