### ISSUE TITLE
Theming does not longer show right Name and Slogan after upgrade to 10 RC1

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/server#949]
### Expected behaviour
Shows Name of your Cloud and Slogan

### Actual behaviour
It shows the standard Nextcloud name and slogan, even when the name etc. was set

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.0.9
**Nextcloud version:** (see Nextcloud admin page)
10.0 RC1
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 9.0.53

### Client configuration
**Browser:**
Safari, Firefox
**Operating system:**
OS X El Capitan

cc @juliushaertl @jancborchardt

**Comment by juliushaertl** [comment]
This is also happening on master.
Looks like it happend after merging #796, i'll have a look later today.

**Comment by LukasReschke** [comment]
> i'll have a look later today.

🚀

**Comment by juliushaertl** [comment]
Fixed with #971 
backported to stable10 #972
