### ISSUE TITLE
shared folder do not sync in one direction

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/server#9498]
### Steps to reproduce
1. Share folder in version 11.x.x (currentverion 13.0.2) with group
2. I share the folder, and if I update something it is synced
3. If the other person add something I do not see it in my folder

### Expected behaviour
Files and Folders should be shown also in my folder

### Actual behaviour
Files and folder from other persons a not shown in my folder

### Server configuration

**Operating system**:
Official Docker FPM

**Web server:**

**Database:**
mysql

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
installation exists since 11.x.x and takes all version without 13.0.0

**Where did you install Nextcloud from:**
Docker reposotory

#### Nextcloud log (data/nextcloud.log)
No logs appear in admin panel

**Comment by MorrisJobke** [comment]
Could it be that the propagation does not fully work for old shares?

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
