### ISSUE TITLE
Add new log_type GELF

### ISSUE THREAD

**Issue by colttt** [nextcloud/server#95]
Hello,

it would be very nice if you add GELF support (http://docs.graylog.org/en/2.0/pages/gelf.html) for logging, also the outputformat (like apache access-logs) to customize the logs. Please also add Log-server address+Port

best regards

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Comment by MEitelwein** [comment]
Would be really useful to have this
