### ISSUE TITLE
porblems with renaming folders in group folder

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/server#9501]
### Steps to reproduce
1. Creating group folder
2. Upload Folder via Linux desktop client
3. Rename the file on PC

### Expected behaviour
Rename the folder on server

### Actual behaviour
Sync from client to server throws an error an do not sync. I got different erros, the last one was an "CSync failed to access subfolder/subsubfolder" 

### Server configuration

**Operating system**:
Official Docker container version 13.0.2-fpm

**Web server:**

**Database:**
MySQL

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
11.x.x (was the first installation) last update was from 13.0.1 but folder was created with version 13.0.2

**Where did you install Nextcloud from:**
Docker repository

**Signing status:**
No error have be found

**List of activated apps:**
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - drawio: 0.8.9
  - encryption: 2.0.0
  - end_to_end_encryption: 1.0.5
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.8.1
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - piwik: 0.4.1
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - ransomware_protection: 1.1.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_diaspora: 1.0.2
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - spreed: 3.2.1
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - twofactor_u2f: 1.5.5
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
Disabled:
  - files_accesscontrol
  - files_automatedtagging
  - notes
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.dropanote.de",
            "192.168.178.39"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.dropanote.de",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 2
        },
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "maintenance": false,
        "loglevel": 3,
        "theme": "",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "app.mail.imaplog.enabled": false,
        "app.mail.smtplog.enabled": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
I have includes a ftp sever file, but do not work, so is not really in use

**Are you using encryption:** yes/no
yes

### Client configuration
**Browser:**
Desktop Sync Client
**Operating system:**
Ubuntu 18.04
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
{"reqId":"Ejk6WutDYcMQlLjtFd49","level":3,"time":"2018-05-17T08:43:51+00:00","remoteAddr":"172.17.0.1","user":"wolle","app":"core","method":"MOVE","url":"\/remote.php\/dav\/files\/wolle\/valyriot\/website\/leitfaden_admin_tool%C3%B6","message":"unable to rename, file does not exists : __groupfolders\/1\/website\/leitfaden_admin_tool\u00f6","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.2.1"}
{"reqId":"XzYl0KzNXBX0yQoHLham","level":3,"time":"2018-05-17T08:44:32+00:00","remoteAddr":"172.17.0.1","user":"wolle","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/files\/wolle\/valyriot\/website\/backup\/leitfaden.md","message":"Could not find mount point, can't keep encryption keys","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.2.1"}
{"reqId":"HN1cPsp2xZ3hsFqKqxNA","level":3,"time":"2018-05-17T08:44:33+00:00","remoteAddr":"172.17.0.1","user":"wolle","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/files\/wolle\/valyriot\/website\/backup\/pictures\/navigation.png","message":"Could not find mount point, can't keep encryption keys","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.2.1"}
{"reqId":"jVCSxxmtkVi0y9AqExIh","level":3,"time":"2018-05-17T08:44:33+00:00","remoteAddr":"172.17.0.1","user":"wolle","app":"core","method":"MOVE","url":"\/remote.php\/dav\/files\/wolle\/valyriot\/website\/leitfaden_admin_tool%C3%B6","message":"unable to rename, file does not exists : __groupfolders\/1\/website\/leitfaden_admin_tool\u00f6","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.2.1"}
{"reqId":"LkqgRutrI5wN7g7EEfzh","level":3,"time":"2018-05-17T08:45:12+00:00","remoteAddr":"172.17.0.1","user":"wolle","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/files\/wolle\/valyriot\/website\/backup\/pictures\/add_new_elements.png","message":"Could not find mount point, can't keep encryption keys","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.2.1"}
{"reqId":"y48SpcOSnWdLB8he5SZy","level":3,"time":"2018-05-17T08:45:12+00:00","remoteAddr":"172.17.0.1","user":"wolle","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/files\/wolle\/valyriot\/website\/backup\/pictures\/admin_teaser.png","message":"Could not find mount point, can't keep encryption keys","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.2.1"}
{"reqId":"4NDDRkeCE22eKiaUghRs","level":4,"time":"2018-05-17T08:45:41+00:00","remoteAddr":"172.17.0.1","user":"wolle","app":"webdav","method":"DELETE","url":"\/remote.php\/webdav\/valyriot\/website\/leitfaden_admin_tool_b","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"path needs to be relative to the system wide data folder and point to a user specific file\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(253): OC\\\\Encryption\\\\Util->getUidAndFilename('\\\/__groupfolders...')\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(169): OC\\\\Encryption\\\\Keys\\\\Storage->getFileKeyDir('', '\\\/__groupfolders...')\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(306): OC\\\\Encryption\\\\Keys\\\\Storage->deleteAllFileKeys('\\\/__groupfolders...')\\n#3 [internal function]: OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->rmdir('__groupfolders\\\/...')\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(273): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(208): OCA\\\\Files_Trashbin\\\\Storage->doDelete('__groupfolders\\\/...', 'rmdir')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Jail.php(95): OCA\\\\Files_Trashbin\\\\Storage->rmdir('__groupfolders\\\/...')\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(91): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Jail->rmdir('website\\\/leitfad...')\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/PermissionsMask.php(108): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rmdir('website\\\/leitfad...')\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(91): OC\\\\Files\\\\Storage\\\\Wrapper\\\\PermissionsMask->rmdir('website\\\/leitfad...')\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(1148): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rmdir('website\\\/leitfad...')\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(346): OC\\\\Files\\\\View->basicOperation('rmdir', '\\\/valyriot\\\/websi...', Array)\\n#12 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(303): OC\\\\Files\\\\View->rmdir('\\\/valyriot\\\/websi...')\\n#13 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#14 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('valyriot\\\/websit...')\\n#15 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#17 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#18 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#20 \\\/var\\\/www\\\/html\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Encryption\\\/Util.php\",\"Line\":235}","userAgent":"gvfs\/1.36.1","version":"13.0.2.1"}
{"reqId":"lshjFO0cg8WJVE0AdQFO","level":4,"time":"2018-05-17T08:58:19+00:00","remoteAddr":"172.17.0.1","user":"wolle","app":"webdav","method":"MOVE","url":"\/remote.php\/webdav\/valyriot\/website\/backup","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"path needs to be relative to the system wide data folder and point to a user specific file\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(347): OC\\\\Encryption\\\\Util->getUidAndFilename('\\\/__groupfolders...')\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(274): OC\\\\Encryption\\\\Keys\\\\Storage->getPathToKeys('\\\/__groupfolders...')\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(282): OC\\\\Encryption\\\\Keys\\\\Storage->renameKeys('\\\/__groupfolders...', '\\\/__groupfolders...')\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(160): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->rename('__groupfolders\\\/...', '__groupfolders\\\/...')\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Jail.php(280): OCA\\\\Files_Trashbin\\\\Storage->rename('__groupfolders\\\/...', '__groupfolders\\\/...')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(276): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Jail->rename('website\\\/backup', 'website\\\/leitfad...')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/PermissionsMask.php(91): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rename('website\\\/backup', 'website\\\/leitfad...')\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(276): OC\\\\Files\\\\Storage\\\\Wrapper\\\\PermissionsMask->rename('website\\\/backup', 'website\\\/leitfad...')\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(806): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rename('website\\\/backup', 'website\\\/leitfad...')\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Node.php(138): OC\\\\Files\\\\View->rename('\\\/valyriot\\\/websi...', '\\\/valyriot\\\/websi...')\\n#10 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Node->setName('leitfaden_admin')\\n#11 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(642): Sabre\\\\DAV\\\\Tree->move('valyriot\\\/websit...', 'valyriot\\\/websit...')\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#15 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/html\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Encryption\\\/Util.php\",\"Line\":235}","userAgent":"gvfs\/1.36.1","version":"13.0.2.1"}
{"reqId":"HgB6s1WngSev0gFEzMHt","level":4,"time":"2018-05-17T08:58:50+00:00","remoteAddr":"172.17.0.1","user":"wolle","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/files\/wolle\/valyriot\/website\/backup","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"path needs to be relative to the system wide data folder and point to a user specific file\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(253): OC\\\\Encryption\\\\Util->getUidAndFilename('\\\/__groupfolders...')\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(169): OC\\\\Encryption\\\\Keys\\\\Storage->getFileKeyDir('', '\\\/__groupfolders...')\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(306): OC\\\\Encryption\\\\Keys\\\\Storage->deleteAllFileKeys('\\\/__groupfolders...')\\n#3 [internal function]: OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->rmdir('__groupfolders\\\/...')\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(273): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(208): OCA\\\\Files_Trashbin\\\\Storage->doDelete('__groupfolders\\\/...', 'rmdir')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Jail.php(95): OCA\\\\Files_Trashbin\\\\Storage->rmdir('__groupfolders\\\/...')\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(91): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Jail->rmdir('website\\\/leitfad...')\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/PermissionsMask.php(108): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rmdir('website\\\/leitfad...')\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(91): OC\\\\Files\\\\Storage\\\\Wrapper\\\\PermissionsMask->rmdir('website\\\/leitfad...')\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(1148): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->rmdir('website\\\/leitfad...')\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Files\\\/View.php(346): OC\\\\Files\\\\View->basicOperation('rmdir', '\\\/valyriot\\\/websi...', Array)\\n#12 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(303): OC\\\\Files\\\\View->rmdir('\\\/valyriot\\\/websi...')\\n#13 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#14 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(637): Sabre\\\\DAV\\\\Tree->delete('files\\\/wolle\\\/val...')\\n#15 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#17 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#18 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#20 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#21 \\\/var\\\/www\\\/html\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Encryption\\\/Util.php\",\"Line\":235}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.2.1"}
{"reqId":"sxYTdKr0ess52g4oOzqf","level":3,"time":"2018-05-17T09:03:30+00:00","remoteAddr":"172.17.0.1","user":"wolle","app":"PHP","method":"GET","url":"\/core\/preview.png?file=%2Fvalyriot%2Fwebsite%2Fbackup%2Fleitfaden.md&c=d930106af74398db2934ca859291042f&x=32&y=32&forceIcon=0","message":"fopen(\/var\/www\/html\/data\/__groupfolders\/1\/website\/backup\/leitfaden.md): failed to open stream: No such file or directory at \/var\/www\/html\/lib\/private\/Files\/Storage\/Local.php#282","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.2.1"}

**Comment by CordlessWool** [comment]
I toke a look to the file system on the server, I there are shown two folder in the web interface that are not shown on the filesystem

**Comment by CordlessWool** [comment]
I have the same error with an other folder today, it seems to be happen, if I rename the folder, before it was completely synced

**Comment by MorrisJobke** [comment]
looks like an issue with encryption and group folders - cc @nextcloud/encryption @icewind1991
