### ISSUE TITLE
Share link suggestion: default expiration date and maximum expiration date

### ISSUE THREAD

**Issue by fa-ribeiro** [nextcloud/server#9510]
Our organization defined 7 days as a reasonable period to keep shares available; however, in some cases, we need to extend shares up to 30 days.

To implement this, we defined a default expiration date = 30 days (in Admin -> Sharing Settings) and asked users to change it to 7 days, unless absolutely necessary more time.

Of course, almost no one changes the expiration date and all shares are available for the default/maximum expiration date ...

So, I think it would be great to have a default expiration date and a maximum expiration date :-)

Thus, we could help users by suggesting a reasonable sharing period (ex: 7 days) by default but also give some flexibility within established limits (ex: 30 days).

I imagine this would be possible by creating a "maximum expiration date" setting to complement the already existing "default expiration date".

For example:

- Admin -> Sharing Settings:
  - default expiration date : 7 days.
  - maximum expiration date: 30 days.

Expected behavior:

- User shares by link;
  - expiration date automatically is set to now + default_expiration_date;
  - user can change expiration date up to maximum_expiration_date;

What do you think?

It is possible to go even further and let users define their own personal "default expiration date", within the "maximum expiration date" defined by the administrator :-)

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing

**Comment by eengstrom** [comment]
On additional element to the OPs suggestions:  "Enforce Expiration Dates" as an admin option, parallel to "Enforce Password Protection".  The latter has requirements for password policies ("Security" section), and the same could be done with the OPs suggestion for "Default" and Maximum" expiration dates.  In this way, administrators can __require__ expiration dates and set a max bound.

**Comment by joshtrichards** [comment]
Fixed in #17725 
Documented in nextcloud/documentation#3019

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/file_sharing_configuration.html#distinguish-between-max-expiration-date-and-default-expiration-date
