### ISSUE TITLE
external storage (SMB) slow

### ISSUE THREAD

**Issue by Af0x** [nextcloud/server#9511]
hello,
I added an external samba to my cloud and first of all it is very slow if I try to access it via webdav from a desktop client.
Edit: The problem is the option "Check for changes". As I set it to never, it loads very fast.

Nextcloud 13.0.2

Regards,

Af0x

**Comment by migueltg** [comment]
+1 here

**Comment by MorrisJobke** [comment]
> I added an external samba to my cloud and first of all it is very slow if I try to access it via webdav from a desktop client.
> Edit: The problem is the option "Check for changes". As I set it to never, it loads very fast.

That's by design. If it needs to check on every request for changes then it is slow. You could try out the notify configuration to work around this, but this needs to be supported by your SMB server: 
https://docs.nextcloud.com/server/13/admin_manual/configuration_files/external_storage/smb.html#smb-update-notifications

**Comment by Af0x** [comment]
I am using a linux smb-server, so this is not possible I guess.
what I don´t understand: why does it have to check the whole smb-share? why can´t it check the currently accessed folder. I have like 5000 files in my share so the check takes ages when cheking all of them.

**Comment by MorrisJobke** [comment]
> what I don´t understand: why does it have to check the whole smb-share? why can´t it check the currently accessed folder. I have like 5000 files in my share so the check takes ages when cheking all of them.
> Even when mounting only a specific folder of a share it seems it checks the whole share.

Because then you never know if a subfolder has changed and the clients then would never know about this change in a sub sub sub sub folder.

**Comment by Af0x** [comment]
on my setup it checks on every directory change inside a mounted share. So if it checks anyway on every action, why does it have to know the subfolders already that aren´t displayed yet.
Maybe I think wrong.

**Comment by Af0x** [comment]
maybe a third option involving a cron that automatically syncs the share in an user defined interval would be possible?
