### ISSUE TITLE
OCS / User Provisioning API: New User can assign self to admin group!

### ISSUE THREAD

**Issue by tpiskula** [nextcloud/server#9512]
After playing with the user provisioning api today, I could successfully set an new user, without any group, to the admin group!

### Steps to reproduce
1. Create an new user without groups
2. Set the new users username/password as basic auth in eg. Postman
3. Send request to add said user to admin group
```
  <nextcloud-url>/ocs/v1.php/cloud/users/test/groups \
  -H 'accept: application/json' \
  -H 'authorization: Basic <test-user>' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'ocs-apirequest: true' \
  -d groupid=admin
```
4. wonder why it returns success

### Expected behaviour
Endpoint should check rights before adding user to group

### Actual behaviour
new, empty user can add self to admin group and play with nextcloud

### Server configuration

**Operating system**:
nextcloud docker
**Web server:**
nextcloud docker
**Database:**
mariadb
**PHP version:**
7.1.17
**Nextcloud version:** (see Nextcloud admin page)
13.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
Docker
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Activity	2.6.1	
Auditing / Logging	1.3.0	
Collaborative tags	1.3.0	
Comments	1.3.0	
Custom CSS	1.0.0
Default encryption module	2.0.0	
Deleted files	1.3.0	
Federation	1.3.0	
File sharing	1.5.0	
First run wizard	2.2.1	
Gallery	18.0.0	
Group folders	1.2.0		
Log Reader	2.0.0	
Mail	0.8.1
Markdown Editor	2.0.4		
Metadata	0.6.0
Monitoring	1.3.0	
Nextcloud announcements	1.2.0	
Notifications	2.1.2	
ONLYOFFICE	1.3.0	
Password policy	1.3.0	
Passwords	2018.5.2	
PDF viewer	1.2.1	
Share by mail	1.3.0	
Text editor	2.5.1	
Theming	1.4.1	
Update notification	1.3.0	
Usage survey	1.1.0	
Versions	1.6.0	
Video player	1.2.0	
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Comment by tpiskula** [comment]
adding config report:

```
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'default_language' => 'de',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '/',
  'trusted_domains' => 
  array (
    0 => 'cloud..',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://cloud..',
  'dbtype' => 'mysql',
  'version' => '13.0.2.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextcloud-database',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp..org',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'cloud..',
  'mail_smtpname' => 'noreply@cloud..',
  'mail_smtppassword' => '#{',
  'maintenance' => false,
);
```

**Comment by rullzer** [comment]
Are you sure the user is actually added to the group? The v1.php always returns a http status code of 200.

Check the returned json. It should show an error.

**Comment by tpiskula** [comment]
I have tried to reproduce it today, **it does return an error and the user is not added to the group.**
Must have made a mistake with the auth header yesterday, sorry for rushing this issue.
