### ISSUE TITLE
A file completely disappears after deleting from a group folder

### ISSUE THREAD

**Issue by altokarev** [nextcloud/server#9523]
### Steps to reproduce
1. Create a file in a group folder
2. Delete it using another account

### Expected behaviour
A file should move to trash bin

### Actual behaviour
A file completely disappears 

**Nextcloud version:** 13

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>
<br>
Actually, I unable to locate the file after I deleted it.
<br><br>
And I have some additional question:<br>
- is there any way to manage by admin deleted from group folders files?<br>
- can I restrict deleting the files from group folders somehow?
<br><br>
Thanks in advance!

**Comment by MorrisJobke** [comment]
Known issue of the group folders. There is no versions and trashbin support yet.

https://github.com/nextcloud/groupfolders/issues/50
https://github.com/nextcloud/groupfolders/issues/99
