### ISSUE TITLE
Wrong display of special characters in First Run Wizard

### ISSUE THREAD

**Issue by binarybear-de** [nextcloud/server#9534]
![unbenannt](https://user-images.githubusercontent.com/28809880/40284668-17d8d7ae-5c93-11e8-996d-9cfe80889cb4.PNG)

Some special characters are shown as ASCII-Code (e.g. ' as ASCII#39).
On the bottom of the login page it is working probably.

**Comment by MariusBluem** [comment]
Please reopen this issue in this repo:
https://github.com/nextcloud/firstrunwizard
