### ISSUE TITLE
email notifications not sending

### ISSUE THREAD

**Issue by jazztickets** [nextcloud/server#9536]
I have a user, admin, that has the following settings:
![1](https://user-images.githubusercontent.com/425930/40324629-524d83cc-5cf6-11e8-8af8-b808c1488cd1.png)

Email server settings through gmail:
![2](https://user-images.githubusercontent.com/425930/40324655-61e3448e-5cf6-11e8-9bdb-edf8fdd9335a.png)

The "send email" button works perfect. The test email arrives immediately everytime.

The problem is when i upload a file, i expect an email immediately saying a new file is uploaded. The email is not being sent at all.

### Server configuration

**Operating system**:
Archlinux

**Web server:**
nginx 1.14.0-1

**Database:**
sqlite

**PHP version:**
php 7.2.5-2
php-fpm 7.2.5-2
php-gd 7.2.5-2
php-intl 7.2.5-2
php-sqlite 7.2.5-2

**Nextcloud version:** (see Nextcloud admin page)
nextcloud 13.0.2-1

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
archlinux

**List of activated apps:**
Activity
Auditing / Logging
Collaborative tags
Comments
External storage support
Federation
File sharing
First run wizard
Gallery
Log Reader
Monitoring
Nextcloud announcements
Notifications
Password policy
Share by mail
Text editor
Theming
Update notification
Video player

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Firefox/Chrome latest versions

**Operating system:**
arch linux

#### Nextcloud log (data/nextcloud.log)
[nextcloud.log](https://github.com/nextcloud/server/files/2023743/nextcloud.log)

**Comment by c0fe** [comment]
Try a different distro like centos or Debian. Arch is bleeding edge and depends to have a lot of rough edges.

**Comment by MorrisJobke** [comment]
Unfortunately we can't reproduce this issue and also the log file does not hold any useful information.

Could you check your system logs to see what is happening?

As this seems to be a setup issue I would like to ask you to raise further questions in the forums: https://help.nextcloud.com
