### ISSUE TITLE
Use use email of sharing user in share email

### ISSUE THREAD

**Issue by geromueller** [nextcloud/server#9539]
The share file/folder email has the admin email in the From field. I get emails from users replying the share emails, hoping to reach the user who shared the folder.

**Comment by MorrisJobke** [comment]
@schiessle @rullzer Didn't we had discussions about this? 

The code says that we add a "reply-to" header with the sharers email address: https://github.com/nextcloud/server/blob/339e32006479daf9e11152c386c34e6b2d757cf2/lib/private/Share20/Manager.php#L757-L761

@geromueller Could you check the email for the reply-to header? If it is in there it's a problem of the mail client to not use this properly.

**Comment by skjnldsv** [comment]
Old digging! :)
We apparently use the sender email if set. Otherwise the admin mail is used!

**Comment by rullzer** [comment]
So we can't set the initiator as the from.

The reason for this is the ever stricter mail requirements. Right now it is very likely that your mail server at `mail.example.com` can't send emails for 'foo.com'. So that is why we have to use the default address. Else those e-mails will just bounce probably.

**Comment by skjnldsv** [comment]
> So we can't set the initiator as the from.

Initiator is already the from (if initiator's mail is set of course)

@rullzer can't we put a default like noreply@cloud.domain.com if the initiator mail is not set?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/24978
