### ISSUE TITLE
RC 10 Password Reset Not Working when using email address as username 

### ISSUE THREAD

**Issue by zeugmatis** [nextcloud/server#954]
### Steps to reproduce
1. On login screen, enter account email address for the username.  
2. Intentionally enter a bad password.  "Wrong Password.  Reset it?" 
3. Click "Reset it" 
### Expected behaviour

Password reset link should be sent to the email address entered for the account.  
### Actual behaviour

"Couldn't send reset email.  Please make sure your username is correct." 
- Note that it works OK using the username, but users who forgot their username but remember their email address, will not be able to reset their passwords and require Admin intervention.  
### Server configuration

**Operating system**: Debian 8.5 (jessie)

**Web server:**
Apache 2.4.10 (Debian)

**Database:**
MySQL 5.5.50 (Debian)

**PHP version:**
5.6.24 (Debian)

**Nextcloud version:** (see Nextcloud admin page)
RC 10

**Updated from an older Nextcloud/ownCloud or fresh install:**
Older ownCloud - 9.1.0.15 
(Note: only noticed bug today but could have existed prior) 

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/prereleases/nextcloud-10.0RC1.tar.bz2

**Signing status:**
<details>
<summary>

Signing status</summary>

unsure

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

Enabled:
- activity: 2.3.2
- admin_audit: 1.0.0
- calendar: true
- comments: 1.0.0
- contacts: true
- dav: 1.0.0
- federatedfilesharing: 1.0.1
- federation: 1.0.1
- files: 1.5.2
- files_pdfviewer: 0.8.1
- files_sharing: 1.0.0
- files_texteditor: 2.1
- files_trashbin: 1.0.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- notifications: 0.3.0
- password_policy: 1.0.0
- provisioning_api: 1.0.0
- serverinfo: 1.1.1
- survey_client: 0.1.5
- systemtags: 1.0.1
- templateeditor: 0.1
- theming: 1.0.1
- updatenotification: 1.0.1
- workflowengine: 1.0.0
  Disabled:
- encryption
- external
- files_accesscontrol
- files_automatedtagging
- files_external
- files_retention
- user_external
- user_ldap
- user_saml

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>
### Client configuration

**Browser:**
Firefox and Chrome

**Operating system:**
OSX El Capitan

**Comment by michag86** [comment]
... and it's also not working if you use wrong case sensitivity of you UsERnAme :stuck_out_tongue_winking_eye:

**Comment by MorrisJobke** [comment]
> Note that it works OK using the username, but users who forgot their username but remember their email address, will not be able to reset their passwords and require Admin intervention.

This works with Nextcloud 12 - see #4123
