### ISSUE TITLE
Theming app code signature not found after upgrade

### ISSUE THREAD

**Issue by cmseal** [nextcloud/server#9568]
### Steps to reproduce
1. Web-based upgrade from 13.0.1 to 13.0.2

### Expected behaviour
No issues with code signing

### Actual behaviour
Theming app code signature not found

### Server configuration

**Operating system**:
CentOS 7
**Web server:**
Apache 2.4
**Database:**
MariaDB
**PHP version:**
7.1
**Nextcloud version:**
13.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.0.1
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

Results
=======
- theming
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [theming] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
</details>

**Comment by deddc23efb** [comment]
This affects me too. Updated from 13.0 to 13.2 and now get the same warning.

**Comment by INLinuxdude** [comment]
I'm getting it also...

Operating system:
CentOS 7.4.1708
Web server:
Apache 2.4.6
Database:
MariaDB 5.5.56
PHP version:
7.0.2.9
Nextcloud version:
13.0.2
Updated from an older Nextcloud/ownCloud or fresh install:
Updated from 13.0.1

**Comment by MorrisJobke** [comment]
@blizzz @juliushaertl 😉

**Comment by juliushaertl** [comment]
@cmseal @deddc23efb @INLinuxdude Did you update the theming app though the apps management today?

**Comment by MorrisJobke** [comment]
> @cmseal @deddc23efb @INLinuxdude Did you update the theming app though the apps management today?

Yes - this app is missing the signature :/

**Comment by blizzz** [comment]
Doh. Sorry. Yeah, obviously I missed adding that signature file :(

**Comment by MorrisJobke** [comment]
@blizzz And please also remove the "*.orig" files 😉

**Comment by blizzz** [comment]
@MorrisJobke already cleaned up.

**Comment by PiotrIr** [comment]
Could you tell me how to fix this please? Do I need to wait for next version?

**Comment by MorrisJobke** [comment]
> Could you tell me how to fix this please? Do I need to wait for next version?

We will publish a new version soon (within a few hours).

**Comment by PiotrIr** [comment]
Great, thank you!

**Comment by blizzz** [comment]
Fixed with 1.4.3. 

After updating, you need to click on "Rescan" in the admin settings to trigger a new integrity check. This happens automatically only when running the updater, not after single app installs/updates.

**Comment by deddc23efb** [comment]
Thanks the fix worked for me. 
AN fyi for others, update your theming app in the admin APP page (you should see an option to update) then go back to the warning and request a rescan.

**Comment by alexandre1985** [comment]
I get a code integrity fail after updating the theming app.
This is exactly what I get:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- gallery
	- INVALID_HASH
		- js/vendor/bigshot/bigshot-compressed.js
- files_trashbin
	- INVALID_HASH
		- l10n/pa.json
		- lib/Controller/PreviewController.php

Raw output
==========
Array
(
    [gallery] => Array
        (
            [INVALID_HASH] => Array
                (
                    [js/vendor/bigshot/bigshot-compressed.js] => Array
                        (
                            [expected] => dc9f82912ccb9ee96556fb30e9e078ecc1d693090437147777314652ade05716711006e5b41be4ea61153df2b71f752cc25e19976ce5f3dba028fd362dab6b59
                            [current] => eda3ad98733a47cd9e7495d9a057e532c5fa305f4a69f3859e3b42a76dd2fc0830d1db8d41d791a1c079bf035f649b698808730ad7e13b9d22351f0bc0948c82
                        )

                )

        )

    [files_trashbin] => Array
        (
            [INVALID_HASH] => Array
                (
                    [l10n/pa.json] => Array
                        (
                            [expected] => 47266f6b4903b10175d03ac1b41d9fa11c44694aa985859cc47dfd8966fd0f24af4fe88b43666d87e6a6068b032a4e4896679877054c1b684093e475e5edd5a2
                            [current] => 1c4ba83648927b55626fcf23c12d3702c28af79c18bccd156f1c5fb30cb03ce7b246c527402ed123a61296cfb0bf93d58d43e19e459cc38e095b56b8ac0a5460
                        )

                    [lib/Controller/PreviewController.php] => Array
                        (
                            [expected] => 8e7caf2dc78e410ecd09290098203ccddecde30a8f1075a3d21594508eeec401230087390360c6cbf7fd589903d157722e9e3b9037746ee2b561379752443396
                            [current] => d5fc20e2c8772823018ad9784fc8839acb77b855fedc5f61a72b2b53be7b91176050a4ee72d31c1d410e965c51c4dfb50ce5a926ddcd6ddde72553125f2b82a5
                        )

                )

        )

)

```
What should I do?

**Comment by DJCrashdummy** [comment]
@alexandre1985 as you can see in the _Results_, your issue has nothing to do with the theming app, but the `gallery` and `files_trashbin`.
