### ISSUE TITLE
Theming App scroll bar on login page when using imprint

### ISSUE THREAD

**Issue by worldworm** [nextcloud/server#9572]
### Steps to reproduce
1. Install Theming App v.1.4.2
2. Setup an imprint
3. Logout an go to /login

### Expected behaviour
When to login page is opened at an large monitor so there is nothing to scroll. there should be no scrollbar, because the page fits 100%

### Actual behaviour
There is a tiny scrollbar 
![grafik](https://user-images.githubusercontent.com/13227454/40452451-28e00008-5ee2-11e8-9c03-b32ef62f70e5.png)

### Server configuration

**Nextcloud version:** 13.0.2 & 13.0.1

### guess
The footer object has an height of 70px
The p.info object inside has an height of around 41px + 20px top an bottom margin
41 + 20 + 20 = 81
81!=70

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming @blizzz @skjnldsv

**Comment by MorrisJobke** [comment]
Fixed with #9586
