### ISSUE TITLE
Can't log in after Fedora upgrade from 27 to 28

### ISSUE THREAD

**Issue by biggaz666** [nextcloud/server#9588]
### Steps to reproduce
1. Upgrade from working Owncloud on Fedora 27 to Fedora 28 with DNF
2. Try and log into Owncloud, 500 internal server error
3. Port data to Nextcloud as wanted to move to that anway, and see same issue, followed this guide - https://www.hogarthuk.com/?q=node/17

### Expected behaviour
Should be able to log into Owncloud / Nextcloud

### Actual behaviour
After log in screen, get a 500 Apache error. If I put in an incorrect password, it tells me so. This means it's sort of still working.

### Server configuration
Linux 4.16.8-300.fc28.x86_64, Fedora 28, httpd-2.4.33-5.fc28.x86_64 Apache, mariadb-10.2.14-1.fc28.x86_64, php-7.2.5-1.fc28.x86_64

**Nextcloud version:** (see Nextcloud admin page)
nextcloud-10.0.4-3.fc27.noarch
owncloud-9.1.5-3.fc28.noarch

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Fedora 27 to 28, which bricked my install. Tried to move over to Nextcloud, but this hasn't helped  :(

**Where did you install Nextcloud from:**
Official Fedora repos.

**List of activated apps:**
<details>
<summary>App list</summary>
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'OC\Log\All' not found in /usr/share/nextcloud/lib/private/Log.php on line 299
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 1.0.0
  - contacts: 1.5.1
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.1
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - user_external
  - user_ldap
  - user_saml
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'log_type' => 'All',
  'datadirectory' => '/var/lib/nextcloud/data',
  'updatechecker' => false,
  'check_for_working_htaccess' => false,
  'asset-pipeline.enabled' => false,
  'assetdirectory' => '/var/lib/nextcloud',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/share/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/lib/nextcloud/apps',
      'url' => '/apps-appstore',
      'writable' => true,
    ),
  ),
  'instanceid' => '*********************',
  'passwordsalt' => '****************************',
  'secret' => '***************',
  'trusted_domains' => 
  array (
    0 => '192.168.1.200'
  ),
  'overwrite.cli.url' => 'http://192.168.1.200/nextcloud',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'nextclouddb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud_user',
  'dbpassword' => '*************',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 0,
  'maintenance' => false,
  'htaccess.RewriteBase' => '/nextcloud',
);
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
Brave and Gnome Web

#### Web server error log
<details>
<summary>Web server error log</summary>

Full of entries like so

Thu May 24 05:15:37.207936 2018] [autoindex:error] [pid 17040:tid 140574046856960] [client 189.130.163.50:38245] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Thu May 24 05:38:00.048899 2018] [autoindex:error] [pid 17462:tid 140573382002432] [client 37.29.19.174:40819] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Thu May 24 06:29:53.405669 2018] [autoindex:error] [pid 17040:tid 140573809833728] [client 185.100.46.43:58035] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Thu May 24 06:29:53.406372 2018] [autoindex:error] [pid 17462:tid 140573365217024] [client 185.100.46.43:58036] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
EMPTY?!?!
```
</details>

**Comment by biggaz666** [comment]
See updates on Redhat bugzilla .... https://bugzilla.redhat.com/show_bug.cgi?id=1582274

**Comment by MorrisJobke** [comment]
No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive

This seems to be the issue. Please solve the setup of your web server first.

Thanks for reporting anyways.

**Comment by biggaz666** [comment]
I also managed to find this, as I've put on the Fedora bug ...

[30-May-2018 20:50:07 UTC] PHP Fatal error:  Declaration of OC\Files\Storage\Local::copyFromStorage(OCP\Files\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath) must be compatible with OC\Files\Storage\Common::copyFromStorage(OCP\Files\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath, $preserveMtime = false) in /usr/share/owncloud/lib/private/Files/Storage/Local.php on line 42

Which is what's causing the 500 error.

**Comment by biggaz666** [comment]
I think that other message is just because I haven't got anything in the root, and nextcloud is in a subdirecory.

**Comment by biggaz666** [comment]
Thanks for reopening, cheers mate.

**Comment by Leffe64** [comment]
Don't know if it will solve all your problems but just add  ", $preserveMtime = false" to the function in Local.php so the definition is the same as in Common.php

public function copyFromStorage(\OCP\Files\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath, $preserveMtime = false)

**Comment by biggaz666** [comment]
Well, that amazingly has actually fixed it for my old Owncloud installation.

I can now see about upgrading to Nextcloud and see if this fixes that too.

The only question now is how have I ended up in this state? Is it something in the move from PHP 7.1 to PHP 7.2 that's made it demand that parameter is included, even though it has a default value?

**Comment by biggaz666** [comment]
Hi, this was with Owncloud. I've managed to migrate to Nextcloud tonight, and the version packaged with Fedora has the same issue.

owncloud-9.1.5-3.fc28.noarch
nextcloud-10.0.4-3.fc27.noarch

I fixed it in the same way.

**Comment by MorrisJobke** [comment]
> nextcloud-10.0.4-3.fc27.noarch

Then you should upgrade to the last supported version, because 10 is end of life and 10.0.4 is also not even the latest patch level: see https://nextcloud.com/changelog/#latest10 and https://nextcloud.com/security/advisories/

Only 12 and 13 is still maintained. Thus closing because it is an unsupported version you are running. If you have the same problems with either 12 or 13 we can have a look at this again.

**Comment by biggaz666** [comment]
Thanks everyone for all your help! I will feed this back on the Redhat Bugzilla.
