### ISSUE TITLE
NC13: Shared folder which has been marked of the owner as "cant’ reshare" can be shared in public

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#9597]
Detailled information and screenshots:
https://help.nextcloud.com/t/remote-sharing-nc-13-does-not-work-as-expected/31672

**Comment by tflidd** [comment]
I can confirm that with a current NC 12.0.9 and NC 13.0.4 setup:

- create folder in NC 13 and share with other user on different setup via federated cloud sharing
- accept the share in NC 12
- you can create a link to share this folder (but you can't share to other users)

@rullzer @LukasReschke Is this a security issue? Or does this restriction not apply to sharing via link?

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
