### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Ammar7347** [nextcloud/server#9598]
Hi,

Everything was working fine until I started updating the nextcloud apps. This has never happened to me before. I was updating an official nextcloud app(I don't remember the name) and then everything just froze with "updating" and then page suddenly page refreshed automatically and I got an error. Now the thing is that there is no way to fix the problem as I can't even log into my account. You can go the URL and it will ask for the user and password as usual but when you enter the credentials, it will give you the same error. I can't reset my password as well because when I receive the password reset email and I click on the link, I get the same error. I tried updating the nextcloud server with occ but it's saying that nextcloud is already at the latest version. So is there any way to fix this error?

![image](https://user-images.githubusercontent.com/19525838/40528126-9f9ba4d0-5fe7-11e8-86cb-407b1ed11238.png)

### Steps to reproduce
1. Login

### Expected behaviour
You should be logged in to the admin panel

### Actual behaviour
You will be greeted with a HTTP ERROR 500

### Server configuration

**Operating system**: Debian 8

**Web server:** NGINX

**Database:** MySQL

**PHP version:** 5

**Nextcloud version:** 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**List of activated apps:**
I don't remember all the apps but there were quite a few activated apps

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - apporder: 0.4.1
  - audioplayer: 2.3.0
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - camerarawpreviews: 0.5.3
  - circles: 0.13.6
  - cms_pico: 0.9.7
  - comments: 1.3.0
  - dashboard: 4.0.6
  - dav: 1.4.6
  - dicomviewer: 0.0.6
  - end_to_end_encryption: 1.0.5
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_antivirus: 1.2.0
  - files_downloadactivity: 1.2.0
  - files_frommail: 0.1.0
  - files_fulltextsearch: 0.7.2
  - files_markdown: 2.0.4
  - files_opds: 0.8.8
  - files_pdfviewer: 1.2.1
  - files_reader: 1.2.3
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - fulltextsearch: 0.6.1
  - fulltextsearch_elasticsearch: 0.7.2
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - lsd: 1.0.0
  - mail: 0.7.10
  - metadata: 0.6.0
  - mood: 0.3.3
  - music: 0.5.6
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ojsxc: 3.3.2
  - onlyoffice: 1.3.0
  - passman: 2.1.4
  - password_policy: 1.3.0
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - quicknotes: 0.1.3
  - quota_warning: 1.2.0
  - radio: 0.6.1
  - rainloop: 5.0.6
  - ransomware_protection: 1.1.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - sociallogin: 1.5.2
  - socialsharing_diaspora: 1.0.2
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - spreed: 3.2.0
  - spreedme: 0.3.11
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - twofactor_u2f: 1.5.1
  - twofactor_yubikey: 0.3.0
  - unsplash: 1.1.1
  - updatenotification: 1.3.0
  - user_usage_report: 1.0.1
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.thenoobstribe.ga"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.thenoobstribe.ga",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "theme": "",
        "loglevel": 2
    }
}



With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "ldap" namespace.

### Client configuration
**Browser:** Google Chrome, Firefox and Edge

**Operating system:** Windows 10

**Comment by MorrisJobke** [comment]
> PHP version: 5

With PHP version 7.0+ updating apps cannot break the server anymore that hard, because it allows more checking.

Please check out the nextcloud log, apache error log and maybe the php-fpm log (if you use php-fpm)
