### ISSUE TITLE
App password get Invalid from time to time

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#9599]
I have two nextcloud Server which I use. On one Server I have the Problem, that the App-Password get invalid from time to time. I have a special condition. I use the IMAP based Authentication. I could tell that the IMAP Password do no change. Is there some kind of term setting I was not able to see? It's interesting that not all App-Passwords at once are affected. Sometime it's the Nextcloud App on Windows, some time the one on Linux then the CalDAV from Thunderbird. It happens around all ~4-6 months. 

## Server configuration detail

**Operating system:** Linux 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.1.31

**PHP version:** 7.1.17
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, fileinfo, gd, imagick, imap, intl, json, exif, mcrypt, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, posix, pspell, soap, sqlite3, sysvmsg, sysvsem, sysvshm, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Updater

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.3
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - impersonate: 1.0.4
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.8.1
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ownbackup: 17.5.0
 - password_policy: 1.3.0
 - piwik: 0.4.1
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_external: 0.4
 - workflowengine: 1.3.0
Disabled:
 - activity
 - admin_audit
 - encryption
 - files_videoplayer
 - spreed
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "logtimezone": "UTC",
    "installed": true,
    "appstore.experimental.enabled": false,
    "mail_smtpmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "default_language": "de",
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "{localhost:143\/novalidate-cert\/imap\/readonly}"
            ]
        }
    ],
    "maintenance": false,
    "debug": false,
    "loglevel": 3,
    "theme": "",
    "mail_smtpsecure": "ssl",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

**Comment by MorrisJobke** [comment]
Maybe related to #2581 - let's close this one as part of #2581 because we are reworking on how app passwords work and when they expire. This should then make this problem here either be more known to WHY it expired or not happen anymore.
