### ISSUE TITLE
Files being removed from the client after Nextcloud server Bare Metal recovery

### ISSUE THREAD

**Issue by khasnl** [nextcloud/server#9604]
### Steps to reproduce
1. Upload a file through the WebGUI of Nextcloud
2. Sync the file with a Desktop client 
3. Start a bare metal recovery (8 hours ago) of the Nextcloud server. 
4. Start the Nextcloud server
5. Suddenly the uploaded file is being removed instead of being synced to the server.

### Expected behaviour
Nextcloud server should see that the client has a file who is not existing on the server or has a newer timestamp and should sync it to the Nextcloud server.

### Actual behaviour
Nextcloud server sees that the client has a file who does not exist on the server and performs via the Nextcloud client to remove the file without any confirmation.

### Server configuration

**Operating system**:
centos-release-7-5.1804.el7.centos.2.x86_64
**Web server:**
httpd-2.4.6-80.el7.centos.x86_64
httpd24-httpd-2.4.27-8.el7.x86_64
httpd24-httpd-tools-2.4.27-8.el7.x86_64
httpd24-libnghttp2-1.7.1-6.el7.x86_64
httpd24-runtime-1.1-18.el7.x86_64
httpd-tools-2.4.6-80.el7.centos.x86_64
**Database:**
mariadb-server-5.5.56-2.el7.x86_64
**PHP version:**
rh-php70-2.3-1.el7.x86_64
rh-php70-php-7.0.27-1.el7.x86_64
rh-php70-php-cli-7.0.27-1.el7.x86_64
rh-php70-php-common-7.0.27-1.el7.x86_64
rh-php70-php-fpm-7.0.27-1.el7.x86_64
rh-php70-php-gd-7.0.27-1.el7.x86_64
rh-php70-php-gmp-7.0.27-1.el7.x86_64
rh-php70-php-intl-7.0.27-1.el7.x86_64
rh-php70-php-json-7.0.27-1.el7.x86_64
rh-php70-php-mbstring-7.0.27-1.el7.x86_64
rh-php70-php-mysqlnd-7.0.27-1.el7.x86_64
rh-php70-php-opcache-7.0.27-1.el7.x86_64
rh-php70-php-pdo-7.0.27-1.el7.x86_64
rh-php70-php-pear-1.10.1-3.el7.noarch
rh-php70-php-process-7.0.27-1.el7.x86_64
rh-php70-php-xml-7.0.27-1.el7.x86_64
rh-php70-php-zip-7.0.27-1.el7.x86_64
rh-php70-runtime-2.3-1.el7.x86_64
sclo-php70-php-pecl-apcu-5.1.11-1.el7.x86_64
sclo-php70-php-pecl-apcu-bc-1.0.3-1.el7.x86_64
sclo-php70-php-pecl-igbinary-2.0.5-1.el7.x86_64
sclo-php70-php-pecl-imagick-3.4.3-1.el7.x86_64
sclo-php70-php-pecl-redis-3.1.6-1.el7.x86_64
sclo-php70-php-phpiredis-1.0.0-1.el7.x86_64
sclo-php70-php-smbclient-0.9.0-1.el7.x86_64

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Installation
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/latest-13.zip

```
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary> List
</summary>
Theming	1.4.3	Official
Activities for shared file downloads	1.2.0	
Activity	2.6.1	Official	
Antivirus App for files 
Auditing / Logging	1.3.0	Official
Checksum 	0.4.0 	View in store ↗
Collaborative tags 1.3.0	Official
Comments 	1.3.0	Official
Deleted files 	1.3.0 	Official
Draw.io 	0.8.9 	
Federation 	1.3.0 	Official
File access control	 1.3.0	
File sharing 	1.5.0 	Official
Files automated tagging 	1.3.0 
First run wizard 	2.2.1 	Official
Gallery 	18.0.0 	Official
Log Reader 	2.0.0  	Official
Metadata 	0.6.0 	
Monitoring 	1.3.0 Official
Nextcloud announcements 	1.2.0 	Official
Notes 	2.3.2 	
Notifications 	2.1.2 	Official
Password policy 	1.3.0 	Official
PDF viewer 	1.2.1 	Official
Quota warning 	1.2.0 
Share by mail	1.3.0	Official
Social sharing via email 	1.0.3
Text editor 	2.5.1 	Official
Two Factor TOTP Provider 	1.4.1 	
Update notification 	1.3.0 	Official
Usage survey 	1.1.0 	Official
Versions 	1.6.0 	Official
Video player 	1.2.0 	Official

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - checksum: 0.4.0
  - comments: 1.3.0
  - dav: 1.4.6
  - drawio: 0.8.9
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_antivirus: 1.2.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.3
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap
```
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dev.cloud.frecon.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/dev.cloud.frecon.eu",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": "0",
            "timeout": "0.0"
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "enable_previews": "true",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "preview_max_x": "1024",
        "preview_max_y": "768",
        "preview_max_scale_factor": "1",
        "auth.bruteforce.protection.enabled": "true",
        "trashbin_retention_obligation": "auto,7",
        "skeletondirectory": "",
        "defaultapp": "file",
        "activity_expire_days": "14",
        "integrity.check.disabled": "false",
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}

```
</details>

**Are you using external storage.
No

**Are you using encryption:** 
yes, full disk encryption with LUKS

**Are you using an external user-backend, 
No

### Client configuration
**Browser:**
Chrome, Firefox
**Operating system:**
Windows 10, Fedora 27, Ubuntu 16.04
### Logs
No logs behalf of the Desktop client who tells that the file is deleted.

**Comment by MorrisJobke** [comment]
> Start a bare metal recovery (8 hours ago) of the Nextcloud server.

Have you run the `occ maintenance:data-fingerprint` command like it is documented in https://docs.nextcloud.com/server/13/admin_manual/maintenance/restore.html to announce that a server backup was restored? Otherwise the clients have no idea that a restore happened.

**Comment by khasnl** [comment]
Thanks for your reply Morris,

Actually I did not run the command as you specified. In a last mile crisis solution I am required to restore the bare metal backup. After the restore the server will boot up and whenever its reachable by the clients it starts directly to remove the data from the client. The removed data cannot be restored, as it will not be moved to the recycle bin.

So if I understand you correctly, I should make the server unreachable for the clients and enter the `occ maintenance:data-fingerprint` and make it reachable again? I will reproduce the issue with your advise and give you feedback.

In an ideal situation, I would really like to see the client confirming before deleting or at least moving them to the recycle bin.

**Comment by MorrisJobke** [comment]
> So if I understand you correctly, I should make the server unreachable for the clients and enter the occ maintenance:data-fingerprint and make it reachable again? I will reproduce the issue with your advise and give you feedback.

Correct.



> In an ideal situation, I would really like to see the client confirming before deleting or at least moving them to the recycle bin.

We tried very hard to detect this and prevent further damage. Sadly this is not really easily detectable and thus the fingerprint is the only way to do so. The client just does it job and if the server says "there are no such files" then the client takes this as the truth. Regarding the trash bin: please report this in the client repo.

**Comment by MorrisJobke** [comment]
Let's close this ticket for now.
