### ISSUE TITLE
Nextcloud 13: Class 'XMLReader' not found with php 7.0.27-1.el7

### ISSUE THREAD

**Issue by fmikker** [nextcloud/server#9606]
### Steps to reproduce
1. Upgrade php packages to 7.0.27-1.el7
`yum clean metadata && yum update rh-php70-*` 
2. Restart apache
`systemctl restart httpd`
3. Navigate to the login page and log in
4. View the "Files" section

### Expected behaviour
The files app displaying contents

### Actual behaviour
White page with a loading wheel

### Server configuration

**Operating system**:
CentOS Linux release 7.5.1804 (Core) 

**Web server:**

Server version: Apache/2.4.6 (CentOS)
Server built:   Apr 20 2018 18:10:38
Server's Module Magic Number: 20120211:24
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

**Database:**
mariadb-server-5.5.56-2.el7.x86_64

**PHP version:**
php --version
PHP 7.0.27 (cli) (built: Apr  4 2018 13:48:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.0.27, Copyright (c) 1999-2017, by Zend Technologies

These are the versions prior to the upgrade. With these versions Nextcloud works fine. 
rh-php70-php-ldap-7.0.10-2.el7.x86_64
rh-php70-php-mbstring-7.0.10-2.el7.x86_64
sclo-php70-php-pecl-apcu-5.1.11-1.el7.x86_64
rh-php70-php-pdo-7.0.10-2.el7.x86_64
rh-php70-php-7.0.10-2.el7.x86_64
rh-php70-php-gd-7.0.10-2.el7.x86_64
rh-php70-php-xml-7.0.10-2.el7.x86_64
rh-php70-runtime-2.3-1.el7.x86_64
rh-php70-2.3-1.el7.x86_64
sclo-php70-php-pecl-igbinary-2.0.5-1.el7.x86_64
rh-php70-php-json-7.0.10-2.el7.x86_64
rh-php70-php-cli-7.0.10-2.el7.x86_64
rh-php70-php-mysqlnd-7.0.10-2.el7.x86_64
rh-php70-php-opcache-7.0.10-2.el7.x86_64
sclo-php70-php-pecl-redis-3.1.6-1.el7.x86_64
rh-php70-php-pear-1.10.1-3.el7.noarch
rh-php70-php-process-7.0.10-2.el7.x86_64
rh-php70-php-zip-7.0.10-2.el7.x86_64
rh-php70-php-intl-7.0.10-2.el7.x86_64

These are the versions post-upgrade:
rh-php70-php            7.0.27-1.el7    centos-sclo-rh
rh-php70-php-cli        7.0.27-1.el7    centos-sclo-rh                 
rh-php70-php-common     7.0.27-1.el7    centos-sclo-rh           
rh-php70-php-gd         7.0.27-1.el7    centos-sclo-rh
rh-php70-php-intl       7.0.27-1.el7    centos-sclo-rh
rh-php70-php-json       7.0.27-1.el7    centos-sclo-rh
rh-php70-php-ldap       7.0.27-1.el7    centos-sclo-rh
rh-php70-php-mbstring   7.0.27-1.el7    centos-sclo-rh         
rh-php70-php-mysqlnd    7.0.27-1.el7    centos-sclo-rh         
rh-php70-php-opcache    7.0.27-1.el7    centos-sclo-rh         
rh-php70-php-pdo        7.0.27-1.el7    centos-sclo-rh         
rh-php70-php-process    7.0.27-1.el7    centos-sclo-rh         
rh-php70-php-xml        7.0.27-1.el7    centos-sclo-rh         
rh-php70-php-zip        7.0.27-1.el7    centos-sclo-rh

**Activated PHP-Modules**

```
$ php -m
[PHP Modules]
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```
**Nextcloud version:** (see Nextcloud admin page)
13.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
12.0.x
**Where did you install Nextcloud from:**
Nextcloud Updater app

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
- activity: 2.6.1
  - admin_audit: 1.3.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - cms_pico: 0.9.7
  - comments: 1.3.0
  - contacts: 2.1.3
  - dashboard: 4.0.6
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
 - files_markdown: 2.0.4                                                                                                                                                [0/105]
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - news: 12.0.1
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - ransomware_protection: 1.1.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - federation
  - files_clipboard
  - files_external
  - files_versions
  - ocsms
  - systemtags
  - tasks
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.fqdn",
],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/mikker.se\/cloud",
        "htaccess.RewriteBase": "\/cloud",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Stockholm",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "loglevel": 2,
        "has_internet_connection": true,
        "maintenance": false,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "knowledgebaseenabled": true,
        "updater.release.channel": "stable",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "log_rotate_size": 104857600
    }
}


```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:**
59.0.2 (64-bit)

**Operating system:**
Fedora release 27 (Twenty Seven)
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Fri May 25 12:42:11.699879 2018] [:error] [pid 23954] [client 193.201.96.49:41346] PHP Fatal error:  Class 'XMLReader' not found in /var/www/html/nextcloud/3rdparty/sabre/xml/lib/Reader.php on line 20
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"WwfnrrIBQRayzRN5mN1b4wAAAA0","level":3,"time":"2018-05-25T12:38:38+02:00","remoteAddr":"94.254.51.200","user":"fmikker","app":"PHP","method":"PROPFIND","url":"\/cloud\/remote.php\/dav\/files\/fmikker\/","message":"Class 'XMLReader' not found at \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/xml\/lib\/Reader.php#20","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.2.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
Please install also the xmlreader module: https://secure.php.net/manual/en/book.xmlreader.php

**Comment by fmikker** [comment]
These aree the modules that are compiled in the installed package: 
```
php -m | grep xml
libxml
xml
xmlreader
xmlwriter
```
It looks like the module is compiled and enabled.

**Comment by MorrisJobke** [comment]
But then this error does not make any sense:

```
PHP Fatal error:  Class 'XMLReader' not found in /var/www/html/nextcloud/3rdparty/sabre/xml/lib/Reader.php on line 20
```

Could you check the output of `phpinfo();` from within the web server? Just place a file `info.php` in the web server and put in there this:

```
<?php

phpinfo();

```

Then open this via the browser.

**Comment by blizzz** [comment]
after module installation it also needs a webserver restart. The CLI output also does not tell you anything about the config valid for the webserver.

**Comment by fmikker** [comment]
@MorrisJobke You were indeed correct, the module isn't loaded via the web server using `phpinfo();`. 

Something seems pretty broken with the package version 7.0.27-1 according to the `error.log`: 
```Failed loading /opt/rh/rh-php70/root/usr/lib64/php/modules/opcache.so:  /opt/rh/rh-php70/root/usr/lib64/php/modules/opcache.so: undefined symbol: zend_is_smart_branch
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/rh/rh-php70/root/usr/lib64/php/modules/curl.so' - /opt/rh/rh-php70/root/usr/lib64/php/modules/curl.so: undefined symbol: zend_unset_property in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/rh/rh-php70/root/usr/lib64/php/modules/dom.so' - /opt/rh/rh-php70/root/usr/lib64/php/modules/dom.so: undefined symbol: php_libxml_node_free_list in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/rh/rh-php70/root/usr/lib64/php/modules/xsl.so' - /opt/rh/rh-php70/root/usr/lib64/php/modules/xsl.so: undefined symbol: dom_node_class_entry in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/rh/rh-php70/root/usr/lib64/php/modules/xmlreader.so' - /opt/rh/rh-php70/root/usr/lib64/php/modules/xmlreader.so: undefined symbol: dom_node_class_entry in Unknown on line 0
```
I will try with the 7.1 branch of PHP instead and see how that works out.

@blizzz Yes, I know.

**Comment by MorrisJobke** [comment]
Okay - then let's close this here for now and if there is still a problem this is anyways a separate ticket.

**Comment by fmikker** [comment]
I want to come back to this issue and report my findings if someone else should have the same problem.

The issue was that the module loaded by Apache `librh-php70-php7.so` was the wrong version so there was a version mismatch between what module that was loaded in cli compared to what was loaded into Apache.
from: `/etc/httpd/conf.modules.d/15-rh-php70-php.conf`
```# Cannot load both php5 and php7 modules
<IfModule !mod_php5.c>
  <IfModule prefork.c>
    LoadModule php7_module modules/librh-php70-php7.so
  </IfModule>
</IfModule>
```
This module in the relative path `modules/` was version 7.0.10 and not owned by any package, so to do a quick and dirty fix, I removed the module file `/usr/lib64/httpd/modules/librh-php70-php7.so` and created a symlink to the updated module:
```
# cd /etc/httpd/modules
# ln -s /opt/rh/httpd24/root/usr/lib64/httpd/modules/librh-php70-php7.so .
# systemctl restart httpd
``` 
And now Apache finds the correct module.
