### ISSUE TITLE
[FEATURE] Allow config.php per domain name

### ISSUE THREAD

**Issue by Kalimeiro** [nextcloud/server#9607]
Hi,

I'm not developper and it's not an issue, but most admin of nextcloud needed to have a different config.php file per domain, this feature can enable different theme per domain.

I have found two files to modify and it works (do not hit me, I'm not developer) :
/lib/base.php
```
		// Create config if it does not already exist
                $fileName="/config_".$_SERVER['HTTP_HOST'].".php";
                $configFilePath = self::$configDir .$fileName';
                if(!file_exists($configFilePath)) {
                        @touch($configFilePath);
                }
```

/lib/private/Config.php
```
        public function __construct($configDir, $fileName = 'config.php') {
                $fileName="config_".$_SERVER['HTTP_HOST'].".php";
                $this->configDir = $configDir;
                $this->configFilePath = $this->configDir.$fileName;
                $this->configFileName = $fileName;
                $this->readData();
        }
```

Next, i need to modify theming apps accordling to the config file, and with this feature you can have different theme with different logo, name, slogan, etc... per domain

Can someone give me a helping hand? in the end this feature could be integrated in nextcloud stable branche ?

**Comment by c0fe** [comment]
This seems like a more convoluted method of doing something that can be accomplished through LXD or Docker containers. Why not just run two separate instances for two different domains?

**Comment by rullzer** [comment]
There is the (not recommended and not documented `NEXTCLOUD_CONFIG_DIR` enviroment variable.

However, I strongly advice against this. You will have to upgrade all your installations in lock step. Have 1 app somewhere that is not ready? You can't upgrade. etc.

Nextcloud is tiny in comparison to the files stored. Just have multiple installations.
