### ISSUE TITLE
No files/folders are displayed in the files app

### ISSUE THREAD

**Issue by flixman** [nextcloud/server#9623]
### Steps to reproduce
1. Migrate a native installation of v13.0.2 to the nextcloud:fpm docker container
2. Adapt the apache virtualhost
3. login and check contacts / calendar / files are there

### Expected behaviour
Contacts / calendars and files show up.

### Actual behaviour
files do not show up on the files app, but the space they occupy is properly noted on the user settings. As it is not clear to me if the files are served by the php-fpm or considered static and served by apache, I have even tried rescanning the files by running

    php occ files:scan-app-data
    php occ files:scan --all

unsuccessfully.

### Server configuration

**Operating system:** Debian

**Web server:** Apache

**Database:** Mysql

**PHP version:** 7.x (the one bundled in the nextcloud:fpm docker image)

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Originally from github, migrated to docker container

**Signing status:**
<details>
<summary>Signing status</summary>

- theming
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - deck: 0.3.1
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_opds: 0.8.8
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_videoplayer: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - news: 12.0.1
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - passman: 2.1.4
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - rainloop: 5.1.0
  - richdocuments: 2.0.8
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.2
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
Disabled:
  - activity
  - admin_audit
  - encryption
  - files_texteditor
  - files_trashbin
  - files_versions
  - firstrunwizard
  - gallery
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "asset-pipeline.enabled": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***FQDN FOR MY VHOST***"
        ],
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "uik_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_authfailip": true,
        "loglevel": 2,
        "logfile": "\/var\/www\/html\/data\/owncloud.log",
        "logtimezone": "Europe\/Paris",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "588",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "session_lifetime": 3600,
        "share_folder": "\/Shared",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***URL TO MY VHOST***",
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** yes, Webdav

### Client configuration
**Browser:** Firefox 60.0.1

**Operating system:** Arch Linux

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
