### ISSUE TITLE
Allow admin to revoke all users tokens/sessions

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#9642]
In case you suspect the account of a user is compromised it would make sense that admins have a way to kill all the apptokens and sessions of a user.

That way they can enforce a password change and be sure that non of the tokens are compromised (since they are all removed).

I'd vote for

1. and occ command (quick and easy)
2. something in the admin interface

CC: @MorrisJobke @ChristophWurst

**Comment by ChristophWurst** [comment]
> and occ command (quick and easy)

:+1: good enough for most setups, I guess

**Comment by schadom** [comment]
https://github.com/nextcloud/server/issues/8720#issuecomment-426111637

**Comment by szaimen** [comment]
As far as I can see is this already implemented by selecting `Wipe all devices` on the user overview.
![image](https://user-images.githubusercontent.com/42591237/118955943-7459b580-b95f-11eb-9964-15dfa5473719.png)
Please reopen if this shouldn't be the case!

**Comment by tilllt** [comment]
I don't think this issue should have been closed. Closing all dangling sessions and remote wiping the device are two very different options. Remote wiping a device just to get rid of a session seems like an extremely nuclear approach.

![Screenshot_2025-12-14-08-52-44-648_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/c636fc2c-f870-46ba-bd3c-21ca9f19a20c)

![IMG_20251214_085220.jpg](https://github.com/user-attachments/assets/859b1ca9-adc3-481a-9b0b-ee182a2ca232)
