### ISSUE TITLE
Admin 2FA app

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#9643]
Assume:

A user is locked out of their account because they lost access to all their 2FA tokens/devices etc. (their phone got stolen or whatever). Maybe also their laptop is out of order so they can't access their backup codes either.

Currently this would mean disabling 2FA so the user can continue to use their Nextcloud.

A 2FA backup provider would help here.

1. Call an admin
2. Admin clicks a button for the user and a 6 digit code is generate (which is valid once and for 10 minutes or so?)
3. The user enters the code and is logged in

This would allow the user to login while keeping 2FA active on their account.

CC: @MorrisJobke @ChristophWurst

**Comment by ChristophWurst** [comment]
Makes sense and is technically reasonable :+1:

**Comment by MorrisJobke** [comment]
cc @oparoz

**Comment by rullzer** [comment]
Tacked in #11020
