### ISSUE TITLE
User id column is too short on users page

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#9644]
The IDs break and overlap on current master:

![screenshot_20180529_124255](https://user-images.githubusercontent.com/2184312/40654178-cff6bc88-633d-11e8-84c3-5e23018d303e.png)

Try with a user id like: `6a34a394-a9c6-4759-a89c-1e4e1cd48724`

@skjnldsv

**Comment by skjnldsv** [comment]
What browser?

**Comment by blizzz** [comment]
Firefox 60

**Comment by rullzer** [comment]
Also happens on firefox 59
