### ISSUE TITLE
LDA / AD integration: Advanced Settings are empty at first call.

### ISSUE THREAD

**Issue by mrlochis** [nextcloud/server#9645]
**LDA / AD integration: Advanced Settings are empty at first call.**

### Steps to reproduce
1. Brand new installation of nextCloud
2. Enable "LDAP / AD integration" App
3. "Settings" -> "LDAP / AD integration"
4. Page "Server": successful connection to Apple OD Server -> "continue"
5. Page "Users": set object class to "posixAccount" -> "continue"
6.  Page "Login attribute":  Uncheck "LDAP / AD Username" and check "LDAP / AD Username" -> "continue"
7. Page "Groups": -> set object class to "posixGroup" 
8. Select Page "Advanced"
9. unfold "Directory settings"

### Expected behaviour
Values in "Base user tree" and "Base Group Tree" and "uid" in "User Display Name Field"

### Actual behaviour
"Base user tree" and "Base Group Tree" are empty.
"displayName" in "User Display Name Field"

### Workaround
1. Leave "LDAP / AD integration" settings (change to e.g. sharing/security,....)
2. Enter "LDAP / AD integration" settings
3. Select "Advanced"
4. unfold "Directory settings"
5. Now the values are set.

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
>  "displayName" in "User Display Name Field"

that's the default, uid must be set manually if this is desired

> "Base user tree" and "Base Group Tree" are empty.

indeed, there the base tree should be present.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
