### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by hume1991** [nextcloud/server#9646]
Hello, 

is it possible to use the theming app SVG? How can the favicon be changed here?

Is there a detailed example if you want to use your own theme? The example is not enough for me. Have created several favicons with: https://realfavicongenerator.net/
and I would like to use these.

Would appreciate answers.

Best regards 

Christian Huml

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers @nextcloud/theming

**Comment by MariusBluem** [comment]
Is coming with Nextcloud 14 as dedicated option: https://github.com/nextcloud/server/pull/8540
