### ISSUE TITLE
Excessive scanning in appdata preview during preview generation causes slowdown

### ISSUE THREAD

**Issue by spantaleev** [nextcloud/server#9648]
I'm running Nextcloud 13.0.2 using the official Docker image (`nextcloud:13.0.2`).

My `appdata_xxx/preview` directory lives on a remote filesystem (Amazon S3 mounted using [Goofys](https://github.com/kahing/goofys)).

I'm experiencing extremely **slow preview image generation**, and not only generation but **also slow serving of existing (already generated) preview images**.

This may be at least somewhat related to #1732.

----------

I've tried digging into the code a bit, to see where the slowness comes from.

The trace goes something like this:
- `Preview/Generator::getPreview()`
- `Files/AppData/AppData::getFolder()`
- `Files/AppData/AppData::getAppDataFolder()`
- `Files/Node/Folder::get('preview')` called from `Files/AppData/AppData::getAppDataFolder()` via `$appDataFolder = $appDataFolder->get($this->appId)`
- `Files/Node/Root::get('/appdata_xxx/preview')`
- `Files/View::getFileInfo()`with `$path = '/appdata_xxx/preview'`
- `Files/View::getCacheEntry()` with `$internalPath = 'appdata_xxx/preview'` and `$relativePath = '/appdata_xxx/preview'`
- `Files/Cache/Scanner::scan()` with `$internalPath = 'appdata_xxx/preview'` and `Cache\Scanner::SCAN_SHALLOW`
- ..
- which causes all sub-directories in `appdata_xxx/preview` (about 3k for me, currently) to get scanned (calling `scanFile()` for each one & taking ~1ms for each one)

-------

So it seems like the slowdown happens because:
- a shallow scan is performed on the whole `preview` directory on each preview-generation (and preview-serving) request
- `scanFile()` is called for each of the 3k+ sub-directories (e.g. `appdata_xxx/preview/8443`), taking 1ms on each

`scanFile()` itself seems to spends its time in 2 places:
- mostly in locking (`OC\Lock\DBLockingProvider()`) - about ~0.6ms for each sub-directory in `preview/`
- a bit in getting file metadata (`Scanner::getData()` -> `Files\Storage\Common::getMetaData()`) - about ~0.2ms for each sub-directory in `preview/`

Unless there's some configuration issue on my installation which causes all this to happen, this likely affects everyone.

Faster filesystems likely don't experience some of the degradation (at least the metadata-fetching part), but they probably experience the DB-locking degradation. The more the `preview/` directory grows, the slower it becomes.

In any case, it probably shouldn't be like that.

Is there anything which necessitates such excessive scanning of the whole `preview` directory? Does it need to happen on each request?

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991

**Comment by rullzer** [comment]
It shouldn't scan...

Can you run: `./occ files:scan-app-data` to see if that fixes the issue?

**Comment by spantaleev** [comment]
@rullzer, I did run `./occ files:scan-app-data` and it fixed the problem.

```
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 3650    | 37455 | 00:04:25     |
+---------+-------+--------------+
```

It doesn't seem like scans are performed anymore.

I'm not sure what had happened to my environment and whether it will happen again. Maybe it has something to do with me running with the `appdata_xxx/preview` directory being local at first and then changed it to be a fuse-mounted directory.

I guess this issue can be closed, unless you want to pursue things further.

Thanks so much for your help!

**Comment by rullzer** [comment]
Good it is fixed. It is something with an incomplete db state. But we already have a ticket describing that I think.
