### ISSUE TITLE
occ user:delete does not remove storage and files where using Swift as primary store

### ISSUE THREAD

**Issue by vpecinka** [nextcloud/server#9690]
### Steps to reproduce
1. Set up Nextcloud using Swift as a primary storage
2. Login as admin and create user (e.g. tester)
3. Login as tester and add some files (for sure, there are the default ones)
4. As www-data user run cmd: php occ user:delete tester

### Expected behaviour
The user and its oc_storage and oc_filecache should be deleted

### Actual behaviour
The users is deleted, however the oc_storages and oc_filecache stil remain, together with files in the object storage.

Pre conditions:
```
MySQL [nextcloud_v13]> select * from oc_storages;
+------------+---------------------------------------------------+-----------+--------------+
| numeric_id | id                                                | available | last_checked |
+------------+---------------------------------------------------+-----------+--------------+
|          1 | object::store:nc0                                 |         1 |         NULL |
|          2 | object::user:admin                                |         1 |         NULL |
|          4 | object::user:775DA7E6-9157-48EE-92AD-DE87D45E22F1 |         1 |         NULL |
|          5 | object::user:tester                               |         1 |         NULL |
+------------+---------------------------------------------------+-----------+--------------+
5 rows in set (0.01 sec)
```

Delete user:

```
www-data@9264da61a860:/www/nextcloud$ php occ user:delete tester
The specified user was deleted
```

After delete:
```
MySQL [nextcloud_v13]> select * from oc_storages;
+------------+---------------------------------------------------+-----------+--------------+
| numeric_id | id                                                | available | last_checked |
+------------+---------------------------------------------------+-----------+--------------+
|          1 | object::store:nc0                                 |         1 |         NULL |
|          2 | object::user:admin                                |         1 |         NULL |
|          4 | object::user:775DA7E6-9157-48EE-92AD-DE87D45E22F1 |         1 |         NULL |
|          5 | object::user:tester                               |         1 |         NULL |
+------------+---------------------------------------------------+-----------+--------------+
5 rows in set (0.00 sec)

MySQL [nextcloud_v13]> select count(*) from oc_filecache where storage=5;
+----------+
| count(*) |
+----------+
|       22 |
+----------+
1 row in set (0.00 sec)
```

### Server configuration

**Operating system**: Linux Debian 9.4
**Web server:** Nginx 1.10.3
**Database:** MySQL
**PHP version:** 7.0
**Nextcloud version:** (see Nextcloud admin page) 13.0.1.1
**Updated from an older Nextcloud/ownCloud or fresh install:** either
**Where did you install Nextcloud from:** tarfile from nextcloud.com
**Are you using external storage, if yes which one:** Swift as primary
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** LDAP but same problem with local user

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"6RvewTtNcUFNNlCSEPaR","level":3,"time":"2018-05-28T14:35:45+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined offset: 1 at \/www\/nextcloud\/apps\/admin_audit\/lib\/Actions\/Console.php#32","userAgent":"--","version":"13.0.1.1"}
```
</details>

**Comment by vpecinka** [comment]
Well, when removing record from `oc_storage` for the given `numeric_id` to make stubs in the `oc_filecache`, and running `php occ files:cleanup`, I sucessfuly delete oc_filecache entries. However, the file objects remain in the Swift storage...

**Comment by MorrisJobke** [comment]
> Set up Nextcloud using Swift as a primary storage

I guess that is missing some parts.

> The user and its oc_storage and oc_filecache should be deleted

Usually not.

This is how to set up a Nextcloud instance with object storage:

* add a second config file (only needs to end in `.config.php` so `s3.config.php`)
* put in there the normal config for the object storage:

```php
<?php

$CONFIG = [
	'objectstore' =>
		array (
			'class' => 'OC\\Files\\ObjectStore\\S3',
			'arguments' =>
				array (
					'bucket' => 'abc',
					'key' => '123',
					'secret' => 'abc',
					'hostname' => '127.0.0.1',
					'port' => '4567',
					'use_ssl' => false,
					'use_path_style' => true,
				),
		),
];
```
* then run the installation (either via `occ maintenance:install` or via the web UI)
* then you should have a working Nextcloud with the object storage as primary storage

I hope this helps to resolve your issues.

**Comment by vpecinka** [comment]
I`m not sure if we understand each other. The Swift (not S3) object primary storage works fine. Until user deletion. The problem is that Nextcloud leaves object in database and storage as well.

During normal life cycle, when user creates or deletes files, everything is ok - in the database and in the swift storage (=object are created and deleted as well). Only when I delete user (via `php occ user:delete`), the user disappears, but the object in storage and database not.

I do not understand the code to easily find the bug but I think there is something wrong with deleting user when having object storage.... Because user is removed e.g. from `oc_users` or `oc_preferences`  but not from `oc_storages` and `oc_filecache` tables.

**Comment by MorrisJobke** [comment]
> I`m not sure if we understand each other. The Swift (not S3) object primary storage works fine. Until user deletion. The problem is that Nextcloud leaves object in database and storage as well.
> 
> During normal life cycle, when user creates or deletes files, everything is ok - in the database and in the swift storage (=object are created and deleted as well). Only when I delete user (via php occ user:delete), the user disappears, but the object in storage and database not.
> 
> I do not understand the code to easily find the bug but I think there is something wrong with deleting user when having object storage.... Because user is removed e.g. from oc_users or oc_preferences but not from oc_storages and oc_filecache tables.

Okay - that one I clearly misunderstood.


@icewind1991 @rullzer Does this ring a bell for you?

**Comment by fdoumet** [comment]
The bug is in `OC\User::delete` line 229:
```
// Delete user files in /data/
if ($homePath !== false) {
   // FIXME: this operates directly on FS, should use View instead...
   // also this is not testable/mockable...
   \OC_Helper::rmdirr($homePath);
}
```
Looks like files are only actually removed when using local storage(!)

**Comment by MorrisJobke** [comment]
> Looks like files are only actually removed when using local storage(!)

cc @icewind1991 @rullzer @blizzz

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer

**Comment by MarcoStuurman** [comment]
How could this possibly not be fixed, or at least in progress? I'm in no position to say this is bad, but I just recovered my own data just by recreating an old username on my personal nextcloud server. This data is very old but was still recoverable without the use of my original password. I think object storage users should at least know there is a major security flaw in Nextcloud when they don't use encryption, which is not completely supported by Nextcloud on object storage.

**Comment by JUVOJustin** [comment]
I dont know if this is the same issue, but i currently notice the same behaviour with s3 primary storage with Nextcloud 17.0.1

**Comment by Shyndard** [comment]
Same issue with s3 primary storage with nextcloud v18.0.0

**Comment by JUVOJustin** [comment]
Is there any info about the priority? In my opinion this is a very critical bug. It is currently possible to get access to files from previously deleted users. This is a vulnerability!

**Comment by rlSimonLi** [comment]
Also observing this bug with 18.0.1. It's absurd that this is not being dealt with. For now, it seems that we have to settle with mounting the bucket directly.

**Comment by mkauttu** [comment]
This really should be fixed. It's a show stopper for my S3 primary storage plans. I must be able to delete users files. Any ideas on a work-around?

**Comment by Rapsoulis** [comment]
Came here looking for the same thing as everyone. I've around 9GB of used storage on the WebUI but my S3 Bucket is using 64GB! Which means the files haven't been deleted. I believe this should be dealt with as it is a huge deal breaker for Nextcloud + S3 storage.

**Comment by cinghaman** [comment]
I am on Nextcloud 18.0.3 and deleting the data (not even user) doesn't delete/empty the S3 storage (it has been set as primary storage)

**Comment by mkauttu** [comment]
I tried a workaround on this issue and it seems to work at some level. You need to install Impersonate -app for this to work. When user is to be deleted do following:
1. Impersonate the user to be deleted
2. Get rid of the shares so that you do not delete other users data.
3. Delete all users files and folders
4. Empty recycle bin
5. Log out from the impersonate -session
6. Delete user

**Comment by cinghaman** [comment]
> I tried a workaround on this issue and it seems to work at some level. You need to install Impersonate -app for this to work. When user is to be deleted do following:
> 
> 1. Impersonate the user to be deleted
> 2. Get rid of the shares so that you do not delete other users data.
> 3. Delete all users files and folders
> 4. Empty recycle bin
> 5. Log out from the impersonate -session
> 6. Delete user

My issue is mostly on the S3 side where the deleted files don't get removed.

**Comment by mkauttu** [comment]
> > I tried a workaround on this issue and it seems to work at some level. You need to install Impersonate -app for this to work. When user is to be deleted do following:
> > 
> > 1. Impersonate the user to be deleted
> > 2. Get rid of the shares so that you do not delete other users data.
> > 3. Delete all users files and folders
> > 4. Empty recycle bin
> > 5. Log out from the impersonate -session
> > 6. Delete user
> 
> My issue is mostly on the S3 side where the deleted files don't get removed.

@cinghaman I was referring to the original issue. Yours seems to be something else.

**Comment by suslikas** [comment]
Same problem for Nextcloud **18.0.4.2** with **\\OC\\Files\\ObjectStore\\S3** External storage support version **1.9.0**

When user removed all users files still present on disk forever.

**Comment by su-do-systems** [comment]
I am still experiencing this for Nextcloud **19.0.4** with **OC\\Files\\ObjectStore\\S3** as **primary storage**, no experience with external storage on Nextcloud.

Deleted users still all appear for me in oc_storages, I had never seen that before this thread.

**If a _username_ is deleted from the webui the files remain in object storage forever. If a user registers an account later, with the same _username_, that user is granted access to the first user's files immediately.**

I feel there should be more than username alone to a user account, a truly unique identifier should be used, even just a unique 'userid'. If users are never removed from oc_storages, if the plan was to allow 'recovery' of user accounts then administrators could simply write the original userid to the 'current iteration' of that username.

I thought I had problems with versioning and lifecycle policies but I verified some days ago that versions have all finally been actually deleted after marking them so a week ago. I have now migrated everything off this instance, emptying it totally. s3 standard is not cheap. I have another instance identical to the first that uses s3 compatible object storage at Linode where my experience is identical, just cheaper.

**Comment by IIPoliII** [comment]
I have the same issue, even if you remove it directly via the web interface it does the same thing.

Can anyone look to fix that? It's really a security issue...

**Comment by IIPoliII** [comment]
@rullzer Is there any possibilites that you look at that issue. It's still the case in NextCloud 20, and I think it's really an important security breach.

**Comment by pierreozoux** [comment]
Same issue here, maybe add you 👍 to the issue? I don't know how Nc does the prio.
