### ISSUE TITLE
TempManager on shared hosting

### ISSUE THREAD

**Issue by jankal** [nextcloud/server#9691]
### Steps to reproduce
1. Install Nextcloud on shared hosting where `/temp` is not accessible
2. Set up a cron
3. Wait some hours

### Expected behaviour
Nothing should happen.

### Actual behaviour
Massive amount of errors in the logs.

### Server configuration

**Operating system**: Debian (shared hosting at all-inkl.com)

**Web server:** Apache2

**Database:** MySQL 5.6

**PHP version:** 7; 7.1; 7.2 (tested all of those)

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated; can reproduce in pervious versions, too

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_downloadactivity: 1.2.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_saml: 1.5.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_accesscontrol
  - files_external
  - impersonate
  - passwords
  - twofactor_u2f
  - unsplash
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.zeraton.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.zeraton.de",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "debug": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** SAML

### Client configuration (error only happes when cron is called...)
**Browser:** Firefox 60

**Operating system:** Windows 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Ww7YkWsjWbul@KiQwJFYGgAAAAg","level":3,"time":"2018-05-30T17:00:01+00:00","remoteAddr":"85.13.134.57","user":"--","app":"PHP","method":"GET","url":"\/cron.php","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/w017dd1e\/cloud.zeraton.de\/lib\/private\/TempManager.php#190","userAgent":"cronBROWSE v0.92","version":"13.0.2.1"}
```
</details>

**Comment by MorrisJobke** [comment]
Set the `tempdirectory` in the `config.php`:

https://github.com/nextcloud/server/blob/1ceb081c9be32fd0bb6167171f7437852ab17207/config/config.sample.php#L1349-L1357

Or check one of the other available php.ini or env variables to set the temp folder:

https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/TempManager.php#L217-L234

**Comment by jankal** [comment]
Thanky @MorrisJobke

**Comment by dartcafe** [comment]
@MorrisJobke Wouldn't it be nice, if there would be an additional fallback or a possibility to set tempdirectory on installation or the settings (like the data dir)? The problem with the share hosters is not that the directory is not writable, it is not searchable for good reasons. This is because it is shared with other users on the same server.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Wouldn't it be nice, if there would be an additional fallback or a possibility to set tempdirectory on installation or the settings (like the data dir)?

That's already the case - see my comment above: https://github.com/nextcloud/server/issues/9691#issuecomment-393508805

**Comment by dartcafe** [comment]
@MorrisJobke 

The problem I see, is that `checkTemporaryDirectory` just checks, if the directory is writable. 
https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/TempManager.php#L256-L269

The error after installation occurs from the fact, that the temp dir on a shared host is writeable, but not searchable. 

And why not define a last fallback in the installation or data directory?

**Comment by dartcafe** [comment]
Setting tempdirectory in the config.php seem to be a hard to find solution for some users.

**Comment by MorrisJobke** [comment]
> The error after installation occurs from the fact, that the temp dir on a shared host is writeable, but not searchable.

But then we should make sure to also check for this to catch the error as early as possible and avoid the confusion here with error messages that doesn't reflect the error correctly. Mind to open a issue with some example steps on how to make a dir not searchable? I guess on Linux it's enough to withdraw the read permission on the parent folder only, right?

**Comment by dartcafe** [comment]
@MorrisJobke AFAIK the execute flag allows or denies to search the directory. This is a security setting on shared hosts. Do we need a new issue? This one describes what happens and has all steps to reproduce the issue.

**Comment by dartcafe** [comment]
And again, this is a security feature (even if it is a weak one).
