### ISSUE TITLE
Deleted files are not available in the UI. But are present in the trashbin folder.

### ISSUE THREAD

**Issue by devjb** [nextcloud/server#9706]
### Steps to reproduce
Klick on the entry "deleted files" in the files app.

### Expected behaviour
A list of the deleted files is shown

### Actual behaviour
A notification appears in the notification  bar stating "This directory is unavailable. Please check the logs or contact the Admin". The files area stays blank.
However, the trashbin is accessible on the server and if I delete files, they are put in the trashbin as expected.

No entry at all about what is happening in the logs though.

## Server configuration detail

**Operating system:** Linux 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2~bpo8+1 (2017-01-05) x86_64

**Webserver:** nginx/1.6.2 (fpm-fcgi)

**Database:** mysql 10.0.32

**PHP version:** 5.6.33-0+deb8u1
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cgi-fcgi, mysqlnd, PDO, curl, gd, json, mysql, mysqli, pam, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, redis, sqlite3, mhash, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.3
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_external_dropbox: 1.0.0
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "logtimezone": "Europe\/Berlin",
    "logfile": "\/srv\/dev-disk-by-label-Storage\/nc-data\/nextcloud.log",
    "loglevel": 1,
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "maintenance": false,
    "theme": ""
}
```

**Comment by c0fe** [comment]
Deleted files show up for me in the trash bin. So I am confused by this issue. Are you referring to activity app?

**Comment by devjb** [comment]
As stated above, no entries are in the nextcloud log.

To clarify the behaviour: the deleted files are not shown in the ui. But If you delete a file (with a sync client or with the button in the ui), you can see it on the server in the files_thrashbin directory. So the actual deleting process itself ist working, but the files are not shown in the ui.

**Comment by devjb** [comment]
Correct. But there ist a Link in the web ui, where you can normally see all deleted files. And when you access that Link, the above error happens.

Isn't this a Server issue?

**Comment by c0fe** [comment]
@devjb ok so just to under this correctly:

- You delete a folder
- Nextcloud syncs this deletion
- You no longer see the folder on desktop
- You see the directory that was deleted in the Web UI
- When you click on the deleted directory in Web UI you see the error

Correct?

**Comment by devjb** [comment]
Not really... I cannot see the deleted directory in the ui. And thus, I cannot click on it. I want to see the overview of all files that have been deleted. I'll try to make a screenshot, about which link I am talking. I think, it is still unclear, what link I am referring to. The link in the highlighted area is the link to "Deleted files".

![image](https://user-images.githubusercontent.com/2217280/40879144-d8a35df8-669b-11e8-8e60-dac060442211.png)

**Comment by c0fe** [comment]
@devjb can you please use camtasia and reproduce this issue? You can upload the video onto screencast. I tried reproducing it several times but no luck.

**Comment by devjb** [comment]
![Screencast](http://jochenbauer.net/publicpics/deletedfiles_issue.gif)

**Comment by MorrisJobke** [comment]
@devjb: And again: Please check your logs. Somewhere there needs to be something. Is the disk maybe full and thus the log entry would fill it up completely (more than what was written to the text file). Is something in the apache logs? What does the web dev console in your browser say when accessing the trash bin? There is a request which seems to fail and causing this error message.

**Comment by MorrisJobke** [comment]
This also highly looks like a setup issue as we can't reproduce this and it works on many thousand instances without problems.

**Comment by c0fe** [comment]
@devjb thanks for the video this helps clear things up for me. though unfortunately i tried it on my two instances of nextcloud and I couldn't reproduce this issue. I think this has something to do with your setup specifically. rather than Nextcloud as @MorrisJobke pointed out.

**Comment by devjb** [comment]
@MorrisJobke @c0fe , thanks for your help. Of course, it was a configuring issue in the end. I did not check the server logs, because I expected anything to be in the nc logs. But when I now read my error log of nginx, I saw the following:

```
2018/06/05 18:58:20 [error] 34297#0: *451592 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 77 bytes) in /srv/dev-disk-by-label-server-data/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 142" while reading response header from upstream, client: 127.0.0.1, server: 127.0.0.1, request: "GET /nextcloud/index.php/apps/files_trashbin/ajax/list.php?dir=%2F&sort=mtime&sortdirection=desc HTTP/1.0", upstream: "fastcgi://unix:/var/run/fpm-48b60c57-4478-4550-9bc9-4c05f8d5c2fb.sock:", host: "myhost"
```

I increased the memory limit to 1024M and after reloading nginx, the files view is working again. 

I think the problem was caused by a webdav client on my new phone five days ago. It synced a lot of photos to my nextcloud by deleting the present ones first, maybe because of the timestamp differences due to the transfer from my old phone to the new one.

That lead to a lot of deleted files which I think the view could not handle to show at once.

I consider this closed!

**Comment by Krautmaster** [comment]
I have the exactly same issue again. There is no trash item in the Nextcloud GUI.

**Comment by flowlee** [comment]
Same problem here. Everything I delete gets moved to the files_trashbin folder but nothing is shown in the GUI. The problem only affects one user though, so I think my database might be corrupt.

Where are the deleted files currently stored?

**Comment by pierpa63** [comment]
Hello,
I'm facing same problem. Just deleted a folder using web GUI, after that trashbin is no more available in the GUI. What can i check?
Thank you

**Comment by pierpa63** [comment]
Understood - at least in my case.
Trashbin exeeded some trashold size, this caused en error "Return value of OCA\\Files_Trashbin\\Sabre\\AbstractTrash::getSize() must be of the type integer, float returned". Only solution was to cleanup trashbin via occ.
Hope this helps

**Comment by kesselb** [comment]
@pierpa63 https://github.com/nextcloud/server/issues/13160
