### ISSUE TITLE
Enable occ to edit hierarchical config values, e.g. for redis configuration

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#9708]
Per [documentation](https://docs.nextcloud.com/server/11/admin_manual/configuration_server/caching_configuration.html), Redis configuration requires a config entry like this:
```
'redis' => array(
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'dbindex' => 0,
    'password' => 'secret',
    'timeout' => 1.5,
  )
```

However, the current `occ` command-line tool does not appear to be able to handle this kind of hierarhical value with name-value pairs "further down" the hierarchy. The documentation [here](https://docs.nextcloud.com/server/11/admin_manual/configuration_server/occ_command.html?highlight=occ#config-commands-label) appears to exclude it, and there seems to be some code that proactively prevents hierarchical values from being used. `import` is not a workaround as it cannot be used incrementally.

So: would be nice if `occ` was upgraded to be able to edit all configuration values, not just some.

**Comment by MorrisJobke** [comment]
@jernst Could you try out the syntax that is used in https://github.com/nextcloud/server/issues/4184#issue-218751115 ?

Does this work for you?

**Comment by MorrisJobke** [comment]
cc @nickvergessen Didn't you added this as well?

**Comment by jernst** [comment]
@MorrisJobke This seems to work:
```
occ config:system:set redis host --value=/var/run/redis/redis.sock
occ config:system:set redis timeout --value=1.5
...
```
In which case, it seems, we only need documentation that says so ...

**Comment by nickvergessen** [comment]
Yes:
```
occ config:system:get --help
Usage:
  config:system:get [options] [--] <name> (<name>)...

Arguments:
  name                                 Name of the config to get, specify multiple for array parameter
```
