### ISSUE TITLE
Invalid authorization specification: 1045 Access denied for user

### ISSUE THREAD

**Issue by MBurchard** [nextcloud/server#9719]
Aktualisierung auf 13.0.2

Doctrine\DBAL\Exception\ConnectionException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table` FROM INFORMATION_SCHEMA . COLUMNS WHERE TABLE_SCHEMA = ? AND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME <> 'utf8') AND TABLE_NAME LIKE 'oc_%'' with params ["nextcloud"]: SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'xxxxxxxx'@'%' (using password: YES)
Detaillierte Protokollmeldungen
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Doctrine\DBAL\Exception\ConnectionException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table` FROM INFORMATION_SCHEMA . COLUMNS WHERE TABLE_SCHEMA = ? AND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME <> 'utf8') AND TABLE_NAME LIKE 'oc_%'' with params ["nextcloud"]: SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'xxxxxxxx'@'%' (using password: YES)
Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community.

### Server configuration

**Operating system**: Inside official Docker image

**Web server**: Inside official Docker image

**Database**: MySQL 8.0.11

**PHP version**: Inside official Docker image

**Nextcloud version:** (see Nextcloud admin page): Update to 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install**: Update from 13.0

<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxx',
  'passwordsalt' => 'xxxxxxxx',
  'secret' => 'xxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'xxxxxxxx',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'xxxxxxxx',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'xxxxxxxx',
  'overwritewebroot' => '/cld',
  'dbtype' => 'mysql',
  'version' => '13.0.1.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'mysql',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxxx',
  'dbpassword' => 'xxxxxxxx',
  'logtimezone' => 'CET',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'xxxxxxxx',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxxxxxxx',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'xxxxxxxx',
  'mail_smtppassword' => 'xxxxxxxx',
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
);

#### Nextcloud log (data/nextcloud.log)
{"reqId":"nvd0EAqY8vpDN9LRFjXJ","level":3,"time":"2018-06-02T19:26:10+01:00","remoteAddr":"172.18.0.1","user":"--","app":"updater","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=ta2uEKY%2BBw0IKAdiRnTy1a2KJWN3PQGXBJxAO6AiJbY%3D%3Axf6eYYl5YG5JQG4NLzaivMTHYAchW2T2cvQICI8RROU%3D","message":"\\OC\\Updater::failure: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table`\tFROM INFORMATION_SCHEMA . COLUMNS\tWHERE TABLE_SCHEMA = ?\tAND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME <> 'utf8')\tAND TABLE_NAME LIKE 'oc_%'' with params [\"nextcloud\"]:\n\nSQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'cloudadmin'@'%' (using password: YES)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"nvd0EAqY8vpDN9LRFjXJ","level":3,"time":"2018-06-02T19:26:10+01:00","remoteAddr":"172.18.0.1","user":"--","app":"updater","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=ta2uEKY%2BBw0IKAdiRnTy1a2KJWN3PQGXBJxAO6AiJbY%3D%3Axf6eYYl5YG5JQG4NLzaivMTHYAchW2T2cvQICI8RROU%3D","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"nvd0EAqY8vpDN9LRFjXJ","level":1,"time":"2018-06-02T19:26:10+01:00","remoteAddr":"172.18.0.1","user":"--","app":"updater","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=ta2uEKY%2BBw0IKAdiRnTy1a2KJWN3PQGXBJxAO6AiJbY%3D%3Axf6eYYl5YG5JQG4NLzaivMTHYAchW2T2cvQICI8RROU%3D","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"nvd0EAqY8vpDN9LRFjXJ","level":1,"time":"2018-06-02T19:26:10+01:00","remoteAddr":"172.18.0.1","user":"--","app":"updater","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=ta2uEKY%2BBw0IKAdiRnTy1a2KJWN3PQGXBJxAO6AiJbY%3D%3Axf6eYYl5YG5JQG4NLzaivMTHYAchW2T2cvQICI8RROU%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"jL0aPNwIklqnLtEvMSo8","level":1,"time":"2018-06-02T19:27:05+01:00","remoteAddr":"172.18.0.1","user":"--","app":"updater","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=HmYTRtGoM%2B72a9vkhfVBLpcq74hgDdtMHeFdwK0Hk3Y%3D%3AbjUjN%2F7vVI23A7KL7LcRR%2F5nquw2a74ta4kV84I08iU%3D","message":"\\OC\\Updater::maintenanceEnabled: Turned on maintenance mode","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"jL0aPNwIklqnLtEvMSo8","level":0,"time":"2018-06-02T19:27:05+01:00","remoteAddr":"172.18.0.1","user":"--","app":"core","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=HmYTRtGoM%2B72a9vkhfVBLpcq74hgDdtMHeFdwK0Hk3Y%3D%3AbjUjN%2F7vVI23A7KL7LcRR%2F5nquw2a74ta4kV84I08iU%3D","message":"starting upgrade from 13.0.1.1 to 13.0.2.1","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"jL0aPNwIklqnLtEvMSo8","level":1,"time":"2018-06-02T19:27:05+01:00","remoteAddr":"172.18.0.1","user":"--","app":"updater","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=HmYTRtGoM%2B72a9vkhfVBLpcq74hgDdtMHeFdwK0Hk3Y%3D%3AbjUjN%2F7vVI23A7KL7LcRR%2F5nquw2a74ta4kV84I08iU%3D","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"jL0aPNwIklqnLtEvMSo8","level":3,"time":"2018-06-02T19:27:05+01:00","remoteAddr":"172.18.0.1","user":"--","app":"core","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=HmYTRtGoM%2B72a9vkhfVBLpcq74hgDdtMHeFdwK0Hk3Y%3D%3AbjUjN%2F7vVI23A7KL7LcRR%2F5nquw2a74ta4kV84I08iU%3D","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException\",\"Message\":\"An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table`\\tFROM INFORMATION_SCHEMA . COLUMNS\\tWHERE TABLE_SCHEMA = ?\\tAND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME <> 'utf8')\\tAND TABLE_NAME LIKE 'oc_%'' with params [\\\"nextcloud\\\"]:\\n\\nSQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'cloudadmin'@'%' (using password: YES)\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT DISTINCT...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/DB\\\/Connection.php(195): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT DISTINCT...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Repair\\\/Collation.php(129): OC\\\\DB\\\\Connection->executeQuery('SELECT DISTINCT...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Repair\\\/Collation.php(78): OC\\\\Repair\\\\Collation->getAllNonUTF8BinTables(Object(OC\\\\DB\\\\Connection))\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Repair.php(93): OC\\\\Repair\\\\Collation->run(Object(OC\\\\Repair))\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Updater.php(258): OC\\\\Repair->run()\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Updater.php(139): OC\\\\Updater->doUpgrade('13.0.2.1', '13.0.1.1')\\n#8 \\\/var\\\/www\\\/html\\\/core\\\/ajax\\\/update.php(212): OC\\\\Updater->upgrade()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":103}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"jL0aPNwIklqnLtEvMSo8","level":3,"time":"2018-06-02T19:27:05+01:00","remoteAddr":"172.18.0.1","user":"--","app":"updater","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=HmYTRtGoM%2B72a9vkhfVBLpcq74hgDdtMHeFdwK0Hk3Y%3D%3AbjUjN%2F7vVI23A7KL7LcRR%2F5nquw2a74ta4kV84I08iU%3D","message":"\\OC\\Updater::failure: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table`\tFROM INFORMATION_SCHEMA . COLUMNS\tWHERE TABLE_SCHEMA = ?\tAND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME <> 'utf8')\tAND TABLE_NAME LIKE 'oc_%'' with params [\"nextcloud\"]:\n\nSQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'cloudadmin'@'%' (using password: YES)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"jL0aPNwIklqnLtEvMSo8","level":3,"time":"2018-06-02T19:27:05+01:00","remoteAddr":"172.18.0.1","user":"--","app":"updater","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=HmYTRtGoM%2B72a9vkhfVBLpcq74hgDdtMHeFdwK0Hk3Y%3D%3AbjUjN%2F7vVI23A7KL7LcRR%2F5nquw2a74ta4kV84I08iU%3D","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"jL0aPNwIklqnLtEvMSo8","level":1,"time":"2018-06-02T19:27:05+01:00","remoteAddr":"172.18.0.1","user":"--","app":"updater","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=HmYTRtGoM%2B72a9vkhfVBLpcq74hgDdtMHeFdwK0Hk3Y%3D%3AbjUjN%2F7vVI23A7KL7LcRR%2F5nquw2a74ta4kV84I08iU%3D","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}
{"reqId":"jL0aPNwIklqnLtEvMSo8","level":1,"time":"2018-06-02T19:27:05+01:00","remoteAddr":"172.18.0.1","user":"--","app":"updater","method":"GET","url":"\/cld\/core\/ajax\/update.php?requesttoken=HmYTRtGoM%2B72a9vkhfVBLpcq74hgDdtMHeFdwK0Hk3Y%3D%3AbjUjN%2F7vVI23A7KL7LcRR%2F5nquw2a74ta4kV84I08iU%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"13.0.1.1"}

**Comment by MorrisJobke** [comment]
> SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'xxxxxxxx'@'%' (using password: YES)

There is not much we can do here - it looks like the DB access good denied by the database server. Make sure the account has access and then it should work.

**Comment by MBurchard** [comment]
Interesting, because it worked until I updated Nextcloud and the access is still given...

**Comment by MorrisJobke** [comment]
> Interesting, because it worked until I updated Nextcloud and the access is still given...

o.O We didn't changed anything between 13.0.0/1 to 13.0.2 in regard of that. Maybe a php module also got upgraded or the DB?

**Comment by MorrisJobke** [comment]
As this also seems to be a setup issue I would like to ask you to raise further questions in the forums: https://help.nextcloud.com
