### ISSUE TITLE
Add documentation to config.php for share_folder

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/server#9726]
https://github.com/nextcloud/server/blob/1ceb081c9be32fd0bb6167171f7437852ab17207/config/config.sample.php#L1376

e.g.
Changes to this value will only have effect on new shares. Existing shares are listed in the share_folder valid at the time of the creation of the share.

**Comment by MorrisJobke** [comment]
@schaarsc Could you hand in this change with an pull request? Thanks
