### ISSUE TITLE
WebLoginFlow: toggle password visibility

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#9729]
Ref: https://github.com/nextcloud/android/issues/2677

When typing long passwords on mobile, currently there is no possibility to check if the entered password is correct.
The last entered char is shown for a short time, but maybe a toggle is also possible?

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
We used to have this, then removed it as people complained. (Don’t remember the issue, probably in the old repo.) We now only have the "Show password" toggle when you create the admin user, and when you set a new password (to replace the need for a "repeat password" field).

But yeah, I’d say this is a good enhancement especially on mobile, and we could simply reuse what we already have on the other forms. I’m just worried people will scream again.

**Comment by tobiasKaminsky** [comment]
Working. Tested with master.
