### ISSUE TITLE
App Update Phone Sync (ocsms) 13.0.2

### ISSUE THREAD

**Issue by kaiowas1974** [nextcloud/server#9738]
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_ocsms_smsdatas CHANGE `sms_address` `sms_address` VARCHAR(512) NOT NULL': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.

**Comment by MorrisJobke** [comment]
This is a bug in the ocsms app. Please report it there. The data stored in the columns is too long for the indexes. 

See https://github.com/nextcloud/ocsms
