### ISSUE TITLE
When you configure many alternative accesses footer moves down too much and new privacy links are no more evident

### ISSUE THREAD

**Issue by danielepercivaldi** [nextcloud/server#9740]
### Steps to reproduce
1. Configure as many alternative accesses as possible (registration, facebook, google, github, etc.)
2. Go to the login page (use a human display, not a 50" inches developer / designer display ...)

### Expected behaviour
All information is visible and scrolling down is no needed to view footer and privacy links.

### Actual behaviour
Footer moves down and information is not visible but scrolling down login page

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache/2.4.18

**Database:** mysql  Ver 14.14 Distrib 5.7.22

**PHP version:** PHP 7.0.30

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from oc 9.1.7 / nc 10.* / nc 11.* / nc 12.*

**Where did you install Nextcloud from:** offline installation

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - audioplayer: 2.3.0
  - bruteforcesettings: 1.0.3
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - data_request: 1.0.0
  - dav: 1.4.6
  - deck: 0.3.1
  - drawio: 0.8.9
  - drop_account: 0.0.11
  - external: 3.0.3
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_antivirus: 1.2.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_linkeditor: 1.0.5
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.4
  - ldapcontacts: 1.1.4
  - ldaporg: 1.2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ocdownloader: 1.5.6
  - onlyoffice: 1.3.0
  - ownbackup: 17.5.0
  - password_policy: 1.3.0
  - piwik: 0.4.1
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - registration: 0.4.2
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - sociallogin: 1.7.1
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - spreed: 3.2.1
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_frommail
  - richdocuments
  - unsplash
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "eva02.intre.it"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/eva02.intre.it",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "logdateformat": "r",
        "logtimezone": "Europe\/Rome",
        "loglevel": 1,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "mail_smtpmode": "php",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\Image",
            "1": "OC\\Preview\\MP3",
            "2": "OC\\Preview\\TXT",
            "3": "OC\\Preview\\MarkDown",
            "11": "OC\\Preview\\PNG",
            "12": "OC\\Preview\\JPEG",
            "13": "OC\\Preview\\GIF",
            "14": "OC\\Preview\\BMP",
            "15": "OC\\Preview\\XBitmap",
            "16": "OC\\Preview\\Illustrator",
            "17": "OC\\Preview\\Movie",
            "18": "OC\\Preview\\Photoshop",
            "19": "OC\\Preview\\Postscript",
            "20": "OC\\Preview\\SVG",
            "21": "OC\\Preview\\TIFF",
            "22": "OC\\Preview\\Font",
            "23": "OC\\Preview\\MSOfficeDoc",
            "24": "OC\\Preview\\MSOffice2003",
            "25": "OC\\Preview\\MSOffice2007",
            "26": "OC\\Preview\\OpenDocument",
            "27": "OC\\Preview\\StarOffice",
            "28": "OC\\Preview\\PDF",
            "29": "OC\\Preview\\FB2",
            "30": "OC\\Preview\\Epub"
        },
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "updatechecker": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "updater.release.channel": "stable",
        "auth.bruteforce.protection.enabled": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "onlyoffice": {
            "jwt_header": "AuthorizationJwt"
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
+-------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                             |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                                                 |
| hasPagedResultSupport         |                                                                                                                 |
| homeFolderNamingRule          |                                                                                                                 |
| lastJpegPhotoLookup           | 0                                                                                                               |
| ldapAgentName                 | cn=admin,dc=percivaldi,dc=it                                                                                    |
| ldapAgentPassword             | ***                                                                                                             |
| ldapAttributesForGroupSearch  |                                                                                                                 |
| ldapAttributesForUserSearch   | mail;name;givenName;sn                                                                                          |
| ldapBackupHost                |                                                                                                                 |
| ldapBackupPort                |                                                                                                                 |
| ldapBase                      | dc=percivaldi,dc=it                                                                                             |
| ldapBaseGroups                | OU=groups,DC=percivaldi,DC=it                                                                                   |
| ldapBaseUsers                 | OU=users,DC=percivaldi,DC=it                                                                                    |
| ldapCacheTTL                  | 600                                                                                                             |
| ldapConfigurationActive       | 1                                                                                                               |
| ldapDefaultPPolicyDN          |                                                                                                                 |
| ldapDynamicGroupMemberURL     |                                                                                                                 |
| ldapEmailAttribute            | mail                                                                                                            |
| ldapExperiencedAdmin          | 0                                                                                                               |
| ldapExpertUUIDGroupAttr       |                                                                                                                 |
| ldapExpertUUIDUserAttr        |                                                                                                                 |
| ldapExpertUsernameAttr        | uid                                                                                                             |
| ldapGidNumber                 | gidNumber                                                                                                       |
| ldapGroupDisplayName          | cn                                                                                                              |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))                                                                                  |
| ldapGroupFilterGroups         |                                                                                                                 |
| ldapGroupFilterMode           | 0                                                                                                               |
| ldapGroupFilterObjectclass    | posixGroup                                                                                                      |
| ldapGroupMemberAssocAttr      | gidNumber                                                                                                       |
| ldapHost                      | 192.168.254.3                                                                                                   |
| ldapIgnoreNamingRules         |                                                                                                                 |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson)(objectclass=posixAccount))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                 |
| ldapLoginFilterEmail          | 1                                                                                                               |
| ldapLoginFilterMode           | 0                                                                                                               |
| ldapLoginFilterUsername       | 1                                                                                                               |
| ldapNestedGroups              | 0                                                                                                               |
| ldapOverrideMainServer        |                                                                                                                 |
| ldapPagingSize                | 500                                                                                                             |
| ldapPort                      | 389                                                                                                             |
| ldapQuotaAttribute            |                                                                                                                 |
| ldapQuotaDefault              |                                                                                                                 |
| ldapTLS                       | 0                                                                                                               |
| ldapUserDisplayName           | cn                                                                                                              |
| ldapUserDisplayName2          |                                                                                                                 |
| ldapUserFilter                | (|(objectclass=inetOrgPerson)(objectclass=posixAccount))                                                        |
| ldapUserFilterGroups          |                                                                                                                 |
| ldapUserFilterMode            | 0                                                                                                               |
| ldapUserFilterObjectclass     | inetOrgPerson;posixAccount                                                                                      |
| ldapUuidGroupAttribute        | auto                                                                                                            |
| ldapUuidUserAttribute         | auto                                                                                                            |
| turnOffCertCheck              | 0                                                                                                               |
| turnOnPasswordChange          | 0                                                                                                               |
| useMemberOfToDetectMembership | 1                                                                                                               |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------+

</details>

### Client configuration
**Browser:** firefox / chrome / edge

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
No errors
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
{"reqId":"wsFvwguRJwqyvPMKXnCC","level":3,"time":"Mon, 04 Jun 2018 22:09:57 +0200","remoteAddr":"192.168.254.131","user":"administrator","app":"PHP","method":"GET","url":"\/apps\/logreader\/poll?lastReqId=Sr4iKz9ZxNcouXnUaxNG","message":"fopen(\/var\/www\/owncloud\/data\/nextcloud.log): failed to open stream: No such file or directory at \/var\/www\/owncloud\/apps\/logreader\/lib\/Controller\/LogController.php#56","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"wsFvwguRJwqyvPMKXnCC","level":3,"time":"Mon, 04 Jun 2018 22:09:57 +0200","remoteAddr":"192.168.254.131","user":"administrator","app":"index","method":"GET","url":"\/apps\/logreader\/poll?lastReqId=Sr4iKz9ZxNcouXnUaxNG","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Error while opening \\\/var\\\/www\\\/owncloud\\\/data\\\/nextcloud.log\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/logreader\\\/lib\\\/Controller\\\/LogController.php(83): OCA\\\\LogReader\\\\Controller\\\\LogController->getLogIterator()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/logreader\\\/lib\\\/Controller\\\/LogController.php(111): OCA\\\\LogReader\\\\Controller\\\\LogController->getLastItem()\\n#2 [internal function]: OCA\\\\LogReader\\\\Controller\\\\LogController->poll('Sr4iKz9ZxNcouXn...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\LogReader\\\\Controller\\\\LogController), 'poll')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\LogReader\\\\Controller\\\\LogController), 'poll')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\LogReader\\\\\\\\C...', 'poll', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/logreader...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(37): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/logreader\\\/lib\\\/Controller\\\/LogController.php\",\"Line\":60}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"UZBUoE37UFaEzPn3UR6e","level":1,"time":"Mon, 04 Jun 2018 22:10:08 +0200","remoteAddr":"192.168.254.131","user":"administrator","app":"admin_audit","method":"GET","url":"\/logout?requesttoken=%2BGDQwNGCxuZqQiSj6KZf\/GiGKZsg2qhS6Ag0DvN\/Z9Y%3D%3AuwSDoqK0rdMoN2XKsIlu1wbrbd5LosM6hkdZJdhGMJc%3D","message":"Logout occurred","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"hYZzn83sPpP29x0r1O0X","level":0,"time":"Mon, 04 Jun 2018 22:10:10 +0200","remoteAddr":"192.168.254.131","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/owncloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"hYZzn83sPpP29x0r1O0X","level":0,"time":"Mon, 04 Jun 2018 22:10:10 +0200","remoteAddr":"192.168.254.131","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/owncloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"hYZzn83sPpP29x0r1O0X","level":0,"time":"Mon, 04 Jun 2018 22:10:10 +0200","remoteAddr":"192.168.254.131","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/owncloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"hYZzn83sPpP29x0r1O0X","level":0,"time":"Mon, 04 Jun 2018 22:10:10 +0200","remoteAddr":"192.168.254.131","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/owncloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.181 Safari\/537.36","version":"13.0.2.1"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log:
Navigated to https://eva02.intre.it/login
core.js?v=11bd8361-126:7 JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://eva02.intre.it/core/vendor/purify.min.js.map
```
</details>

**Comment by MorrisJobke** [comment]
@danielepercivaldi Could you post a screenshot?


We removed the header with "Alternative logins" in 14 and gain at least one line in height.

**Comment by danielepercivaldi** [comment]
Hi @MorrisJobke .
The screenshot:
![immagine](https://user-images.githubusercontent.com/8720648/40968412-c5779ebc-68b5-11e8-9447-7b73a4b9c38f.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by danielepercivaldi** [comment]
What about the proposal below?
1. remove privay link from the footer
2. add "I agree with" checkbox + links under login button
3. remove (?) "stay connected" checkbox (is it usefull?)
4. don't care anymore about the footer ...
![immagine](https://user-images.githubusercontent.com/8720648/41090853-86376188-6a45-11e8-9b4e-07877dc2bfce.png)

**Comment by jancborchardt** [comment]
We also removed the »Remember me« checkbox for 14, so another row won.

The solution with checking a box on every _log in_ makes little sense, as you should accept the legal stuff while registering, not on _every_ log in process. It will also be different on mobile again (which is even more widely used), where we can’t possibly show all info at the same time and people just need to scroll.
