### ISSUE TITLE
commit tags missing and don't match nc version numbers

### ISSUE THREAD

**Issue by tchncs** [nextcloud/server#975]
Hi there, i just experienced, that the tagging somehow stops at v9.1.0RC1.
I just updated my master branch (why is there no develop for developement?) and landed in 11a.
My current releasenumber is 9.2.0.2 and stable10 (is this 10rc? there are other stable10 branches!) is 9.1.0.15. So i am somehow stuck and it seems like my only way is forward, to the alpha where i have to hope that 30% of my used apps are just incompatible because their configured versionnumber.

I hope the developers can enhance their tagging strategies a bit since i really don't see any way out of this as described.

kind regards. :)

**Comment by LukasReschke** [comment]
> I just updated my master branch (why is there no develop for developement?) 
> and landed in 11a.

Master is development and will be branched in stable[0-9]+ branch before release.

> My current releasenumber is 9.2.0.2 and stable10 (is this 10rc? there are other stable10 branches!) is 9.1.0.15. So i am somehow stuck and it seems like my only way is forward, to the alpha where i have to hope that 30% of my used apps are just incompatible because their configured versionnumber.

Stable10 branch is the current development of the stable10 releases. You can use a tag if you want but it's easier to just use daily builds from https://download.nextcloud.com/server/daily/ as that also includes all shipped apps.

The version numbers shown in version.php are also cosmetically and you should pretty much ignore them. 9.1 is 10.0, 9.2 is 11.0. I added the missing tag for  v10.0RC1

**Comment by tchncs** [comment]
Thanks for clarifying.
Well, then i am on 11.0 but on an early state. I guess.
But it showed it as v10rc1 in the past, i am pretty sure about this.

So i should just downgrade the version.php to be able to update?
