### ISSUE TITLE
Secondary email in personal infos

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#9754]
A secondary email in personal info for backup-security purpose would be nice...

I've just spent 2 fulls days trying to recover a gmail address, and despise two factor auth, gmail keept saying i can't recover the password. 

Hopefully, i had a secondary mail as a backup option...

- In the personnal info, a secondary email
- In the recover option, primary or secondary email could be used

Just a hintch

**Comment by blizzz** [comment]
Not getting the problem on Nextcloud side. Were you using the IMAP user backend?

Otherwise I understand you did not have access to the Gmail account. Unless you didn't loose the password for your Nextcloud account, this would not have been an issue? Since you can change the mail address in the personal settings.

**Comment by stratege1401** [comment]
the issue, as a test purpose, was to create a server test with a google1admin account who lost his password and his unable to manage his server from the browser-side.
Some admin rely on a 3rd party for installation or ssh access, so for them, most of the time, the browser admin side is the only option.
So, if the google1admin account is freeze for whatever reason, like loosing a password and having google (or whatever provider) not been able to give you permission to retrieve usage, this mean you also loose your nextcloud only admin account, and one more time, rely on 3rd party to regain control.

So, a secondary email as an admin or user would be usefull.

**Comment by jancborchardt** [comment]
A secondary email seems good, some services use that. (Another option would be to use the phone number as fallback, but I guess that might not be possible with own server and PHP only. ;)

**Comment by stratege1401** [comment]
phone number is asked, but sms cost might be an hassles...

secondary email can be used also for a managed account:

ecemple:
My client, a small restaurant is depending more and more on a software suite for backoffice ( client invoices, menu editor, VAT and TAX declaration, and so on ...).
Using some imaging software, backup files are created and thanks to app desktop saved to a nextcloud server...
But, the client doesnt seem to care to manage his account, but need to be the primary user. in that case, i use email1
As the nextcloud manager, i manage the account, check files integrity, ... do the "stuff". But as i am overbooked by a lot of stuff, and a lot of bugs, i have lost/forget the password of this managed account. Here come email2 (mine) to ask/recover password, while in paralell the client is warned throught email1

See the point !

**Comment by skjnldsv** [comment]
@jancborchardt I don't think it actually find a real use on nextcloud.
I think this is not on our roadmap :)

Thoughts on closing?

**Comment by jancborchardt** [comment]
Just checked Twitter, Github, Discourse and Meetup. Of those, only Github seems to offer the ability to set multiple email addresses.

And since it’s not very common for regular people to have multiple email addresses, we should rather have another way of a backup reset function. Like e.g. the mobile phone number I mentioned above.

**Comment by skjnldsv** [comment]
@jancborchardt so, closing and creating a new issue about supporting phone number?

**Comment by jancborchardt** [comment]
@skjnldsv I’d say so, yes – if it’s feasible?

**Comment by skjnldsv** [comment]
@jancborchardt no idea, but we should open a new issue then :)

**Comment by skjnldsv** [comment]
@jancborchardt we already have a phone number xD

**Comment by jancborchardt** [comment]
@skjnldsv yes we do, but it’s not usable for resetting yet. :)
