### ISSUE TITLE
cloud sub path domain

### ISSUE THREAD

**Issue by flpfontes** [nextcloud/server#9759]
I installed nextcloud in the /var/www/html/nextcloud folder using the following tutorial: https://websiteforstudents.com/install-nextcloud-on-ubuntu-16-04-lts-with-apache2-mariadb-php-7-1-and-lets-encrypt-ssl-tls/

Now every time I access my my-domain.com it redirects me to my-domain.com/nextcloud How do I leave my-domain.com empty to be added to another website? My server is ubuntu 17 running apache

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
