### ISSUE TITLE
Unable to access to Personal->Additionnal settings pages since 13.0.2

### ISSUE THREAD

**Issue by Oliv4945** [nextcloud/server#9763]
### Steps to reproduce
1. Upgrade docker image from 13.0.0 to 13.0.2
2. Open `settings/user/additional` page

### Expected behaviour
Additional settings are displayed

### Actual behaviour
The frame is blank with only a "1" displayed on the top left corner
The HTML is: `<div id="">1</div>`

### Server configuration
**Operating system**: Up to date nextcloud docker fpm image

**Web server:** Nginx 1.13.8 in docker

**Database:** MariaDB 5.5.57

**PHP version:** 7.1.17

**Nextcloud version:** (see Nextcloud admin page) 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Was working on 13.0.0 before the update

**Where did you install Nextcloud from:** docker

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - contacts: 2.1.5
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - music: 0.6.1
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - passman: 2.1.4
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - serverinfo
  - systemtags
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "next.iobook.net",
            "176.137.129.243"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/next.iobook.net",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "installed": true,
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "activity": {
            "enabled": "no",
            "installed_version": "2.6.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "57"
        },
        "comments": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "2.1.5",
            "types": ""
        },
        "core": {
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "installedat": "1520354691.5143",
            "lastcron": "1528291781",
            "lastupdateResult": "[]",
            "lastupdatedat": "1528289886",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "8cfcf8f5825757dc949b46ae9bf65f49",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.4.6",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "no",
            "installed_version": "0.3.1",
            "types": ""
        },
        "encryption": {
            "masterKeyId": "master_e4d5bee6",
            "publicShareKeyId": "pubShare_e4d5bee6",
            "recoveryKeyId": "recoveryKey_e4d5bee6"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.5.1",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "music": {
            "enabled": "yes",
            "installed_version": "0.6.1",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "passman": {
            "enabled": "yes",
            "installed_version": "2.1.4",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "last_report": "{\"id\":\"ocjzxa1zqd0x\",\"items\":[[\"server\",\"version\",\"13.0.0.14\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"ajax\"],[\"php\",\"version\",\"7.1.14\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",535822336],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"5.5.57\"],[\"database\",\"size\",17301504],[\"apps\",\"activity\",\"disabled\"],[\"apps\",\"comments\",\"disabled\"],[\"apps\",\"contacts\",\"2.1.3\"],[\"apps\",\"dav\",\"1.4.6\"],[\"apps\",\"deck\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.3.1\"],[\"apps\",\"federation\",\"disabled\"],[\"apps\",\"files\",\"1.8.0\"],[\"apps\",\"files_pdfviewer\",\"1.2.0\"],[\"apps\",\"files_sharing\",\"1.5.0\"],[\"apps\",\"files_texteditor\",\"2.5.1\"],[\"apps\",\"files_trashbin\",\"1.3.0\"],[\"apps\",\"files_versions\",\"1.6.0\"],[\"apps\",\"files_videoplayer\",\"1.2.0\"],[\"apps\",\"firstrunwizard\",\"2.2.1\"],[\"apps\",\"gallery\",\"18.0.0\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"lookup_server_connector\",\"1.1.0\"],[\"apps\",\"music\",\"0.5.6\"],[\"apps\",\"nextcloud_announcements\",\"1.2.0\"],[\"apps\",\"notifications\",\"2.1.2\"],[\"apps\",\"oauth2\",\"1.1.0\"],[\"apps\",\"passman\",\"2.1.4\"],[\"apps\",\"password_policy\",\"1.3.0\"],[\"apps\",\"provisioning_api\",\"1.3.0\"],[\"apps\",\"serverinfo\",\"disabled\"],[\"apps\",\"sharebymail\",\"1.3.0\"],[\"apps\",\"survey_client\",\"1.1.0\"],[\"apps\",\"systemtags\",\"disabled\"],[\"apps\",\"tasks\",\"0.9.6\"],[\"apps\",\"theming\",\"1.4.1\"],[\"apps\",\"twofactor_backupcodes\",\"1.2.3\"],[\"apps\",\"updatenotification\",\"1.3.0\"],[\"apps\",\"workflowengine\",\"1.3.0\"],[\"stats\",\"num_files\",9154],[\"stats\",\"num_users\",2],[\"stats\",\"num_storages\",3],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",2],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",0],[\"files_sharing\",\"num_shares_user\",0],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",0],[\"files_sharing\",\"num_shares_link_no_password\",0],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"yes\"]]}",
            "last_sent": "1526575791",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.6",
            "types": ""
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": ""
        },
        "updatenotification": {
            "contacts": "2.1.5",
            "core": "13.0.2.1",
            "enabled": "yes",
            "files_pdfviewer": "1.2.1",
            "installed_version": "1.3.0",
            "music": "0.6.1",
            "theming": "1.4.5",
            "types": "",
            "update_check_errors": "0"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        }
    }
}

</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 60.0.1 and Chrome 67.0.3396.62

**Operating system:** Windows 10 & Debian 9

#### Web server error log
<details>
<summary>Web server error log</summary>

172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /settings/user/additional HTTP/1.1" 200 4529 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /css/core/7f0b-0757-jquery-ui-fixes.css?v=ce7e6d19-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /css/core/7f0b-0757-server.css?v=ce7e6d19-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /css/core/7f0b-0757-share.css?v=ce7e6d19-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /css/core/7f0b-0757-jquery.ocdialog.css?v=ce7e6d19-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /css/settings/7f0b-0757-settings.css?v=ce7e6d19-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /js/core/merged-template-prepend.js?v=ce7e6d19-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /js/core/merged-share-backend.js?v=ce7e6d19-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /js/notifications/merged.js?v=ce7e6d19-0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /apps/theming/styles?v=0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:35 +0000] "GET /apps/theming/js/theming?v=0 HTTP/1.1" 200 196 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:36 +0000] "GET /avatar/oliv/32?v=0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:36 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
2018/06/06 13:36:36 [error] 5#5: *6237 access forbidden by rule, client: 172.x.x.xx1, server: , request: "GET /data/.ocdata?t=1528292196727 HTTP/1.1", host: "next.iobook.net"
172.x.x.xx1 - - [06/Jun/2018:13:36:36 +0000] "GET /data/.ocdata?t=1528292196727 HTTP/1.1" 403 169 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:36 +0000] "GET /cron.php HTTP/1.1" 200 51 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:36 +0000] "PROPFIND /remote.php/webdav HTTP/1.1" 207 1332 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:36 +0000] "GET /heartbeat HTTP/1.1" 200 31 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"
172.x.x.xx1 - - [06/Jun/2018:13:36:37 +0000] "GET /settings/ajax/checksetup HTTP/1.1" 200 378 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "172.x.x.xx2"

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 304
172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 304
172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 304
172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 304
172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 304
172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 304
172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 304
172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 304
172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 304
172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 200
172.x.x.xx3 -  06/Jun/2018:13:36:35 +0000 "GET /index.php" 304
172.x.x.xx3 -  06/Jun/2018:13:36:36 +0000 "GET /ocs/v2.php" 200
172.x.x.xx3 -  06/Jun/2018:13:36:36 +0000 "GET /cron.php" 200
172.x.x.xx3 -  06/Jun/2018:13:36:36 +0000 "PROPFIND /remote.php" 207
172.x.x.xx3 -  06/Jun/2018:13:36:36 +0000 "GET /index.php" 200
172.x.x.xx3 -  06/Jun/2018:13:36:36 +0000 "GET /index.php" 200
</details>

#### Browser log
<details>
<summary>Browser log</summary>
No javascript error in the browser console
</details>

**Comment by MorrisJobke** [comment]
This is caused by the passman app. It has an empty personal settings page, that causes that there appears this 1. It's not the best way to deal with an empty setting, but fixing this in the app would solve the issue.

https://github.com/nextcloud/passman/blob/0b6f427adc4a941e6832366cf534580a18373054/personal.php#L2-L1

Could you please report it to that repo then: https://github.com/nextcloud/passman

**Comment by Oliv4945** [comment]
I have disabled personal settings in Passman code and it works, thank you
for the hint
