### ISSUE TITLE
No Notification of app-Update when Update is incombatible 

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#977]
### Steps to reproduce
1. Go to the apps as admin
### Expected behaviour

Nothing
### Actual behaviour

NC shows me
"You have 1 app update pending"
### Server configuration

**Operating system**: 
ubuntu 16.04 lts

**Web server:** 
apache2

**Database:** 
mariadb

**PHP version:** 
7

**Nextcloud version:** 
9.53

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

---

Since News 9.0.0 is available in the appstore, I get the notice "You have 1 app update pending"

News 9.0.0 and now News 9.0.1 are ownly compatible with Nextcloud >= 10

An enhancement would be, that only updates wich are compatible withe your Nc-Version are announced as updatable...

**Comment by nickvergessen** [comment]
Should not happen anymore, because apps can specify which server version they are compatible with
