### ISSUE TITLE
Missing artifacts for 12.0.8

### ISSUE THREAD

**Issue by crazy-max** [nextcloud/server#9785]
Hi,

Some artifacts are missing for the release 12.0.8 at https://download.nextcloud.com/server/releases/ :

![image](https://user-images.githubusercontent.com/1951866/41100696-50929abc-6a62-11e8-9bab-54422ee90eab.png)

Can you fix that ? Thanks

**Comment by rullzer** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
fixed
