### ISSUE TITLE
Easier Server migration

### ISSUE THREAD

**Issue by Serverfrog** [nextcloud/server#979]
It would be awesome if there was a easier Possibility for a server migration.
What i mean by that is that if i would like to transfer all my nextcloud data to a new server.

There would be two approaches:
- A Migration Service
  - The Old server Enabled it on his Admin Page for one Server Address
  - The new Server hat inside of the Installation a Option to Import the Data from the old server
- Backup Import
  - a Easier method to Export and Import of Backups.
  - The best would be a Import function in the Installation

The Last one seems more efficient because of the use of existing Technologie.

**Comment by MorrisJobke** [comment]
This is what we want to accomplish in the end with #6773 - thus closing this as duplicate.
