### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by alfioalfio** [nextcloud/server#9795]
### Steps to reproduce
1. Upgraded from 13.0  to 13.0.2
2. Error message

#### Web server error log
<details>
Doctrine\DBAL\Exception\ConnectionException: An exception occurred while executing 'UPDATE `oc_appconfig` SET `configvalue` = ? WHERE (`appid` = ?) AND (`configkey` = ?) AND (`configvalue` <> ?)' with params ["", "files_pdfviewer", "types", ""]: SQLSTATE[42000]: Syntax error or access violation: 1142 UPDATE command denied to user 'Sql1106696'@'89.46.104.186' for table 'oc_appconfig'
<summary>Web server error log</summary>

**Comment by MorrisJobke** [comment]
> SQLSTATE[42000]: Syntax error or access violation: 1142 UPDATE command denied to user 'Sql1106696'@'89.46.104.186' for table 'oc_appconfig'

The DB user has not the needed permissions to update that table. Please check that the DB user in Nextcloud has those and try again.

For further setup related questions please reach out in our forums at https.//help.nextcloud.com
