### ISSUE TITLE
updatenotification: l10n: Strange strings on Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#9799]
Since today there are some strings at Transifex which do not belong there IMHO.

![grafik](https://user-images.githubusercontent.com/2069590/41155458-66897946-6b1e-11e8-8ac4-d8da98658025.png)

Found them in 
https://github.com/nextcloud/server/blob/132597bbd3e3e1633fa83c77c268242d5c59a4f4/apps/updatenotification/js/merged.js#L7

Could someone please check?

**Comment by MorrisJobke** [comment]
@rakekniven Could you tell me in which resource they are? (see the details right on transifex)

**Comment by rakekniven** [comment]
Here you go

![grafik](https://user-images.githubusercontent.com/2069590/41157413-f2daa1fc-6b25-11e8-8909-a644160b8382.png)

**Comment by MorrisJobke** [comment]
Yes - this is due to minified code where the functions get minified to one letter names which result then in this. Let me have a look on how to turn this off.

**Comment by rakekniven** [comment]
Same strings are now in module "oauth2" as well. @MorrisJobke  Please check. Thank you.

**Comment by MorrisJobke** [comment]
Found it and fixed - waiting for docker hub to build the new container

**Comment by MorrisJobke** [comment]
Fixed via https://github.com/nextcloud/docker-ci/commit/ea5ff0b187bb4e102cf2363142a8d75b9f40ea04 and will trigger the re-run once it is done.

Thanks for noticing.

**Comment by rakekniven** [comment]
Hello @MorrisJobke 
Same for https://github.com/nextcloud/bruteforcesettings/blob/master/js/bruteforcesettings.js L7

Could you fix this as well?

**Comment by MorrisJobke** [comment]
> Could you fix this as well?

🙈 Obviously forgot it - sorry. Now it is included: https://github.com/nextcloud/docker-ci/commit/ea653cb0936a71051a3246587aeb02764b596e42
