### ISSUE TITLE
NextCloud Fails to Upload Large Files - Contentiously stops and needs to be forced synced every 5 minutes

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#9809]
(Solved)

**Comment by ProPublic1110** [comment]
Bump?

**Comment by Fray2000** [comment]
I have the same issue, some files are not supported by the server such as xxx.mca and xxx.dat files. It also fails when it has to upload a lot of small files. 

OS: Dietpi (https://dietpi.com/)
Hardware : Raspberry pi 2 b+
Database : Mysql with data on external hard drive
Steps to reproduce : A tutorial dedicaed to the installation of nextcloud on Rpi
https://www.youtube.com/watch?v=O8h_Dlf2MOA

Summarized commands from the video :

        cd /
	rm /var/www/nextcloud/config/config.php
	mysql -u root -pdietpi
	create database nextcloud;
	drop user 'oc_admin'@'localhost';
	flush privileges;
	grant all privileges on nextcloud.* to 'oc_admin'@'localhost'
	identified by 'myserver';
	flush privileges;
	exit;
	mkfs.ext4 /dev/sda
	nano /etc/fstab
	/dev/sda /datastore ext4 defaults 0 0
	mkdir /datastore
	mount -a
	chown www-data:www-data /datastore
	chmod 0770 /datastore
Image of the issue
[https://imgur.com/a/eBK2yoC](url)

**Comment by MorrisJobke** [comment]
> I have the same issue, some files are not supported by the server such as xxx.mca and xxx.dat files. It also fails when it has to upload a lot of small files.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
