### ISSUE TITLE
Nextcloud Sync with Windows and Android App doesnt work [GER / ENG]

### ISSUE THREAD

**Issue by DekoLP** [nextcloud/server#9811]
Hallo,

vor ein paar Tagen ist die Laufzeit meines Webspaces abgelaufen. Heute habe ich die Laufzeit wieder erneuert (Daten sind noch alle vorhanden). Aber nun wird mir immer gesagt wenn ich mich bei der Windows und der Android App einloggen will, dass die Daten falsch sind obwohl sie zu 100% richtig sind. Ich kann mich NUR im Browser einloggen. Die Fehlernummer ist 401.

Bevor das Webspace abgelaufen ist ging noch alles.

Ich hoffe ihr könnt mir helfen.

~ Deko

----------------------------------------------------------------------------------------------------------------
Hello,

A few days ago my webspace expired. Today I renewed the runtime (data is still available). But now I am always told if I want to log in to the Windows and the Android App that the data is wrong, even though they are 100% correct. I can ONLY log in to the browser. The error is 401.

Everything worked before the webspace expired.

I hope you can help me.

~Deko

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
