### ISSUE TITLE
Share folders doesnt work anymore

### ISSUE THREAD

**Issue by DekoLP** [nextcloud/server#9813]
### Steps to reproduce
1. Share a folder
2. open the downloadlink
3. Password required (without reason)

### Expected behaviour
All files in the folder should be visible

### Actual behaviour
Nextcloud wants to know a password and I dont know it (tried already my own password)

**Comment by c0fe** [comment]
Need logs to look into this problem further.

**Comment by DekoLP** [comment]
error log: https://ghostbin.com/paste/4og4n

**Comment by DekoLP** [comment]
Browser Log: https://ghostbin.com/paste/d3g33

**Comment by DekoLP** [comment]
Errors which appears in the log of the hoster: https://images-ext-2.discordapp.net/external/2JgdubP6ApaawVBIE29WpcC_Y8jKwdZBdSEznUWD7og/https/image.prntscr.com/image/Ng-jkjPcSgSTSBLvCcr9Xg.png?width=1167&height=559

**Comment by c0fe** [comment]
i am hitting capacity problems can't read the logs

**Comment by c0fe** [comment]
Error shows that there is an issue with the .htaccess log and where your data directory is supposed to be. Check those two areas and make sure you haven't moved the data directory.

**Comment by DekoLP** [comment]
well I dont even find the htaccess log. What should be wrote in the file?

**Comment by c0fe** [comment]
There is no .htaccess log. You need to have an .htaccess file

**Comment by DekoLP** [comment]
Well I dont have one.

**Comment by c0fe** [comment]
There is your problem. You should have one. 

I would recommend you start from the first step in the installation instructions and go through it matching what your setup is, when you find a discrepancy there could be your culprit.

**Comment by DekoLP** [comment]
So I now need to make uninstall everything and install everything again?

**Comment by DekoLP** [comment]
I now installed it in a other folder. I dont find a htaccess file. In which folder should this file be

**Comment by DekoLP** [comment]
But I now know: in the new installed nextcloud is the same errors.

**Comment by DekoLP** [comment]
Hello, I finally know the mistake. My hoster says this is the error: the file permission of the "data" folder is apparently changed back to 770 on the call. But Nextcloud does not seem to work with this permission configuration. If you find a way to disable this, you could test the functionality further. We recommend to contact the NextCloud support again.
