### ISSUE TITLE
No update 13.0.3 possible

### ISSUE THREAD

**Issue by jgrete** [nextcloud/server#9815]
### Steps to reproduce
1.  Got Notification: update 13.0.3 available
2. go to preferences and notice your system is the latest one (but it **is** 13.0.2)
3.

### Expected behaviour
After getting a notification that an update is available I would expect to be able to update...

### Actual behaviour
No update possible?!?!

## Server configuration detail

**Operating system:** Linux 4.4.132-53-default #1 SMP Wed May 23 06:57:07 UTC 2018 (036cd2f) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.2.13

**PHP version:** 7.0.7
Modules loaded: Core, date, libxml, pcre, filter, hash, Reflection, SPL, session, SimpleXML, standard, xml, mysqlnd, apache2handler, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, exif, mcrypt, mysqli, openssl, pcntl, PDO, pdo_mysql, pdo_sqlite, posix, redis, shmop, sockets, sqlite3, tidy, tokenizer, xmlreader, xmlwriter, xsl, zip, zlib, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - announcementcenter: 3.2.1
 - apporder: 0.4.1
 - bookmarks: 0.11.0
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - camerarawpreviews: 0.5.3
 - caniupdate: 0.1.2
 - checksum: 0.4.0
 - circles: 0.13.6
 - cms_pico: 0.9.7
 - comments: 1.3.0
 - contacts: 2.1.5
 - data_request: 1.0.0
 - dav: 1.4.6
 - deck: 0.3.1
 - drawio: 0.8.9
 - drop_account: 0.0.11
 - dropit: 0.1.1
 - end_to_end_encryption: 1.0.5
 - external: 3.0.3
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_antivirus: 1.2.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_linkeditor: 1.0.5
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.2.1
 - files_reader: 1.2.3
 - files_retention: 1.2.0
 - files_rightclick: 0.8.4
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trackdownloads: 1.2.2
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - flowupload: 0.0.7
 - gallery: 18.0.0
 - gpxedit: 0.0.8
 - gpxmotion: 0.0.6
 - gpxpod: 2.2.2
 - groupfolders: 1.2.0
 - impersonate: 1.0.4
 - issuetemplate: 0.3.0
 - keeporsweep: 0.1.6
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.8.1
 - metadata: 0.6.0
 - mood: 0.3.3
 - music: 0.6.1
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ocdownloader: 1.5.6
 - ojsxc: 3.4.0
 - ownbackup: 17.5.0
 - ownpad: 0.6.6
 - passman: 2.1.4
 - password_policy: 1.3.0
 - polls: 0.8.1
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - qownnotesapi: 17.5.0
 - quicknotes: 0.1.3
 - quota_warning: 1.2.0
 - radio: 0.6.1
 - ransomware_protection: 1.1.0
 - registration: 0.4.2
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - smb_test: 0.1.0
 - socialsharing_diaspora: 1.0.2
 - socialsharing_email: 1.0.3
 - socialsharing_facebook: 1.0.2
 - socialsharing_googleplus: 1.0.2
 - socialsharing_twitter: 1.0.2
 - spreed: 3.2.2
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - telephoneprovider: 1.0.1
 - theming: 1.4.5
 - theming_customcss: 1.0.0
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_usage_report: 1.0.1
 - weather: 1.5.1
 - workflowengine: 1.3.0
Disabled:
 - encryption
 - limit_login_to_ip
 - spreedme
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "g*********o",
        "cloud-server.*****",
        "hal",
        "hal.*****"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:**************",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "thema1",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "timeout": 0
    },
    "log_rotate_size": 13107200,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
    "loglevel": 2,
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by jgrete** [comment]
![screenshot_20180609_204123](https://user-images.githubusercontent.com/14105933/41195032-3c3a94fa-6c26-11e8-9b5b-9adf300354e5.png)

**Comment by tflidd** [comment]
They found a bug last minute that has impact on a few systems. So they preferred to stopped the current roll-out and put on a fixed version next week:
https://github.com/nextcloud/server/pull/9802

If you really need this update quickly and you are not affected by the mentioned bug, you can probably go ahead an install 13.0.3 from https://nextcloud.com/changelog/ manually.
If not or if you are in doubt, wait for the release next week.

**Comment by raimund-schluessler** [comment]
But shouldn't the update notification app then not show the notifciation to update?

**Comment by jgrete** [comment]
@tflidd 
thanks for clarification
