### ISSUE TITLE
Move image cache clearing to background job

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#9825]
While doing an upgrade a big instance the image cache clearing takes a lot of time. Is there a way to move this to a background job (also the SCSS and JS compilation), but this takes a lot less time.

```
2018-06-11T04:46:33+00:00 Repair info: Image cache cleared
2018-06-11T05:12:51+00:00 Repair info: SCSS cache cleared
2018-06-11T05:12:53+00:00 Repair info: JS cache cleared
2018-06-11T05:12:53+00:00 Update successful
```

@rullzer @juliushaertl 

There seem to be million of files inside `[data]/appdata_[instance_id]/{css,preview,js,avatar}`

This would improve the update performance drastically from over 20 minutes to only a few minutes.

**Comment by rullzer** [comment]
> There seem to be million of files inside [data]/appdata_[instance_id]/{css,preview,js,avatar}

There are supposed to be a lot of files. As the previews are stored there. The number of files should be significantly less when you don't consider the preview folder.

Same for avatars this scales with the number of users ;) And they shoudl be there.

**Comment by rullzer** [comment]
```
2018-06-11T04:46:33+00:00 Repair info: Image cache cleared
2018-06-11T05:12:51+00:00 Repair info: SCSS cache cleared
2018-06-11T05:12:53+00:00 Repair info: JS cache cleared
2018-06-11T05:12:53+00:00 Update successful
```

I must say it is kind of surprising the cleaning the SCSS  cache takes them so long. As this is basically 1 reset to the cache.
And then looping over all SCSS files. Which scales with the number of apps (roughly). So this should almost be instanteneous. As it is identical to the js repair step basically.

**Comment by rullzer** [comment]
It sounds more to me that at some point the appdata was messed with.

Run a: `./occ files:scan-app-data` first

**Comment by rullzer** [comment]
Also they can't be moved to background jobs as then you could have a broken instance until the background job runs ;)

(broken as in old JS and/or old CSS)

**Comment by juliushaertl** [comment]
Deleting the files seems to be pretty expensive, it already takes around 1.4s on my dev machine for 51 SCSS files. https://blackfire.io/profiles/6ccbedd7-8995-4f2a-b866-9618639f2389/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=OC%5CRepair%3A%3Arun&callname=main()

As @rullzer said, a background job doesn't make much sense here, since we want to ensure that all the cache is cleaned once the first user requests the frontend.

**Comment by MorrisJobke** [comment]
> As @rullzer said, a background job doesn't make much sense here, since we want to ensure that all the cache is cleaned once the first user requests the frontend.

Ah ... I misread the info here. You are right the long running process is the SCSS cleanup and not the image cleanup. Let me see.

**Comment by MorrisJobke** [comment]
No feedback for now -> closing.
