### ISSUE TITLE
Upgrade Nextcloud 13.0.2 -> 13.0.4 --> "No apps found for your version"

### ISSUE THREAD

**Issue by fettfoen** [nextcloud/server#9827]
I upgraded (manually proceed like https://docs.nextcloud.com/server/13/admin_manual/maintenance/manual_upgrade.html) my nextcloud 13.0.2 to 13.0.4. Now when im broswing to APPs im not able to install APPs. Just showing the message "No apps found for your version"

I have NO notifications in nextcloud.log!

**Comment by MorrisJobke** [comment]
There was an issue with the App Store this afternoon which was fixed. Should work again
