### ISSUE TITLE
IRequest::getPathInfo() returns empty string when pretty URLs are used

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#983]
This causes the notifications app to load its `notification.js` file and therefore reload the 2FA pages every 5sec. Hence, I get bug reports in https://github.com/ChristophWurst/twofactor_totp because the page reloads while people enter their TOTP code.

### Steps to reproduce
1. Install and configure nc to use pretty URLs (without the `index.php` prefix)
2. Install and enable a 2FA app
3. Load the 2FA challenge page and wait a few seconds

### Expected behaviour
The page should *not* reload.

### Actual behaviour
The page reloads.

### Server configuration
**Operating system**:

**Web server:**
Apache

**Nextcloud version:** (see Nextcloud admin page)
10

@nickvergessen as discussed

cc @LukasReschke

**Comment by LukasReschke** [comment]
Could reproduce under Ubuntu, this is caused by https://github.com/nextcloud/server/blob/8f3dc0ba43123915c25ff9b328104d6fe4faf9e9/lib/private/AppFramework/Http/Request.php#L703-L705 since `PATH_INFO` is set to a zero value.

**Comment by LukasReschke** [comment]
I'd vote for removing the check for $_SERVER['PATH_INFO'] and just use the below logic.

**Comment by nickvergessen** [comment]
That works for me as well, on both (index and index-less) urls

**Comment by nickvergessen** [comment]
is index-less also part of 9? Then we should backport this to 9 as well

**Comment by LukasReschke** [comment]
Patch is at https://github.com/nextcloud/server/pull/984 

> is index-less also part of 9? Then we should backport this to 9 as well

Unless we have a bigger bug report with this already in 9 I'd say we should avoid this if possible. This could have some backslash, you never know what strange systems are out there 🙈

**Comment by nickvergessen** [comment]
Well any app that relies on path info get's invalid information.
