### ISSUE TITLE
Share folder failed on readonly storage

### ISSUE THREAD

**Issue by pulcov** [nextcloud/server#9838]
It is impossible to share folder with external user if folder is readonly. No error occurs if this action is done with a file.

### Steps to reproduce
1. Set external storage to readonly
2. Select folder on readonly storage and share it with external user (e-mail address)

### Expected behaviour
Folder is shared and external user get an e-mail with link

### Actual behaviour
Error : Can't increase permissions of ....

### Server configuration
**Nextcloud version: 13.0.4

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing @icewind1991

**Comment by rullzer** [comment]
This is fixed in 14 I think.

**Comment by MorrisJobke** [comment]
Then let's close it for 14 and if there are still edge cases we can look into them.
