### ISSUE TITLE
Update failure from 13.0 to 13.0.4

### ISSUE THREAD

**Issue by cyborghaines** [nextcloud/server#9840]
Tried to update,
then got the following error:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_accounts AS SELECT uid, data FROM oc_accounts': SQLSTATE[HY000]: General error: 10 disk I/O error

Don´t know what to do at all.....

**Comment by MorrisJobke** [comment]
> SQLSTATE[HY000]: General error: 10 disk I/O error

This looks like a problem with your I/O on the database. Check the system logs for more details

As this seems to be a setup issue I would like to ask you to raise further questions in the forums: https://help.nextcloud.com
