### ISSUE TITLE
Direct Download to Server via URI Feature (similar to wget or download managers)

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/server#9847]
Integration of a wget like or download manager function into the Nextcloud server files app could save some steps and upload bandwith of clients.

When clicking on "+" in files app, there should be an option like "Download URI" where you can enter a remote file URI and the server autonomously downloads it to the chosen directory. Ideally it would even continue after the user has logged out and be shown somewhere in a list of active downloads.

Especially in asymmetrical DSL line situations the client would not have to download the file first from a remote source and then use a lot of upload bandwidth when transferring it to the Nextcloud Server.

I have not found a feature like this and there doesn't seem to be a filed issue. I hope I did not overlook it and this is not a duplicate of something.

**Comment by MorrisJobke** [comment]
We remove this feature back in ownCloud 7 because it allowed to attack the server via this command. Also a denial of service would be possible by this.

I unfortunately couldn't find the ticket anymore, but it was named "Upload via link" or "Upload via URL".

Thus I will close this here.
