### ISSUE TITLE
Customize default for the resharing option

### ISSUE THREAD

**Issue by edelhamster** [nextcloud/server#9848]
At our organization there are many departments with different opinions about the resharing feature.
Some have confidential project with just a few team members: they fear to lose control over their data and who has access to it.
Other working groups are hugh and open minded: they feel over regulated and want to share quickly, i.e. without the project leader.

To minimize any configuration risks we currently disabled the 'resharing' feature in the admin panel.
We would appreciate to have the ability to set the default value to "opt in" in the admin panel instead.

Therefor it would be great to have an option "Set default to disabled" right under the "Allow resharing" check box in the admin panel within the section sharing.

Expected behavior: When a user shares an object, the resharing checkbox is not checked by default.

**Comment by kimsyversen** [comment]
Coming soon, ref https://github.com/nextcloud/server/pull/7363

**Comment by MorrisJobke** [comment]
Fixed by #7363
