### ISSUE TITLE
Should the primary button have the color of the theming app?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#985]
@jancborchardt @nextcloud/designers

**Comment by mar1u5** [comment]
YES 👊 ... IT SHOULD 😉

**Comment by juliushaertl** [comment]
This is already mentioned in #454 
Implementation is waiting in pull request #771

**Comment by jancborchardt** [comment]
Closing this in favor of the aforementioned issue & pull request. Please review @nickvergessen @mar1u5  ;)
