### ISSUE TITLE
Upload the logo in Theming App failed

### ISSUE THREAD

**Issue by hume1991** [nextcloud/server#9851]
### Expected behaviour
Upload the logo in Theming App.

### Actual behaviour
Error: No file uploaded

### Server configuration

**Operating system**:
Ubuntu 16.04.4 LTS

**Web server:**
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-04-18T14:53:04

**Database:**
mysql 13.0.4.0

**PHP version:**
7.2.6

**Nextcloud version:** (see Nextcloud admin page)
13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
Web server

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
Activity 
Antivirus App for files 
Calendar 
Collaborative tags
Comments 
Contacts 
Custom CSS 
Data Request 
Default encryption module 
Deleted files 
End-to-End Encryption 
Federation 
File sharing 
Gallery
Log Reader 
Monitoring 
Nextcloud announcements 
Notifications
Password policy 
PDF viewer 
Quota warning 
Share by mail
Text editor 
Theming version:  1.4.5
Update notification 
Usage survey 
Versions 
Video player   

Best regards

Christian Huml

**Comment by juliushaertl** [comment]
Please provide some details on your browser used and check the logs inside of the browser console and the nextcloud log file for possible related entries.

**Comment by hume1991** [comment]
Hello @juliushaertl,

i have solved that problem. It was in the php settings http upload was on off.

Best regards 

Christian Huml
