### ISSUE TITLE
No route to host when trying to install an app

### ISSUE THREAD

**Issue by lug-gh** [nextcloud/server#9853]
nextcloud 13.0.4

when i want to install files right click it cant find the route to the host to download it.

![Image: Error Message](https://i.imgur.com/1GGOIHC.png)

The error status "no route" may be confusing, because it's pingable, but opening the website times out.

**Comment by MorrisJobke** [comment]
Then contact the maintainer of that app. The apps are hosted wherever the maintainers put them. So we can do very little here. See https://github.com/NastuzziSamy/files_rightclick
