### ISSUE TITLE
Nextcloud download problem Help please!

### ISSUE THREAD

**Issue by Itay1787** [nextcloud/server#9854]
Hi everyone I have an annoying and strange problem

System Information
FreeNAS 11.1 U5
Nextcloud 13.0.2
PHP version 7.0.30
Storage: SMB

The problem is that I try to download files in my domain(outside the network) so the download gets stuck and after a minute - 30 seconds it fails it can be stuck at the beginning in the middle or immediatel
And the strange thing is that in my IP local network it can download  no problems at all

So they told me (Forum of freenas) that it was the ISP that blocked it (even though I spoke to them and they said they were not blocking anything, I do not know if to believe them)

For testing I opened up an FTP server through a Windows computer and connected outside the network and it was downloaded without any problems at all

Someone at FreeNAS Forum suggested that I check directly through the IP I get through the ISP
And the results are:
I tried downloading a file that weighs 881MB and then gets stuck at 50 MB
I tried the second time the same file got stuck at 645 MB
Then again for the third time (I had to look with a change) and then it got stuck at 25 MB
Then I tried the last time (for the fourth time) and he downloaded the whole file all 881 MB
And the file opens without problems

Downloads do not make the 60 MB and this one is with luck
Not strange?

And I turned to the community of nextcloud and did not answer there
Sorry for the English - Google translation
I used this guide https://forums.freenas.org/index.ph...ll-checks-passed-updated-to-use-iocage.61934/
I installed the jail through vent
I had this problem in the Owncloud plug-in but I turned to Owncloud Forum they told me it's because I'm missing PHP files so that's why I moved on to Nextcloud
So you think it's the ISP all the time despite what I mentioned above?
Any additional information you need just say
I also checked with someone who has a system setup (from the same directory) really similar to mine and everything works
My DNS 1.1.1.1 (https://1.1.1.1)

Someone here has a way of thinking about a solution or checking out the problem because I'm desperate and already this problem haunts me!

Thanks Itay

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
