### ISSUE TITLE
Cannot log in after upgrade to NC10 RC1, php-fpm segfaults

### ISSUE THREAD

**Issue by mrflow** [nextcloud/server#986]
### Steps to reproduce
1. Upgrade to NC10 RC1
2. Try to log in
3. Face a 502 warning

### Expected behaviour
Be logged in.

### Actual behaviour
Not being logged in, but facing a 502 instead.

### Server configuration
**Operating system**:
Centos 7

**Web server:**
Nginx 1.8

**Database:**
Postgres 9.4

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
10 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Latest 9.1

**Where did you install Nextcloud from:**
Git

**Signing status:**
<details>
<summary>Signing status</summary>
if only i could reach this site...
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
quite a few
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oceefae26795",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.brainflush.org"
        ],
        "datadirectory": "\/media\/owncloud-storage",
        "dbtype": "pgsql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "brainflush.org",
        "asset-pipeline.enabled": false,
        "theme": "",
        "maintenance": false,
        "appstoreenabled": true,
        "updatechecker": false,
        "loglevel": 0,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "htaccess.RewriteBase": "\/"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NOPE

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
2016/08/19 19:35:54 [error] 23777#0: *1472 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: cloud.brainflush.org, request: "POST /index.php/login?redirect_url=%252Findex.php%252Fsettings%252Fintegrity%252Ffailed HTTP/1.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "cloud.brainflush.org"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"ZzIU4ne95+Spn8XQmx40","remoteAddr":"127.0.0.1","app":"admin_audit","message":"Login attempt: \"florian\"","level":1,"time":"2016-08-19T17:35:51+00:00","method":"POST","url":"\/index.php\/login?redirect_url=%252Findex.php%252Fsettings%252Fintegrity%252Ffailed","user":"--"}
{"reqId":"ZzIU4ne95+Spn8XQmx40","remoteAddr":"127.0.0.1","app":"admin_audit","message":"Login successful: \"florian\"","level":1,"time":"2016-08-19T17:35:51+00:00","method":"POST","url":"\/index.php\/login?redirect_url=%252Findex.php%252Fsettings%252Fintegrity%252Ffailed","user":"florian"}
</details>

aaaand php-fpm:

<details>
[19-Aug-2016 19:35:54] WARNING: [pool www] child 1142 exited on signal 11 (SIGSEGV) after 63.479760 seconds from start
[19-Aug-2016 19:35:54] NOTICE: [pool www] child 1671 started
</details>

**Comment by rullzer** [comment]
Seems like we need: https://github.com/owncloud/core/pull/25789 and https://github.com/owncloud/core/pull/25799

@icewind1991 does that look good?

**Comment by mrflow** [comment]
Workaround: disable files_sharing app.

**Comment by rullzer** [comment]
PRs are in => Closing time

**Comment by mrflow** [comment]
Could it be that the fix introduced this tiny little UI regression, that redirects me to  index.php/apps/files/?dir=/&fileid=2 every time I open the Files app, which happens to Highlight a directory, which is an external storage mount?

**Comment by LukasReschke** [comment]
@mrflow Please open a new issue for this.
