### ISSUE TITLE
No update and new installation possible for Apps in nextcloud

### ISSUE THREAD

**Issue by hotschmaster23** [nextcloud/server#9860]
### Steps to reproduce
1.update any app or install a new one
2.the whole nextcloud is freezing and nothing happens
3.cpu and ram are not overloaded
4.then i got the error could not update app
5.in the log on apache i see nothing
6.only a curl error 7 is there
7.internet is working without any issues

### Expected behaviour
Update and installation should be possible

### Actual behaviour
Couldn't update app. is displayed after 30 sec when i want to update any app in nextcloud

this error is displayed
Error | core | cURL error 7: Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection timed out
-- | -- | --

### Server configuration

**Operating system**:16.04.1 Ubuntu, Kernel 4.13.0-43-generic

**Web server:** Apache 2.4.18 Built 2018-04-18

**Database:**10.0.34 MySQL MariaDB

**PHP version:**7.0.30

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated since Version 11 to 12 to 13

**Where did you install Nextcloud from:**
Updated since Version 11 to 12 to 13

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>
Theming	1.4.1 -> 1.4.2 not possible
Collabora Online	2.0.8 -> 2.0.9 not possible
Contacts	2.1.3 -> 2.1.5 not possible
Standard Apps not special Apps installed
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one: no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> Error | core | cURL error 7: Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection timed out

This looks like your server can't connect to the internet.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
