### ISSUE TITLE
[Idea, Suggestion] local .nclnk File-dl .nclnk  weburl .nclnk ftp .nclnk for the NC fs cloud

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#9861]
Hi,

why not make able links setting up to outside from Mod or Admin of the servers and may also from the users, with the extension .nclnk could it be marked as a "link to an other thing" 
like it is on WinNT Desk/fs where it is ".lnk" (but in NC viewable) to different thinks could 
it also be it in the Nextcloud for the Users to have a possible for direct-linking Webpages, Files for external download, http-ftp  and maybe others where be external linked as popup / extra Browser window (configured in the browser tabbed/extra Window) via target="_blank" created like the id3 editor from the mp3 files from Audio-player or was it Musik ? the possibility to edit the url, name,password for ssl logins, if it edit by Admin, it is the created logon-datas: 
Hidden for the foreign and Normal User, like for Factorys and internal nclnk's to special factory servers
or created by a Foreign User for a internal group directories, also login-datas hidden by others, 
only editable and view able by the creation user of the nclnk. Also for foreign folder.nclnk's for Directories from an other server in Hawaii, Pakistan, Antarctica and other places, therewith could be given the connectivity directly to an other nextcloud/owncloud folder behind the login with path and login.
And the ability to create links from other places , like a spiderweb with single nclinks outside of the stationary Nextcloud.
If it's possible also to create Directory nc-links with NCfs-logins, ftp-logins, samba, sftp directly in the ncfs and therewith by clicking on connecting and "hanging in" by leave of it, directly disconnect and close the connection.
Maybe build up like something in htaccess with more informations for Nextcloud to feel files like files and directory's like directory's nclnk's and external filelinking with password (on an ftp with password) like a compressed file with password if the password not setting up to popup an password question like a zip file or maybe open http-folders to be formated like them of nextcloud, i meant therewith this : 
http://blackysgate.net/phpfilemirror/upload/emty/
or with a login-index.php with name and password

and this formatted for the NCFS to look and feel as it in the nextcloud.

therewith could it also be possible to link in local fs from an linkserver
from the admin and this in a shared folder for groups Users or Special Users

like different musik-folders collecting from jamendo and co
or buyed musik folder for the family in the Family-NextCloud :

at moment works the softlink in the shared locale folder nomore
this could be also a possibility to link in a local folder directly and maybe 
stay connected for the musikplayers and co, or other folders where be 
local on the Server/Computer in the House/Factory for connect 
direct on this folder via Name and password of the User/group (UID/GID)
for make accessible the files and rw-able or only Readable and so on..

Also maybe create able by Admin for Groups / Users view able and this as /with 
UID/GID from the local computer for NC-Groups or user/s

Adding in the app "Files Right Click" and in the Cloude directly by the "***" config dialog Edit/Delete "NCLnk" On top of the Directory listing in the "+" Add a "NCLnk" 

and make it able to setting up as "popup" in a tab or [x]new Browserwindow,
[x]Nonpopup, [x]Permanent connection, [x]look and feel like a real Directory/File(with different protocols or a [x]file (dl-only and remove the link automatically) or copy to local file (by [x] enabling from owner of the nclnk [x]DLonly (and remove nclink)) maybe or as [x]direct connect for [x]local fs like files and directory's from the local fs (enabling for users or groups) and so on and maybe more ..

this makes more able for a bigger possibility's handling of the whole
and makes it possible more easy to update and make more addons/possibility's for 
the whole handling and Stack .

Happy Programming \:)))

best regards
Blacky

**Comment by MorrisJobke** [comment]
Hi Blacky,

thanks for the feature idea. It sounds nice. I would propose to develop such a feature as part of an Nextcloud app. There you can hook into the opening of given filetypes and do whatever logic you want. Thus I will close this ticket here as this is the bug tracker for the server core code.

If you are seeking for co–developers I would ask you to raise your idea in the forums: https://help.nextcloud.com
