### ISSUE TITLE
Customize theme for IOS and Android

### ISSUE THREAD

**Issue by hume1991** [nextcloud/server#9865]
Hello, 

is it possible to customize the design in the app (Nextcloud app for IOS and Android).
The link gives no explanation: https://docs.nextcloud.com/server/13/developer_manual/core/theming.html

Best regards 

Christian Huml

**Comment by hume1991** [comment]
Example see: https://ibb.co/mCRSQJ the blue background.

Best regards 

Christian Huml

**Comment by MorrisJobke** [comment]
If the theming app is used then the apps try to adapt to this automatically.

**Comment by MorrisJobke** [comment]
If you wish branded clients the Nextcloud Subscription offers an option to get fully branded clients from Nextcloud GmbH. https://nextcloud.com/enterprise/

**Comment by hume1991** [comment]
I created my own theme. It's just about the background in the app. I do not believe in the theming app.
Have my own Server.

Best regards 

Christian Huml

**Comment by MorrisJobke** [comment]
> I do not believe in the theming app.

Why? Sure the theming app also runs on your server - where is the problem?

**Comment by hume1991** [comment]
See: https://github.com/nextcloud/server/issues/9983#event-1699387575

Best regards

Christian Huml
