### ISSUE TITLE
Cannot connect with CardBook

### ISSUE THREAD

**Issue by biva** [nextcloud/server#9869]
I have issues to connect my Nextcloud with CardBook on Thunderbird, while it works on DavDroid. I get a validation error when creating a new address book to sync with Nextcloud.

We are trying to find a solution with CardBookd developer on https://gitlab.com/CardBook/CardBook/issues/306 but without success. You'll find all our investigation there.

### Steps:
1. Create new address book 
2. Enter CalDAV info (https://nextcloud.mysite.com/remote.php/dav/addressbooks/users/sisim/Perso/
3. Credentials, click Validate
4. Error message: "Validation en erreur"

### Version: 
TB 60.0b7
Cardbook 29.6
Nextcloud 13.0.4
Contacts app 2.1.5

### Cardbook Log:

```
2018.06.14 08:52:34:342 : Validation module : Requête de validation sans découverte d'URL sur https://nextcloud.mysite.com/remote.php/dav/addressbooks/users/sisim/Perso/ …
2018.06.14 08:52:34:346 : Validation module : debug mode : method : (new String("PROPFIND"))
2018.06.14 08:52:34:346 : Validation module : debug mode : headers : (new String("depth: \"1\", content-type: \"application/xml; charset=utf-8\", User-Agent: \"Thunderbird CardBook/29.6\", Authorization: \"Basic \"*****\""))
2018.06.14 08:52:34:346 : Validation module : debug mode : body : (new String("<?xml version=\"1.0\" encoding=\"utf-8\"?><D:propfind xmlns:D=\"DAV:\"><D:prop><D:resourcetype/><D:displayname/></D:prop></D:propfind>"))
2018.06.14 08:52:34:346 : Validation module : debug mode : username : (new String("sisim"))
2018.06.14 08:52:34:346 : Validation module : debug mode : url : (new String("https://nextcloud.mysite.com/remote.php/dav/addressbooks/users/sisim/Perso/"))
2018.06.14 08:52:34:415 : Validation module : debug mode : response code : (new Number(503))
2018.06.14 08:52:34:416 : Validation module : Synchronisation en erreur (étape : validateWithoutDiscovery, url : https://nextcloud.mysite.com/remote.php/dav/addressbooks/users/sisim/Perso/, statut : 503)
2018.06.14 08:52:35:360 : Validation module : debug mode : cardbookRepository.cardbookServerDiscoveryRequest : (new Number(1))
2018.06.14 08:52:35:361 : Validation module : debug mode : cardbookRepository.cardbookServerDiscoveryResponse : (new Number(1))
2018.06.14 08:52:35:362 : Validation module : debug mode : cardbookRepository.cardbookServerDiscoveryError : (new Number(1))
2018.06.14 08:52:35:362 : Validation module : debug mode : cardbookRepository.cardbookServerValidation : ({length:0, user:"sisim"})
2018.06.14 08:52:35:373 : Validation module : Requête de découverte d'URL phase 1 sur https://nextcloud.mysite.com/remote.php/dav/addressbooks/users/sisim/Perso/.well-known/carddav …
2018.06.14 08:52:35:376 : Validation module : debug mode : method : (new String("PROPFIND"))
2018.06.14 08:52:35:376 : Validation module : debug mode : headers : (new String("depth: \"0\", content-type: \"application/xml; charset=utf-8\", User-Agent: \"Thunderbird CardBook/29.6\", Authorization: \"Basic \"*****\""))
2018.06.14 08:52:35:376 : Validation module : debug mode : body : (new String("<?xml version=\"1.0\" encoding=\"utf-8\"?><D:propfind xmlns:D=\"DAV:\"><D:prop><D:current-user-principal/></D:prop></D:propfind>"))
2018.06.14 08:52:35:376 : Validation module : debug mode : username : (new String("sisim"))
2018.06.14 08:52:35:376 : Validation module : debug mode : url : (new String("https://nextcloud.mysite.com/remote.php/dav/addressbooks/users/sisim/Perso/.well-known/carddav"))
2018.06.14 08:52:35:427 : Validation module : debug mode : response code : (new Number(503))
2018.06.14 08:52:35:427 : Validation module : Synchronisation en erreur (étape : discoverPhase1, url : https://nextcloud.mysite.com/remote.php/dav/addressbooks/users/sisim/Perso/.well-known/carddav, statut : 503)
2018.06.14 08:52:36:400 : Validation module : debug mode : cardbookRepository.cardbookServerDiscoveryRequest : (new Number(1))
2018.06.14 08:52:36:400 : Validation module : debug mode : cardbookRepository.cardbookServerDiscoveryResponse : (new Number(1))
2018.06.14 08:52:36:400 : Validation module : debug mode : cardbookRepository.cardbookServerDiscoveryError : (new Number(1))
2018.06.14 08:52:36:400 : Validation module : debug mode : cardbookRepository.cardbookServerValidation : ({length:0, user:"sisim"})
2018.06.14 08:52:36:411 : Validation module : Requête de validation sans découverte d'URL sur https://nextcloud.mysite.com/remote.php/dav/addressbooks/sisim …
2018.06.14 08:52:36:415 : Validation module : debug mode : method : (new String("PROPFIND"))
2018.06.14 08:52:36:416 : Validation module : debug mode : headers : (new String("depth: \"1\", content-type: \"application/xml; charset=utf-8\", User-Agent: \"Thunderbird CardBook/29.6\", Authorization: \"Basic \"*****\""))
2018.06.14 08:52:36:416 : Validation module : debug mode : body : (new String("<?xml version=\"1.0\" encoding=\"utf-8\"?><D:propfind xmlns:D=\"DAV:\"><D:prop><D:resourcetype/><D:displayname/></D:prop></D:propfind>"))
2018.06.14 08:52:36:416 : Validation module : debug mode : username : (new String("sisim"))
2018.06.14 08:52:36:416 : Validation module : debug mode : url : (new String("https://nextcloud.mysite.com/remote.php/dav/addressbooks/sisim"))
2018.06.14 08:52:36:469 : Validation module : debug mode : response code : (new Number(503))
2018.06.14 08:52:36:469 : Validation module : Synchronisation en erreur (étape : validateWithoutDiscovery, url : https://nextcloud.mysite.com/remote.php/dav/addressbooks/sisim, statut : 503)
2018.06.14 08:52:37:430 : Validation module : debug mode : cardbookRepository.cardbookServerDiscoveryRequest : (new Number(1))
2018.06.14 08:52:37:430 : Validation module : debug mode : cardbookRepository.cardbookServerDiscoveryResponse : (new Number(1))
2018.06.14 08:52:37:431 : Validation module : debug mode : cardbookRepository.cardbookServerDiscoveryError : (new Number(1))
2018.06.14 08:52:37:431 : Validation module : debug mode : cardbookRepository.cardbookServerValidation : ({length:0, user:"sisim"})
```

### Nextcloud apache access log:
```
192.168.1.1 - sisim [14/Jun/2018:11:58:02 +0200] "PROPFIND /remote.php/dav/addressbooks/users/sisim/Perso/ HTTP/2.0" 503 -
192.168.1.1 - sisim [14/Jun/2018:11:58:03 +0200] "PROPFIND /remote.php/dav/addressbooks/users/sisim/Perso/.well-known/carddav HTTP/2.0" 503 -
192.168.1.1 - sisim [14/Jun/2018:11:58:04 +0200] "PROPFIND /remote.php/dav/addressbooks/sisim HTTP/2.0" 503 -
```

### Nextcloud log:
```
{"reqId":"XXXXXZZZ","level":1,"time":"2018-06-14T11:48:42+00:00","remoteAddr":"192.168.1.1","user":"--","app":"admin_audit","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/sisim\/Perso\/","message":"Login attempt: \"sisim\"","userAgent":"Thunderbird CardBook\/29.6 Lightning\/6.2","version":"13.0.3.2"}
{"reqId":"XXXXXYYY","level":1,"time":"2018-06-14T11:48:42+00:00","remoteAddr":"192.168.1.1","user":"sisim","app":"admin_audit","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/sisim\/Perso\/","message":"Login successful: \"sisim\"","userAgent":"Thunderbird CardBook\/29.6 Lightning\/6.2","version":"13.0.3.2"}
```

**Comment by biva** [comment]
Investigating further, it does not come from Nextcloud, but from Thunderbird. I close it for now

**Comment by vampsm** [comment]
For all Users with used Thunderbird 60 and problems with Adress and Calendar Sync.
You need 

-> about:config
----> network.cookie.same-site.enabled = true    ---> false

Than works all sync......


https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/

https://bugzilla.mozilla.org/show_bug.cgi?id=1468912

https://www.thunderbird.net/en-US/thunderbird/60.0/releasenotes/#known-issues

**Comment by adsworth** [comment]
The above fix from @vampsm also fixes lightning calender connection issues.

**Comment by dcrobertson01** [comment]
Edit -> Preferences -> General -> Config Editor.

**Comment by ar-ml** [comment]
Changing 
network.cookie.same-site.enabled = true ---> false
worked for me also.  **DON'T FORGET TO RESTART THUNDERBIRD!** 
Otherwise the changes won#t take effect.

**Comment by diqidoq** [comment]
`network.cookie.same-site.enabled` doesn not exist anymore in actual Thunderbird and issue persists.

**Comment by j-ed** [comment]
@diqidoq Are you aware that this is the Nextcloud **product bug tracker** and **NOT** the Nextcloud help forum? Thundebird 68.3.0/Cardbook 43.1 are definitely working with Nextcloud 17.x. Please use the search function of the [Nextcloud help forum](https://help.nextcloud.com/) to find answers on your question, see e.g.
https://help.nextcloud.com/search?q=thunderbird%2060%20cardbook

**Comment by karlmiles** [comment]
@diqidoq, if `network.cookie.cookiebehavior` is set to `2` or `3`, change it to `1`, and it should work.  I had the same trouble with Thunderbird 68 and searching lead me here.

**Comment by Alain-81** [comment]
Thanks @diqidoq it also works for me but `network.cookie.cookiebehavior` was at "0" I changed it to 1. 
I have Thunderbird 78.10.2 and Cardbook 59.4

**Comment by diqidoq** [comment]
For those who humble over this thread all the years again, in our case here I managed to solve this TB issue with Nextcloud, which pops up here and there again, then it disappears, and then appears again, by the ordering of sync configurations, so that you FIRST sync your calendars and THEN the contacts for cardbook, and not the other way around. In our case here it seem to be caused by the private serverside self-signed generated SSL certificate which (so I assume) many use by default. And it seems that Thunderbird calendar sync asks for permission to use this certificate and the contacts sync of cardbook does not and simply refuses without notification. By confirming the url in the calendar sync config steps it seems that this domain related certificate is confirmed TB wide and so it is for cardbook too. Just an assumption. But it surely needs other users to confirm this, because, IF IT IS the reason for the issue or maybe one of the possible reasons for this issue we maybe need a "warning" or something for Nextcloud regardng self-signed certificates and syncs with TB.

(And no, this is not wrong to report here. It is 200% OK to report here to help others getting over this issue between NC & TB quickly. From managing multiple huge issue queues of big Open Source projects I know we learn a lot of such user reports about issues from other perspectives to focus on parts corresponding to this.)
