### ISSUE TITLE
Sharing with a Circle shows an error

### ISSUE THREAD

**Issue by go2sh** [nextcloud/server#9879]
### Steps to reproduce
1. Click on the share button for a unshared folder
2. Search for a Circle
3. Select the Circle as sharing target

### Expected behaviour
Sharee will show up in the list and the folder is shared with the circle.

### Actual behaviour
The error bar is shown with "Fehler" (Error) and the sharee is not selected. If I reload the page, the sharee is selected and can access the share. No audit log entry is created.

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
nginx
**Database:**
mariadb
**PHP version:**
7.0.30
**Nextcloud version:**
13.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
auto-update
**Signing status:**
No errors have been found.

**List of activated apps:**
circles 	0.13.6

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 7
#### Nextcloud log (data/nextcloud.log)
No relevant entry
#### Browser log
Javascript Console
POST https://***host***/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json 403 (Forbidden)
Post Data:
```
shareType: 7
shareWith: ***ID***
circleInfo: Secret circle
circleOwner: ***NAME***
permissions: 31
path: /folder
```

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing @daita

**Comment by go2sh** [comment]
From the appstore.

**Comment by daita** [comment]
Are you a member of the circle you're trying to share to ?

Can you share to anything else that a circle (like another user or group) ?

**Comment by go2sh** [comment]
Yes, I'am the only member and owner. (Secret Circle)

Yes, normal groups are working.

**Comment by daita** [comment]
In the Settings page, Admin Section/Additional Settings, there is a paragraph about Circles and a button to 'Test Async'. Can you click on that button and confirm me the value you have (from 0 to 5)

**Comment by go2sh** [comment]
> Test is now over; final score: null

**Comment by go2sh** [comment]
Server Lock for test.
```
2003:d2:1bca:b7f1:60a0:88a4:c9c9:b9d7 - - [18/Jun/2018:11:29:01 +0200] "GET /apps/circles/admin/testAsync HTTP/1.1" 201 159 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
2003:d2:1bca:b7f1:60a0:88a4:c9c9:b9d7 - - [18/Jun/2018:11:29:05 +0200] "GET /apps/circles/admin/testAsync HTTP/1.1" 201 159 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
2003:d2:1bca:b7f1:60a0:88a4:c9c9:b9d7 - - [18/Jun/2018:11:29:09 +0200] "GET /apps/circles/admin/testAsync HTTP/1.1" 201 159 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
2003:d2:1bca:b7f1:60a0:88a4:c9c9:b9d7 - - [18/Jun/2018:11:29:13 +0200] "GET /apps/circles/admin/testAsync HTTP/1.1" 201 159 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
```
Result is always the same:
```
{"test":{"running":1,"counting":0,"note":null},"init":"1529314094","hand":"1","lock":"***LOCK***","count":"0","status":1}
```
