### ISSUE TITLE
Missing private key

### ISSUE THREAD

**Issue by 0xC1A551C** [nextcloud/server#9880]
### Steps to reproduce
1. Update nextcloud from older version
2. ???
3. login

### Expected behaviour
Tell us what should happen

Files should be decrypted.

### Actual behaviour
Tell us what happens instead

Files are not decrypted. Tells me that my encryption key password needs to be updated at the top.
Then when I go to change the user password on the user account it says "private key is missing". I have the user.private and user.public keys in the user folder. never moved them, and they are still untouched.

i am a noob as i have not updated nextcloud for a long time. I have a recovery password or whatever. 

### Server configuration
Setup on a docker

**Operating system**:
Latest unraid

**Web server:**
nginx
**Database:**
mariadb
**PHP version:**
php 7
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
apps on unraid

is any of the other information needed? all i did was update nextcloud & now I am pretty sad all my personal photos are encrypted because the private key for my user is missing although I am looking at it in the /nextcloud/user/OC???/user.privatekey

**Comment by MorrisJobke** [comment]
cc @nextcloud/encryption

**Comment by MorrisJobke** [comment]
Maybe related to #8546

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.

**Comment by jknockaert** [comment]
> It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.

Now that's a helpful reaction after two years.

**Comment by szaimen** [comment]
Sorry but we are currently cleaning up old/stale issues. I am sorry if I have chosen the wrong answer. I didn't want to be rough.
