### ISSUE TITLE
Nextcloud 13.0.4 Update and installed news app(!) -> Failure due to utf8mb4

### ISSUE THREAD

**Issue by peter198210** [nextcloud/server#9886]
Hello everyone,
I tried to update my Nextcloud instance from 13.0.1 to 13.0.4. Having battled with the utf8mb4 issue - produced by the app News - I am in the same conundrum again. This time however it seems, it can't be solved. I emply MySQL/MariaDB as backend and I followed the steps of https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html
See attached below my issue (sorry it is partially in German) the salient bits of the issue however are in English. Any help is highly appreciated. Thank you in advance! 

If there is anything missing please let me know.

Peter

Update vorbereiten (Preparing update)
Log-Level auf "debug" gesetzt (Log-Level set to "debug)
Wartungsmodus eingeschaltet (Maintenance Mode set to on)
Das Datenbankschema wird aktualisiert (Updating DB scheme)
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken ADD expires INT UNSIGNED DEFAULT NULL': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Das Update ist fehlgeschlagen (Update failed). Bitte melde dieses Problem an die Nextcloud Community.

**Comment by peter198210** [comment]
The issue was resolved by reducing the VARCHAR length in oc_authtoken from 255 to 191. Nextcloud now works without any issues.

**Comment by stefanschulz** [comment]
Hi,

Unfortunately I do not understand the resolution of this issue. I just ran into the same problem when updating from 13.0.2.1 to 13.0.4. 
Where can I "reduce the VARCHAR length" and of what field?

Thanks,
Stefan
