### ISSUE TITLE
Files versioning not active and css error.

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#9887]
NC 13.0.4 fresh install

### Steps to reproduce
1. upload/create file  ( txt for exemples )
2. modify file
3. check activities for the files
Found: 
```
You changed 2018.txt
2 minutes ago
--
You changed 2018.txt
2 days ago
--
You created 2018.txt
3 days ago
```
4. Check versioning infos
Found:
`No earlier versions available`

### Expected behaviour
Files versioning should be available

**IMPORTANT INFOS**
When sshed to my server, i can found the versioning files under .../users/files_versions/whatever

actually, i have
2018.txt.v1528556337  2018.txt.v1529066639  2018.txt.v1529249150

**Comment by stratege1401** [comment]
![versio1](https://user-images.githubusercontent.com/8655165/41509478-9c94023a-7254-11e8-9b8c-8b7bdad84504.JPG)
![versio2](https://user-images.githubusercontent.com/8655165/41509481-9fc6e332-7254-11e8-9734-b7f80082532f.JPG)

**Comment by MorrisJobke** [comment]
We fixed something related to that lately. Please try again with a newer version.
