### ISSUE TITLE
/settings/ajax/checksetup and /settings/apps/list crash php-fpm

### ISSUE THREAD

**Issue by imacks** [nextcloud/server#9889]
### Steps to reproduce
1. run alpine version of nextcloud in docker
2. goto apps > got blank
3. goto settings > basic settings. sometimes 502, sometimes `Error occurred while checking server setup`

### Expected behaviour
/settings/ajax/checksetup should return something

### Actual behaviour
php-fpm crash

```
2018/06/17 19:51:31 [error] 232#232: *24724 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.42.178.69, server: , request: "GET /settings/ajax/checksetup HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "***reduct***"
6/18/2018 3:51:31 AM[NGINX-REQ] 17/Jun/2018:19:51:31 +0000 - 10.42.178.69 - - - "GET /settings/ajax/checksetup HTTP/1.1"
6/18/2018 3:51:31 AM[17-Jun-2018 19:51:31] WARNING: [pool www] child 321 exited on signal 11 (SIGSEGV - core dumped) after 2801.690192 seconds from start
```

### Server configuration

**Operating system**:

**Web server:**
Nginx
**Database:**
MySQL
**PHP version:**
7.1 fpm
**Nextcloud version:** (see Nextcloud admin page)
13.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

---------------------------

I am not able to see any apps over the web:

```
- - - "GET /settings/apps/list?category=installed HTTP/1.1"
6/18/2018 3:55:14 AM2018/06/17 19:55:14 [error] 232#232: *25391 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.42.178.69, server: , request: "GET /settings/apps/categories HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "***reduct***"
6/18/2018 3:55:14 AM[17-Jun-2018 19:55:14] WARNING: [pool www] child 423 exited on signal 11 (SIGSEGV - core dumped) after 105.205655 seconds from start
6/18/2018 3:55:14 AM[NGINX-REQ] 17/Jun/2018:19:55:14 +0000 - 10.42.178.69 - - - "GET /settings/apps/categories HTTP/1.1"
```

I have turned loglevel to 0 and debug = true. but data/nextcloud.log doesn't produce anything that relates to this issue.

What could be wrong? I seem to recall 13.0 doesn't have this problem. What php code gets called when getting these urls? can i write something to test the source of the error?

**Comment by imacks** [comment]
just to update, i have managed to track this to  `http/client` and `clientservice`. still investigating

**Comment by ChristophWurst** [comment]
This is out of scope for Nextcloud. If php-fpm crashes than it's a bug in php(-fpm).

Also, nc13 has reached EOL. You should update to a newer release.
