### ISSUE TITLE
Webdav search: folders with double slash

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#9892]
When searching via webdav search on NC13, I get:
`<d:href>/nc13/remote.php/dav/files/test//sse//</d:href>
`

Those double slashes look a bit suspicious and cause problems for us on android, as we extract then the wrong path "//sse//" instead of "/sse/".
(Of course I can & will fix this on client side, but it should be also fixed on server).

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991
