### ISSUE TITLE
"occ encryption:decrypt-all" fails with obscure error message when not connected to an interactive terminal

### ISSUE THREAD

**Issue by zerodogg** [nextcloud/server#9894]
### Steps to reproduce
1. Run `occ encryption:decrypt-all` without an interactive terminal, ie. using docker (`docker exec --user www-data nextcloud php occ encryption:decrypt-all xx`)

### Expected behaviour
Should tell me that it needs an interactive terminal, not just say "aborted".

### Actual behaviour
Outputs: 

    Disable server side encryption... done.
    
    
    You are about to start to decrypt all files stored in xx's account.
    It will depend on the encryption module and your setup if this is possible.
    Depending on the number and size of your files this can take some time
    Please make sure that no user access his files during this process!
    
    Enable server side encryption... done.
    aborted

In the docker case, it works when providing `-it` to docker (ie. `docker exec -it --user www-data nextcloud php occ encryption:decrypt-all xx`)

### Server configuration

**Operating system**: official docker image (up to date as of 2018-06-18) running on Debian x86_64 9.4

**Database:** MariaDB

**PHP version:** 7.1.18

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** Docker

**Comment by MorrisJobke** [comment]
cc @nextcloud/encryption

**Comment by ChristophWurst** [comment]
-> PR at https://github.com/nextcloud/server/pull/10439.

Thank you, @eugulixes :v:
