### ISSUE TITLE
Appstore: allow search across all categories

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#9898]
E.g. I wanted to install "dashboard", but searching (ctrl+f) on "apps" as admin, did not worked.
So I had to go through all categories until I found the desired app.
(especially harder because no category is listed in appstore webpage (https://github.com/nextcloud/appstore/issues/528)

**Comment by MorrisJobke** [comment]
Duplicate of #6868
Fixed by #9565
