### ISSUE TITLE
Gnome notification still shows "owncloud"

### ISSUE THREAD

**Issue by enricogalli** [nextcloud/server#9901]
### Steps to reproduce
1. Install linux desktop client
2. Wait for the computer to enter "sleep mode"
3. Upload something to your nextcloud server

### Expected behaviour
It should show the name of the software (nextcloud) and number of notification 

### Actual behaviour
It should show the name of the other software (owncloud) and number of notification 

### Server configuration

**Operating system**:
Ubuntu Linux 18.04

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Server is a fresh install
Desktop client is also a fresh install but previously also owncloud client was installed
![pict_20180618_181339](https://user-images.githubusercontent.com/1555519/41549424-1ac58094-7326-11e8-8937-81b25d6dd0e5.JPG)

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by juliushaertl** [comment]
Please report issues to the client repo at https://github.com/nextcloud/client

The specific issue has already be fixed in master and will be in the next client release, see https://github.com/nextcloud/desktop/issues/28

**Comment by enricogalli** [comment]
I messaggi inviati a questa casella potrebbero non essere letti.
L'attività è cessata definitivamente il 31/10/2017.

Enrico
