### ISSUE TITLE
"no app in context" after update 13.0.1 -> 13.0.4

### ISSUE THREAD

**Issue by voxspox** [nextcloud/server#9908]
I would have used your template but most sections I can not fill in, because I could not login anymore. sorry.

### Steps

I have just updated nextcloud from 13.0.1 to 13.0.4 via the update button. And directly before the "themes" plugin.

If I want to login now this fails: "The page isn't redirecting properly".
The nextcloud.log file says (extract):
```
app":"no app in context",
"method":"GET","url":"/index.php/apps/files/",
"message":
Exception":"Error",
    "Message":"Class 'OCA Files App' not found",
    "Code":0,
    "Trace":
      #0 /var/www/.../html/nextcloud/lib/private/legacy/app.php(245): require_once()
      #1 /var/www/.../html/nextcloud/lib/private/legacy/app.php(154): OC_App::requireAppFile('systemtags')
      #2 /var/www/.../html/nextcloud/lib/private/legacy/app.php(127): OC_App::loadApp('systemtags')
      #3 /var/www/.../html/nextcloud/lib/base.php(984): OC_App::loadApps()
      #4 /var/www/.../html/nextcloud/index.php(42): OC::handleRequest()
      #5 {main}","File":"/var/www/.../html/nextcloud/apps/systemtags/appinfo/app.php",
    "Line":64
```

I have remove all cookies and session data in Firefox.

How can I provide more information (if necessary)?

**Comment by MorrisJobke** [comment]
> #5 {main}","File":"/var/www/.../html/nextcloud/apps/systemtags/appinfo/app.php",

This looks fishy - as if the request does not load via the index.php but via a different entry point, which then fails. So this looks like a setup issue in the web server IMO. 

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
