### ISSUE TITLE
Dropbox API v1 will be shutdown: **June 28th 2017**

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#991]
We use that in the external storage app, if we want to keep the Dropbox provider (I honestly wouldn't mind removing it) then we need to update.

https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by mar1u5** [comment]
We should consider about that in the forums (where our users are). 
...or we wait for what upstream does 😈

**Comment by rullzer** [comment]
Does the 'survey' app provide this info? @nickvergessen @schiessle ?
Because that could give us an indication how often this is actually used.

**Comment by nickvergessen** [comment]
I dont think we get the type of mounts, just the numbers.
But anyway I'd say update

**Comment by LukasReschke** [comment]
> I dont think we get the type of mounts, just the numbers.

Add it? :P

**Comment by rullzer** [comment]
As far as I can see we can't move while we support 5.4

**Comment by nickvergessen** [comment]
So 11 sounds like a good point in time to do that ;)

**Comment by mar1u5** [comment]
Ref: https://github.com/owncloud/core/issues/25969

**Comment by nickvergessen** [comment]
Related IRC:
```irc
<PVince81> need to port the dropbox ext storage to the new API before June 2017: https://github.com/owncloud/core/issues/25969
<PVince81> any volunteers?
<DeepDiver> kill it
```

**Comment by mar1u5** [comment]
Muhaha :smiling_imp:

**Comment by rullzer** [comment]
So kill in 12?

**Comment by powerpaul17** [comment]
Please don't let it die. For me it is a very useful feature because I can avoid having to install the Dropbox client and still satisfy the need of using it because of my friends. Personally if it was just for me, Dropbox could go to hell.. ;)

**Comment by MariusBluem** [comment]
I also see the use-case of @powerpaul17 ... Would cause many problems killing Dropbox API, because we have releases out there (9, 10, 11) which have a Dropbox Integration. Killing a feature which is already shipped seems to be ... updating it - So Dropbox API v2 would also be something we would need to backport to our `stable`-branches (or we use sell it as reason for upgrading 😈) 

* is a seamless upgrade possible from user-perspective? (without re-adding the storage)

But ... Let me ask - how much time would it cost now **and** in the future to support this? 🤔 @nickvergessen 

Nextcloud as a save and **all-in-one** home for your data - even if your friends are using the cloud service starting with **D** - this should be our goal (Of course only if it is worth) 😉

**Comment by nickvergessen** [comment]
Date of death is **June 28th 2017**. We just need to make sure to have 12 out before that. Otherwise I don't see a way not to backport this.

**Comment by MorrisJobke** [comment]
@nickvergessen @LukasReschke @icewind1991 I guess we are late on this item here. I would vote to make this an app to get this nasty dependency out of the server part.

**Comment by MorrisJobke** [comment]
> @nickvergessen @LukasReschke @icewind1991 I guess we are late on this item here. I would vote to make this an app to get this nasty dependency out of the server part.

Volunteers?

**Comment by LukasReschke** [comment]
I'd say let's wait for https://summerofcode.withgoogle.com/projects/#6749747938328576?

**Comment by rullzer** [comment]
It would be nice to rip it out for 12. Just so that somebody that cares can fix it once v1 is EOL etc.

I took a quick look and basically 

* https://github.com/nextcloud/server/issues/4531 : else you need to make sure the app is after files_external (we load alphabetically)
* You also need to rip out the oauth1 thingy
* Probabaly a migration from current dropbox stuff to the new app

All in all more than I can do with my very limted files_external knowledge. And since I also don't use dropbox I might not be the best test person.

**Comment by e-alfred** [comment]
Final deprecation (i. e. turning off endpoint) seems to be postponed until end of September:

https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

Well, maybe the GSOC results can be applied then to make it work with the new API.

**Comment by sunjam** [comment]
afaik Dropbox is no longer allowing users to create Oauth 1 end points as the current **Dropbox API v2** only allows creation of Oauth v2.  So anyone just starting out (like me) is totally unable to connect their Dropbox account to Nextcloud by following the Nextcloud 12 Adminstrative Documentation.

**Comment by JimmyKater** [comment]
dropbox has definitly cancelled Oauth1 - was getting no connection since some days and didnt care (since i didnt know about their new policy) only to find out today that it's impossible to connect with Oauth1 today. 
for me it isn't meag-important but as i have moved some files to there it would be nice to have (i know i could get them back by DL from dropbox and UL them to NC again

**Comment by haxti** [comment]
Dropbox Sync is still working here. Maybe only new connections will be rejected atm.

**Comment by e-alfred** [comment]
This seems to be the repository where the GSOC code for Owncloud will go:

https://github.com/owncloud/files_external_dropbox

**Comment by sunjam** [comment]
[Here is the active pull request for the code submitted 8/28.](https://github.com/owncloud/files_external_dropbox/pull/1#pullrequestreview-59084541)

**Comment by e-alfred** [comment]
Okay, since yesterday Dropbox support using v1 API is officially dead now.

**Comment by heskja** [comment]
Any updated plans for this issue?

**Comment by go2sh** [comment]
The owncloud app should also work with nextcloud. You can give it a try.

**Comment by tedd77** [comment]
Hello , Where to find that app of owncloud and what is it called ?

**Comment by Escubaer** [comment]
https://marketplace.owncloud.com/apps/files_external_dropbox
Install instructions are here: https://owncloud.org/blog/external-storage-dropbox/

Maybe you can get it to work for NC. However please check out the license, its GPLv2 and therefor can't be redistributed by Nextcloud or through the Nextcloud app store.

Have it running in my ownCloud instance as I can't make up my mind yet on the two options. Seems ownCloud has more dedication to quality but less of the newest feature which is hot and very early Alpha ...

**Comment by Teyro** [comment]
cant get it to work in nc.... says versions make nextcloud unstable....

**Comment by AlexBedeker** [comment]
Fixed the version part, than ran into the next error: It's making my nextcloud instance unstable... so can't activate...

**Comment by Teyro** [comment]
Same here... Makes me very sad :(

**Comment by e-alfred** [comment]
This is indeed bad. Somebody would have to make it compatible with Nextcloud and then there would have to be an exception in the App Store because of the GPLv2 license which sounds like a complicated mess.

**Comment by go2sh** [comment]
The restriction to AGPL seams odd to me. Its allowed to mix GPL and AGPL code and the GPL is compatible with the AGPL.

**Comment by Teyro** [comment]
Will Pay 25€ for adding Support

**Comment by icewind1991** [comment]
I've done a quick port of the app: https://github.com/icewind1991/files_external_dropbox

Since I don't use dropbox myself I would appreciate some testing before I push it to the appstore.
(I don't expect major issues, but as always when using unreleased software, make sure you have backups)

**Comment by Teyro** [comment]
Cant find the app at the app store :(

**Comment by sunjam** [comment]
Dude, it isn't in the app store yet.  As the author just said, please test
it to make sure if works properly before it is added to the app store
officially.  Manual installation instructions are in Nextcloud's
documentation, which you can search for.

**Comment by notjoe** [comment]
I'd be happy to if I could figure our how. I'm not seeing any documentation and it doesn't seem to be a drop-in replacement for what I see inside of `apps/files_external`

**Comment by ConorIA** [comment]
@icewind1991, getting "Error: This app can not be enabled because it makes the server unstable"

**Comment by MariusBluem** [comment]
If you are experiencing issues with the files_external_dropbox app, please open them in the related repo ;) THX!

**Comment by notjoe** [comment]
Looks like it worked though a little buggy

**Comment by notjoe** [comment]
For those who were a little clueless and want to try this out:
1) Log into your server, 
2) Change directories to your Nextcloud installation and then go into the app directory.  
3) git clone https://github.com/icewind1991/files_external_dropbox.git
4) cd files_external_dropbox && make
5 Open up http://yourdomain.com/settings/apps?category=disabled# 
6) Enable the Dropbox app.
7) Follow the rest of the instructions on the repo page.

**Comment by notjoe** [comment]
So, I found a "Bug" I guess. I upload files as account A and account B (Or any other account) can see the files inside of the Dropbox storage.

**Comment by nickvergessen** [comment]
Closing this, because it has been "resolved" with a new app:
https://github.com/icewind1991/files_external_dropbox

**Comment by e-alfred** [comment]
@nickvergessen Well, not completely:

1. The now obsolete code for v1 would have to be removed.
2. The new app would have to be put into the App Store (which is difficult because it would need an exception because of the GPLv2 license).

**Comment by nickvergessen** [comment]
1. The dropbox code seem to be already removed from our code base (didn't find it in php files anymore)
2. Uploading it to the appstore is up to the owner of the app. So not sure why there should be an issue open in the server repo. Also when there is a license issue, the thing to do is: resolve the license issue or deal with it in a okay-way and not to add an exception to the appstore. Licenses and their incompatibilities have their reasons.

**Comment by jgoerzen** [comment]
I'm puzzled that you say it's not in the code base.  It's still documented: https://docs.nextcloud.com/server/12/user_manual/external_storage/external_storage.html

My 12.0.3 system still shows files all over.  And I don't see any new app in the app store.  So the feature is still listed on the web site, is broken, and the replacement doesn't work...

On my system, I still see:
```
find . | grep -i dropbox
./apps/files_external/js/dropbox.js
./apps/files_external/3rdparty/Dropbox
./apps/files_external/3rdparty/Dropbox/Exception.php
./apps/files_external/3rdparty/Dropbox/Exception
./apps/files_external/3rdparty/Dropbox/Exception/Forbidden.php
./apps/files_external/3rdparty/Dropbox/Exception/RequestToken.php
./apps/files_external/3rdparty/Dropbox/Exception/NotFound.php
./apps/files_external/3rdparty/Dropbox/Exception/OverQuota.php
./apps/files_external/3rdparty/Dropbox/API.php
./apps/files_external/3rdparty/Dropbox/OAuth.php
./apps/files_external/3rdparty/Dropbox/OAuth
./apps/files_external/3rdparty/Dropbox/OAuth/Zend.php
./apps/files_external/3rdparty/Dropbox/OAuth/Consumer
./apps/files_external/3rdparty/Dropbox/OAuth/Consumer/Dropbox.php
./apps/files_external/3rdparty/Dropbox/OAuth/Wordpress.php
./apps/files_external/3rdparty/Dropbox/OAuth/Curl.php
./apps/files_external/3rdparty/Dropbox/OAuth/ca-bundle.pem
./apps/files_external/3rdparty/Dropbox/OAuth/PHP.php
./apps/files_external/3rdparty/Dropbox/OAuth/PEAR.php
./apps/files_external/3rdparty/Dropbox/autoload.php
./apps/files_external/lib/Lib/Backend/Dropbox.php
./apps/files_external/lib/Lib/Storage/Dropbox.php
./core/doc/admin/_sources/configuration_files/external_storage/dropbox.txt
./core/doc/admin/_images/dropbox-2.png
./core/doc/admin/_images/dropbox-oc.png
./core/doc/admin/_images/dropbox.png
./core/doc/admin/_images/dropbox-6.png
./core/doc/admin/_images/dropbox-1.png
./core/doc/admin/_images/dropbox-5.png
./core/doc/admin/_images/dropbox-4.png
./core/doc/admin/_images/dropbox-3.png
./core/doc/admin/configuration_files/external_storage/dropbox.html
```

**Comment by nickvergessen** [comment]
Yeah but it does not exist in master (going to be nextcloud 13), so it's already fixed for the next bigger release...

**Comment by sunjam** [comment]
Honest Question:

Could we politely ask they change the license.  If so, what to?

**Comment by ConorIA** [comment]
@sunjam, the license issue has been resolved. @icewind1991 forked the owncloud app at a commit where that code was AGPL licensed.

**Comment by tedd77** [comment]
any progress on this? could someone share info on this app? is it final and working ? thank you

**Comment by ConorIA** [comment]
@tedd77, follow along here: https://github.com/icewind1991/files_external_dropbox
I haven't had any luck so far, as I keep getting redirected to a Google Oauth page, instead of Dropbox.

**Comment by tedd77** [comment]
@ConorIA  thank you. So if I understand well no luck so far to solve this  !! although I consider important and high priority.

**Comment by nickvergessen** [comment]
Please report any further bugs and problems in https://github.com/icewind1991/files_external_dropbox

**Comment by petercdee** [comment]
Guys this really sucks. It was a great feature of Owncloud and then of course Nextcloud. Any chance we can get this released back into the core functionality of Nextcloud in a future release.

**Comment by jgoerzen** [comment]
The files_external_dropbox that you are linking to is un-installable.  README.md says to install it from the Nextcloud app store, but it doesn't exist there and there is no response to questions about it.  Does anybody know what the migration path from Nextcloud to Owncloud looks like?  I switched to Nextcloud early on, but I rely on this feature and it's time to get it working.

**Comment by e-alfred** [comment]
@jgoerzen The readme was updated. The described method (building it on your own) works for now. You have to enable the files_external app as well which isn't mentioned at the moment.

**Comment by sunjam** [comment]
How do we enable the files_external app?

---Sent from Boxer | http://getboxer.com

On October 20, 2017 at 11:41:13 PDT, e-alfred <notifications@github.com> wrote:@jgoerzen The readme was updated. The described method (building it on your own) works for now. You have to enable the files_external app as well which isn't mentioned at the moment.  —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.           {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nextcloud/server","title":"nextcloud/server","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nextcloud/server"}},"updates":{"snippets":[{"icon":"PERSON","message":"@e-alfred in #991: @jgoerzen The readme was updated. The described method (building it on your own) works for now. You have to enable the files_external app as well which isn't mentioned at the moment."}],"action":{"name":"View Issue","url":"https://github.com/nextcloud/server/issues/991#issuecomment-338290066"}}}
