### ISSUE TITLE
Upload to external storage fails but creates .part file

### ISSUE THREAD

**Issue by noriyuki41** [nextcloud/server#9915]
### Steps to reproduce
1. Login to Nextcloud
2. Open External Folder
3. Upload new File

### Expected behaviour
Files should appear on external folder

### Actual behaviour
Upload starts but never finishes. Only a xxx.part file appears on the external storage. No error Message.
Smaller files seam to work. Upload to local storage works fine.
Screenshot attached!
![19 06](https://user-images.githubusercontent.com/40025978/41596111-8745640c-73c9-11e8-8bb3-b71181ddd39a.png)

## Server configuration detail

**Operating system:** Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.2.15

**PHP version:** 7.0.30-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, redis, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** Nextcloud VM

**Where did you install Nextcloud from:** Nextcloud VM

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>Enabled:
 - calendar: 1.6.1
 - caniupdate: 0.1.2
 - comments: 1.3.0
 - contacts: 2.1.3
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_external: 0.4
 - workflowengine: 1.3.0
Disabled:
 - activity
 - admin_audit
 - encryption
 - user_ldap</summary>

</details>

**Nextcloud configuration:**
<details>
<summary>{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.130.11",
            "nextcloud",
            "transfer.piesslinger.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/192.168.130.11\/",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "log_rotate_size": "10485760",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</summary>

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
YES

**Are you using encryption:** 
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**
Firefox 60.0.2
Microsoft Edge 41.16299.492.0

**Operating system:**
Windows 10 Pro V1709 Build 16299.492

#### Web server error log

PLEASE HELP ME TO POST THE LOGS HERE!
DON'T KNOW HOW TO FIND THEM?

**Comment by paulbach83** [comment]
I also have a lot of problem with external storage, I think that nextcloud 13 is not totally stable (with external storage).
Try with an earlier version as nextcloud 11.

**Comment by rominator1983** [comment]
Same over here. Using the sync client for Windows. I have some huge files (> 8 GB) that constantly fail to upload and cause .part files that are spilling my drive. I have to remove those manually (tedious) from time to time. I am using version 13.0.5

**Comment by tomtomas99911** [comment]
I am facing this issue too. When I user windows client I can find in /tmp .part files - sometimes they have many GB.

**Comment by nafets1234** [comment]
Can confirm with 13.0.6.1 . This is a major issue. Who fixes this until when?

**Comment by Lumm23** [comment]
We've got the same issue over here. Any Idea when this is fixed or is there a workaround ?

**Comment by mwitschel** [comment]
This might be helpfull:
https://github.com/nextcloud/server/issues/11295#issuecomment-428110342

**Comment by tomtomas99911** [comment]
Not helpfull for us, we are using S3 storage, not SMB.

**Comment by rominator1983** [comment]
Same over here with local storage Am 09.10.2018 12:04 nachm. schrieb Tomáš Mores <notifications@github.com>:Not helpfull for us, we are using S3 storage, not SMB.

**Comment by janusn** [comment]
My nextcloud server has a similar issue. When I try to upload files to a folder just been created by nextcloud in the iOS client App, it failed with errors like these:

- rename(/mnt/ds918plus/media/shared/temp/IMG_1873.PNG.ocTransferId460390567.part,/mnt/ds918plus/media/shared/temp/IMG_1873.PNG):

 Permission denied at /usr/local/www/nextcloud/lib/private/Files/Storage/Local.php#272

- Undefined variable: run at /usr/local/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php#223

- renaming part file to final file failed ($run: false, $renameOkay: false, $fileExists: false)

- unlink(/mnt/ds918plus/media/shared/temp/IMG_1873.PNG.ocTransferId460390567.part): Operation not permitted at /usr/local/www/nextcloud/lib/private/Files/Storage/Local.php#227

- 

Sabre\DAV\Exception: Could not rename part file to final file/usr/local/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156: OCA\DAV\Connector\Sabre\File->put(null)/usr/local/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile("IMG_1873.PNG", null)/usr/local/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 529: Sabre\DAV\Server->createFile("Shared_Medi ... G", null, null)Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/usr/local/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/usr/local/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])/usr/local/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/usr/local/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/usr/local/www/nextcloud/remote.php - line 163: require_once("/usr/local/ ... p")
--

As the folder was created by the nextcloud server, the sever has no permission issues with the folder.
I have verified it by running the following command with the nextcloud user account successfully.
`sudo -u www mv /mnt/ds918plus/media/shared/temp/IMG_1873.PNG.ocTransferId460390567.part /mnt/ds918plus/media/shared/temp/IMG_1873.PNG`

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
