### ISSUE TITLE
demo.nextcloud.com: Firefox warns of virus in Nut.jpg

### ISSUE THREAD

**Issue by MaxBarraclough** [nextcloud/server#9916]
On demo.nextcloud.com, if I attempt to download Nut.jpg, Firefox warns me of a virus.

I am running Firefox 60.0.2 64-bit, on Windows 10.

![nextclouddemovirusissue](https://user-images.githubusercontent.com/1122128/41600646-5f291810-73ce-11e8-8b37-f6154655822c.png)

**Comment by MorrisJobke** [comment]
I can reproduce this with Firefox on macOS, but not with IE/Edge anything on Windows. So it seems to be a problem with Firefox.

Also VirusTotal does not detect it: https://www.virustotal.com/#/file/a8ebadd70a86688d5a7c808eb717b30d46083fa4a51cc75c874341ba3df005c6/detection

Could I ask you to report this to Firefox? Thank you a lot for reaching out, but unfortunately this is out of our hands. :/

**Comment by MorrisJobke** [comment]
Original file can be found at https://github.com/nextcloud/example-files/blob/master/Photos/Nut.jpg

**Comment by MaxBarraclough** [comment]
[Apparently](https://support.mozilla.org/en-US/questions/1049744) it's powered by Google's 'Safe Browsing' project.

Chrome on Windows gives me the same scary warning, and unlike Firefox, it ***does not allow me to bypass it***.

I'd [report it](https://safebrowsing.google.com/safebrowsing/report_error/?hl=en) but I don't know what specific URL to use.

**Comment by MaxBarraclough** [comment]
That link works fine, and shows the image in the browser.

Far from ideal, but might it be beneficial to display a warning pre-empting the browser's false-positive?

**Comment by MorrisJobke** [comment]
> Far from ideal, but might it be beneficial to display a warning pre-empting the browser's false-positive?

Those are the example files ... I guess it makes very little sense to add a hardcoded warning that there might be a false-positive for one of the example files, which will be most likely deleted anyways.
