### ISSUE TITLE
Import of a vcf-file to the contacts app caused errors

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#9918]
Steps to reproduce
1.import a vcf-file
2. The contacts seems to work OK
3. check the log

Expected behaviour
There should not be errors

Actual behaviour
There are lots of errors - 1 new every second
Error	OC_USER_SQL	Failed to connect to the database: Unsupported type:	2018-06-19T12:34:27+0200

If I stay with the error-window active "top" fills up with php-fpm7.2 instances.

1240 www-data 20 0 1140700 65488 47860 S 2.7 1.1 0:09.27 php-fpm7.2
1242 www-data 20 0 845360 55988 40464 S 2.7 0.9 0:09.11 php-fpm7.2
1227 www-data 20 0 1140032 64556 47540 S 2.3 1.1 0:09.51 php-fpm7.2
1229 www-data 20 0 845312 54836 39352 S 2.3 0.9 0:09.84 php-fpm7.2
1234 www-data 20 0 1063500 62756 46424 S 2.3 1.0 0:09.10 php-fpm7.2
1236 www-data 20 0 1140132 64840 47768 S 2.3 1.1 0:09.26 php-fpm7.2
1238 www-data 20 0 845380 54596 38972 S 2.3 0.9 0:09.30 php-fpm7.2
1243 www-data 20 0 1140668 68584 50924 S 2.3 1.1 0:09.40 php-fpm7.2
1244 www-data 20 0 845372 52692 37200 S 2.3 0.9 0:08.95 php-fpm7.2
1245 www-data 20 0 845360 55364 39776 S 2.3 0.9 0:09.39 php-fpm7.2
1246 www-data 20 0 845352 56864 41308 S 2.0 0.9 0:09.10 php-fpm7.2
1231 www-data 20 0 767852 49176 35440 S 1.3 0.8 0:09.10 php-fpm7.2
1233 www-data 20 0 767860 52416 38660 S 1.3 0.9 0:09.15 php-fpm7.2
1235 www-data 20 0 851664 59280 43568 S 1.3 1.0 0:09.33 php-fpm7.2
1237 www-data 20 0 845264 54396 38900 S 1.3 0.9 0:09.22 php-fpm7.2
1239 www-data 20 0 767736 52836 39088 S 1.3 0.9 0:08.85 php-fpm7.2
1228 www-data 20 0 1142832 69624 49556 S 1.0 1.1 0:09.80 php-fpm7.2
1230 www-data 20 0 767760 52828 39056 S 1.0 0.9 0:08.99 php-fpm7.2
1232 www-data 20 0 1063508 62620 46336 S 1.0 1.0 0:08.75 php-fpm7.2
1241 www-data 20 0 1140516 65600 48360 S 1.0 1.1 0:09.26 php-fpm7.2

This has been verified also by c-rieger

I deactivated the Contact app. The errors remain the same. 
After a reboot  I had to start php-fpm7.2 manually. 
NC functions normally except for the errors filling up. 

see this for further information https://github.com/nextcloud/contacts/issues/574
They think this is a server issue. 

Server configuration detail
Operating system: Linux 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64

Webserver: nginx/1.14.0 (fpm-fcgi)

Database: mysql 10.1.29

PHP version: 7.2.6-1+ubuntu18.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 13.0.4 - 13.0.4.0

** fresh install:**

Enabled:

activity: 2.6.1

admin_audit: 1.3.0

apporder: 0.4.1

audioplayer: 2.3.0

calendar: 1.6.1

cms_pico: 0.9.7

comments: 1.3.0

contacts: 2.1.5

dav: 1.4.7

external: 3.0.3

federatedfilesharing: 1.3.1

federation: 1.3.0

files: 1.8.0

files_frommail: 0.1.0

files_markdown: 2.0.4

files_pdfviewer: 1.2.1

files_rightclick: 0.8.4

files_sharing: 1.5.0

files_texteditor: 2.5.1

files_trashbin: 1.3.0

files_versions: 1.6.0

files_videoplayer: 1.2.0

gallery: 18.0.0

groupfolders: 1.2.0

issuetemplate: 0.3.0

logreader: 2.0.0

lookup_server_connector: 1.1.0

mail: 0.8.1

nextcloud_announcements: 1.2.0

notifications: 2.1.2

oauth2: 1.1.1

onlyoffice: 1.3.0

password_policy: 1.3.0

provisioning_api: 1.3.0

serverinfo: 1.3.0

sharebymail: 1.3.0

systemtags: 1.3.0

theming: 1.4.5

twofactor_backupcodes: 1.2.3

updatenotification: 1.3.0

user_sql: 3.1.0

workflowengine: 1.3.0
Disabled:

encryption

files_external

firstrunwizard

survey_client

user_external

user_ldap

"dbtype": "mysql",
"version": "13.0.4.0",
"mysql.utf8mb4": true,
"auth.bruteforce.protection.enabled": true,
"blacklisted_files": [
".htaccess",
"Thumbs.db",
"thumbs.db"
],
"cron_log": true,
"enable_previews": true,
"enabledPreviewProviders": [
"OC\Preview\PNG",
"OC\Preview\JPEG",
"OC\Preview\GIF",
"OC\Preview\BMP",
"OC\Preview\XBitmap",
"OC\Preview\Movie",
"OC\Preview\PDF",
"OC\Preview\MP3",
"OC\Preview\TXT",
"OC\Preview\MarkDown"
],
"filesystem_check_changes": 0,
"filelocking.enabled": "true",
"htaccess.RewriteBase": "/",
"integrity.check.disabled": false,
"knowledgebaseenabled": false,
"logtimezone": "Europe/Berlin",
"log_rotate_size": 104857600,
"memcache.local": "\OC\Memcache\APCu",
"memcache.locking": "\OC\Memcache\Redis",
"preview_max_x": 1024,
"preview_max_y": 768,
"preview_max_scale_factor": 1,
"redis": {
"host": "REMOVED SENSITIVE VALUE",
"port": 0,
"timeout": 0
},
"quota_include_external_storage": false,
"share_folder": "/Shares",
"skeletondirectory": "",
"trashbin_retention_obligation": "auto, 7",
"0": {
"verify_peer_off": true
}
}

**Are you using encryption:** no

**Comment by rollanders** [comment]
In my vcf there are names with åäö.

**Comment by brunt82** [comment]
And could you reproduce it with a vcf without such special characters?

**Comment by rollanders** [comment]
I cannot test it as the errors remain active all the time. Even after deactivating the Contacts app. 
Roland 

    Den onsdag, 20 juni 2018 13:48 skrev brunt82 <notifications@github.com>:
 

 And could you reproduce it with a vcf without such special characters?—

**Comment by rollanders** [comment]
This is what it looks like since 2 days ago. Every second a new error. 

![image](https://user-images.githubusercontent.com/36486009/41664992-3c51d1f4-74a7-11e8-9ab3-f2eb33f80f8f.png)

**Comment by rollanders** [comment]
You can try it yourself. Add one contact. Try adding one contact with odd letter like é or similar. The error was confirmed in another installation importing this vcf-file. 
 

 

    Den onsdag, 20 juni 2018 13:48 skrev brunt82 <notifications@github.com>:
 

 And could you reproduce it with a vcf without such special characters?—

**Comment by skjnldsv** [comment]
Closing as this is the proper behaviour.
Vcard parsing fails -> not compatible or malformed.

For better detail sont he reason of failure: https://github.com/nextcloud/contacts/issues/990
