### ISSUE TITLE
Download action in share link header split in two

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#9933]
In the header of sharing, on the top right there’s the download actions:
![screenshot from 2018-06-20 13-51-10](https://user-images.githubusercontent.com/925062/41656659-097ae808-7491-11e8-838b-a07d3daa1ad4.png)

Now the design for this (and as it worked before) is:
- Both text and 3-dot menu toggle are _one_ element. The text is merely a label for the icon as the actions are all "related" to download (and Download shows in the menu).
- The text "Download" is not displayed on mobile to save space for the title of the file, only the 3-dot-menu remains.

As it currently is:
- It’s split into "header-primary-action" and "header-secondary-action" which is confusing.
- The "Download" text does not vanish on mobile.

Now we could do the following to mix the approaches:
- On mobile, only have the 3-dot icon and all actions in the 3-dot menu (primary action first) like in the intended design
- On bigger sizes, having the primary action outside of the menu (like in the current way)
- To make it less confusing, on desktop we need to make obvious that there’s a primary button, so we should probably add a white border (a la button style) around the text.

What do you think @juliushaertl @skjnldsv @nextcloud/designers?

**Comment by skjnldsv** [comment]
Is this causing issues actually? Or is it just a nitpick to improve the design?

**Comment by juliushaertl** [comment]
> On mobile, only have the 3-dot icon and all actions in the 3-dot menu (primary action first) like in the intended design

:+1: 

> To make it less confusing, on desktop we need to make obvious that there’s a primary button, so we should probably add a white border (a la button style) around the text.

That sounds like a good approach. @nextcloud/designers 

![image](https://user-images.githubusercontent.com/3404133/41986504-a0158fc0-7a36-11e8-9850-38df1004d29a.png)

**Comment by skjnldsv** [comment]
Ah yes, I did not understand the issue like that!
I'm all in as well :)

**Comment by jancborchardt** [comment]
@juliushaertl yep, like that! :) But on bigger widths, the "Download" action then does not need to be in the 3-dot menu too when it’s already shown outside of it. Otherwise, want to open a pull request for it?

**Comment by MorrisJobke** [comment]
@jancborchardt @skjnldsv Moved to 15

**Comment by skjnldsv** [comment]
@MorrisJobke no, it's in #10838
