### ISSUE TITLE
(federation file sharing) cannot share file to user with @ in username

### ISSUE THREAD

**Issue by p5n** [nextcloud/server#9935]
### Steps to reproduce
1. Set up 2 nextcloud instances
2. Use IMAP external authentication with IMAP server that uses user@domain usernames
3. Try to share file to user@domain@cloud.domain

### Expected behaviour
File shared

### Actual behaviour
Nothing happened: file looks shared, but another instance does not get it. However it works for other nextcloud instances that does not use IMAP external auth.

### Server configuration

**Operating system**:
ArchLinux

**Web server:**
nginx and apache

**Database:**
mariadb

**PHP version:**
7.2.1

**Nextcloud version:** (see Nextcloud admin page)
13.0.4

**Comment by MorrisJobke** [comment]
cc @schiessle @nextcloud/sharing

**Comment by p5n** [comment]
This strange but after some time I received notification and was able to accept file. I am closing it now and continue testing
