### ISSUE TITLE
Deprecate scss variables in favour of css

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#9940]
Following #9723 

- [x] Stop importing the scss variable style on every compilation
- [x] Throw warning at the user/dev [?]
- [x] Remove runtime scss compilation in favour of buildtime compilation

**Comment by MorrisJobke** [comment]
This one didn't made it to 15 - let's move it to 16.

**Comment by MorrisJobke** [comment]
Let's move it to 17.

**Comment by MorrisJobke** [comment]
Will happen when IE11 is not supported anymore - ref #20855 - planned for 22. So adding it there.

**Comment by skjnldsv** [comment]
Well, not really, we have a ponyfill for ie11.
But it also most likely won't happen for 21, so good coincidence! :stuck_out_tongue_closed_eyes:

**Comment by Pytal** [comment]
@skjnldsv I don't think there's a CSS4 should we update title to CSS3?

**Comment by skjnldsv** [comment]
Yes, it used to be called css4 :p

**Comment by ChristophWurst** [comment]
@skjnldsv I would like to push forward with this. Can we declare the scss stuff as deprecated for 22 since we droped IE11? This still gives everyone three years of migration period in theory. So I would like to see this rather sooner than later :)

**Comment by skjnldsv** [comment]
Sure, we can do that for 23 and remove the variables.scss from the default import

https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/private/Template/SCSSCacher.php#L340
https://github.com/nextcloud/server/blob/9de329a4c2327767d86bd7f594b232eb56af0d01/autotest-js.sh#L31
https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/apps/accessibility/lib/Controller/AccessibilityController.php#L143

Feel free to push forward.
It will throw hard for all scss that uses that.
Then the following step is nuking:
1. the svg colour api
2. the on-the-fly scss compiler and have a dedicated npm/bash step to compile all scss?

**Comment by ChristophWurst** [comment]
@skjnldsv I'm not talking about taking action. I meant to say that we add a formal note about this transition to https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html saying that this mechanism is expected to go away

**Comment by skjnldsv** [comment]
Sure thing! Please do!

**Comment by skjnldsv** [comment]
Removed in 25

https://github.com/nextcloud/documentation/pull/9136
