### ISSUE TITLE
Searching and then pressing enter in apps management leads to blank page

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#9943]
1. Go to the apps management
2. Use the search in the top right, type something in
3. Press enter

You will be redirected to a blank page. Pressing enter should not do anything in this case, as we have no details for apps.

(In a new app management, we could for example open the sidebar with app details on pressing enter. cc @juliushaertl @skjnldsv)

**Comment by MorrisJobke** [comment]
Already reported to @skjnldsv - haven't you opened a fix for this already?

**Comment by skjnldsv** [comment]
No, I introduced the bug actually
