### ISSUE TITLE
nc13.0.4 admin delete user failed

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#9945]
Was trying to verify if #8402 was reproductive with nextcloud upgraded to 13.0.4

Step1: As admin, manually created user02 + password
Step2: Log one time that user, edit a files and remove a folder --> some activities.
Step3: As admin, delete user.
 
Expected behavior: 
- user02 should be deleted.

Actual behavior:
- user02 not deleted, a message appear on top middle of page with text "deleted test02 undo"
- user02 is gone, no more listed in page
- page refresh, user02 is back

redacted log without IP and username log:
```
{"reqId":"5vDTdLJt9Ab3ukAxzaFa","level":3,"time":"2018-06-21T11:12:33+00:00","remoteAddr":"...","user":"-","app":"PHP","method":"DELETE","url":"\/index.php\/settings\/users\/users\/test02","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) at \/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.87 Safari\/537.36","version":"13.0.4.0"}
{"reqId":"qQYWls7Dj8WpN7m9nm30","level":3,"time":"2018-06-21T11:12:40+00:00","remoteAddr":"...","user":"-","app":"PHP","method":"DELETE","url":"\/index.php\/settings\/users\/users\/test02","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) at \/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.87 Safari\/537.36","version":"13.0.4.0"}
{"reqId":"nrkmSeutJBd2aWcIDTlc","level":3,"time":"2018-06-21T11:12:42+00:00","remoteAddr":"...","user":"-","app":"PHP","method":"DELETE","url":"\/index.php\/settings\/users\/users\/test02","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) at \/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.87 Safari\/537.36","version":"13.0.4.0"}
{"reqId":"DxADJxOkSGXO52oXErFd","level":3,"time":"2018-06-21T11:12:44+00:00","remoteAddr":"...","user":"-","app":"PHP","method":"DELETE","url":"\/index.php\/settings\/users\/users\/test02","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) at \/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#105","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.87 Safari\/537.36","version":"13.0.4.0"}

```

**Comment by MorrisJobke** [comment]
> page refresh, user02 is back

Instead of refresh could you wait at least 30 seconds and then refresh. Is it still gone? Then it might be a missing event listener, because we wait AFAIK for 7-10 seconds (until the badge with the undo on top is hidden) until we trigger the actual delete. So it is basically a count down and only fires once 0 is reached. Usually there is a page unload event that we listen for and also trigger then.

cc @nextcloud/javascript

**Comment by stratege1401** [comment]
UPDATED: please, consider this fix. I notice the `Allowed memory size of 134217728 bytes exhausted ` but did not know it was a fatal error for php.

after modifying the /etc/php/7.0/apache2/php.ini to set `memory_limit` in concordance with my RAM and restarted apache2, i am now able to deseable/delete users without problems.
