### ISSUE TITLE
Warning when disabling maintenance mode using occ

### ISSUE THREAD

**Issue by simonspo** [nextcloud/server#9949]
When disabling maintenance mode using occ, the warning "Nextcloud is in maintenance mode - no apps have been loaded" is sent to stderr. However, trying to disable maintenance mode when it is not enabled, produces no warnings and no output to strerr.

### Steps to reproduce
1. Make sure maintenance mode is enabled: `sudo -u www-data php occ | grep 'in maintenance'`. Output: `Nextcloud is in maintenance mode - no apps have been loaded`
2. Disable maintenance mode: `sudo -u www-data php occ  maintenance:mode --off`, output: 
  ```
  Nextcloud is in maintenance mode - no apps have been loaded

  Maintenance mode disabled
  ```
3. Disable maintenance mode again: `sudo -u www-data php occ  maintenance:mode --off`, output `Maintenance mode disabled`

### Expected behaviour
When running  `occ  maintenance:mode --off`, I expect nextcloud be in maintenance mode, so:

2. should disable maintenance mode without warning,
3. should give a warning that maintenance mode is already disabled.

### Server configuration

**Operating system**:
Debian Stretch

**PHP version:**
PHP 7.0.27-0

**Nextcloud version:** (see Nextcloud admin page)
13.0.4

**Where did you install Nextcloud from:**
Official tar.bz2

**Comment by weeman1337** [comment]
I'll take this one!
