### ISSUE TITLE
All files get Password protected if user saves password on the browser

### ISSUE THREAD

**Issue by forgadex** [nextcloud/server#9950]
### Steps to reproduce
1. Login in nextcloud
2. Save password in the browser
3. Share a file with someoneelse 

### Expected behaviour
Be able to select another user other than yourself and not protect with password

### Actual behaviour
Selected user for sharing is always yourself and the file is protected with my own nextcloud password

### Browser
Google Chrome all versions

**Comment by MorrisJobke** [comment]
This is very likely the same cause as #9524

We fixed part of this with #7461 

On which version are you?

**Comment by forgadex** [comment]
We are running version 12. So the issue is solved.

Thanks

Rafael Freire
________________________________
De: Morris Jobke <notifications@github.com>
Enviado: quinta-feira, 21 de junho de 2018 13:30
Para: nextcloud/server
Cc: forgadex; Author
Assunto: Re: [nextcloud/server] All files get Password protected if user saves password on the browser (#9950)


This is very likely the same cause as #9524<https://github.com/nextcloud/server/issues/9524>

We fixed part of this with #7461<https://github.com/nextcloud/server/pull/7461>

On which version are you?
