### ISSUE TITLE
Show Full Path for Shared Item (External Share Screen)

### ISSUE THREAD

**Issue by jonathanpantall** [nextcloud/server#9952]
Hello,
We have a group of users that have a set / generic folder structure for projects they work on. When they share a sub-folder out to a client, they would like the ability to display the full folder path to the external user so they have context of what they're viewing. This would apply to folders or individual files being shared externally.

I'm not sure if this has been requested as an enhancement yet or not. I did some searching and didn't see it. This change would be specifically applied to external shares created.

Here is a screenshot that demonstrates this idea:

![nextcloud - enhancement - external share folder path](https://user-images.githubusercontent.com/25255725/41723434-a852869e-7530-11e8-8b76-b46de3cf5c72.png)

This may be useful for others who share files externally, who might appreciate giving extra context to what they're sharing.

Thanks ahead of time and we love your product!

**Comment by MorrisJobke** [comment]
This is nearly the opposite of #9789. I would not add it to the server directly, but do this in an app.

cc @nextcloud/sharing Opinion?

**Comment by rullzer** [comment]
Yes in some app please. i don't like exposing any more info than needed.

**Comment by MorrisJobke** [comment]
This should then be done by implementing an app. Thus I will close this ticket here in the server repo. If someone wants to tackle this problem, then we are happy to assist and answer questions.

We just don't want to track this inside the server repository, as it is not planned to be included right into the server itself.

**Comment by daveloper** [comment]
I want to contribute, My idea is to develop an application that can handle the situation and administrator should be able to configure overall behavior.
