### ISSUE TITLE
Search-as-you-type in apps management does not work anymore

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#9959]
Search in the apps management used to be search-as-you-type, now you need to press enter.

This should of course be back to search-as-you-type. ;)

cc @juliushaertl @skjnldsv

**Comment by MorrisJobke** [comment]
Ref #9954, #9943, #9767 and #9565

**Comment by skjnldsv** [comment]
The search is working for me on latest master :)
![kazam](https://user-images.githubusercontent.com/14975046/41762061-c5a7d860-75f9-11e8-9b86-0dadfdd1d802.gif)

**Comment by arnowelzel** [comment]
Hmm - but this works for me in the latest stable 13.0.4 as well.

**Comment by skjnldsv** [comment]
@arnowelzel this is about latest nextcloud 14 ;)

**Comment by juliushaertl** [comment]
@skjnldsv If I got @jancborchardt correct, the issue is about searching as you type, like in hit a letter key and the filter is applied. (without hitting enter)

**Comment by skjnldsv** [comment]
@juliushaertl that's what I did :)

**Comment by juliushaertl** [comment]
Ah sorry, i was thinking that it wasn't working from your screen recording, but it is just the debounce delay. @jancborchardt Should already work fine then.

**Comment by skjnldsv** [comment]
We could lower the debounce if that's necessary though
