### ISSUE TITLE
RC 10 Share File Link by email missing send button 

### ISSUE THREAD

**Issue by zeugmatis** [nextcloud/server#996]
### Steps to reproduce
1. Click "Share Link" checkbox in Share File dialogue 
2. Enter email address in the field, "Email Link to Person" 
3. Press Enter or click "Send" button / icon next to the field

### Expected behaviour
Share Link should be sent to email provided. 

### Actual behaviour
There is no button visible (see attached image).  

Pressing "Enter" key, the page reloads and no email is sent.  

If you hover the mouse directly to the right side of the field, the mouse pointer changes - you can then click and it works.  The button or icon is not visible, however - so regular users get confused: 

<img width="326" alt="screen shot 2016-08-20 at 1 42 18 pm" src="https://cloud.githubusercontent.com/assets/2687584/17834058/5344e062-66e5-11e6-80a2-eb00b9a19189.png">

I purged cache in Chrome as well no different.  It isn't really throwing any errors, it's just that any button or icon is not visible to the right of the email address field; regular users don't know what to do.  For now, we are telling them to just "hover your mouse to the right of the field and click when the pointer changes" - but I think there was an envelope icon or send button there in previous versions, that they would intuitively click.  

### Server configuration
**Operating system**: Debian Jessie, vanilla everything from packages

**Nextcloud version:** RC 10

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from ownCloud 9.1

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/prereleases/nextcloud-10.0RC1.tar.bz2

### Client configuration
**Browser:** FF nightly and Chrome

**Operating system:**OSX El Capitan

**Comment by rullzer** [comment]
Thanks for testing!

A fix is in #1000

**Comment by zeugmatis** [comment]
Perfect thanks much!  :-)
