### ISSUE TITLE
Calendar-app extension for a year-view

### ISSUE THREAD

**Issue by Titango2083** [nextcloud/server#9963]
Is the nextcloud-calendar planned to get a year-view? That would be awesome :)

**Comment by MorrisJobke** [comment]
Please report this in the calendar app: https://github.com/nextcloud/calendar/issues

Thankss

**Comment by sunjam** [comment]
[This Nextcloud calendar issue 159 for a year view seems related.](https://github.com/nextcloud/calendar/issues/159)
