### ISSUE TITLE
caldav drops still active tasks

### ISSUE THREAD

**Issue by charlemagnelasse** [nextcloud/server#9971]
I have nextcloud 13.0.4 and suddenly some tasks disappeared from caldav. They were all tasks which started on 2018-03-08, were not marked as finished and had no due to date.

**Comment by charlemagnelasse** [comment]
The 'sync only newer than" setting in akonadi is set to 99 years

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by georgehrke** [comment]
@charlemagnelasse I strongly suspect this to be a client issue. The Nextcloud calDAV server has no routine to cleanup old tasks, that's the clients task. So unless we get a proper DELETE command, Nextcloud doesn't delete anything.

Did you check if the tasks are still there in the database? Can you see them in the Nextcloud tasks app in the browser? 

Unless you are able to provide detailed reproduction steps, there is not much we can do here.
