### ISSUE TITLE
User management: display name and password field prefilled

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#9973]
When creating a new user, the display name and password fields are prefilled already with my own info:

![screenshot from 2018-06-23 18-11-05](https://user-images.githubusercontent.com/925062/41811490-e3ef994e-7710-11e8-9e53-034cb1732d19.png)

cc @nextcloud/designers @nextcloud/javascript

**Comment by skjnldsv** [comment]
Ah the good old prefill issue.
No browsers follow the actual w3c on this. This is really annoying! :(

**Comment by MorrisJobke** [comment]
Something for the autocomplete setting: https://developer.mozilla.org/de/docs/Web/HTML/Element/Input#attr-autocomplete but there are reports that this will not work reliable. :/

**Comment by skjnldsv** [comment]
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields

> If you are defining a user management page where a user can specify a new password for another person, and therefore you want to prevent autofilling of password fields, you can use autocomplete="new-password"; however, support for this value has not been implemented on Firefox.

**Comment by sunny75016** [comment]
Pentest-tools.com identified password autocompletion as a risk factor. It is easy to sort this problem by changing to autocomplete="off" at the two places in login.php. I do not understand why the so call security oriented developers choose to leave holes. Care to bother?.

**Comment by skjnldsv** [comment]
@sunny75016 no developer will want to help you if you take this tone and attitude.
Please have a look at our code of conduct here: https://nextcloud.com/code-of-conduct/

**Comment by kesselb** [comment]
> Please create a pull request with those two changes then.

That would be cool :+1: If not please create a new issue (you can skip most of the issue template for this kind) because this issue is about a different part (the user management which is available for administrators only).

**Comment by sunny75016** [comment]
Sorry you did not like my comment. Withdrawn.

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
