### ISSUE TITLE
App management navigation has padding on bottom

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#9974]
There is no settings area for settings, so we don’t need the padding on the bottom:
![screenshot from 2018-06-23 18-07-05](https://user-images.githubusercontent.com/925062/41811494-00ce8cfa-7711-11e8-8bfc-bd6d6a2f32e3.png)

@nextcloud/designers didn’t we have that in the CSS before?

**Comment by skjnldsv** [comment]
This should be automated with css. I guess we need to also update the positioning of the settings?

**Comment by jancborchardt** [comment]
> This should be automated with css.

Yep, as said I thought I remember this worked before. But then again, how can you modify a parent’s style based on if they have a child or not. We could require a class like `with-settings` (like `with-icon`) on the #app-navigation?

> I guess we need to also update the positioning of the settings?

What do you mean by that? There’s no settings here at all, so nothing to update?

**Comment by skjnldsv** [comment]
No, we need to stop using classes as toggles! :)
Css is powerful enough to detect the presence or not of an element. We should properly set things up so nothing is required ;)

**Comment by jancborchardt** [comment]
Haha – nevermind, we do already have this class and use it in personal settings ;) it’s `without-app-settings`. I’ll use that.

> Css is powerful enough to detect the presence or not of an element. We should properly set things up so nothing is required ;)

Currently you can not modify a parent based on a child using CSS. :) See [caniuse :has() CSS relational pseudo-class](https://caniuse.com/#feat=css-has)

**Comment by jancborchardt** [comment]
Ok, this apparently has to be done by someone who knows Vue, as I have no idea where to insert the class or the logic for it.

Seems either settings/src/components/appNavigation.vue or settings/src/views/Apps.vue

**Comment by skjnldsv** [comment]
> Currently you can not modify a parent based on a child using CSS. :) See caniuse :has() CSS relational pseudo-class

There are other ways to do that than use a padding on the parent

**Comment by jancborchardt** [comment]
I know, we can use fancy ways for lots of things – but I can't see how to use them short of rewriting our HTML. Which is not a proper fix in this case where we simply need to add a class we already use.

So if there are other ways we can do this for Nc 14, let me know. :) Otherwise, @juliushaertl @skjnldsv can you educate me where/how I would have to add the class in the Vue template?

**Comment by skjnldsv** [comment]
Here you go @jancborchardt https://github.com/nextcloud/server/pull/9977
