### ISSUE TITLE
Web page not displayed properly , Nginx + fpm , and they are located on different servers

### ISSUE THREAD

**Issue by foxinstone** [nextcloud/server#9975]
I have successfully installed NC13 on my ubuntu16.04 server, Every thing looks good, And I feel NC is an amazing software.
But there’s only one problem, when i use Nginx & PHP7.0-FPM， and they are located on different servers ，the web interface is wrong (Please see the screenshot, i know, it’s not configured, just example), Why is this?
But if i direct access the apache server， every thing is ok, i can finished the config by web page.
The funny thing is ,when i use Nginx & PHP7.0-FPM, The APP on android is working properly. even the web interface display is wrong.
Also,when i use simple nginx reverse proxy (not through FPM) , the web page is ok,but, The APP on android can not backup the contacts list(Other functions are normal).
You know, nginx+fpm (or nginx + php standard), and they are located on a different server models is of great significance. This model can be used to implement Intranet through…
Please help me make Web page display properly(use FPM), or make Android APP backup contacts properly(not use FPM).

![error1](https://user-images.githubusercontent.com/35874666/41817664-2fe87944-77d2-11e8-888b-e1521ce2e5cd.JPG)

**Comment by foxinstone** [comment]
Thanks for your reply.
But i think my situation is quite different. if I strictly according to the official document (use FPM), the web page not displayed properly(But Android APP is OK) .But, if i use this config:

   location / {
      proxy_set_header Host $Host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass http://192.168.1.2/;   #Point the apache server, Nginx server's ip=192.168.1.1
   }

The web page will be ok, At this point, just Android APP cannot back up contacts, other functions are normal. So I think my nginx server should not be a problem.


I've been tested, when nginx and Apache on one server, everything is functioning correctly. So the point is, nginx and Apache on a different server, you need to pay attention to what?

For me, It is not necessary to use the FPM, direct reverse proxy is acceptable because the vast majority of functions are normal, I just don't know why, can't back up the contacts on the APP ( "you don't permission......")?

**Comment by MorrisJobke** [comment]
Web server and php need to run on the same server. So I will close this as an Setup issue.
