### ISSUE TITLE
Login as deactivated user shows an error

### ISSUE THREAD

**Issue by RailsViceRoads** [nextcloud/server#9978]
### Steps to reproduce
1. add an user account
2. deactivate this user
3. try login for this user on web interface

### Expected behaviour
* The same behaviour as login with wrong user name **or**
* the same behaviour as login with wrong password. 

### Actual behaviour
* Login with wrong password will work as expected.
* Login with right password will show an error "user disabled". No login fields displayed. Page reload in web-browser does also not display login screen.

I suspect for privacy reasons login for an deactivated user should work as login for an non existent user. 

### Server configuration

**Nextcloud version:** 13.0.4.0

**Comment by RailsViceRoads** [comment]
Hi Marius, yes this will work. But I think it will be more user friendly to get something like this

![grafik](https://user-images.githubusercontent.com/36618192/41862985-bb850b06-78a5-11e8-99a0-402a6050f6ff.png)

because on the error-page is no navigation item (like a button) to get back to login the page. 

![grafik](https://user-images.githubusercontent.com/36618192/41863061-f9530262-78a5-11e8-96b1-b15ec7a00993.png)

Also I think it is not an "error" if a deactivated user tries an login. But you are right. This is not a bug. :)
Should I close this issue now?

**Comment by MorrisJobke** [comment]
> Also I think it is not an "error" if a deactivated user tries an login. But you are right. This is not a bug. :)
> Should I close this issue now?

Still something to polish ;)
