### ISSUE TITLE
Own Theme, Background etc. for IOS, Android

### ISSUE THREAD

**Issue by hume1991** [nextcloud/server#9983]
Hello, 

I have already reported a problem see: https://github.com/nextcloud/server/issues/9865 .
I created my own theme (defaults.php, server.css etc.) 

I would like to use this as it is possible with the theming app, how is this possible if you have your own theme? It's not about a complete branding!

Best regards 

Christian Huml

**Comment by MariusBluem** [comment]
So you want to use the theming-app (set colors, logo, ...) beside the old-theming folder where you have customized defaults.php and CSS-files?

**Comment by MorrisJobke** [comment]
> I want the colors to be applied the same way as in the theming app.

Then use the theming app. We build everything into the theming app. The plan is to remove themes itself completely, because they cause more issues than they solve. Also theming and themes can be used in parallel in the latest 13 release.

For custom CSS use the theming_customcss app.

**Comment by hume1991** [comment]
Hello @MorrisJobke,

There are some things I do not like about the Theming app. When using the Theming App, for example, the link to the same page is displayed (Footer). The adjustments themselves are very little in the Theming App. There are restrictions (Theming App).

Best regards

Christian Huml

**Comment by MorrisJobke** [comment]
> The adjustments themselves are very little in the Theming App. There are restrictions (Theming App).

This is for some reason limited, because it broke so many instances in the past.



> the link to the same page is displayed (Footer).

What do you mean? If there is a bug please report it.

**Comment by MorrisJobke** [comment]
> This is for some reason limited, because it broke so many instances in the past.

The idea of the theming app is to give the possibility to change the rough look, but not allow anymore to change the whole UI, because it causes more trouble than what it actually solve.

**Comment by hume1991** [comment]
Hello @MorrisJobke,

Without Theming App: https://cloud.geonativ-energie.de/index.php/s/NK3mFZtYHdzqbpa
with Theming App is shown as a link (New window back to homepage).

**Comment by hume1991** [comment]
@MorrisJobke 

Our footer without theming app: www.cloud.geonativ-energie.de (Without link).
Demo with Link: https://demo.sieg-net.ch/index.php/login

**Comment by hume1991** [comment]
Problem solved.

Best regards

Christian Huml

**Comment by seblu** [comment]
How did you solved it? By enabling the app or by another tricks in the theme files?
