### ISSUE TITLE
Lost passphrase

### ISSUE THREAD

**Issue by hume1991** [nextcloud/server#9988]
Hello, 

I lost the 12-word how can I recover it anyway (is an administrator account).

Best regards

Christian Huml

**Comment by MorrisJobke** [comment]
This is an issue within the twofactor_totp app. Thus please report it to the maintainer of that app in its repository: https://github.com/nextcloud/twofactor_totp

**Comment by hume1991** [comment]
Hello @MorrisJobke,

it is default encryption module (App).

Best regards 

Christian Huml

**Comment by MorrisJobke** [comment]
I guess then there is very little chance to recover. cc @schiessle @tobiasKaminsky @rullzer

**Comment by hume1991** [comment]
Have created new admin account and deleted old.

Best regards

Christian Huml

**Comment by rhondahz70** [comment]
rhondahz70@gmail.com
