### ISSUE TITLE
New folders created by other users are automatically selected although outside selection.

### ISSUE THREAD

**Issue by TomCan** [nextcloud/server#9990]
### Steps to reproduce
0. Considder following folder structure
Clients
- A
  - Aaron
- B
  - Brian

1. In the client of User 1, select to sync only the folder **Clients > A > Aaron**.
2. With User 2, create the folder **Clients > A > Amelia**, and **Clients > B > Brenda** and force a sync by placing some files in it.

### Expected behaviour
The Amelia folder **is not** synced with User 1
The Brenda folder **is not** synced with User 1

### Actual behaviour
The Amelia folder **is** synced with User 1
The Brenda folder is not synced with User 1

### Server configuration

**Operating system**: debian 9

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.1

**Nextcloud version:** 13.0.3

**Where did you install Nextcloud from:** downloaded from Nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, SMB

**Comment by MorrisJobke** [comment]
This is an issue within the client. Thus please report it to the maintainer of that app in its repository: https://github.com/nextcloud/client

Beside that this is usually the wanted behavior. The selective sync is a blacklist of existing files (you unselect what NOT to sync). Thus it works as wanted. It is not a whitelist to sync only those folders. If new folders appear the wanted behavior is to sync them by default.
