### ISSUE TITLE
Controls bar background missing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#9993]
The controls bar in Files doesn’t have a background anymore (used to be white with 90 or 95% opacity):
![screenshot from 2018-06-25 19-02-11](https://user-images.githubusercontent.com/925062/41864472-6e4c0d1c-78aa-11e8-8c4d-e9d33df710ab.png)

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by violoncelloch** [comment]
also on right scroll in user list (navigation bar should be sticky horizontally as well)

![grafik](https://user-images.githubusercontent.com/22591354/41992913-1da79088-7a4a-11e8-9908-870219d65d71.png)

**Comment by MorrisJobke** [comment]
> also, guide me if I should create a separate issue for this)

Separate issue, which is fixed in 14.
